### ISSUE TITLE
New install using repository on network share never starts initial sync

### ISSUE THREAD

**Issue by mmccarn** [syncthing/syncthing#2651] opened 2016-01-03 18:59 UTC
System A (windows 7) is sharing a folder ("Backup") over the network from a Mac running Yosemite.  The folder contains 178 zip files, most of which are 2GB (this folder is the backup target for another process). The share is setup as 'Folder Master'

System B (windows 10) is connected to System A, sharing both "Backup" and "default"

Changes made to default are synchronized OK.

Nothing done on the Mac ever generates any sync activity in Backup (the existing files are not synced, and test files created in that folder are not synced).  Files created in 'Backup' on System B generate the ren 'Override Changes' button on System A.

I've tried multiple computers at the originating end, and I've tried both mapped drives and UNC syntax.

Q: Should my configuration work, or do I need to install Syncthing directly onto the Mac (or get the source files off of the Mac some other way)?

Thanks.

**Comment by calmh** [comment] 2016-01-03 19:01
Screenshots from both sides, showing the Backup folder expanded?

**Comment by mmccarn** [comment] 2016-01-03 19:13
System A:
![system_a_screenshot](https://cloud.githubusercontent.com/assets/2945678/12080280/f6081138-b223-11e5-8dab-9f71e4a62150.png)

System B:
![system_b_screenshot](https://cloud.githubusercontent.com/assets/2945678/12080286/0811ba78-b224-11e5-8b5f-818aa3299698.png)

**Comment by calmh** [comment] 2016-01-03 19:16
You system A doesn't see any files there. Either it doesn't have permission to see the files, or something else funky is happening. But you can experiment quicker by looking at the "local state" line on system A, as it should represent the full contents of that folder.

**Comment by mmccarn** [comment] 2016-01-03 19:18
Thanks; I'll take a look at the permissions.

**Comment by mmccarn** [comment] 2016-01-03 21:19
I've done everything I can think of with no change in the observed behavior.

I have verified that syncthing can create new folders in the network share.

I have verified that I can create and edit .stignore in the non-syncing folder from within the syncthing gui, then verified that all files in the folder have the same ownership and access rights as .stignore.

I have re-created the folder from the syncthing gui, then moved the files I want to sync into the newly created folder.

I have recreated the shared folder using a mapped network drive, and have run syncthing from a CMD prompt to eliminate possible user vs service access rights issues.

No matter what I do, 'Local State' remains '0 items, ~0 B'

**Comment by calmh** [comment] 2016-01-03 21:36
Okay, from a CMD prompt:

```
SET STTRACE=scanner
syncthing
```

Post that. It should tell us what it sees about the folder in question.

**Comment by mmccarn** [comment] 2016-01-03 21:40
It certainly seems to be saying that it can't see the path...

```
[7RTWG] 2016/01/03 16:37:42.119285 walk.go:214: DEBUG: error: \\?\K:\Kerio_Backup &{Kerio_Backup {16 {229001856 30492264} {1619067264 30492266} {3399132672 3049 2268} 0 0} {0 0} \\?\K:\Kerio_Backup 0 0 0} Readdir \\?\K:\Kerio_Backup: The system cannot find the path specified.
```

**Comment by mmccarn** [comment] 2016-01-03 22:12
... yet, if I:
* remove the 'folder master' property from the repo on System A
* add a file ("syncthing.exe") to the repo on System B

The file is properly synced from system B -> System A, the the folder properties are updated to show 'Global State' and 'Local State' with '1 items, ~14.0 MiB'

I'm pretty sure my issue is related to my specific configuration.  I suggest that this issue be closed as user-specific or user-error since I won't have another chance to work on it for 2 - 4 weeks.

**Comment by AudriusButkevicius** [comment] 2016-01-03 22:13
I think it might be due to the fact that one side is a network mount.

**Comment by mmccarn** [comment] 2016-01-03 22:15
Yes, I agree.

Also, I'm certain I could solve the problem by installing syncthing directly on the Apple server -- but it's been a bit fragile lately, so I don't want to install any new software.

**Comment by wweich** [comment] 2016-01-03 22:27
I use syncthing to sync a network mount at work (SyncTrayzor) and it works without a problem. Even the built in inotify of SyncTrayzor works.

Are you sure syncthing runs exactly as the logged in user? No "Run as Admin" Console or something like that? Does `pushd K:\Kerio_Backup` inside the console work?

**Comment by mmccarn** [comment] 2016-01-03 22:32
[noob question]
How do I execute a command 'inside the console'?

**Comment by wweich** [comment] 2016-01-03 22:43
console = CMD prompt ;)

**Comment by mmccarn** [comment] 2016-01-03 22:47
OK; then at the same elevated cmd prompt that I'm running syncthing in, 'PUSHD K:\Kerio_Backup' works as expected.

I find it confusing that from the GUI I can:
* create new folders in the same network share (eg "K:\TEST")
* create/edit/delete .stignore

... and files added to the remote repo are successfully synced to my main repo (if I deselect 'Folder Master')

**Comment by calmh** [comment] 2016-01-04 07:55
It's odd that a readdir fails with that error. Some symlink or junction or something involved?

**Comment by AudriusButkevicius** [comment] 2016-01-04 08:35
Or a deduplicated drive?

**Comment by mmccarn** [comment] 2016-01-04 11:29
The network share is hosted on a Mac running os x 10.10 (Yosemite)

**Comment by calmh** [comment] 2016-01-23 05:09
This seems awfully system specific (especially since literally no one else has reported this behavior). I'm not sure where to go with this without a reproduction, preferably one not requiring multiple "exotic" operating systems in a sharing setup... I'm going to close this as I think it's a weird OS interaction and also not something we'll ever be able to get to the bottom of, but I'll gladly reopen if someone can show me otherwise.

**Closed by calmh** 2016-01-23 05:09 UTC
