### ISSUE TITLE
Respect the file structure

### ISSUE THREAD

**Issue by Jacques-z** [syncthing/syncthing#9272] opened 2023-12-10 09:18 UTC
I found syncthing putting things like `index.db` or `log`s in the config folder.

I'm not an expert about this, but I feel this inappropriate.
As different folders are for different purposes and meanings, they don't seem to be belong to this place.
I guess they are supposed to be stored in somewhere like `.local/share` or `.cache`? 
At least not in `.config`.
BTW, those `pem`s may also be better stored somewhere else?

Put files in where they meant to be could **let users find what they want more quickly and more accurate, avoiding lots of search on net or in docs**.

Could you please adapt syncthing to follow convention of Unix?

---
Below this line describe I the reason I issued this.
**WARNING**: tedious and not much relevant, just for background info.

I really love syncthing so that I made some experiments, one of them caused something harmless but annoying.

I had one folder `X` shared by two devices, one phone who uses syncthing-fork, the other, pad who uses `syncthing` through termux.
I deleted the folder from the shared folders list on pad, then used phone to ask for share again, and accepted on the pad immediately. 
However, instead of an `up to date`, what I got was something like `out of sync`.
The `global state` contains twice the actual files, and when I click `items out of sync`, it was empty with only page numbers.
Then I tried a few times deleting or moving destination, now global state is 6 times the actual size, while local state 4 times it.

Anyway, wherever syncthing got such misunderstand, I thought I could simply remove relevant files to solve the problem.
But I failed.
I don't know which files are save to remove and which are not, I even don't know where those relevant files are.
I've looked up using `find ~ -name "*sync*"`(searching for st would lead to too much results) but found nothing I wanted.
Also I looked up `.cache` and `.local{,/share}`.

Actually, despite the error msg, syncthing is working well.
But I just feel so uneasy about that.
So I decided to open this issue.

I know I shouldn't put two problems in one issue, but I don't mean to issue this problem, as it's only for background info.
As for the error msg, it's ok. 
I surely can live with it.

**Comment by tomasz1986** [comment] 2023-12-10 09:40
Duplicate of https://github.com/syncthing/syncthing/issues/9178 and https://github.com/syncthing/syncthing/issues/8102.

**Closed by tomasz1986** 2023-12-10 09:40 UTC
Labels: enhancement, needs-triage

**Comment by Jacques-z** [comment] 2023-12-10 10:08
yes, I just had my syncthing up-to-date and it's now v1.27.0 android (64-bit ARM) "Gold Grasshopper".
And I saw paths in the about window, wow.

Though I don't understand what you mean by "a completely clean state", after a restart it no longer produced this bug.
So it should be reading info from those ldb files, I guess.

And thx for the links. Enhanced me a lot

**Comment by tomasz1986** [comment] 2023-12-10 10:16
> Though I don't understand what you mean by "a completely clean state"

This basically means that it needs to be a clean installation. Otherwise, if you are upgrading and the previous versions of Syncthing were already using the old paths, then the new version will continue to use those as well. It is only when the old paths don't exist that the new ones are used.

**Comment by acolomb** [comment] 2023-12-10 14:01
> it's now v1.27.0 android

Android is a different story altogether. The app does not have access to any XDG paths, but lives in its own sandbox. What was said and linked concerned only Unix-like environments.

**Comment by Jacques-z** [comment] 2023-12-10 14:17
> Android is a different story altogether. The app does not have access to any XDG paths, but lives in its own sandbox. What was said and linked concerned only Unix-like environments.

Well, ok, interesting.

BTW, I have two users on PC, one uses Hyprland and the other uses plasma(x11).
The file hierarchy of the former is similar to the one I see on android, while the latter puts files in `.local/state`.
That makes sense
