### ISSUE TITLE
Variable placeholders not filled: {%device%} wants to share folder ...

### ISSUE THREAD

**Issue by justinormont** [syncthing/syncthing#6687] opened 2020-05-27 18:35 UTC
![image](https://user-images.githubusercontent.com/4080826/83058372-1ffe4d00-a00d-11ea-91be-337aa7828881.png)

Says: 
`{%device%} wants to share folder "{%folderlabel%}" ({%folder%}). Add new folder?`

The page looks correct otherwise; hence Angularjs is loaded.

Reloading the page fixes the issue.

This was mentioned four years ago:
https://github.com/syncthing/syncthing/issues/3162

### Does your log mention database corruption?

No `panic` in the logs.

### Include required information
Version:  v1.5.0, macOS (64 bit) "Fermium Flea"
OS: macOS 10.14.6
Browser: Chromium 82.0.4078.0 (Developer Build) (64-bit)

**Comment by AudriusButkevicius** [comment] 2020-05-27 18:43
I think this usually happens due to initialization error, which might be due to your non mainline build. 

Closing this as I am not convinced this is our bug. 

If you can reproduce it on a vanilla browser, start a thread on the forum with the steps for us to repro.

**Closed by AudriusButkevicius** 2020-05-27 18:43 UTC
Labels: bug, needs-triage

**Comment by justinormont** [comment] 2020-05-27 20:36
> I think this usually happens due to initialization error, which might be due to your non mainline build.
> 
> Closing this as I am not convinced this is our bug.
> 
> If you can reproduce it on a vanilla browser, start a thread on the forum with the steps for us to repro.

Yes, this seems like an initialization error.

Perhaps there are also stable releases of Chromium, though the developer builds seem to be the normal.

These are the normal/official Chromium builds:
https://www.chromium.org/getting-involved/download-chromium

**Comment by AudriusButkevicius** [comment] 2020-05-27 20:50
Are you sure its not some sort of plugin you have that causes this?

Effectively, we need a reproducer to be able to fix this.

**Comment by justinormont** [comment] 2020-05-27 22:54
Transient bugs certainly are difficult to fix. When refreshing the page, the issue went away. 

Too bad I didn't think to look in the JS console for an error. There may have been a JS error causing the rendering to not complete.

There's pretty minimal extensions installed: _(all w/ default settings)_
![image](https://user-images.githubusercontent.com/4080826/83079495-d0ca1380-a030-11ea-819f-2ea358cb5e3f.png)

I suspect it's not the extensions as the page normally renders correctly; except for this one time.

Refreshing the page a couple of dozen times, shows no repros. Also no repo w/ restarting using `Actions => Restart`, `Quit`, or `kill -9`.

**Comment by justinormont** [comment] 2020-07-11 00:42
@AudriusButkevicius : I hit the same placeholder issue today:
![image](https://user-images.githubusercontent.com/4080826/87212443-4f260080-c2d3-11ea-8b7d-88dd5f706393.png)

The rest of the fields below these announcements are correctly filled. Refreshing the page fixes the issue. 

Version: `v1.7.0, macOS (64 bit) "Fermium Flea"` _(bug was initially reported w/ `v0.5.0`)_
OS: `macOS 10.14.6`
Browser: `Version 86.0.4197.0 (Developer Build) (64-bit)`

I did notice a secondary issue. I was expecting the date to all match; the bottom one lists the current date/time. This is still true in the refreshed page.
