### ISSUE TITLE
Consider moving index location under ~/.cache/

### ISSUE THREAD

**Issue by desbma** [syncthing/syncthing#5359] opened 2018-12-09 23:14 UTC
Under Linux the DB Index is currently stored in `~/.config/syncthing/index-vVERSION.db`.

However the usual convention is that `~/.config` is for configuration files, not internal files with frequent changes which are rather put in `~/.cache`.

See https://standards.freedesktop.org/basedir-spec/basedir-spec-latest.html

A good way to discriminate between both, is to ask "does it make sense to backup theses files"?
* config.xml, keys, etc. => yes, should go in `~/.config`
* internal database => nope (will be rebuild if lost), should go in `~/.cache`

**Comment by imsodin** [comment] 2018-12-09 23:16
Duplicate of https://github.com/syncthing/syncthing/issues/4924

**Closed by imsodin** 2018-12-09 23:16 UTC
