### ISSUE TITLE
Folder Sync % and other stats appear to overflow when file(s) deleted during sync

### ISSUE THREAD

**Issue by Novox** [syncthing/syncthing#1200] opened 2015-01-07 14:40 UTC
What happened:
I was transfering a 2GB file in addition to other files.  90mb into it, I deleted it from the source.  The receiving host correctly kept receiving the remaining files, but the sync % was above 100% and the "Out of Sync" status was a negative number.

What did you expect to happen instead of what did happen, if it's not crazy obvious... crazy obvious :)

What operating system, operating system version and version of Syncthing you are running
Receiving: Windows server 2012 R2
Sending: Windows 8.1 Pro

Screenshot if the issue concerns something visible in the GUI
![capture](https://cloud.githubusercontent.com/assets/10436186/5647141/1ff39638-9651-11e4-98d7-e7b2a60259ce.PNG)

Console log entries, where possible and relevant
version 0.10.18

**Comment by AudriusButkevicius** [comment] 2015-01-07 14:55
Seems to be a duplicate of https://github.com/syncthing/syncthing/issues/679

**Closed by AudriusButkevicius** 2015-01-07 14:55 UTC
