### ISSUE TITLE
Can't connect to global discovery server: Client.Timeout exceeded while awaiting headers

### ISSUE THREAD

**Issue by fqqf** [syncthing/syncthing#8665] opened 2022-11-10 12:45 UTC
![image](https://user-images.githubusercontent.com/77983090/201093632-23669b13-e757-44aa-a9ee-d0af4cfb14c5.png)

**global@https://discovery-v4.syncthing.net/v2/: Post "https://discovery-v4.syncthing.net/v2/": context deadline exceeded (Client.Timeout exceeded while awaiting headers)**

- Syncthing ver: 1.22.0 (Linux)
- Browser: Firefox 105.0.2 (64-bit)
- OS: Fedora 37

**Comment by nekr0z** [comment] 2022-11-10 12:48
Duplicate of #8625

**Comment by fqqf** [comment] 2022-11-10 12:49
Thanks

**Closed by nekr0z** 2022-11-10 12:48 UTC
Labels: bug, needs-triage
