### ISSUE TITLE
With Windows Terminal syncthing is not hiding itself

### ISSUE THREAD

**Issue by Unc3nZureD** [syncthing/syncthing#8676] opened 2022-11-15 18:14 UTC
I'm using Windows 11 Build 22H2 22623.891, but it shouldn't be specific to this version.

I created a shortcut for Syncthing in the `shell:startup` directory (short for: `C:\Users\<username>\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Startup`) with the following target: `C:\Syncthing\syncthing.exe --no-console --no-browser`

The default "terminal" is NOT the old command prompt, but the new Windows Terminal, this one:
![image](https://user-images.githubusercontent.com/8837736/201994445-2f537170-dc8b-4a24-9031-cdd981981013.png)
---
![image](https://user-images.githubusercontent.com/8837736/201994493-f40dd131-bfb5-40ef-9354-cbd9cff806fc.png)

The problem is that --no-console is NOT hiding this terminal. I'd like to keep synching running in the background, but this way it's always kept in front :(

**Comment by tomasz1986** [comment] 2022-11-15 19:32
Duplicate of https://github.com/syncthing/syncthing/issues/8248. This is a known problem and the only workaround is to use the "legacy" console as default. The consensus was that this issue should be fixed in the Windows Terminal itself.

**Closed** 2022-11-15 19:47 UTC
Labels: bug, needs-triage
