### ISSUE TITLE
(android phone) Out of Sync folders eat CPU

### ISSUE THREAD

**Issue by lukash** [syncthing/syncthing#3851] opened 2016-12-31 16:15 UTC
Please see attached log.

The remote end (desktop PC with syncthing 0.14.16) on which the music folder is was paused, because the changes were too many and I'll have to copy the files over USB later.

The files in the photos folder were deleted on this phone some time ago, but now syncthing wanted to sync them to this phone from another one (phone2 from now on :)) instead of deleting them on phone2, I currently have clue why. I didn't want that so I removed the folder on phone2 and that should be the state in which the log was captured.

The point is, syncthing is eating CPU and battery and unless I'm missing something it makes no sense. When there is no connection to the remote, it should not loop over the files like this. It's pretty bad on desktops but even much worse on mobile devices.

### Version Information

    Syncthing Version: v0.14.16
    OS Version: Android 6.0.1
    Android App Version: 0.9.3
[syncthing_log.gz](https://github.com/syncthing/syncthing/files/679719/syncthing_log.gz)

**Comment by calmh** [comment] 2017-01-23 19:08
Sync is failing for several items. One of the causes for this has been fixed in later releases, which is good. But this can happen for many reasons, and then there are periodic retries. Retries eat CPU. The retry interval can be changed, and perhaps it would be useful for the Android app to do this (https://docs.syncthing.net/users/config.html#folder-element, `pullerSleepS`).

**Closed by calmh** 2017-01-23 19:08 UTC

**Comment by lukash** [comment] 2017-01-24 09:02
So the sleep is 0 seconds, imho not very clever, especially in case of permanent errors (requiring user intervention) which will essentially cause a busy loop with zero sleep. That is bad for all platforms, not just Android.

Did you do some action that would cause at least the sleep for Android to be adjusted on closing this issue?

**Comment by AudriusButkevicius** [comment] 2017-01-24 09:06
It's never 0, if it's 0, it uses the defaults:

https://github.com/syncthing/syncthing/blob/master/lib/model/rwfolder.go#L74

**Comment by calmh** [comment] 2017-01-24 09:13
> Did you do some action that would cause at least the sleep for Android to be adjusted on closing this issue?

No, that would need to be handled on the Android side, if it's desirable. That's a different repo and different team.

**Comment by lukash** [comment] 2017-01-24 09:36
> It's never 0, if it's 0, it uses the defaults

So that means 60 seconds? That would sound reasonable, but it should not eat the CPU that much. I don't remember the details and don't have the time to have another look at the log right now...

> No, that would need to be handled on the Android side, if it's desirable. That's a different repo and different team.

Well, if it's indeed 60 seconds and it still eats the CPU, then there is not much sense in increasing the value further... The problem must be somewhere else.
