### ISSUE TITLE
Always notify user on manual CPU-poking short-interval jobs

### ISSUE THREAD

**Issue by KeyWeeUsr** [syncthing/syncthing#6123] opened 2019-11-03 14:51 UTC
Please always stick a warning to the user's face in case the daemon checks for something **once in a minute** or in a similar interval. I had a problem with permissions on certain files due to stupid ``chmod -R 644 <folder>`` which borked the folder permissions (folder needs to be executable).

Once I did a couple of rescans an actual warning popped out with Syncthing not being to access a folder due to permissions error and that **it'll repeat the scanning each minute**. This message however was not displayed except for that one time, so I suspect some kind of bug, however it'd be nice to notify the user that Syncthing manually attempts to do something in such a short interval because it plays with CPU quite a bit and I noticed it only after inspecting why the fan is spinning.

Reproducible with already synced folder and executing these commands. Then just wait for System Monitor or ``top`` to show Syncthing poking the CPU each minute or so.

```shell
# normal usage
$ mkdir testfolder
$ stat --format '%a' testfolder
755

# trigger
$ sudo chmod -R 644 testfolder
$ ls -lah testfolder
ls: cannot access 'testfolder/.': Permission denied
ls: cannot access 'testfolder/..': Permission denied
total 0
d????????? ? ? ? ?            ? .
d????????? ? ? ? ?            ? ..
$ stat --format '%a' testfolder/
644
```
### Version Information

Syncthing Version: v1.3.0
OS Version: LinuxMint Tina 19.2 64-bit

**Comment by AudriusButkevicius** [comment] 2019-11-03 14:54
I disagree.

Repeated warnings about the same subject is just clutter. We'll have the other spectrum of people complaining that nothing is happening.

Cpu usage should not spike if we can't read the directory, as there would be nothing todo.

**Comment by KeyWeeUsr** [comment] 2019-11-03 15:35
Well the point it the warning was not there at all. When I tried to resync the whole folder (which can take a while for multiple hundreds of GBs) only then the warning appeared and only once per multiple resync attempts.

Currently CPU will spike once in a minute, however because a certain job is executed within a very small interval and the CPU spiked, the fan for such CPU will be almost in a constant trying to cool the CPU down which means more noise (audio) than a gui warning noise (way less annoying and may be dismissed unlike physical device's noise).

**Comment by AudriusButkevicius** [comment] 2019-11-03 15:42
Sure, but CPUs have fans for a reason, and software does retries for a reason (something failed, perhaps it was a transient error), I am not sure what you are unhappy about. The error is shown once every 10 or so attempts, so even if it's not immediately visible, it will be after some number of minutes.

**Comment by KeyWeeUsr** [comment] 2019-11-04 20:26
Yes, I understand your point. But, when the files sync the ordinary way, there is really small activity, the fan does not even start, nor the activity is visible as in this image:

![image](https://user-images.githubusercontent.com/8825439/68154657-4614b080-ff48-11e9-8390-d375cf38a6e1.png)(orange line on 30-20s)

For this particular case I had 3 folders with total of 11 files and each folder had 644 set recursively. This plot was the result. Ordinary syncing does not get above 10% or so with hundreds up to thousands of files in the queue, however when this was happening, syncthing process had 14-20% CPU (and I've seen even 25%+) usage for such small amount of files.

![image](https://user-images.githubusercontent.com/8825439/68154331-95a6ac80-ff47-11e9-81eb-7e9690c41397.png)

The warning (the same style as inodes warning) was displayed only once and since that I was not able to reproduce even showing the warning. The amount of "fails" i.e. 
is almost always present, however I had even 100+ files for multiple days in the "fails" section due to file having too long name and that was no issue for CPU unlike this folder permissions issue.

![image](https://user-images.githubusercontent.com/8825439/68151192-845aa180-ff41-11e9-996e-89b7b618a397.png)

Checked on ``Intel(R) Core(TM) i7-4500U CPU @ 1.80GHz``.

**Comment by AudriusButkevicius** [comment] 2019-11-04 21:30
I suspect whats happening is the CPU spiking to compare the temp file/existing file to what we want to achieve, the file maybe/maybe not gets downloaded, but then subsequently fails to land in the right place. The logs can probably explain where it fails exactly.

This loop has 10 or so retries with exponential backoff between every 10 or so attempts, so at some point this will happen less and less.

The Failed items is the expected warning in this case, I did not expect anything else.

As it stands we are discussing some form of symptom and not the cause, so it's not clear what needs fixing.

If you are technically capable enough, you could grab a CPU profile (explained how in the docs), and see what it's actually doing, and propose a PR optimising this or atleast explain what is causing this and what needs fixing so it's an actionable bug report.

However, on the basis that someone asked pretty much the opposite today (do stuff even if not connected, etc, etc - even if not directly related) in the forums (https://forum.syncthing.net/t/idea-offline-sync-with-local-files) I am going to close this until a more concrete analysis is done and it's known what exactly needs fixing.

**Closed by AudriusButkevicius** 2019-11-04 21:30 UTC
