### ISSUE TITLE
Decrypt versions folder

### ISSUE THREAD

**Issue by Ratio2** [syncthing/syncthing#8575] opened 2022-10-03 00:14 UTC

**Comment by AudriusButkevicius** [comment] 2022-10-03 00:16
What does this even mean?

**Comment by Ratio2** [comment] 2022-10-03 00:18
@AudriusButkevicius syncthing decrypt skip .stvertsions folder

**Comment by tomasz1986** [comment] 2022-10-03 05:38
Somewhat a duplicate of https://github.com/syncthing/syncthing/issues/7914? This one is more generic though, but the same problem of not decrypting `.stversions` was discussed in the other issue as well.

**Comment by imsodin** [comment] 2022-10-03 07:17
Yes, duplicate of https://github.com/syncthing/syncthing/issues/7914

**Closed by imsodin** 2022-10-03 07:17 UTC
Labels: enhancement, needs-triage
