### ISSUE TITLE
Out of sync page should mention what machine the conflict comes from

### ISSUE THREAD

**Issue by flz** [syncthing/syncthing#2476] opened 2015-11-15 19:43 UTC
I've got a cluster with about 40 machines and one has a file that's causing a conflict on my master (readonly=True) but I've got no way to figure out which without logging on each host and looking for the file myself.

**Comment by andrewufrank** [comment] 2015-11-20 11:33
i have the same problem (with 10 machines). the issue is usually a problem caused by changing a .syncignore file (and a new software inventing yet another way of naming backup files).
would it be solved if all machines had the same syncignore? would this be desirable - in my case, it would.
thank you for considering!

**Comment by Nutomic** [comment] 2016-03-02 21:46
Looks like a duplicate of #2327.

**Closed** 2016-03-02 22:02 UTC
Labels: easy, enhancement
