### ISSUE TITLE
Syncthing stops on Android Q beta 4

### ISSUE THREAD

**Issue by omgdz** [syncthing/syncthing#5812] opened 2019-06-24 11:33 UTC
Syncthing android release version and beta version both install on Android Q beta, but they crash with error "syncthing was terminated" "failed to create config file" and this:
--------- beginning of crash
--------- beginning of main
06-24 06:30:49.372 W/SyncthingNativeCode(23399): error: "/data/app/com.nutomic.syncthingandroid-AVo9Kc5JtogF6f-OtI9AFw==/lib/arm64/libsyncthing.so": executable's TLS segment is underaligned: alignment is 8, needs to be at least 64 for ARM64 Bionic

**Comment by imsodin** [comment] 2019-06-24 11:35
Wrong repository and duplicate of https://github.com/syncthing/syncthing-android/issues/1291

**Closed by imsodin** 2019-06-24 11:35 UTC

**Comment by omgdz** [comment] 2019-06-24 11:39
Thank you. (Danke?)
