### ISSUE TITLE
Cannot delete folder

### ISSUE THREAD

**Issue by maaksv** [syncthing/syncthing#1308] opened 2015-01-29 08:37 UTC
Hi i have
v0.10.21 and Windows Server 2003
i delete folder "1" or "test" (C:\test\1\archive.zip) from comp A
in comp B archive.zip deleted, but folders cannot deleted (C:\test\1\)

Web GUI: Folder "test" isn't making progress - check logs for possible root cause. Pausing puller for 1m0s.

Logs: delete: remove: file is busy by another process (but folder is empty)
or delete: remove: directory not empty

**Comment by AudriusButkevicius** [comment] 2015-01-29 10:00
well it seems that we cannot delete the file as the file is being opened by someone.
And because the file is still there, we cannot delete the directory.

**Comment by maaksv** [comment] 2015-01-29 13:37
yes, i try delete manually but i cant, folder busy by syncthing.exe ... if i kill syncthing.exe process then folder can deleted
and this is folders empty, file archive.zip can deleted without errors

**Comment by facastagnini** [comment] 2015-01-29 15:43
I just had this problem too.

I deleted a folder on computer A and computer B show the same error.

I manually deleted the folder on computer B and after a while the sync
resumed.

I fix this last night and this morning. Two different folders.

Computers are two Macintosh 64bits running macos 10.10.1, syncthing 0.10.21
over the lan

**Comment by AudriusButkevicius** [comment] 2015-01-29 16:05
Well it's not clear what is the exact error to me to understand where it's coming from.

**Comment by maaksv** [comment] 2015-01-30 00:40
ok, sorry for my english
1) on the computer B (C:\TEST\1\) there is a file Archive.zip
![screenshot_3](https://cloud.githubusercontent.com/assets/10754508/5969077/6f09839a-a862-11e4-9ef8-991f9c61799e.jpg)
![screenshot_1](https://cloud.githubusercontent.com/assets/10754508/5969057/40204c76-a862-11e4-9dee-519df45f95e1.jpg)
2)I delete the folder "1" on the computer A, but on the computer B folder "1" cant deleted (file Archive.zip deleted)
![screenshot_4](https://cloud.githubusercontent.com/assets/10754508/5969108/c4873a92-a862-11e4-869b-907300c2c30a.jpg)
with error: 9:32:31: Folder "TEST" isn't making progress - check logs for possible root cause. Pausing puller for 1m0s.
Log(translated from russian): INFO: Puller (folder "TEST", dir "1"): delete: remove C:\TEST\1: Process can't get access to the file as this file is occupied with other process.
3) i cannot delete folder "1" manually too. Folder "1" busy by Syncthing.exe ...
![screenshot_5](https://cloud.githubusercontent.com/assets/10754508/5969145/41fd2d24-a863-11e4-9012-643b2435f379.jpg)
folder "1" have next attributes:
![screenshot_6](https://cloud.githubusercontent.com/assets/10754508/5969190/f2040a9e-a863-11e4-8da6-4797336c1c79.jpg)
how to solve this ?
Thanks

**Comment by AudriusButkevicius** [comment] 2015-01-30 08:13
So I don't understand why syncthing is holding a handle on the file. Do you have more nodes which are perhaps issueing requests for the ile?

**Comment by maaksv** [comment] 2015-01-30 08:30
No, 
comp A (main) -> comp B
comp A (main) -> comp C
...
comp A (main) -> comp N
so, comp B synchronized only with comp A
upd.: on several computers (ex. comp D, comp E) folders deleted without errors
all computers have v0.10.21 and Windows Server 2003, all profiles have administrator privilegies

**Comment by maaksv** [comment] 2015-02-03 04:10
I collected the program from this source code, install this on comp A (main) and on comp B:
1) folders aren't occupied with other process
2) i can delete folders manually, but syncthing cannot delete folders automaticaly
logs: Log(translated from russian): INFO: Puller (folder "TEST", dir "1"): delete: remove C:\TEST\1: Process can't get access to the file as this file is occupied with other process.
But the folder isn't occupied with other process:
![screenshot_1](https://cloud.githubusercontent.com/assets/10754508/6014380/0215ddc8-aba6-11e4-8295-79f4bcb6996d.jpg)

**Comment by AudriusButkevicius** [comment] 2015-02-03 09:24
So I cannot reproduce the problem with my machine, which leads me to believe that it's some sort of misconfiguration/permissions issue in your end. Can you try running syncthing as an administrator?

**Comment by maaksv** [comment] 2015-02-04 07:41
im very sorry, earlier I told that all computers on Windows Server 2003.
there is a problem with computers on Windows XP.
Comp A (main) (Windows Server 2003) syncronization with 22 comps (Windows Server 2003) without errors. All work excellent (delete, remove, rename)
But i have 2 comps on Windows XP, they are have this problem with comp A (main), cannot delete folders.
I hope for your understanding

**Comment by maaksv** [comment] 2015-02-04 07:42
P.S. on windows XP users have adminictrator privilegies.

**Comment by AudriusButkevicius** [comment] 2015-02-04 10:24
Yeah, to be honest I don't know what to suggest anymore.

Is there an easy set of reproduction steps, so that I could try and reproduce it?

**Comment by doychi** [comment] 2015-02-14 11:25
I have had the same issue, which appears to be because the file is marked Read Only on a Windows 8.1 system.

**Comment by maaksv** [comment] 2015-02-16 00:05
it is seen a problem in privileges between different versions in hosts

**Comment by doychi** [comment] 2015-02-18 09:55
I am running the same version on both end points.  They are both set to automatic update so should always be within one version of each other, as they are both turned on regularly.

**Comment by AudriusButkevicius** [comment] 2015-02-18 10:01
I assume this has now fixed itself?
If not, reopen.

**Closed** 2015-02-18 10:00 UTC

**Comment by doychi** [comment] 2015-02-18 10:05
I ended up manually deleting the files on the read only side.  This has solved the problem for now.

**Comment by adi-dev** [comment] 2015-04-02 10:21
syncthing 0.10.30 still the same problem on XP, have to manually remove folders

**Comment by lovetox** [comment] 2015-04-02 17:32
have the same problem on 0.10.30 ,  windows 7 x64

**Comment by sreynen** [comment] 2015-06-01 12:31
Only collaborators can re-open issues on Github, which doesn't appear to include any of the people reporting this issue. I'm personally having the problem on two OSX machines. I created zip archives of several directories to reduce CPU load on scan, and deleted the old directories. The directories are still there on the other "Up to Date" machine, though all the files within have been deleted. So now I have to manually compare the two machines and delete the directories.

**Comment by AudriusButkevicius** [comment] 2015-06-01 12:49
Are there errors in the logs, or perhaps ignore patterns matching the folder?

This particular issue relates to Windows, and the write-protected issue has recently been fixed.

**Comment by kononenko-nikolay** [comment] 2015-08-08 07:04
Hi, I'm also watching this issue. the problem occurs on a PC with windows xp (32 bit). reproduced in 100% cases. If you connect this catalog to a different host (for windows7 or linux) is on them is not a problem, all nodes are removed and empty directories remain only on a PC with windows xp

version syncthing v0.11.18

**Comment by AudriusButkevicius** [comment] 2015-08-08 10:46
Sorry but XP is 14 years old and long dead hence I don't think this will get any attention.

**Comment by canton7** [comment] 2015-11-30 16:23
(FYI, looks like this is fixed by #2522 - thanks to @t-o-l-i-x)
