### ISSUE TITLE
Syncthing quits after or while update?

### ISSUE THREAD

**Issue by sisu4syncthing** [syncthing/syncthing#5877] opened 2019-07-19 21:37 UTC
Hi,

ok, this is the second time this happens, so I file a bug here.

I see that v1.2.1 rc3 has just rolled out and it was installed successfully on macOSX.

On **Win7 64Bit** machines, it seems, that something bad happens, because I have no syncthing.exe processes running anymore.

This is, what the log says:
```
[FNH3H] 2019/07/19 21:42:46.792272 INFO: Connected to device FOOBAR with a newer version (current "v1.2.1-rc.2" < remote "v1.2.1-rc.3"). Checking for upgrades.
[FNH3H] 2019/07/19 21:42:46.924285 INFO: Automatic upgrade (current "v1.2.1-rc.2" < latest "v1.2.1-rc.3")
[FNH3H] 2019/07/19 21:43:01.828910 WARNING: Automatically upgraded to version "v1.2.1-rc.3". Restarting in 1 minute.
[FNH3H] 2019/07/19 21:44:01.833657 INFO: Connection to FOOBAR at 192.168.168.77:20001-192.168.168.66:65102/tcp-server/TLS1.2-TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305 closed: Syncthing is being stopped
[FNH3H] 2019/07/19 21:44:02.123692 INFO: TCP listener ([::]:20001) shutting down
[FNH3H] 2019/07/19 21:44:02.713744 INFO: Connection to BARFOO at 192.168.168.77:20001-79.227.67.118:50392/tcp-server/TLS1.3-TLS_CHACHA20_POLY1305_SHA256 closed: Syncthing is being stopped
2019/07/19 21:44:11 Supervisor discover.cachingMux: discover.cachingMux: Service IPv6 local failed to terminate in a timely manner
2019/07/19 21:44:11 Supervisor local: local: Service multicastBeacon failed to terminate in a timely manner
[FNH3H] 2019/07/19 21:44:11.885731 INFO: Exiting

```

And this, after manually starting:
```
2019/07/19 23:38:21.650983 INFO: Automatic upgrade is always enabled for candidate releases.
[FNH3H] 2019/07/19 23:38:21.725493 INFO: syncthing v1.2.1-rc.3 "Fermium Flea" (go1.12.7 windows-amd64) teamcity@build.syncthing.net 2019-07-19 17:41:16 UTC

```

I'm starting syncthing this way via batch:
```
@start "Syncthing" /low syncthing.exe -no-console -no-browser -home="C:\syncthing\st" -logflags=7 -logfile="C:\syncthing\syncthing.log" 
@REM start "Syncthing"
```

I can't reproduce until a new RC comes out :-)

**Comment by AudriusButkevicius** [comment] 2019-07-19 21:57
Please check closed issues and changed commits and what issues they closed in the RC, so we don't have duplicates.

**Closed by AudriusButkevicius** 2019-07-19 21:57 UTC

**Comment by calmh** [comment] 2019-07-19 22:04
Duplicate of #5869

**Comment by sisu4syncthing** [comment] 2019-07-19 22:07
At least you know, that its still not fixed.

Why is there no entry in the changelog? Would be useful for ppl. which check github not every day.

**Comment by imsodin** [comment] 2019-07-19 22:07
I think the problem is understandable and not a case of checking closed issues:  
@sisu4syncthing The problem happened while you were still on rc.2, the fix is only in rc.3. So in a future upgrade to 1.2.1 or 1.2.1-rc.4 it will work. We can't change rc.2 that you already have.
