### ISSUE TITLE
Feature: More meaningful errors in the GUI

### ISSUE THREAD

**Issue by thegeek1977** [syncthing/syncthing#1550] opened 2015-03-31 02:48 UTC
Hi.

"The folder <some foldername> isn't making progress. Check logs...."

Is just not a user friendly error to throw on the users. Instead the error should tell WHY the folder does not making progress. 

i.e:
"The folder "picts" isn't making progress because of an error. The error is: File picture1.jpg - permission denied while changing ctime of the file. Check file permissions, making sure the ovner of the syncthing process is allowed to write to the file"

It's fine to have this info in the logs /Stdout too but the GUI should really reflect the error that syncthing are throwing and giving the user a chance to know what went wrong and why for him to solve the issues.

All other errors that affects the syncprocess should also be communicated to the user in a more user friendly way" the user should really not go to the logs to find theese informations. This will really enhance the UX and the feel of this great piece of software, even for a experienced user like me. 

Thanks

**Comment by calmh** [comment] 2015-04-04 07:37
This needs resolving.

**Comment by ralder** [comment] 2015-04-04 12:49
and maybe add able to translate errors

**Comment by generalmanager** [comment] 2015-04-13 08:23
Seems to be a dupe of https://github.com/syncthing/syncthing/issues/1437

**Comment by Zillode** [comment] 2015-05-10 18:10
It is

**Closed by Zillode** 2015-05-10 18:10 UTC
Labels: enhancement
