### ISSUE TITLE
Incomprehensible error message: 'directory is not empty; files within are probably ignored on connected devices only'

### ISSUE THREAD

**Issue by LinuxOnTheDesktop** [syncthing/syncthing#6575] opened 2020-04-26 21:02 UTC
![image](https://user-images.githubusercontent.com/47056543/80319577-ff25ba80-8808-11ea-9e08-f5122c62a6ec.png)

> directory is not empty; files within are probably ignored on connected devices only

Grammar and therefore clarity requires an 'it' after the 'within'. More importantly: 'are probably ignored on connected devices only'? What does that mean? More: how does this 'ignoring' relate to the non-emptiness of the directory? Further, the user should be given some information on how to solve the problem. (Also: 'they are retried automatically' should be 'will be retried automatically' - yes?)

### Version Information

Syncthing Version: 1.5.0-rc2
OS Version: Linux Mint 19.3

**Comment by calmh** [comment] 2020-04-26 21:47
"Inquire within" seems a common phrase with "it" not following "within". But none of us working on this are native English speakers, so please feel free to propose a better wording.

**Comment by LinuxOnTheDesktop** [comment] 2020-04-27 06:23
Yes, 'files within' is good (if perhaps slightly archaic) English. The problem is that the 'within' refers to something that was mentioned before the semi-colon. That might not matter - might not generate any unclarity -were the rest of the line to be in perfect English; but, as I said, I fail to understand the rest of the sentence. If you tell me what the rest of the sentence means, then I can propose a better wording!

**Comment by calmh** [comment] 2020-04-27 06:45
It means that the directory probably contains files, files which are ignored on other devices but not ignored on this device.

**Comment by imsodin** [comment] 2020-04-27 06:49
shouldn't we just resurrect the dir then? i even think we already do that and  this is done even cornery corner case, but can't check right now

**Comment by calmh** [comment] 2020-04-27 06:53
I think our dir resurrection applies in another case (we get a change for a file in a directory which we have deleted). I guess we could do the same in this case. The effect then would be that the user on the other side gets confused when they deleted a dir and it gets created again a short while after...

**Comment by LinuxOnTheDesktop** [comment] 2020-04-27 07:08
So, what the error message means to report is, partly, the following? **There is a directory that cannot be synchronised between devices, because that directory is not empty.** OK. But (1) _why_ does that non-emptiness prevent synchronisation? (2) _What has the 'ignoring' got to do with anything?_

**Comment by imsodin** [comment] 2020-04-27 08:43
lets say we have dir foo on two devices a and b. b has ignore patterns foo/**. on a there is a file /foo/bar, which is not synced by b as it is ignored. now on b dir foo is deleted. a tries to delete it too to get in sync bot notices the not deleted file and consequently doesn't delete it but trow this error.

 > The effect then would be that the user on the other side gets confused when they deleted a dir and it gets created again a short while after...

true that and most the solution will be deleting the file within respectively also ignoring it, thus the message is on the right side. so imo we should improve the error msg, maybe with a link to a sample scenario if we can't come up with something short and clear.

**Comment by LinuxOnTheDesktop** [comment] 2020-04-27 09:30
Let me check I understand the problem (the problem syncthing is reporting). Is it as follows? 

Folder F1 exists on two devices, call them Device A and Device B. Device B is set to ignore F1. On Device B, F1 is deleted (for, although B is set to ignore F1, somehow F1 does exist on B). And . . no, I still do not understand.

**Comment by arpie42** [comment] 2020-04-27 09:38
As a native english speaker, I thought I might butt in on this!  Let me try explaining... see if I have understood correctly :
Folder F1 exists on two devices, call them Device A and Device B. Device B is set to ignore the contents of F1, but not the directory F1 itself.  So, on Device A, F1 can contain files but these files will not be synced to Device B. On Device B, F1 is deleted... what should Device A do?  Report an error because it doesn't want to delete a non-empty folder.

**Comment by arpie42** [comment] 2020-04-27 09:45
As for the error message, how about :
'directory is not empty on all devices: its contents may match an ignore pattern on another device'

I also agree that 'they are retried automatically' should be 'will be retried automatically'.

**Comment by LinuxOnTheDesktop** [comment] 2020-04-27 10:28
I wish to stress my earlier claim that the user should be given some help in deciding what to do (presuming that the program is not modified to solve the problem automatically).

**Comment by AudriusButkevicius** [comment] 2020-04-27 11:15
It's up to the user to decide what todo, the program is given unsatisfiable constraints, it's just telling you that it has encountered them.

**Comment by imsodin** [comment] 2020-04-27 11:51
> As for the error message, how about :
'directory is not empty on all devices: its contents may match an ignore pattern on another device'

i'd remove the 'on all devices' because the relevant device is the local one, i.e.   
> 'directory is not empty: its contents may match an ignore pattern on another device'

and for comparison the current msg:  
> 'directory is not empty; files within are probably ignored on connected devices only'  

personally i do prefer the new one, but do not see a major difference respectively improvement in understandability. then again as mentioned i am not natively English speaking and anyway not a good judge for understanding of syncthing (started at it too long already).

**Comment by LinuxOnTheDesktop** [comment] 2020-04-27 12:05
> It's up to the user to decide what todo, the program is given unsatisfiable constraints, it's just telling you that it has encountered them. We don't know what the users intentions are.

I suppose I was thinking that the program should tell the user some options. However, I suppose that might be unnecessary were the error message to be clear enough. With the _present_ error message, the user is likely to have no idea what is happening and no idea how to fix the problem and indeed no idea whether the problem is serious or not; and I do not think I can be blamed for thinking that such a user deserves some help.

**Comment by arpie42** [comment] 2020-04-27 13:34
> > As for the error message, how about :
> > 'directory is not empty on all devices: its contents may match an ignore pattern on another device'
> 
> i'd remove the 'on all devices' because the relevant device is the local one, i.e.

I chose to add 'on all devices' to stress that the folder on the local device may be empty but the error is caused by non-empty directories on other devices.  In my opinion, the relevant device is the one with the ignore patterns defined (so probably not the local one)?

In other words, the error is caused by a disagreement between what two or more devices are trying to do - one is ignoring files, the other is trying to delete them.  In any case, the 'relevant' device depends on the users intention and is not necessarily the local one, since the fix may involve editing an ignore pattern on a different device.

I have to add, though, that anybody capable of adding ignore patterns to any devices is surely a power-user who will be able to solve this issue from the original error message, even if it is not totally clear?

That said, using the term 'ignore pattern' is much clearer than just saying 'ignored' (it makes it obvious why it is being ignored).

**Comment by LinuxOnTheDesktop** [comment] 2020-04-27 14:39
> I have to add, though, that anybody capable of adding ignore patterns to any devices is surely a power-user who will be able to solve this issue from the original error message, even if it is not totally clear?

Perhaps not. For, (1) someone might set an ignore option and then totally forget having done so. That may have happened with me. On the other hand, (2) perhaps the problem can arise without an ignore option being set. I may have occcasioned the problem by a combination of moving folders around in the directory tree (on one or more devices) and deleting items (on one or more devices). It is perhaps worth adding that I have Syncthing 1.5.0-rc2 on three devices (a Windows desktop and two Linux laptops) and Syncthing 1.4.2 on another device (an Android 'phone; I have not found an easy way to get 1.5.0-rc2 on the 'phone).

**Comment by arpie42** [comment] 2020-04-27 15:02
@LinuxOnTheDesktop perhaps you are right.  Running different versions seems like you are asking for trouble!  In any case, I stand by my above suggestion of alternative wording for the error message and wish you luck tracking down your problem.  I presume you have already checked your ignore patterns on all devices, searched within the folder for hidden files or files with odd permissions (on all devices), and tried deleting the same folder on other devices?

**Comment by LinuxOnTheDesktop** [comment] 2020-04-27 15:18
> wish you luck tracking down your problem.

Thank you. I solved the problem by deleting all the affected folders and then restarting Syncthing on all devices. I do not think I had any ignore patterns set. Nor do I think that any of the affected items were hidden or had strange permissions (though I can envisage that _maybe_ they had strange permissions). And _here we see the sort of things that might be mentioned in the error message, in order to help the user_.

**Comment by imsodin** [comment] 2020-04-27 15:57
> In my opinion, the relevant device is the one with the ignore patterns defined (so probably not the local one)?

Relevant was a poor choice of words, what I meant is the device where this error occurs is the device where the dir is not empty. Saying `directory is not empty on all devices` leaves an ambiguity on whether it's empty on this device or not. That's why I like just `directory is not empty` as a first short and factual statement. Maybe instead extend the latter part of your proposition to `its contents may match an ignore pattern *and not exist* on another device` (italic just to highlight the change).

And for debugging and discussing possible other causes for this error state please use the forum. None of the other circumstances mentioned should cause this error, thus it first requires investigating to identify what exactly is going on - which better happens on the forum. Then once we know more failure modes, we can consider how to best bring those to the user, lets first focussing on making the currently known info understandable.

**Comment by arpie42** [comment] 2020-04-27 22:12
@imsodin Yes, you're quite right.  My bad.  I have reread your earlier explanation and now it makes sense.  I agree with you that 'on all devices' is misleading.  However, I would guess that more complex situations could cause this same error, eg. where the directory is not empty on either device, but only some of its contents match an ignore pattern on one of those devices.

It seems that the OP has solved his particular problem by brute force, but would have liked a more descriptive/helpful error message to help him solve it more quickly.  I can't imagine this particular scenario occurs very often!

After some consideration, I think what is needed to make this clearer is to express in the error message what syncthing *wants* to do (ie. delete the directory), as well as why it can't.  For example :

'Directory has been deleted on a synced device but won't be automatically deleted here as some contents match an ignore pattern on other device.'

**Comment by LinuxOnTheDesktop** [comment] 2020-04-28 18:27
Good job @imsodin (though I've nitpicked on [this page](https://github.com/imsodin/syncthing/commit/cded2bb09459e158e70f04abccd260a965c20233)).

**Comment by imsodin** [comment] 2020-04-28 18:41
You don't need to close issues, they get closed automatically when the corresponding PR is merged (here #6586). Actually please don't close issues in general unless you discovered that what you reported doesn't actually apply.

And thanks for the comment. It's customary (and easier to find) if you comment on the PR not the commit. I should mentioned it (I find it a bit weird that having the issue in the PR title doesn't create a link anyway...).

**Closed** 2020-05-01 09:11 UTC
