### ISSUE TITLE
debian package postinst failure

### ISSUE THREAD

**Issue by errror** [syncthing/syncthing#7633] opened 2021-05-05 07:33 UTC
### Include required information

Please be sure to include at least:

 - which version of Syncthing and what operating system you are using: **syncthing 1.16.0**
 - browser and version, if applicable: **not applicable**
 - what happened:
   - Upgrading syncthing package from apt.syncthing.net
   - no syncthing systemd service configured
   - no syncthing process running
   - postinst fails in `pkill -HUP -x syncthing`
 - what you expected to happen instead:
   - postinst should not fail if no syncthing processes are running, e.g. check for existing syncthing processes before HUPing them
 - any steps to reproduce the problem.
   - see "what happened"

**Comment by imsodin** [comment] 2021-05-05 07:35
Duplicate of https://github.com/syncthing/syncthing/issues/7628

**Closed by imsodin** 2021-05-05 07:35 UTC
Labels: bug, needs-triage
