### ISSUE TITLE
Many Sync conflicts are generated, while the file is modified on only one Client 

### ISSUE THREAD

**Issue by domonoky** [syncthing/syncthing#2584] opened 2015-12-15 17:11 UTC
Since Version 0.12.x is get many Sync-conflict files on files which are definitely only modified on one system. Often the new content is then in the .sync-conflict file and the old content is somehow restored in the orginal file. 

If someone can tell me which option i should enable to get a usefull log. Please tell me.

Setup:
3 Syncthing clients: Windows 7, Windows Server, Windows XP

**Comment by AudriusButkevicius** [comment] 2015-12-15 17:48
I think its impossible for what you've described to happen. You can use the /db/file endpoint to query the version of the file, which can explain if its being modified in one or more places.

If this was a bug, it should happen to every single file.

I think what can potentially happen is that modification timestamp of the file gets adjusted by some piece of software you have on the side which is not modifying the file content, but the metadata, which is still a valid reason for a conflict.

**Comment by AudriusButkevicius** [comment] 2015-12-15 17:50
Also, -verbose -audit options could show something.

**Comment by domonoky** [comment] 2015-12-15 18:30
I noticed this strange sync-conflicts while editing .odt files and editing images with gimp. So it isn't a active db or so.
I will try to reproduce it with -verbose -audit and see if i can find a useful output. Is there any STTRACE option which shows the detected conflicts ?

**Comment by AudriusButkevicius** [comment] 2015-12-15 18:44
No, there isn't. You already know what conflicts were detected by looking at the file names that had the suffix appended. Also, I am guessing you are using inotify for the conflict to happen immediately? It could also be due to some wierd file locking, but you should see errors in the logs (without any extra debug flags) in that case. Also, it potentially could be some sort of indexing software, like picasa, detecting a new file, adding it to a gallery and updating the jpeg/png header about which gallery its in, essentially leaving the viewable image intact, but modifying the content.

**Comment by domonoky** [comment] 2015-12-15 18:57
As far as i know, i do not use inotify, at least i did not configure for it :-) 
Also it should not be something like picasa as it also happens with .odt file, .c files and many more file types. Its really strange (and pretty dangerious, as i now often have old content in the file and my new content moved to the conflict file) .:-) 
I looked at the log file but can not find any errors regarding the conflicts. There is only one repeating error, that it can not delete a specific directory because it is not empty, and then it pauses the puller for a minute and then continues. 
Maybe the error is somehow related, with changes happening maybe when the puller is paused ? 

For the logs: I am looking for some option to find out why syncthing thinks this is a conflict, when the file is changed locally. The timestamp should be newer then the last one in the index, so it should treat it as a new version, not a conflict. 
Maybe i should dig into the source myself :-)

**Comment by domonoky** [comment] 2015-12-15 19:07
Attached is a zip file with the syncthing.log and the audit log while such strange conflicts where generated. The affected files where 197.jpg, 198.jpg and 199.jpg. This time the conflict files contained older data...

Not sure if this logs help to debug the issue...

[logs.zip](https://github.com/syncthing/syncthing/files/63076/logs.zip)

**Comment by domonoky** [comment] 2015-12-15 19:48
To prevent any issues with deleted and recreated files i just did another test in a new folder (LB1180_2).
Put the images into this folder and waited till they where synced to the other system. Then i modified them locally and monitored the filesystem on both systems. 
This time it uploaded the modified files to the remote system but somehow decided they where conflicts and not updates on the remote system. So it created the sync-conflict files on the remote system and then sync those back to me. 
Affected files: 135.jpg 174.jpg 179.jpg 190.jpg 191.jpg, 192.jpg 193.jpg 194.jpg 195.jpg 196.jpg 
Files in the same folder but somehow synced without conflict: 197.jpg 198.jpg

I hope this logs somehow help to debug this. If you have any suggestions on what i should try, please tell me.
[logs.zip](https://github.com/syncthing/syncthing/files/63113/logs.zip)

**Comment by AudriusButkevicius** [comment] 2015-12-15 20:07
Right. The logs don't contain anything obvious.
Try this build http://build.syncthing.net/job/syncthing-pr/1349/ with STTRACE=conflict

**Comment by domonoky** [comment] 2015-12-15 21:02
Thank you for your fast response :-) 

I installed this build on the local and the remote system with the STTRACE option. And did the same test again. 
Again the bogus conflict was detected on the remote system on the following files
135.jpg, 174.jpg, 191.jpg, 192.jpg, 193.jpg,194.jpg
the other 5 files where correctly synced.

Attached you will find the log from the remote system. 
Some more information about the remote system: Its a Windows Server2008 and the Data sits on a NAS storage system.
[syncthing.zip](https://github.com/syncthing/syncthing/files/63181/syncthing.zip)

**Comment by AudriusButkevicius** [comment] 2015-12-15 21:50
So it seems the file got modified twice in quick succession before the fact that we've received it gets propagated back, causing a conflict.

In this case the receiver MC5WCAZ already has:
```
protocol.FileInfo{
	Name:"Projekte\\KundenauftrÃ¤ge\\Weightworks\\Laserteile\\Deckel-gelasert\\15.12.15\\LB1180_4\\179.jpg", 
	Flags:0x1a4, 
	Modified:1450212405, 
	Version:protocol.Vector{
		protocol.Counter{ID:MC5WCAZ, Value:0x1}, 
		protocol.Counter{ID:TAQLGAQ, Value:0x1}
	}, 
	LocalVersion:162217, 
	CachedSize:0
} 
```

and suddenly it receives the following file (potentially from TAQLGAQ)
```
protocol.FileInfo{
	Name:"Projekte\\KundenauftrÃ¤ge\\Weightworks\\Laserteile\\Deckel-gelasert\\15.12.15\\LB1180_4\\179.jpg", 
	Flags:0x1a4, 
	Modified:1450212627, 
	Version:protocol.Vector{
		protocol.Counter{ID:TAQLGAQ, Value:0x2}
	}, 
	LocalVersion:61207, 
	CachedSize:0
}
```


I summon @calmh to answer if there is something fishy here.

**Comment by AudriusButkevicius** [comment] 2015-12-15 21:53
Also, it seems that the first file we alread have only has 5 blocks, and the new file has 7 blocks, so the content is definitely different and not conflicting with itself.

**Comment by calmh** [comment] 2015-12-20 17:12
This sounds like a straight "concurrent modification" kind of conflict to me? Different version counters, different size...

**Comment by AudriusButkevicius** [comment] 2015-12-20 17:25
Well, the only suspicion I have is if we advertise version 1, and before we get acknowledged that everyone has version one, and we produce version 2, why does the fact that someone now has version 1 (which is our old version) cause a conflict?

I think conflicts should only happen from two different devices having the same max version, rather than some device having some older version?

**Comment by domonoky** [comment] 2015-12-20 18:27
Just to clarify i will describe again what i have done to generate this logs:
1. Create files on TAQLGAQ and wait till they are synced (visible in the filesystem) to MC5WCAZ  
2. Modify the files (they got smaller) on TAQLGAQ 
3. After some time they get to MC5WCAZ  but somehow MC5WCAZ determines it is a conflict and not a update (for 6 out of 10) files, so it creates conflict files for those.
4. the conflict files get synced back to me.

I have this problem since version 12.x, and it happens nearly everytime in some different variation (depending on which system detects the bogus conflict). 

If i can do something to debug this problem further, please tell me, as currently synthing is not really useable for me.

**Comment by AudriusButkevicius** [comment] 2015-12-20 18:31
Do you have rate limiting set to very low on either side?

**Comment by andersonvom** [comment] 2015-12-20 18:32
Can you monitor the files on the node where they are not supposed to have been modified? This would guarantee that there's nothing automatically changing either the files or their metadata. Maybe loop over them and get both file attributes and hash them constantly until you see the conflict?

**Comment by AudriusButkevicius** [comment] 2015-12-20 18:34
There is a utility stwatchfile which helps you do that, you only need to somehow predict which file it will be.

**Comment by domonoky** [comment] 2015-12-20 18:38
@AudriusButkevicius TAQLGAQ has a outgoing rate limit of 50kb, MC5WCAZ  has no limit but is pretty slow to update as it is not a local system.

I will try this monitoring thing and report back..

**Comment by AudriusButkevicius** [comment] 2015-12-20 18:40
I suggest you try and remove the limit, and see if it exhibits the same behaviour.

**Comment by domonoky** [comment] 2015-12-20 19:11
I have just done this test again. Syncthing version is now 0.12.9.
- I removed the limit on TAQLGAQ 
- startet stwatchfile on one of the files in the set,once MC5WCAZ once it had the first version of the files.
- modified the files on TAQLGAQ 

Result: 
-after some time MC5WCAZ  recieves the updates, but decides that all files are conflicting and generates conflict files. This time it affected all 12 files of the set.
- stwatchfile detected one modification at the time when syncthing overwrites the file with the new version.

**Comment by AudriusButkevicius** [comment] 2015-12-20 20:10
So I guess I am still interested in @calmh's answer to my question.

Alternatively, you could try and provide an isolated environment where this is reproducible with some arbitrary set of files.

**Comment by domonoky** [comment] 2015-12-20 21:02
I just did some tests with older versions to find out when exactly this problem started.
And i get those bogus conflicts with version 0.12.4 but not version 0.12.3. 
Maybe this helps to find out more ?

**Comment by AudriusButkevicius** [comment] 2015-12-20 21:19
I don't see anything related to conflicts.. There is only changes to the scanner, but I don't think they have any effect.

https://github.com/syncthing/syncthing/compare/v0.12.3...v0.12.4

**Comment by calmh** [comment] 2015-12-21 16:31
What kind of box (OS/version) is MC5WCAZ? 

> after some time MC5WCAZ recieves the updates, but decides that all files are conflicting and generates conflict files. This time it affected all 12 files of the set.

this sounds to me like it's doing something freaky with the filesystem. Antivirus? Something that automatically updates metadata or thumbnails in your JPEG? FAT filesystem with limited mtime precision? A combination?

**Comment by domonoky** [comment] 2015-12-21 17:14
MC5WCAZ is Windows Server 2008 and the data sits on a NAS (accessed via //NAS... path).
I tried stwatchfile on this system and let it monitor one of teh files i updated. It did not notice any changes until syncthing overwrote file with new data (and created the conflict file).

I have now downgraded all my systems to Syncthing 0.12.3 and till now i did not see any bogus conflicts. If this was some problem with antivir or a like, shouldnt this happen with this version too?

**Comment by andersonvom** [comment] 2015-12-21 19:09
Since you seem to be the only one who can reproduce the issue, do you think you could run a [`git bisect`](http://git-scm.com/book/en/v2/Git-Tools-Debugging-with-Git#Binary-Search) between [v0.12.3...v0.12.4](https://github.com/syncthing/syncthing/compare/v0.12.3...v0.12.4) locally and find the exact commit that causes the issue?

**Comment by domonoky** [comment] 2015-12-21 19:38
Sure I can try to bisect and find the exact commit if that helps.
But as i only have time for this on weekend and christmas is coming up, it will probably take some time till i get to it.

**Comment by AudriusButkevicius** [comment] 2016-01-15 23:59
Ping @domonoky

**Comment by AudriusButkevicius** [comment] 2016-02-25 19:08
So following https://forum.syncthing.net/t/sync-conflicts-generated-when-syncing-over-network-storage/6700/4

It seems it was introduced by addition of sparse file support.
I am not exactly sure how that affects it, but both cases of the same problem seem to point to the same issue.

I guess we need a test environment to try and reproduce it.

**Comment by AudriusButkevicius** [comment] 2016-02-25 19:13
http://serverfault.com/questions/731632/does-nfs-and-smb-support-sparse-files

**Comment by domonoky** [comment] 2016-03-02 18:25
One of the systems where I get the bug is using a NAS system with SMB protocol for storage. 
So it is very likely that this is the bug. And the conflict is created as the file changes due to the expanded zeros on sparse files.

**Comment by cmarsura** [comment] 2016-03-02 21:03
I think the problem is more general and unrelated to sparse files but to related code or underlying libraries; I don't have to do with sparse files but with various kind of files. Also with simple text files the problem surfaces; if you append some text to a file with a simple command like this:
> echo some_inline_text>>incr.txt

and force a rescan, you can see the sync conflict warning to appear.

I noted that the file replicated on the share have a time that is 2-3 seconds ahead of the original source file (but the content is the same of source) hence the sync conflict.
Not being very practical with go language and git I cannot say where is the difference, but looking at the lower level OS api calls there is a point where there is a call to set the file modification time that seems ignored by the OS.

@AudriusButkevicius : as previously stated, let me known if you need help to make some tests for you.

**Comment by AudriusButkevicius** [comment] 2016-03-02 21:13
@cmarsura but is the assumption still correct that a networked filesystem needs to be involved?

**Comment by cmarsura** [comment] 2016-03-02 21:36
Yes, you -must- have the destination folder on a SMB share. Having dest folder placed on a local disk does not make the problem to appear.
I experienced the problem on both a Qnap SMB share and Windows share as destinations.

You should conduct tests using two machines: if you use a single Windows pc with a share and two sessions running Syncthing at same time does not work, I think because the OS 'cut short' on some underlying API calls or change some return code sufficient to divert the code path. I experienced this on a Windows 7 pc while trying to setup a more simpler and unique test machine.

**Comment by cmarsura** [comment] 2016-03-02 22:12
Mhhh, searching more info on my Qnap TVS 471 with QTS 4.2 OS, I found this link [https://www.qnap.com/i/en/tutorial/con_show.php?op=showone&cid=184](url)
that summarizes also the SMB version implemented by the Windows OSes: my Qnap implements SMB v 3.0, while Windows 7 and Windows Server 2008 R2 implement SMB v 2.1 .
I should say that I have not tested a destination folder on a more recent Windows version, but the Qnap I use seems to have same SMB version of the newest Microsoft OSes.

**Comment by cmarsura** [comment] 2016-04-05 21:36
After dissecting the sources, seems that the culprit is the code that truncates the file:
`
if err := fd.Truncate(s.file.Size()); err != nil {
    s.failLocked("dst truncate", err)
    return nil, err
}
`
at line 147 of lib\model\sharedpullerstate.go as of version v0.12.21.
Commenting those lines make the sync conflicts problem disappear.

**Comment by AudriusButkevicius** [comment] 2016-04-05 21:46
So you have a flag, which allows disabling truncate, which should fix the issue.

**Comment by cmarsura** [comment] 2016-04-06 11:48
Yes, it works.
Thank you Adrius :-)

**Comment by AudriusButkevicius** [comment] 2016-04-06 11:55
We should do a test upon startup, and set that automatically.

**Comment by calmh** [comment] 2016-04-06 13:52
Or just remove the config option completely and make the failure non-fatal. We don't *need* the truncate to succeed, but if it doesn't we should write out zero blocks literally and also handle the (rare) case that we have an existing temp file to reuse that is actually *larger* than what we're aiming for...

**Comment by AudriusButkevicius** [comment] 2016-04-06 13:55
So the issue is not the truncate call failing, it's the end result file not being what we expect it to be. Do we send truncated blocks across?

**Comment by calmh** [comment] 2016-04-06 14:00
That's weird. When sparseness is enabled we 1) Truncate() the file, 2) Skip transferring/copying/writing blocks that match the hash of a full all-zeroes block.

**Comment by AudriusButkevicius** [comment] 2016-04-06 14:32
So conflict implies that the hashes are somehow different, which implies that the list of blocks produced on two sides are different.

**Comment by calmh** [comment] 2016-04-06 14:41
I don't see how commenting out the truncate call would help, unless it is that call that fails...

**Comment by AudriusButkevicius** [comment] 2016-04-06 15:26
I don't think it fails though. @cmarsure can you confirm if you see errors in the log?

**Comment by calmh** [comment] 2016-04-06 18:56
<anecdote>
There is some other completely unrelated issue here as well. I see it in my own setup (unix to unix, local filesystem on both sides), I just haven't had the energy to get to the bottom of it. I have one side that is master, and it will seemingly randomly become out of sync on a couple of files and require overriding. I'm 100% super duper certain that no changes happen to the files on the other side - it's an isolated VM that *only* runs syncthing to receive these files. I've been unable to narrow down what it thinks the changes are; there's nothing obvious when looking at the file data in the rest interface, other than that the "correct" file has a version vector like `{"masterdevice": 42}` and the other has `{"masterdevice": 42, "slave": 1}` and when I hit override that becomes `{"masterdevice": 43}` and stays that way for "a while". It doesn't affect the same files always. It doesn't happen very often, but probably at least once a week if I did check that often.
</anecdote>

**Comment by cmarsura** [comment] 2016-04-06 22:09
@AudriusButkevicius there are no errors in the log following the file truncation.

I think the problem is not the truncation operation per se, but the the truncation change the modification time of the ~syncthing~filename.tmp that you after go to rename to become the definitive file; in the next scan syncthing find the file with a time ahead of few seconds respect the source file, so flag the file as conflicting.

In the other forum I posted [here](https://forum.syncthing.net/t/sync-conflicts-generated-when-syncing-over-network-storage/6700/7) an apicalls.xls file with the underlying traces of syncting's OS calls to manipulate the incr.txt file.
Look for example at the st12.19-1 sheet:
row 10 the SetEndOfFileInformationFile truncate the ~syncthing~incr.txt.tmp;
row 24 the ~syncthing~incr.txt.tmp receive LastWriteTime: 20/02/2016 19:35:09
row 37 the incr.txt file is deleted
row 41 the QueryBasicInformationFile retrieve info on ~syncthing~incr.txt.tmp, the LastWriteTime: 20/02/2016 19:35:13 is more recent than the time set previously by 4 seconds
row 42 the ~syncthing~incr.txt.tmp is renamed to incr.txt

For some strange reason you get this behavior only for files residing on shares. For local files the QueryBasicInformationFile retrieve the same LastWriteTime set at row 24

As an experiment, you should try to set  the modification time before closing the tmp file.

**Comment by AudriusButkevicius** [comment] 2016-04-06 22:15
The modification timestamp is the last thing that gets set, so your theory is incorrect.

**Comment by AudriusButkevicius** [comment] 2016-04-08 22:32
So I wasted 3-4 hours setting up an environment, and I cannot repro.

Side A:
WIndows 10 as the client, 
as the server
```
root@debian:~# smbd --version
Version 4.3.6-Debian
```

Side B:
Plain filesystem

**Comment by cmarsura** [comment] 2016-04-09 21:08
Strange. I have 2 Setup and both manifests the problem:
1) Windows Seven (virtual) acting as source of files (folder master) and Windows 8.1 acting as slave and having his folder on a share of Windows Seven;
2) Windows 2012R1 acting as source of files (folder master) and Windows 2008R2 acting as slave and having his folder on a Qnap NAS share;
Both setups are using Syncting v012.21, on the slave the folder path are in UNC format \\\servername\volume\pathtofolder, on advanced settings for the folder disableSparseFiles is disabled (unchecked).

In my spare time I am experimenting with the Syncthing sources. Just tonight have found something that attracted my attention in the performFinish() function, but I would not be wrong.
Let me to perform more experiments.
I will update here after.

**Comment by AudriusButkevicius** [comment] 2016-04-09 21:29
So I guess the problem requires smb share hosted on Windows in order to reproduce this?

**Comment by cmarsura** [comment] 2016-04-09 22:23
Share hosted on Windows but not only Windows: my second setup uses a Qnap share that is a Linux flavour OS ([see here](https://www.qnap.com/i/en/qts4/con_show.php?op=showone&cid=1)).

**Comment by AudriusButkevicius** [comment] 2016-04-09 22:24
Anyways, I cannot reproduce this, so I am closing this.

**Closed** 2016-04-09 22:25 UTC
Labels: bug
