### ISSUE TITLE
Deleted files replaced with empty files.

### ISSUE THREAD

**Issue by mobilediesel** [syncthing/syncthing#2804] opened 2016-02-27 15:05 UTC
If I delete files on my desktop, the filenames are reproduced as empty files. If I then delete the empty files, they come back the next time Syncthing syncs.
### Version Information
Syncthing Version: v0.12.19
OS Version: Debian 7.

Syncthing Version: v0.12.19
Syncthing-Android Version: v0.7.8
OS Version: Android 4.1.1.

**Comment by AudriusButkevicius** [comment] 2016-02-27 15:10
Are you using a network mount anywhere?

Sounds like a duplicate of https://github.com/syncthing/syncthing/issues/2792

**Comment by AudriusButkevicius** [comment] 2016-02-27 15:10
Are they 128 bytes big?

**Closed by AudriusButkevicius** 2016-02-27 15:10 UTC

**Comment by mobilediesel** [comment] 2016-02-27 16:54
They show as 0 bytes. Syncthing isn't pointing to any network shares on any device.

**Comment by AudriusButkevicius** [comment] 2016-02-27 16:57
Are there any errors in the log?

**Comment by mobilediesel** [comment] 2016-02-27 17:11
$HOME/.config/syncthing/index-v0.11.0.db/LOG doesn't appear to have any errors and $HOME/.config/syncthing/index-v0.11.0.db/000893.log doesn't seem to be a text file. Is there another location for a log file or would I have to change the config to write a meaningful log file?

**Comment by AudriusButkevicius** [comment] 2016-02-27 17:26
That's the database log.
It logs to stdout by default.

**Comment by mobilediesel** [comment] 2016-02-27 17:39
Restarted it from the command line and there are no errors. The deleted files all came back again. How would I find the log on the Android device?

**Comment by AudriusButkevicius** [comment] 2016-02-27 17:46
It's somewhere in the options menu I think.

**Comment by mobilediesel** [comment] 2016-02-27 17:52
The log on the tablet shows just "--------- beginning of /dev/log/main" at the top and nothing else.

**Comment by AudriusButkevicius** [comment] 2016-02-27 18:19
Dunno. If you have root access on the phone, you can run it from the command line too
otherwise it's usually in logcat.
