### ISSUE TITLE
Syncthing hangs with slightly malformed listen address

### ISSUE THREAD

**Issue by VA1DER** [syncthing/syncthing#6697] opened 2020-06-01 20:39 UTC
### Overview

With syncthing 1.5 a slightly malformed listen address (tcp4:/127.0.0.1:22000) causes the process to hang.  

### Does your log mention database corruption?

Negative

### Include required information

Please be sure to include at least:

 - **Version:** syncthing 1.5.0 on Linux Mint 19.3 (based on Ubuntu 18.04)  with kernel 5.3.0-53
 - **Steps to reproduce:** Replace the listen address with tcp4:/127.0.0.1 and restart
 - **Errant behaviour:** Syncthing hangs.  Ctrl-C is detected but not actioned.  Kill -9 is required to terminate the process.
 - **Expected behaviour:** syncthing should detect malformed addresses and display an error message, especially addresses that are malformed in common ways

**Comment by AudriusButkevicius** [comment] 2020-06-01 20:49
What do you mean by hang?

I think it simply won't listen on that address and operate "as usual" other than that, it just won't connect anywhere, but UI etc should still be accessible.

I think it does detect that it's malformed, and prints a warning to both web ui and console, so I am not sure what else is expected here.

**Comment by VA1DER** [comment] 2020-06-01 21:14
"Hang" is sometimes a vague term, I apologize.  I mean it in the traditional sense, though.  Does not respond to any input or stimulus.  Web UI is non-functional, the browser is not launched at syncthing startup, and syncthing does not initiate outside connections.  The process detected a CTRL-C but would not then terminate.

Log with local listen address set to tcp:/127.0.0.1:22000
```
[start] 18:01:30 INFO: syncthing v1.5.0 "Fermium Flea" (go1.13.10 linux-amd64) teamcity@build.syncthing.net 2020-04-21 20:45:03 UTC
[MECHS] 18:01:31 INFO: My ID: <snip>
[MECHS] 18:01:32 INFO: Single thread SHA256 performance is 551 MB/s using minio/sha256-simd (480 MB/s using crypto/sha256).
[MECHS] 18:01:32 INFO: Hashing performance is 457.23 MB/s
[MECHS] 18:01:32 INFO: Overall send rate is unlimited, receive rate is unlimited
[MECHS] 18:01:32 INFO: Ready to synchronize "Default Folder" (default) (sendreceive)
[MECHS] 18:01:32 INFO: Completed initial scan of sendreceive folder "Default Folder" (default)
^C[monitor] 18:01:43 INFO: Signal 2 received; exiting



^C^C^C^Z
```
I then have to kill -9 the process to terminate it

Log with local listen address set to tcp://127.0.0.1:22000
```
[start] 18:08:54 INFO: syncthing v1.5.0 "Fermium Flea" (go1.13.10 linux-amd64) teamcity@build.syncthing.net 2020-04-21 20:45:03 UTC
[MECHS] 18:08:54 INFO: My ID: <snip>
[MECHS] 18:08:55 INFO: Single thread SHA256 performance is 547 MB/s using minio/sha256-simd (474 MB/s using crypto/sha256).
[MECHS] 18:08:55 INFO: Hashing performance is 453.94 MB/s
[MECHS] 18:08:55 INFO: Overall send rate is unlimited, receive rate is unlimited
[MECHS] 18:08:55 INFO: Ready to synchronize "Default Folder" (default) (sendreceive)
[MECHS] 18:08:55 INFO: TCP listener (127.0.0.1:22000) starting
[MECHS] 18:08:55 INFO: GUI and API listening on 127.0.0.1:8080
[MECHS] 18:08:55 INFO: Access the GUI via the following URL: http://127.0.0.1:8080/
[MECHS] 18:08:55 INFO: My name is "GoaSTv2.1"
[MECHS] 18:08:55 INFO: Device <snip> is "VA1DER.CA" at [quic4://va1der.ca:22000]
[MECHS] 18:08:55 INFO: Completed initial scan of sendreceive folder "Default Folder" (default)
[MECHS] 18:08:56 INFO: Established secure connection to <snip> at [::]:44828-67.231.28.129:22000/quic-client/TLS1.3-TLS_CHACHA20_POLY1305_SHA256
[MECHS] 18:08:56 INFO: Device <snip> client is "syncthing v1.5.0" named "VA1DER.CA" at [::]:44828-67.231.28.129:22000/quic-client/TLS1.3-TLS_CHACHA20_POLY1305_SHA256
^C
[monitor] 18:12:20 INFO: Signal 2 received; exiting
[MECHS] 18:12:20 INFO: Connection to <snip> at [::]:44828-67.231.28.129:22000/quic-client/TLS1.3-TLS_CHACHA20_POLY1305_SHA256 closed: Syncthing is being stopped
[MECHS] 18:12:20 INFO: TCP listener (127.0.0.1:22000) shutting down
[MECHS] 18:12:20 INFO: Exiting
```

**Comment by calmh** [comment] 2020-06-02 06:23
The problem is that a listening address like `tcp:/127.0.0.1:22000` gets parsed into a URL like `tcp:///127.0.0.1:22000` and we're not entirely consistent in where we use the original string and where we use the parsed string. The result is that try to stop a listener when the supervisor for it hasn't started yet, and this hangs forever.

**Comment by calmh** [comment] 2020-06-02 06:34
Fixing this is easy, it's just a matter of canonicalizing the URL before we use it as a key in a bunch of places. But there's an interesting footgun here, because `tcp:/127.0.0.1:22000` gets leniently parsed into a URL with `Host:"", Path:"/127.0.0.1:22000"`. The lack of host gets fixed by us into the unspecified host and default port, i.e., `0.0.0.0:22000`. That's probably a bit unexpected. So with the naive fix we'll just use this config and silently listen on all interfaces instead of localhost.

Should it be an error to have a URL in non-canonical form?

**Closed** 2020-06-02 09:19 UTC
Labels: bug
