### ISSUE TITLE
Syncthing periodically makes my system unusable by eating all the disk IO

### ISSUE THREAD

**Issue by adamnovak** [syncthing/syncthing#2992] opened 2016-04-19 20:48 UTC
I am running Syncthing in what I think is a fairly common configuration: on a desktop Ubuntu machine. The machine (4 gigs of ram, spinning HDD) and the Ubuntu in question (12.04) are a little old, but they work fine for everything other than Syncthing. I am using Syncthing to sync many gigabytes of photos and other documents between this machine and some others.

Once every few days, my machine will slow to near-unusability. Applications will grey out their windows (which Ubuntu does for you when the app isn't responding), and typing or running commands in terminal windows will be slow and laggy. My Spotify music will stop playing. It can take several minutes to log in to the system over ssh in this state.

I did manage to open up iotop during all this, and found 4 syncthing processes (threads?) fighting to use IO, usually with 2 getting "99.99%" on each screen refresh.

This IO contention seems to reduce overall throughput. My disk is only getting about 1.5 mb/sec read throughput during all this, even though it is capable of much more.

It seems like the suggested solution to this is to run syncthing through ionice, and hope that the IO scheduler works well enough to prevent nice'd IO requests from DoSing the rest of the system. However, I'm already running under `ionice -n 7`, which should be making it defer to normal-priority applications already.

If it's relevant, all the IO is going to an encrypted Ubuntu home directory; I don't know if that confuses the IO scheduler.

My issue is:

**1. How do I stop syncthing from gobbling up all the disk bandwidth and bringing my system to a halt?**

**2. Why is syncthing in its default configuration willing to render a desktop system unusable with its disk IO load? Shouldn't it default to safe behavior?**

### Version Information

Syncthing Version: v0.12.22
OS Version: Ubuntu 12.04
Browser Version: N/A

**Comment by AudriusButkevicius** [comment] 2016-04-19 20:59
Your OS/kernel is unable to cope with the disks that you have. 
Ideally the kernel does read aheads, and having 4 threads of IO is perfectly acceptable when the kernel is able to do it's thing. Your disks are either very old and perhaps near death. I suggest you run disk benchmarks to see where you are at, and check for errors, and you might end up surprised.

In the meanwhile you can adjust `Hashers` option on each folder that you have in the advanced config and set that to one, to have only one thread per folder performing hashing, but I think your issue lies somewhere else.

Also what does not make sense that this builds up over time. I don't think time has anything todo with this.

I am closing this as there is no actionable item.
If you want to have a further discussion it can be done under the closed ticket or ideally moved to the forum, given the nature of this is not a bug report, but rather a support request.

**Closed by AudriusButkevicius** 2016-04-19 20:59 UTC

**Comment by adamnovak** [comment] 2016-04-20 17:24
FWIW gsmartcontrol thinks the drive is perfectly healthy.

I can try knocking down the hasher counts.

I think the unusable slowness isn't a direct consequence of the syncthing
IO load. It might depend on (or really be caused by) memory pressure from
Firefox causing the system to start swapping, and syncthing is just
coincidentally trying to hash stuff at the same time.
