### ISSUE TITLE
"Currently Shared With Devices" list in the folder Sharing tab should be sorted alphabetically

### ISSUE THREAD

**Issue by tomasz1986** [syncthing/syncthing#7940] opened 2021-09-12 03:20 UTC
The list of devices under "Currently Shared With Devices" appears not to be sorted alphabetically. I'm not sure what the order is actually defined by right now. Is it by device ID?

![image](https://user-images.githubusercontent.com/5626656/132970854-d67ed753-07b4-4e6f-9f08-353d7a622abb.png)

On the other hand, the "Unshared Devices" list right below the current one is sorted alphabetically, so I believe that there is no reason not to sort this one alphabetically too. Not a huge deal, but it can become bothersome quickly if you have lots of devices.

**Comment by tomasz1986** [comment] 2021-09-12 13:59
I've just found out there are a lot of errors in the console when opening the modal.

![image](https://user-images.githubusercontent.com/5626656/132990472-27d1f346-ba3f-4fa7-9115-a8c3bb3bae2d.png)

Not sure if related to the sorting issue or not, but I'm including this just in case.

**Comment by AudriusButkevicius** [comment] 2021-09-12 14:04
Looks like warnings rather than errors?

**Comment by tomasz1986** [comment] 2021-09-12 14:54
Yeah, and I've just gone through the code to find out whether there is any connection, but the warnings seem to be about a hidden element. It would be nice to fix them, but they have no relation to the sorting thing. I haven't been able to find out how to actually sort the device list though.

**Comment by acolomb** [comment] 2021-09-13 09:28
Sorting is fixed in #7945.

I can't reproduce the duplicate ID issue.  It has the correct `sharedwith-XXXXXXX` ids when I check using Firefox inspector.

**Closed** 2021-09-13 18:41 UTC
Labels: enhancement, ui
