### ISSUE TITLE
Docker: 'standard_init_linux.go:211 exec user process caused "exec format error"'

### ISSUE THREAD

**Issue by nsa** [syncthing/syncthing#6789] opened 2020-06-23 12:32 UTC
I wanted to give the Docker container a try from the Docker page at [Readme-Docker.md](https://github.com/syncthing/syncthing/blob/main/README-Docker.md) for my Raspberry Pi Model B Rev2(Arch Linux ARM armv6l) device. But the container did not even start. I searched for a specific tag for **armv6** arch on syncthing's [Docker hub](https://hub.docker.com/r/syncthing/syncthing/tags) but I could not find any. I believe this error is architecture related.

I tried this command:
```
docker run -p 8384:8384 -p 22000:22000 -v /home/alarm/rasp:/var/syncthing syncthing/syncthing:latest
```
I got this message:
```
standard_init_linux.go:211: exec user process caused "exec format error"
```

![image](https://user-images.githubusercontent.com/4787945/85402470-6be8d700-b564-11ea-87cd-f4fdd2ffc4af.png)

I wonder if this is my fault or not and if so; I'm sorry for spending your time and you may close this issue.

**Comment by AudriusButkevicius** [comment] 2020-06-23 12:43
I think we only ship amd64 docker images.

Looking at https://github.com/moby/moby/issues/36552 I don't think there is even a way to even tell it which architecture images to pull down.

**Comment by nsa** [comment] 2020-06-23 12:57
I am not sure because for example if I pull down `dperson/torproxy` image from docker hub to my computer it pulls *amd64* image but if I pull the same image to my raspberry pi it pulls the *arm* image. I can see that in `docker inspect dperson/torproxy` command.

Or maybe you could provide arm specific tags like in https://hub.docker.com/r/nodered/node-red/tags?page=1&name=arm

**Comment by calmh** [comment] 2020-06-23 13:09
Duplicate of #5436

**Closed by calmh** 2020-06-23 13:09 UTC
Labels: bug, needs-triage
