### ISSUE TITLE
Could it support "Selective Sync",such as NAS?

### ISSUE THREAD

**Issue by ErDongChen1973** [syncthing/syncthing#8330] opened 2022-05-08 06:53 UTC

**Comment by tomasz1986** [comment] 2022-05-08 07:18
Probably a duplicate of https://github.com/syncthing/syncthing/issues/2491?

You can actually use ignore patterns (see https://docs.syncthing.net/users/ignoring.html) to do "selective" sync already. Yes, it's a little clunky, and you do still need to manually delete files from the disk after ignoring them, but it does the job nevertheless.

**Comment by ErDongChen1973** [comment] 2022-05-08 08:07
> Probably a duplicate of #2491?
> 
> You can actually use ignore patterns (see https://docs.syncthing.net/users/ignoring.html) to do "selective" sync already. Yes, it's a little clunky, and you do still need to manually delete files from the disk after ignoring them, but it does the job nevertheless.

Thank u for your reply！

**Closed** 2022-05-08 09:54 UTC
Labels: enhancement, needs-triage
