### ISSUE TITLE
Option to choose which folder will sync through mobile data only

### ISSUE THREAD

**Issue by HaremKnight** [syncthing/syncthing#9249] opened 2023-12-03 04:56 UTC
### Include required information

Please be sure to include at least:

 - what problem your new feature would solve
 - how or why you think it is generally useful (i.e., not just for you)
 - what alternatives or workarounds you considered
 I have a folder for backup things but sometimes the file are big and I don't want to use my mobile data.

However, there are also some files that I want to transfer to my work laptop using syncthing to work. It's annoying to disable the "wifi only" option and restarting syncthing everytime.

By having this option, user can also make separate folder that have high priority to always sync even on mobile data while keeping other folder waiting for wifi.

**Comment by imsodin** [comment] 2023-12-19 23:03
Duplicate of https://github.com/syncthing/syncthing/issues/8394

That issue doesn't have the "per-folder" aspect in the title, but it came up in discussion. And once the much bigger pre-requisite is there (handling/detecting mobile/metered networks), configuring that per folder likely makes sense from the start or is a simple add.

**Closed by imsodin** 2023-12-19 23:03 UTC
Labels: enhancement, needs-triage
