### ISSUE TITLE
feature: new global change event: move/rename

### ISSUE THREAD

**Issue by slytomcat** [syncthing/syncthing#4363] opened 2017-09-11 08:44 UTC
Last day I changed extension for couple of hundreds images in Syncthing folder. And it started to download new files to all nodes in the cluster. I know that this happens that delete event can come first and and new event will require the new file transfer through the net. 

What about new type of event: move/rename from <file name> to <file name>? 

It could guarantee that no transfer will be generated by file rename or movement within the synced folder.

I know that it is not so easy to catch such event even through the i-notify facility (I have some the experience in this area). Catching of such event during regular scans - seems even more difficult task.
But I'm sure that this is what werth to work on. At least it can be realised via syncthing-inotify utility (but core have to support such event).

**Comment by AudriusButkevicius** [comment] 2017-09-11 08:58
Syncthing already tries to handle this, though the problem is caused by index batching. @calmh was working on a graph puller that could have helped solve this, but it's not there yet. I am closing this as I think it's a dupe.in the meanwhile, copy, sync, delete, sync is the workaround.

**Closed by AudriusButkevicius** 2017-09-11 08:58 UTC

**Comment by slytomcat** [comment] 2017-09-11 09:00
Ok. Thanks!
