### ISSUE TITLE
Path assistant in Windows should not be case sensitive

### ISSUE THREAD

**Issue by bugith** [syncthing/syncthing#4126] opened 2017-05-03 12:15 UTC
v0.14.27 FF38 windows 32bits / FF52 win64
The path assistant on folder creation is case sensitive so that it won't trigger warnings for Parent/Children of existing share. More it won't assist at all when one starts **typing** some path with c:\ or d:\ like it does on ~ followed either with arrows keys or typing matching head of path.

**Comment by AudriusButkevicius** [comment] 2017-05-03 12:42
This is a duplicate of an issue that already exists I think.

**Comment by bugith** [comment] 2017-05-03 12:42
Sorry for the noise

**Comment by uok** [comment] 2017-05-03 13:20
see #1347

**Closed** 2017-05-03 14:09 UTC
