### ISSUE TITLE
panic: cannot start already running folder www

### ISSUE THREAD

**Issue by Aranjedeath** [syncthing/syncthing#5178] opened 2018-09-11 00:31 UTC
Hi, I tried to add a few folders from another node in quick succession (via webui). This resulting in syncthing losing its shit. It is now not usable, because it will not start. Well, it starts 4 times and then stops, that's the issue. 

https://explodie.org/panic-20180910-172441.log

That's my panic log. Let me know when somebody has read it and I'll remove the log. I'm sure there's all kinds of private info in it.

### Version Information

Syncthing Version: syncthing v0.14.48 "Dysprosium Dragonfly" (go1.11 freebsd-amd64) aranje[at]explodie.org 2018-09-05 04:31:10 UTC [noupgrade]
OS Version: FreeBSD 11.2-p2
Browser Version: Chrome, latest, KDE NEON.

**Comment by Aranjedeath** [comment] 2018-09-11 00:39
Short term solution is to nuke the configuration directory. Hopefully the log here is enough.

I love syncthing but "clicked buttons too fast" should not leave me with an unusable server.

**Comment by calmh** [comment] 2018-09-11 06:12
Duplicate of #5063

**Closed by calmh** 2018-09-11 06:12 UTC
