### ISSUE TITLE
Default listener only sends ULA addresses to Discovery, global addresses are not sent

### ISSUE THREAD

**Issue by uniquepurpose** [syncthing/syncthing#9184] opened 2023-10-25 18:37 UTC
### Does your log mention database corruption?
No.

### Include required information

Please be sure to include at least:

 - v1.25.0, Linux (64-bit Intel/AMD)
 - when using the "default" listener then only ULA addresses are sent to the discovery service.
 - when entering "tcp6://[20ad:123:234::1]:22000" then this IP is sent to the discovery service.
 - tested with https://discovery.syncthing.net/?device=(id)

This makes IPv6 connections over the internet impossible.

**Comment by calmh** [comment] 2023-10-25 18:44
Not impossible, as the source address the discovery server sees is used, same as for IPv4. This is by design, to avoid exposing potentially private internal addressing to the world.

**Comment by uniquepurpose** [comment] 2023-10-25 18:47
Hi @calmh, then there is something completely wrong. Here is the output of the query of the discovery service (removed public v4 addresses):

```
{
    "seen": "2023-10-25T18:30:12Z",
    "addresses": [
        "quic://172.17.0.1:22000",
        "quic://192.168.178.8:22000",
        "quic://[fd7a:115c:a1e0:ab12:4843:cd96:627e:437f]:22000",
        "quic://[fdcd:7a62:3430:0:1428:a8ff:fe49:1a7d]:22000",
        "tcp6://192.168.178.8:22000",
        "tcp6://[2a0d:3344:188c:1c00::305]:22000",
        "tcp6://[fd7a:115c:a1e0:ab12:4843:cd96:627e:437f]:22000",
        "tcp6://[fdcd:7a62:3430:0:1428:a8ff:fe49:1a7d]:22000",
        "tcp://172.17.0.1:22000",
        "tcp://172.17.0.1:33729",
        "tcp://172.17.0.1:35987",
        "tcp://172.17.0.1:36432",
        "tcp://172.17.0.1:36654",
        "tcp://172.17.0.1:36744",
        "tcp://172.17.0.1:36994",
        "tcp://172.17.0.1:37270",
        "tcp://172.17.0.1:37644",
        "tcp://172.17.0.1:37868",
        "tcp://172.17.0.1:37871",
        "tcp://172.17.0.1:38688",
        "tcp://172.17.0.1:38879",
        "tcp://172.17.0.1:38904",
        "tcp://172.17.0.1:41420",
        "tcp://172.17.0.1:42613",
        "tcp://172.17.0.1:43884",
        "tcp://172.17.0.1:44703",
        "tcp://172.17.0.1:45304",
        "tcp://172.17.0.1:48260",
        "tcp://172.17.0.1:49874",
        "tcp://172.17.0.1:50546",
        "tcp://172.17.0.1:50756",
        "tcp://172.17.0.1:51834",
        "tcp://172.17.0.1:52260",
        "tcp://172.17.0.1:52380",
        "tcp://172.17.0.1:52562",
        "tcp://172.17.0.1:52632",
        "tcp://172.17.0.1:52971",
        "tcp://172.17.0.1:53926",
        "tcp://172.17.0.1:54892",
        "tcp://172.17.0.1:55763",
        "tcp://172.17.0.1:58932",
        "tcp://172.17.0.1:59212",
        "tcp://192.168.178.8:22000",
        "tcp://[fd7a:115c:a1e0:ab12:4843:cd96:627e:437f]:22000",
        "tcp://[fdcd:7a62:3430:0:1428:a8ff:fe49:1a7d]:22000"
    ]
}
```

**Comment by bt90** [comment] 2023-10-25 18:49
This is odd, as the discovery server should at least maintain the public IPv6 used to publish the addresses.

Better IPv6 connectivity is partly addressed by #9010, since we'll be publishing addresses that we can open a pinhole for.

But I agree that an opt-in mechanism for publishing public IPv6 interface IPs would be nice.

> Not impossible, as the source address the discovery server sees is used

ULA addresses are not routed. They are comparable to private IPv4 addresses.

**Comment by bt90** [comment] 2023-10-25 19:03
> tcp6://192.168.178.8:22000


An artifact from manual listener configuration?

> tcp://172.17.0.1:33729

That looks like the result of a typical error loop in our current UPnP implementation. Also addressed by #9010

Is your device able to reach the global discovery server via IPv6?

**Comment by uniquepurpose** [comment] 2023-10-25 19:12
> > tcp6://192.168.178.8:22000
> 
> An artifact from manual listener configuration?

Could be, yes. Is there a way to remove all known addresses from the discovery service or will they eventually time out anyway?

> Is your device able to reach the global discovery server via IPv6?

Yes.
```
$ curl -v --insecure https://discovery.syncthing.net/?device=(id)
*   Trying 2a03:b0c0:0:1010::bb:4001:443...
* TCP_NODELAY set
* Connected to discovery.syncthing.net (2a03:b0c0:0:1010::bb:4001) port 443 (#0)
```

**Comment by bt90** [comment] 2023-10-25 19:31
Hmm. No public IPv6 addresses for my device either...

**Comment by bt90** [comment] 2023-10-25 19:46
I have had my eye on the low IPv6 usage at https://data.syncthing.net/ for some time. I thought these numbers might just be the sad reality after the fix for #8274. But we only publish public IPv6 addresses that are manually configured, or that are seen by the discovery server itself. If the discovery server mechanism didn't work, IPv6 connectivity would drop like a stone.

**Comment by calmh** [comment] 2023-10-25 20:03
No public IPv4 in that result above, either...

**Comment by calmh** [comment] 2023-10-25 20:14
I think this is a server side problem, since a recent update. Fixing that, first...

**Comment by calmh** [comment] 2023-10-25 20:18
I am now seeing public v6 addresses for my devices that have them, which I didn't before. In short, I had fucked up a Docker deployment of the discovery server...

**Comment by uniquepurpose** [comment] 2023-10-25 21:46
Hey, I can confirm that discovery service shows now much better data, including the correct IPv6 addresses. Thanks so much for fixing this so quickly. I have tried for hours on my end, reading firewall logs, etc. So glad that it works again.

I'm curious on how this fix will impact the "IP version (v3)" KPI in the Usage Reports.

Chapeau, @calmh and @bt90!

**Closed** 2023-10-26 06:06 UTC
Labels: bug
