### ISSUE TITLE
Add an option to make -logfile append instead of truncate

### ISSUE THREAD

**Issue by sbraz** [syncthing/syncthing#3936] opened 2017-01-25 22:33 UTC
Hi, would it be possible to add an option to make '-logfile' append to an existing file instead of of overwriting it? This would allow us to use logrotate and kill -HUP for proper log rotation.

**Comment by AudriusButkevicius** [comment] 2017-01-25 22:38
-logfile shouldn't even exist on Linux, it exists solely for windows.
If you want log rotation and what not, redirect stdout, that's my view.

**Comment by sbraz** [comment] 2017-01-25 23:02
Well we at Gentoo currently use SSD to capture stdout and it works fine. But we can't rotate the log without stopping and restarting the process.
I guess this isn't a problem for systemd but for other init systems, but don't you agree that restarting a whole daemon just to rotate its logs is a bit overkill (I'm not mentioning copytruncate at all because it's even worse IMO)?

**Comment by AudriusButkevicius** [comment] 2017-01-25 23:15
If you are capturing stdout, I don't really see how log rotation issues are caused by syncthing?

**Comment by sbraz** [comment] 2017-01-25 23:42
> If you are capturing stdout, I don't really see how log rotation issues are caused by syncthing?

I am doing it because syncthing doesn't handle logging on its own so it's not directly syncthing's fault.

>I mean, you can pipe stdout to some other process/pipe that handles log reopening?

I don't know any standard tool that does that (apart from systemd and journald, or course). Maybe we could use syslog though?  I never thought about going down that road but it might be possible.
> I mean imagine -logfile was not there, what would you do?

The same thing I currently do, that doesn't mean -logfile can't be improved :P

Anyway, it's no big deal. You can close this issue if you want to.

**Comment by calmh** [comment] 2017-01-26 07:07
There's been lots of discussion about logging over the years. To summarize, my/our opinion is that,

- Logging is a stream and you should handle it as such.
- We log to stdout, because handling logging is system specific and not our concern.

Popular choices in the Unix world are to let systemd grab the output (you can have your opinions on how well systemd does this...), let whatever other service manager grab the logs (launchd on Mac, SMF on Solaris does this by default), or pipe the output to `logger` to get it into syslog.

The -logfile option was added because on Windows all of these options are nonstandard and painful.

Rotation can be done by time, by size, with compression, in however many iterations and so on. We will never support them all.

*Although* we do support log rotation by closing and reopening. So you can in fact just rotate the logfile and Syncthing will act accordingly. Maybe this solves your case already.

**Closed by calmh** 2017-01-26 07:07 UTC
