### ISSUE TITLE
Multiple GUI listen addresses

### ISSUE THREAD

**Issue by Unrud** [syncthing/syncthing#3723] opened 2016-11-11 10:13 UTC
Syncthing only supports one listen address for the GUI.

[Documentation](https://docs.syncthing.net/users/config.html#gui-element):

> Set the listen addresses. One or more address elements must be present. Entries must have the protocol prefix tcp://.

The part with the prefix is also wrong.

Settings dialog in the GUI:

> GUI Listen Addresse**s**:

Is the documentation and GUI wrong or should Syncthing actually support multiple listen addresses (with protocol prefixes)?

**Comment by ProactiveServices** [comment] 2016-11-11 10:35
Syncthing fatals when the tcp:// prefix exists:
`FATAL: Starting API/GUI: listen tcp: too many colons in address tcp://localhost:22402`

And when more than one address exists:
`FATAL: Starting API/GUI: listen tcp: too many colons in address localhost:22402, localhost:22403`

I think earlier in the year, Syncthing was updated with regards to how protocols and addresses are handled internally, and this part of the code might have been missed. The documentation represents how addresses are used everywhere else, so I suspect the docs are "correct".

**Comment by AudriusButkevicius** [comment] 2016-11-11 10:59
No, address specification applies only to BEP protocol addresses.
Whats the usecase here?

**Comment by canton7** [comment] 2016-11-11 11:14
The issue is a docs one I think: [the docs](https://docs.syncthing.net/users/config.html) say that the GUI listen address is the same format as the other addresses (with the `tcp://` prefix, etc), which is untrue.

**Comment by AudriusButkevicius** [comment] 2016-11-11 12:02
Indeed, it makes mostly no sense to export ui over anything else apart from TCP . Pls open an issue on the docs repo. I am keeping this open to hear the usecase.

**Comment by Ferroin** [comment] 2016-11-11 12:31
#3616 kind of relates, and if that ever does get implemented (and any argument for or against that should be in _that_ issue, not here), then there needs to be some way to differentiate TCP versus UDS sockets, although it doesn't necessarily need to be a URL style prefix (it could just be matching on a leading / in the listen address).

**Comment by Unrud** [comment] 2016-11-11 13:13
> Whats the usecase here?

I was also thinking about #3616. ``net.Listen`` already supports unix domain sockets, that issue would be solved very easy.

What about multiple addresses? Otherwise it's impossible to have the GUI available via ipv4 and ipv6.

**Comment by Ferroin** [comment] 2016-11-11 13:28
I think we already listen on all addresses if you make the element empty, which includes IPv4 and IPv6, the problem arises when you want to listen on a specific set of addresses (not just IPv4 vs IPv6).

Think of a NAT router running Syncthing.  Depending on how it's configured, it's not unreasonable to listen both on the loopback interface (so that local tools can talk to it easily with low overhead) and whatever the internal network interface is, but you absolutely do not want to listen on the external interface because it's a severe security hazard even if you have authentication and SSL set up.

As another example, I've got a home server system running a bunch of VM's on an isolated network separate from the rest of my home network.  I run Syncthing on this system, and would love to be able to control it from my laptop while on my home network, while still being able to control it from the server itself, but I absolutely do not want the Vm's to be able to control it.

Currently, the only way to do this is to proxy Syncthing through an external program which adds unneeded complexity as well as increasing the overall attack-surface of the system (put differently, I shouldn't have to run a web server just to get Syncthing to listen on only 2 out of three interfaces).

**Comment by Ferroin** [comment] 2016-11-11 13:31
Correction, you could also technically use firewall rules, but that's pretty error prone and very much non-trivial to set up on most systems.  Currently, this is what I'm doing in the situation I listed above, but I'd really rather have proper support for multiple listen addresses in Syncthing.

**Comment by AudriusButkevicius** [comment] 2016-11-11 14:23
So you can already bind to v4 or v6 or both so i don't buy that. Yes, unix sockets agtee, but is there any other usecase for this?

**Comment by Unrud** [comment] 2016-11-11 14:36
> So you can already bind to v4 or v6 or both so i don't buy that.

For example it's not possible to bind to ``[::1]:8384`` and ``127.0.0.1:8384`` at the same time.

> Yes, unix sockets agtee, but is there any other usecase for this?

No. The format of addresses would be the same everywhere.

**Comment by calmh** [comment] 2016-11-11 14:51
> For example it's not possible to bind to [::1]:8384 and 127.0.0.1:8384 at the same time.

This is legitimate, but I think unimportant compared to the potential complexity.

**Comment by Ferroin** [comment] 2016-11-11 15:04
I'd argue that while it's unimportant for the loopback interface , it becomes important when you're dealing with exposing the GUI on a dual-stack network, since you can't assume that any arbitrary client will be able to access it over one protocol or the other.

**Comment by spectras** [comment] 2016-11-11 16:26
For what it's worth, I gave a shot at working on #3616 a few days ago and came to the conclusion that the ability to start multiple GUI handlers would be a great enabler. Unfortunately I never touched Go in my life so it makes navigating the language and the library that comes with it tricky.

**Comment by calmh** [comment] 2016-11-11 19:21
I think most people wanting to expose the interact to the network, dual stack or not, would simply listen on the wildcard address. That covers both IPv4 and IPv6.

**Comment by Ferroin** [comment] 2016-11-11 19:57
I've seen a pretty significant number of people who run Syncthing on a router, and if you even remotely care about security, you absolutely _do not_ want to have the GUI listening on the external interface.  In such a situation, you can't use a wildcard address, which in turn means that you are stuck with v4 or v6 as things stand now, which in turn means that stuff like mDNS or LLMNR won't work reliably to get to the GUI (if you want specifics on why mDNS and LLMNR aren't reliable in such a situation, I'll be happy to explain, but it's kind of off-topic).

I also don't entirely agree that it's required to support UDS.  The primary use cases for that as outlined in #3616 (and really the only practical reasons for it) are to either use only local scripts and CLI tools to control it, or to expose it through a separate proxy (like nginx) without the full network overhead, both with improved security relative to listening on the loopback interface.  In both cases, you don't need to have more than one listening socket (in the first one you don't need the GUI at all, and the second it _has_ to be served over the UDS connection with the REST API, otherwise the proxying won't work).  I can see having it listen both on a UDS and a TCP port would be useful for debugging, but doing that also completely eliminates all security benefits from using UDS in the first place, so I'd say that the common case for people using that is going to probably be just listening on a single UDS and nothing else.

**Comment by AudriusButkevicius** [comment] 2016-11-11 19:59
Anywyas, this would have to be delivered by #3616, closing.

**Closed by AudriusButkevicius** 2016-11-11 19:59 UTC

**Comment by Unrud** [comment] 2016-11-12 03:57
> Anywyas, this would have to be delivered by #3616, closing.

I don't really care if this gets implemented or not but the label in the GUI is still wrong.
