### ISSUE TITLE
Allow folders or individual files to be downloaded on demand. (Hydrate/Dehydrate)

### ISSUE THREAD

**Issue by Simpler1** [syncthing/syncthing#8845] opened 2023-03-30 18:27 UTC
Many file synchronization products (OneDrive, Dropbox, etc.) have the option to set a folder or even individual files to only sync on demand.  This means that one device would hold the file and a second device would know about the file, but would only have a placeholder or stub of the file.  The second device could then "hydrate" the file on demand if they wanted to open it.

The file would then stay synchronized as normal unless the user then specified that file be "dehydrated" to turn it back into a placeholder.

This would help on devices (such as phones) with limited disk space to still be able to access any of the files in the synchronized folder.

**Comment by er-pa** [comment] 2023-03-31 10:52
Now, correct me if I'm wrong but, this is not really synchronising? The whole point of a pure sync product, like Syncthing, is to have an equal (with exceptions) state on several devices. If you are going to work with placeholders and only load files on demand, then this whole concept gets thrown overboard.

I'm not saying that it's not useful for certain devices, but I'm not sure that Syncthing is the tool for this type of job.

**Comment by bt90** [comment] 2023-03-31 10:54
Duplicate of #193 ?

**Comment by tomasz1986** [comment] 2023-03-31 11:06
> Many file synchronization products (OneDrive, Dropbox, etc.)

I think it's literally only OneDrive and Dropbox. They achieve this by a very tight integration with the filesystem, and only on a few selected operating systems.

**Comment by imsodin** [comment] 2023-03-31 11:25
This can absolutely be done with the BEP (syncthing's protocol)/compatible with syncthing. There are two discontinued projects that basically did something very similar I am aware of:  
Fuse based filesystem implementation: https://github.com/burkemw3/syncthingfuse
Java implementation of BEP with the goal of an on-demand android app: https://github.com/syncthing/syncthing-lite

And that's also were it's at: This is out of scope for syncthing itself. I'd be super exited if anyone were to give it another push at developping such a solution!

**Closed by imsodin** 2023-03-31 11:25 UTC
Labels: enhancement, needs-triage

**Comment by escape0707** [comment] 2023-10-23 08:18
I think most of the time this could be worked around by using an SFTP or Nextcloud on one of your best available Syncthing devices. But yeah, they don't come with a distributed / p2p model in mind.
