### ISSUE TITLE
Grouping of shared folders

### ISSUE THREAD

**Issue by Kedryn** [syncthing/syncthing#9418] opened 2024-02-14 09:58 UTC
### Include required information

The ability to organize group of shared folders, for easier and cleaner interface
The group can be collapsed or minimized, showing only it's name.

**Comment by tomasz1986** [comment] 2024-02-14 10:03
Duplicate of https://github.com/syncthing/syncthing/issues/2070.

**Closed by tomasz1986** 2024-02-14 10:03 UTC
Labels: enhancement, needs-triage
