### ISSUE TITLE
Invalid filenames (Windows) shouldn't be retried indefinitely

### ISSUE THREAD

**Issue by xCapRx** [syncthing/syncthing#4562] opened 2017-11-30 04:36 UTC
Hello. It seems like the issue is mainly Windows 10. It doesn't like special characters like | / ? " etc. Can this be fixed so these characters are automatically deleted when syncing between devices? I recently got someone to write a script for me which helps me save pictures in Windows 10 by replacing the incompatible characters with compatible ones . Unfortunately, this has only exacerbated my sync problem so it's difficult for me to show a log of the original problem. For whatever it's worth though, here is a sample of my log: 

```
[XFMQ3] 21：14：12 INFO： Puller (folder ''＼''Backgrounds＼'' (fbqpg-6j81c)'', file ''Anyone up for some coffee？'')： need： filename is invalid
[XFMQ3] 21：14：12 INFO： Puller (folder ''＼''Backgrounds＼'' (fbqpg-6j81c)'', file ''Oh so y'all doing Datsuns huh？ How about this Datsun 240z？ [1023×680]'')： need： filename is invalid
[XFMQ3] 21：14：12 INFO： Puller (folder ''＼''Backgrounds＼'' (fbqpg-6j81c)'', file ''Shot last year during a foggy morning in ＼''Exotenwald＼'' Weinheim (Germany)[OC][1620x1080]'')： need： filename is invalid
[XFMQ3] 21：14：12 INFO： Puller (folder ''＼''Backgrounds＼'' (fbqpg-6j81c)'', file ''So f∗cking true'')： need： filename is invalid
[XFMQ3] 21：14：12 INFO： Puller (folder ''＼''Backgrounds＼'' (fbqpg-6j81c)'', file ''Wildlife Photography Workshops ∣ BSOP(1024 × 683)'')： need： filename is invalid
[XFMQ3] 21：14：12 INFO： Puller (folder ''＼''Backgrounds＼'' (fbqpg-6j81c)'', file ''Winston's shield needs a ＼''health＼'' indicator like Reinhardt and Orisa'')： need： filename is invalid
[XFMQ3] 21：14：12 INFO： Folder ''Backgrounds'' (fbqpg-6j81c) isn't making progress. Pausing puller for 1m0s.
[XFMQ3] 21：15：12 INFO： Puller (folder ''＼''Backgrounds＼'' (fbqpg-6j81c)'', file ''Anyone up for some coffee？'')： need： filename is invalid
[XFMQ3] 21：15：12 INFO： Puller (folder ''＼''Backgrounds＼'' (fbqpg-6j81c)'', file ''Oh so y'all doing Datsuns huh？ How about this Datsun 240z？ [1023×680]'')： need： filename is invalid
[XFMQ3] 21：15：12 INFO： Puller (folder ''＼''Backgrounds＼'' (fbqpg-6j81c)'', file ''Shot last year during a foggy morning in ＼''Exotenwald＼'' Weinheim (Germany)[OC][1620x1080]'')： need： filename is invalid
```

Thanks.

**Comment by calmh** [comment] 2017-11-30 06:58
This is roughly working as intended - files which are not possible on Windows can't be synced to Windows, and we will not automatically replace the characters.

However, it should realise this and not retry them indefinitely. That's a bug. (But will not help you with your issue, so go ahead and rename those files anyway.)

**Comment by imsodin** [comment] 2017-11-30 11:32
That was actually a deliberate decision in the recent invalidation PR: symlinks on Windows are marked as invalid and thus not retried, while invalid file names aren't. The reason was that filenames can be fixed by the user, while symlinks cannot as we simply don't support them.
I am not sure what is the right thing to do here.

**Comment by calmh** [comment] 2017-11-30 12:13
Some time way back we issued a warning at index receive time and then ignored them.

**Comment by calmh** [comment] 2017-12-25 19:46
@imsodin Your #4607 didn't happen to fix this, did it?

**Comment by imsodin** [comment] 2017-12-25 23:23
It didn't, but #4340 made it at least less problematic: Interval between unsuccessful pulls increase exponentially up to 1h.

I guess we could differentiate between errors which could be solved by trying again and others like this (maybe there is more?) that could not. However I certainly don't think it is a pressing issue, as these pulls happen so infrequently, and it might not even warrant the additional complexity of handling two types of errors.

**Comment by nekr0z** [comment] 2018-01-24 13:38
> I guess we could differentiate between errors which could be solved by trying again and others like this (maybe there is more?) that could not.
Just in case you were wondering: there's at least one other similar case: ecfyptfs on Linux limits filename length, so a file with a name too long for ecryptfs (but short enough for EXT4, NTFS, etc. so that it exists elsewhere in the cluster) is not pulled but retried every time. Not a huge issue with increasing intervals, and current (as of 0.14.43) UI gives user enough information on the situation.

**Comment by jyf007** [comment] 2018-02-07 02:58
How about rename ? as %9E ?

**Comment by canton7** [comment] 2018-02-07 11:53
There was a previous issue somewhere discussion potential approaches. I don't want to repeat it here, but the problem with turning `foo?` into `foo%9E` is avoiding `foo%9E` from being synchronized back, meaning you end up with both `foo?` and `foo%9E` on the original device. The solutions to that start getting hard.

**Comment by belgacea** [comment] 2018-03-14 15:30
I've seen some sync bugs with files whose names contain spaces or some files with case sensitive names.

**Comment by canton7** [comment] 2018-03-14 16:00
@belgacea if you have details, the forum is the appropriate place to present them.

**Comment by xgdgsc** [comment] 2018-06-27 01:34
Although from the log I can see the puller pausing time increases exponentially. The syncthing process still takes constant 100% of one core of CPU on windows. What could be the reason? How to debug this?

**Comment by calmh** [comment] 2018-06-27 05:56
Discuss it on the forum, please.

**Comment by imsodin** [comment] 2018-08-03 07:07
Since #5066 pulling is not retried only for invalid filenames. They still show up as failed items and if there is a different change, causing a pull, the error will be renewed. That's actually fine this way, I don't want to totally bury this problem, it should be visible to the user.

**Closed by imsodin** 2018-08-03 07:07 UTC
Labels: bug
