### ISSUE TITLE
Customized temporary file directory, unified storage of temporary files during the synchronization process

### ISSUE THREAD

**Issue by wobure123** [syncthing/syncthing#9570] opened 2024-06-08 12:56 UTC
### Feature description

Ability to customize save directory parameters for temporary files

### Problem or use case

Currently syncthing can achieve one end for webdav mounted virtual folder synchronization, but there will be bugs, if you can customize syncthing's temporary folder, you can use the hard disk as a temporary file, isolating the temporary file with the  official file, this isolation can prevent the davfs2 cache file and syncthing temporary files from  running into conflicts, and allows syncthing to gracefully synchronize webdav-mounted virtual disks.

### Alternatives or workarounds

none

**Comment by calmh** [comment] 2024-06-08 14:19
Duplicate of #2208 I think

**Closed by calmh** 2024-06-08 14:19 UTC
Labels: enhancement, needs-triage

**Comment by wobure123** [comment] 2024-06-08 14:26
I check the source code, since atomic operation is needed, it maybe hard to change the directory of temp file. The bug I came across in synchnizing a webdav type folder is: for instance a new 50 MB test.txt is added in the other machine, soon ,Syncthing begins to work, a downloading is started, temp file .syncthing.test.temp is created and soon finished, since  I use davfs2 mount  webdav file , there is also a .syncthing .test.temp created in davfs2 cache diretory, everything is fine, But aside with the temp file,there is a Target file  text.txt   also in the davfs2 cache diretory, and..., it is cycling from 0 MB to 50MB, the network is taken over by it, and syncthing is stuck in downloading the file, even though,the total temp file is already in there. It is so weird....
