### ISSUE TITLE
Feature request: Option for maximum folder size

### ISSUE THREAD

**Issue by eritbh** [syncthing/syncthing#8132] opened 2022-01-20 20:10 UTC
As a complement to the existing "Minimum Free Disk Space" option, I'd also like an option for limiting the amount of disk space which can be used by individual folders.

This would be useful for those who want to reserve a limited amount of space on their systems for others to use as a backup target. For example, if a friend wants to use my computer as an offsite backup for her Syncthing folder, I could set a limit on the amount of data synced to my computer from hers. If her folder size ever exceeds that limit, syncing to my computer would stop, allowing me to review the limit and take action as necessary rather than having the folder continue to grow and take up space on my system.

I found [a forum post about this from 2019](https://forum.syncthing.net/t/option-maximum-disk-size-per-folder/13581) which had some discussion. A workaround suggested there is to create dedicated partitions of the desired size and sync folders there, but this feels a bit clunky, and it isn't possible everywhere. For example, I run a Syncthing docker instance on an unRAID system, and unRAID (as far as I know) doesn't have an effective mechanism for limiting the size of a share. The "Minimum Free Disk Space" option can't be used for this use case since the limit would be influenced by the size of other folders which I may want to allow to grow indefinitely.

Ideally it would be presented similarly to the existing minimum free disk space option, allowing the user to select a percentage of the disk's total space or an absolute file size in kB/MB/GB/TB. The two options should also be able to work together, so a folder would stop syncing if it reaches its absolute size cap *or* if it starts to encroach on reserved free space. While there is a global version of the minimum free disk space setting that applies to the home disk, I'm not sure if it would be appropriate to implement any sort of global setting for maximum folder size - it would probably be better to just make it a per-folder setting.

**Comment by imsodin** [comment] 2022-01-20 20:36
Duplicate of https://github.com/syncthing/syncthing/issues/4244

**Closed by imsodin** 2022-01-20 20:36 UTC
Labels: enhancement, needs-triage
