### ISSUE TITLE
Index Exchange Bug: Ghost files leading to permanent out-of-sync on single device

### ISSUE THREAD

**Issue by bentolor** [syncthing/syncthing#9624] opened 2024-08-03 10:14 UTC
Thank you for this awesome tool! Nevertheless, Syncthing seems to expose a singe and probably simple bug breaking the sync functionality and I'd like to see if I can support to identify & resolve this bug for a more reliable UX.

### What happened?

For full context, please [refer to my forum entry](https://forum.syncthing.net/t/bug-remote-device-reports-10gb-outstanding-sync-vs-up-to-date-everywhere-else-empty-changes-popup/22437/)

*    Only my mobile (ben@s21) reports in the “Remote Devices” view 10GB outstanding sync.
     * Clicking on the “Out of Sync: 3 items, 10,6GB” link provides an empty popup.
*    “Folders” list view on all devices are all “Up to Date”
*    Also “Remote devices” list on other end (ben@neptun) is “Up to Date”.
*  Global state reports `6 files 0 directories ~21,3GB` on S21 vs. `3 files 0 directories ~10,7GB` on neptun. 
* Only these two devices are involved. They are also online & connected to each other.

I can pretty sure tell, where Synchthing is wrong: The shared folder syncs Signal messenger backup files between mobile and desktop. Those files are ~5,2GB in size, created every day on S21, and only the last two are kept on the mobile by Signal.

My guess: so obviously this situation seems to occur, when a file is deleted while it is in transfer. In my case the mobile phone one syncs i.e. at home WLAN. To me it seems that the sender site (S21) tries to keep track of a file which has vanished on sender site.

I’m now experiencing more or less the exact same situation with another Syncthing folder& device combination. There: 400b outstandinge due to a renamed `.stignore-custom-file`.

Any idea how I can help to further spot/identify the problem? Or at least how to easily reset the wrong sync data?

#### neptun view
![image](https://github.com/user-attachments/assets/86801083-1af4-4c0e-8569-5549ee5fce94)
![image](https://github.com/user-attachments/assets/6706a5a9-af8e-43c0-a7be-ab58ee0cb3a3)

#### S21 view
![image](https://github.com/user-attachments/assets/62bf9c10-0670-47bd-951e-182f90e4db46)
![image](https://github.com/user-attachments/assets/db88e905-f339-4d43-ae50-ebe496edf164)
![image](https://github.com/user-attachments/assets/b804e44c-fae4-4498-95ce-1864626752e7)

### Syncthing version

v1.27.9

### Platform & operating system

Android & Linux

**Comment by tomasz1986** [comment] 2024-08-03 12:14
The global state looks doubled, so I think the issue may somehow be related to https://github.com/syncthing/syncthing/issues/8416.

**Comment by bentolor** [comment] 2024-08-03 12:20
@tomasz1986 Yes, can confirm this could be. But not with a 3rd device involved: Instead I might have accepted, removed, and then re-accepted the shared folder on `neptun`-Side.

But don't give too much on the "doubled" size: This directory always only contains two 5,x GB files. In the other case I have a single ghost file only a few bytes large and part of a much larger set showing a similar/identical behaviour.

**Comment by tomasz1986** [comment] 2024-09-06 10:17
Closing as duplicate of https://github.com/syncthing/syncthing/issues/8018 (ghost files stuck in sync) and https://github.com/syncthing/syncthing/issues/8416 (doubled global state).

**Closed by tomasz1986** 2024-09-06 10:17 UTC
Labels: bug, needs-triage
