### ISSUE TITLE
Tool-support for interactively ignoring things to avoid data loss

### ISSUE THREAD

**Issue by novoid** [syncthing/syncthing#4196] opened 2017-06-05 07:48 UTC
The number one goal of Syncthing is: **Safe From Data Loss**

I do see a usability/method issue. Please bear with me as I do have to give an example situation for this somehow subtle issue:

1. Given is a "master" Syncthing node that holds a repository `MYREPO` with the files/folders `A`, `B`, and `C`.
2. A new "client" Syncthing node on a different device gets this `MYREPO`, resulting in `A`, `B`, and `C` synced in the initial process.
3. Relevant for this new "client" is only repository `A`. Therefore, the users decides to add `B` and `C` to the `.stignore` file and then deletes `B` and `C` from the "client".

Here comes the pain point: when the user did a mistake (simple typo, not used to RegEx that much, not used to Syncthing ignore patterns that much,...), `B` and/or `C` gets removed from the "master". **This results in data loss**, if the "master" is not configured to do any versioning.

- Even with using versioning, the mistake has to be detected soon in order to be un-done immediately.
- The user might lose data and decides not to use Syncthing any more because she/he feels uncomfortable for the future.

> If you need a real-world example: I do have one Syncthing repository that holds configuration files for all of my hosts. On most hosts, I prefer to have the complete repository (disk space does not matter) but on some hosts, I prefer to sync only the host-specific folder(s). I don't want to split the repository in multiple repositories since "sync all" is the default case and I have (too?) many Syncthing folders already (causing poor overview).

Issues:

Possible workarounds:

1. Feature:
    - When activated, the user is able to delete (and add) files/folders to a Syncthing node
    - Then the user confirms the status
    - Now Syncthing itself adds all changes as ignore-cases to the `.ignore` file so that no synchronization is necessary: when all files of a sub-folder are "affected", (optionally) add the folder to the `.ignore` file instead of the sum of all file names
    - Syncthing deactivates the feature
2. Feature: a `.ignore` file generator that visualizes, what parts of the local Syncthing repository gets affected how before anything got synced/deleted.
3. _Your proposals_ -> there might be even better workaround or even solutions for this issue

> I was using the Unison File Synchronizer for decades, before I fond Syncthing. This issue is solved rather elegant within Unison. When I delete files and manually re-start Unison for this repository, I get an overview what will be done when I confirm the situation. I am able to override the choices (e.g., I deleted a file by mistake and reverse the sync-direction to re-create the file) or adapt the ignore file by pressing a keyboard shortcut and the corresponding item gets added to the ignore file. As you can see, this is somehow similar to the first feature I described above. Therefore, I never had this issue with Unison.

**Comment by AudriusButkevicius** [comment] 2017-06-05 08:08
This is equivalent of accidentally deleting a directory you did not intend to delete. We can't protect people from every mistake they will ever make. There are already plenty of ways to combat this if you are clumsy, such as versioning, send only folders and so on.

There is a large ticket explaining what the new ignore system should look like that I think we can call this ticket duplicate off.

**Closed by AudriusButkevicius** 2017-06-05 08:08 UTC

**Comment by novoid** [comment] 2017-06-05 08:22
Can you provide a link to the "large ticket explaining what the new ignore system should look like"? I could not locate it by myself.
Thanks!

**Comment by AudriusButkevicius** [comment] 2017-06-05 08:28
#2491

**Comment by novoid** [comment] 2017-06-05 08:41
Thanks. This does seem to address my issue.
