### ISSUE TITLE
Logging/systemd defaults in the official debian package are not sane

### ISSUE THREAD

**Issue by graboluk** [syncthing/syncthing#2326] opened 2015-09-28 23:15 UTC
After about 24 hours of running st, my syslogs on all four machines which run it are in excess of 150MB of logdata generated by st. This is not sane.

Most of the messages are related to the comment I made on the issue Sync missing files #2211. That is: st very often gets out of sync, and can't get back to sync by itself. I think it's unreasonable to expect that a user will hunt the offending files and manually delete them, hence st keeps adding messages of the sort 

`Sep 29 00:02:32 archimedes syncthing[592]: [WUZ2F] INFO: Puller: final: stat /home/luke/Sync/sync-config/luke/.config/syncthing: no such file or directory`

to its stderr or stdout, and in the provided configuration systemd logs all of them to /var/log/syslog

(Of course the real issue is why does st get out of sync so often...)

**Comment by AudriusButkevicius** [comment] 2015-09-28 23:45
You seem to be syncings own home directory, potentially coorupting the database.

**Comment by graboluk** [comment] 2015-09-28 23:57
Come on, have some faith in people. I'm not doing it. I'm linking items of my choice from ~/Sync/sync-config/luke/.config/ to  ~/.config.  

syncthing folder is obviously not one of them. Therefore I don't need it to have in sync-config, therefore  I deleted it before it got synced across devices to save time. And this got st to get "out of sync" again.  At no point there was any database corruption possibility. 

The "out of sync" incidents  happen for me  in the situations when I delete files which have not yet been distributed to all devices, as I tried to make clear also in Sync missing files #2211.

**Comment by AudriusButkevicius** [comment] 2015-09-29 07:01
Thats fine. I was just pointing out a potential issue.

**Comment by calmh** [comment] 2015-11-19 13:08
We don't actually include any systemd stuff in the Debian packages. We do have some in the repo here though which I assume is the affected stuff. I guess stdout does get saved to /var/log/syslog by default? That's fine as I see it - possible the issue here could be that we're logging too much, but I don't think this is related to the defaults of the Debian package. Closing as I don't see anything actionable here, but feel free to clarify otherwise.

**Closed by calmh** 2015-11-19 13:08 UTC

**Comment by rumpelsepp** [comment] 2015-11-19 13:11
>  guess stdout does get saved to /var/log/syslog by default?

It goes to the journal `/var/log/journal`.

**Comment by graboluk** [comment] 2015-11-19 13:29
calmh of course it's fine by since I've already changed the defaults to suit me.

Are you sure the syslog service files are not shipped in the package? This seems to be the case as of 0.11.25, and these are the files which should be changed to avoid logging stdout

In any case, I think its's absolutely crazy that I've had ___150MB___ syslog after running syncthing for 24h.

**Comment by calmh** [comment] 2015-11-19 13:42
No, you're right, we *do* ship the systemd service, and systemd of course takes care of loggging by default. My bad.

That said, that part is fine. The part that possibly isn't fine is that we log too much data. On the hand we need to log failures somewhere, or it's impossible to figure out what's going on. Only log it with -verbose logging level? Maybe.

**Comment by graboluk** [comment] 2015-11-19 13:50
Frankly I don't remember what was in that syslog, but I believe it actually was entire stdout, which is not really "failures". If I had 150Mb syslog which happened to be filled by failure info generated by syncthing I'd not complain.

**Comment by wweich** [comment] 2015-11-19 13:57
Just as a reference: My Syncthing log file has 3.5MiB (24200 lines) after 2 months.

**Comment by calmh** [comment] 2015-11-19 14:30
@graboluk  It is a failure though, as the thing above is either caused by a bug or a weird situation syncthing doesn't know how to handle (i.e. a bug).
