### ISSUE TITLE
Syncthing update to 1.16 fails on Debian Bullseye

### ISSUE THREAD

**Issue by daniel-s** [syncthing/syncthing#7632] opened 2021-05-05 00:27 UTC
### Does your log mention database corruption?

No

#### OS version and setup

$ cat /etc/debian_version 
bullseye/sid

$ cat sources.list.d/syncthing.list 
deb https://apt.syncthing.net/ syncthing stable

#### What happened

An apt upgrade produces the following output:

Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
All packages are up to date.
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Calculating upgrade... Done
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
1 not fully installed or removed.
After this operation, 0 B of additional disk space will be used.
Setting up syncthing (1.16.0) ...
dpkg: error processing package syncthing (--configure):
 installed syncthing package post-installation script subprocess returned error exit status 1
Errors were encountered while processing:
 syncthing
needrestart is being skipped since dpkg has failed
E: Sub-process /usr/bin/dpkg returned an error code (1)

#### What was expected

Not that error message.

Note that Syncthing does in fact appear to be v1.16, so the upgrade appears to have worked, but the above error is received, even after repeating the upgrade. I do not know the previous version from which I am upgrading, but unless there have been multiple releases in the last few weeks, it's whatever the previous version was.

**Comment by rednessreliever** [comment] 2021-05-05 06:40
Similar output on Pop!_OS/Ubuntu 20.10:

```
Reading package lists... Done
Building dependency tree       
Reading state information... Done
syncthing is already the newest version (1.16.0).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
1 not fully installed or removed.
After this operation, 0 B of additional disk space will be used.
Do you want to continue? [Y/n] y
Setting up syncthing (1.16.0) ...
dpkg: error processing package syncthing (--configure):
 installed syncthing package post-installation script subprocess returned error exit status 1
Errors were encountered while processing:
 syncthing
E: Sub-process /usr/bin/dpkg returned an error code (1)
```

**Comment by imsodin** [comment] 2021-05-05 06:50
Duplicate of https://github.com/syncthing/syncthing/issues/7628

**Closed by imsodin** 2021-05-05 06:50 UTC
Labels: bug, needs-triage
