### ISSUE TITLE
Option to do not push delete file

### ISSUE THREAD

**Issue by sphinx02** [syncthing/syncthing#1254] opened 2015-01-14 16:36 UTC
When e.g. syncing the camera folder of my mobile-phone to my pc it would be nice to have an option (in addition to "Folder Master") to stop my mobile-phone from deleteing files on my pc (maybe called "Do not push deleted files"). It should be only activateable when "Folder Master" is already activated, else it makes no sense, as the deleted file will be synced back immediately. This would result in some kind of one way sync from phone to pc.

The target is to
 - Sync camera folder from phone to pc (<b>given</b> base functionality of syncthing)
 - Delete unneeded subfolders on the pc but do not sync these changes to the mobile-phone (<b>given</b> by activation of "Folder Master" on the phone)
 - Be able to clean up phones images without delete them on the pc (this is the <b>missing feature</b> which in addition to "Folder Master" should be as easy as stopping the phone's syncthing from pushing the file delete to the pc)

**Comment by rumpelsepp** [comment] 2015-01-14 16:39
Yeah this one would be nice.

**Comment by AudriusButkevicius** [comment] 2015-01-14 17:07
Yeah, but it's not that easy though, because if you deleted the file, and no other node has it, it could never go back to 100% in sync, so you cannot just not send deletes.

**Comment by AudriusButkevicius** [comment] 2015-01-14 17:10
Though this is a duplicate of #62

**Comment by calmh** [comment] 2015-01-14 17:11
By itself, this kind of makes sense. But after a while, you end up in the situation where

PC has
 - FileA
 - FileB
 - ~~FileC~~ deleted
 - ~~FileD~~ deleted

Phone has
 - ~~FileA~~ deleted
 - ~~FileB~~ deleted
 - FileC
 - FileD

100% in sync! But nothing is the same. I'm confused. :( And what happens when a file on the phone, that has been deleted on the PC, is updated on the phone? Does the update override the delete? Or the file stays deleted...?

**Comment by sphinx02** [comment] 2015-01-14 17:22
Hm I thought the use-case is clear, I simply want to have all pictures from my phone to my pc. But if I clean up the folder on my phone I dont want that the fotos are also deleted on my pc. Also if I delete e.g. some unneeded thumbnail-folders on my pc I dont want my pc to delete them on the mobile phone.

The option "Folder Master" is already given, so I can easily delete the thumbnail folder but if I at the moment clean up the camera-folder on my mobile phone, the files get also deleted on my pc which is what I dont want. So to do this, for me its as easy as do not push the delete to the pc. The phone is simply doing as it have never had the file. For the phone it is the same as if I delete a file on the pc and then copy it back on the pc (but because of the "Folder Master"-option it is not synced back to the phone).

And for the file that is updated on the phone: I dont know, how is it handled at the moment? This does not depend on the new feature, or? So this situation is also possible with the "Folder Master" option enabled...!?

**Comment by calmh** [comment] 2015-01-14 17:48
No, it's more complicated than the folder master option, because this prevents sync in both directions. It's "easy" to just sync one way. It's more difficult to not sync both ways. :) The way sync works currently is that each file has a version number that increases. For example version=5 can contain some data, version=6 can be the deleted version. If a machine has version 5, it knows it should go up to version 6 and delete the file. But if we ignore the delete, and then create a new file in the same place - is that a new file, newer than the delete we ignored? If we ignore version 6 (the delete) and keep version 5, but there is then a version 7 with other content, should we sync to that? What if we manually deleted the file after ignoring the delete...?

Point being, it's tricky. :) At this point, too tricky for this special case I think. If you or someone else wants to iron out all the details though, I won't be against it.

(I don't think is an exact duplicate of #62 though, that's something slightly different.)

**Comment by AudriusButkevicius** [comment] 2015-01-14 17:48
To be honest, you can already achieve a similar behaviour with versioning enabled, as at the point you delete a file it gets archived preserving a copy.

**Comment by sphinx02** [comment] 2015-01-14 17:58
Dont think to complicate, if the feature is implemented as I mean, the behaviour is exactly the same as if I am doing the following:

- Set camera-folder on the phone to "Folder Master"
- Let camera sync files to the pc
- Set pc to versioning (keep 1 last file)
- Delete pictures from the phone
- Copy pictures from version folder back to the main-folder on the pc (remember they get not synced back to the phone because on the phone "Folder Master" is active)

In this scenario we do have the same "tricky" problems, but for Camera-Upload of the phone to the pc it would be a very nice feature and you never will have any problems with updated files as usually the phone takes a picture with date-string in its name which is never modified..

**Closed** 2015-07-21 18:48 UTC

**Comment by jpjp** [comment] 2015-07-22 07:57
Will this option let me truncate files?

**Comment by calmh** [comment] 2015-07-22 08:45
@jpjp Sure. That's a modification from our POV, not a delete.

**Comment by ged-nn** [comment] 2015-08-01 18:38
Not the options in web interface. Only config files.

**Comment by tchoulihan** [comment] 2016-01-08 17:30
I just installed this on my phone and computer, but there are no options for ignoring deletes in any of the menus. This is pretty vital, considering my use case is syncing photos from my phone to computer, and when I clear photos on the phone, I don't want them to be removed from the computer.

**Comment by AudriusButkevicius** [comment] 2016-01-08 18:45
It's in the advanced config available over web ui

**Comment by tchoulihan** [comment] 2016-01-08 19:39
I tried that on android, using the web-gui too, and there was no option for that.

**Comment by canton7** [comment] 2016-01-08 22:02
Look harder :wink:

![capture](https://cloud.githubusercontent.com/assets/568104/12210657/7ec9b32c-b653-11e5-9c6e-17f799a7b0a5.PNG)

**Comment by tchoulihan** [comment] 2016-01-09 16:23
Where are you seeing that?

Here is the webgui for android:

![pic1](https://cloud.githubusercontent.com/assets/930215/12217090/70cc9346-b6c3-11e5-854a-48739296fc2f.png)

No option to ignore deletes.

**Comment by tchoulihan** [comment] 2016-01-09 16:25
Also, just checked on my mac, v12.11, and I can't find any of those options in the folder menu.

**Comment by AudriusButkevicius** [comment] 2016-01-09 16:29
Actions -> Advanced -> Folder XYZ -> ignoreDelete

**Comment by tchoulihan** [comment] 2016-01-09 16:32
Oh jesus, thanks. That was weird. You'd think that within the folder menu itself would be an expandable advanced menu. IMO ignore deletes is such a fundamental use case for so many of us syncing photos and such, that it should be built into the main part of the folder menu itself.

**Comment by AudriusButkevicius** [comment] 2016-01-09 16:33
We don't think so.

**Comment by tchoulihan** [comment] 2016-01-09 16:35
Syncing photos and being able to delete them from my phone is pretty much my only use case for syncthing.

**Comment by AudriusButkevicius** [comment] 2016-01-09 16:57
It's not handled well enough to be in the main set of settings yet, as you will see that enabling this option will cause devices to show up out of sync.
