### ISSUE TITLE
Panic: Failed to find GetFileInformationByHandleEx after update from 1.01 to 1.1.

### ISSUE THREAD

**Issue by piromanneo** [syncthing/syncthing#5577] opened 2019-03-06 09:01 UTC
I got this panic after update from 1.01 to 1.1 on windows server 2003:

```
panic: Failed to find GetFileInformationByHandleEx procedure in kernel32.dll: The specified procedure could not be found.

goroutine 1 [running]:
syscall.(*LazyProc).mustFind(0x204499e0)
	C:/Go/src/syscall/dll_windows.go:287 +0x42
syscall.(*LazyProc).Addr(0x204499e0, 0x2043e540)
	C:/Go/src/syscall/dll_windows.go:294 +0x21
internal/syscall/windows.GetFileInformationByHandleEx(0x728, 0x9, 0x20470ca0, 0x8, 0x3, 0x2042f348)
	C:/Go/src/internal/syscall/windows/zsyscall_windows.go:353 +0x27
os.newFileStatFromGetFileInformationByHandle(0x20420840, 0x3d, 0x728, 0x0, 0x20420840, 0x3d)
	C:/Go/src/os/types_windows.go:52 +0x135
os.(*File).Stat(0x204fe190, 0xc9fa9c, 0x204fe190, 0x0, 0x204fe190)
	C:/Go/src/os/stat_windows.go:55 +0x133
io/ioutil.ReadFile(0x20420840, 0x3d, 0x0, 0x0, 0x0, 0x0, 0x0)
	C:/Go/src/io/ioutil/ioutil.go:62 +0xac
crypto/tls.LoadX509KeyPair(0x20420840, 0x3d, 0x20420740, 0x3c, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	C:/Go/src/crypto/tls/tls.go:189 +0x48
github.com/syncthing/syncthing/lib/tlsutil.NewCertificate(0x20420840, 0x3d, 0x20420740, 0x3c, 0xae3f75, 0x9, 0x0, 0x0, 0x0, 0x0, ...)
	C:/BuildAgent/work/174e136266f8a219/lib/tlsutil/tlsutil.go:155 +0xbec
main.syncthingMain(0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x204281e0, 0x42, 0x0, ...)
	C:/BuildAgent/work/174e136266f8a219/cmd/syncthing/main.go:589 +0x2ea4
main.main()
	C:/BuildAgent/work/174e136266f8a219/cmd/syncthing/main.go:388 +0x245

goroutine 6 [select]:
github.com/syncthing/syncthing/lib/events.(*Logger).Serve(0x20476090)
	C:/BuildAgent/work/174e136266f8a219/lib/events/events.go:260 +0xde
created by github.com/syncthing/syncthing/lib/events.init.1
	C:/BuildAgent/work/174e136266f8a219/lib/events/events.go:234 +0x4e

goroutine 7 [chan receive]:
github.com/syncthing/notify.(*recursiveTree).dispatch(0x2044b140)
	C:/BuildAgent/work/pkg/mod/github.com/syncthing/notify@v0.0.0-20181107104724-4e389ea6c0d8/tree_recursive.go:125 +0xa7
created by github.com/syncthing/notify.newRecursiveTree
	C:/BuildAgent/work/pkg/mod/github.com/syncthing/notify@v0.0.0-20181107104724-4e389ea6c0d8/tree_recursive.go:119 +0x115

goroutine 10 [sleep]:
runtime.goparkunlock(...)
	C:/Go/src/runtime/proc.go:307
time.Sleep(0x1dcd6500, 0x0)
	C:/Go/src/runtime/time.go:105 +0x15b
github.com/syncthing/syncthing/lib/dialer.init.0.func2()
	C:/BuildAgent/work/174e136266f8a219/lib/dialer/internal.go:55 +0x2d
created by github.com/syncthing/syncthing/lib/dialer.init.0
	C:/BuildAgent/work/174e136266f8a219/lib/dialer/internal.go:54 +0x1ff

goroutine 12 [syscall]:
os/signal.signal_recv(0x0)
	C:/Go/src/runtime/sigqueue.go:139 +0x12f
os/signal.loop()
	C:/Go/src/os/signal/signal_unix.go:23 +0x1a
created by os/signal.init.0
	C:/Go/src/os/signal/signal_unix.go:29 +0x37

goroutine 13 [chan receive]:
main.setupSignalHandling.func1(0x2044ae80)
	C:/BuildAgent/work/174e136266f8a219/cmd/syncthing/main.go:881 +0x29
created by main.setupSignalHandling
	C:/BuildAgent/work/174e136266f8a219/cmd/syncthing/main.go:880 +0x9f

goroutine 14 [chan receive]:
main.setupSignalHandling.func2(0x2044aec0)
	C:/BuildAgent/work/174e136266f8a219/cmd/syncthing/main.go:891 +0x29
created by main.setupSignalHandling
	C:/BuildAgent/work/174e136266f8a219/cmd/syncthing/main.go:890 +0x149

goroutine 15 [select]:
github.com/thejerf/suture.(*Supervisor).Serve(0x204a4000)
	C:/BuildAgent/work/pkg/mod/github.com/thejerf/suture@v3.0.2+incompatible/supervisor.go:454 +0x2d9
created by github.com/thejerf/suture.(*Supervisor).ServeBackground
	C:/BuildAgent/work/pkg/mod/github.com/thejerf/suture@v3.0.2+incompatible/supervisor.go:407 +0x33

goroutine 16 [chan receive]:
github.com/syncthing/syncthing/lib/events.(*bufferedSubscription).pollingLoop(0x204b64b0)
	C:/BuildAgent/work/174e136266f8a219/lib/events/events.go:441 +0x56
created by github.com/syncthing/syncthing/lib/events.NewBufferedSubscription
	C:/BuildAgent/work/174e136266f8a219/lib/events/events.go:436 +0x125

goroutine 66 [chan receive]:
github.com/syncthing/syncthing/lib/events.(*bufferedSubscription).pollingLoop(0x204b6510)
	C:/BuildAgent/work/174e136266f8a219/lib/events/events.go:441 +0x56
created by github.com/syncthing/syncthing/lib/events.NewBufferedSubscription
	C:/BuildAgent/work/174e136266f8a219/lib/events/events.go:436 +0x125

```

OS: Windows Server 2003
Chrome 32
Syncthing 1.01 / 1.1.

**Comment by calmh** [comment] 2019-03-06 09:06
Duplicate of #5575

**Closed by calmh** 2019-03-06 09:06 UTC
