### ISSUE TITLE
Corrupted files after synchronization

### ISSUE THREAD

**Issue by IT-Hurasys** [syncthing/syncthing#9262] opened 2023-12-05 17:21 UTC
Saddly I can't provide much information.
Just wan't to warn about a problem.
One colleague find out after several months that all files from a specific period (<= 03/2023) are corrupted.
After checking carefully with an hexa editor I find out that all files where filled with 0.

I search on the net if something similar already occur.

I could find :
https://github.com/syncthing/syncthing/issues/1315
https://forum.syncthing.net/t/corrupted-files/13096

Not sure if it was the same problem or not.

After that my colleague didn't used anymore Synchting without informing me :-(
I know the information are not complete but maybe it helps to understand the problem.

I will reinstall Syncthing on his laptop and write a small code that check if content of the files is filled with 0 to try to identify when it start. The problem is that we lost 3 years of his work with that corruption. I will also add versionning (what he didn't configure :-( )

Any suggestion is welcome.
Thanks

**Comment by calmh** [comment] 2023-12-05 17:37
That's unfortunate, but barring specific indications or a smoking gun I'm more inclined to think hardware error... Syncthing is quite careful to hash each block when wiring and reacting to ensure correctness.

**Comment by AudriusButkevicius** [comment] 2023-12-13 20:01
That is the default mode. Everything is cryptographically verified, before being written. Every file is fsynced before renamed to it's final name, every directory is fsynced after rename (hence why syncthing is slow with many small files). I can't think of anything more we could do to ensure correctness, except of doing the same thing twice or something.

People usually run syncthing on joker hardware (rasberry pi's, with 3$ sd cards etc) which is usually the cause of these issues, or joker software that doesn't do what we do, so I suggest to start the investigation there.

**Comment by imsodin** [comment] 2023-12-19 23:06
Closing that as it's not actionable - see comments above. If you are able to provide tangible information (ideally a way to reproduce, logs of when something unexpected/corruption happened, ...), please share and we can revisit that.

**Closed by imsodin** 2023-12-19 23:06 UTC
Labels: bug, needs-triage
