### ISSUE TITLE
Synchting using much memory (again)

### ISSUE THREAD

**Issue by Helium314** [syncthing/syncthing#6226] opened 2019-12-12 17:29 UTC
I just noticed that syncthing was using 1.2 GiB memory on my Raspberry Pi 3 (1 GiB available, + ~1 GiB swap on SD card), which slowed down things a lot.
This happened while uploading 2 files (ca 150 MiB each) to the only other remote device that was online. It looks a bit similar to #6160, but after upgrading to 1.3.2 this did not happen again despite transferring larger files several times.

After restarting syncthing the transfers continued normally, with memory usage staying below 200 MiB... so unfortunately I can't reproduce this issue.

Anyway I got a [memory profile](https://github.com/syncthing/syncthing/files/3957038/syncthing-heap-linux-arm-v1.3.2-171438.pprof.gz) and a [screenshot of the web GUI](https://user-images.githubusercontent.com/43007630/70734327-5ae52080-1d0c-11ea-969b-dd479311eee5.png) from the problem, I hope this helps.
Database tuning is set to small, I don't remember touching any other "advanced" option.

**Comment by AudriusButkevicius** [comment] 2019-12-12 18:13
It did not happen once you upgraded, and the upgrade included the fix, so it's somewhat expected as it's fixed?

Which version is the profile from, and is it during the period of high memory usage or just some random period?

I feel we should close this and move it to the forum until it's clear what exactly we are talking about here.

**Comment by Helium314** [comment] 2019-12-12 18:35
#6160 did not happen again since the upgrade. I think. Because #6160 was easily reproducible, while I noticed this problem only once. Still it looks very similar in the effects I see: high memory usage while uploading.

This happened just today on 1.3.2 for 32 bit ARM Linux. The profile was taken during high memory usage, maybe a few minutes after the screenshot (slow Raspi takes time to react).

**Comment by imsodin** [comment] 2019-12-12 18:40
The profile accounts ~500MB most of which is used by quic (with packet handling using 270MB) - which seems like too much. Looks like it's unrelated to requests/syncing. Without a reproducer it's probably not possible to debug this.

**Comment by AudriusButkevicius** [comment] 2019-12-12 18:58
We should probably raise it with them indicating which objects are causing this

**Comment by calmh** [comment] 2019-12-12 21:43
Haven't looked at anything yet, but keep in mind we're lagging a couple of QUIC versions since they've dropped Go 1.12 compatibility and we haven't.

**Comment by Helium314** [comment] 2019-12-13 06:33
Not sure if this is relevant, but I just saw in the logs that synchting actually did't react to the restart button, instead it was killed some 5 minutes later because the system ran out of memory (and apparently syncthing used even more than the 1.24 GiB from the screenshot)
`Killed process 24710 (syncthing) total-vm:1517740kB, anon-rss:586556kB, file-rss:0kB, shmem-rss:0kB`

**Comment by Helium314** [comment] 2019-12-17 18:04
Over the past few days I noticed that syncthing keeps using more and more memory, although still not as much as in the case above.

Usage when not syncing (this is very rough, sometimes it changed by more than 100 MiB while I was in webgui)
Friday - 150 MiB
Saturday - 250 MiB 
Sunday - 350 MiB
Monday - 600 MiB
Tuesday - 500 MiB
[heapprofs](https://github.com/syncthing/syncthing/files/3974730/heapprof.zip) for Saturday - Tuesday might help to see what is going on

**Comment by Helium314** [comment] 2020-01-09 10:26
Still happening in 1.3.3, memory usage rises by 50 to 100 MiB each day. I simply restart syncthing every 3 or 4 days to reduce memory usage.
As apparently no one else has (or reports) this problem - could it be an issue with my configuration?

**Comment by imsodin** [comment] 2020-01-09 10:51
Yes, it's possible that you hit some niche scenario affecting either our handling of quic or the quic library itself.

Something you could test is disable quic listener, to see whether the problem is on the dialing or listening side: Assuming you have the default listening address, replace it with `tcp://0.0.0.0:22000, quic://0.0.0.0:22000,dynamic+https://relays.syncthing.net/endpoint` (settings->connections).

**Comment by Helium314** [comment] 2020-01-13 09:40
I tried this (replacing `default` with `tcp://0.0.0.0:22000, quic://0.0.0.0:22000,dynamic+https://relays.syncthing.net/endpoint` in the listen addresses & restart), but memory usage still increases over time (350 MiB after 3 days).

[another heapprof](https://github.com/syncthing/syncthing/files/4052820/syncthing-heap-linux-arm-v1.3.3-103103.pprof.zip) (of st using the 350 MiB after 3 days) in case there is anything different to be found with 1.3.3 and the changed settings.

**Comment by imsodin** [comment] 2020-01-13 09:46
I messed up: The replaced listen address should not include quic (that's what's using the memory), i.e. `tcp://0.0.0.0:22000,dynamic+https://relays.syncthing.net/endpoint` - sorry for wasting your time.

**Comment by Helium314** [comment] 2020-01-15 06:48
Thanks, looks like this helped!
Should I close this issue (because disabling quic worked for me) or leave it open (because the actual problem with quic is not solved)?

**Comment by imsodin** [comment] 2020-01-15 07:10
Leave it open, because "runaway" memory usage with default settings is still a defect. We should at least ask upstream if they have any idea given the heap profile.

**Comment by calmh** [comment] 2020-01-15 07:27
Before doing that I think we should check that we're not simply amassing connections/streams/listeners ourselves incorrectly...

**Comment by imsodin** [comment] 2020-05-09 13:37
@Helium314 We upgraded quic in 1.5.0 - could you please reenable quic and check whether the problem has disappeared.

**Comment by Helium314** [comment] 2020-05-10 06:58
I set the listening address back to `default` and restarted syncthing.
How can I see RAM Utilization now? Apprarently the line got removed...

**Comment by AudriusButkevicius** [comment] 2020-05-10 08:41
Check with your OS tools.

**Comment by Helium314** [comment] 2020-05-11 05:34
Currently (after 1 day) syncthing is using 11.4% according to top (1 GiB RAM + 1 GiB Swap)

pmap:
```
19258:   /usr/bin/syncthing -no-browser -no-restart -logflags=0
00010000   7272K r-x-- syncthing
00730000   9160K r---- syncthing
01030000    324K rw--- syncthing
01081000    104K rw---   [ anon ]
02000000 118784K rw---   [ anon ]
09400000 409600K -----   [ anon ]
66a18000  10880K rw---   [ anon ]
674b8000 256832K -----   [ anon ]
76f88000    256K rw---   [ anon ]
7eaf0000    132K rw---   [ stack ]
7eb94000      4K r-x--   [ anon ]
7eb95000      4K r----   [ anon ]
7eb96000      4K r-x--   [ anon ]
ffff0000      4K r-x--   [ anon ]
 total   813360K
```

I have no idea how this compares to the values that used to be shown in the GUI, but I'll post same outputs again in a few days

**Comment by calmh** [comment] 2020-05-11 07:58
A memory profile is useful if it seems to use more than it should.

**Comment by Helium314** [comment] 2020-05-11 08:28
Oh right, I completely forgot about that... sorry


[syncthing-heap-linux-arm-v1.5.0-102142.pprof.gz](https://github.com/syncthing/syncthing/files/4608409/syncthing-heap-linux-arm-v1.5.0-102142.pprof.gz)

**Comment by imsodin** [comment] 2020-05-11 09:13
The heap accounts 33MB, none in quic, thus looks good - thanks for testing :)

**Closed by imsodin** 2020-05-11 09:13 UTC
Labels: needs-triage, waiting-for-info
