### ISSUE TITLE
Add an option in CLI to stop syncthing when the synchronization is done

### ISSUE THREAD

**Issue by sangorys** [syncthing/syncthing#7959] opened 2021-09-22 11:25 UTC
### Include required information
Hello,

I need (for technical and political reasons) to do a synchronization on demand and to stop the process.

So it would be great if you add an option to stop the process when the synchronization is finished.

Lets imagine : syncthing --autoclose

It will :

- Launch the synchronization
- Wait the end of synchronization
- Stop the process

I have seen some old requests in this gitHub and some discussions in the web (syncthing forum, redit, ...) of people searching a way to automatically stop the process after synchronization.

I appreciate your support :)

**Comment by imsodin** [comment] 2021-09-22 12:17
Duplicate of https://github.com/syncthing/syncthing/issues/7874

If you want to get help on how to achieve something similar with e.g. tooling of your own, please ask on https://forum.syncthing.net

**Closed by imsodin** 2021-09-22 12:17 UTC
Labels: enhancement, needs-triage
