### ISSUE TITLE
I need iOS APP for syncthing

### ISSUE THREAD

**Issue by snowdream** [syncthing/syncthing#7501] opened 2021-03-18 02:35 UTC
Thank you.

**Comment by calmh** [comment] 2021-03-18 05:51
Duplicate of #102

**Closed** 2021-03-18 05:51 UTC
Labels: enhancement, needs-triage

**Comment by snowdream** [comment] 2021-03-18 05:52
#102  This conversation has been locked as off-topic and limited to collaborators.

**Comment by calmh** [comment] 2021-03-18 07:22
I've unlocked it, primarily so that it can be voted on. Keep in mind though that comments along the lines of "I want this!" is not a valuable contribution and will be deleted -- please vote, instead.
