### ISSUE TITLE
-no-console does not work on win 11

### ISSUE THREAD

**Issue by Blade-B3AR** [syncthing/syncthing#8750] opened 2023-01-15 08:16 UTC
-no-console which should not open a cmd window like on win 10 but on win a 11 it opens a cmd window then minamizes it and am using v1.23.0

**Comment by tomasz1986** [comment] 2023-01-15 08:23
Duplicate of https://github.com/syncthing/syncthing/issues/8046.

**Comment by Blade-B3AR** [comment] 2023-01-15 08:26
> 

thank you did a search but it didnt pop up for some reason

**Closed** 2023-01-15 08:29 UTC
Labels: bug, needs-triage
