### ISSUE TITLE
Flaky UPnP

### ISSUE THREAD

**Issue by AudriusButkevicius** [syncthing/syncthing#1113] opened 2014-12-13 01:51 UTC
I've managed to reproduce this weird case where UPnP does not work.
Fired up wireshark, and I can see discovery packets leaving, but I cannot see UPnP MSEARCH packets leaving my machine.

I changed the broadcast address to something else within my subnet, and it starts working, meaning that either Go or Windows doesn't like the address.

Given I ran a different UPnP utility and it works, it makes me think there is something wrong with Go's stuff.

**Comment by cqcallaw** [comment] 2015-01-01 01:07
Interesting, I did a test with the [latest commit](https://github.com/syncthing/syncthing/tree/e94bd90782c25ef1a65cc0fe375bcafd1d398275 of syncthing) of syncthing, and the port mapping worked fine--and the discovery packets showed up in Wireshark! I really don't know what changed, but this issue doesn't seem reproducible enough to keep open. I vote to close the issue until someone can reliable reproduce it.

**Comment by AudriusButkevicius** [comment] 2015-01-03 16:53
Happening again on my machine with the new code :cry: 
I think the NIC messes up after sleep/hibernate which causes this issue.

**Comment by Rewt0r** [comment] 2015-01-05 17:36
on v0.10.17 I am unable to get a UPnP mapping on my machine.

```txt
[AAW47] 2015/01/05 17:31:22.974769 main.go:401: INFO: syncthing v0.10.17 (go1.4 windows-amd64 default) unknown-user@syncthing-builder 2015-01-04 19:18:14 UTC
[AAW47] 2015/01/05 17:31:22.975766 main.go:402: INFO: My ID: AAW47
[AAW47] 2015/01/05 17:31:23.435121 main.go:654: INFO: Starting web GUI on http://127.0.0.1:8080/
[AAW47] 2015/01/05 17:31:23.916462 upnp.go:106: INFO: Starting UPnP discovery...
[AAW47] 2015/01/05 17:31:23.916462 upnp.go:155: DEBUG: Starting discovery of device type urn:schemas-upnp-org:device:InternetGatewayDevice:2...
[AAW47] 2015/01/05 17:31:23.916462 upnp.go:175: DEBUG: Sending search request for device type urn:schemas-upnp-org:device:InternetGatewayDevice:2...
[AAW47] 2015/01/05 17:31:23.916462 upnp.go:187: DEBUG: Listening for UPnP response for device type urn:schemas-upnp-org:device:InternetGatewayDevice:2...
[AAW47] 2015/01/05 17:31:26.917072 upnp.go:228: DEBUG: Discovery for device type urn:schemas-upnp-org:device:InternetGatewayDevice:2 finished.
[AAW47] 2015/01/05 17:31:26.917072 upnp.go:155: DEBUG: Starting discovery of device type urn:schemas-upnp-org:device:InternetGatewayDevice:1...
[AAW47] 2015/01/05 17:31:26.917072 upnp.go:175: DEBUG: Sending search request for device type urn:schemas-upnp-org:device:InternetGatewayDevice:1...
[AAW47] 2015/01/05 17:31:26.917072 upnp.go:187: DEBUG: Listening for UPnP response for device type urn:schemas-upnp-org:device:InternetGatewayDevice:1...
[AAW47] 2015/01/05 17:31:29.917481 upnp.go:228: DEBUG: Discovery for device type urn:schemas-upnp-org:device:InternetGatewayDevice:1 finished.
[AAW47] 2015/01/05 17:31:29.917481 upnp.go:133: INFO: UPnP discovery complete (found 0 devices).
```

Using a Virgin Media SuperHub 2ac

**Comment by AudriusButkevicius** [comment] 2015-01-05 17:44
Hence why this issue is not yet closed.

I assume you had the issue before?
There is something really fishy with go and broadcast packets on Windows which I haven't solved, nothing todo with routers.
For the time being I suggest you setup a port mapping on the router.

**Comment by Rewt0r** [comment] 2015-01-05 17:49
Yeah spoke to you about it before https://discourse.syncthing.net/t/certain-clients-unable-to-connect-to-eachother/1445/11

**Comment by AudriusButkevicius** [comment] 2015-01-05 17:55
Yeah, I really need to find a way to reproduce this.
After restarting the machine UPnP usually succeeds for me, until some strange condition happens.

**Comment by Rewt0r** [comment] 2015-01-05 17:58
Since this new release I'm unable to do anything to get it to work. I've rebooted my router, rebooted my laptop, stopped and restarted the service (I run Syncthing as a service under Windows).

**Comment by Rewt0r** [comment] 2015-01-05 18:01
Weird. Just restarted Syncthing again and it's working...

```txt
[AAW47] 2015/01/05 17:58:40.014807 main.go:401: INFO: syncthing v0.10.17 (go1.4 windows-amd64 default) unknown-user@syncthing-builder 2015-01-04 19:18:14 UTC
[AAW47] 2015/01/05 17:58:40.015807 main.go:402: INFO: My ID: AAW47
[AAW47] 2015/01/05 17:58:40.515182 main.go:654: INFO: Starting web GUI on http://127.0.0.1:8080/
[AAW47] 2015/01/05 17:58:41.044534 upnp.go:106: INFO: Starting UPnP discovery...
[AAW47] 2015/01/05 17:58:41.044534 upnp.go:155: DEBUG: Starting discovery of device type urn:schemas-upnp-org:device:InternetGatewayDevice:2...
[AAW47] 2015/01/05 17:58:41.044534 upnp.go:175: DEBUG: Sending search request for device type urn:schemas-upnp-org:device:InternetGatewayDevice:2...
[AAW47] 2015/01/05 17:58:41.044534 upnp.go:187: DEBUG: Listening for UPnP response for device type urn:schemas-upnp-org:device:InternetGatewayDevice:2...
[AAW47] 2015/01/05 17:58:41.050537 upnp.go:238: DEBUG: Handling UPnP response:

HTTP/1.1 200 OK

CACHE-CONTROL: max-age=120

ST: urn:schemas-upnp-org:device:InternetGatewayDevice:2

USN: uuid:3db32f38-9504-11e4-96dc-e4f4c6cc2631::urn:schemas-upnp-org:device:InternetGatewayDevice:2

EXT:

SERVER: FedoraCore/6 UPnP/1.1 MiniUPnPd/1.7

LOCATION: http://192.168.0.1:1900/rootDesc.xml

OPT: "http://schemas.upnp.org/upnp/1/0/"; ns=01

01-NLS: 1

BOOTID.UPNP.ORG: 1

CONFIGID.UPNP.ORG: 1337




[AAW47] 2015/01/05 17:58:41.084567 upnp.go:435: DEBUG: [http://192.168.0.1:1900/rootDesc.xml] Found urn:schemas-upnp-org:service:WANIPConnection:1 with URL http://192.168.0.1:1900/ctl/IPConn
[AAW47] 2015/01/05 17:58:41.084567 upnp.go:424: DEBUG: [http://192.168.0.1:1900/rootDesc.xml] No services of type urn:schemas-upnp-org:service:WANPPPConnection:1 found on connection.
[AAW47] 2015/01/05 17:58:41.092573 upnp.go:335: DEBUG: Finished handling of UPnP response.
[AAW47] 2015/01/05 17:58:44.064128 upnp.go:228: DEBUG: Discovery for device type urn:schemas-upnp-org:device:InternetGatewayDevice:2 finished.
[AAW47] 2015/01/05 17:58:44.064128 upnp.go:155: DEBUG: Starting discovery of device type urn:schemas-upnp-org:device:InternetGatewayDevice:1...
[AAW47] 2015/01/05 17:58:44.064128 upnp.go:175: DEBUG: Sending search request for device type urn:schemas-upnp-org:device:InternetGatewayDevice:1...
[AAW47] 2015/01/05 17:58:44.064128 upnp.go:187: DEBUG: Listening for UPnP response for device type urn:schemas-upnp-org:device:InternetGatewayDevice:1...
[AAW47] 2015/01/05 17:58:44.080139 upnp.go:238: DEBUG: Handling UPnP response:

HTTP/1.1 200 OK

CACHE-CONTROL: max-age=120

ST: urn:schemas-upnp-org:device:InternetGatewayDevice:1

USN: uuid:3db32f38-9504-11e4-96dc-e4f4c6cc2631::urn:schemas-upnp-org:device:InternetGatewayDevice:1

EXT:

SERVER: FedoraCore/6 UPnP/1.1 MiniUPnPd/1.7

LOCATION: http://192.168.0.1:1900/rootDesc.xml

OPT: "http://schemas.upnp.org/upnp/1/0/"; ns=01

01-NLS: 1

BOOTID.UPNP.ORG: 1

CONFIGID.UPNP.ORG: 1337




[AAW47] 2015/01/05 17:58:44.081139 upnp.go:283: DEBUG: Ignoring known device with UUID 3db32f38-9504-11e4-96dc-e4f4c6cc2631
[AAW47] 2015/01/05 17:58:47.064315 upnp.go:228: DEBUG: Discovery for device type urn:schemas-upnp-org:device:InternetGatewayDevice:1 finished.
[AAW47] 2015/01/05 17:58:47.064315 upnp.go:118: DEBUG: UPnP discovery result:
[AAW47] 2015/01/05 17:58:47.064315 upnp.go:120: DEBUG: [3db32f38-9504-11e4-96dc-e4f4c6cc2631]
[AAW47] 2015/01/05 17:58:47.064315 upnp.go:123: DEBUG: * [urn:upnp-org:serviceId:WANIPConn1] http://192.168.0.1:1900/ctl/IPConn
[AAW47] 2015/01/05 17:58:47.064315 upnp.go:133: INFO: UPnP discovery complete (found 1 device).
[AAW47] 2015/01/05 17:58:47.064315 upnp.go:488: DEBUG: SOAP Request URL: http://192.168.0.1:1900/ctl/IPConn
[AAW47] 2015/01/05 17:58:47.064315 upnp.go:489: DEBUG: SOAP Action: "urn:schemas-upnp-org:service:WANIPConnection:1#AddPortMapping"
[AAW47] 2015/01/05 17:58:47.064315 upnp.go:490: DEBUG: SOAP Request:

<?xml version="1.0" ?>
	<s:Envelope xmlns:s="http://schemas.xmlsoap.org/soap/envelope/" s:encodingStyle="http://schemas.xmlsoap.org/soap/encoding/">
	<s:Body><u:AddPortMapping xmlns:u="urn:schemas-upnp-org:service:WANIPConnection:1">
	<NewRemoteHost></NewRemoteHost>
	<NewExternalPort>35311</NewExternalPort>
	<NewProtocol>TCP</NewProtocol>
	<NewInternalPort>22000</NewInternalPort>
	<NewInternalClient>192.168.0.2</NewInternalClient>
	<NewEnabled>1</NewEnabled>
	<NewPortMappingDescription>syncthing-35311</NewPortMappingDescription>
	<NewLeaseDuration>0</NewLeaseDuration>
	</u:AddPortMapping></s:Body>
	</s:Envelope>

[AAW47] 2015/01/05 17:58:47.088323 upnp.go:500: DEBUG: SOAP Response:

<?xml version="1.0"?>

<s:Envelope xmlns:s="http://schemas.xmlsoap.org/soap/envelope/" s:encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"><s:Body><u:AddPortMappingResponse xmlns:u="urn:schemas-upnp-org:service:WANIPConnection:1"/></s:Body></s:Envelope>



[AAW47] 2015/01/05 17:58:47.088323 main.go:778: INFO: Created UPnP port mapping for external port 35311 on UPnP device 'VMDG490' (192.168.0.1).
```

**Comment by AudriusButkevicius** [comment] 2015-01-16 00:18
Multicast examples, might be relevant: https://gowalker.org/github.com/golang/net/ipv4

**Closed** 2015-04-16 13:32 UTC
Labels: bug
