### ISSUE TITLE
Can't open local web gui, synchting working.

### ISSUE THREAD

**Issue by JeanOlivier** [syncthing/syncthing#2310] opened 2015-09-25 15:07 UTC
Hi,

For a few days, I haven't been able to open the webgui on my local machine (127.0.0.1:8080). On my remote server though, everything is fine and the synchronisation betweeen both machines is unaffected; both are running v0.11.25, Linux (64bit). I really don't understand the problem and any help would be appreciated.

I can provide the stdout of syncthing if need be but I don't want to pollute this post with a meter of text.

Thank you!

Jos

**Comment by AudriusButkevicius** [comment] 2015-09-25 15:56
Check the logs, it might have started on a different port if it was taken, also, you might have disabled gui from the settings.

**Comment by JeanOlivier** [comment] 2015-09-25 16:15
Thank you for your answer!

I can't seem to find the proper logs, any cue would be appreciated.

When I start syncthing from the terminal, it outputs, among others, this line:
[MR5K3] 09:24:48 INFO: Starting web GUI on http://127.0.0.1:8080/
Then a few lines later:
[MR5K3] 09:24:48 INFO: API listening on 127.0.0.1:8080

After that it seems to crash and restart:
[MR5K3] 09:23:43 INFO: Local discovery (broadcast writer): write udp4: network is unreachable
[MR5K3] 09:23:43 INFO: Paused state detected, possibly woke up from standby. Restarting in 1m0s.
[MR5K3] 09:24:13 INFO: Local discovery (broadcast writer): write udp4: network is unreachable
[MR5K3] 09:24:15 INFO: Connection to [redacted] closed: ping timeout
[MR5K3] 09:24:17 INFO: Established secure connection to [redacted] at [redacted]
[MR5K3] 09:24:17 INFO: Device [redacted] client is "syncthing v0.11.25"
[MR5K3] 09:24:17 INFO: Device [redacted] name is "[redacted]"
[MR5K3] 09:24:44 INFO: Restarting
[MR5K3] 09:24:44 OK: Exiting

After the restart there's the two lines I mentioned earlier
[MR5K3] 09:24:48 INFO: Starting web GUI on http://127.0.0.1:8080/
[Few lines]
[MR5K3] 09:24:48 INFO: API listening on 127.0.0.1:8080

And then everything seems fine except that I can't access the web gui.

**Comment by AudriusButkevicius** [comment] 2015-09-25 16:21
Can you run `curl -v -s http://127.0.0.1/` in the shell?

**Comment by JeanOlivier** [comment] 2015-09-25 17:22
If I run 
curl -v -s http://127.0.0.1:8080 
instead, as I chose that port for syncthing, I get a big output starting with
* Rebuilt URL to: http://127.0.0.1:8080/
* Hostname was NOT found in DNS cache
*   Trying 127.0.0.1...
* Connected to 127.0.0.1 (127.0.0.1) port 8080 (#0)
> GET / HTTP/1.1
> User-Agent: curl/7.38.0
> Host: 127.0.0.1:8080
> Accept: */*
> 
< HTTP/1.1 200 OK
< Cache-Control: public
< Content-Length: 33759
< Content-Type: text/html
< Last-Modified: Sun, 13 Sep 2015 09:46:05 GMT
[redacted personal infos]

And then follows what appears to be html.

Still unable to connect to it in the browser though.

Thank you again!

**Comment by AudriusButkevicius** [comment] 2015-09-25 17:28
Well the problem is your browser. Are you browsing on the same machine as its running? Do you have a proxy setup on the browser? Given its not a syncthing issue, as curl clearly works, I am closing this.

**Closed by AudriusButkevicius** 2015-09-25 17:28 UTC

**Comment by JeanOlivier** [comment] 2015-09-25 17:39
Just in case someone else has that kind of problem in the future, I fixed my problem by making syncthing use https for the webgui. 

The only issue is that it now complains about the https being not safe when I conenct to it. If I switch it back to http, the texdt is all bold and ugly and the icon representing the devices are HUGE. But that's fine for me now as I can monitor what's happening anyways!

In any case, thank you for your support!

Jos

**Comment by AudriusButkevicius** [comment] 2015-09-25 17:40
Shift + F5 or clear your briwser cache

**Comment by JeanOlivier** [comment] 2015-09-25 17:42
Thank you sir. Sorry for the hassle!
