### ISSUE TITLE
Bad propagation in case of ENOSPC

### ISSUE THREAD

**Issue by viric** [syncthing/syncthing#1498] opened 2015-03-20 11:13 UTC
I had two syncthing, A and B. A had a big file that was synched to B. syncthing on B died because of ENOSPC.

Once I freed space and started back syncthing on B, the sending did not continue. Instead, the short file of B was propagated to A, hence the original big file was destroyed (truncated).

I think that in ENOSPC suicide the timestamp in B was left newer than that of A, and hence it decided to propagate from B to A, destroying the original data.

This happened in version 0.10.26.

**Comment by AudriusButkevicius** [comment] 2015-03-20 11:38
Do you have a stacktrace of where the crash happened?

**Comment by calmh** [comment] 2015-03-20 12:54
This sounds extremely odd. We don't move the temporary (to which changes are written during sync) to the final filename until it's complete and blocks have passed the verification. Unless there's a bad bug...

**Comment by viric** [comment] 2015-03-20 13:09
I had a 4GB file in one side, and ENOSPC in the other. The result: 600MB in both sides.

Here is the log I have from the ENOSPC side (still on backlog buffer, luckily):
```
[MD4JY] 09:29:40 INFO: My ID: MD4JYBT-MXFLIJW-A4BSARY-ADYPQ6E-YKPI63C-FG5YNUN-TH363VU-46BJLAV
[MD4JY] 09:29:40 FATAL: Cannot open database: write /home/llbatlle/.config/syncthing/index/000012.ldb: no space left on device - Is another copy of Syncthing already running?
[monitor] 09:29:40 INFO: Syncthing exited: exit status 1
channel 3: open failed: connect failed: Connection refused
[monitor] 09:29:41 INFO: Starting syncthing
channel 3: open failed: connect failed: Connection refused
[MD4JY] 09:29:42 INFO: syncthing v0.10.24 (go1.4.2 linux-amd64 default) unknown@unknown 1970-01-01 00:00:00 UTC
[MD4JY] 09:29:42 INFO: My ID: MD4JYBT-MXFLIJW-A4BSARY-ADYPQ6E-YKPI63C-FG5YNUN-TH363VU-46BJLAV
[MD4JY] 09:29:42 FATAL: Cannot open database: write /home/llbatlle/.config/syncthing/index/000012.ldb: no space left on device - Is another copy of Syncthing already running?
[monitor] 09:29:42 INFO: Syncthing exited: exit status 1
channel 3: open failed: connect failed: Connection refused
[monitor] 09:29:43 INFO: Starting syncthing
[MD4JY] 09:29:43 INFO: syncthing v0.10.24 (go1.4.2 linux-amd64 default) unknown@unknown 1970-01-01 00:00:00 UTC
[MD4JY] 09:29:43 INFO: My ID: MD4JYBT-MXFLIJW-A4BSARY-ADYPQ6E-YKPI63C-FG5YNUN-TH363VU-46BJLAV
[MD4JY] 09:29:43 FATAL: Cannot open database: write /home/llbatlle/.config/syncthing/index/000012.ldb: no space left on device - Is another copy of Syncthing already running?
[monitor] 09:29:43 INFO: Syncthing exited: exit status 1
channel 3: open failed: connect failed: Connection refused
channel 3: open failed: connect failed: Connection refused
channel 3: open failed: connect failed: Connection refused
channel 3: open failed: connect failed: Connection refused
[monitor] 09:29:44 INFO: Starting syncthing
channel 3: open failed: connect failed: Connection refused
[MD4JY] 09:29:45 INFO: syncthing v0.10.24 (go1.4.2 linux-amd64 default) unknown@unknown 1970-01-01 00:00:00 UTC
[MD4JY] 09:29:45 INFO: My ID: MD4JYBT-MXFLIJW-A4BSARY-ADYPQ6E-YKPI63C-FG5YNUN-TH363VU-46BJLAV
[MD4JY] 09:29:45 FATAL: Cannot open database: write /home/llbatlle/.config/syncthing/index/000012.ldb: no space left on device - Is another copy of Syncthing already running?
[monitor] 09:29:45 INFO: Syncthing exited: exit status 1
channel 3: open failed: connect failed: Connection refused
[monitor] 09:29:46 WARNING: 4 restarts in 6.57555725s; not retrying further
```

**Comment by viric** [comment] 2015-03-20 13:23
Sorry, here are some earlier lines to the restart attempts (the first crash):
```
[MD4JY] 09:29:10 INFO: Puller (folder "default", file "00017.MTS"): dst write: write /home/llbatlle/Sync/.syncthing.00017.MTS: no space left on device
[MD4JY] 09:29:18 INFO: Puller (folder "default", file "00017.MTS"): dst write: write /home/llbatlle/Sync/.syncthing.00017.MTS: no space left on device
[MD4JY] 09:29:26 INFO: Puller (folder "default", file "00017.MTS"): dst write: write /home/llbatlle/Sync/.syncthing.00017.MTS: no space left on device
[MD4JY] 09:29:26 WARNING: Folder "default" isn't making progress - check logs for possible root cause. Pausing puller for 1m0s.
panic: write /home/llbatlle/.config/syncthing/index/000010.log: no space left on device
[monitor] 09:29:38 WARNING: Panic detected, writing to "/home/llbatlle/.config/syncthing/panic-20150320-092938.log"
[monitor] 09:29:38 WARNING: Please create an issue at https://github.com/syncthing/syncthing/issues/ with the panic log attached
[monitor] 09:29:38 INFO: Syncthing exited: exit status 2
```

The file panic-20150320-092938.log is completely blank. 0 bytes length. Due to ENOSPC I guess.

**Comment by viric** [comment] 2015-03-20 13:25
Another note, as you mention about when the rename is effective... Copying the 4GB file locally to ~/Sync took a long time, and during the copy, syncthing had run more than one synchronisation. I guess that when the file was 600MB long, it transferred those 600MB and did the rename. The file was growing and growing in A, while it was being copied, and regularly synchronized, until ENOSPC.

That's the reason why there was a 600MB copy in B, I guess. Why A lost the 4GB and got the contents of B, I don't know.

**Comment by calmh** [comment] 2015-03-20 13:33
Hmm. With the disk full on the partition holding the index the database is trash as well. Could be related. Panicing as above is probably the right reaction in that situation.

**Comment by viric** [comment] 2015-03-20 13:37
A right reaction that propagates file destruction because one node has ENOSPC. This sounds really bad. :)

**Comment by calmh** [comment] 2015-03-20 13:45
No, that's something else that is not explained yet. The output above only shows one syncthign not starting due to no disk space, and the other one exiting due to no disk space.

**Comment by viric** [comment] 2015-03-20 13:53
Ok. Both outputs are from the same syncthing, in machine B. I posted the second log because I noticed that in my first post I forgot the earlier lines that showed why it was dying originally).

The syncthing in machine A did not have any problem of ENOSPC, and it had the 4GB file in ~/Sync that ended up destroyed.

**Comment by calmh** [comment] 2015-03-20 13:55
For what it's worth, I can't immediately reproduce this. This is one syncthing living on a 100MB partition trying to sync a 150MB file. It fails, then fails to start (similar to your setup), but the file remains as a temporary and the "source" side is untouched.

```
jb@syno:/Volumes/Disk Image $ df -h .
Filesystem     Size   Used  Avail Capacity iused ifree %iused  Mounted on
/dev/disk4s1   98Mi  2.8Mi   95Mi     3%     721 24272    3%   /Volumes/Disk Image
jb@syno:/Volumes/Disk Image $ syncthing -home h1
[monitor] 14:53:35 INFO: Starting syncthing
[I6KAH] 14:53:35 INFO: syncthing v0.10.27+30-gfc483cd (go1.4 darwin-amd64 default) jb@syno 2015-03-20 08:35:02 UTC
[I6KAH] 14:53:35 INFO: My ID: I6KAH76-66SLLLB-5PFXSOA-UFJCDZC-YAOMLEK-CP2GB32-BV5RQST-3PSROAU
[I6KAH] 14:53:35 INFO: Starting web GUI on http://127.0.0.1:8081/
[I6KAH] 14:53:36 INFO: Starting UPnP discovery...
[I6KAH] 14:53:42 INFO: UPnP discovery complete (found 0 devices).
[I6KAH] 14:53:42 INFO: Starting local discovery announcements
[I6KAH] 14:53:42 INFO: Local discovery over IPv4 unavailable
[I6KAH] 14:53:42 OK: Ready to synchronize default (read-write)
[I6KAH] 14:53:42 OK: Ready to synchronize s12 (read-write)
[I6KAH] 14:53:42 INFO: Device EJHMPAQ-OGCVORE-ISB4IS3-SYYVJXF-TKJGLTU-66DIQPF-GJ5D2GX-GQ3OWQK is "s4" at [127.0.0.1:22004]
[I6KAH] 14:53:42 INFO: Device I6KAH76-66SLLLB-5PFXSOA-UFJCDZC-YAOMLEK-CP2GB32-BV5RQST-3PSROAU is "s1" at [127.0.0.1:22001]
[I6KAH] 14:53:42 INFO: Device JMFJCXB-GZDE4BN-OCJE3VF-65GYZNU-AIVJRET-3J6HMRQ-AUQIGJO-FKNHMQU is "s2" at [127.0.0.1:22002]
[I6KAH] 14:53:42 INFO: Device 373HSRP-QLPNLIE-JYKZVQF-P4PKZ63-R2ZE6K3-YD442U2-JHBGBQG-WWXAHAU is "s3" at [127.0.0.1:22003]
[I6KAH] 14:53:42 INFO: No automatic upgrades; v0.10.27+30-gfc483cd is not a release version.
[I6KAH] 14:53:42 INFO: Completed initial scan (rw) of folder default
[I6KAH] 14:53:42 INFO: Completed initial scan (rw) of folder s12
[I6KAH] 14:53:42 INFO: Established secure connection to JMFJCXB-GZDE4BN-OCJE3VF-65GYZNU-AIVJRET-3J6HMRQ-AUQIGJO-FKNHMQU at 127.0.0.1:57920-127.0.0.1:22002
[I6KAH] 14:53:42 INFO: Device JMFJCXB-GZDE4BN-OCJE3VF-65GYZNU-AIVJRET-3J6HMRQ-AUQIGJO-FKNHMQU client is "syncthing v0.10.27+30-gfc483cd"
[I6KAH] 14:53:42 INFO: Device JMFJCXB-GZDE4BN-OCJE3VF-65GYZNU-AIVJRET-3J6HMRQ-AUQIGJO-FKNHMQU name is "s2"
[I6KAH] 14:53:44 INFO: Puller (folder "default", file "bigfile"): save: write s1/.syncthing.bigfile: no space left on device
[I6KAH] 14:53:44 INFO: Puller (folder "default", file "bigfile"): save: write s1/.syncthing.bigfile: no space left on device
[I6KAH] 14:53:45 INFO: Puller (folder "default", file "bigfile"): save: write s1/.syncthing.bigfile: no space left on device
[I6KAH] 14:53:46 INFO: Puller (folder "default", file "bigfile"): save: write s1/.syncthing.bigfile: no space left on device
[I6KAH] 14:53:47 INFO: Puller (folder "default", file "bigfile"): save: write s1/.syncthing.bigfile: no space left on device
[I6KAH] 14:53:48 INFO: Puller (folder "default", file "bigfile"): save: write s1/.syncthing.bigfile: no space left on device
[I6KAH] 14:53:49 INFO: Puller (folder "default", file "bigfile"): save: write s1/.syncthing.bigfile: no space left on device
[I6KAH] 14:53:49 INFO: Puller (folder "default", file "bigfile"): save: write s1/.syncthing.bigfile: no space left on device
[I6KAH] 14:53:50 INFO: Puller (folder "default", file "bigfile"): save: write s1/.syncthing.bigfile: no space left on device
[I6KAH] 14:53:51 INFO: Puller (folder "default", file "bigfile"): save: write s1/.syncthing.bigfile: no space left on device
[I6KAH] 14:53:51 INFO: Puller (folder "default", file "bigfile"): save: write s1/.syncthing.bigfile: no space left on device
[I6KAH] 14:53:51 WARNING: Folder "default" isn't making progress - check logs for possible root cause. Pausing puller for 1m0s.
^C[monitor] 14:53:56 INFO: Signal 2 received; exiting
jb@syno:/Volumes/Disk Image $ ls -la s1
total 194048
drwx------  4 jb  staff       136 Mar 20 14:53 ./
drwxr-xr-x  9 jb  staff       374 Mar 20 14:53 ../
-rw-r--r--  1 jb  staff         0 Mar 20 14:53 .stfolder
-rw-r--r--  1 jb  staff  99352576 Mar 20 14:53 .syncthing.bigfile
jb@syno:/Volumes/Disk Image $ syncthing -home h1
[monitor] 14:54:02 INFO: Starting syncthing
[I6KAH] 14:54:03 INFO: syncthing v0.10.27+30-gfc483cd (go1.4 darwin-amd64 default) jb@syno 2015-03-20 08:35:02 UTC
[I6KAH] 14:54:03 INFO: My ID: I6KAH76-66SLLLB-5PFXSOA-UFJCDZC-YAOMLEK-CP2GB32-BV5RQST-3PSROAU
[I6KAH] 14:54:03 FATAL: Cannot open database: open h1/index/LOG: no space left on device - Is another copy of Syncthing already running?
[monitor] 14:54:03 INFO: Syncthing exited: exit status 1
[monitor] 14:54:04 INFO: Starting syncthing
[I6KAH] 14:54:04 INFO: syncthing v0.10.27+30-gfc483cd (go1.4 darwin-amd64 default) jb@syno 2015-03-20 08:35:02 UTC
[I6KAH] 14:54:04 INFO: My ID: I6KAH76-66SLLLB-5PFXSOA-UFJCDZC-YAOMLEK-CP2GB32-BV5RQST-3PSROAU
[I6KAH] 14:54:04 FATAL: Cannot open database: open h1/index/LOG: no space left on device - Is another copy of Syncthing already running?
[monitor] 14:54:04 INFO: Syncthing exited: exit status 1
[monitor] 14:54:05 INFO: Starting syncthing
[I6KAH] 14:54:06 INFO: syncthing v0.10.27+30-gfc483cd (go1.4 darwin-amd64 default) jb@syno 2015-03-20 08:35:02 UTC
[I6KAH] 14:54:06 INFO: My ID: I6KAH76-66SLLLB-5PFXSOA-UFJCDZC-YAOMLEK-CP2GB32-BV5RQST-3PSROAU
[I6KAH] 14:54:06 FATAL: Cannot open database: open h1/index/LOG: no space left on device - Is another copy of Syncthing already running?
[monitor] 14:54:06 INFO: Syncthing exited: exit status 1
[monitor] 14:54:07 INFO: Starting syncthing
[I6KAH] 14:54:07 INFO: syncthing v0.10.27+30-gfc483cd (go1.4 darwin-amd64 default) jb@syno 2015-03-20 08:35:02 UTC
[I6KAH] 14:54:07 INFO: My ID: I6KAH76-66SLLLB-5PFXSOA-UFJCDZC-YAOMLEK-CP2GB32-BV5RQST-3PSROAU
[I6KAH] 14:54:07 FATAL: Cannot open database: open h1/index/LOG: no space left on device - Is another copy of Syncthing already running?
[monitor] 14:54:07 INFO: Syncthing exited: exit status 1
[monitor] 14:54:08 WARNING: 4 restarts in 5.649435204s; not retrying further
[1]
jb@syno:/Volumes/Disk Image $ 
```

**Comment by viric** [comment] 2015-03-20 13:59
I think that what I commented in https://github.com/syncthing/syncthing/issues/1498#issuecomment-84017040 is important.

Syncthing in A and B was running, ~/Sync empty in both. Then I started copying a 4GB file to A:~/Sync. It took several minutes.

Refresh happens every 60 seconds, so there was a first synchronisation round when the file in A was about 200MB big, and it propagated to B.

A second synchronisation round happened when the file in A was about 600MB big, and it propagated to B.

At a third synchronisation round, I don't know the size of the file in A, but B hit ENOSPC and died, and couldn't be restarted.

Meanwhile, the file copy in A finished, and the file grew to 4GB. Then I freed space in B, and started syncthing again. I expected the 4GB to go to B, but instead, the 600MB file in B went to A, destroying the 4GB.

**Comment by calmh** [comment] 2015-03-20 14:09
Right, yes. So what probably happened is the index database on B got corrupted due to out of space. Once you'd cleared up the space on B the file there (600 MB) was detected as a new file and synced over to A. This'll be resolved by solving #220 then, is it should really have been a conflict (changes on two sides). But in general, running out of space for the database is bad, as it would be for anything using an on disk database.

**Comment by viric** [comment] 2015-03-20 14:12
I agree that ENOSPC situations are hard to handle. But when the consequence of such bad handling is extra data destruction reaching to multiple copies, it's worse than what a naive user would expect. I will wait for the fix. Thank you!

**Comment by thegeek1977** [comment] 2015-03-31 05:15
Might be that the ENOSPC-situation can be dealt with by reserving a little extra space for the database when the system runs good.. The blank space can then be written to in the event of ENOSPC. This will definitely make the handling of such errors better. Don't really know if this could easily bve implemented as I don't know about the exact database-structure so tis is jjust an idea.

**Comment by calmh** [comment] 2015-05-07 19:45
We should no longer be destroying data in this case as there is conflict handling, so I'm going to close this. There will still be unhappiness when the database can't be written to due to full disk; we have this in common with almost every other program in the world so I'm fine with that for the moment. If someone disagrees, it's a different ticket anyhow. :)

**Closed by calmh** 2015-05-07 19:45 UTC
