### ISSUE TITLE
Partially sync

### ISSUE THREAD

**Issue by LoginByCall** [syncthing/syncthing#7349] opened 2021-02-09 18:03 UTC
### Include required information

Please be sure to include at least:

 - what problem your new feature would solve
Lack of free disk space.

 - how or why you think it is generally useful (i.e., not just for you)
It will be possible to exchange with large folders.

 - what alternatives or workarounds you considered
Ability to mark a folder with the "partially synchronization" flag. After that, for each file from the remote folder, are created file in the local folder as "*.sync" (with pointer to real remote file). With Explorer or Finder (right-click menu), you can manage files (download or delete) the current file without deleting it in the remote folder.

Right-click menu for manage file or folder:
- download
- delete here
- delete at all

**Comment by imsodin** [comment] 2021-02-09 18:37
There's ignore patterns: https://docs.syncthing.net/users/ignoring.html

Then what you want might be a duplicate of https://github.com/syncthing/syncthing/issues/4729 and/or https://github.com/syncthing/syncthing/issues/2491.

If you think that's not the case or have other questions, please post to https://forum.syncthing.net.

**Closed by imsodin** 2021-02-09 18:37 UTC
Labels: enhancement, needs-triage

**Comment by LoginByCall** [comment] 2021-02-09 20:28
1. I'll give you a big folder. Connect it yourself and specify which files you want to download without downloading the entire folder first. How do you know the list of files in a folder without first downloading it entirely?
2. I will give you a list of 200 files and ask you not to sync 20 of them (you will have to manually create 20 .stignore files. In an hour I will give you another list of 20 files. Delete the previous files and create new ones. And so on several times. How soon  will you get tired?
3. The solution you proposed does not fit the patterns of typical user behavior. This will kill him.
4. I've used both synthing and resilio sync. the second is convenient but proprietary. Why not take the good solution of it?

**Comment by alins** [comment] 2021-09-29 21:05
totally agree @LoginByCall 

IMO there's a fundamental disagreement on how "partial sync" (or "selective sync") should work. for me, it should work exactly how you outlined it. keep seeing comments from core maintainers pointing to ignore patterns. I can't wrap my head around how ignore patterns actually gives you partial or selective sync for the exact same reason you outlined above. it gives you "something" but not selective sync using the definition that I know

I guess better said: for anybody that has used dropbox selective sync OR resilio selective sync, I would dare say is really obvious that ignore patterns is NOT the solution to this problem, not even in the ballpark. but that assumes that one has used selective sync from other solutions and they would like to see something similar here.

now if one has NOT used selective sync before and they come fresh to the problem, yes...I can see you would think that ignore patterns would get you what you want.

**Comment by LoginByCall** [comment] 2021-10-01 06:03
> totally agree @LoginByCall
> 
> IMO there's a fundamental disagreement on how "partial sync" (or "selective sync") should work. for me, it should work exactly how you outlined it. keep seeing comments from core maintainers pointing to ignore patterns. I can't wrap my head around how ignore patterns actually gives you partial or selective sync for the exact same reason you outlined above. it gives you "something" but not selective sync using the definition that I know
> 
> I guess better said: for anybody that has used dropbox selective sync OR resilio selective sync, I would dare say is really obvious that ignore patterns is NOT the solution to this problem, not even in the ballpark. but that assumes that one has used selective sync from other solutions and they would like to see something similar here.
> 
> now if one has NOT used selective sync before and they come fresh to the problem, yes...I can see you would think that ignore patterns would get you what you want.

I have a suspicion that syncthing and resilio are owned by the same development team. It explains everything)
