### ISSUE TITLE
GUI for .stversion restoration (feature)

### ISSUE THREAD

**Issue by ericszimmermann** [syncthing/syncthing#2599] opened 2015-12-19 12:11 UTC
I've come across the versioning function of Syncthing. I use it to sync the files to a backup storage.
However restoration form the .stversion folder is a mess. You have to rename all the files to remove the timestamp in the name. It would be great to have a GUI for this function.
## USECASE:

I had the problem, when i was working with my colleague on a school project.
I accidentally deleted a folder inclusive its subfolders. Through inotify, they were also immediately deleted on his side too. Luckily he had the "Simple Versioning" enabled. So we could copy all the files back from the .stversion folder. But it was HARD work to manually rename all the files back to their original name and to sort the multiple versions out.

It would have been only four or five clicks with a GUI. Just give the order to revert the files (copy the files back to the Sync folder and rename them), which have a timestamp between 13:10 and 13:20.

And at least, I had to ask my Colleague to copy the files back, because they were in his .stversion folder. I couldn't have done anything from my side.

I just thought it would be a nice feature in usability, to have such a GUI revert function.
## IMPLEMENTATION:

It would just require a list of all the files in .stversion folder to be transfered.
After that the list only has to be filtered for the files, the user wants to restore,
based on the timestamp and send back.
At least a single command could be emited to fullfill the copy and rename process of the selected files.
## GUI:

I propose to insert a "Revert" Button next to the "Rescan" and "Edit" buttons of the folders.
Of course only if versioning is enabled in any of the synced devices.

This opens a Window like following Picture:
![gui_proposal](https://cloud.githubusercontent.com/assets/13203829/11912872/8712a924-a651-11e5-8573-1492b3396c53.png)

**Comment by ericszimmermann** [comment] 2015-12-27 16:56
This with the Schoolproject was real luck, but here an other usecase:

I often use the Commandline to remove files, for example "rm *.txt".
Therefore the files are not moved to the Filemanagers trash, and lost.

Because I sync my working folder with inotify to my NAS, which has the "Staggered Versioning" function turned on, I get a nice History in the .stversion folder. (Syncthing realy does a nice job in that).

However to get the files back from the .stversion folder, I always have to login to my NAS per ssh to recover (copy and rename) the files.

**Comment by calmh** [comment] 2016-01-01 21:55
I see that you never got a human response on this one; sorry about that! I think your request is a reasonable one that we could do, but we're probably going to need some outside help from someone who's invested in this feature.

**Comment by wonderbeyond** [comment] 2016-07-15 00:29
+1 want

**Comment by c-gom** [comment] 2016-11-08 13:12
+1

This is striking me as not a particularly popular feature request, but is definitely something which has been keeping me on the fence about rolling out syncthing. I suppose that as syncthing develops it may be useful to revisit support for this niche use case.

**Comment by wiwie** [comment] 2016-11-16 09:39
+1 on this; I basic revert functionality in the GUI would already do for me...

**Comment by canton7** [comment] 2016-11-16 09:44
Guys, please use the 'reaction' buttons to add +1s, rather than filling the comments with "me too" posts :smile:

**Comment by vincentardern** [comment] 2017-03-28 10:56
I've posted a bounty for this of $250 on bountysource

**Comment by calmh** [comment] 2017-03-30 19:34
In the interest of keepings things straight and manage expectations on your dollars, let me note that the issue is unlikely to ever be resolved to exactly the extent that the original request describes. "GUI for restoration from .stversions" is fine, but the mockup requires a lot more than that and looks more like a full featured backup program.

**Comment by generalmanager** [comment] 2017-10-25 22:46
@calmh As a first step in the direction of better restorability I'd suggest changing the folder & naming scheme inside the .stversions folder. This poses the problem that after accidentally deleting a big folder (which can also happen with some kind of mounting problems) one has to write a script to rename thousands of files. Simple file renaming tools don't work, because Syncthing generally doesn't delete several thousand files within the same second, so the last digits of the timestamp are different.

This could be completely avoided by moving the timestamps from the filename into subfolders of the .stversions folder.
The current folder- and filenamestructure looks like this:

.stversions/complete/original/path/originalfilename~YYYYMMDD-hhmmss.ext

I would suggest to put all files from within 1 day increments in the same folder with subfolders for hours, minutes and seconds:
.stversions/YYYYMMDD/hhmmss/complete/original/path/originalfilename.ext

This way the first folder level doesn't get an unreasonable number of subfolders, while one is probably interested in all deleted files from one day, which can be easily found and merged back together.

If you would consider implementing this (imho rather easy but important step in improving the restorability), would you prefer this to be the new default and existing .stversions folders will be ported to the new format. Or would you prefer adding a new option?
If the latter, one could also let the user declare the preferred structure without much additional effort.

**Comment by AudriusButkevicius** [comment] 2017-10-25 22:50
This is plain confusing, as I now have to use search to find when the file got deleted, as I have no idea which directory it landed in. Worse, what if I don't remember the exact name?

**Comment by imsodin** [comment] 2017-10-26 06:48
I don't agree that it is unreasonable, it is just another use case: If you know/are interested in when the change happened, the proposed scheme totally makes sense, if you know/are interested in a particular file or just "browsing", the existing scheme is better. Apart from doing hardlink magic (not an option), I guess the only way to combine the two is adding an abstraction (i.e. create such a restoring Ui).

**Comment by calmh** [comment] 2017-10-26 08:47
So I think the main thing here is that there *is* no restorability on more than the single file level.

If we were to offer something that looks to the user like "restore this directory to the state it was at $time" we would need to know which files were *not* in it at that time, which files were created and renamed since, and so on, and none of this information is in the versions dir. So any functionality that looks like restoring directories as a whole is going to be incorrect and broken. Changing the naming isn't going to help. If we wanted to offer that sort of restorability we would need to track a whole bunch of more metadata, and we would also run straight into the issue that it then seems like it would be able to rewind local changes, which it wont...

What the versioning scheme gives today is the ability to move back in time per file.

**Comment by generalmanager** [comment] 2017-10-26 17:41
@calmh My proposal wasn't meant to offer a whole restore UI, but to make the restoration process of lots of accidentally deleted big directory trees and/or lots of files less painfull. And that with minimal coding effort. No UI needed, it should just be a step in this direction to make restoration easier. I can also open a new ticket, if you'd prefer that.
With the described usecase one generally has:
- Knowledge of the approximate day+time of deletion. Even if not, du -h -d 2 will give a good idea when big files/lots of files were deleted.
- Local file/folder structure mostly intact, but missing lots of files scattered across the file system or one/several directories with lots of subdirectories.
- A ton of renamed files in the .stversions folder of another device, but the ones I'm interested in are bunched together with lots of old files I don't want. So I have to scan every folder to approximate the period it took to delete the files and sync the deletion progress to the other device. Then I have to cobble together a script to hopefully select the right versions and rename them, bearing in mind that most of them have different timestamps.

With my proposal the workflow would be this:
- Choose the folder of the approximate deletion, maybe narrow it down with du -h -d 1.
- Copy the whole folder from the remote device to the local device.
- Merge folders by copying/rsync/whatever. No renaming and very little directory scanning involved.

So for the usecase I laid out a boolean option in the advanced options would be enought to switch between the current and the proposed folder structure. Either deleting or porting the existing .stversions folder, depending on how much time you are willing to spend on this. But if it's not too much effort, custom structures with variables for path, file name and timestamp would be awesome, as I'm sure some people would prefer something else depending on their usecase.

@AudriusButkevicius As @imsodin wrote, it depends on the use case. If you are looking for one or few specific file(s) and know it's/their destination the current setup is preferable.

If you don't remember the exact name and path, I'd assume my proposal would work better, because you are probably missing it (why else would you look for it) so you should have a general idea when the file disappeared. Then you don't have to search in every folder and subfolder (like now) to look for it. But this is probably an edge case, depending on whether or not the approximate time of deletion is known.

But for the use case I layed out (accidental or bug related deletion of big directories) the current way is truly a pita, as all filenames are modified, but with different timestamps.

**Comment by calmh** [comment] 2017-10-26 17:53
I hear you. So in this case it's reasonably easy to replicate with the external versioner. It doesn't get the to-the-seconds time of the *pull iteration* that we could do internally, but could create the hierarchy either to just the minute of the time, or see if there is already a directory within a few minutes of the current time. Then it's just an mv.

**Comment by generalmanager** [comment] 2017-10-26 18:17
Yes, I figured that a similar functionality could be achived with the external versioner. But IMHO we should either offer this functionality as a ready-to-go template for the external versioner and mention it generously in the documentation and maybe in the UI, or actually integrate it into syncthings staggered versioning concept.

Why do I consider this important? I think this use case is more common than one might think. I do have rather large repos and sync-setups (several servers, 1-3TB each). But this is mainly because 15-20 people are actively using this to share their pictures, music, movies and documents. And most of them have asked me in the last two years how they can restore this big folder they accidentally deleted, or all the *.mp3 files they intended to rename but deleted and so on. And they weren't too happy when I told them they'd have to rename hundreds of files. 

So even I had to write the same renaming script three times before I spent the time to dig deep enough to discover the possibilities of the external versioner. But I'm sure there are more non-techy users of Syncthing suffering from this than people who aren't afraid to write their own versioning script.

Maybe this would be worthy of discussion in the forum? What do you think?

**Comment by AudriusButkevicius** [comment] 2017-10-26 18:33
So we should add command line option for restoring into syncthing as a minimum. The naming scheme is consistant, so it's not too hard.

**Comment by shantanugoel** [comment] 2017-10-31 06:06
Just as a suggestion/reference, there's this project that implements a CLI for restoring files albeit in python. https://github.com/madmickstar/restorething

**Comment by nelsonkhan** [comment] 2017-11-04 04:50
Is the process for restoring files a completely manual process at this point?

**Comment by Ferroin** [comment] 2017-11-06 13:58
Yes, it's functionally completely manual (though as the link given by @shantanugoel indicates, it's not hard to automate in most scripting languages).

**Comment by julienrobin28** [comment] 2017-12-16 23:04
Hi, 
Just noticed this discussion, today I've done a GUI for that (restore from .stversions files using from/to datetimes), using Qt in order to have it working on any OS. 

![image](https://user-images.githubusercontent.com/33288584/34075137-7b976c6a-e2bd-11e7-8f66-0ac9c114852e.png)

Since I was planning to submit it to Syncthing's User Contributions, I've already taken care of having something rigorous with layout, resizes, error handling indicated into messages, no overwrite if not wanted... simple but must have.

https://github.com/julienrobin28/Syncthing-Restore

If there is something with the License do not hesitate to tell me, I choose GPL3 by default but if another License should be used it's of course possible.

**Comment by vincentardern** [comment] 2017-12-21 00:14
@julienrobin28 This is amazing news! I'd like to give this a try sometime in Jan when I have some time.

**Closed** 2018-01-01 14:39 UTC
Labels: enhancement
