### ISSUE TITLE
Master folder exception patterns

### ISSUE THREAD

**Issue by BETLOG** [syncthing/syncthing#2097] opened 2015-07-29 10:50 UTC
Master folder exception patterns:
ie:
an .stMasterExempt file list
To enable a Master folder to have some components which are treated like regular non-master syncs, and be automatically propagated globally without the "Override changes" dialog.
eg:
/music is stored on //server as a Master Folder
X.playlist is stored in //server/music and thereby pushed to //device/music
Normal Master folder behaviour ignores and destroys any alterations made to //device/music/X.playlist
However it is desirable to edit existing, and generate new .playlist files on //device, and have //server accept this type of files _back_ into the //server/music Master Folder, as per a normal sync.

---

//server/music/.stMasterExempt

(?i)_.playlist
(?i)_.m3u
(?i)*.pls

---

Topic source:
https://forum.syncthing.net/t/suggestion-folder-master-override-changes-info-and-include-exception/5257

**Comment by calmh** [comment] 2023-03-10 13:56
Duplicate of #2710

**Closed by calmh** 2023-03-10 13:56 UTC
Labels: enhancement
