### ISSUE TITLE
Syncthing v1.27.11 on desktop claims there are Local Additions for all folders from Android v1.27.10

### ISSUE THREAD

**Issue by mcexit** [syncthing/syncthing#9677] opened 2024-09-03 19:18 UTC
### What happened?

After upgrading to Syncthing v1.27.11 on my desktop, it claims all my receive-only folders have Local Additions. These are being synced from Syncthing on Android v1.27.10. Reverting to v1.27.10 on desktop and disabling upgrades fixes the issue. Comparing hashes of the files shows that they never changed.

### Syncthing version

v1.27.11

### Platform & operating system

Windows x64

**Comment by Knaspin** [comment] 2024-09-03 19:52
Having the same issue. Also checked hashes between files and they remained unchanged.

This seems to only affect Syncthing 1.27.11 on Windows. Other clients do not show "Local Additions" after syncing.

**Comment by tomasz1986** [comment] 2024-09-03 22:07
I can confirm the issue. It happens when using v1.27.11 on Windows. The Android side can still be on v1.27.10 (or older).

I've compared a sample file. The left is Android, the right is Windows.

![image](https://github.com/user-attachments/assets/e4b5a315-ae9f-42ad-affe-a05a6c6d5fbc)

**Comment by tomasz1986** [comment] 2024-09-03 22:34
I've narrowed down the culprit to https://github.com/syncthing/syncthing/commit/7517d18fbbf34b42aa3d4b231018d2ee704a159d.

**Comment by imsodin** [comment] 2024-09-04 04:59
The info from the mtimefs layer is missing in 1.27.11, resulting in truncated mtime and thus the difference.

> I've narrowed down the culprit to https://github.com/syncthing/syncthing/commit/7517d18fbbf34b42aa3d4b231018d2ee704a159d.

That certainly makes sense in that said PR touches the filesystem layer. However I have no clue yet what happens/goes wrong. Just in case there's an additional hint to be had there: What exactly did you do to narrow that down?

**Comment by imsodin** [comment] 2024-09-04 05:04
Also could you check the involved filenames on disk on devices - any case differences? E.g. the ".pdf" being ".PDF" somewhere else.

**Comment by imsodin** [comment] 2024-09-04 05:30
The `err: {}` for mtime also looks suspicious - in other places that's `err: null`.

**Comment by tomasz1986** [comment] 2024-09-04 06:49
> What exactly did you do to narrow that down?

Sorry for being too brief (it was late at night 🙁). I just cherry-picked the commit on top of v1.27.10.

> Also could you check the involved filenames on disk on devices - any case differences? E.g. the ".pdf" being ".PDF" somewhere else.

That's not it for sure. All files in my random test folder were marked as "local additions", with no exception.

Just for the record, what I did specifically when testing was:

1. Still at v1.27.10 on both sides, share the `/sdcard/Download` folder from Android to a Windows device.
2. Accept the folder on Windows as Receive Only under a completely new path, and let it sync.
3. At this point, the folder is "Up to Date" on both sides.
4. Shut Syncthing down on Windows, upgrade it to v1.27.10+7517d18, then restart.
5. All files in the folder are now marked "local additions".

> @tomasz1986 If you could provide debug logs with scanner and walkfs logs while reproducing the issue, that would be great too. If you can reproduce in isolation with a single file, that's of course best, but I'll also take huge dumps to sift through (privately if necessary). For reproducing I'd almost bet you need to set it up on 1.27.10 to get the file into the DB, and then upgrade - I would not be surprised if directly starting on 1.27.11 doesn't show the same problem.

Will provide the logs soon 🙂.

**Comment by calmh** [comment] 2024-09-04 06:54
I didn't look at the code yet, but I suspect this is a question of mtimefs wrapping. The loss of precision in the timestamp looks like we're now looking at the raw on-disk timestamp instead of the one returned by mtimefs.

**Comment by imsodin** [comment] 2024-09-04 07:39
Yep, indeed. I tried to write a reproducer based on that assumption but failed. Do you spot anything wrong with it? https://github.com/syncthing/syncthing/pull/9680

**Comment by calmh** [comment] 2024-09-04 08:06
So a couple of things that may be relevant, the mtimefs has a case insensitivity option that I don't see that we ever set (?) and I wonder if the switcheroo makes a difference if we no longer case-sanitise the folder root?

**Comment by tomasz1986** [comment] 2024-09-04 09:12
This is a debug log from the Windows side:

[syncthing-windows.log](https://github.com/user-attachments/files/16865035/syncthing-windows.log)

Do you need the same from the Android side?

**Comment by imsodin** [comment] 2024-09-04 09:37
> mtimefs has a case insensitivity option that I don't see that we ever set (?) 

That confused me too when I created the test. As far as I see it never was used except for tests. So I just ignored it.

> if we no longer case-sanitise the folder root for walking, making the existing mtimefs entries no longer match?

mtimefs stores it's stuff by relative paths, so the root being sanitised or not shouldn't matter. And we anyway never case-resolve the root. Actually we never "resolve" a case ever, we only complain if there's a case conflict. We do not change the casing to the "correct one" in the case filesystem layer. That's why I fail to see how changing the order could lead to not finding entries in mtimefs. It very mouch looks like that's happening though. Then again if all files are affected, it might not even be directly related to case lookups.

@tomasz1986 Haven't yet have time to look at the logs - thanks for providing them. I don't think the android side is relevant at all except maybe for context, so no debug logging there should be fine.

**Comment by akronym0** [comment] 2024-09-04 10:56
I also encountered this bug. Android and Linux synchronization. All Linux "receive only" folders showed the "local additions" message even though there were no local additions. Downgrading to 1.27.10 solved this issue.

**Comment by nathanielcwm** [comment] 2024-09-04 14:14
This problem also affects send & receive folders on Linux on 1.27.10.

**Comment by milroneth** [comment] 2024-09-04 20:33
I'm on Windows, Syncthing 1.27.11
My observation if it helps: it does this even when it has never talked to the other devices to know if anything actually changed. I know this as I have a second Android phone that syncs in send-only and has been off since Syncthing updated on my PC which is receive-only, but it still shows Local additions. It is not all files in the receive-only folder, only some of them.

I also have another folder that is receive-only, that was originally shared with 2 other devices which I have since removed but I kept the folder (unshared). I am not 100% sure, but from looking at the "Local additions" to this specific folder that I can kinda recognise by eye, it seems to affect all the files that have been changed and pulled since the original sync. So the other devices had around 3500 text files in said folder which I pulled when I set up the receive-only folder on my PC, some of them changed over time, until I stopped syncing it and removed those devices 2 months ago.

Now it shows 145 files as local additions and from my understanding it's all the files that were edited during the time that sync was running on it, but none that was only pulled once at first run.

Not sure if any of this might point to a specific part of the codebase, but it may click to people that understand it.

**Comment by Mzdyl** [comment] 2024-09-05 02:53
In the same situation, on Mac (sending) and Windows (receiving) platforms, files synchronized perfectly in version 1.27.10, but in version 1.27.11 on the Windows side, the locally added files are displayed. Moreover, the bug seems to be related to time; my two computers had a 3-minute time difference. After updating the time, the number of locally added files decreased from over 8,400 to over 8,100.

**Comment by calmh** [comment] 2024-09-05 14:31
So I've found the problem, just need to hack up a neat solution to it as well.

**Closed** 2024-09-06 07:39 UTC
Labels: bug
