### ISSUE TITLE
read timeout and the sync server becomes unresponsive

### ISSUE THREAD

**Issue by andrewufrank** [syncthing/syncthing#2815] opened 2016-03-05 09:30 UTC
i have 3 sync server (cubietruck armhf running debian and synchting 0.12.19). i observe in the systectl status log regularly that they close connectin for 'read timeout'. then the server becomes semi-dead: if i open the gui (on another computer) i get for all connections a blank (neither connected nor disconnected shown). 
this happens typically if the remote has received a massive update in a folder or an additional other server to share a folder. 
i would expect that the remote (server) is recovering gracefully from overload and eventually achieves 'up to date'.
 
### Version Information
Syncthing Version: v012.19 (arm)
OS Version: debian jessie (on the remote server). up to data

**Comment by AudriusButkevicius** [comment] 2016-03-05 11:03
This is because the device you are using has a CPU of a calculator, and syncthing being very heavy on crypto is not the best candidate to run on calculators.

**Comment by andrewufrank** [comment] 2016-03-05 16:51
i understand the limitations of arm v7 and expect a slower behaviour, but not silent semi-death. i appreciate the use of crypto to ensure data is not accessible to others. still, systems with slower calculators should just run slower, not fail. 
eventually, with several restarts, the servers become synced and everything works. - i believe a net of 2 or 3 small synced servers (<200 Euro including disks) is a perfect use case for syncthing and gives much better protection against loss of data than any other i can imagine. i was not able to find intel chip based systems for the same price and with the same power consumption, thus i would appreciate any improvement for the arm v7 processor. 
thank you!

**Comment by AudriusButkevicius** [comment] 2016-03-05 17:00
I am closing this as I think there is nothing we can do here, so you just have to accept the fact that it will be slow, and will not respond to GUI requests sometimes, as this is due to the hardware its running on.

**Closed by AudriusButkevicius** 2016-03-05 17:00 UTC

**Comment by andrewufrank** [comment] 2016-03-05 17:16
i do accept running slow, and that is is not responding to gui sometimes - ok.
BUT : i think there is a bug somewhere how concurrent processes are handled leading/causing read timeout (could i set the accepted delays higher?) and then go to a semi-dead state (infinite wait for something?). 
the gui in this situation is permanently showing the list of other servers with blank info (neither connected nor disconnected). such a state should never be reached and is pointing to some bug.

**Comment by AudriusButkevicius** [comment] 2016-03-05 17:26
From your description it's not even obvious where the timeout happens, or which connections you are talking about.

You haven't provided any logs, and you haven't provided any reproduction steps (especially on a device that is not yours), so you can think it's a bug, but I very much doubt that, atleast until we have some evidence.

**Comment by canton7** [comment] 2016-03-05 17:53
What you're reporting is consistent with what I saw when I tried to run Syncthing on a pi, and with what many users have subsequently reported. That family of devices are simply incredibly low-power which aren't powerful enough to run Syncthing, if you're synchronising a large amount of data. 

I've found an Odroid-C1 is powerful enough to run Syncthing over a hundred gigs or so... How does your SBC compare specs-wise?

**Comment by andrewufrank** [comment] 2016-03-06 12:40
i run it on cubietrucks (which report an encoding speed of 7 mb/s when syncthing starts). they have 1tb disk on sata, 2 cores and 2GB of memory. i think of replacing them with odroids xu4 (4 + 4 cores, report 30 mb/s encoding, really nice machines, even working on a xfce desktop is comfortable). 
at the moment the behavior is reproducible, but not likely on a test setup (300 gb of data) and the whole ran fine till i thought of replacing a node (taking one out for long time keeping) and adding a new one. and i am nearly through  - the problem is that the 'folder x is shared with device y" are occasionally lost. i just moved to 19.20. i will try to send SIGQUIT and capture the output. 

thank you for your help!

**Comment by AudriusButkevicius** [comment] 2016-03-06 12:49
7mb/s is as bad as RPI. Folder X shared with Y being lost is a different issue that is not related to this.

**Comment by andrewufrank** [comment] 2016-03-07 23:33
it seems that my problems are mostly resolved (they are the result of some massive changes). thank you for your help - especially the hint that sharing of folders being lost is a different point. i will report back if i observe it again and try to document the circomstances. 
-
when i was testing raspi i saw closer to 1 or 3 mb/s of encoding. what is the performance of the odroid-c1
