### ISSUE TITLE
Version 1.27.0+ not work on Windows Server 2008 R2

### ISSUE THREAD

**Issue by rampageX** [syncthing/syncthing#9403] opened 2024-02-06 11:01 UTC
Syncthing version 1.27.0+ include 1.27.1, 1.27.2 and 1.27.3 can not start on Windows Server 2008 R2, both x86 or x64 version.

1.27.0 working fine.

Log:

```
Exception 0xc0000005 0x8 0x0 0x0
PC=0x0
runtime.asmstdcall()
	runtime/sys_windows_amd64.s:65 +0x75 fp=0x22fca0 sp=0x22fc80 pc=0x473eb5
rax     0x0
rbx     0x1a43f00
rcx     0x1aa4240
rdi     0x7fffffde000
rsi     0x22fea0
rbp     0x22fde0
rsp     0x22fc78
r8      0x0
r9      0x22fee0
r10     0x1a75a18
r11     0x21
r12     0x22fec0
r13     0x1
r14     0x1a43360
r15     0x0
rip     0x0
rflags  0x10293
cs      0x33
fs      0x53
gs      0x2b
Exception 0xc0000005 0x8 0x0 0x0
PC=0x0
runtime.asmstdcall()
	runtime/sys_windows_amd64.s:65 +0x75 fp=0x22fca0 sp=0x22fc80 pc=0x473eb5
rax     0x0
rbx     0x1a43f00
rcx     0x1aa4240
rdi     0x7fffffde000
rsi     0x22fea0
rbp     0x22fde0
rsp     0x22fc78
r8      0x0
r9      0x22fee0
r10     0x1a75a18
r11     0x21
r12     0x22fec0
r13     0x1
r14     0x1a43360
r15     0x0
rip     0x0
rflags  0x10293
cs      0x33
fs      0x53
gs      0x2b
Exception 0xc0000005 0x8 0x0 0x0
PC=0x0
runtime.asmstdcall()
	runtime/sys_windows_amd64.s:65 +0x75 fp=0x22fca0 sp=0x22fc80 pc=0x473eb5
rax     0x0
rbx     0x1a43f00
rcx     0x1aa4240
rdi     0x7fffffde000
rsi     0x22fea0
rbp     0x22fde0
rsp     0x22fc78
r8      0x0
r9      0x22fee0
r10     0x1a75a18
r11     0x21
r12     0x22fec0
r13     0x1
r14     0x1a43360
r15     0x0
rip     0x0
rflags  0x10293
cs      0x33
fs      0x53
gs      0x2b
Exception 0xc0000005 0x8 0x0 0x0
PC=0x0
runtime.asmstdcall()
	runtime/sys_windows_amd64.s:65 +0x75 fp=0x22fca0 sp=0x22fc80 pc=0x473eb5
rax     0x0
rbx     0x1a43f00
rcx     0x1aa4240
rdi     0x7fffffde000
rsi     0x22fea0
rbp     0x22fde0
rsp     0x22fc78
r8      0x0
r9      0x22fee0
r10     0x1a75a18
r11     0x21
r12     0x22fec0
r13     0x1
r14     0x1a43360
r15     0x0
rip     0x0
rflags  0x10293
cs      0x33
fs      0x53
gs      0x2b
```

**Comment by imsodin** [comment] 2024-02-06 11:16
Duplicate of https://github.com/syncthing/syncthing/issues/9282

**Closed by imsodin** 2024-02-06 11:16 UTC
Labels: bug, needs-triage
