### ISSUE TITLE
Deleting/moving directory on Android causes error: folder marker missing (this indicates potential data loss, search docs)

### ISSUE THREAD

**Issue by DerekCaelin** [syncthing/syncthing#9583] opened 2024-06-14 19:12 UTC
### What happened?

A sequence of folder deletion and movement results in erronious errors, including permissions warning and: `folder marker missing (this indicates potential data loss...`

## Steps to reproduce
Using web GUI

1. Client - Create folder "A" 
2. Server -  Share folder "B" with client device
3. Client -  Accept share, sync files with folder "A"
4. Client -  "Remove" shared folder
5. Server -  Unshare folder "B" with client device, save
6. Server -  share folder "B" with client device, save
7. Client -  accept the share (any location)
8. See issue

## Expected behavior
Sync between folder B and folder A proceeds normally

## Actual behavior
In main UI, error messages include a permissions warning, share rules are "Send Only"
In Web GUI, sync is "stopped", error message `folder marker missing (this indicates potential data loss...`

## Resolution
The issue is resolved by:
1. Server - Remove folder "B" and end share with client
2. Server - Create new folder "C" (linked to the same directory) and share with client
3. Client - Accept share, sync proceeds normally

### Syncthing version

v1.27.6

### Platform & operating system

Android 11 (Client), Linux Mint (Server)

**Comment by kuba-orlik** [comment] 2024-09-30 11:02
I'm also experiencing this issue, it seems that the ID of the folder is persisted somehow by the client after deleting it

**Comment by tomasz1986** [comment] 2024-11-24 20:05
Closing as duplicate of https://github.com/syncthing/syncthing/issues/8416.

**Closed by tomasz1986** 2024-11-24 20:05 UTC
Labels: bug, needs-triage
