### ISSUE TITLE
Deletion does not work.

### ISSUE THREAD

**Issue by maxim-boligatov** [syncthing/syncthing#1331] opened 2015-02-05 11:25 UTC
When I delete some folder inside tracked directory those changes are not applied to remote host. I pressed Rescan, restarted syncting... but it does not work. After deletion adding of files does not work as well... it still shows N items, but I just added new one and pressed rescan. It should be N+1. I am using last version and 2 windows hosts (Windows 7 x64 Enterprise and Ultimate).

Initial sync was OK.

**Comment by AudriusButkevicius** [comment] 2015-02-05 19:43
Do you have rate limiting enabled?
Also, you could run syncthing with `STTRACE=model` enironment variable to see what it is actually doing.

**Comment by maxim-boligatov** [comment] 2015-02-06 08:08
If you mean scan timeout then it is 60 seconds. If it is some specific settings then I do not know what you mean. All settings are default except added directory for sync. I will try to use STTRACE=model.

**Comment by maxim-boligatov** [comment] 2015-02-06 08:50
I enabled STTRACE. I have added file test.txt to root of my disk E. Nothing strange happens:

[SNQCS] 2015/02/06 11:47:25.116818 puller.go:148: DEBUG: puller/Software@0xc08a2e13b0 skip (curVer == prevVer) 130208
[SNQCS] 2015/02/06 11:47:25.788856 puller.go:212: DEBUG: puller/Software@0xc08a2e13b0 rescan
[SNQCS] 2015/02/06 11:47:32.722253 puller.go:226: DEBUG: puller/Software@0xc08a2e13b0 next rescan in 56.862315358s
[SNQCS] 2015/02/06 11:47:32.722253 puller.go:148: DEBUG: puller/Software@0xc08a2e13b0 skip (curVer == prevVer) 130208
[SNQCS] 2015/02/06 11:47:33.722310 puller.go:148: DEBUG: puller/Software@0xc08a2e13b0 skip (curVer == prevVer) 130208

Can it be problem that it is root of partition? It looks strange because in settings it shows E: and not E:\

**Comment by AudriusButkevicius** [comment] 2015-02-06 09:15
Seems a duplicate of #1130 . If you open config.xml it should have the \ appended at the end automatically.

**Comment by maxim-boligatov** [comment] 2015-02-06 14:04
Now I have tested it a bit more. I have manually changed in config E: to E:\ and have started Syncthing. Synchronization is started once again... Now any new file is normally transferred to other side and deleted file is also removed as well. So I think it can be bug with folder name. But of course it still can be dependent on some other issues.

**Comment by AudriusButkevicius** [comment] 2015-02-06 14:42
If the path was somehow wrong, it should cough up some more complicated errors.

**Closed** 2015-02-25 20:17 UTC
