### ISSUE TITLE
SyncThing Stopped shortly after starting.

### ISSUE THREAD

**Issue by SunsparcSolaris** [syncthing/syncthing#2492] opened 2015-11-19 15:41 UTC
I'm using SyncThing inside of SyncTrayzor, who has directed me to post an issue here after viewing SyncTrayzor's log.

SyncThing will stop shortly after starting with no warning, just "SyncThing stopped" message inside of SyncTrayzor.

Here is the log from SyncTrayzor:
http://pastebin.com/VJn6Nvk1

**Comment by AudriusButkevicius** [comment] 2015-11-19 15:46
We need syncthing log, not synctrayzors log.

**Comment by calmh** [comment] 2015-11-19 15:47
There is some syncthing log in there. But:

```
2015-11-19 10:22:14.9120 [Debug] SyncTrayzor.SyncThing.SyncThingProcessRunner: [HO6DB] 10:22:14 INFO: Completed initial scan (rw) of folder tron 
... nothing from syncthing
2015-11-19 10:24:27.7646 [Debug] SyncTrayzor.SyncThing.EventWatcher.SyncThingEventWatcher: Received 1 events 
2015-11-19 10:24:27.7646 [Debug] SyncTrayzor.SyncThing.EventWatcher.SyncThingEventWatcher: <GenericEvent ID=610 Type=FolderCompletion Time=11/19/2015 10:24:27 AM> 
2015-11-19 10:24:36.0550 [Info] SyncTrayzor.SyncThing.SyncThingProcessRunner: Syncthing process stopped with exit status -1073741790 
```

So we were alive and well, and sent a FolderCompletion event, then suddenly stopped? We need a panic log or something here. Also the exit code seems weird - @canton7 ?

**Comment by SunsparcSolaris** [comment] 2015-11-19 15:51
The last write to \AppData\Local\SyncThing\syncthing.log is from Oct 14th, so very old. References the Ant version. Am I looking in the right place?

**Comment by canton7** [comment] 2015-11-19 15:51
(ref canton7/synctrayzor#177)

The exit code is reported verbatim: the process simply quit with that code - don't you give weird and wonderful codes in some cases?

Worth checking for a panic log, maybe?

**Comment by canton7** [comment] 2015-11-19 15:51
Syncthing doesn't log on Windows any more I think - known bug. The SyncTrayzor log contains all Syncthing output though.

**Comment by calmh** [comment] 2015-11-19 15:52
We can't get as weird and wonderful as that as the exit code is a single byte. :) That exit code is however 34 with two high bits set. We don't exit 34 under any circumstances that I know of either...

**Comment by canton7** [comment] 2015-11-19 15:55
0xC0000002 seems to be a not-uncommon exit code in Windows

**Comment by canton7** [comment] 2015-11-19 15:57
0xC0000022 seems to be a not-uncommon exit code under Windows

**Comment by canton7** [comment] 2015-11-19 15:58
Yeah, `STATUS_ACCESS_DENIED` from here: https://msdn.microsoft.com/en-gb/library/cc704588.aspx

**Comment by calmh** [comment] 2015-11-19 16:03
Oookay... So we crash with that, about three minutes in... The timing is a bit off, otherwise the best guess I can have that could possibly cause this would be that the usage report kicks in, which runs memorySize() which loads kernel32.dll, which - if that can't be loaded - could possibly be a hard crash?

**Comment by calmh** [comment] 2015-11-19 16:03
Because as far as I can tell, this must be something close to a SIGSEGV, i.e. a hard stop from the OS itself where we get no say in the matter or even a chance to panic.

**Comment by SunsparcSolaris** [comment] 2015-11-19 16:07
On the initial load of SyncTrayzor, it does take SyncThing a few minutes to stop. Once started again, it only takes about 10 seconds to stop again.

**Comment by canton7** [comment] 2015-11-19 16:09
Worth enabling `STTRACE=all` and seeing what the last traced event is?

**Comment by calmh** [comment] 2015-11-19 16:10
Absolutely.`STTRACE=all` please.

**Comment by SunsparcSolaris** [comment] 2015-11-19 16:30
Input STRACE=all into SyncTrayzor's SyncThing Env Variables field, the log file ballooned to ~15MB. Had to upload it:

https://www.bwmhost.us/SyncTrayzor.log

**Comment by canton7** [comment] 2015-11-19 16:34
Lines before the crash:

```
2015-11-19 11:10:32.2981 [Debug] SyncTrayzor.SyncThing.SyncThingProcessRunner: [HO6DB] 2015/11/19 11:10:32.300127 leveldb_transactions.go:91: DEBUG: update global; folder="tron" device=L3JP4R2 file="tron/resources/stage_3_disinfect/sophos_virus_remover/engine/xvdl90.vdb" version=[{3954809488550820319 1} {4092660858925001817 1} {4099005133925650137 1} {4304368957648313532 4} {6832803166830252255 4} {7464274563869553528 16} {10490806781379491891 1} {10544433294757843627 1} {10885981539294810269 1} {14720736360115309902 1} {18151752594311116645 1}] 
2015-11-19 11:10:32.2981 [Debug] SyncTrayzor.SyncThing.SyncThingProcessRunner: [HO6DB] 2015/11/19 11:10:32.302127 leveldb_transactions.go:188: DEBUG: new global after update: {{[{3954809488550820319 1} {4092660858925001817 1} {4099005133925650137 1} {4304368957648313532 4} {6832803166830252255 4} {7464274563869553528 16} {10490806781379491891 1} {10544433294757843627 1} {10885981539294810269 1} {14720736360115309902 1} {18151752594311116645 1}], L3JP4R2}, {[{3954809488550820319 1} {4092660858925001817 1} {4099005133925650137 1} {4304368957648313532 4} {6832803166830252255 4} {7464274563869553528 16} {10490806781379491891 1} {10544433294757843627 1} {10885981539294810269 1} {14720736360115309902 1} {18151752594311116645 1}], 7777777}, {[{4304368957648313532 1} {7464274563869553528 5} {10490806781379491891 1} {18151752594311116645 1}], SJKVUNX}, {[{4304368957648313532 1} {7464274563869553528 5} {10490806781379491891 1} {18151752594311116645 1}], ZRFI7OO}, {[{4304368957648313532 1} {7464274563869553528 5} {10490806781379491891 1} {18151752594311116645 1}], 6N2A26W}, {[{4304368957648313532 1} {7464274563869553528 5} {10490806781379491891 1} {18151752594311116645 1}], 4UMYHPB}, {[{4304368957648313532 1} {7464274563869553528 5} {10490806781379491891 1} {18151752594311116645 1}], X2K6WYU}} 
2015-11-19 11:10:32.2981 [Debug] SyncTrayzor.SyncThing.SyncThingProcessRunner: [HO6DB] 2015/11/19 11:10:32.303127 leveldb_transactions.go:74: DEBUG: insert; folder="tron" device=L3JP4R2 File{Name:"tron/resources/stage_3_disinfect/sophos_virus_remover/engine/xvdl91.vdb", Flags:0777, Modified:1441127684, Version:[{3954809488550820319 1} {4092660858925001817 1} {4099005133925650137 1} {4304368957648313532 4} {6832803166830252255 4} {7464274563869553528 16} {10490806781379491891 1} {10544433294757843627 1} {10885981539294810269 1} {14720736360115309902 1} {18151752594311116645 1}], Size:600368, Blocks:[Block{0/131072/6a1f5f7138c46a57e803abf7257f468684984b90ce4014cbde57013f26113258} Block{0/131072/e7b222fb0c1027093f912c24a709b069224be7ac7f561d6bc898d2ae0e8256fa} Block{0/131072/a2e1a3d16e5f939e2413fe07036387203c11bdf499b1f22cd4539d9d506e8196} Block{0/131072/9f46e1fad8f9c5aec031a2b972b367ee0b29e17306208a9793c835db9b4c89fe} Block{0/76080/bf700224d64b6d257ce3c48298273c829ef82d51f24645a3004047909d679c8b}]} 
2015-11-19 11:10:32.2981 [Debug] SyncTrayzor.SyncThing.SyncThingProcessRunner: [HO6DB] 2015/11/19 11:10:32.304127 leveldb_transactions.go:91: DEBUG: update global; folder="tron" device=L3JP4R2 file="tron/resources/stage_3_disinfect/sophos_virus_remover/engine/xvdl91.vdb" version=[{3954809488550820319 1} {4092660858925001817 1} {4099005133925650137 1} {4304368957648313532 4} {6832803166830252255 4} {7464274563869553528 16} {10490806781379491891 1} {10544433294757843627 1} {10885981539294810269 1} {14720736360115309902 1} {18151752594311116645 1}] 
2015-11-19 11:10:32.2981 [Debug] SyncTrayzor.SyncThing.SyncThingProcessRunner: [HO6DB] 2015/11/19 11:10:32.307128 leveldb_transactions.go:188: DEBUG: new global after update: {{[{3954809488550820319 1} {4092660858925001817 1} {4099005133925650137 1} {4304368957648313532 4} {6832803166830252255 4} {7464274563869553528 16} {10490806781379491891 1} {10544433294757843627 1} {10885981539294810269 1} {14720736360115309902 1} {18151752594311116645 1}], L3JP4R2}, {[{3954809488550820319 1} {4092660858925001817 1} {4099005133925650137 1} {4304368957648313532 4} {6832803166830252255 4} {7464274563869553528 16} {10490806781379491891 1} {10544433294757843627 1} {10885981539294810269 1} {14720736360115309902 1} {18151752594311116645 1}], 7777777}, {[{4304368957648313532 1} {7464274563869553528 5} {10490806781379491891 1} {18151752594311116645 1}], SJKVUNX}, {[{4304368957648313532 1} {7464274563869553528 5} {10490806781379491891 1} {18151752594311116645 1}], ZRFI7OO}, {[{4304368957648313532 1} {7464274563869553528 5} {10490806781379491891 1} {18151752594311116645 1}], 6N2A26W}, {[{4304368957648313532 1} {7464274563869553528 5} {10490806781379491891 1} {18151752594311116645 1}], 4UMYHPB}, {[{4304368957648313532 1} {7464274563869553528 5} {10490806781379491891 1} {18151752594311116645 1}], X2K6WYU}} 
2015-11-19 11:10:32.4381 [Info] SyncTrayzor.SyncThing.SyncThingProcessRunner: Syncthing process stopped with exit status -1073741790 
```

**Comment by calmh** [comment] 2015-11-19 16:39
That's just a database update like a million others.... 

@SunsparcSolaris can you run syncthing from the command line and see if it behaves the same, and if it mentions a panic log or so when it restarts in that case?

**Comment by SunsparcSolaris** [comment] 2015-11-19 16:58
Started SyncThing from SyncTrayzor's folder, no issues so far. Still running after 15 minutes.

**Comment by canton7** [comment] 2015-11-19 17:00
1. Try running it with `-no-restart`
2. Under File -> Settings -> Syncthing, do you have 'Use Syncthing's default database location' checked?

**Comment by SunsparcSolaris** [comment] 2015-11-19 17:02
Default DB is checked in SyncTrayzor's settings.

What do I need to run with that option? SyncThing or SyncTrayzor?

**Comment by canton7** [comment] 2015-11-19 17:03
Syncthing. So open a command window inside `C:\Users\<You>\AppData\Roaming\SyncTrayzor`, and run `syncthing.exe -no-restart`

**Comment by SunsparcSolaris** [comment] 2015-11-19 17:17
Still working fine.

**Comment by canton7** [comment] 2015-11-19 17:27
Ok... Try `syncthing.exe -no-browser -no-restart -gui-apikey=123456 -gui-address=https://localhost:8384/`

That's how SyncTrayzor launches it....

**Comment by SunsparcSolaris** [comment] 2015-11-19 17:42
Still fine, aside from Chrome throwing a warning about the https gui. Nothing in the console about any errors or warnings.

**Comment by canton7** [comment] 2015-11-19 18:26
Weird. Can you try again in SyncTrayzor, just in case you've observed it magically fixing itself?

**Comment by SunsparcSolaris** [comment] 2015-11-19 20:34
Did you do some voodoo on your end? SyncTrayzor has been up for about 10 minutes now with no issues so far.

**Comment by canton7** [comment] 2015-11-19 20:40
OK, so something was happening before, independent of what's happening now, which perhaps happened to correspond with you moving to Syncthing by itself? Or maybe Syncthing was trying to do something and failing within SyncTrayzor, then succeeded when run by itself and so isn't trying to do it again..?

The other thing we didn't try was trying to run Syncthing with `C:\Program Files\SyncTrayzor` as its CWD. @calmh, should that affect anything?

**Comment by calmh** [comment] 2015-11-19 21:24
I don't think so.

**Comment by AudriusButkevicius** [comment] 2015-11-20 00:00
I wonder how does the firewall prompt get handled when syncthing is invoked by trayzor?

**Comment by canton7** [comment] 2015-11-20 07:37
In my experience, it happens as usual, as soon as syncthing is launched for the first time.

**Comment by AudriusButkevicius** [comment] 2015-11-20 09:21
Closing as the issue is gone.

**Closed by AudriusButkevicius** 2015-11-20 09:21 UTC

**Comment by canton7** [comment] 2015-11-20 09:30
I'll do the same to the issue on my end. Feel free to re-open, @SunsparcSolaris , if it reappears

**Comment by SunsparcSolaris** [comment] 2015-12-03 14:57
I just wanted to be one of those that actually posts when they solve the issue for future people to stumble on.

The issue is BitDefender Free. It was blocking the SyncThing service from running, causing SyncTrayzor to throw it's hands up, without warning. I finally managed to catch BitDefender in action blocking the service and added it to the exception list. It hasn't happened since. Beforehand, it was a daily issue, having to stop SyncTrayzor, run SyncThing on its own, then start SyncTrayzor again.

Thanks again for everyone's help.

**Comment by canton7** [comment] 2015-12-03 15:02
Gotta love the good old anti-malware programs which don't tell you what they're doing :smile: 

Thanks for getting back!
