### ISSUE TITLE
Optio to pause non-local devices on metered network

### ISSUE THREAD

**Issue by xeruf** [syncthing/syncthing#9328] opened 2024-01-07 09:41 UTC
I am on the road with my phone and laptop.
I regularly sync between them using a hotspot from my phone that also provides internet, and additionally I have a remote server that I only want to sync to when I am on an unmetered network (Wifi) to not strain my data plan.
I found out how to set the metered flag for a network connection in NetworkManager.
But now I am missing a flag in syncthing for that - for now I always pause the device and unpause it on a WiFi, but forgetting to pause it again has already cost me a bit.

Sorta relates to https://github.com/syncthing/syncthing/issues/1336

**Comment by calmh** [comment] 2024-01-07 10:37
Duplicate of #8394 I think (or at least related enough in that we'd need the functionality to see/decide something is on a metered network)

**Closed by calmh** 2024-01-07 10:37 UTC
Labels: enhancement, needs-triage
