### ISSUE TITLE
21:58:04 INFO: Puller (folder "xxxxxxxx", file "yyyyy"): pull: no available source device

### ISSUE THREAD

**Issue by odgeza** [syncthing/syncthing#2093] opened 2015-07-27 07:27 UTC
I get the no available source device on a file sometimes (not on the instance that created the file).

But the file remains unsynced even after a restart, and a rescan on both sides. Renaming the file, and renaming it back, makes it sync.

let me know what I should look at to start? The console only shows the "no available source device", but on the machine that has the file, its copyable, and renamable. As soon as its renamed back and forth everything goes back to normal.

**Comment by AudriusButkevicius** [comment] 2015-07-27 07:32
Dup. Check #2043 for data we'd be interested in. If you have steps of reproduction that would also be useful. I will also make a guess that it's Windows? Does it have some fancy file system or deduplication enabled underneath?

**Comment by AudriusButkevicius** [comment] 2015-07-27 11:08
Are you sure that the file in question is nit a memory mapped file? Also, I suggest you verify that it's really not changing with md5 or something.

**Comment by odgeza** [comment] 2015-07-27 15:04
Well, the file in question was a MS SQL transaction log backup file. Once it is created, thats it, but I had a stack of them from the weekend that were all like this, I just had to change the date, and it fixed it. 

I'll add the enviroment variable like you suggested, and wait for it to happen again.

**Comment by AudriusButkevicius** [comment] 2015-07-27 15:14
I am 99.99% sure that mysql transaction log is a memory mapped file, just like sqlite transaction log is. If you run md5 + stat you will see that the content is changing and the mtime is not. These sort of files are not supported by syncthing, because we can't reliably tell when they change. We already check size and mtime, I don't think there is anything else we could check apart from rehashing the whole file which would be an overkill.

**Comment by AudriusButkevicius** [comment] 2015-07-27 16:47
If I understand it correctly, and this is mssql binlog equivalent, then ideally you should not sync these to start with, as these are usually only used for faster recovery/replication (between nodes if enabled) on the local instance, and are not required for backups (please tell me that you are not using syncthing for sql replication)

**Comment by odgeza** [comment] 2015-07-27 16:55
Hi, 

You are jumping the gun here :)

Its not MySQL. Its MS SQL 2014. The backup is made using a 3rd party tool called Redgate SQL Backup. The Purpose is get the backups to different servers and remote sites as quickly and reliably as possible (as opposed to the altenative - FTP for remote, and SMB Shares).

The file does not change after its modification time. It is not a memory mapped file.

**Comment by AudriusButkevicius** [comment] 2015-07-27 18:20
Can you compile:
https://github.com/syncthing/syncthing/tree/master/cmd/stwatchfile

and use it to watch one of the files of the type  that you are having trouble with.
Please note this should be used one the file before or as it's being created (you can start the utility before the file exists, given you known the name), and then post the output here.

Alternatively, you can download a compiled version from here, given you trust me and OneDrive:
http://1drv.ms/1VJtpv6

**Comment by odgeza** [comment] 2015-07-27 18:32
Hi

I'm still waiting for it to happen again, it had tons of files from the weekend, but it hasn't happened once today.

I wonder if the issue might be more likely to occur under heavyload? (There are only 3 things that have changed 1) server load from VMWare server backups on the weekend 2) or if there has been a version released after last night? 3) the files on the weekend are smaller than during the weekdays (SQL usage is much less on weekend)

**Comment by AudriusButkevicius** [comment] 2015-07-27 18:37
The new version had nothing changed in the scanner.
I will close it for now.
Give a shout once it happens again.
Also STTRACE=scanner should log all the files that it's sending for scanning, hence it might be useful to run it over the weekend + the watcher I suggested.

**Closed by AudriusButkevicius** 2015-07-27 18:37 UTC

**Comment by odgeza** [comment] 2015-07-27 18:46
Thanks, will do
