### ISSUE TITLE
Gets confused about removed files (inotify)

### ISSUE THREAD

**Issue by madduck** [syncthing/syncthing#5414] opened 2018-12-29 10:47 UTC
I was researching #4599 and I think I happened upon another problem, that is related, but not quite the same.
I have three devices, two of which running the latest Syncthing DEB from your APT repo on Linux, and the third running the Android apk from FDroid.

The problem seems to arise when I move or delete files out of syncthing-control.

Most of the time when I move or delete files, the "failed items" count on the host on which I made the change will go up by the number of files I removed (one entry for each file removed with "no such file or directory" given as explanation). So it seems like syncthing picks up on the change (I am using inotify) properly, but then forgets to update its own internal file list.

This is a representative log message entry:

```
2018-12-29 11:28:00 Scanner (folder o3y5s-oaoye, file "Camera/20181109_151009(0).jpg"): scan: lstat /home/ssd/madduck/sync/sgs7e/dcim-int/Camera/20181109_151009(0).jpg: no such file or directory
```

Most of the time, the changes get propagated to the other hosts, and their "failed items" count does not increase. However, I've seen even that happening, i.e. removing 10 files on the laptop would increase the laptop's failed items count by 10, but also added 4 to the failed items count on my desktop. The reason given there was also the same (as is the entry in the log), but I have not seen the same number of failed files to get recorded there, i.e. it'll be 0 or 4 or 7, but not 10.

Every now and then, deleting/moving files on one host actually causes the failed items count to go down to 0.

It seems as if restarting syncthing resets the count.

Here is the debug log (+scanner, +aggregator) on the device on which I initiated the change:

```
[E2S6A] 2018/12/29 11:36:57.421483 aggregator.go:233: DEBUG: aggregator/"sgs7e DCIM int" (o3y5s-oaoye): Creating eventDir at: Camera
[E2S6A] 2018/12/29 11:36:57.421553 aggregator.go:278: DEBUG: aggregator/"sgs7e DCIM int" (o3y5s-oaoye): Tracking (type remove): Camera/20180817_152426.jpg
[E2S6A] 2018/12/29 11:36:57.421596 aggregator.go:297: DEBUG: aggregator/"sgs7e DCIM int" (o3y5s-oaoye): Resetting notifyTimer to 10s
[E2S6A] 2018/12/29 11:37:07.421913 aggregator.go:329: DEBUG: aggregator/"sgs7e DCIM int" (o3y5s-oaoye): Notifying about 1 fs events
[E2S6A] 2018/12/29 11:37:07.421981 aggregator.go:297: DEBUG: aggregator/"sgs7e DCIM int" (o3y5s-oaoye): Resetting notifyTimer to 10s
[E2S6A] 2018/12/29 11:37:07.422249 walk.go:101: DEBUG: Walk [Camera/20180817_152426.jpg] Matcher/[]@0xc42059aab0
[E2S6A] 2018/12/29 11:37:07.422367 walk.go:538: INFO: Scanner (folder o3y5s-oaoye, file "Camera/20180817_152426.jpg"): scan: lstat /home/ssd/madduck/sync/sgs7e/dcim-int/Camera/20180817_152426.jpg: no such file or directory
[E2S6A] 2018/12/29 11:37:07.422530 walk.go:164: DEBUG: Walk progress done o3y5s-oaoye [Camera/20180817_152426.jpg] Matcher/[]@0xc42059aab0
[E2S6A] 2018/12/29 11:37:17.422227 aggregator.go:305: DEBUG: aggregator/"sgs7e DCIM int" (o3y5s-oaoye): No tracked events, waiting for new event.
```

And here the corresponding log on the other Linux device:

```
[EYQXP] 2018/12/29 11:37:07.432886 aggregator.go:233: DEBUG: aggregator/"sgs7e DCIM int" (o3y5s-oaoye): Creating eventDir at: Camera
[EYQXP] 2018/12/29 11:37:07.433633 aggregator.go:278: DEBUG: aggregator/"sgs7e DCIM int" (o3y5s-oaoye): Tracking (type remove): Camera/20180817_152426.jpg
[EYQXP] 2018/12/29 11:37:07.433775 aggregator.go:297: DEBUG: aggregator/"sgs7e DCIM int" (o3y5s-oaoye): Resetting notifyTimer to 10s
[EYQXP] 2018/12/29 11:37:13.344856 walk.go:101: DEBUG: Walk [] Matcher/[]@0xc4200ca990
[EYQXP] 2018/12/29 11:37:13.355309 walk.go:237: DEBUG: ignored (internal): .stfolder
[EYQXP] 2018/12/29 11:37:13.355609 walk.go:237: DEBUG: ignored (internal): .stignore
[EYQXP] 2018/12/29 11:37:13.357557 walk.go:164: DEBUG: Walk progress done madduck-invoices [] Matcher/[]@0xc4200ca990
[EYQXP] 2018/12/29 11:37:17.434589 aggregator.go:329: DEBUG: aggregator/"sgs7e DCIM int" (o3y5s-oaoye): Notifying about 1 fs events
[EYQXP] 2018/12/29 11:37:17.434685 aggregator.go:297: DEBUG: aggregator/"sgs7e DCIM int" (o3y5s-oaoye): Resetting notifyTimer to 10s
[EYQXP] 2018/12/29 11:37:17.435122 walk.go:101: DEBUG: Walk [Camera/20180817_152426.jpg] Matcher/[]@0xc4200caab0
[EYQXP] 2018/12/29 11:37:17.435453 walk.go:538: INFO: Scanner (folder o3y5s-oaoye, file "Camera/20180817_152426.jpg"): scan: lstat /home/madduck/sync/sgs7e/dcim-int/Camera/20180817_152426.jpg: no such file or directory
[EYQXP] 2018/12/29 11:37:17.435858 walk.go:164: DEBUG: Walk progress done o3y5s-oaoye [Camera/20180817_152426.jpg] Matcher/[]@0xc4200caab0
[EYQXP] 2018/12/29 11:37:09.164360 device.go:43: DEBUG: stats.DeviceStatisticsReference.WasSeen: E2S6AJG-T3RWPWR-WB4YWOG-V53LIUV-7RRZHQ5-YYMPMO7-5OUKGET-EQ33LQO
```

**Comment by imsodin** [comment] 2018-12-29 15:47
This is a duplicate of https://github.com/syncthing/syncthing/issues/5385, which is already fixed.

**Closed by imsodin** 2018-12-29 15:47 UTC
