### ISSUE TITLE
Creation date gone after sync

### ISSUE THREAD

**Issue by martin1194** [syncthing/syncthing#9536] opened 2024-05-12 12:35 UTC
### What happened?

I keep using SyncThing to sync my Hexo Mark Down file between laptop, desktop and Linux host server. I found that the creation date will keep changing after I add a new stuff in my Mark Down File.

### Syncthing version

v1.27.6 & v1.27.7

### Platform & operating system

ubuntu 23.1  and WIndows 10 HOME

**Comment by calmh** [comment] 2024-05-12 13:39
Duplicate of #9191

**Closed by calmh** 2024-05-12 13:39 UTC
Labels: bug, needs-triage
