### ISSUE TITLE
panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by tomasz1986** [syncthing/syncthing#6493] opened 2020-04-04 07:35 UTC
Today, right after clicking the "Pause All" button in the Web GUI, Syncthing suddenly stopped working. The process was still running in the background, but the GUI suddenly became unavailable.

A panic log was automatically created in the Syncthing home folder, which I have attached below. In addition, the `config.xml` file was reset, while the old one was renamed to `.syncthing.tmp.001460216`.

I have renamed the file back to `config.xml` and Syncthing seems to be working fine again.

[panic.log](https://github.com/syncthing/syncthing/files/4430903/panic.log)

### Version Information

Syncthing Version: v1.4.0
OS Version: Windows 10 Enterprise 2019 LTSC x64

**Comment by calmh** [comment] 2020-04-04 07:43
Actual panic is a "classic" failed handling of database close: 

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x198 pc=0xaef5d0]

goroutine 252049 [running]:
github.com/syndtr/goleveldb/leveldb.(*DB).isClosed(...)
	C:/BuildAgent/work/pkg/mod/github.com/syndtr/goleveldb@v1.0.1-0.20190923125748-758128399b1d/leveldb/db_state.go:230
github.com/syndtr/goleveldb/leveldb.(*DB).ok(...)
	C:/BuildAgent/work/pkg/mod/github.com/syndtr/goleveldb@v1.0.1-0.20190923125748-758128399b1d/leveldb/db_state.go:235
github.com/syndtr/goleveldb/leveldb.(*Snapshot).Get(0xc01d4bb800, 0xc00f1e0190, 0x48, 0x48, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	C:/BuildAgent/work/pkg/mod/github.com/syndtr/goleveldb@v1.0.1-0.20190923125748-758128399b1d/leveldb/db_snapshot.go:103 +0x60
github.com/syncthing/syncthing/lib/db/backend.leveldbSnapshot.Get(0xc01d4bb800, 0xc01cd4e450, 0xc00f1e0190, 0x48, 0x48, 0xc00011db80, 0x10000c007d08630, 0x0, 0x48, 0xc00f1e0190)
	C:/BuildAgent/work/174e136266f8a219/lib/db/backend/leveldb_backend.go:117 +0x69
github.com/syncthing/syncthing/lib/db.readOnlyTransaction.getFileTrunc(0x110b640, 0xc01cd4e460, 0x1119ac0, 0xc000053180, 0xc00f1e0190, 0x48, 0x48, 0x0, 0x10000000c, 0x48, ...)
	C:/BuildAgent/work/174e136266f8a219/lib/db/transactions.go:54 +0x63
github.com/syncthing/syncthing/lib/db.readOnlyTransaction.getFileByKey(0x110b640, 0xc01cd4e460, 0x1119ac0, 0xc000053180, 0xc00f1e0190, 0x48, 0x48, 0x0, 0x0, 0x0, ...)
	C:/BuildAgent/work/174e136266f8a219/lib/db/transactions.go:46 +0xbf
github.com/syncthing/syncthing/lib/db.readOnlyTransaction.getFile(0x110b640, 0xc01cd4e460, 0x1119ac0, 0xc000053180, 0xc010ae4cb0, 0xb, 0x10, 0xc01e3b0f00, 0x20, 0x20, ...)
	C:/BuildAgent/work/174e136266f8a219/lib/db/transactions.go:42 +0x1b0
github.com/syncthing/syncthing/lib/db.(*Snapshot).Get(0xc006137a00, 0xffffffffffffffff, 0xffffffffffffffff, 0xffffffffffffffff, 0xffffffffffffffff, 0xc01daba780, 0x3f, 0x0, 0x0, 0x0, ...)
	C:/BuildAgent/work/174e136266f8a219/lib/db/set.go:336 +0x1af
github.com/syncthing/syncthing/lib/model.cFiler.CurrentFile(0xc006137a00, 0xc01daba780, 0x3f, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	C:/BuildAgent/work/174e136266f8a219/lib/model/folder.go:927 +0x9e
github.com/syncthing/syncthing/lib/scanner.(*walker).walkRegular(0xc01b4763c0, 0x110a600, 0xc000f2e540, 0xc01daba780, 0x3f, 0x1114920, 0xc01ed31c80, 0xc0244b6de0, 0x0, 0xc000f25b80)
	C:/BuildAgent/work/174e136266f8a219/lib/scanner/walk.go:334 +0x8f
github.com/syncthing/syncthing/lib/scanner.(*walker).handleItem(0xc01b4763c0, 0x110a600, 0xc000f2e540, 0xc01daba780, 0x3f, 0xc0244b6de0, 0xc0244b6e40, 0x0, 0x0, 0xc01cb8f6f8, ...)
	C:/BuildAgent/work/174e136266f8a219/lib/scanner/walk.go:327 +0x29c
github.com/syncthing/syncthing/lib/scanner.(*walker).walkAndHashFiles.func1(0xc01daba780, 0x3f, 0x1114920, 0xc01ed31c60, 0x0, 0x0, 0x0, 0x0)
	C:/BuildAgent/work/174e136266f8a219/lib/scanner/walk.go:268 +0xb7e
github.com/syncthing/syncthing/lib/fs.(*MtimeFS).Walk.func1(0xc01daba780, 0x3f, 0x1114920, 0xc01ed31c60, 0x0, 0x0, 0x40a9cf, 0xdba9e0)
```

The config being reset is the more concerning bit...

**Comment by tomasz1986** [comment] 2020-04-04 07:48
Well, I am not sure what exactly happened :(

The config file was indeed completely reset to the default one.

I have backed up the whole Syncthing home folder, including the database, before reverting the config file, etc. so please let me know if you need any more information.

**Comment by calmh** [comment] 2020-04-04 07:50
I expect that what happened is that the crash was precisely during the config save (because it was caused by the config save, although that should not result in a database close...). 

On Windows there are no atomic renames, so after saving a new temporary config we must 

1. delete the old config.xml
2. rename the new .config.tmp.whatever to config.xml

and we can crash between those two steps. On the next startup there is no config, so a default is generated.

Maybe we could check on startup if there is no config but there *is* a recent temp file and assume this situation.

And maybe we should not crash with a database close error...

**Comment by greatroar** [comment] 2020-04-04 09:31
Re: no atomic renames on Windows, I'm no expert on the Windows API, but this is what os.Rename promises:

    Rename renames (moves) oldpath to newpath. If newpath already exists and
    is not a directory, Rename replaces it. OS-specific restrictions may
    apply when oldpath and newpath are in different directories. If there is
    an error, it will be of type *LinkError.

From this, and from what I can find out online about the underlying MoveFileEx, it would seem that trying os.Rename and reporting an error if it fails may be a safer option than the current behavior. The [renameio](https://github.com/google/renameio) package uses it, too.

**Comment by calmh** [comment] 2020-04-04 09:41
So we have this, since five years:

https://github.com/syncthing/syncthing/blob/48f9d323fa04e8aaa0f755badd99c8378e4b156d/lib/osutil/atomic.go#L96-L104

but at the moment I'm not sure under what circumstances the rename would fail without the prior remove. I would assume/hope that was a valid reason, perhaps if the file was readonly (which would be more appropriately solved with a chmod).

Should be trivial to test for this on windows and remove if not neceseary.

**Comment by greatroar** [comment] 2020-04-04 10:03
You're not confused, os.Rename [was different five years ago](https://github.com/golang/go/commit/92c57363e0b4d193c4324e2af6902fe56b7524a0).

**Comment by imsodin** [comment] 2020-04-13 16:29
The config problem was fixed, and database closing panics is https://github.com/syncthing/syncthing/issues/5907 - anything left to fix specific to this issue?

**Closed** 2020-04-13 20:57 UTC
