### ISSUE TITLE
Local discovery doesn't work by WiFi network (special problem)

### ISSUE THREAD

**Issue by Realisimus** [syncthing/syncthing#1312] opened 2015-01-29 22:23 UTC
Summary: On my laptop local discovery doesn't work by wifi network.
Environment:
1) Router mikrotik.
2) PC with wired network.
3) Two laptops with windows 8.1 x86 and x64
4) Network is 192.168.88.0/24 for wired and wifi and doesn't have firewall.
5) Syncthing v0.10.21 x86 + x64

One of laptops has this problem. Windows 8.1 x64. If I use wifi - pc and second laptop are disconnected. Connect between second laptop and PC work fine.
If I use wired network - all work fine.
Global discovery with remote devices work fine.
If I use static addresses in device settings - all work fine.
Check for both client on windows, x64 and x86.
Second laptop work fine with both networks, wired and wifi.

Problem ONLY with local discovery on one laptop by wifi !!!!

Log is clean:
[MPLL2] 23:06:54 INFO: syncthing v0.10.21 (go1.4.1 windows-386 default) XXX-user@syncthing-builder 2015-01-19 20:40:36 UTC
[MPLL2] 23:06:54 INFO: My ID: XXX
[MPLL2] 23:06:54 INFO: Starting web GUI on http://127.0.0.1:8080/
[MPLL2] 23:06:55 INFO: Starting local discovery announcements
[MPLL2] 23:06:55 INFO: Local discovery over IPv6 unavailable
[MPLL2] 23:06:55 OK: Ready to synchronize 1 (read-write)
[MPLL2] 23:06:55 INFO: Device XXX is "Laptop1" at [dynamic]
[MPLL2] 23:06:55 INFO: Device XXX is "Laptop2" at [dynamic]
[MPLL2] 23:06:55 INFO: Device XXX is "PC" at [dynamic]
[MPLL2] 23:06:56 INFO: Completed initial scan (rw) of folder 1

I checked all network settings in windows and compared it with working laptop.

I don't know, what does else information you need ??

**Comment by Realisimus** [comment] 2015-01-29 22:26
<configuration version="7">
    <folder id="1" path="d:\ololo" ro="false" rescanIntervalS="60" ignorePerms="false">
        <device id="XXX"></device>
        <device id="XXX"></device>
        <device id="XXX"></device>
        <versioning type="simple">
            <param key="keep" val="5"></param>
        </versioning>
        <lenientMtimes>false</lenientMtimes>
        <copiers>1</copiers>
        <pullers>16</pullers>
        <hashers>0</hashers>
    </folder>
    <device id="XXX" name="Laptop1" compression="false" introducer="false">
        <address>dynamic</address>
    </device>
    <device id="XXX" name="Laptop2" compression="true" introducer="false">
        <address>dynamic</address>
    </device>
    <device id="XXX" name="PC" compression="true" introducer="true">
        <address>dynamic</address>
    </device>
    <gui enabled="true" tls="false">
        <address>127.0.0.1:8080</address>
        <apikey>XXX</apikey>
    </gui>
    <options>
        <listenAddress>0.0.0.0:22000</listenAddress>
        <globalAnnounceServer>udp4://announce.syncthing.net:22026</globalAnnounceServer>
        <globalAnnounceEnabled>false</globalAnnounceEnabled>
        <localAnnounceEnabled>true</localAnnounceEnabled>
        <localAnnouncePort>21025</localAnnouncePort>
        <localAnnounceMCAddr>[ff32::5222]:21026</localAnnounceMCAddr>
        <maxSendKbps>0</maxSendKbps>
        <maxRecvKbps>0</maxRecvKbps>
        <reconnectionIntervalS>60</reconnectionIntervalS>
        <startBrowser>true</startBrowser>
        <upnpEnabled>false</upnpEnabled>
        <upnpLeaseMinutes>0</upnpLeaseMinutes>
        <upnpRenewalMinutes>30</upnpRenewalMinutes>
        <urAccepted>-1</urAccepted>
        <urUniqueID></urUniqueID>
        <restartOnWakeup>true</restartOnWakeup>
        <autoUpgradeIntervalH>0</autoUpgradeIntervalH>
        <keepTemporariesH>24</keepTemporariesH>
        <cacheIgnoredFiles>true</cacheIgnoredFiles>
        <progressUpdateIntervalS>5</progressUpdateIntervalS>
        <symlinksEnabled>true</symlinksEnabled>
    </options>
</configuration>

**Comment by AudriusButkevicius** [comment] 2015-01-29 22:31
Sounds like a duplicate of #1113 
Can you try a different OS via WiFi?
Also it could be that your router is just blocking announcements made via WiFi.

**Comment by Realisimus** [comment] 2015-01-29 22:53
Another laptop works fine via wifi. Windows 8.1 x32. It doesn't router settings.
And problem ONLY with local discovery. UPnP works. And status remote devices are "connected", but local are "disconnected".
I think that problem can be in wireless network settings, but I cheсked all knew.

settings:
```
<configuration version="7">
    <folder id="1" path="d:\ololo" ro="false" rescanIntervalS="60" ignorePerms="false">
        <device id="XXX"></device>
        <device id="XXX"></device>
        <device id="XXX"></device>
        <versioning type="simple">
            <param key="keep" val="5"></param>
        </versioning>
        <lenientMtimes>false</lenientMtimes>
        <copiers>1</copiers>
        <pullers>16</pullers>
        <hashers>0</hashers>
    </folder>
    <device id="XXX" name="Laptop1" compression="false" introducer="false">
        <address>dynamic</address>
    </device>
    <device id="XXX" name="Laptop2" compression="true" introducer="false">
        <address>dynamic</address>
    </device>
    <device id="XXX" name="PC" compression="true" introducer="true">
        <address>dynamic</address>
    </device>
    <gui enabled="true" tls="false">
        <address>127.0.0.1:8080</address>
        <apikey>XXX</apikey>
    </gui>
    <options>
        <listenAddress>0.0.0.0:22000</listenAddress>
        <globalAnnounceServer>udp4://announce.syncthing.net:22026</globalAnnounceServer>
        <globalAnnounceEnabled>false</globalAnnounceEnabled>
        <localAnnounceEnabled>true</localAnnounceEnabled>
        <localAnnouncePort>21025</localAnnouncePort>
        <localAnnounceMCAddr>[ff32::5222]:21026</localAnnounceMCAddr>
        <maxSendKbps>0</maxSendKbps>
        <maxRecvKbps>0</maxRecvKbps>
        <reconnectionIntervalS>60</reconnectionIntervalS>
        <startBrowser>true</startBrowser>
        <upnpEnabled>false</upnpEnabled>
        <upnpLeaseMinutes>0</upnpLeaseMinutes>
        <upnpRenewalMinutes>30</upnpRenewalMinutes>
        <urAccepted>-1</urAccepted>
        <urUniqueID></urUniqueID>
        <restartOnWakeup>true</restartOnWakeup>
        <autoUpgradeIntervalH>0</autoUpgradeIntervalH>
        <keepTemporariesH>24</keepTemporariesH>
        <cacheIgnoredFiles>true</cacheIgnoredFiles>
        <progressUpdateIntervalS>5</progressUpdateIntervalS>
        <symlinksEnabled>true</symlinksEnabled>
    </options>
</configuration>
```

**Comment by AudriusButkevicius** [comment] 2015-01-29 22:56
You can try running with environment variable `STTRACE=discovery` set.

**Comment by Realisimus** [comment] 2015-01-29 23:11
No, I use windows 8.1 x64

**Comment by AudriusButkevicius** [comment] 2015-01-29 23:15
Why does that matter?

**Comment by Realisimus** [comment] 2015-01-29 23:28
Sorry, I am sleeping :)
```
[MPLL2] 2015/01/30 01:19:01.120324 main.go:401: INFO: syncthing v0.10.21 (go1.4.1 windows-amd64 default) XXX-user@syncthing-builder 2015-01-19 20:40:36 UTC
[MPLL2] 2015/01/30 01:19:01.121327 main.go:402: INFO: My ID: XXX
[MPLL2] 2015/01/30 01:19:01.142343 main.go:654: INFO: Starting web GUI on http://127.0.0.1:8080/
[MPLL2] 2015/01/30 01:19:01.666530 main.go:1134: INFO: Starting local discovery announcements
[MPLL2] 2015/01/30 01:19:01.706554 discover.go:88: DEBUG: discover: Start local v6: listen udp ff32::5222: setsockopt: not supported by windows
[MPLL2] 2015/01/30 01:19:01.711560 discover.go:90: INFO: Local discovery over IPv6 unavailable
[MPLL2] 2015/01/30 01:19:01.711560 main.go:559: OK: Ready to synchronize 1 (read-write)
[MPLL2] 2015/01/30 01:19:01.711560 main.go:575: INFO: Device MyLaptop is "MyLaptop" at [dynamic]
[MPLL2] 2015/01/30 01:19:01.711560 main.go:575: INFO: Device XXX is "XXX" at [dynamic]
[MPLL2] 2015/01/30 01:19:01.711560 main.go:575: INFO: Device XXX is "XXX" at [dynamic]
[MPLL2] 2015/01/30 01:19:01.715561 discover.go:308: DEBUG: discover: Received local announcement from 192.168.56.1:21025 for MyLaptop
[MPLL2] 2015/01/30 01:19:01.719563 puller.go:231: INFO: Completed initial scan (rw) of folder 1
[MPLL2] 2015/01/30 01:19:31.715287 discover.go:308: DEBUG: discover: Received local announcement from 192.168.56.1:21025 for MyLaptop
[MPLL2] 2015/01/30 01:20:01.715118 discover.go:308: DEBUG: discover: Received local announcement from 192.168.56.1:21025 for MyLaptop
[MPLL2] 2015/01/30 01:20:31.716530 discover.go:308: DEBUG: discover: Received local announcement from 192.168.56.1:21025 for MyLaptop
[MPLL2] 2015/01/30 01:21:01.715391 discover.go:308: DEBUG: discover: Received local announcement from 192.168.56.1:21025 for MyLaptop
......

```
192.168.56.0 - virtualbox's network. There are no syncthing. My local network is 192.168.88.0

**Comment by Realisimus** [comment] 2015-01-29 23:31
I disable this interface and all work !!! But it problem. I wrote that need option for choosing interfaces :)

**Comment by AudriusButkevicius** [comment] 2015-01-29 23:43
Well it uses all interfaces for broadcasts, the fact that it doesn't get delivered over a certain interface most likely means that the virtual switch is doing something funky.

**Comment by Realisimus** [comment] 2015-01-29 23:58
I hope that you can find the solution, because it the first program that has problem with virtual network interface. Problematic adapter is "VirtualBox Host-Only Ethernet Adapter"
And when I am using wired network - all work.
Thanks.

**Comment by Spellshaper** [comment] 2015-01-30 14:38
From what you write, it seems you have an instance of Syncthing running on a virtual machine? A host-only network adapter does just what it says - it allows you to connect the VM to the host machine and other guests (virtual machines) and that is it.
Should this be the case, what you experience is no bug in Syncthing, but an improperly set-up virtual machine.

Did you create this VM just for Syncthing? Try setting the virtual network adapter to bridged networking in the VM's settings.

**Comment by AudriusButkevicius** [comment] 2015-01-30 14:57
I think what is actually happening, is that his OS routes his network through the virtual box virtual router (which itself routes the packets to the VM or to the physical adapter based on IPs), which then swallows the broadcasts (probably because it's a separate network in a different subnet) hence they never reach any other node.

Once he disables that, his OS falls back to routing through the physical adapter and all is well.

Syncthing makes broadcasts on all adapters (as it's a broadcast after all: https://github.com/syncthing/syncthing/blob/master/internal/beacon/broadcast.go#L57 and https://github.com/syncthing/syncthing/blob/master/internal/beacon/multicast.go#L60) but his OS decides that the only "active" or "main" adapter is the virtual box one.

I would like to see what `net.InterfaceAddrs()` and `net.Interfaces()` returns on his machine.

**Comment by Realisimus** [comment] 2015-01-30 15:28
I use syncthing on phisical laptop, but virtualbox installed virtual adapter for connect to VM.
Now I have 5 network interfaces on my laptop:
1. Wired network (phisical)
2. Wi-Fi (phisical)
3. VirtualBox (virtual and always connected, if enable in devices)
4. L2TP VPN
5. Cisco VPN
And I deleted 2 interfaces PPTP VPN for testing this network problem. (Yes, so many interfaces, but I am working in IT, automation and manual QA)

I can try to debug program, but I don't know Go. What does IDE for it you advise?

I could to help after 08:00 pm by local time (+2 time zone), I will be at home.

P.S. I think that problem with "missunderstanding" beetwen syncthing and interfaces. And IMHO best solution is settings interfaces for using and their priority.

**Comment by AudriusButkevicius** [comment] 2015-01-30 16:12
We send the message to ALL interfaces, so I don't see how a priority will solve Go not seeing the relevant interface.

You can just install the Go runtime, and write a tiny script which just prints what `net.Interfaces()` returns.

**Comment by Realisimus** [comment] 2015-01-30 20:46
I don't think that will be reed about Go :)
```
fmt.Println(net.Interfaces())
fmt.Println(net.InterfaceAddrs())
```
When VB interface is disable:
```
[{4 1500 {2531F5CD-5C69-45C4-BB29-871F5B786933} c0:14:3d:db:98:c5 0} {3 1500 {1A1C7094-E5DC-421D-8450-E35DDD2DD49E} 3c:97:0e:40:e8:f3 0}] <nil>

[192.168.88.11 0.0.0.0] <nil>
```

When enable:
```
[{4 1500 {2531F5CD-5C69-45C4-BB29-871F5B786933} c0:14:3d:db:98:c5 up|broadcast|multicast} {3 1500 {1A1C7094-E5DC-421D-8450-E35DDD2DD49E} 3c:97:0e:40:e8:f3 0} {10 1500 {FAC7F945-B1CD-4C45-BDEA-FCB180C193D0} 08:00:27:00:b8:dd 0}] <nil>

[192.168.88.11 0.0.0.0 192.168.56.1] <nil>
```
I don't see anything strange

**Comment by Realisimus** [comment] 2015-01-30 20:54
Now VB interface is enable and after restart syncthing local PC is disconnected. Reproducing 100%

**Comment by AudriusButkevicius** [comment] 2015-01-30 21:05
Well we always announce on all interfaces, so I don't see how this could not work.
I assume 192.168.88.11 is your physical interface, and 192.168.56.1 is your virtual box interface?
I guess the next step is to fire up wireshark and see if syncthing is advertising the broadcasts through those interfaces.

If not, I feel it's the same issue as #1113

**Comment by Realisimus** [comment] 2015-01-30 22:03
Checked. I think that problem in broadcast send module. Wireshark show packets only from 192.168.56...
Packets 255.255.255.255 from port 21025 to port 21025 56 bytes
After disable VB interface - from 192.168.88....
And very interesting thing - after connect wired network - only from wired !!
On my laptop broadcast packets sending from one interface, only from one !!

**Comment by AudriusButkevicius** [comment] 2015-01-30 22:11
Can you run with `STTRACE=beacon` that should list which IPs of the interfaces it's broadcasting on.
That will show us if syncthing is at least attempting to advertise on other interfaces.

The code atleast tries to do that, I don't see how that could be failing.

**Comment by Realisimus** [comment] 2015-01-30 22:28
I checked it on another machine, for better statistic. OS Windows Home Server 2011. My another local machine.
Networks:
Ethernet adapter LAN:
   DNS-суффикс подключения . . . . . :
   IPv4-адрес. . . . . . . . . . . . : 192.168.88.254
   Маска подсети . . . . . . . . . . : 255.255.255.0
   Основной шлюз. . . . . . . . . : 192.168.88.1

Ethernet adapter VMware Network Adapter VMnet1:
   DNS-суффикс подключения . . . . . :
   Локальный IPv6-адрес канала . . . : fe80::9056:71eb:c5d0:8de5%16
   IPv4-адрес. . . . . . . . . . . . : 192.168.18.1
   Маска подсети . . . . . . . . . . : 255.255.255.0
   Основной шлюз. . . . . . . . . :

Ethernet adapter VMware Network Adapter VMnet8:
   DNS-суффикс подключения . . . . . :
   Локальный IPv6-адрес канала . . . : fe80::4cdb:2159:b784:268b%18
   IPv4-адрес. . . . . . . . . . . . : 192.168.157.1
   Маска подсети . . . . . . . . . . : 255.255.255.0
   Основной шлюз. . . . . . . . . :
Sorry, there are Russian OS, but I think that you see 3 interfaces, 1 physical and 2 virtual. 

And log:
```
[ZYCLN] 2015/01/31 00:18:15.827945 broadcast.go:77: DEBUG: addresses: [255.255.255.255]
[ZYCLN] 2015/01/31 00:18:15.827945 broadcast.go:89: DEBUG: sent 56 bytes to 255.255.255.255:21025
[ZYCLN] 2015/01/31 00:18:15.828945 beacon.go:39: DEBUG: recv 56 bytes from 192.168.88.254:21025
[ZYCLN] 2015/01/31 00:18:45.825945 broadcast.go:77: DEBUG: addresses: [255.255.255.255]
[ZYCLN] 2015/01/31 00:18:45.825945 broadcast.go:89: DEBUG: sent 56 bytes to 255.255.255.255:21025
[ZYCLN] 2015/01/31 00:18:45.827945 beacon.go:39: DEBUG: recv 56 bytes from 192.168.88.254:21025
[ZYCLN] 2015/01/31 00:19:15.823945 broadcast.go:77: DEBUG: addresses: [255.255.255.255]
[ZYCLN] 2015/01/31 00:19:15.823945 broadcast.go:89: DEBUG: sent 56 bytes to 255.255.255.255:21025
[ZYCLN] 2015/01/31 00:19:15.823945 beacon.go:39: DEBUG: recv 56 bytes from 192.168.88.254:21025
[ZYCLN] 2015/01/31 00:19:45.822945 broadcast.go:77: DEBUG: addresses: [255.255.255.255]
[ZYCLN] 2015/01/31 00:19:45.822945 beacon.go:39: DEBUG: recv 56 bytes from 192.168.88.254:21025
[ZYCLN] 2015/01/31 00:19:45.822945 broadcast.go:89: DEBUG: sent 56 bytes to 255.255.255.255:21025
[ZYCLN] 2015/01/31 00:20:15.820945 broadcast.go:77: DEBUG: addresses: [255.255.255.255]
[ZYCLN] 2015/01/31 00:20:15.820945 broadcast.go:89: DEBUG: sent 56 bytes to 255.255.255.255:21025
[ZYCLN] 2015/01/31 00:20:15.822945 beacon.go:39: DEBUG: recv 56 bytes from 192.168.88.254:21025
```

Check please on your machines. I think that it's a problem - work only one interface.

**Comment by Realisimus** [comment] 2015-01-30 22:32
But it can be wrong test. It needs to check by wireshark for correct results. Please checked it on your machine.

**Comment by Realisimus** [comment] 2015-01-30 22:54
I am reading about broadcast and think that you can't fix it. https://social.technet.microsoft.com/Forums/windows/en-US/72e7387a-9f2c-4bf4-a004-c89ddde1c8aa/how-to-fix-the-global-broadcast-address-255255255255-behavior-on-windows?forum=w7itpronetworking

**Comment by Realisimus** [comment] 2015-01-30 23:04
Best solution - use broadcast for each interface, for example for me - 192.168.88.255 and etc.
It more correct. And my intuition was right - choose interfaces for local discovering :) And program will be more "enterprising" :)
Thank you for your time and company.

**Comment by AudriusButkevicius** [comment] 2015-01-30 23:13
Well we default to all interfaces, if the OS decides to make wrong decisions, there is very little we can do.

I agree we could allow specifying the IP (or IPs) of the interfaces we want to broadcast, but that would still have issues as far as I understand from the link you provided?

Anyways, I do not feel that we should tackle this problem eventually, as it does have a use case, but  I don't think it's such a big issue compared to other issues that are currently out there.

**Comment by Realisimus** [comment] 2015-01-30 23:35
I understand that it will not be fix soon. But I hope that you maybe find time for it.
And problem will be with checking every time ip and mask on each interfaces.
For example: Now mask for my broadcast 192.168.88.255
At the work it will be 10.0.0.255 (for example) etc.
But each packet will be link to interface. And program will be send several broadcast packets by one time (from each interfaces in list)

**Comment by Zillode** [comment] 2015-02-03 11:16
@Realisimus could you remove " && iaddr.IP.IsGlobalUnicast()" from https://github.com/syncthing/syncthing/blob/b88c5a89a8c8a830c503555de7c9de05ca08f0f2/internal/beacon/broadcast.go#L65 and try again?

**Comment by Realisimus** [comment] 2015-02-03 11:27
I will check it at home, but I have one question: Your program can send broadcast package not 255.255.255.255 ?
If no - it doesn't resolve a problem. Because OS windows broadcast package 255.255.255.255 send ONLY ONE, from interface with minimal metric.
Linux broadcast 255.255.255.255 send from all interfeces, several copies of this package.

**Comment by Zillode** [comment] 2015-02-03 11:28
Yes it only falls back to 255.255.255.255 if no suitable interfaces were found.

**Comment by calmh** [comment] 2015-02-09 21:36
Indeed, we should be sending to the specific interface broadcast addresses. Wonder why we don't? Could add some more debugging around that path to see what interface addresses we discover...

**Comment by theAdmiral777** [comment] 2015-04-16 19:30
I had a similar issue with VirtualBox installed. Syncthing would not create a UPnP mapping when the "VirtualBox Host-Only Network" adapter was enabled, and it could when that adapter was disabled. It looks like it may have been fixed in [#1113](https://github.com/syncthing/syncthing/issues/1113)?

**Comment by AudriusButkevicius** [comment] 2015-04-16 19:33
Yes.

**Comment by theAdmiral777** [comment] 2015-04-16 20:14
I downloaded v0.11.0-rc0 and it seems to work fine, even with the VirtualBox adapter on. Nice work, thanks!

**Comment by AudriusButkevicius** [comment] 2015-05-17 15:41
I believe this is now fixed.

**Closed by AudriusButkevicius** 2015-05-17 15:41 UTC
Labels: enhancement, help-wanted
