### ISSUE TITLE
Sync in same device

### ISSUE THREAD

**Issue by EHMilon** [syncthing/syncthing#9354] opened 2024-01-17 19:52 UTC
### Include required information

Please be sure to include at least:

 - what problem your new feature would solve
 - how or why you think it is generally useful (i.e., not just for you)
 - what alternatives or workarounds you considered

Synching offer peer-to-peer file synchronization and directories across different devices on a local network or over the internet. It does not support cloud storage integration. Is it possible to add third party cloud storage integration such as Google Drive, One Drive, Drop Box etc. It will be helpful because in peer to peer synchronization, tow device need to connect a same network in same time. 
If it is not possible, then add sync data in same directory. If i need to backup data on my external drive suppose pen drive when i plug it on this device it will automatically sync data to my pen drive

**Comment by tomasz1986** [comment] 2024-01-17 19:58
Duplicate of https://github.com/syncthing/syncthing/issues/4721.

**Closed by tomasz1986** 2024-01-17 19:58 UTC
Labels: enhancement, needs-triage
