### ISSUE TITLE
Move db folder to $HOME/.cache for safe system backups

### ISSUE THREAD

**Issue by zilexa** [syncthing/syncthing#7193] opened 2020-12-12 13:18 UTC
As mentioned several times on the forum, when you restore your system, do not restore the `/.config/syncthing/index-v0.14.0.db/` folder because it will delete files that are not known in the database (which makes total sense). 

Currently on all my (Ubuntu) systems, I exclude this specific folder from snapshots. If I restore a snapshot, my Syncthing configuration is restored but the db is not, forcing Syncthing to simply rescan all local files and not deleting anything. 

I would like to suggest to move this folder to /.cache. This way users backing up their system configuration files and application configuration files (a lot of those types of files are in $HOME/ folder by default on Ubuntu systems) will not automatically backup the database.

Especially on filesystems that support snapshots natively (BTRFS) it is not really possible to exclude just the /syncthing/index-v0.14.0.db/ folder while keeping the syncthing config and key files in /syncthing.

**Comment by imsodin** [comment] 2020-12-12 13:53
Duplicate of https://github.com/syncthing/syncthing/issues/4924 and already fixed:  
The database is data, not just cache, thus if `$XDG_DATA_HOME` is set or `~/.local/share/syncthing` exists, that is used for the db (unless of course a db already exists in `~/.config/syncthing`).

**Closed by imsodin** 2020-12-12 13:53 UTC
Labels: enhancement, needs-triage

**Comment by zilexa** [comment] 2020-12-12 14:20
The question then remains if this still holds true?
https://github.com/syncthing/syncthing/issues/4924#issuecomment-445719373

If the database is expendable now, could it safely be moved to /.cache as requested here?
https://github.com/syncthing/syncthing/issues/4924#issuecomment-445585560

**Comment by calmh** [comment] 2020-12-12 15:25
The index remains not expendable.
