### ISSUE TITLE
IP addresses from interfaces that are down, should be ignored

### ISSUE THREAD

**Issue by BartG95** [syncthing/syncthing#9043] opened 2023-08-19 15:07 UTC
Pretty self-explanatory, I think.

As an example: I have docker installed on my laptop. It adds two interfaces. But I mostly do not use docker, so these interfaces are down. But the assigned IP address are included and tried in Syncthing.

As an alternative to ignoring them: make them least-preferable.

**Comment by bt90** [comment] 2023-08-19 16:38
Duplicate of #8767 ?

**Closed** 2023-08-19 19:41 UTC
Labels: bug, needs-triage
