### ISSUE TITLE
Forced rescan doesn't happen when the file to be overwritten is new (not present in the index)

### ISSUE THREAD

**Issue by jgabriels** [syncthing/syncthing#2416] opened 2015-10-28 21:36 UTC
On server 1 I typed:  echo 1 >> test
On server 2 I typed: echo 2 >> test
On server 1 I typed:  echo 3 >> test
On server 2 I typed: echo 4 >> test
On server 1 I typed:  echo 5 >> test
On server 2 I typed: echo 6 >> test
On server 1 I typed:  echo 7 >> test
On server 2 I typed: echo 8 >> test
On server 1 I typed: echo 9 >> test
I then waited for them to sync and then did a "cat test" which contained:
2
4
6
8
9
and there was no conflict files generated.
I did it a second time and got 2,4,6,8 and a third time and got 1,3,5,7,9 again with no conflict files
and both servers still saying that they are in sync and up to date.
If a local file has been modified since last sync, shouldn't it generate a conflict instead
of silently dropping data?

Also, it doesn't even seem to care what the "latest" file is as the "9" doesn't even always appear in the file.

Thanks.

**Comment by Zillode** [comment] 2015-10-29 00:01
This is https://github.com/syncthing/syncthing/pull/1852 / https://github.com/syncthing/syncthing/pull/2113

**Comment by AudriusButkevicius** [comment] 2015-10-29 00:18
Why did you close it though?

**Comment by calmh** [comment] 2015-10-29 07:25
This is a file being synced and not detected as a conflict as the other side hasn't scanned it yet and discovered the change, right?

**Comment by AudriusButkevicius** [comment] 2015-10-29 08:06
Basically yes, but it doesn't have to be this way.

**Comment by jgabriels** [comment] 2015-10-29 22:27
Thanks for the commit.  I tested the commit.  It's better.  It does actually produce conflict files but there is still missing data that doesn't appear in the original file or any of the conflict files.  I'm not sure what is going on.

**Comment by AudriusButkevicius** [comment] 2015-10-29 22:40
But are there conflict files generated next to the file with 17 entries?

**Comment by jgabriels** [comment] 2015-10-29 22:46
Yes, there are multiple conflict files but some of the 20 number don't appear in either the kept file or the conflict files.  Some of the 20 numbers just disappear.

**Comment by AudriusButkevicius** [comment] 2015-10-29 22:48
I'll reopen, and @calmh can close it if he understands why it happens, as I personally don't.

**Comment by calmh** [comment] 2015-10-30 07:58
Conflict resolution doesn't merge, it picks one of the two files and lets it win, so there's no reason to expect there to be 20 entries in the resulting file. However I do think the data should then be in the conflict copies. You're running with inotify I guess?

**Comment by jgabriels** [comment] 2015-10-30 12:59
No, I'm not using inotify.  syncthing is on a 60 second refresh and I'm writing to the file every 10 seconds from both hosts.  Obviously not a good situation, but I agree that the data should still be in one of the conflict files.

**Comment by calmh** [comment] 2015-10-30 14:07
Can't reproduce here. Running the h1 and h2 instances in the test directory, with one terminal doing


```
$ for ((i=100;i<199;i++)); do echo $i >> s1/test;sleep 5; done
```

and the other

```
$ for ((i=200;i<299;i++)); do echo $i >> s2/test;sleep 5; done
```

and the files as a whole contain the whole series of 1xx and 2xx, as seen by `cat s2/test* | sort | uniq` and eyeballing. What I expect to happen, and what actually seems to happen in my setup is something like this:

![img_1332](https://cloud.githubusercontent.com/assets/125426/10847601/af707fc4-7f17-11e5-8746-5d52722d37cf.JPG)

Where s1 and s2 are the two devices with time running downwards, appends coming in from the left and right, syncs being the diagonal transfers s1->s2 (they will randomly be in the other direction of course) and the file contents at various points being the boxed in stuff...

**Comment by jgabriels** [comment] 2015-10-30 16:07
Ok, I found the problem.  When I run the commands you gave, I'm always missing data at the beginning of one of the sequences.  If I prime the file by doing  "echo start >>testfile" and wait 75 seconds for it to sync to the other server and then run the commands, then all the data is accounted for in the conflict files.

so this causes loss of data:
server1#  for ((i=100;i<199;i++)); do echo $i >> testfile;sleep 5; done
server2#  for ((i=200;i<299;i++)); do echo $i >> testfile;sleep 5; done

but doing this seems to prevent it from losing data:
server1#  echo start>testfile ; sleep 75; for ((i=100;i<199;i++)); do echo $i >> testfile;sleep 5; done
server2#  echo start>testfile ; sleep 75; for ((i=200;i<299;i++)); do echo $i >> testfile;sleep 5; done

**Comment by calmh** [comment] 2016-11-23 14:02
Superseded by #3742 as this had anyway slipped off the radar...

**Closed by calmh** 2016-11-23 14:02 UTC
Labels: bug
