### ISSUE TITLE
Adding a folder without a password from an untrusted device via a popup 

### ISSUE THREAD

**Issue by Ratio2** [syncthing/syncthing#7762] opened 2021-06-10 17:00 UTC
v1.18.0-rc.1, Linux (64-bit Intel/AMD)

1. Connect to untrusted device and mark it as untrusted in advanced settings.
2. Share any folder from untrusted device.
3. On our device we can press Allow button in popup and folder automatically be added without password.

There should be no way to add folders without a password for an untrusted device.

**Comment by imsodin** [comment] 2021-06-10 21:11
Duplicate of https://github.com/syncthing/syncthing/issues/7705

I am working on it.

**Closed** 2021-06-10 21:12 UTC
Labels: bug, needs-triage
