### ISSUE TITLE
Panic: fatal error: missing stackmap

### ISSUE THREAD

**Issue by nigelhooper** [syncthing/syncthing#7559] opened 2021-04-09 18:20 UTC
All of a sudden I am now getting this panic log error at startup when running under SyncTrayzor on windows and so I am reporting it her as per the instructions in the console:

[start] 19:10:25 INFO: syncthing v1.15.1 "Fermium Flea" (go1.16.3 windows-amd64) teamcity@build.syncthing.net 2021-04-06 08:42:29 UTC
...
Panic at 2021-04-09T19:10:25+01:00
fatal error: missing stackmap

runtime stack:
runtime.throw(0x104b719, 0x10)
	runtime/panic.go:1117 +0x79
runtime.getStackMap(0x28d0f968, 0x28d0fa70, 0x28d0fa01, 0x0, 0x0, 0x18, 0x127a223, 0x0, 0x0, 0x0)
	runtime/stack.go:1257 +0x7a8
runtime.adjustframe(0x28d0f968, 0x28d0fa58, 0x189ebc0)
	runtime/stack.go:644 +0x8b
runtime.gentraceback(0xffffffffffffffff, 0xffffffffffffffff, 0x0, 0xc000048000, 0x0, 0x0, 0x7fffffff, 0x1237138, 0x28d0fa58, 0x0, ...)
	runtime/traceback.go:322 +0x1155
runtime.copystack(0xc000048000, 0x8000)
	runtime/stack.go:908 +0x311
runtime.shrinkstack(0xc000048000)
	runtime/stack.go:1180 +0x149
runtime.scanstack(0xc000048000, 0xc000041e98)
	runtime/mgcmark.go:720 +0x58e
runtime.markroot.func1()
	runtime/mgcmark.go:233 +0xce
runtime.markroot(0xc000041e98, 0x7)
	runtime/mgcmark.go:206 +0x35a
runtime.gcDrain(0xc000041e98, 0x7)
	runtime/mgcmark.go:1014 +0x12d
runtime.gcBgMarkWorker.func2()
	runtime/mgc.go:2003 +0x176
runtime.systemstack(0x0)
	runtime/asm_amd64.s:379 +0x6b
runtime.mstart()
	runtime/proc.go:1246

goroutine 12 [GC worker (idle)]:
runtime.systemstack_switch()
	runtime/asm_amd64.s:339 fp=0xc000437f60 sp=0xc000437f58 pc=0x4727e0
runtime.gcBgMarkWorker()
	runtime/mgc.go:1967 +0x1e7 fp=0xc000437fe0 sp=0xc000437f60 pc=0x41ef47
runtime.goexit()
	runtime/asm_amd64.s:1371 +0x1 fp=0xc000437fe8 sp=0xc000437fe0 pc=0x474681
created by runtime.gcBgMarkStartWorkers
	runtime/mgc.go:1835 +0x3e

goroutine 1 [preempted (scan)]:
reflect.resolveNameOff(0xf1aa20, 0x16110, 0xe4dfd0)
	runtime/runtime1.go:497 +0x53
reflect.(*rtype).nameOff(...)
	reflect/type.go:686
reflect.implements(0xf1aa20, 0xfeee00, 0xfeee00)
	reflect/type.go:1523 +0x4cc
reflect.(*rtype).Implements(0xfeee00, 0x13589a8, 0xf1aa20, 0x13589a8)
	reflect/type.go:1440 +0x7d
encoding/xml.(*Decoder).unmarshal(0xc000272240, 0x101b6c0, 0xc000435800, 0x199, 0xc0004c3f00, 0xc000435800, 0x199)
	encoding/xml/read.go:358 +0x2711
encoding/xml.(*Decoder).unmarshal(0xc000272240, 0xeb4280, 0xc00006d820, 0x197, 0xc0004c3f00, 0xeb4280, 0xc00006d820)
	encoding/xml/read.go:401 +0x25c5
encoding/xml.(*Decoder).unmarshalPath(0xc000272240, 0xc0004074a0, 0xf81c00, 0xc00006d800, 0x199, 0x0, 0x0, 0x0, 0xc0004c3f00, 0x1, ...)
	encoding/xml/read.go:690 +0x58d
encoding/xml.(*Decoder).unmarshal(0xc000272240, 0xf81c00, 0xc00006d800, 0x199, 0xc00005fb40, 0x199, 0x0)
	encoding/xml/read.go:524 +0x1055
encoding/xml.(*Decoder).DecodeElement(0xc000272240, 0x1020ea0, 0xc00006d800, 0x0, 0x0, 0xc000000000)
	encoding/xml/read.go:151 +0x145
encoding/xml.(*Decoder).Decode(...)
	encoding/xml/read.go:139
github.com/syncthing/syncthing/lib/config.ReadXML(0x1330ee0, 0xc000006290, 0x4be71947c6d291f6, 0x4d6460434ee9ec81, 0x377a7cd51a10b9ce, 0xf4ca7d982201890d, 0x0, 0x0, 0x0, 0x0, ...)
	github.com/syncthing/syncthing/lib/config/config.go:153 +0xaa
github.com/syncthing/syncthing/lib/config.Load(0xc000037270, 0x4d, 0x4be71947c6d291f6, 0x4d6460434ee9ec81, 0x377a7cd51a10b9ce, 0xf4ca7d982201890d, 0x1341858, 0xc00025f140, 0x0, 0x0, ...)
	github.com/syncthing/syncthing/lib/config/wrapper.go:161 +0x146
github.com/syncthing/syncthing/lib/syncthing.LoadConfigAtStartup(0xc000037270, 0x4d, 0xc000179098, 0x1, 0x1, 0xfad700, 0xc00025d800, 0x0, 0x0, 0x0, ...)
	github.com/syncthing/syncthing/lib/syncthing/utils.go:71 +0x12b
main.syncthingMain(0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	github.com/syncthing/syncthing/cmd/syncthing/main.go:611 +0x4ea
main.serveOptions.Run(0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	github.com/syncthing/syncthing/cmd/syncthing/main.go:423 +0x3f8
reflect.Value.call(0x1032fc0, 0x1900c00, 0x293, 0x103ebae, 0x4, 0xc00009fc38, 0x0, 0x0, 0x4acdd4, 0x1032fc0, ...)
	reflect/value.go:476 +0x907
reflect.Value.Call(0x1032fc0, 0x1900c00, 0x293, 0xc00009fc38, 0x0, 0x0, 0xb, 0xec7f60, 0x0)
	reflect/value.go:337 +0xc5
github.com/alecthomas/kong.callMethod(0x103e6ca, 0x3, 0x1032fc0, 0x1900c00, 0x199, 0x1032fc0, 0x1900c00, 0x293, 0xc00025d410, 0xc0000a7180, ...)
	github.com/alecthomas/kong@v0.2.12/callbacks.go:71 +0x4ba
github.com/alecthomas/kong.(*Context).RunNode(0xc0000a7180, 0xc000176750, 0x0, 0x0, 0x0, 0x0, 0x0)
	github.com/alecthomas/kong@v0.2.12/context.go:679 +0x565
github.com/alecthomas/kong.(*Context).Run(0xc0000a7180, 0x0, 0x0, 0x0, 0x0, 0x0)
	github.com/alecthomas/kong@v0.2.12/context.go:696 +0xa5
main.main()
	github.com/syncthing/syncthing/cmd/syncthing/main.go:259 +0x2b6

goroutine 6 [chan receive]:
github.com/syncthing/notify.(*recursiveTree).dispatch(0xc0000626e0)
	github.com/syncthing/notify@v0.0.0-20210308121556-f45149b04939/tree_recursive.go:125 +0xce
created by github.com/syncthing/notify.newRecursiveTree
	github.com/syncthing/notify@v0.0.0-20210308121556-f45149b04939/tree_recursive.go:119 +0x13b

goroutine 7 [sleep]:
time.Sleep(0x1dcd6500)
	runtime/time.go:193 +0xe5
github.com/syncthing/syncthing/lib/dialer.init.0.func2()
	github.com/syncthing/syncthing/lib/dialer/internal.go:44 +0x35
created by github.com/syncthing/syncthing/lib/dialer.init.0
	github.com/syncthing/syncthing/lib/dialer/internal.go:43 +0x16c

goroutine 9 [select]:
github.com/thejerf/suture/v4.(*Supervisor).Serve(0xc000272120, 0x1345548, 0xc00005fa00, 0x0, 0x0)
	github.com/thejerf/suture/v4@v4.0.0/supervisor.go:349 +0x42a
created by github.com/thejerf/suture/v4.(*Supervisor).ServeBackground
	github.com/thejerf/suture/v4@v4.0.0/supervisor.go:294 +0x5e

goroutine 10 [select]:
github.com/syncthing/syncthing/lib/events.(*logger).Serve(0xc00025f140, 0x1345548, 0xc00005fa40, 0x0, 0x0)
	github.com/syncthing/syncthing/lib/events/events.go:290 +0x174
github.com/thejerf/suture/v4.(*Supervisor).runService.func2(0xc000272120, 0xc000000000, 0x1baa118, 0xc00025f140, 0x1345548, 0xc00005fa40, 0xc000264330, 0xc000431140)
	github.com/thejerf/suture/v4@v4.0.0/supervisor.go:546 +0x7e
created by github.com/thejerf/suture/v4.(*Supervisor).runService
	github.com/thejerf/suture/v4@v4.0.0/supervisor.go:534 +0x185

**Comment by calmh** [comment] 2021-04-09 18:39
This is a weird error I've never seen before and it looks like it's during startup, so I'm going to guess the binary is corrupted, your hardware is broken, or you have some weird antivirus that tries to inject itself somehow and breaks things...

**Comment by nigelhooper** [comment] 2021-04-12 09:36
It is happening during startup.  I have redownloaded SyncTrayzorPortable-x64 Version 1.1.28 (same version I had installed) and copied the data directory across and it is still doing it. I am running windows defender as the antivirus.  The hardware is not showing any indications of problems.  When I get a chance I will try the previous version of SyncTrayzor and also try a virgin install without my data directory.

**Comment by AudriusButkevicius** [comment] 2021-04-12 09:39
I suggest you try latest syncthing release from github without synctrayzon

**Comment by bt90** [comment] 2021-04-12 10:51
> It is happening during startup. I have redownloaded SyncTrayzorPortable-x64 Version 1.1.28 (same version I had installed) and copied the data directory across and it is still doing it. I am running windows defender as the antivirus. The hardware is not showing any indications of problems. When I get a chance I will try the previous version of SyncTrayzor and also try a virgin install without my data directory.

I think Synctrazor downloads and executes the syncthing binary in its AppData folder. You might still be testing a corrupted exe.

**Comment by imsodin** [comment] 2022-01-29 14:11
As it can't be reproduced one cannot act on this (and it might be hardware related) -> closing.

**Closed by imsodin** 2022-01-29 14:11 UTC
Labels: bug, needs-triage
