### ISSUE TITLE
Make smthg with Upper/lowercase filenames

### ISSUE THREAD

**Issue by Xeenych** [syncthing/syncthing#5184] opened 2018-09-12 08:00 UTC
ST refuses to sync SomeFileName.txt to somefilename.txt on windows or if you rename file changing case of some letters
It is related to how filename is hashed and stored in database and how changes are watched based on filename.

ST should respect caseness of filenames.
If filesystem do not support similar filenames in one folder (e.g. on windows filename and FileName are equal) ST should warn and do not sync this folder

**Comment by imsodin** [comment] 2018-09-12 08:13
duplicate of https://github.com/syncthing/syncthing/issues/2739

**Closed by imsodin** 2018-09-12 08:13 UTC
