### ISSUE TITLE
Previously not ignored folders syncing continuosly after delete then ignore

### ISSUE THREAD

**Issue by gigabit942007** [syncthing/syncthing#8136] opened 2022-01-23 12:02 UTC
### Does your log mention database corruption?

No

### Include required information
Client 1:  v1.18.6, Linux (64-bit Intel/AMD)  -> Device P in screenshots
Client 2: v1.18.6, Windows (64-bit Intel/AMD) -> Device D in screenshots
Client 3: V1.18.6 Windows (64-bit Intel/AMD) -> Device A in screenshots (this device was once connected and was syncing the folder i deleted. For the duration of the modification it was disconnected)

Syncthing tries to sync ignored folders.
![image](https://user-images.githubusercontent.com/8338004/150677171-2371b4e1-0dc5-43be-a4c3-d5a9f701ee42.png)

I have this issue since quite a long time, at least version 1.0.0

I had only Syncthing Linux running, while it was running i deleted some folders from folder "Documents".
After i deleted the folder i have put it in the folder in the ignore list like this:
![image](https://user-images.githubusercontent.com/8338004/150676914-f4df4e2a-4e30-424d-9f30-012aa510a4de.png)

Add client D and share folders. Add the ignore list too. The device D also has that folder already made but it should be ignored because it was never synced.

At the moment:

Deleted folder does not exist on Device P
Deleted folder exists on Device D (it is created automatically)
Deleted folder exists on Device A (however this device was never turned on)

Syncthing tries to sync files that are ignored:
![image](https://user-images.githubusercontent.com/8338004/150677095-70c8af4f-441e-4c02-923b-8eb9ab1a8faf.png)

Steps to follow:
- link 3 devices with syncthing
- sync a folder with subfolders and sub-sub-folders on all 3 devices
- disconnect one device
- remove 1 device
- you now have; 1 connected device and 1 disconected device
- from the connected device copy the folder structure to a new device which was never connected.
- remove sub-sub-folder from the currently connected device and add it to the ignore list
- add the new device with the old folder structure to the network complete with the ignore list
- you should now have syncthing trying to sync folders that are ignored from the new device just like you see in the screenshot.

The solution is to start with a fresh database everywhere, but from time to time i add stuff to the ignore list that was previously syncing and this causes an issue like to happen so it's not really convenient.

**Comment by tomasz1986** [comment] 2022-01-23 12:31
Honestly, the explanation sounds quite complex, but the issue itself, at least for me, looks similar to https://github.com/syncthing/syncthing/issues/7474. There's no fix to the problem so far, unfortunately, other than connecting all devices together.

I don't understand these three steps though.

> * disconnect one device
> * remove 1 device
> * you now have; 1 connected device and 1 disconected device

What do you mean exactly by "remove"? If the device was indeed removed, it shouldn't be present on the "remote devices" list. Do you, by any chance, mean that you just shut Syncthing down on it?

**Comment by imsodin** [comment] 2022-01-30 16:57
I agree with the above: This might be a duplicate of #7474, but generally isn't clear enough to be an actionable/fixable issue, i.e. requires further debugging. Please open a topic on https://forum.syncthing.net to investigate this issue further.

**Closed by imsodin** 2022-01-30 16:57 UTC
Labels: bug, needs-triage
