### ISSUE TITLE
More detailed sync logs in the web gui

### ISSUE THREAD

**Issue by lovetox** [syncthing/syncthing#1683] opened 2015-04-22 21:12 UTC
Hi there,

Something i wished for since im using syncthing, are data like:

which files did a node already sync and which not

right now i only know the last time the node was online and that it finished (?) at least one file.
thats not very much. 
last synced file is cute, but i dont see why it has a place in the gui when other more meaningful data doesnt.

i guess some of that information can be obtained through log files, but i hope its planned to move some  of the data like this into the gui

i tried to search for a similar thread but didnt find anything, sorry if that topic was already requested.

keep going with the good work.

**Comment by AudriusButkevicius** [comment] 2015-04-22 21:36
What exactly would you expect to see?

**Comment by calmh** [comment] 2015-04-23 00:42
I think this may be #1550...

**Comment by calmh** [comment] 2015-04-23 00:43
Which in turn was a duplicate of #1437...

**Comment by lovetox** [comment] 2015-04-23 08:13
@calmh the other tickets are mostly about errors, definitely also an issue, though i didnt see many errors until now :D

for example:

if you klick on some history button for a folder

you can see in rows, all the files that were synced with the date, time, size and finish.

so someone could see for example: the node was online synced these files but the most important one is still left etc.

or for example, that i could see, the node finished all the files, and i can delete the node from my syncthing cause that was all was needed.

**Comment by AudriusButkevicius** [comment] 2015-04-23 08:30
Well if the node ia offline, we don't even know what it has as it's offline hence we cannot make any assumptions on what he has and what portion of his files we have. Furthermore the files might have changed while he was offlinr, so the fact that we think we have everything might be a lie. We can only deduce this once connected, and at that point you have the out of sync list/status bar which gives you what you want.

**Comment by lovetox** [comment] 2015-04-23 08:41
im not talking about "status" in percent or something like this, i know this was discussed in other topics and it looks to be a problem.

im not a programmer, but i cant believe you need the other node online to determine what your own computer transfered. this information surley has to be already in some logs? 

date time, file x started transfering
date time, node x signaled file x is finished - move on to the next

this information is stored, and can be viewed, if the node is later online or not does not matter

i hope i expressed myself better.

**Comment by calmh** [comment] 2015-04-23 08:44
Currently, what the other devices do is not logged. Actually, not even what we do ourselves, though that could at least be done. For other devices though, we don't know what they did. Maybe the synced file A from us and file B from someone else. We could show file A as the latest file synced by them, but it could be a lie.

**Comment by lovetox** [comment] 2015-04-23 08:54
hm ok.

yeah i only want to see what my machine did.
if a node gets a file from another node than me, that of course should not show up in my log / or at least thats not what i need.
i also understand that this needs no prominent place in the gui.

its just the simple case, i come home, nodes are all offline, i want to get a glimpse of what was done. there is no need for you to make definitive statements about percentage, status.
just the simple facts what was done. without further conclusions.

date, file x was transfered at that time. like a log, somewhere in some hidden menu.
i understand that you dont want to draw wrong conclusions in the gui and give wrong information.

**Comment by calmh** [comment] 2015-04-23 12:21
No that makes sense, we could keep that information somewhere.

**Comment by AudriusButkevicius** [comment] 2015-04-23 12:59
It would also be fairly easy to implement. We could just have a log file to start with.

**Comment by hashworks** [comment] 2015-04-24 10:23
At least the normal output isn't providing this information. Is it logged anywhere else atm?

**Comment by AudriusButkevicius** [comment] 2015-04-24 10:25
No, apart from something which could indicate that fact in verbose cryptic logs with all debug flags enabled.

**Comment by Mirodin** [comment] 2015-07-22 19:39
I could picture to myself something like the "Sync" Log the ownCloud Desktop Client as I always loved that feature for the information that file x was synced 5 sec ago or something like that. All these informations can be discarded on next startup as they are no longer relevant (changes on other machines etc.).

For example: I do have a KeePass file in one of my sync folders and the "rescan interval" is set to 600 sec cause there are many files in that folder and I don't want constant scanning. But whenever I add a new entry to my KeePass file I could see on a glance that the file has been transfered to at least one other node and I can shutdown my workstation as that change will propagate to all my nodes eventually.

**Comment by AudriusButkevicius** [comment] 2015-07-22 19:41
The -verbose or -audit option provides that I think, but in the console, same way `Up to date` status on the device implies that the device has everything.

Also, there is no such concept as `someone has downloaded X`, there is only a concept of `someone asked for a slice of X, I am not sure if he's got the whole thing yet or he's still missing some other file Y` kind of thing.

**Comment by Mirodin** [comment] 2015-07-22 19:49
I think I get what you mean but if the node is not connected right now, I don't know if the file was synced i.e. 5 minutes ago or 2 hours ago. I understand that this is no easy task but one could ask the other node to provide something like a timestamp for all of its files so I know how old they are.

If that is to big of a deal a local list of timestamps would help a lot as well which does not include any assumption about status on other machines.

**Comment by AudriusButkevicius** [comment] 2015-07-22 19:56
I think what you are after is actually https://github.com/syncthing/syncthing/issues/1883

**Comment by Mirodin** [comment] 2015-07-22 20:06
Yes, you are right it is something in between this issue and the one you mentioned. But I think a detailed "who has which blocks" is too much for 99 out of 100 cases. Most people I know only care if a file they changed has been propagated i.e.: timestamp + hash on the other node == my timestamp + hash => identical file (so I can log that on the gui).

**Comment by nrm21** [comment] 2015-11-29 02:35
Hi,

I believe I have coded some sort of semi-solution to this.  I'm not sure it's exactly what the OP is looking for but basically I have written some code that listens for incoming changes and records them in a separate log file than the debug log.  The feature is far from what I would call complete (it still needs a way to turn it off an on in the config, and maybe some log rollover capabilities).

But anyway.. how does this work?  Do I submit some sort of pull request on the code?  I've very little experience with Git, or FOSS ettiquite when working on others teams for coding.

**Comment by AudriusButkevicius** [comment] 2015-11-29 02:40
Yeah, you submit a PR against head, subject its well implemented and useful, it will get merged.

**Comment by nrm21** [comment] 2015-11-29 04:24
Lol, well... It might not be the best implemented but it's also my first attempt at Go code (I've previously only coded in C#, Java, Python and VB before).  I'm certainly willing to learn and try out any suggestions to fix if it sucks.  :)

**Comment by AudriusButkevicius** [comment] 2016-12-21 18:00
Closed by #3694

**Closed by AudriusButkevicius** 2016-12-21 18:00 UTC
Labels: easy, enhancement
