### ISSUE TITLE
Syncthing not distinguishing DOS 8.3 aliases on Windows

### ISSUE THREAD

**Issue by nicholaelaw** [syncthing/syncthing#3800] opened 2016-12-14 03:32 UTC
This just happened to me and I'm having a hard time finding a solution besides file recovery.

I have a folder that's sync'ed between the office computer and my desktop & NAS back home. Folder contains roughly 3k subfolders and 45k files, mainly txt, pdf, xlsx and R scripts & data file (rds).

 - what happened,

Last night at home I noticed that there are two extra folders that I didn't create. I have a folder named `bulldozer`, and one the extra folder is named `BULLDO~1`; within `bulldozer` there is a subfolder named `LFDataTool`, and the other extra folder is named `LFDATA~1` and resides in the same parent directory.

To illustrate this, consider the following folder hierarchy:

    - <sync folder root>
        - bulldozer
            - LFDATA~1
                <partially matching LFDataTool>
            - LFDataTool
            <... other folders and files>
        - BULLDO~1
            <partially matching bulldozer>

I briefly checked both folders and found them containing partial content from the matching originals. In a moment of confusion and eager for bedtime, I decided that these are temporary files and deleted them. To further complicate things, I deleted one folder on my PC, and the other through CIFS on the NAS. 

When I arrived at work this morning, I'm suprised that the content of both `bulldozer` and `LFDataTool` are mostly gone, what's left resembles the content of those two `~1` folders, which I deleted and may or may not have emptied the recycle bin. The PC at least has a recycle bin, but the NAS does not.

 - what you expected to happen instead,

Obviously I didn't expect to find two extra folders that I didn't create and weren't named as syncthing-conflict. Neither did I expect that deleting those folders could result in files being deleted in other folders. I'm desperately searching for file recovery programs, and it seems that browser cache has already overwritten some of those lost data. I'd have to wait until home to try a full recovery.

 - any steps to reproduce the problem.

Not sure how to recreate this, but I was mainly working on my office computer. The home computer only gets powered on once every two days or so. The NAS however was constantly sync'ed and the extra two folders were visible on the NAS as well. One more detail, at the time of deletion, the folders have some failed items. They've been there for a while, from some symlinks generated during package development I think.

### Version Information

Office: Windows 10 Pro, Syncthing 0.14.13
Home: Windows 10 Pro, Syncthing 0.14.13
NAS: Synology DSM 6.0, Syncthing 0.14.12

**Comment by calmh** [comment] 2016-12-14 06:52
The root problem here is that `LFDataTool` and `LFDATA~1` are the same thing on Windows, but not anywhere else, and Syncthing doesn't know of this equivalence. How both folders ended up there is the question.

**Comment by nicholaelaw** [comment] 2016-12-14 06:52
I should add that I am not 100% certain that syncthing did this. I'm merely describing what I'm observing. 

I'm still in the process of recovering the files and folders and structures. Office computer is toast, too much overwritten already. Best shot is the home computer where the folder was stored on a non-boot disk.

**Comment by nicholaelaw** [comment] 2016-12-14 07:14
@calmh Well got to try recover those files first. Then I can dig around to see why the folders got "split"

**Comment by bugith** [comment] 2016-12-14 07:19
dir /x shows 8.3 aliases

**Comment by nicholaelaw** [comment] 2016-12-14 08:03
@bugith But DOS programs that actually use 8.3 aliases should not be able to create a folder with an 8.3 alias that is conflicting existing folder names. Similarly explorer would stop and ask to merge folders if you do this via GUI. Indeed how they both ended up showing is the real question.

**Comment by bugith** [comment] 2016-12-14 13:03
Take note that the registry key above is for NTFS only. Not sure it would change [ex]FATXX behaviour.

**Comment by AudriusButkevicius** [comment] 2016-12-14 14:21
Anyways, I don't really see how this is our bug to be honest, it's just windows handling it incorerectly?

**Comment by nicholaelaw** [comment] 2016-12-14 15:07
I'm not sure where the problem lies. Maybe I'll change the title to reflect that fact.

**Comment by AudriusButkevicius** [comment] 2016-12-14 15:21
So how exactly do we reproduce the problem, or what exactly needs fixing? As I am against having a ticket open that is not actionable by us (oppse to microsoft or whatever software that created the aliases).

**Comment by nicholaelaw** [comment] 2016-12-14 15:53
I understand it is most likely that syncthing merely propagated the error to other machines. Is it possible that we implement a check on such folder names, and at least pop up a warning for action, so that user may realise the problem and fix it before it is sync'ed across the net?

**Comment by canton7** [comment] 2016-12-14 16:10
It seems odd that Syncthing would pick up on an 8.3 filename, I think? What could cause it to do this?

**Comment by wweich** [comment] 2016-12-14 16:21
I could imagine, that if a software uses the DOS 8.3 alias to create/modify a file, inotify could get that path.

**Comment by canton7** [comment] 2016-12-14 16:40
Aha, inotify. That's a good point.

@nicholaelaw do you use syncthing-inotify, or another wrapper which provides inotify support?

**Comment by canton7** [comment] 2016-12-14 16:49
Incidentally, Go doesn't provide an official way to expand an 8.3 filename, but there is an unsupported method (https://github.com/golang/go/issues/17084). You can of course call winapi stuff as well.

My instinct is that the smartest solution is for Syncthing to canonicalise paths it receives scan requests for over the API, recognising that multiple paths can refer to the same directory. Whether it's worth the effort is of course another matter.

**Comment by AudriusButkevicius** [comment] 2016-12-14 16:49
Sadly I don't think there is anything we can do here, as explained, due to things like inotify picking these up anyway. You should just disable these or kill the software that generates them.

**Comment by canton7** [comment] 2016-12-14 16:51
> Sadly I don't think there is anything we can do

Sure, you certainly can do stuff. SyncTrayzor is (IIRC) smart enough to see filesystem notifications for 8.3 paths and canonicalise them into full paths before sending them to Syncthing. If I can do it, it's possible for you to do it, too.

Whether you choose to do it - whether it's worth doing - is another matter.

**Comment by AudriusButkevicius** [comment] 2016-12-14 16:55
But the problem is that both of these physically exist on disk, so we shouldn't really expand it? Otherwise I don't see how we could pick up these paths as I don't think listdir returns them to us unexpanded?

**Comment by canton7** [comment] 2016-12-14 17:11
I *think* the cause is (and @nicholaelaw needs to confirm this):

1. Just the long path exists on all devices (e.g. "FooBarBaz\File")
2. Something on device A manipulates a file using its 8.3 path (e.g. "FooBarBa~1\File", which is just another way of accessing FooBarBaz\File)
3. Some inotify client spots this and tells Syncthing "hey, go and scan "FooBarBa~1\File" now".
3. Syncthing scans the 8.3 path, "FooBarBa~1\File", goes "OH! A new file! I'll track and synchronize that".
4. Device B receives the "new" file at "FooBarBa~1\File" and creates an actual new directory and files. 
5. This then gets propagated back to Device A.

My understanding is that Syncthing is the reason both "FooBarBa~1\File" and "FooBarBaz\File" exist on disk in the first place, because it saw "FooBarBa~1\File" and thought it referred to a different thing than "FooBarBa~1\File".

**Comment by nicholaelaw** [comment] 2016-12-14 17:40
@canton7 I can confirm that your description does fit what happened here. I am using `inotify` to get timely sync. 

I'm still trying to figure out when this happened based on what I've recovered and which program is responsible. In the mean time as a precaution I'll disable `inotify` on all Windows machines. It is probable that one of the tools R uses to build packages did this, but I need to verify my suspicion. Thank you all for helping, I've learned a lot this day.

**Comment by AudriusButkevicius** [comment] 2016-12-14 17:54
It still does not add up. How did deleting this 8.3 path (or stuff in it) delete files in the original folder?

**Comment by nicholaelaw** [comment] 2016-12-14 18:06
@AudriusButkevicius That's because I was wrong in interpreting what happened. I've combed through half of `BULLDO~1` now, and my theory is that once syncthing got confused and actually creates a matching 8.3   folder, it starts (or got notified) to syncthing all files to the 8.3 folder, never looking back.

My observations are as follows:

1. `BULLDO~1` contains some of the folders/files from `bulldozer`;
2. `bulldozer` is missing many files and folders. Most are recently accessed/modified;
3. There are many duplicates;
4. All the duplicates I've looked at so far have timestamps merely seconds apart;
5. There is a `LFDATA~1` under both `BULLDO~1` and `bulldozer`.

Perhaps you can draw a more reasonable conclusion.

**Comment by canton7** [comment] 2016-12-14 18:08
In step 2, Syncthing created new entries in device A's database saying that a new real path, `FooBar~1\File`, exists. This is propagated to device B as a real path.

 When the real path is deleted on device B, device A received an index update saying "Delete `FooBar~1\File`. It dutifully asks Windows to delete `FooBar~1\File`, which deletes `FooBarBaz\File1`.

**Comment by nicholaelaw** [comment] 2016-12-14 18:09
@canton7 Per my previous post, I think the files got deleted by syncthing before I deleted the 8.3 folders. But that's based on a MacBook backup which wasn't affected. So I could be wrong.

**Comment by canton7** [comment] 2016-12-14 18:10
Hmm, there's some other funky weirdness going on then. Either way, I bet it's ultimately due to inotify giving Syncthing an 8.3 path and Syncthing getting confused by the fact that there are two paths which refer to the same file on disk. Canonicalising the path before scanning should solve it, whatever it is, I think.

**Comment by nicholaelaw** [comment] 2016-12-14 18:14
To correct my mistakes, I now think most of the duplicate files in `BULLDO~1` are NOT recently accessed/modified. Many of these files were last accessed months ago and was sync'ing fine at least last week.

**Comment by AudriusButkevicius** [comment] 2016-12-14 18:36
Anyways, until someone has a step by step repro that deletes files incorrectly, I am skeptical of potential data loss. Sure, we should do expansion on input on the API I guess, yet I don't see an easy way to do that, and to be honest, it's easier for the user just to disable this nonsense         all together.

**Comment by canton7** [comment] 2016-12-14 19:30
> and to be honest, it's easier for the user just to disable this nonsense all together.

Really? That requires changing a registry key, which potentially breaks other things.

Fixing it is, at its worst, one or two winapi calls.

**Comment by calmh** [comment] 2016-12-15 07:29
In the end I think this is the same or similar to the case sensitivity issue (two directories `foo` and `FOO` that are separate on Linux etc but map to the same directory on Windows & Mac).

But if there is a simple way to resolve short names to real names we should do that in the scanner so that we get consistent names from that layer. I think that should solve this issue, as we would get asked to scan `LFDATA~1` but return index entries for `LFDataTool` etc.

**Comment by nicholaelaw** [comment] 2016-12-16 05:08
As a sidenote, any suggestions on how to clean this up? After all that debacle, I've got 33 items failed across all machines. They either come from `BULLDO~1` or `LFDATA~1`, and the reason for sync failure is either `The process cannot access the file because it is being used by another process.` or `The directory is not empty.`.

Can I just mark the folder on one the machines as the newest, and force the others to forget about the failures and sync to it?

**Comment by calmh** [comment] 2016-12-16 05:41
I'd do something like this. 

Rename the LFDataTool folder to something else. Same for other affected folders. 

Let the deleted of LFDataTool sync everywhere, along with the new files from the rename. If syncthing fails to clean our LFDataTool somewhere, help it by cleaning it out manually. 

Rename it back.

**Comment by AudriusButkevicius** [comment] 2017-07-27 19:41
This needs to be plugged in somewhere.

```
func ToLong(path string) (string, error) {
        p, err := syscall.UTF16FromString(path)
        if err != nil {
                return "", err
        }
        b := p // GetLongPathName says we can reuse buffer
        n := uint32(len(b))
        for {
                n, err = syscall.GetLongPathName(&p[0], &b[0], uint32(len(b)))
                if err != nil {
                        return "", err
                }
                if n <= uint32(len(b)) {
                        return syscall.UTF16ToString(b[:n]), nil
                }
                b = make([]uint16, n)
        }
}
```

**Comment by canton7** [comment] 2017-07-29 15:17
Bear in mind that you might be notified about a deleted 8.3 path, and GetLongPathName will fail in that case. The approach I took was to chop the path back until it didn't contain any directories with a ~ in and scan that, but there might be something better.

**Comment by AudriusButkevicius** [comment] 2017-07-29 15:41
Worst case we should just refuse to scan anything with `~\d\/`

**Comment by imsodin** [comment] 2018-05-28 22:06
I adapted @canton7's implementation and @AudriusButkevicius's snippet above to filter out 8.3 filenames coming from the FS watcher (probable cause of #4956): #4975 I only added it there, as the "normal" os commands (i.e. while walking to scan) don't return 8.3 stuff as far as I understand.

**Comment by fbreve** [comment] 2018-06-11 12:45
Since this has a major potential for data loss, shouldn't an update be pushed immediately? Either enabling the fix or disabling fswatcher on Windows until the next version?

**Comment by calmh** [comment] 2018-06-11 13:40
.49 tomorrow.

**Comment by fbreve** [comment] 2018-06-11 14:51
Thanks. I'll wait for it before trying to rejoin the folders. Otherwise they keep getting split and losing files all the time.

**Comment by AudriusButkevicius** [comment] 2018-06-11 16:44
If you already had it, it's potentially too late, you'll have to rebuild your db to fix things and not loose data.

**Comment by fbreve** [comment] 2018-06-11 22:23
I was thinking about letting it get synced. Then rename the 8.3 folder, wait for the deletion to propagate to other machines and come back to the original folder, then move the content of the 8.3 folder back to the original folder.

**Comment by AudriusButkevicius** [comment] 2018-06-11 22:54
Either way, keep a backup, as a rename/delete one could delete either.

**Comment by tomasz1986** [comment] 2021-10-01 12:55
There's been no new reports on this issue for at least 3 years, and I myself haven't seen anything on the forums related to 8.3 names at least during the last 2 years.

Is this issue still relevant, or was the problem in fact completely fixed by https://github.com/syncthing/syncthing/pull/4975?

**Closed** 2021-10-01 14:07 UTC
Labels: enhancement
