### ISSUE TITLE
Add local sync mode

### ISSUE THREAD

**Issue by SpringWhisper** [syncthing/syncthing#9533] opened 2024-05-08 17:40 UTC
### Feature description

The ability to sync between devices is great right now, but I'm wondering if you can add local sync. That is, keep two folders on the same device in sync.

### Problem or use case

Example 1:
I have computer A at home and computer B in company. Company computers are not allowed to connect to the Internet, but USB flash drives are allowed. I want to plug the USB flash drive into computer A, sync the files, and then bring it to the company computer B, sync the files.

Example 2: :
I am mapping a web disk, to a local disk, and I want to synchronize the local files to the web disk, that is, use the web disk as a nas.

### Alternatives or workarounds

There are many software that enable local synchronization, such as SyncToy. But I need to sync files between different devices and locally at the same time, and I'm wondering if I can use one software to solve this problem.

**Comment by tomasz1986** [comment] 2024-05-08 20:19
Duplicate of https://github.com/syncthing/syncthing/issues/4721.

**Closed by tomasz1986** 2024-05-08 20:19 UTC
Labels: enhancement, needs-triage
