### ISSUE TITLE
Suspecting a memory leak related to QUIC connections

### ISSUE THREAD

**Issue by leipert** [syncthing/syncthing#8243] opened 2022-03-30 13:31 UTC
### Does your log mention database corruption?

> If your Syncthing log reports panics because of database corruption it is
most likely a fault with your system's storage or memory. Affected log
entries will contain lines starting with `panic: leveldb`. You will need to
delete the index database to clear this, by running `syncthing
-reset-database`.

No

### Include required information

Please be sure to include at least:

 - which version of Syncthing and what operating system you are using
 
   - `syncthing v1.19.1 "Fermium Flea" (go1.17.6 darwin-arm64) brew@HMBRW-A-001-M1-004.local 2022-02-21 13:57:21 UTC [noupgrade]` (via homebrew)
   - macOS Monterey 12.3, MacBook Pro (2021), 32GB RAM
 - browser and version, if applicable: 'N/A'

After running for a few days syncthing takes up almost 1 GB of RAM, which is unexpected for a machine with just 1 shared folder with: 269 files, 22 folders and  ~628 MiB total size. The contents of the folder don't change that often, and a few days ago the RAM usage was way lower. syncthing hasn't been interacted with in these last two days. syncthing is running for about a week now.

| March 28th | March 30th |
| - | - |
| <img width="998" alt="Screenshot 2022-03-28 at 22 55 43" src="https://user-images.githubusercontent.com/2906107/160845819-5e7cf01b-bbc0-4e6c-8c9c-5eab2b421033.png"> | ![Screenshot 2022-03-30 at 15 21 06](https://user-images.githubusercontent.com/2906107/160845728-b189efb5-1f85-40b4-ab4a-aecd360bce58.png) |
| 394 MB RAM | 932 MB RAM |

**Comment by AudriusButkevicius** [comment] 2022-03-30 16:39
Feels like this should live on the forum?

**Comment by calmh** [comment] 2022-03-30 18:03
Let's see what the profile says

**Comment by leipert** [comment] 2022-03-30 19:01
@calmh Here are the profiles:
[syncthing-profiles.zip](https://github.com/syncthing/syncthing/files/8383365/syncthing-profiles.zip)

Sorry if this isn't the right place to report this, @AudriusButkevicius

**Comment by leipert** [comment] 2022-03-30 19:21
Had a look with pprof. Seems like a lot of memory is related to `quic`. Wonder if https://github.com/lucas-clemente/quic-go/issues/3322 is somehow related 🤔

**Comment by AudriusButkevicius** [comment] 2022-03-30 19:35
I don't think we churn through streams, we have one per connection. I'm on the phone so can't check the profile to give any more meaningful insights.

**Comment by charleshan** [comment] 2022-03-30 21:36
I've had this issue as well. After a while, the memory usage grows 10x. Also, there's a constant 20-25% CPU usage. After restarting, it goes down to ~0.6%.

![ScreenCapture 2022-03-30 at 14 33 56](https://user-images.githubusercontent.com/3143154/160934886-337817b2-6dcd-40b2-a725-800e75074780.png)

![ScreenCapture 2022-03-30 at 14 31 16](https://user-images.githubusercontent.com/3143154/160934365-c65fa3f0-950f-4c7a-82c2-7dc1741dc6a2.png)

**Comment by leipert** [comment] 2022-03-30 22:33
@imsodin Just created a profile, about 4h later, saw an increase of 100MB since then:
[syncthing-heap-darwin-arm64-v1.19.1-003026.pprof.zip](https://github.com/syncthing/syncthing/files/8384571/syncthing-heap-darwin-arm64-v1.19.1-003026.pprof.zip)

**Comment by imsodin** [comment] 2022-03-31 06:49
Accompanied by a 30MB increase in that particalur pool in the profile.

Can you als grap goroutine traces please, to check if there's an unexpected amount of open streams or something - would be surprising but better be sure http://localhost:8384/debug/pprof/goroutine

The linked quic-go issue talks about not closing connections if I understand correctly. In our code it should be guaranteed that close is called, unless something is hung (which should then show in the traces from above).

**Comment by leipert** [comment] 2022-03-31 08:23
@imsodin That URL doesn't work. I assume I need to restart with `STPROFILER` set, as per: https://docs.syncthing.net/branch/untrusted/html/dev/debugging.html

**Comment by tomasz1986** [comment] 2022-03-31 08:41
> http://localhost:8384/debug/pprof/goroutine

The URL is http://localhost:9090/debug/pprof/goroutine actually 😉. `STPROFILER` does need to be enable beforehand though.

**Comment by bt90** [comment] 2022-03-31 09:04
Not a go dev but the note about using `io.ReadAll` instead of `io.ReadFull` seems relevant?

https://github.com/lucas-clemente/quic-go/issues/3322#issuecomment-1023882246

**Comment by leipert** [comment] 2022-04-06 08:40
Sorry for the delay. I haven't been using the M1 Mac in a while, and so I am not seeing a lot memory usage right now (also a system update forced a restart 🙈 ). It went from 70 MB baseline to 140 MB. Here are the dumps: [goroutine-check.zip](https://github.com/syncthing/syncthing/files/8425160/goroutine-check.zip). Will continue to monitor.

**Comment by leipert** [comment] 2022-04-08 11:10
@calmh / @imsodin After a few more days, I am north of 450 MB memory again. Attached the profiles here: 
[dumps_and_profiles.zip](https://github.com/syncthing/syncthing/files/8451283/dumps_and_profiles.zip)

Do you need more information or is this sufficient?

**Comment by bt90** [comment] 2022-04-08 15:18
@marten-seemann maybe this might be interesting for you

**Comment by imsodin** [comment] 2022-04-08 16:22
There's a ton of message writing routines. And a quic conn to be closed. Maybe the are contending or even dead-locking on something. @leipert Could you grap goroutines again with `http://localhost:9090/debug/pprof/goroutine?debug=2`

```
     35510   runtime.gopark
             runtime.goparkunlock (inline)
             runtime.semacquire1
             internal/poll.runtime_Semacquire
             internal/poll.(*fdMutex).rwlock
             internal/poll.(*FD).writeLock (inline)
             internal/poll.(*FD).WriteMsg
             net.(*netFD).writeMsg
             net.(*UDPConn).writeMsg
             net.(*UDPConn).WriteMsgUDP
             github.com/syncthing/syncthing/lib/stun.(*writeTrackingUdpConn).WriteMsgUDP
             github.com/AudriusButkevicius/pfilter.(*filteredConnObb).WriteMsgUDP
             github.com/lucas-clemente/quic-go.(*oobConn).WritePacket
             github.com/lucas-clemente/quic-go.(*baseServer).sendRetry
             github.com/lucas-clemente/quic-go.(*baseServer).handleInitialImpl.func1

         1   runtime.gopark
             runtime.chanrecv
             runtime.chanrecv1
             github.com/lucas-clemente/quic-go.(*session).CloseWithError
             github.com/syncthing/syncthing/lib/connections.(*quicTlsConn).Close
             github.com/syncthing/syncthing/lib/connections.internalConn.Close
             github.com/syncthing/syncthing/lib/protocol.(*rawConnection).internalClose.func1
             sync.(*Once).doSlow
             sync.(*Once).Do (inline)
             github.com/syncthing/syncthing/lib/protocol.(*rawConnection).internalClose
             github.com/syncthing/syncthing/lib/protocol.(*rawConnection).readerLoop
             github.com/syncthing/syncthing/lib/protocol.(*rawConnection).Start.func1
```

**Comment by leipert** [comment] 2022-04-08 16:46
@imsodin: Here you go:
[goroutine_debug_2.zip](https://github.com/syncthing/syncthing/files/8453923/goroutine_debug_2.zip)

**Comment by marten-seemann** [comment] 2022-04-08 17:34
Looks like sending of Retry packets (https://github.com/lucas-clemente/quic-go/blob/332473668a992ce372c54c353b2bdc24344cf46e/server.go#L424-L436) is leading to a big backlog. Any idea why `net.(*UDPConn).WriteMsgUDP` would do that?

> @imsodin: Here you go:
[goroutine_debug_2.zip](https://github.com/syncthing/syncthing/files/8453923/goroutine_debug_2.zip)

How do I open that file?

**Comment by bt90** [comment] 2022-04-08 17:48
> How do I open that file?

It's just a zipped textfile

**Comment by marten-seemann** [comment] 2022-04-08 17:55
Got it, looks like they're actually stuck at `WriteMsgUDP`.

Now one change we _could_ do in quic-go is to not spawn a separate Go routine for every retry, but only have a limited number of worker threads and discard Retries once they're all busy. But I'd prefer to understand why sending UDP packets is creating so much contention here.

**Comment by imsodin** [comment] 2022-04-08 19:20
The all try to write to the same `*netFD` protected by a lock which is held by one routine in iowait/netpoll since 1289min o.O  
No idea why it's blocked, but regardless a single write not going through shouldn't stall everything.  
Goroutines formatted with panicparse: [goroutine_debug_2-pp.txt](https://github.com/syncthing/syncthing/files/8454696/goroutine_debug_2-pp.txt)

**Comment by leipert** [comment] 2022-04-11 11:47
Thanks all for looking into this!

If it might help, I often switch between two networks (home and office). Maybe after waking from hibernation and/or between wired via Thunderbolt / wifi causes some weirdness. When I stayed at home for a few days, I didn't see the memory rise as dramatically.

@imsodin / @marten-seemann Unless you tell me otherwise I would restart the process regularly starting tomorrow as a mitigation, I am up to 900 MB again.

**Comment by marten-seemann** [comment] 2022-04-11 17:44
> They all try to write to the same *netFD protected by a lock which is held by one routine in iowait/netpoll since 1289min

This sounds like a potential Go bug, to be honest. Really, there's not a lot that a QUIC implementation can reasonably do if sending a packet takes longer than 21h.

**Comment by imsodin** [comment] 2022-04-11 21:44
The problem is all these operations are blocking, there's no way to pass a context/deadline to them. So even if the hang was detected, the goroutines would stick around.

Anyway a relevant problem in the current context is `quic.Connection.CloseWithError` blocking: It waits for sends to finish before returning, thus we never close the actual connection here. Maybe having a deadline there to unblock in quic would be appropriate (@marten-seemann ?). And we definitely can do that when closing the quic conn on our side: Wait 10s for the session to close, and if it doesn't go ahead closing everything else cutting our losses (leaving that on goroutine pending, but not accumulating further ones like it's happening here). Ugly, but less ugly than status quo.

**Comment by calmh** [comment] 2022-04-12 04:18
Does WriteMsgUDP not respect write deadlines? It seems one should be set, to be able to fail with a timeout at some point. (Maybe internally in the quic package, maybe from our side if it's exposed.)

We had a similar issue way back with TLS/TCP connections because Close() does a write, and if we're closing because the connection is dead that will block forever. Setting a write deadline before close works.

**Comment by imsodin** [comment] 2022-04-12 22:27
That's actually it: Due to all the wrapping in quic conns, the deadline we set on the tls conn before closing is not applied to the underlying udp conn. And it's not as simple as just setting that deadline, as all quic connections from the listener share the underlying udp connection - we don't want to set a (very short) deadline for all quic connections when closing one.  
One option would be to set a long timeout on the listener udp-conn (something in line with the ping timeout in the protocol). However there's no possibility to set a timeout, just deadlines - so we'd have to wrap the udp-conn to override all write methods to extend the deadline on every successful write. Very ugly.

**Comment by calmh** [comment] 2022-04-13 02:58
Yeah... I'm not aware of any reasonable circumstances where an UDP write should block for an appreciable amount of time, really, so to me this feels like something that should happen in the QUIC package prior to each write. If the UDP write is still blocked after a minute or something, it feels safe to say that something bad has happened and that connection is dead...

**Comment by bt90** [comment] 2022-04-16 10:07
> Due to all the wrapping in quic conns

I remember vaguely that it was discussed at some point to abandon the current wrapping/pfilter approach and reimplement it as a handler for non-QUIC packets passed to quic-go.

**Comment by imsodin** [comment] 2022-04-16 11:19
Looking at the quic server code it would be simple to add a write timeout via `net.PacketConn.SetWriteDeadline` in the `sendQueue`, possibly configurable through the `*Config` parameter. @marten-seemann Does that approach seem sensible and if yes, would you welcome such a contribution?

> I remember vaguely that it was discussed at some point to abandon the current wrapping/pfilter approach and reimplement it as a handler for non-QUIC packets passed to quic-go.

I don't remember these or know what it's abouth. However my "wrapping comment" wasn't correct, it plays a role butit isn't really the fundamental issue here. That's the difference between tcp and quic, where in the former we have one tcp conn per "syncthing connection", while for the latter it's a single udp conn with multiplexed "syncthing/quic connections" on top.

**Comment by marten-seemann** [comment] 2022-04-16 11:36
> Looking at the quic server code it would be doable to add a write timeout via net.PacketConn.SetWriteDeadline in the sendQueue, possibly configurable through the *Config parameter. @marten-seemann Does that approach seem sensible and if yes, would you welcome such a contribution?

Not sure I understand how that's supposed to work. It's still the same underlying `net.PacketConn`, so the deadline would apply to all connections. I'd be very worried about the performance impact of setting a write deadline for every packet sent.

I'd like to raise the question again why we're not raising this problem with the Go team. This is a Go bug after all.

**Comment by imsodin** [comment] 2022-04-16 12:13
> Not sure I understand how that's supposed to work. It's still the same underlying net.PacketConn, so the deadline would apply to all connections.

The deadline would indeed apply to all connections from one quic server/`Listener` with it's underlying connection. That seems like a desirable property, as all those connections are affected if the underlying connection is broken/timing out.

> I'd be very worried about the performance impact of setting a write deadline for every packet sent.

That can be done more smartly than setting it on eery write, e.g. by setting a deadline and only extending it some time before it expires.

> I'd like to raise the question again why we're not raising this problem with the Go team. This is a Go bug after all.

I don't understand this: Why is a blocking/hanging udp conn clearly a go bug (as in not an issue with the underlying system outside of go's control)?

**Comment by bt90** [comment] 2022-05-23 09:51
@marten-seemann is the issue related to our problem here?

https://github.com/lucas-clemente/quic-go/issues/3409

**Comment by marten-seemann** [comment] 2022-05-23 10:05
Probably not. https://github.com/lucas-clemente/quic-go/issues/3409 would cause a connection to be dropped, but shouldn't result in a memory leak (unless your code doesn't properly deal with closed connections).

**Comment by calmh** [comment] 2023-03-10 08:07
I'm going to consider this either solved, or need of refreshed troubleshooting if not, as there have been a lot of water under the bridge (new quic-go releases, new Go releases).

**Closed by calmh** 2023-03-10 08:07 UTC
Labels: bug, needs-triage

**Comment by leipert** [comment] 2023-03-11 08:12
Makes sense to me, haven't noticed the problem lately!
