### ISSUE TITLE
All devices shown as not having accepted shared folders

### ISSUE THREAD

**Issue by imsodin** [syncthing/syncthing#8266] opened 2022-04-11 12:06 UTC
The visual indication added in https://github.com/syncthing/syncthing/pull/8201 is active for all of my folders (old long accepted, and newly shared ones). @acolomb Can you repro?

Added skip-changelog, as it's only released as nightlies so far.

**Comment by acolomb** [comment] 2022-04-11 15:50
Are the devices currently disconnected or paused by any chance? If so, see the Caveats headline in the PR description. Guess there was some unfinished business after all. The current default value was suggested like that by @calmh in the forum thread, but I think it is makes more sense to change it and not mark disconnected devices as having unaccepted folders.

If that's not the cause for your issue here, let me investigate when back at my desk tonight.

**Comment by imsodin** [comment] 2022-04-11 16:16
Not just disconnected, literally all of them.

For the general point about indication and disconnected devices: I'd agree with not showing any information by default. It's an auxiliary information, so having a potential false negative on disconnected devices seems less problematic (consuing) than showing folders as not accepted e.g. on a very old folder-device combo.

**Comment by tomasz1986** [comment] 2022-04-11 20:28
I'm testing this right now, and it seems that the wrong status somehow "fixes" itself with time. For instance, right after sharing a folder from Device 1 with Device 2 and accepting it on the latter, the status on Device 1 still said that the folder hadn't been accepted. However, I then left Syncthing running for ~40 minutes, and now there's no "not having accepted" notification anymore, on neither of the two devices.

Obviously, the expected behaviour would be to immediately clear the notification as soon as the other device has accepted sharing the folder.

**Comment by acolomb** [comment] 2022-04-11 20:35
I'm having trouble investigating at all, as the current main branch no longer builds with my installe Go version 1.16.  Haven't found a new deb package yet, as https://launchpad.net/ubuntu/+source/golang-1.17 is not available for 20.04...  Shoosh!

**Comment by acolomb** [comment] 2022-04-11 20:45
I have no good explanation for the delays.  Could imagine that after your 40 minutes, the connection gets replaced and therefore a new ClusterConfig is processed, fixing the previously wrong entry.  But ClusterConfig is also sent when the set of shared folders changes, so it should happen immediately.  I cannot reproduce this on my end.

Anyway, making `remoteValid` the default value fixes the display for paused and disconnected devices in my testing.

**Comment by tomasz1986** [comment] 2022-04-11 21:45
This is what I've been doing.

1. Start two new Syncthing instances.
2. Connect them with each other.
3. Create a new folder on syncthing1, then share it with syncthing2.
4. Accept the folder on syncthing2.

The situation looks like this in the GUI.

![image](https://user-images.githubusercontent.com/5626656/162838622-80834525-0607-4c90-90c4-ee72a0238e22.png)
![image](https://user-images.githubusercontent.com/5626656/162838638-ca427e44-32eb-430b-9589-126f6ac6a0df.png)

The output of `/rest/db/completion` is

```
{
  "accepted": false,
  "completion": 100,
  "globalBytes": 0,
  "globalItems": 0,
  "needBytes": 0,
  "needDeletes": 0,
  "needItems": 0,
  "sequence": 0
}
```

and it's identical on both sides.

**Comment by acolomb** [comment] 2022-04-12 20:47
I suppose this might be the culprit:

    func (c *folderSummaryService) listenForUpdates(ctx context.Context) error {
	    sub := c.evLogger.Subscribe(events.LocalIndexUpdated | events.RemoteIndexUpdated | events.StateChanged | events.RemoteDownloadProgress | events.DeviceConnected | events.FolderWatchStateChanged | events.DownloadProgress)

There is simply no event that triggers this again after receiving a new ClusterConfig from the remote with the folder now included.  Thus the completion is not recalculated and the state won't change in the GUI.  Refreshing will pull the completion for all folders from the endpoint again, thus fixing the display "manually".

@imsodin does that sound like a sensible explanation?  I guess updating completing when the remote ClusterConfig changes would be a good idea anyway.  But maybe I just don't see where it's already done.

**Comment by imsodin** [comment] 2022-04-12 21:53
That sounds plausible, yes. Not sure what the nicest way to fix it is: Adding an event on cluster-config just for this seems too heavy handed, then we might as well go back on the original decision of adding it to completions and create a dedicated event for the remote folder state.

**Comment by calmh** [comment] 2022-04-13 03:38
What's your recommendation for the RC we should have shipped yesterday? I don't want to ship it with this being non-functional and if there are API changes coming. Temporarily revert and then add it in the next RC?

**Comment by acolomb** [comment] 2022-04-13 05:42
For the most part, this will be fixed by #8275 I think.  Let's handle the missing immediate update on ClusterConfig after the RC.  I don't think we need to switch away from the current API again.  I'd rather look for an internal solution that just triggers the summary service in that case.

**Comment by imsodin** [comment] 2022-04-13 16:25
I confirmed it's fixed by https://github.com/syncthing/syncthing/pull/8275

I still think of that change as just a "hot-fix" to get the RC out with acceptable user-facing behaviour, but I don't want to keep that behaviour. I currently see two independent possible options:

1. Make the default for the remote folder state enum something like `unknown`. Add the state enum to the folder completion instead of an `accepted` boolean. We set that to true at the moment, while we don't actually know that it's true, because that results in the right UI display - that's unnecessary/bad coupling of the model/event/api with UI.
2. Add a dedicated event/endpoint for remote folder status, instead of adding it on the folder completion as we do know. This will also immediately propagate the information when available from a received CC.

**Comment by acolomb** [comment] 2022-04-13 20:06
Agreed, it's just an intermediate fix until I had some time to work it out. Not sure when, as I'm currently traveling with family, but I do have a laptop in reach.

Regardless of which option we choose, the fact that FolderCompletion is not resent for folders added in the last ClusterConfig is a bug in itself. Fixing that will help here as well if we stay with the current event.

**Comment by acolomb** [comment] 2022-04-15 11:27
It used to be that a DeviceConnected event was fired for each ClusterConfig message, as they were only sent once and the connection torn down every time.  Now I'm not quite sure how to get that behavior back.  The FolderSummary and FolderCompletion events are a bit confusing, I think we'd need a new event type to cleanly hook it up to the folderSummaryService.  But if that event always triggers a FolderSummary (or maybe just a FolderCompletion for the specific folder?), then it'll be even more confusing for the Event API user why there are at least three events for each ClusterConfig change.

**Comment by calmh** [comment] 2022-04-15 12:48
It seems reasonable that we would have something like a `RemoteFoldersChanged` event for when the other side sends a new cluster config. It does not seem confusing to me that this in turn also results in new FolderSummary and FolderCompletion events.

**Comment by AudriusButkevicius** [comment] 2022-04-15 12:52
I guess they might not always change? I think we might send one that was exactly the same one as before?

**Comment by calmh** [comment] 2022-04-15 14:11
I guess if there's no change we can skip sending the event, if we go to the trouble of figuring that out. (As opposed to just sending the content of the CC, more or less.)

**Closed** 2022-04-22 06:42 UTC
Labels: bug, skip-changelog, ui, needs-triage
