### ISSUE TITLE
TestBlockSize fails on some architectures

### ISSUE THREAD

**Issue by aviau** [syncthing/syncthing#5064] opened 2018-07-11 16:29 UTC
Hello!

I am getting test failures for TestBlockSize on armel, armhf, i386, mips and mipsel.

I am building 0.14.48.

```
--- FAIL: TestBlockSize (0.00s)
	protocol_test.go:381: BlockSize(2147483648), size=16777216, expected 2097152
	protocol_test.go:381: BlockSize(3221225472), size=16777216, expected 2097152
```

[More logs](https://buildd.debian.org/status/package.php?p=syncthing)

Cheers <3

**Comment by calmh** [comment] 2018-07-12 07:46
Duplicate of #4990

**Closed by calmh** 2018-07-12 07:46 UTC
