### ISSUE TITLE
No local discovery on MacOS X

### ISSUE THREAD

**Issue by ineiti** [syncthing/syncthing#1155] opened 2014-12-29 15:26 UTC
Sorry to open that again - I know it's a duplicate, and it has been closed, but the only solution seems to be to reboot the computer, which is lame!

So, if I run syncthing for a second time (perhaps it's third or fourth), with or without sudo, it complains about "No local discovery on MacOSX":

```
# ./syncthing
[monitor] 15:52:56 INFO: Starting syncthing
[YQLUO] 15:52:57 INFO: syncthing v0.10.14 (go1.4 darwin-amd64 default) unknown-user@syncthing-builder 2014-12-29 08:42:17 UTC
[YQLUO] 15:52:57 INFO: My ID: xxx
[YQLUO] 15:52:57 INFO: Starting web GUI on http://127.0.0.1:8080/
[YQLUO] 15:52:58 INFO: Starting UPnP discovery...
[YQLUO] 15:53:04 INFO: UPnP discovery complete (found 0 devices).
[YQLUO] 15:53:04 INFO: Starting local discovery announcements
[YQLUO] 15:53:04 INFO: Local discovery over IPv4 unavailable
[YQLUO] 15:53:04 INFO: Local discovery over IPv6 unavailable
[YQLUO] 15:53:04 WARNING: Local discovery unavailable
[YQLUO] 15:53:04 INFO: Starting global discovery announcements
```

And of course the obligatory netcat:

```
# netcat -vl -u -p 21025
Listen mode failed: Address already in use
```

BUT lsof gives nothing on port 21025:

```
# sudo lsof -i -P | grep 21025
#
```

And, just to drive me crazy, here is netstat:

```
# sudo netstat -nl | grep 21025
Proto Recv-Q Send-Q  Local Address          Foreign Address        (state)    
...
udp46  51660      0  *.21025                *.* 
```

Are there any mac-wizards out there that can tell me which PID I have to kill? Or how to flush the udp-queue? If I read the netstat-output right, there is still something stuck in there on the receiving-end... Can it be *Go* still holds that port? How to reset that?

**Comment by christophberger** [comment] 2015-03-04 22:13
I observe the same issue on my Mac since a while. Today I rebooted and started synchthing, and as soon as syncthing did a restart for the first time (in order to activate a config change I did), local discovery became unavailable. 

When I run nettop, I can see that port 21025 is assigned to a process without a name, only the PID is visible. Alas I failed to look up the PID of syncthing before the restart, but I see no reason to assume that the stale PID is not that of the previous syncthing process. 

I really would love to see this fixed soon. Constantly rebooting is indeed not an option, and switching the firewall of and on does not work for me. 

Even if it is some bug in the OSX firewall that keeps the port open, I haven's seen this issue with any other process besides syncthing, so perhaps some change in the way syncthing handles the port might make the issue go away. I would love to help here but I am neither familiar with the syncthing source nor with network programming, so I would not know where to start...

**Comment by nilsws** [comment] 2015-03-05 04:19
Same issue here. "Local discovery unavailable"

**Comment by nilsws** [comment] 2015-03-05 04:19
And global syncing doesn't seem to work even though the Global Announce status is "OK".

**Comment by AudriusButkevicius** [comment] 2015-03-05 07:53
It needs UPnP if you are behind a router. Make sure the log says that it succeeda.

**Comment by nilsws** [comment] 2015-03-05 10:14
Thanks for the tip. It seems something was wrong with the Syncthing client. Restarting the computer fixed it, it seems.

-- 
Please encrypt your email. 
PGP key at nilsweisensee.com

**Comment by dylancarlson** [comment] 2015-03-26 04:11
Experienced this issue today, and was able to clear it with a reboot.  OSX 10.10.2.  I'm also doing this over VPNs which don't block UPnP.   I start syncthing from command line periodically; I don't leave it running all the time.  I haven't been able to get this to reproduce despite trying.

**Comment by calmh** [comment] 2015-05-07 19:39
(Needs someone able to reproduce this to debug; I can't, and I'm pretty much Mac-only...)

**Comment by jpjp** [comment] 2015-05-07 20:08
Little Snitch?

**Comment by calmh** [comment] 2015-05-07 20:13
Good question. You guys have that installed maybe, or something similar?

**Comment by christophberger** [comment] 2015-05-07 21:49
I had a "stale" 21025 port hanging around since a while. Now I updated syncthing to 0.11.2, rebooted my Mac (to remove the stale port), started syncthing, and did a couple of restarts and stop/start sequences. None of these replicated the issue. Syncthing can always reconnect to the syncthing on the other machine, and no hanging 21025 port appears in nettop. Rather, the latest syncthing instance always gets hold of the 21025 port instantly. Seems that the issue is gone with v0.11.2.

However, I now always see two syncthing processes - is this normal? I cannot remember having seen this in previous tests. This second syncthing instance appears inactive (no network activity, no open ports, no CPU load, no I/O activity) and does not seem to negatively affect the active instance.

**Comment by nilsws** [comment] 2015-05-07 23:30
I use Little Snitch. 

-----Original Message-----

**Comment by AudriusButkevicius** [comment] 2015-05-08 08:41
The 2nd instance is the monitor process, dealing witg restarts, etc.

**Comment by jpjp** [comment] 2015-05-08 12:55
I use LS too and get a similar problem sometimes.

**Comment by calmh** [comment] 2015-05-08 14:07
Would be nice if that was the common denominator.

**Comment by christophberger** [comment] 2015-05-09 19:40
I don't use Little Snitch.

**Comment by christophberger** [comment] 2015-05-09 19:42
And with 0.11.2 running since two days, I am unable to replicate the probem anymore.

**Comment by dylancarlson** [comment] 2015-05-16 03:31
I use LS.  I haven't had the problem in a while but haven't tried to replicate.  I've gotten into the habit of only running syncthing when I need to, and shutting it down.  I had to clean up a bunch of sync conflicts.   I'm on 0.11.3 on all machines currently.

**Comment by Zillode** [comment] 2015-07-31 20:56
@dylancarlson could you try reproducing this? If this is no longer an issue we can close this

**Closed** 2015-11-19 12:49 UTC
