### ISSUE TITLE
Default Folder uses different config than user-created folders

### ISSUE THREAD

**Issue by tomasz1986** [syncthing/syncthing#7033] opened 2020-10-13 06:25 UTC
How to reproduce:

1. Create a new folder in a fresh installation of Syncthing.
2. Compare the configuration of the newly created folder, and the Default Folder.

Default Folder
```
<folder id="default" label="Default Folder" path="" type="sendreceive" rescanIntervalS="3600" fsWatcherEnabled="true" fsWatcherDelayS="10" ignorePerms="false" autoNormalize="true">
		<filesystemType>basic</filesystemType>
		<device id="" introducedBy=""></device>
		<minDiskFree unit="">0</minDiskFree>
		<versioning>
				<cleanupIntervalS>0</cleanupIntervalS>
		</versioning>
		<copiers>0</copiers>
		<pullerMaxPendingKiB>0</pullerMaxPendingKiB>
		<hashers>0</hashers>
		<order>random</order>
		<ignoreDelete>false</ignoreDelete>
		<scanProgressIntervalS>0</scanProgressIntervalS>
		<pullerPauseS>0</pullerPauseS>
		<maxConflicts>-1</maxConflicts>
		<disableSparseFiles>false</disableSparseFiles>
		<disableTempIndexes>false</disableTempIndexes>
		<paused>false</paused>
		<weakHashThresholdPct>25</weakHashThresholdPct>
		<markerName>.stfolder</markerName>
		<copyOwnershipFromParent>false</copyOwnershipFromParent>
		<modTimeWindowS>0</modTimeWindowS>
		<maxConcurrentWrites>2</maxConcurrentWrites>
		<disableFsync>false</disableFsync>
		<blockPullOrder>standard</blockPullOrder>
		<copyRangeMethod>standard</copyRangeMethod>
		<caseSensitiveFS>false</caseSensitiveFS>
		<junctionsAsDirs>false</junctionsAsDirs>
</folder>
```

User-created folder
```
<folder id="test" label="Default Folder" path="" type="sendreceive" rescanIntervalS="3600" fsWatcherEnabled="true" fsWatcherDelayS="10" ignorePerms="false" autoNormalize="true">
		<filesystemType>basic</filesystemType>
		<device id="" introducedBy=""></device>
		<minDiskFree unit="%">1</minDiskFree>
		<versioning>
				<cleanupIntervalS>0</cleanupIntervalS>
		</versioning>
		<copiers>0</copiers>
		<pullerMaxPendingKiB>0</pullerMaxPendingKiB>
		<hashers>0</hashers>
		<order>random</order>
		<ignoreDelete>false</ignoreDelete>
		<scanProgressIntervalS>0</scanProgressIntervalS>
		<pullerPauseS>0</pullerPauseS>
		<maxConflicts>10</maxConflicts>
		<disableSparseFiles>false</disableSparseFiles>
		<disableTempIndexes>false</disableTempIndexes>
		<paused>false</paused>
		<weakHashThresholdPct>25</weakHashThresholdPct>
		<markerName>.stfolder</markerName>
		<copyOwnershipFromParent>false</copyOwnershipFromParent>
		<modTimeWindowS>0</modTimeWindowS>
		<maxConcurrentWrites>0</maxConcurrentWrites>
		<disableFsync>false</disableFsync>
		<blockPullOrder>standard</blockPullOrder>
		<copyRangeMethod>standard</copyRangeMethod>
		<caseSensitiveFS>false</caseSensitiveFS>
		<junctionsAsDirs>false</junctionsAsDirs>
</folder>
```

The differences are:

Default Folder
```
<minDiskFree unit="">0</minDiskFree>
<maxConflicts>-1</maxConflicts>
<maxConcurrentWrites>2</maxConcurrentWrites>
```

User-created folder
```
<minDiskFree unit="%">1</minDiskFree>
<maxConflicts>10</maxConflicts>
<maxConcurrentWrites>0</maxConcurrentWrites>
```

The first question is then, which of the two configs is the correct one? The second question is, is this on purpose, or should these configs rather be identical?

Tested with `main` (`v1.10.1-dev.23.gd828adb6`).

**Comment by calmh** [comment] 2020-10-13 06:46
Similar/duplicate #6086, #6748

**Comment by tomasz1986** [comment] 2020-10-13 07:14
> Similar/duplicate #6086, #6748

Yeah, I should have searched first. Although mine does list all the specific values that differ, to give it some justification.

**Comment by imsodin** [comment] 2020-12-19 18:30
Closing as duplicate of https://github.com/syncthing/syncthing/issues/6086, as it's the same root cause.

**Closed by imsodin** 2020-12-19 18:30 UTC
Labels: bug, needs-triage
