### ISSUE TITLE
Move files from source to destination

### ISSUE THREAD

**Issue by Moosbueffel** [syncthing/syncthing#9690] opened 2024-09-08 13:25 UTC
### Feature description

syncthing synchronize a dir also in one direction. I need to delete the files at the source dir after sync. In other words: moving the files to a different location.

### Problem or use case

I scan documents with my scanner in a special directory at my PC. But I need this files than at my paperless - server. So this is a move operation to the server and not a syncthing.

### Alternatives or workarounds

Alternative it would help, if I can call a script to delete the files after synchronisation.

**Comment by tomasz1986** [comment] 2024-09-08 13:35
Duplicate of https://github.com/syncthing/syncthing/issues/6521.

This is not planned, and the developers explained why it is so in the linked issue.

**Closed by tomasz1986** 2024-09-08 13:35 UTC
Labels: enhancement, frozen-due-to-age, needs-triage
