### ISSUE TITLE
Reversed "Insecure Admin Access" on Windows 10 64?

### ISSUE THREAD

**Issue by frlu05** [syncthing/syncthing#6064] opened 2019-10-06 15:08 UTC
Syncthing presents warning "The Syncthing admin interface is configured to allow remote access without a password. This can easily give hackers access to read and change any files on your computer. Please set a GUI Authentication User and Password in the Settings dialog."

However, the "Insecure Admin Access" is de-selected in settings and the GUI adress is set to "127.0.0.1:8384". When selecting (i.e. activating) the "Insecure Admin Access") and hitting "save", the warning disappears.

Seams to be "reversed" behavior here?

I'm running Syncthing with SyncTrayzor.

**Comment by calmh** [comment] 2019-10-06 15:56
Duplicate of #6049 

Resolved in next release

**Closed by calmh** 2019-10-06 15:56 UTC
