### ISSUE TITLE
Feature request: file/directory search in database (REST API)

### ISSUE THREAD

**Issue by andreymal** [syncthing/syncthing#5845] opened 2019-07-10 13:43 UTC
I have a lot of files and folders, and I use `.stignore` for partial synchronization. Sometimes I want to add some exceptions to `.stignore` to download more files, but it's hard to determine what exactly should I add: I want to know exact path to file or folder that I want to exclude. I know part of the name of the desired file, and I want to find this file.

It would be nice to have an endpoint like `/rest/db/search?folder=ID&pattern=NAME` which returns a list of available files and folders that contain this pattern in their names.

Currently I can emulate it using `/rest/db/browse?folder=ID` and recursively traversing this tree, but it's probably too expensive. I hope that server-side implementation can be more efficient (for example, the server can build a search index).

Note that I can't use a local file manager to search (e.g. Windows Explorer), because most files are ignored by `.stignore` and are missing.

**Comment by AudriusButkevicius** [comment] 2019-07-10 16:55
This is effectively a duplicate of "improved ignores" megaticket. 
Sure, rest api search is a bandaid instead of that, but it's not generally useful for anyone other than you. The proper fix for this is to have a treeview with all folders visible.

**Closed by AudriusButkevicius** 2019-07-10 16:55 UTC

**Comment by andreymal** [comment] 2019-07-10 16:58
@AudriusButkevicius the tree for millions of files will be too big, too slow and unusable.

>not generally useful for anyone other than you

Did you ask other users?

**Comment by AudriusButkevicius** [comment] 2019-07-10 17:18
The tree would be loaded on demand as you browse. It would not however list files, as no other desktop sync solution (dropbox, onedrive, google drive et al) allow (un)ignoring individual files (or even seeing them).

I have not asked, but people usually come with feature requests to us, oppose vica versa. This is the first such request, so perhaps you are onto something big.

Most users do not use the rest api directly, so I am fairly positive this will not be a smash hit.

**Comment by andreymal** [comment] 2019-07-10 17:32
@AudriusButkevicius 

>The tree would be loaded on demand as you browse.

I don't want to browse the tree, I want to type the name of the file and see exactly one file, not the tree. Similar to the search in Windows Explorer. It's too hard to search the file using the tree.

Note that Dropbox and Google Drive have the search feature. Why should Syncthing be worse than them?

>no other desktop sync solution ... allow (un)ignoring individual files

This is your chance to be the first! The fact that other solutions are bad does not mean that Syncthing should be bad too. The partial synchronization is very important feature for big folders.

But actually you're lying. Seafile allows (un)ignoring individual files (but Seafile is too hard for administration, so I'm trying to migrate to Syncthing)

>Most users do not use the rest api directly

API existense gives a chance to add the search to GUI. Do you hate other programmers (including me)?

**Comment by AudriusButkevicius** [comment] 2019-07-10 17:53
I don't disagree search is a useful feature. I am saying that this needs thinking through of how we do things (folders vs files, load everything ahead oppose to lazy load, how does that influence how we do search, what api responses look like etc).

I am oppose to some random implementatiom, and I think the discussion should be on the mega ticket so that the implementation serves a general purpose, as in be a building when implementing the tree.

Once you add some random endpoint, it's very hard to remove it.

Google backup and sync does not support file ignores or search. Google drive does but that's not a frontend for your filesystem, its a frontend for theirs - which is massive, distributed indexed system.

We happen to run on shitty RPi Zeros with a 10TB NAS plugged at the USB port, with users complaining that this magical search does not work.

We are happy to accept PRs if you're a developer that needs this so desperately that he is willing to spend time on this, but again, this should probably be discussed on the megaticket to iron out the details.

**Comment by andreymal** [comment] 2019-07-10 18:00
@AudriusButkevicius 

>I think the discussion should be on the mega ticket

The "ignores" is just an example where the search can be useful, but there are many other things where the search can be useful, even without "ignores". That's why I made this separate issue.

>I am oppose to some random implementatiom

Ok, this is a really good point. I do not insist that the search be implemented exactly as I suggested :) But I suggest this endpoint because it is not directly related to the "ignores" megaticket, this is just an example.

**Comment by AudriusButkevicius** [comment] 2019-07-10 18:02
I don't think we should have two searches, one that is generally useful, the other one that is useful for ignores, hence this needs ironing out. After ironing out this needs some developer that cares about this to implement it (insert uncle sam image here).

**Comment by andreymal** [comment] 2019-07-10 18:21
@AudriusButkevicius 

>I don't think we should have two searches

That's why I suggest one single endpoint that will be useful for all cases :D

**Comment by AudriusButkevicius** [comment] 2019-07-10 18:23
We don't know the cases, as nothing has been decided on how the new ignores get implemented.

**Comment by andreymal** [comment] 2019-07-10 18:28
@AudriusButkevicius keeping the focus on "ignores" is the best way to make a bad search implementation that will be useful only with "ignores" and nothing else. It is necessary to discuss all possible cases, not only "ignores". This issue would be a good place to discuss it :)

**Comment by calmh** [comment] 2019-07-11 09:14
> It would be nice to have an endpoint like /rest/db/search?folder=ID&pattern=NAME which returns a list of available files and folders that contain this pattern in their names.

Why? That is, what is the purpose of this endpoint? I don't see that explained in this discussion.

**Comment by andreymal** [comment] 2019-07-11 10:02
@calmh 

>what is the purpose of this endpoint?

To have the search. Have you ever used file search in your life? Every file manager has this feature.

I am very surprised that people think that the file search feature is bad. I thought it was an important thing in the life of any PC user.

![](https://i.stack.imgur.com/GEXm6.png)

**Comment by calmh** [comment] 2019-07-11 10:12
Syncthing, however, is not a file manager. The file manager exists, and you can do searches there. However I got the point about the purpose being to find announced but ignored files.

**Comment by andreymal** [comment] 2019-07-11 10:14
@calmh please read the firse sentence again:

>Note that I can't use a local file manager to search (e.g. Windows Explorer), because most files are ignored by `.stignore` and are missing.

I can't use existing file managers for file search, because my local Syncthing instance ignores some files. It's important to be able to search in the entrie database.

**Comment by andreymal** [comment] 2019-07-11 10:22
@calmh Syncthing is actually a file manager, because it has the `/rest/db/browse` endpoint. If you think Syncthing is not a file manager, you should remove this endpoint. The `/rest/db/search` endpoint I proposed is just a useful addition to the `/rest/db/browse` endpoint.

**Comment by imsodin** [comment] 2019-07-11 10:33
I don't think it's productive to discuss what Syncthing is or isn't, especially not arguing with certain endpoints (not) existing - calling that circumstantial is putting it mildly.

I do remember another request to list ignored files. This request is essentially just a parameter on top of that which allows filtering that list with ignore patterns. The discussion around that previous request was along the lines of what file would be listed, as there's several possible categories:
 - Ignored files known by Syncthing (i.e. in db)
 - Ignored files on disk
 - All kinds of subsets of the two (ignored on disk but not in db, ignored in db (not) existing on disk)

I believe the case was to delete all files that are ignored but exist on disk.

It wasn't developed for the same reason as argued here: It's a niche problem and nobody felt like thinking it through and doing it. I personally think that would be useful functionality, but also very niche functionality. And I think this discussion should go to the forum. Once it's established what exactly the requested functionality is and there's agreement that it wouldn't be harmful to include it a ticket with that specific feature request can be opened. Until then this is noise that shouldn't be on the issue tracker.

**Comment by AudriusButkevicius** [comment] 2019-07-11 11:21
I do agree we should remove /browse however
