### ISSUE TITLE
Make number of items in "Recent Changes" configurable

### ISSUE THREAD

**Issue by uok** [syncthing/syncthing#6851] opened 2020-07-24 09:35 UTC
I have many folders, but the list of "Recent Changes" only shows the last 25 changes from all of them.
It would be great to have an advanced setting where user can change that.
Thanks!

**Comment by imsodin** [comment] 2020-07-24 09:48
That's a duplicate of https://github.com/syncthing/syncthing/issues/5168 (though that's not very well named, will adjust).

Also how did you manage to open an issue without the default flags? o.O

**Closed by imsodin** 2020-07-24 09:48 UTC

**Comment by tomasz1986** [comment] 2020-07-29 08:07
> Also how did you manage to open an issue without the default flags? o.O

Just an observation, but it is possible to delete the default labels by clicking on the cog icon next to "Labels".

**Comment by calmh** [comment] 2020-07-29 08:09
(uok and tomasz1986 can do that as members of the org with permissions to manage issues. Other users cannot, I think.)
