### ISSUE TITLE
Multithreaded Scanning of Directories

### ISSUE THREAD

**Issue by dmriding** [syncthing/syncthing#9754] opened 2024-10-04 09:31 UTC
### Feature description

It would be amazing if we could add multithreaded scanning specifically for large directories. This would eliminate the need to create multiple folders and speed up scan times. Ideally it would be best to allow the end user the option to set the maximum amount of parallel operations per "folder" in syncthing web UI.

### Problem or use case

If you have a very large directory the scan takes a very long time as it is in my understanding a single threaded operation, multithreading can significantly reduce the scan time and increase performance.

### Alternatives or workarounds

For very large directories my current workaround for this is to create many "folders" to scan instead of just the scanning the root of the directory. This can be difficult to maintain and keep up with also it creates a lot more work to get the same result. Another alternative I have used would be freefilesync or rclone and the scan times are significantly reduced by multithreading. I would absolutely love to be able to do the same in syncthing.

**Comment by aminvakil** [comment] 2024-10-24 07:47
Possible duplicate of https://github.com/syncthing/syncthing/issues/8418 ?

**Comment by imsodin** [comment] 2024-10-29 22:17
Indeed duplicate of https://github.com/syncthing/syncthing/issues/8418

**Closed by imsodin** 2024-10-29 22:17 UTC
Labels: enhancement, needs-triage
