### ISSUE TITLE
Adding new folder: Autocompleted path not applied

### ISSUE THREAD

**Issue by dekelund** [syncthing/syncthing#2050] opened 2015-07-10 21:40 UTC
# Scenario
I was going to add a folder. First I wrote a folder path in the text field, but never finished the configuration. 

Later I reopened the modal window, Safari autocompleted my path based on previous value. I was satisfied, stopped writing and applied the settings. But it was not obvious that only characters written by hand was applied (characters written by Safari was not included in the javascript variable).

This is dangerous, it might share files not intended to be shared. This is a common bug shared by other projects, I have seen it before in Safari-AngularJS solutions.

# Expected behaviour
Directories provided by autocompleted path should have been used instead of parent or grandparent.

# Revisions and vendoring
Mac OS X Yosmite, syncthing v0.11.13 and Safari v8.0.6

# Screenshots
<img width="885" alt="screen shot 2015-07-10 at 23 24 55" src="https://cloud.githubusercontent.com/assets/833396/8629546/79ef7818-275c-11e5-9c08-74bd370941d0.png">
<img width="550" alt="screen shot 2015-07-10 at 23 25 21" src="https://cloud.githubusercontent.com/assets/833396/8629547/7a15e642-275c-11e5-9218-b388b3362cdf.png">

# Poor-mans-solution
If it's not possible to prohibit, then maybe a alert window should pop-up verifying the most dangerous values before it's applied to the rest of the system.

**Comment by canton7** [comment] 2015-07-12 12:03
My understanding is that the web browser won't actually set the text of the textbox until you confirm the autocompletion, so there's no way for javascript, or anything else, to know what value the web browser is suggesting.

How would you define a "dangerous value"?

**Comment by AudriusButkevicius** [comment] 2015-07-12 12:06
I don't think we can do anything here.

**Comment by dekelund** [comment] 2015-07-12 18:01
canton7: I more or less agree, except that for me it looks like the text value has been set. I not sure if it's the same thing if I'm clicking on the right side after autocompletion or not, since I'm not on a Mac for the moment.

But as I said, I thought it was part of the value, it really looks like it. But I'm also aware of the problem, that it's a integration thing between JS, angularjs and Safari.

A dangerous scenario would be that you write /Users/<username>/ and it adds "teamfiles" in the end. You accept that value, since you want to share /Users/<username>/teamfiles as shared folder with your coworkers. But in reality all team files are stored in your home-directory, and worse all your private files, such as .ssh .gnupg etc are shared with your coworkers.

**Comment by dekelund** [comment] 2015-07-12 18:02
But my "poor-mans-solution" would at least give you a head up before enabling the wrong path.

**Comment by AudriusButkevicius** [comment] 2015-07-12 18:06
I don't understand your poor mans solution.

**Comment by dekelund** [comment] 2015-07-12 18:22
With "If it's not possible to prohibit" I'm trying to say, if you are not able to fix the bug, then at least you should require a confirmation via a popup window. Nothing magic about that. Just a window listing the values you just entered.

**Comment by dekelund** [comment] 2015-07-12 18:29
Ok, now I have tried it once more. This is the steps:

1) Start writing the path
2) Safari autocompletes
3) Click on the end of the text field, now it has a new value
4) Add the new folder
5) Look at result, part of autocompletion was not part of the value stored
6) Now you share all your private files

This is of course a safari and angularjs integration, but still a serious problem. So when you finish your settings you should receive a confirmation window stating what will be set or something. At least that's what I would prefer.

<img width="546" alt="get_autocomplete_result" src="https://cloud.githubusercontent.com/assets/833396/8639258/4c825dae-28d4-11e5-97ad-22fa03274328.png">
<img width="889" alt="get_autocomplete_confirm_path" src="https://cloud.githubusercontent.com/assets/833396/8639259/4cab016e-28d4-11e5-9d03-7e9fda846c13.png">
<img width="888" alt="get_autocomplete" src="https://cloud.githubusercontent.com/assets/833396/8639260/4cac3eb2-28d4-11e5-88f7-3eb07d530303.png">

**Comment by canton7** [comment] 2015-07-12 19:08
You still haven't defined what a "dangerous value" is...

**Comment by dekelund** [comment] 2015-07-12 19:16
Sorry, with "dangerous value" I'm referring to settings that might "hurt" you if applied with incorrect value. For instance, if you add another Folder Path than intended, then you will share files from another path. As written before, with current behaviour in Safari you risk sharing private keys (SSH, GPG, bitcoin etc). I'm not sure which values that might impact on the security, but if it's not possible to list every value (for instance a modal window might have a limited width and height) then the most important and dangerous settings should be listed and confirmed.

**Comment by AudriusButkevicius** [comment] 2015-07-12 19:29
So to me this makes no sense. I don't want to add a prompt just for people who use safari and don't check the values before saving the form. The rest, who actually use a different browser, and who actually check the values will be annoyed.

After adding a folder you have to restart syncthing anyway, hence that should be enough time for you to notice it, furthermore it is not a destructive action, hence I don't see why we should double prompt people

**Comment by canton7** [comment] 2015-07-12 19:39
I suspect the number of users deliberately sharing their home directory will be far greater than the number of users accidentally doing so because they're not using their browser correctly.

**Comment by dekelund** [comment] 2015-07-12 19:50
Ok it's up to you, I just want to prohibit other users from sharing files unintentional, but just to clarify some things:

 "don't check the values before saving the form"  this is not the case. The text field contains the correct path, as shown in the screenshots earlier, it's just that the java script library does not make use of it. So it doesn't matter if you check the value or not, there are no indication what so ever that you have provided an incorrect path.

"After adding a folder you have to restart syncthing anyway, hence that should be enough time for you to notice it" yes that's true, but it requires the user to open the folder-settings once more, the path are not visible otherwise. Most people probably won't open the folders-settings once more, since it was "correct" path couple of seconds ago, or at least they thought so.

**Comment by dekelund** [comment] 2015-07-12 19:56
canton7: "because they're not using their browser correctly." so how should I then use my browser? I really appreciate the support, but it feels like you are misunderstanding me. If you make use of a auto completed path, then it will be incorrect value in the java script variable. This is not a syncthing problem from the beginning, but it shows up as a bug in that interface. Therefor I'm just suggesting that it might be good to confirm the values, and doing so by listing the variable values.

**Comment by canton7** [comment] 2015-07-12 20:01
> it's just that the java script library does not make use of it

Incorrect - the browser hasn't yet set that value in the form, so there's no way of determining it. 

> Therefor I'm just suggesting that it might be good to confirm the values, and doing so by listing the variable values.

What's a variable value here, and how is it listed?

**Comment by canton7** [comment] 2015-07-12 20:10
I suspect the "real" solution here is to provide a tree-style folder picker, which avoids the issue entirely. @AudriusButkevicius didn't you have something like that in the works? Jakob mentioned something in relation to canton7/SyncTrayzor#78

**Comment by dekelund** [comment] 2015-07-12 20:14
canton7: I just recommend that you list variables such as currentFolder.path

"the browser hasn't yet set that value in the form"
Screenshots attached showing value in the text element, printed in console.
<img width="964" alt="screen shot 2015-07-12 at 22 09 37" src="https://cloud.githubusercontent.com/assets/833396/8639759/4c56f47a-28e3-11e5-8b1e-37e966f35449.png">

**Comment by canton7** [comment] 2015-07-12 20:24
Yes, well, your screenshot shows that you've accepted whatever path your browser suggested, so of course that's available. I assumed you were referring to the value your browser was suggesting. If you were referring to the value you typed in, then the sentence "it's just that the java script library does not make use of it" would be incorrect: the value is saved to Syncthing config, so it must be used :smile:

**Comment by dekelund** [comment] 2015-07-12 20:31
I have always been referring to the value the browser was suggesting, and in all cases I have accepted the value suggested by the browser. But it's not used by syncthing, and I'm pretty sure it's an angular thing (I have had the same problem within another application that I have developed for SMS messages).

And luckily me, I have taken a screenshot of the result from above example :) as you saw before it contains correct path in text field with ID #folderPath. But as you see in my newly attached screenshots the value does not match when applied:
<img width="476" alt="screen shot 2015-07-12 at 22 10 15" src="https://cloud.githubusercontent.com/assets/833396/8639849/ba19aa28-28e5-11e5-9ab3-5777c96f3094.png">

**Comment by AudriusButkevicius** [comment] 2015-07-12 20:48
I feel that this deserves a bug on angular and not syncthing.

**Comment by canton7** [comment] 2015-07-12 20:50
I'm confused. Before, you were talking about paths which Safari had suggested but which you hadn't confirmed, as shown in your first two screenshots (with the blue area of text selected). Now you're talking paths which you have inputted (no area is highlighted in blue), whose value you can read using the javascript console, but whose values aren't saved to Syncthing's configuration when you hit 'Save'?

**Comment by dekelund** [comment] 2015-07-12 21:01
canton7: Sorry if I'm making you confused. It's values that has been suggested by Safari, and it's blue till I change text field, then it's not blue anymore. No they are not saved, but I got it working one time couple of minutes ago. But I have recorded a video of the problem, just to make it easy to understand: https://www.dropbox.com/s/ba46222sem4fnup/bug_path_syncthing.mov?dl=0

AudriusButkevicius: Yea they should also have a bug-report. As I have stated, this is a bug in the angular-safari combination. But since it might impact syncthing users it might be a good thing to give a feedback to users when they have added a new folder or something. I'm not blaming the syncthing code in this issue, I'm just stating out that it's a bug that might share users files unintentionally and that's not good.

**Comment by uok** [comment] 2015-07-12 21:27
I don't speak angular, but maybe this is related https://github.com/angular/angular.js/issues/1460 and this may provide a fix http://victorblog.com/2014/01/12/fixing-autocomplete-autofill-on-angularjs-form-submit/

**Comment by dekelund** [comment] 2015-07-12 21:32
uok: I agree, probably the same bug

**Comment by canton7** [comment] 2015-07-13 07:06
Right! I hadn't realised that you'd accepted the auto-suggested text (none of your earlier screenshots implied that you had). I'm on board now :smile: 

Agreed, this is a frontend bug that needs fixing.

**Comment by AudriusButkevicius** [comment] 2015-07-13 07:49
I will reopenit for visibility, though it's safari which needs to sort it's shit out, don't feel like adding per-browser hacks on top of per-os hacks.

**Comment by canton7** [comment] 2015-07-13 09:37
A web frontend without per-browser hacks? That's the utopia, but we're not there yet...

**Comment by calmh** [comment] 2015-07-13 11:02
https://github.com/angular/angular.js/issues/1460 is a better summary. This should probably be handled somehow, even given that it's a Safari bug...

**Comment by lkwg82** [comment] 2016-05-04 21:38
@dekelund Would mind to retest it with the latest version? (Just to verify it is still there. It has been almost a year since this bug was reported.)

**Comment by calmh** [comment] 2016-09-03 09:09
Closed as old and out of our control

**Closed** 2016-09-03 09:08 UTC
Labels: bug
