### ISSUE TITLE
sparse files result in sync-conflict

### ISSUE THREAD

**Issue by martin-rueegg** [syncthing/syncthing#2823] opened 2016-03-07 12:35 UTC
#### Version Information
Syncthing Version: v0.12.19 (apt package)
OS Version: Ubuntu 14.04 (both devices)
FS device A: zfs
FS device B: ext4
```
# syncthing -version
syncthing v0.12.19 "Beryllium Bedbug" (go1.5.3 linux-amd64) unknown-user@build2.syncthing.net 2016-02-14 19:26:33 UTC
```

### What happened

after syncthing'ing one folder from A to B, on B I found about 76 sync-conflicts, which are all zero-filled (sparse) files, and 1 real conflict.

### What I would have expected
those should not have been created. :-)

### What I did
1. I have two devices using the same version of syncthing.
1. I've added one folder on device A and waited for it to be completely scanned (189497 items, ~156 GiB)
1. I shared that folder with device B
1. On device B I accepted the share, 
  1. pointing to an existing but empty folder
  1. that included an .stignore file
1. Sync is never really complete
  1. On A: Out of Sync (Out of Sync Items: 112 items, ~19.5 MiB, which all match the local .stignore)
  1. On B:  Syncing (35%) (Out of Sync Items: 25141 items, ~101 GiB; probably also matching the local .stignore)

### Suggested solution
if a conflict is detected, and one file is a zero-only file with the same length of the conflicting file, i guess the zero-file can safely be deleted, as there is no information stored in it.

### Maybe related?
- #2584 Many Sync conflicts are generated, while the file is modified on only one Client
- #2619 Should not create sync-conflict file if an identical sync-conflict file already exists
- #1263 Empty files left behind

### Workaround (cleanup)

i used the following scripts to find the files:

##### `zero_file_detect.sh`
```bash
#!/usr/bin/env bash

if [ -z "$1" ]; then
        echo "x missing argument"
        exit 3
fi

file=
found=0
for file in "$@";
do
        if [ ! -f "$file" ]; then
                echo "- $file"
                ((found|=2))
        fi


        if [ -n "$(tr -d '\0000' < "$file" | head -c 1)" ]; then
                echo "1 $file"
                ((found|=1))
        else
                echo "0 $file"
        fi
done
exit $found
```

then I run
`find . -name \*.sync-conflict-\* -exec ./zero_file_detect.sh {} \; | grep -E "^0 "`
to detect the files.

or to count:
```bash
# find . -name \*.sync-conflict-\* -exec ./zero_file_detect.sh {} \; | cut -d" " -f1 | sort -n | uniq -c
     76 0
      1 1
```

in order to clean them out, i created an other script:
##### `zero_file_delete.sh`
```bash
#!/usr/bin/env bash

if [ -z "$1" ]; then
        echo "e missing argument"
        exit 3
fi

file=
found=0
for file in "$@";
do
        if [ ! -f "$file" ]; then
                echo "- $file"
                ((found|=2))
        fi

        e=$(./zero_file_detect.sh "$file")

        if [[ $? == 0 ]]; then
                if rm "$file"; then
                        echo "x $file"
                else
                        echo "e $file"
                        ((found|=1))
                fi
        else
                echo $e
        fi
done
exit $found
```

and run a clean up using
```bash
# find . -name \*.sync-conflict-\* -exec ./zero_file_delete.sh {} \; | cut -d" " -f1 | sort -n | uniq -c
     76 x
      1 1
```

**Comment by calmh** [comment] 2016-03-07 13:00
Hmm. Were the sparse files there to begin with, or did syncthing create them and then cause a conflict on the next pass? This is a great bug report, but I'm not fully following that part.

**Comment by martin-rueegg** [comment] 2016-03-07 13:23
well, I have already deleted the files, but from the zfs-snapshot I checked the date of the *.sync-conflict-* files: but they are the same as there original counterpart:
```
# ls -ln ./.svn/pristine/9f/9f4dd0fdc5d15a45feb01b181afd9165f59973c3.*
-rw-rw---- 1 1574 1009 15523 Jun 19  2014 ./.svn/pristine/9f/9f4dd0fdc5d15a45feb01b181afd9165f59973c3.svn-base
-rw-rw---- 1 1574 1009 15523 Jun 19  2014 ./.svn/pristine/9f/9f4dd0fdc5d15a45feb01b181afd9165f59973c3.sync-conflict-20160306-171604.svn-base
```

i have no reason the expect that those sparse files where already there before i installed syncthing. in fact, when i go back in time (in the snapshots) they where not there.

however i did previously sync that folder with the already-in-sych folder on B before. but since i did not trust the status of the sync, i wanted to do a clean synch. i removed the folder configurations on both sides, re-added it on A and then synch'ed it to B to a vanilla directory.

now it could have been the case, that the where created on A during the first synch episode. however, checking out the snapshots, the conflict files first appeared at 2016-03-06_180000, which was only on the first synch episode, as described here in this bug report.

**so the simple answer to your question:** no, the files have not been there when i started with step 2 of the above procedure. they must have been created during the sync. however I can't tell on which side originally.

**Comment by calmh** [comment] 2016-03-10 15:32
I'm not following how to reproduce this. :/

**Comment by martin-rueegg** [comment] 2016-03-10 21:05
@calmh, i'm not sure, if it is reproducable. but i had two vanilla installations, then

1. added one folder on device A 
1. waited for it to be completely scanned (189497 items, ~156 GiB)
1. I shared that folder with device B
1. On device B I accepted the share,
 1.    pointing to an existing folder
 1.  that  _only_ included an .stignore file

that's basically all i did. it took of course some hours to synchronise. and i also played with adding other folders or an additional device. as such, the service has restarted and re-connected meanwhile several times.

i'm sorry to not be able to deliver better information. but please don't hesitate to ask if you need to know something more specific. - maybe it's a one-time issue. it didn't happen any more ever since. so for me it is not relevant at the moment.

@AudriusButkevicius, no (see version info in my initial post):
> FS device A: zfs
> FS device B: ext4

thanks!

**Comment by martin-rueegg** [comment] 2016-03-10 21:16
well, yes, everything can be mounted over the network. but i would have stated that, of course. :-)

it is all local to each machine. all files and directories owned by the user under which syncthing is running.

**Comment by martin-rueegg** [comment] 2016-03-15 00:08
ok, now it happend again.

#### before i started

- i had a paird folder `arbeiten`, which was basically in sync, as much they can be due to the exclusion list. the logfile however is spammed with messages (see below)
- the folder with the pictures i was going to rename in this process, however, was not affected by such a message or by any exclusion pattern.
- initially, there where two objects in the root of the synch'ed folder:
  - Folder `My Pictures`, containing 
     - 523 directories
     - 30415 files
     - 2 symlinks
     - 21 GB in total
   - Symlink `Pictures -> My Pictures`
   - (there are other files and folders too)

#### what i wanted
- "switch" Folder vs. Symlink: Pictures <-> My Pictures

#### what i did
1. while on both hosts the syncthing service was running and no connection paused ...
1. on `jackal` i issued the following command:<br>`@jackal# rm Pictures && mv My\ Pictures Pictures && ln -s Pictures My\ Pictures`
1. shortly after that, syncthing on `tiger` started to be very active, and it showed that it was copying the files using local copies: obviously 
  - it has locally removed the symlink `Pictures -> My Pictures`
  - created the folder `Pictures` in its place
  - started copying the files at the new location `Pictures` obviously using the local-copy-shortcut from the still existing `My Pictures` folder.
1. i stopped the service on `tiger`
  - waited it for being terminated and
  - issued the following command:<br>`@tiger# rm -r Pictures && mv My\ Pictures Pictures && ln -s Pictures My\ Pictures`
    - as such i removed the partly replicated Folder (667MB)
    - moved `My Pictures -> Pictures` and
    - recreated the symlink to point in the other direction.
  - i re-started `syncthing`, but realised, that i forgot to set the `-paused option` (16:24:15 )
  - i stopped `syncthing again` with s SIGTERM (16:24:27)
  - i re-started `syncthing -paused` in order to give it time to rescan the changes. (16:24:48)
  - i restarted `SIGTERM  && syncthing -paused` again for whatever reason (16:25:27 - 16:28:19)
  - after scan was reported successful, i un-paused the connection to `jackal`
  - metadata was exchanged, but hardly an other data (approx 10-20 MB in total per direction)


#### Result
##### `jackal`
(note creation time of sync-conflict: **17:09**! thus it must have been replicated later on, but originally be created on tiger, as there the ctime of both files are **17:00**):
```
# mtime
@jackal# ls -nlc 20110728_160508\ 2011-07-28_14-05-09.*
-rwxr----- 1 1574 1021 171980 Mar 14 17:00 20110728_160508 2011-07-28_14-05-09.jpg
-rwxr----- 1 1574 1021 171980 Mar 14 17:09 20110728_160508 2011-07-28_14-05-09.sync-conflict-20160314-170005.jpg

# ctime
@jackal# ls -nl 20110728_160508\ 2011-07-28_14-05-09.*
-rwxr----- 1 1574 1021 171980 Jul 28  2011 20110728_160508 2011-07-28_14-05-09.jpg
-rwxr----- 1 1574 1021 171980 Jul 28  2011 20110728_160508 2011-07-28_14-05-09.sync-conflict-20160314-170005.jpg

# zero-sparse-file check
@jackal# /store/data/arbeiten/system/batch/zero_file_detect.sh 20110728_160508\ 2011-07-28_14-05-09.*
1 20110728_160508 2011-07-28_14-05-09.jpg
0 20110728_160508 2011-07-28_14-05-09.sync-conflict-20160314-170005.jpg

# interestingly, all other files in this directory have ctime 20:21
@jackal# ls -lac --time-style=long-iso * | cut -c32-47  | sort -n | uniq -c
    893 2016-03-04 20:21
      1 2016-03-14 17:00
      1 2016-03-14 17:09

# and on the entire moved folder
@jackal:/Pictures# find . -type f -exec ls -lanc --time-style=long-iso {} \; | cut -d" " -f 6,7 | sort -n | uniq -c
   5515 2016-03-04 20:17
  25204 2016-03-04 20:21
      1 2016-03-06 16:44
      5 2016-03-06 17:13
      2 2016-03-06 17:14
      1 2016-03-06 17:16
      3 2016-03-06 17:17
      1 2016-03-06 17:18
      3 2016-03-06 17:19
      3 2016-03-06 17:20
      1 2016-03-06 17:21
      2 2016-03-06 17:23
      6 2016-03-06 17:25
      2 2016-03-06 17:26
      1 2016-03-06 17:28
      2 2016-03-06 17:29
      1 2016-03-09 20:02
      7 2016-03-14 16:58
     11 2016-03-14 16:59
     20 2016-03-14 17:00
     38 2016-03-14 17:09

```
<br>
##### `tiger`
```
# mtime
@tiger# ls -nlc 20110728_160508\ 2011-07-28_14-05-09.*
-rwxr----- 1 1574 1009 171980 Mär 14 17:00 20110728_160508 2011-07-28_14-05-09.jpg
-rwxr----- 1 1574 1021 171980 Mär 14 17:00 20110728_160508 2011-07-28_14-05-09.sync-conflict-20160314-170005.jpg

# ctime
@tiger# ls -nl 20110728_160508\ 2011-07-28_14-05-09.*
-rwxr----- 1 1574 1009 171980 Jul 28  2011 20110728_160508 2011-07-28_14-05-09.jpg
-rwxr----- 1 1574 1021 171980 Jul 28  2011 20110728_160508 2011-07-28_14-05-09.sync-conflict-20160314-170005.jpg

# zero-sparse-file check
@tiger# ./zero_file_detect.sh 20110728_160508\ 2011-07-28_14-05-09.*
1 20110728_160508 2011-07-28_14-05-09.jpg
0 20110728_160508 2011-07-28_14-05-09.sync-conflict-20160314-170005.jpg

#ctimes in directory
@tiger# ls -lac --time-style=long-iso * | cut -c36-50  | sort -n | uniq -c
     54 016-03-06 20:27
    251 016-03-14 16:58
    460 016-03-14 16:59
    130 016-03-14 17:00

# ctime comparison to all other files
@tiger:/Pictures# find . -type f -exec ls -lanc --time-style=long-iso {} \; | cut -d" " -f 6,7 | sort -n | uniq -c
      1 2016-03-06 00:58
      1 2016-03-06 01:07
      1 2016-03-06 01:16
      1 2016-03-06 01:17
      1 2016-03-06 01:23
      1 2016-03-06 01:30
      1 2016-03-06 01:31
      1 2016-03-06 16:16
      2 2016-03-06 17:15
      3 2016-03-06 17:16
      1 2016-03-06 17:17
      1 2016-03-06 17:18
      2 2016-03-06 17:19
      3 2016-03-06 17:20
      1 2016-03-06 17:21
      3 2016-03-06 17:22
      2 2016-03-06 17:23
      2 2016-03-06 17:26
      1 2016-03-06 17:28
      1 2016-03-06 17:29
      1 2016-03-06 17:30
   1190 2016-03-06 20:27
   7843 2016-03-14 16:58
  17156 2016-03-14 16:59
   4195 2016-03-14 17:00

```
so obviously, you modify the ctime according to what? last synch-state? whatever ...

#### Logs

##### `jackal`
```
[YYYYY] 14:49:33 INFO: Invalid IGD response: invalid device UUID UUID-one-char-too-short (continuing anyway)
[YYYYY] 15:19:43 INFO: Invalid IGD response: invalid device UUID UUID-one-char-too-short (continuing anyway)
[YYYYY] 15:19:43 INFO: Invalid IGD response: invalid device UUID UUID-one-char-too-short (continuing anyway)
[YYYYY] 15:19:43 INFO: Invalid IGD response: invalid device UUID UUID-one-char-too-short (continuing anyway)
[YYYYY] 15:19:43 INFO: Invalid IGD response: invalid device UUID UUID-one-char-too-short (continuing anyway)
[YYYYY] 15:19:53 INFO: New UPnP port mapping: external port 8096 to local port 22000.
[YYYYY] 15:49:53 INFO: Invalid IGD response: invalid device UUID UUID-one-char-too-short (continuing anyway)
[YYYYY] 15:49:53 INFO: Invalid IGD response: invalid device UUID UUID-one-char-too-short (continuing anyway)
[YYYYY] 15:49:53 INFO: Invalid IGD response: invalid device UUID UUID-one-char-too-short (continuing anyway)
[YYYYY] 15:49:53 INFO: Invalid IGD response: invalid device UUID UUID-one-char-too-short (continuing anyway)
[YYYYY] 15:56:32 INFO: Connection to XXXXX closed: EOF
[YYYYY] 16:20:03 INFO: Invalid IGD response: invalid device UUID UUID-one-char-too-short (continuing anyway)
[YYYYY] 16:20:03 INFO: Invalid IGD response: invalid device UUID UUID-one-char-too-short (continuing anyway)
[YYYYY] 16:20:03 INFO: Invalid IGD response: invalid device UUID UUID-one-char-too-short (continuing anyway)
[YYYYY] 16:20:03 INFO: Invalid IGD response: invalid device UUID UUID-one-char-too-short (continuing anyway)
[YYYYY] 16:38:25 INFO: Established secure connection to XXXXX at YY.YY.YY.YY:53140-YY.YY.YY.YY:22067 (relay-dial)
[YYYYY] 16:38:25 INFO: Connection to XXXXX closed: EOF
[YYYYY] 16:44:27 INFO: Connection to XXXXX closed: switching connections
[YYYYY] 16:44:28 INFO: Established secure connection to XXXXX at YY.YY.YY.YY:54001-ZZ.ZZ.ZZ.ZZ:43743 (direct-dial)
[YYYYY] 16:44:28 INFO: Device XXXXX client is "syncthing v0.12.20" named "tiger"
[YYYYY] 16:45:49 INFO: Connected to already connected device (XXXXX)
[YYYYY] 16:50:13 INFO: Invalid IGD response: invalid device UUID UUID-one-char-too-short (continuing anyway)
...
[YYYYY] 18:50:53 INFO: Invalid IGD response: invalid device UUID UUID-one-char-too-short (continuing anyway)
[YYYYY] 18:51:03 INFO: New UPnP port mapping: external port 37823 to local port 22000.
[YYYYY] 18:54:46 INFO: Stopping usage reporting
[YYYYY] 18:54:50 INFO: Restarting
[YYYYY] 18:54:50 OK: Exiting
[monitor] 18:54:50 INFO: Syncthing exited: exit status 3


[monitor] 18:54:51 INFO: Starting syncthing
[YYYYY] 18:54:51 INFO: syncthing v0.12.20 "Beryllium Bedbug" (go1.6 linux-amd64) unknown-user@lxslave.syncthing.net 2016-03-06 10:59:03 UTC
[YYYYY] 18:54:51 INFO: My ID: YYYYY
[YYYYY] 18:54:51 INFO: Single thread hash performance is ~207 MB/s
[YYYYY] 18:55:01 OK: Ready to synchronize default (read-write)
[YYYYY] 18:55:02 OK: Ready to synchronize foo1 (read-write)
[YYYYY] 18:55:02 OK: Ready to synchronize foo2 (read-write)
[YYYYY] 18:55:02 OK: Ready to synchronize foo3 (read-write)
[YYYYY] 18:55:03 OK: Ready to synchronize foo4 (read-write)
[YYYYY] 18:55:03 OK: Ready to synchronize foo5 (read-write)
[YYYYY] 18:56:57 OK: Ready to synchronize arbeiten (read-write)
[YYYYY] 18:56:57 INFO: Using discovery server https://support:8443
[YYYYY] 18:56:57 INFO: Completed initial scan (rw) of folder default
[YYYYY] 18:56:57 INFO: Invalid IGD response: invalid device UUID UUID-one-char-too-short (continuing anyway)
...
[YYYYY] 18:56:57 INFO: Invalid IGD response: invalid device UUID UUID-one-char-too-short (continuing anyway)
[YYYYY] 18:56:57 INFO: Device YYYYY is "jackal" at [dynamic]
[YYYYY] 18:56:57 INFO: Device ZZZZZ is "mdrFP2" at [dynamic]
[YYYYY] 18:56:57 INFO: Device XXXXX is "tiger" at [dynamic]

### see here(!):

[YYYYY] 18:56:57 INFO: Cleaned away old file panic-20160304-172654.log

### where would the panic log be stored? so i can get it from the backup?
### but seems unrelated as too old anyway

[YYYYY] 18:56:57 INFO: API listening on [::]:8384
[YYYYY] 18:56:57 INFO: GUI URL is https://127.0.0.1:8384/
[YYYYY] 18:56:58 INFO: Completed initial scan (rw) of folder foo3
[YYYYY] 18:56:58 INFO: Completed initial scan (rw) of folder foo1
[YYYYY] 18:56:58 INFO: Completed initial scan (rw) of folder foo4
[YYYYY] 18:56:58 INFO: Completed initial scan (rw) of folder foo5
[YYYYY] 18:56:59 INFO: Completed initial scan (rw) of folder foo2
[YYYYY] 18:57:07 INFO: New UPnP port mapping: external port 36824 to local port 22000.
[YYYYY] 18:57:41 INFO: Completed initial scan (rw) of folder arbeiten
[YYYYY] 19:27:07 INFO: Invalid IGD response: invalid device UUID UUID-one-char-too-short (continuing anyway)
[YYYYY] 19:27:07 INFO: Invalid IGD response: invalid device UUID UUID-one-char-too-short (continuing anyway)

[YYYYY] 23:03:05 INFO: Restarting
[YYYYY] 23:03:05 OK: Exiting
[monitor] 23:03:05 INFO: Syncthing exited: exit status 3
[monitor] 23:03:06 INFO: Starting syncthing
[YYYYY] 23:03:06 INFO: syncthing v0.12.20 "Beryllium Bedbug" (go1.6 linux-amd64) unknown-user@lxslave.syncthing.net 2016-03-06 10:59:03 UTC
[YYYYY] 23:03:06 INFO: My ID: YYYYY
[YYYYY] 23:03:06 INFO: Single thread hash performance is ~208 MB/s
[YYYYY] 23:03:07 OK: Ready to synchronize foo1 (read-write)
[YYYYY] 23:03:08 OK: Ready to synchronize foo2 (read-write)
[YYYYY] 23:03:08 OK: Ready to synchronize foo3 (read-write)
[YYYYY] 23:03:08 OK: Ready to synchronize foo4 (read-write)
[YYYYY] 23:03:09 OK: Ready to synchronize foo5 (read-write)
[YYYYY] 23:03:27 OK: Ready to synchronize arbeiten (read-write)
[YYYYY] 23:03:27 OK: Ready to synchronize default (read-write)
[YYYYY] 23:03:27 INFO: Using discovery server https://support:8443
[YYYYY] 23:03:27 INFO: Completed initial scan (rw) of folder default
[YYYYY] 23:03:27 INFO: Device YYYYY is "jackal" at [dynamic]
[YYYYY] 23:03:27 INFO: Device ZZZZZ is "mdrFP2" at [dynamic]
[YYYYY] 23:03:27 INFO: Device XXXXX is "tiger" at [dynamic]
[YYYYY] 23:03:27 INFO: API listening on [::]:8384
[YYYYY] 23:03:27 INFO: GUI URL is https://127.0.0.1:8384/
[YYYYY] 23:03:27 INFO: Invalid IGD response: invalid device UUID UUID-one-char-too-short (continuing anyway)
[YYYYY] 23:03:27 INFO: Invalid IGD response: invalid device UUID UUID-one-char-too-short (continuing anyway)
[YYYYY] 23:03:27 INFO: Invalid IGD response: invalid device UUID UUID-one-char-too-short (continuing anyway)
[YYYYY] 23:03:27 INFO: Invalid IGD response: invalid device UUID UUID-one-char-too-short (continuing anyway)
[YYYYY] 23:03:28 INFO: Completed initial scan (rw) of folder foo3
[YYYYY] 23:03:28 INFO: Completed initial scan (rw) of folder foo1
[YYYYY] 23:03:28 INFO: Completed initial scan (rw) of folder foo4
[YYYYY] 23:03:29 INFO: Completed initial scan (rw) of folder foo5
[YYYYY] 23:03:30 INFO: Completed initial scan (rw) of folder foo2
[YYYYY] 23:03:37 INFO: New UPnP port mapping: external port 36824 to local port 22000.
[YYYYY] 23:04:11 INFO: Completed initial scan (rw) of folder arbeiten
[YYYYY] 23:04:30 INFO: Established secure connection to XXXXX at YY.YY.YY.YY:56588-ZZ.ZZ.ZZ.ZZ:43743 (direct-dial)
[YYYYY] 23:04:30 INFO: Device XXXXX client is "syncthing v0.12.20" named "tiger"
[YYYYY] 23:33:37 INFO: Invalid IGD response: invalid device UUID UUID-one-char-too-short (continuing anyway)
```
<br>
##### `tiger`
```
# before i started:

[XXXXX] 11:42:28 INFO: Puller: final: peers who had this file went away, or the file has changed while syncing. will retry later
[XXXXX] 11:42:30 INFO: Puller (folder "arbeiten", file "/.foo.sh.swp"): pull: peers who had this file went away, or the file has changed while syncing. will retry later

# which are occasionally interrupted by the following line:

[XXXXX] 11:12:31 INFO: Folder "arbeiten" isn't making progress. Pausing puller for 1m0s.


# after moving the folder on `jackal/YYYYY`:

[XXXXX] 15:54:24 INFO: Connection to YYYYY closed: device paused
[XXXXX] 15:56:33 INFO: Connection to YYYYY closed: read tcp 10.10.1.63:22000->78.47.126.53:40373: use of closed network connection
[XXXXX] 15:56:42 INFO: Shutting down
[XXXXX] 15:56:42 OK: Exiting


# after moving the folder on `tiger/XXXXX`:

[monitor] 16:24:15 INFO: Starting syncthing
[XXXXX] 16:24:15 INFO: syncthing v0.12.20 "Beryllium Bedbug" (go1.6 linux-amd64) unknown-user@lxslave.syncthing.net 2016-03-06 10:59:03 UTC
[XXXXX] 16:24:15 INFO: My ID: XXXXX
[XXXXX] 16:24:15 INFO: Single thread hash performance is ~196 MB/s
[monitor] 16:24:27 INFO: Signal 15 received; exiting


[monitor] 16:24:48 INFO: Starting syncthing
[XXXXX] 16:24:48 INFO: syncthing v0.12.20 "Beryllium Bedbug" (go1.6 linux-amd64) unknown-user@lxslave.syncthing.net 2016-03-06 10:59:03 UTC
[XXXXX] 16:24:48 INFO: My ID: XXXXX
[XXXXX] 16:24:49 INFO: Single thread hash performance is ~191 MB/s
[XXXXX] 16:25:09 OK: Ready to synchronize arbeiten (read-write)
[XXXXX] 16:25:09 OK: Ready to synchronize default (read-write)
[XXXXX] 16:25:09 INFO: Using discovery server https://support:8443
[XXXXX] 16:25:09 INFO: Completed initial scan (rw) of folder default
[XXXXX] 16:25:09 INFO: Device XXXXX is "tiger" at [dynamic]
[XXXXX] 16:25:09 INFO: Device YYYYY is "Jackal" at [dynamic]
[XXXXX] 16:25:09 INFO: Device ZZZZZ is "mdrFP2" at [dynamic]
[XXXXX] 16:25:09 INFO: API listening on 10.10.11.1:8384
[XXXXX] 16:25:09 INFO: GUI URL is http://10.10.11.1:8384/
[XXXXX] 16:25:09 INFO: Starting usage reporting
[XXXXX] 16:25:19 INFO: New UPnP port mapping: external port 43743 to local port 22000.
[XXXXX] 16:25:20 INFO: Connection from paused device (YYYYY)
[monitor] 16:25:27 INFO: Signal 15 received; exiting


[monitor] 16:28:19 INFO: Starting syncthing
[XXXXX] 16:28:19 INFO: syncthing v0.12.20 "Beryllium Bedbug" (go1.6 linux-amd64) unknown-user@lxslave.syncthing.net 2016-03-06 10:59:03 UTC
[XXXXX] 16:28:19 INFO: My ID: XXXXX
[XXXXX] 16:28:20 INFO: Single thread hash performance is ~196 MB/s
[XXXXX] 16:28:38 OK: Ready to synchronize arbeiten (read-write)
[XXXXX] 16:28:38 OK: Ready to synchronize default (read-write)
[XXXXX] 16:28:38 INFO: Using discovery server https://support:8443
[XXXXX] 16:28:38 INFO: Device YYYYY is "Jackal" at [dynamic]
[XXXXX] 16:28:38 INFO: Device ZZZZZ is "mdrFP2" at [dynamic]
[XXXXX] 16:28:38 INFO: Device XXXXX is "tiger" at [dynamic]
[XXXXX] 16:28:38 INFO: API listening on 10.10.11.1:8384
[XXXXX] 16:28:38 INFO: GUI URL is http://10.10.11.1:8384/
[XXXXX] 16:28:38 INFO: Starting usage reporting
[XXXXX] 16:28:38 INFO: Completed initial scan (rw) of folder default
[XXXXX] 16:28:48 INFO: New UPnP port mapping: external port 43743 to local port 22000.
[XXXXX] 16:29:20 INFO: Connection from paused device (YYYYY)
[XXXXX] 16:30:21 INFO: Connection from paused device (YYYYY)
[XXXXX] 16:31:21 INFO: Connection from paused device (YYYYY)
[XXXXX] 16:32:21 INFO: Connection from paused device (YYYYY)
[XXXXX] 16:33:21 INFO: Connection from paused device (YYYYY)
[XXXXX] 16:34:25 INFO: Connection from paused device (YYYYY)
[XXXXX] 16:35:25 INFO: Connection from paused device (YYYYY)
[XXXXX] 16:36:26 INFO: Connection from paused device (YYYYY)
[XXXXX] 16:37:26 INFO: Connection from paused device (YYYYY)
[XXXXX] 16:37:35 INFO: Completed initial scan (rw) of folder arbeiten
[XXXXX] 16:38:26 INFO: Connection from paused device (YYYYY)
[XXXXX] 16:38:26 INFO: Connection from paused device (YYYYY)
[XXXXX] 16:39:27 INFO: Connection from paused device (YYYYY)
[XXXXX] 16:40:27 INFO: Connection from paused device (YYYYY)
[XXXXX] 16:41:27 INFO: Connection from paused device (YYYYY)
[XXXXX] 16:42:28 INFO: Connection from paused device (YYYYY)
[XXXXX] 16:43:28 INFO: Connection from paused device (YYYYY)
[XXXXX] 16:44:28 INFO: Established secure connection to YYYYY at 10.10.1.63:22000-78.47.126.53:54001 (direct-accept)
[XXXXX] 16:44:30 INFO: Device YYYYY client is "syncthing v0.12.20" named "jackal"
[XXXXX] 16:45:51 INFO: Connected to already connected device (YYYYY)
[XXXXX] 18:52:19 INFO: Relay received: xdr read: EOF
[XXXXX] 18:52:20 INFO: Relay join: Incorrect response code 2: already connected
[XXXXX] 18:52:20 INFO: Relay join: Incorrect response code 2: already connected
[XXXXX] 18:54:51 INFO: Connection to YYYYY closed: EOF
[XXXXX] 23:04:32 INFO: Established secure connection to YYYYY at 10.10.1.63:22000-78.47.126.53:56588 (direct-accept)
[XXXXX] 23:04:32 INFO: Device YYYYY client is "syncthing v0.12.20" named "jackal"
```

<br>
### Anything else?

... that i can provide?

**Comment by AudriusButkevicius** [comment] 2016-04-27 20:33
Closing this because I think this should be fixed.
Please shout if you can reproduce this with version 0.12.3 or master

**Closed by AudriusButkevicius** 2016-04-27 20:33 UTC

**Comment by martin-rueegg** [comment] 2016-04-29 11:59
perfect. and thank you!

i'm currently runniung v0.12.22 "Beryllium Bedbug". can it be that you referred to [v0.13.0-beta.3](https://github.com/syncthing/syncthing/releases/tag/v0.13.0-beta.3)?

anyway, if i observe it with anything newer than that, i'll let you know.

thanks again,
martin.

**Comment by wweich** [comment] 2016-04-29 12:22
Probably a typo (`0.12.3 -> 0.12.23`). Both `0.12.22` and `0.13.0-beta3` are older than the fix.

**Comment by AudriusButkevicius** [comment] 2016-04-29 12:34
No. 0.12.4 is when this bug potentially might have been introduced, so if you can still repro with 0.12.3, we should reopen.

**Comment by martin-rueegg** [comment] 2016-04-29 12:36
ok, thanks for clarification.
