### ISSUE TITLE
Folder rescan Interval reverts to 3600 on first open of folder configurartion

### ISSUE THREAD

**Issue by Vo-Shay** [syncthing/syncthing#4960] opened 2018-05-21 02:40 UTC
The rescan interval for a folder is reset to 3600 in the GUI the first time you open a folder configuration after connecting to Syncthing with a fresh browser session (this does not seem to happen subsequently when opening a folder's configuration after the first time).

Saving the configuration at this point then saves the 3600 rescan interval, overriding the previous value. 

Obviously, I don't expect the rescan interval to revert to 3600 seconds if it was set to something else. 

### Steps to reproduce
Have a syncthing instance running and share a folder, and set its rescan interveral to something other than the default 3600. 
Close the browser (or close Synctrayzor to a notification icon).
Open a new browser session and connect to snycthing (or reopen Synctrayzor).
Expand the folder details (notice the rescan interval is not the default as per your config change).
Open the folder configuration and go to the advanced tab.
See that the Rescan interval value is 3600.

### Version Information

Syncthing Version: v0.14.47
OS Version: Windows 10 (Synctrayzor) / Debian 9
Browser Version: Snyctrayzor 1.1.21 / Firefox 52.7.3

**Comment by calmh** [comment] 2018-05-21 05:48
Duplicate of #4944 

Fixed in current master

**Closed by calmh** 2018-05-21 05:48 UTC
