### ISSUE TITLE
Ignored directories reported as out of sync

### ISSUE THREAD

**Issue by rieje** [syncthing/syncthing#9804] opened 2024-11-06 18:31 UTC
### What happened?

Ignored directories are reported as out of sync between my 3 devices (2 workstations and a server), resulting in "Syncing" never being 100% which is important for me to check whether all the devices are synced. All directories are reported as "Up to Date", including the relevant sync directory with the ignored patterns below.

I have an .stignore file with the following:

    // Whitelisted files
    !firefox/.firefox-template-profile/.mozilla/firefox/main/browser-extension-data
    !firefox/.firefox-template-profile/.mozilla/firefox/main/chrome
    !firefox/.firefox-template-profile/.mozilla/firefox/main/extensions
    !firefox/.firefox-template-profile/.mozilla/firefox/main/sessionstore-backups
    !firefox/.firefox-template-profile/.mozilla/firefox/main/storage
    !firefox/.firefox-template-profile/.mozilla/firefox/main/addonStartup.json.lz4
    !firefox/.firefox-template-profile/.mozilla/firefox/main/cert_override.txt
    !firefox/.firefox-template-profile/.mozilla/firefox/main/extension-preferences.json
    !firefox/.firefox-template-profile/.mozilla/firefox/main/extension-settings.json
    !firefox/.firefox-template-profile/.mozilla/firefox/main/extensions.json
    !firefox/.firefox-template-profile/.mozilla/firefox/main/handlers.json
    !firefox/.firefox-template-profile/.mozilla/firefox/main/prefs.js
    !firefox/.firefox-template-profile/.mozilla/firefox/main/sessionstore.jsonlz4
    !firefox/.firefox-template-profile/.mozilla/firefox/profiles.ini

    // Blacklist everything else
    firefox/.firefox-template-profile

Across my devices, they all report out of sync for *at least* one of the following entries (all directories) and it is seemingly random (sometimes all of them are out of sync, sometimes only 1 of them):

    firefox/.firefox-template-profile/.mozilla 	128 B
    firefox/.firefox-template-profile/.mozilla/firefox 	128 B
    firefox/.firefox-template-profile/.mozilla/firefox/main 	128 B

I tried a combination of `--reset-deltas` and removing the contents of the sync dir and starting a full sync again but would like a more formal debugging process.

If anyone also has a workaround for using the API to consider the devices as 100% synced excluding the entries above, that would also be much appreciated.

### Syncthing version

v.1.28

### Platform & operating system

Linux

**Comment by tomasz1986** [comment] 2024-11-06 19:04
Duplicate of https://github.com/syncthing/syncthing/issues/7474.

**Closed by tomasz1986** 2024-11-06 19:04 UTC
Labels: bug, needs-triage
