### ISSUE TITLE
File restore doesn't work on one folder

### ISSUE THREAD

**Issue by rkfg** [syncthing/syncthing#4738] opened 2018-02-05 09:22 UTC
It works on other directories but on one specific folder there's no tree displayed, the JS console says:

```
TypeError: $scope.restoreVersions.tree.filterNodes is not a function
    at syncthingController.js:1967
    at Object.$watchCollectionAction [as fn] (angular.js:11724)
    at Scope.$digest (angular.js:11827)
    at Scope.$apply (angular.js:12080)
    at done (angular.js:7862)
    at completeRequest (angular.js:8045)
    at XMLHttpRequest.xhr.onreadystatechange (angular.js:8001)
```

Syncthing Version: v0.14.44-rc.3
OS Version: Debian 9.3
Browser Version: Version 64.0.3282.119 (Official Build) beta (64-bit)

**Comment by AudriusButkevicius** [comment] 2018-02-08 20:19
How do I reproduce this exactly?
The term directory and folder are intermingled, so it's not obvious to me what the directory tree needs to look like to repro this.

No data means there is no .stversions directory, or it's empty.

**Comment by AudriusButkevicius** [comment] 2018-02-08 20:30
Also, adding a breakpoint there, and printing the value of `$scope.restoreVersions.tree` and `$scope.restoreVersions.tree.filterNodes` would be interesting.

**Comment by JeanOlivier** [comment] 2018-02-08 20:32
*No Data:*
I confirm that you're right about the No data part. Simple Versioning was seemingly activated for the folder but the .stfolder is empty. I don't remember activating versioning on that device so that may be an unrelated bug or oversight on my part.

*About the real JS bug:*
I really don't know how you could reproduce this. Is there any debug info I can send you that'd help? 
When I say Folder, I mean the Folders in the WebUI, the "shares" between the devices. Not a subdirectory inside of those.

**Comment by AudriusButkevicius** [comment] 2018-02-08 20:34
Well, you can add a breakpoint in the js console, and print the value of those two things and let me know what it is.

**Comment by AudriusButkevicius** [comment] 2018-02-08 20:34
Does the issue persist if you reload the page?

**Comment by JeanOlivier** [comment] 2018-02-08 20:38
Sorry, I did not see the reply just before mine. 
I'm not really used to JS development; how do I add that breakpoint?

If I reload the page, the error appears again if I try to use the "Versions" button. The old one doesn't disappears, but I'd probably just because of how chrome logs it?

**Comment by JeanOlivier** [comment] 2018-02-08 20:45
I think I managed to do it, if it's now what you were looking for, please provide me some pointers.

I put a breakpoint on line 1967 of file /syncthing/core/syncthingController.js

`$scope.restoreVersions.tree: jQuery.fn.init`
`$scope.restoreVersions.tree: undefined`

**Comment by AudriusButkevicius** [comment] 2018-02-08 21:03
Is it reliably reproducible every time on the same machine or does it happen only sometimes?
If it happens always, what OS browser is it? Did you try a different browser?

**Comment by JeanOlivier** [comment] 2018-02-08 21:17
All folders, all the time. Both on Chrome Version 63.0.3239.132 (Official Build) (64-bit) and Firefox 58.0.1.

**Comment by AudriusButkevicius** [comment] 2018-02-08 21:24
But this is on a specific machine right? Is this Windows/Linux/macOS?

**Comment by JeanOlivier** [comment] 2018-02-08 21:55
I'm accessing it from an Ubuntu 16.04 LTS machine and an Android 7 phone with the same result. Syncthing is running on a chromebox running an Ubuntu-based distro called xbmcbuntu. The output of `uname -a` is `Linux <censored> 3.19.0-031900-generic #201502091451 SMP Mon Feb 9 14:52:52 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux`.

**Comment by calmh** [comment] 2018-05-15 16:42
This seems to be hanging; possibly related to #4901? Closing until a reproducer pops up or someone yells.

**Comment by rkfg** [comment] 2018-05-15 16:48
Err... why close a bug that's clearly affecting more than one person and that's not fixed? For me it stopped happening but only because I migrated that folder to gocryptfs and removed .stversions completely. But that doesn't mean this is solved or fixed.

**Comment by AudriusButkevicius** [comment] 2018-05-15 18:39
I say there is no point in keeping something open if there is no reproducer, as it's not something we can fix, hence it's not actionable task we can close in the future

**Comment by DEDAjs** [comment] 2018-06-29 18:04
I have the same issue and spent quite a bit of time debugging until I found the cause. The problem/bug is in the order of execution in which asynchronous events are fired and executed (timing). I'm not sure why it happens on some machines but not others. In my case it started when my version tree got big (> 5000 versions).

Here's the run down:

When the user clicks on the *Versions* button, [`$scope.restoreVersions.show`](https://github.com/syncthing/syncthing/blob/v0.14.48/gui/default/syncthing/core/syncthingController.js#L1852) is invoked and performs the following:

1. Show the ['#restoreVersions'](https://github.com/syncthing/syncthing/blob/v0.14.48/gui/default/syncthing/core/syncthingController.js#L1857) modal/dialog box.
2. Perform HTTP Get request to fetch the versions.
	2a. When the version `data` is returned assign it to [`$scope.restoreVersions.versions = data;`](https://github.com/syncthing/syncthing/blob/v0.14.48/gui/default/syncthing/core/syncthingController.js#L1873)
	2b. Setting `$scope.restoreVersions.versions = data;` triggers an Angular event to add `#restoreTree` to the DOM: [here](https://github.com/syncthing/syncthing/blob/v0.14.48/gui/default/syncthing/folder/restoreVersionsModalView.html#L4)
3. When the top 2 promises are resolved:
	3a. Initialize the tree [`$("#restoreTree").fancytree({})`](https://github.com/syncthing/syncthing/blob/v0.14.48/gui/default/syncthing/core/syncthingController.js#L1882)
	3b. Initialize the filters and other stuff.

The issue is that sometimes **3a** is being executed before **2b**. In other words the initialization of `#restoreTree` node is called before Angular event is fired to add `#restoreTree` node to the DOM.

The right fix is to wait until Angular event **2b** is fired and completed before performing **3**.
A quick fix/test/hack is to replace the line [here](https://github.com/syncthing/syncthing/blob/v0.14.48/gui/default/syncthing/core/syncthingController.js#L1876) with the following code to essentially wait until `#restoreTree` is added to the DOM before initializing it:

```javascript
var waitForRestoreTree = $q.defer();
var waitTimer = setInterval( ()=>{
    if ($("#restoreTree").length){
        clearInterval(waitTimer);
	waitForRestoreTree.resolve();
    }     
}, 100);

$q.all([dataReceived, modalShown.promise, waitForRestoreTree.promise]).then(function() {
...
```
@rkfg @AudriusButkevicius : This bug is very different to replicate since the order of execution in which asynchronous promises and events are not guarantee to always occur in the same order. Nevertheless, this bug is a legitimate issue and should be re-opened. Thanks

**Comment by AudriusButkevicius** [comment] 2018-06-29 18:36
So I am not a fan of the interval hacks, and ehoever decides to address this should probably somehow wait for angular/fancy tree to do it's thing before continuing with work.

**Comment by AudriusButkevicius** [comment] 2018-06-29 18:48
I guess we could wait for a full digest cycle before setting up filters and what not.

**Comment by AudriusButkevicius** [comment] 2018-06-29 18:48
Or make the tree hidden rather than not existant.

**Comment by calmh** [comment] 2018-06-29 19:00
Take off, nuke from orbit, and rewrite the GUI in Dart or React or something.

**Comment by DEDAjs** [comment] 2018-06-29 19:15
I tested waiting for the AngularJS full digest cycle using `$timeout(...)` and it seems to work as well

```javascript
$q.all([dataReceived, modalShown.promise]).then(function() {
    $timeout(function(){
        ....
    })
});
```

**Comment by AudriusButkevicius** [comment] 2018-06-29 19:22
Pr welcome.

**Comment by AudriusButkevicius** [comment] 2018-06-29 19:23
I am sure dart fart and all others will have their own issues with their own lack of components such as trees.

**Comment by calmh** [comment] 2018-08-01 20:59
So I guess this is a bonafide bug?

**Comment by AudriusButkevicius** [comment] 2018-08-01 21:14
Yeah, one that happens under some specific conditions that I can't reproduce. But what @DEDAjs suggested makes sense I guess.

**Comment by JeanOlivier** [comment] 2018-08-01 21:52
I can confirm that I still have that bug with `Syncthing v0.14.49, Linux (64 bit)` on all but one folder that decided to work somehow.

**Comment by milefork** [comment] 2018-10-23 08:56
I've this issue too. 400 GB in .stversions Folder with simple file revisioning.
Syncthing Version: v0.14.51, Linux (64 bit)


Problem appeared in: 

`logbar.js:11 TypeError: $scope.restoreVersions.tree.filterNodes is not a function
    at syncthingController.js:2079`

![image](https://user-images.githubusercontent.com/1383479/47348551-028b3380-d6b2-11e8-8ae6-c56d1dc9d298.png)

![image](https://user-images.githubusercontent.com/1383479/47348588-16369a00-d6b2-11e8-88b4-685e82273c3b.png)

Browser as you can see is Chrome on Windows 10

**Comment by AudriusButkevicius** [comment] 2018-10-23 17:14
I don't think so. It's a race between angular and fancy tree.

**Comment by AudriusButkevicius** [comment] 2018-10-23 17:14
The solution above should help. Someone with PC access should make a PR.

**Comment by imsodin** [comment] 2018-10-30 20:47
@AudriusButkevicius 

> The solution above should help. Someone with PC access should make a PR.

The solution above as in https://github.com/syncthing/syncthing/issues/4738#issuecomment-401448753? I.e.

```diff
--- a/gui/default/syncthing/core/syncthingController.js
+++ b/gui/default/syncthing/core/syncthingController.js
@@ -1968,6 +1968,9 @@ angular.module('syncthing.core')
                         });
 
                     $q.all([dataReceived, modalShown.promise]).then(function() {
+                        $timeout(function(){
+                            ...
+                        })
                         if (closed) {
                             resetRestoreVersions();
                             return;
```

If yes, just a noop function is fine, or should there be something? I have no clue what the whole thing does, so I would just be dumbly executing here.

**Comment by AudriusButkevicius** [comment] 2018-10-30 23:01
This defers angular from touching stuff until the next digest cycle, which makes sure that watch events on collections are not fired in the same cycle.

**Closed** 2018-11-11 12:42 UTC
Labels: bug

**Comment by cromefire** [comment] 2018-11-11 12:57
Artifacts:
[linux](https://build.syncthing.net/viewLog.html?buildId=29724&buildTypeId=Syncthing_BuildLinuxCross&tab=artifacts)
[windows](https://build.syncthing.net/viewLog.html?buildId=29725&buildTypeId=Syncthing_BuildWindows&tab=artifacts)
[mac](https://build.syncthing.net/viewLog.html?buildId=29726&buildTypeId=Syncthing_BuildMac&tab=artifacts)

In case any one needs to restore data urgently.
