### ISSUE TITLE
Unable to share (partially) R/W folder

### ISSUE THREAD

**Issue by GaijinSystems** [syncthing/syncthing#6171] opened 2019-11-21 03:19 UTC
What happened:
When sharing a partially R/W folder (files can be deleted and modified, but not created), it enters a Stopped state with an i/o error referring to the inability to open .stignore.

What I expected to happen:
Having specified an existing markerName in the advanced configuration, I assumed it would behave similarly to when a RO folder is shared.  Specifically, scanning the folder, sharing the contents and erroring only when trying a delete or modify operation that it was unable to perform.

Steps to reproduce the problem:
1. Using encfs, create a reverse encrypted folder.
```mkdir ~/decrypted ~/encrypted ; encfs --reversewrite ~/decrypted ~/encrypted```
Press <enter> a couple of times and then choose a password.
2. Create a file in the decrypted folder and a corresponding file will appear in the encrypted folder.  Make a note of the encrypted filename (in my case I created .stfolder and the resulting filename was alphanumeric with no special characters).
3. Set up the share for the encrypted folder and modify the advanced settings so markerName is looking for that particular file.
4.  When those changes are applied and syncthing refreshes/restarts, the share will stop with the aforementioned error.

Notes:
I don't think this is an encfs-specific problem.  I'm fairly confident that this can be encountered in any case with a fuse-based (or other) filesystem that isn't identified as purely read-only (like a CD/DVD), but isn't fully read/write either.
Unfortunately, I wasn't able to find a way to change or override the .stignore behavior, hence this ticket.
This **does** work when the encrypted folder is a sub-folder of the share as opposed to the share itself.

Syncthing version: v1.3.1, Linux (64 bit)
OS Version:  Debian 10

**Comment by AudriusButkevicius** [comment] 2019-11-21 07:58
You description is confusing as it refers to .stfolder markerName and then talks about .stignore which is a completely different file.

Then it talks about only being possible to delete or modify files: "files can be deleted and modified, but not created"
but afterwards inverts that: 
"erroring only when trying a delete or modify operation".

I suspect this won't work in general anyway, as syncthing writes to a temp file before moving it to place for atomicity, which needs to be created, and then modified (renamed).

We don't try to identify whether a folder is read only or not, we just assume it's writable, and if its not propagate the errors to the user.

You should enable more verbose logging and capture the more precise error message and the line number where it happens.

Also, you could precreate an empty ignore file yourself while you have the permissions.

**Comment by GaijinSystems** [comment] 2019-11-21 18:25
Thank you for the quick response, @AudriusButkevicius , and my apologies for any confusion.

With this type of filesystem (reverse encfs), I am not able to directly create any files in the shared folder.  The creation of any new file occurs in a different non-shared folder and subsequently propagate to the shared folder with an encrypted name and content.

No .stignore file can be prepopulated in that folder because the act of mounting the encfs filesystem over the top renders the file inaccessible; a new .stignore file cannot be created (by touch, etc) in the shared folder because an i/o error is returned; and there is no way that any file created in the non-encrypted "source" will result in a ciphered filename matching .stignore.

When following the documentation regarding a R/O filesystem ([https://docs.syncthing.net/users/faq.html#how-do-i-serve-a-folder-from-a-read-only-filesystem](url)) due to the similar access limitations, I was not aware that the inability to access/create a .stignore file would cause a problem--since syncthing isn't able to create it on a shared CD/DVD, either.
I mentioned .stfolder because that was something referenced in the docs, and identified as something that needed to be worked around (which I did).
The actual problem lies squarely with .stignore.

I'm pasting some of the log output with the debug level increased for fs functions:
```2019/11/21 11:32:18.175362 logfs.go:79: DEBUG: ignore.go:320 basic /encrypted Open .stignore <nil> open /encrypted/.stignore: input/output error
2019/11/21 11:32:18.175386 model.go:383: WARNING: Loading ignores: open /encrypted/.stignore: input/output error
2019/11/21 11:32:18.175433 logfs.go:145: DEBUG: model.go:311 basic /encrypted Hide .stfolder <nil>
2019/11/21 11:32:18.175449 logfs.go:145: DEBUG: model.go:312 basic /encrypted Hide .stversions <nil>
2019/11/21 11:32:18.175460 logfs.go:145: DEBUG: model.go:313 basic /encrypted Hide .stignore <nil>
2019/11/21 11:32:18.175493 model.go:248: INFO: Ready to synchronize "encrypted" (qd4xt-ujhsx) (sendreceive)
2019/11/21 11:32:18.182359 logfs.go:115: DEBUG: folderconfiguration.go:158 basic /encrypted Stat . {0xc000226340} <nil>
2019/11/21 11:32:18.182538 logfs.go:115: DEBUG: folderconfiguration.go:176 basic /encrypted Stat svxlePd2Lsdvoiwertxcsagvw {0xc0002265b0} <nil>
2019/11/21 11:32:18.182852 logfs.go:79: DEBUG: ignore.go:320 basic /encrypted Open .stignore <nil> open /encrypted/.stignore: input/output error
2019/11/21 11:32:18.182902 folder.go:720: WARNING: Error on folder "encrypted" (qd4xt-ujhsx): loading ignores: open /encrypted/.stignore: input/output error
2019/11/21 11:32:18.182929 folder.go:571: INFO: Failed initial scan of sendreceive folder "encrypted" (qd4xt-ujhsx)
2019/11/21 11:32:22.984041 logfs.go:115: DEBUG: folderconfiguration.go:158 basic /encrypted Stat . {0xc00010bad0} <nil>
2019/11/21 11:32:22.984380 logfs.go:115: DEBUG: folderconfiguration.go:176 basic /encrypted Stat svxlePd2Lsdvoiwertxcsagvw {0xc000258f70} <nil>
2019/11/21 11:32:22.984687 logfs.go:79: DEBUG: ignore.go:320 basic /encrypted Open .stignore <nil> open /encrypted/.stignore: input/output error
2019/11/21 11:32:23.994692 logfs.go:115: DEBUG: folderconfiguration.go:158 basic /encrypted Stat . {0xc000916c30} <nil>
2019/11/21 11:32:23.994916 logfs.go:115: DEBUG: folderconfiguration.go:176 basic /encrypted Stat svxlePd2Lsdvoiwertxcsagvw {0xc000916ea0} <nil>
2019/11/21 11:32:23.995455 logfs.go:79: DEBUG: ignore.go:320 basic /encrypted Open .stignore <nil> open /encrypted/.stignore: input/output error```

Your time is greatly appreciated.

**Comment by AudriusButkevicius** [comment] 2019-11-21 18:40
I don't think this should be an issue, perhaps ot's a bug, or perhaps it's becausw this is not a permissions error bur a random io error.

**Comment by GaijinSystems** [comment] 2019-11-21 19:39
@AudriusButkevicius ; after looking at the source code and trying a few other tests with common ways to determine file existence and properties, I think you may be right.  Any hack-ish solution for this fringe problem would probably be a large amount of pain for a small amount of reward...

Do you think a simple boolean toggle in the advanced folder options (defaulting to false) like "bypass stignore check" which skips that check would be worthwhile or doable?

**Comment by AudriusButkevicius** [comment] 2019-11-21 20:03
It's not really a mandatory file I think, so I can't think of a reason to blow up because of it not existing. Obviously there might be a bigger story for this.

**Comment by imsodin** [comment] 2019-11-21 20:26
The problem is that the error returned is `fs.ErrNotExist(err) == false`. Otherwise we'd just go on with our lives (no .stignore is totally fine), but if there is one but we can't access is, we don't want to scan tons of otherwise ignored files. So the solution here would be for encfs to return a specific error instead of a generic i/o error.

**Comment by AudriusButkevicius** [comment] 2019-11-21 20:49
Yeah, sadly I think we're doing the right thing here.

I am not a fan of adding flags working around particularities of other software.

I guess if the file does not exist, it's silly for encfs to return something else, hence I feel this should be fixed with them.

**Closed by AudriusButkevicius** 2019-11-21 20:49 UTC

**Comment by Pavel8419** [comment] 2019-11-22 01:12
https://github.com/syncthing/syncthing/issues/6171?email_source=notifications&email_token=AGMG4Q7ZG7GWBW2KYRPZ6SDQU3X6TA5CNFSM4JP4K7N2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEE3TH7I#issuecomment-557265917
--
Sent from Mail.ru app for Android Thursday, 21 November 2019, 11:49PM +03:00 from Audrius Butkevicius  notifications@github.com :
