### ISSUE TITLE
lib/model: Filter out invalid symlinks on windows

### ISSUE THREAD

**Issue by Phoenix616** [syncthing/syncthing#4443] opened 2017-10-21 13:13 UTC
Currently the folder puller will pause for a minute if it isn't making progress anymore. This happens for example if you have symlinks in your folder which will fail as they are not supported.

This request is for the puller to completely stop if all items that would be left are either not supported or fail so that it does not unnecessary run again and again and cause CPU spikes.

### Version Information

Syncthing Version: v0.14.39
OS Version: Windows 7 (64 bit)
Browser Version: SyncTrayzor 1.1.18

**Comment by AudriusButkevicius** [comment] 2017-10-21 15:43
And how do we ever recover if we stop forever?

**Comment by Phoenix616** [comment] 2017-10-21 15:53
Well it kinda seems that it is trying to transfer the same unsupported items every time instead of ignoring them?

**Comment by AudriusButkevicius** [comment] 2017-10-21 16:01
What if it's not unsupported items but files that are in use, or directories that cannot be deleted because they have files that are ignored, etc etc?

It shouldn't be trying to transfer unsupported files in the first place, what's the actual error you are seeing?

**Comment by imsodin** [comment] 2017-10-21 16:37
I assume the folder goes to error state and pulling is paused due to the `fileValid` check, which fails for symlinks on windows:
https://github.com/syncthing/syncthing/blob/master/lib/model/rwfolder.go#L380

I think this should not cause an error, as there is nothing the user can do. Removing the symlink may not be desirable in a mixed linux-windows cluster. I think there wouldn't be any harm in just ignoring symlinks on windows or just warn about it. I don't see any reason to put the entire folder in an error state and keep pulling to no apparent benefit.

**Comment by AudriusButkevicius** [comment] 2017-10-21 16:47
I think we filter out symlinks on the indexes we receive, hence why I want to see the error message, whether it's caused by us, or perhaps the underlying filesystem doesn't support symlinks making it an error of a different flavor.

**Comment by imsodin** [comment] 2017-10-21 17:05
I can't remember any checks at all when receiving indexes from when I recently fiddled with the ignores/invalid stuff.

**Comment by Phoenix616** [comment] 2017-10-21 17:22
The main issue is that it is retrying to sync the folder with the failed/unsupported items in it every minute (as the puller is paused for a minute by default) which results in a [CPU spike](https://i.imgur.com/JTh15Xs.png). (Orange is the syncthing.exe process, all other folders are paused) Pausing the syncing of that folder removes the spike. The spike also does not happen with other folders that do not have these unsupported files in them.

**Comment by imsodin** [comment] 2017-10-21 17:23
Can you please post logs to confirm where exactly the problem is as Audrius suggested - thanks.

**Comment by Phoenix616** [comment] 2017-10-21 17:28
What kind of logs do you need, there's like two dozen debug options.

**Comment by AudriusButkevicius** [comment] 2017-10-21 17:29
The message about unsupported failed items.

**Comment by AudriusButkevicius** [comment] 2017-10-21 17:37
Yeah so that's ours and this doesn't look good.
I think we've lost the filtering out somewhere along the way.

Not sure what's the right thing todo here, potentially drop these entries upon receipt.

**Comment by calmh** [comment] 2017-10-21 17:38
I'm not looking at the code but this *could* be historical, things we've accepted into the index before we decided symlinks on windows aren't happening

**Comment by AudriusButkevicius** [comment] 2017-10-21 17:48
I can't see us filtering them out anywhere though.

**Comment by calmh** [comment] 2017-10-21 18:04
So maybe we never decided to and this is expected behavior - flagging that the box is not able to sync the expected contents of the folder. We might want to rethink that for this specific case, maybe breaking it out into a once-only warning or something. But it would require some new mechanism in the puller to note the fact that all the things we didn't manage to pull are thing we *cannot* pull and update the expected sequence number accordingly (so we don't retry).

**Comment by imsodin** [comment] 2017-10-21 18:06
Just add to the local index as invalid?

**Comment by AudriusButkevicius** [comment] 2017-10-21 18:37
Seems so.

**Comment by calmh** [comment] 2017-10-21 18:51
Yeah that sounds reasonable and in line with the other PR

**Comment by imsodin** [comment] 2017-10-21 19:00
I can think of one remaining question: `fileValid` checks for symlink and invalid filenames. How should the invalid filenames error be treated?

I would argue invalid filenames should get the folder out of sync as it is now, because the user can/should act on it. Only the symlink on windows case should be silently invalidated, as there is nothing to do there.

**Comment by AudriusButkevicius** [comment] 2017-10-26 05:13
Agree, invalid filenames should bark hard.

**Comment by AudriusButkevicius** [comment] 2017-10-26 05:33
It seems that the pull request that could have addressed this missed it, so marking as unplanned.

**Comment by imsodin** [comment] 2017-10-26 08:45
I can fix this, it isn't hard, but I would rather deal with the other two pending pulling related PRs first, otherwise there will be no end to fixing merge conflicts.

**Comment by imsodin** [comment] 2017-11-25 22:49
This was fixed in #4460 / https://github.com/syncthing/syncthing/commit/c080f677cb0d536d6bdb1465da89653f990d0449 .

**Closed by imsodin** 2017-11-25 22:49 UTC
Labels: bug
