### ISSUE TITLE
GUI: Grouping of synced folders

### ISSUE THREAD

**Issue by serjevski** [syncthing/syncthing#8849] opened 2023-04-04 07:37 UTC
Please can you add Folder grouping feature?
I.e. "Game saves", "Docs" etc.
Now I have more than 50 synced folders - it was hard to keep track of them. :)

**Comment by acolomb** [comment] 2023-04-04 07:42
Have you searched for a similar feature request on the tracker in advance? I'm almost certain there is an open issue for this already. Anyway, it just depends on someone volunteering to do the work involved, nothing else.

**Comment by imsodin** [comment] 2023-04-04 09:52
Yep, duplicate of https://github.com/syncthing/syncthing/issues/2070

**Closed by imsodin** 2023-04-04 09:52 UTC
Labels: enhancement, needs-triage
