### ISSUE TITLE
syncthing is a RAM/CPU resouce hog

### ISSUE THREAD

**Issue by axaluss** [syncthing/syncthing#4099] opened 2017-04-14 15:07 UTC
- what happened,
Server is syncing over LAN using 2.6GB RAM and 80% CPU.
 - what you expected to happen instead, and
Server is syncing over LAN using much fewer resources 
 - any steps to reproduce the problem.
sync a folder over LAN containing  	 632794 files   151083 folders  ~128 GiB in size

Syncthing Version: v0.14.26, Linux (64 bit) "Dysprosium Dragonfly"
OS Version: Ubuntu Linux 16.04 4.4.0-57-generic #78-Ubuntu SMP Fri Dec 9 23:50:32 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux 
Server Hardware: HP Micro G7 N54L Server (AMD Turion II Neo, 2,2GHz, 4GB RAM, ~11TB software RAID, 4-Bay, USB 2.0)

**Comment by calmh** [comment] 2017-04-14 15:22
That sounds wrong. Let me try to reproduce.

**Comment by calmh** [comment] 2017-04-14 15:35
Actually, that depends. 80% CPU is entirely reasonable while syncing (if not bottlenecked on the disk or something else earlier), and during the initial sync it'll keep the list of items to sync in memory, which in your case is a lot of them. Things should calm down after the initial sync.

**Comment by axaluss** [comment] 2017-04-14 15:40
I had to stop some services such that the initial sync has enough memory available. 
On weaker machines to keep a 'list of items in memory' is an issue. Couldn't this be optimized with respect to available RAM?

**Comment by axaluss** [comment] 2017-04-14 16:25
i just added more folders. 
in systemctl status it said 10 minutes ago
"INFO: Ready to synchronize 'MyFolder'"
The GUI is still not reachable after 10 minutes and it does not mention my other folders in the status logs.
iotop shows rarely any activity but the CPU usage of syncthing is @80%!

**Comment by calmh** [comment] 2017-04-14 19:48
It's tricky to optimize as it needs to know the list of things to synchronize in order to sort them according to user preferences, and take into account dependencies (not creating files before the directories that are supposed to contain them, handling renames efficiently, etc).

But I can't really reproduce this. I set up a clean instance and created a folder with 160 directories, each containing another 1000 directories, each containing four files @ 200 KiB each, all named by uuid - totalling 160160 directories, 640000 files, 122 GiB of data.

Sending side, while still idling, before first connection to the other (blank) device:

![screen shot 2017-04-14 at 21 30 49](https://cloud.githubusercontent.com/assets/125426/25054026/31094a7a-215b-11e7-8e3f-dabc534b1b92.png)

Sending side, while sending indexes after first connection:

![screen shot 2017-04-14 at 21 37 20](https://cloud.githubusercontent.com/assets/125426/25054031/3aed695e-215b-11e7-858f-24e10da39e17.png)

Receiving side, while receiving indexes and syncing:

![screen shot 2017-04-14 at 21 37 29](https://cloud.githubusercontent.com/assets/125426/25054042/49c4d82c-215b-11e7-9c4c-6c1cb04ec931.png)

A bit further along:

![screen shot 2017-04-14 at 21 39 13](https://cloud.githubusercontent.com/assets/125426/25054050/54c5a2ce-215b-11e7-91f1-a0fe173ff6b8.png)

Receiving side, after restarting it to make sure it knew of all the things it needs to queue up front, essentially the worst case I was talking about:

![screen shot 2017-04-14 at 21 46 40](https://cloud.githubusercontent.com/assets/125426/25054172/ec59d9a2-215b-11e7-8a76-f3e015375f14.png)

I can sort of agree with you that 393 MiB isn't really where I would like it to be here, but it's also quite far from the gigabytes you're apparently seeing so something else must be going on on your side.

**Comment by calmh** [comment] 2017-04-14 20:07
You could grab a memory profile while it's using a lot of memory, might possibly shed some light:

https://docs.syncthing.net/users/profiling.html

**Comment by axaluss** [comment] 2017-04-14 20:21
it's using 2.4 GB currently and CPU is jumping between 20-80%
![syncthing](https://cloud.githubusercontent.com/assets/342630/25054942/53e245ec-2160-11e7-9492-57e334dbdbf5.png)
heap profile attached

**Comment by axaluss** [comment] 2017-04-14 20:40
Also the network traffic stops as soon as there is a "Remote change detected in folder "": added file ...."

**Comment by calmh** [comment] 2017-04-14 20:43
Thanks. Unfortunately it looks like it's used those 2.4 GBs sometime in the recent past, but currently doesn't, as they're not in the profile any more. The profile shows ~150 MB which is roughly what I see (it would manifest as ~300-350 MB memory usage, with GC overhead plus extras).

As for the stalls, it sounds like database operations on this box are really slow for some reason. Maybe slow i/o? That accounts for the slow startup as well. You'll get a lot of database operations when you have multiple connected devices all syncing, like in your screenshot.

**Comment by axaluss** [comment] 2017-04-14 20:49
I guess then it's the io/database why it starts up slowly and hangs often. It's running on an software RAID.

**Comment by axaluss** [comment] 2017-04-15 09:00
The folder is not @44% with 68GB still to sync.
Damn that's slow.

**Comment by calmh** [comment] 2017-05-04 06:37
I'm closing this as it's unclear to the underlying cause and we are continually working to reduce the resource requirements. (See for example #2250, #4112 closed in 0.14.28)

**Closed by calmh** 2017-05-04 06:37 UTC
