### ISSUE TITLE
Version 0.14.15 regression configuring remote device address: port required?

### ISSUE THREAD

**Issue by vice** [syncthing/syncthing#3828] opened 2016-12-20 14:09 UTC
I had a remote device address in the form tcp://IP.ADDR without the port part and syncthing connected correctly to the default 22000 port in many previous versions.

Now with version 0.14.15 this device does not connect.
I need to explicitly put the default TCP port in the remote device address (tcp://IP.ADDR:22000) for syncthing  version 0.14.15 to connect to it.
Dynamic address work perfectly but this remote device is from a network that needs routing.

I just upgrade another Ubuntu machine with the same results after switching from a dynamic remote device to its IP address. It only connect when the port is included. This device is on the same network segment so I left it as dynamic.

Is the port part now required?

### Version Information
Syncthing Version: v0.14.15
OS Version: Ubuntu 16.10 / Gentoo

**Comment by kerko** [comment] 2016-12-20 14:19
duplicate of  #3824 and #3817
You can use `tcp://hostname.domain.tld:22000` as a workaround.

**Closed** 2016-12-20 14:26 UTC
