### ISSUE TITLE
Consider multi-connection support to transfer files

### ISSUE THREAD

**Issue by hardhub** [syncthing/syncthing#8731] opened 2022-12-27 06:29 UTC
To synchronize 2 sites which are geographically distributed Syncthing has to pass through many hops. Single TCP (or any other) connection which is used to transfer data is _very limited in bandwidth by magistral or local providers_.  
It usually happens because traffic exchange points are heavily loaded, traffic shaped, or networks misconfiguration etc.  
It is easy to check via [speedtest.net](https://www.speedtest.net/) by selection of single/multi mode and some server in another country (or even continent).

For example, connecting from Europe to USA in **single connection**:

![image](https://user-images.githubusercontent.com/4306334/209620795-a98c2fc7-de3e-4525-ae02-7cbe2d5d0925.png)

And the same setting, except **multi-connections**:

![image](https://user-images.githubusercontent.com/4306334/209620862-ca2307b4-39a3-4940-8731-a48e47299e06.png)

In my specific case situation even much worse, it results that on 200 MBit/s connection Syncthing exchanges data in peak hours with speed 100 KB/s, and up to 2 MB/s at night. In comparison _aria2c_ with 100 connections even in worst cases can utilize full bandwidth and downloads file with speed 22-24 MB/s.  
Increasing of speed is dramatic... Even 2 MB/s is very slow but 100 KB/s makes Syncthing unusable for scenarios with geo-distributed sites and a lot of hops.

So it is crucial thing for Syncthing to **support multi-connections** like it is made for example in aria2c.

**Comment by bt90** [comment] 2022-12-27 07:10
Can you test QUIC? It should work noticeably better on high latency connections.

**Comment by calmh** [comment] 2022-12-27 09:19
Duplicate of #8184

In short, not right now.

**Closed by calmh** 2022-12-27 09:19 UTC
Labels: enhancement, needs-triage

**Comment by hardhub** [comment] 2022-12-27 10:23
> Can you test QUIC? It should work noticeably better on high latency connections.

Just tested - no difference. And that is expected, as I said the reason is not high latency.
