### ISSUE TITLE
Spurious sync-conflict files created

### ISSUE THREAD

**Issue by jtbr** [syncthing/syncthing#6676] opened 2020-05-24 13:03 UTC
Hello, I've just added a pair of synced folders, where the files (mostly) were already the same in the relevant directories.

Upon the initial scan of the new, previously unscanned folder (which is marked receive-only), a number of files that appear to be identical have been marked as sync-conflicts (or rather, duplicated with this name).  I can't figure out why this might have happened. Here is an example:

    jtbr@eeeserv$ ls DNG* -l --time-style=full-iso
    -rw-r--r-- 1 jtbr jtbr 343647376 2017-12-24 08:32:48.123480000 +0100 DNGConverter_10_1.exe
    -rw-r--r-- 1 jtbr uucp     343647376 2017-12-24 08:32:48.123480000 +0100 DNGConverter_10_1.sync-conflict-20200521-184717-5RQAITR.exe
    jtbr@eeeserv$ sha512sum DNGConverter_10_1.*
    f71ea2185d73f063dd59727ab45aab0cbfcbdeb0f821ef752ca4a31b37bbb99d8ce087847a9098d579f4b71839b6d8e3f90dd363fdc50711ca0beddaaca16946  DNGConverter_10_1.exe
    f71ea2185d73f063dd59727ab45aab0cbfcbdeb0f821ef752ca4a31b37bbb99d8ce087847a9098d579f4b71839b6d8e3f90dd363fdc50711ca0beddaaca16946  DNGConverter_10_1.sync-conflict-20200521-184717-5RQAITR.exe

The only difference I see is the group, which I thought is ignored. All relevant files with this issue seem to be large, in the hundreds of megabytes or gigabytes. The smallest I found is 270MB.

Both machines are running syncthing 1.5.0 in ubuntu-based environments, and the filesystems are EXT4. The new machine is an Intel Atom-based device with 2GB ram, though I doubt that has to do with it.

**Comment by AudriusButkevicius** [comment] 2020-05-24 13:06
Can you reliably reproduce this somehow?

**Comment by calmh** [comment] 2020-05-24 14:12
Is this an old setup, with at least some of the data likely to have been indexed in pre 1.2.0-days? This should only happen if the data or block size is different, and 256 MiB is the cutoff where the block size changes from the minimum.

If so I think this is the effect of a trivial conflict like modtime becoming a "real" conflict because the data looks different, while it would otherwise not create a conflict file and go unnoticed.

**Comment by jtbr** [comment] 2020-05-24 17:53
@AudriusButkevicius I'm in the process of trying to reproduce with a new set of folders on the same devices. I'll let you know how it goes. 

@calmh I'm not sure I follow your hypothesis, but the existing, previously synced (with other devices) folder was indeed first indexed long ago with I think syncthing pre-1.0. It has been repeatedly upgraded since then. The newly synced folder is on an external drive on a new device. At some point in the past it may have been previously synced using syncthing (I can't recall). But it wasn't connected to this computer and so had no syncthing indexes. In any case the files in this case have identical modification times.

**Comment by AudriusButkevicius** [comment] 2020-05-24 17:58
Even though I understand this is unexpected/uncomfortable for you, it's effectively due to the file being indexed in the legacy format on one of the devices, so even though the content is the same, we can't tell that from the indexed data because it was indexed using different block sizes, so the blocks simply don't match.

It's sort of known and accepted that these problems will go away over time as files in peoples folders change and get indexed in the new format, hence we don't plan to do anything here. Therefore closing.

If, however, you can reproduce this on a fresh set of folders with both sides indexing the files with something later than 1.2.0, let us know, and we'll reopen it.

**Closed by AudriusButkevicius** 2020-05-24 17:58 UTC
Labels: bug, needs-triage, waiting-for-info

**Comment by jtbr** [comment] 2020-05-24 19:41
@AudriusButkevicius I see. Is there a way to force a reindex? Most of my files will never change.

**Comment by AudriusButkevicius** [comment] 2020-05-24 19:43
Just touch them, or remove and readd the folder.
`find . -type f | while read A; do touch $A; done`
