### ISSUE TITLE
Run on condition for individual folder

### ISSUE THREAD

**Issue by EHMilon** [syncthing/syncthing#9359] opened 2024-01-21 07:44 UTC
I have to sync a lot of small and big size files. Few are very important and few are less important to sync immediately. But when I am not coverage on my Wi-Fi network, I want to sync a specific folder on metered Wi-Fi or Mobile data. It will keep us always up to date and save our data. So please add run condition for individual folder when we create a new folder. You can set it to the advance section.

**Comment by calmh** [comment] 2024-01-21 07:54
Duplicate of #8394 

(To the extent that "mobile data" on "metered" are not concepts that exist yet and "conditions" probably wouldn't be useful without them.)

**Closed by calmh** 2024-01-21 07:54 UTC
Labels: enhancement, needs-triage
