### ISSUE TITLE
[BUG] Should Sync .stignore

### ISSUE THREAD

**Issue by Joechim94** [syncthing/syncthing#5109] opened 2018-08-10 17:44 UTC
### Problem

- I have two devices (1 and 2) sharing a directory. 
- There is an .stignore in the directory that excludes a couple of files from being managed by syncthing.
- I add a third device to sync the state of the directory between the three devices
- It syncs the ignored directories because the .stignore never became synced to device 2 and resides only on device 1

### Version Information

Syncthing Version: v0.14.49
OS Version: Arch Linux / Ubuntu 18.04

**Comment by imsodin** [comment] 2018-08-10 17:49
This is more or less a duplicate of https://github.com/syncthing/syncthing/issues/2491 and can already be achieved today with `#include` directives, see https://docs.syncthing.net/users/ignoring.html or search the forum for information.

**Closed by imsodin** 2018-08-10 17:49 UTC

**Comment by AudriusButkevicius** [comment] 2018-08-10 17:58
Can you please read the docs and search the forum before you open insta-closable tickets.
Thanks.
