### ISSUE TITLE
Master folder on Linux shared to Macos spurious "out of sync"

### ISSUE THREAD

**Issue by blindchimp** [syncthing/syncthing#3516] opened 2016-08-16 16:09 UTC
This one is easy for me to reproduce... 
(Both machines have ST0.14.4 running.)
* Create empty folder master on Linux (I tried ext4 and vintage ext3 filesystems, no difference in result.)
* Share that master to a MACOS box (with filevault enabled, didn't test on non-filevault fs).
* Create a file on the master "echo >bazbaz"

"bazbaz" is copied to the mac fine, but once the mac does its periodic scan, the
linux box will show "out of sync" with "override changes" button lit up. Once this happens
the folder is essentially "stuck" until you hit the override button. No changes occurred on the
Mac. Since there were no changes on the mac, I didn't expect the "out of sync" to pop up.
Once I hit the override changes, the out-of-sync goes away and doesn't appear to come back
for that file (though subsequent new files will cause it to pop up again.)
Maybe something to do with the new higher-res file times?

This problem didn't exist in 0.13.10.

### Version Information

Syncthing Version: 0.14.4
OS Version: ubuntu 14.04/MacOSX (whatever the latest is)

**Comment by AudriusButkevicius** [comment] 2016-08-16 16:18
Filevault probably does not support preserving modification timestamps, or timestamps with the right accuracy, or modifies files on the fly. Did you check if the content of the files is the same?

**Comment by AudriusButkevicius** [comment] 2016-08-16 16:20
Anyways, closing this as this is more of a support issue due to a funky filesystem, rather than an actual actionable bug. Open a thread on the forum for debugging and discussion, and if the issue can be worked around, we might reopen this as an enhancement.

**Comment by calmh** [comment] 2016-08-16 17:26
No, actually, this should work perfectly fine and does so for me. File vault is block level encryption underneath the normal Mac OS HFS+ file system so should really not affect anything. Reopening to investigate, but i hope it's not as simple to reproduce as reported. If it is, it should be simple to fix as well though.

**Closed** 2016-08-16 18:22 UTC
Labels: bug

**Comment by rdarioc** [comment] 2016-10-05 06:25
I am having exactly the same issue in the opposite configuration (master folder on Mac OS El Capitain syncing on an Ubuntu 16.04). May I ask when are you planning to deliver your fix and do you think your fix should also solve the issue on my configuration?

**Comment by rdarioc** [comment] 2016-10-06 05:33
Then I assume this is another issue. I will open another thread for it. Thank you.
