### ISSUE TITLE
Raspberry Pi 3: Crash during sync

### ISSUE THREAD

**Issue by Re4mstr** [syncthing/syncthing#4050] opened 2017-03-20 14:29 UTC
### General Description
- I am using a Raspberry Pi 3 Model B running Syncthing 0.14.24, Linux (ARM) package downloaded from Github.
- OS: Raspbian Jessie Lite (2017-03-02)
- My setup includes the Pi, a powered hub and a 1TB WD external HDD (ext4)
After setup, connecting and adding 2 other machines on the same network, I start syncing an empty folder shared from both machines. All good.
- I then add a folder from "M1" which has about 35gigs of different files and sizes. After about 5 minutes of syncing, syncthing or the Pi crashes. This has happened about 20 times with different setups...
- Pi / Syncthing also seems to panic when adding a third machine to the share in the middle of sync

### Crash logs etc

[panic-20170320-131043.log.txt](https://github.com/syncthing/syncthing/files/855521/panic-20170320-131043.log.txt) - Crash nr.1

[panic-20170320-162751.log.txt](https://github.com/syncthing/syncthing/files/855664/panic-20170320-162751.log.txt) - Crash nr.2

![illegal instruction detected](https://cloud.githubusercontent.com/assets/15211713/24119273/e1f601d4-0db0-11e7-8394-79e746280839.png) - Crash nr.3

![io timeout](https://cloud.githubusercontent.com/assets/15211713/24119287/ef9490f8-0db0-11e7-9396-28005dec41d3.png) - Crash nr.4

[error.txt](https://github.com/syncthing/syncthing/files/855221/error.txt) - A Crash

### Hardware tests
Memtester 700 10 - 
[memtest.txt](https://github.com/syncthing/syncthing/files/856303/memtest.txt)

### Version Information

[hardware.txt](https://github.com/syncthing/syncthing/files/855250/hardware.txt)

Syncthing Version: v0.14.24, Linux (ARM)
OS Version: Jessie Lite (2017-03-02)

I'll provide any information required to further investigate the issue. (If any)

**Comment by AudriusButkevicius** [comment] 2017-03-20 14:37
Can you provide the full log?

**Comment by Re4mstr** [comment] 2017-03-20 14:43
@AudriusButkevicius Do you want the full output or crash log?
(cmd to get said output would save time)

**Comment by AudriusButkevicius** [comment] 2017-03-20 14:58
It logs to stdout so it should be the same place where you got this excerpt from.
It also saves panic logs in the syncthings home/config directory

**Comment by Re4mstr** [comment] 2017-03-20 15:11
@AudriusButkevicius Added a panic-log.

**Comment by AudriusButkevicius** [comment] 2017-03-20 16:41
The first panic looks like a go bug, the second one looks like a corrupt database, the one you initially posted also like a go bugs, but in general the panics are so different that I think your RPI is just broken. Did you try running memtest or something like that on it to validate the hardware is ok?

**Comment by Re4mstr** [comment] 2017-03-20 16:45
My thoughts during this problem, but wanted to try everything before replacing it.
I'll run a memtest and see if I can get the output.

I'll replace it if it turns out to be faulty, I guess.

**Comment by Re4mstr** [comment] 2017-03-20 20:48
Memtest succeeded as far as my knowledge goes.
I'm replacing the Pi in the coming days.

Currently testing to see if it's a problem with the HDD by syncing the same folders on the same HDD on a different computer.

**Comment by AudriusButkevicius** [comment] 2017-03-20 20:50
@calmh ideas?

**Comment by calmh** [comment] 2017-03-21 00:09
error.txt and panic-20170320-131043.log.txt look like memory corruption to me. Other panic could be the same but indirectly, hard to say. So yeah, I don't know. Doesn't look like something we can fix anyway, regardless of what the root cause is, as it's mysterious crashes deep in the runtime.

**Comment by Re4mstr** [comment] 2017-03-21 09:37
Ok.

If it is of any interest, I will be testing 2 new Pi's of the same model in the next week or so.

**Comment by AudriusButkevicius** [comment] 2017-03-21 09:44
I am closing this for now, as I don't think there is anything to do from our side, but I am pretty sure it's hardware issues.

**Closed by AudriusButkevicius** 2017-03-21 09:44 UTC
