### ISSUE TITLE
Multiple Routers/APs: Failed to set UPnP port mapping: external port 0 on device 

### ISSUE THREAD

**Issue by eduncan911** [syncthing/syncthing#2635] opened 2015-12-31 20:12 UTC
So UPnP is working correctly.  It requests the port open from my gateway router (running AdvancedTomato) on IP X.X.X.1 and all is honky dory.

But... I have 4 other routers on my network that I use for various access points around my house.  Good inexpensive dual-radio devices ($40 each for the WRT610N V1 and V2s and E4200s).  I disable the WAN on them and just use them as dumb APs.

But, SyncThing seems to want to open UPnP ports on them as well!

```
2015-12-31 14:00:42: Failed to set UPnP port mapping: external port 0 on device 'router-den' (X.X.X.3).
2015-12-31 14:30:52: Failed to set UPnP port mapping: external port 0 on device 'router-basement' (X.X.X.4).
2015-12-31 15:01:02: Failed to set UPnP port mapping: external port 0 on device 'router-office' (X.X.X.5).
```

Those three routers/APs are using the stock Linksys/Cisco firmware.

I suspect they are broadcasting something on the network, introducing themselves as a router and SyncThing thinks it needs to open ports on all of them.

NOTE: I have a forth AP, setup just like all others on IP X.X.X.2.  But, it is running TomatoUSB (Shibby) firmware instead of the stock Linksys firmware.  It doesn't show up in the SyncThing logs.

Is there a way to tell SyncThing to ignore everything that is not my gateway?

**Comment by calmh** [comment] 2016-01-01 15:51
There's no way for Syncthing to know which device is your gateway, so what happens here is that these extra deices are answering the query for UPnP routers on the network. Since you don't use that functionality, I think the easiest workaround here is to disable UPnP on these APs.

**Comment by AudriusButkevicius** [comment] 2016-01-01 15:55
Well I don't think that is true.
The reason if fails is because we ask for port 0.

This should be fixed by https://github.com/syncthing/syncthing/pull/2482 once it's done.

**Comment by calmh** [comment] 2016-01-01 16:16
Port zero is just our fallback in this case, I suspect the actual root cause failure is the router telling us to bugger off when we request the mapping, as they are in bridging mode and don't have router functionality enabled, or just plain don't have link on the WAN side.

**Comment by AudriusButkevicius** [comment] 2016-01-01 16:30
Well, we should perhaps handle that more gracefully, but he needs to provide the upnp logs.

**Comment by eduncan911** [comment] 2016-01-01 23:11
More than happy to supply more info.

While I enjoy Bash on my Arch boxes... This particular machine is a Windows machine.  So, I guess I would set `STTRACE=upnp` as a global environment variable?  Would Syncthing pick it up there?

Also, once I enable that sttrace, how do I gather more info for y'all?  Syncthing logs specifically for upnp?

**Comment by AudriusButkevicius** [comment] 2016-01-01 23:19
In the command prompt window, before you launch syncthing do `set STTRACE=upnp`, and then launch syncthing from the same prompt.

It will log to stdout (the prompt), or you can provide a -logfile option.

**Comment by eduncan911** [comment] 2016-01-02 00:48
Attached are the relative DEBUG lines I think you are looking for.  I filtered it down to just 1 router.

Let me know if I need to exclude any sensitive info in this log (already filtered the hash keys).

[log.txt](https://github.com/syncthing/syncthing/files/76094/log.txt)

**Comment by AudriusButkevicius** [comment] 2016-01-02 01:17
So that's only for one gateway, and it seems it's just returning a 500?

**Comment by eduncan911** [comment] 2016-01-02 07:51
The others are identical... Same 500.  

Again, note that this is the stock Linksys firmware.  I could understand if this was custom firmware like Tomato; but, it isn't.

Perhaps since there isn't a WAN IP, this 500 occurs.  

On the routers with Tomato custom firmware, I can disable/turn off the WAN.  But, the stock Linksys firmware does not allow me to.

For now, I've disabled UPnP on those routers.  It seems to have stopped the WARNing squealing.  I mostly came here because it was very annoying to have it shown on the web constantly - even after i click OK to ignore it.

**Comment by AudriusButkevicius** [comment] 2016-01-02 10:55
Well responding that the router provides upnp mappings and then returning 500 when we ask for one is stupid, hence it's actually you devices fault. The warnings being displayed is working as intended.

**Closed by AudriusButkevicius** 2016-01-02 10:55 UTC
