### ISSUE TITLE
missing call to MediaScannerConnection on Android

### ISSUE THREAD

**Issue by steelbytes** [syncthing/syncthing#8519] opened 2022-08-30 00:08 UTC
although you appear to use MediaScannerConnection when new files are added you don't appear to use it when deleting files.

eg, I have folder synced from pc to phone and I then add a file on the pc.  the file does appear in the gallery app on phone.  but when I delete a file on the pc it doesn't disappear from the gallery.  Using a 3rd party app to force MediaScannerConnection across my entire phone fixes this (iirc rebooting the phone also fixes it).

read https://developer.android.com/reference/android/media/MediaScannerConnection for more info

**Comment by tomasz1986** [comment] 2022-08-30 06:35
Probably a duplicate of https://github.com/syncthing/syncthing-android/issues/1818?

**Closed** 2022-08-30 06:38 UTC
Labels: bug, needs-triage
