### ISSUE TITLE
The latest version does not support go1.18 compilation!!

### ISSUE THREAD

**Issue by zxlhhyccc** [syncthing/syncthing#8258] opened 2022-04-07 16:00 UTC
### Does your log mention database corruption?

If your Syncthing log reports panics because of database corruption it is
most likely a fault with your system's storage or memory. Affected log
entries will contain lines starting with `panic: leveldb`. You will need to
delete the index database to clear this, by running `syncthing
-reset-database`.

### Include required information

Please be sure to include at least:

 - which version of Syncthing and what operating system you are using
 - browser and version, if applicable
 - what happened,
 - what you expected to happen instead, and
 - any steps to reproduce the problem.

**Comment by imsodin** [comment] 2022-04-07 16:22
This looks more like a support request than a clear bug or feature request. Please use the forum - https://forum.syncthing.net/ - for support, first by searching for any similar issues and then by posting a new one when required. The forum has a lot more eyes and friendly people on it than the issue tracker.

Thanks!

**Comment by jamesmacwhite** [comment] 2022-04-07 18:24
If it helps, the context of this report is in relation to OpenWrt: https://github.com/openwrt/packages/issues/18267

The master branch recently updated the Go lang host version to 1.18, several Go lang packages have been broken by this, most with the following error:

> ../../vendor/github.com/lucas-clemente/quic-go/internal/qtls/go118.go:5:13: cannot use "quic-go doesn't build on Go 1.18 yet." (untyped string constant) as int value in variable declaration

You can view the compile failure via the faillogs: https://downloads.openwrt.org/snapshots/faillogs/x86_64/packages/syncthing/compile.txt

The current package version in OpenWrt 1.18.2, I tried building 1.19.2 but go other errors:

> Building targets
github.com/marten-seemann/qtls-go1-18
# github.com/marten-seemann/qtls-go1-18
../../vendor/github.com/marten-seemann/qtls-go1-18/cipher_suites.go:143:43: undeclared name: any (requires version go1.18 or later)
../../vendor/github.com/marten-seemann/qtls-go1-18/cipher_suites.go:413:45: undeclared name: any (requires version go1.18 or later)
../../vendor/github.com/marten-seemann/qtls-go1-18/cipher_suites.go:418:46: undeclared name: any (requires version go1.18 or later)
../../vendor/github.com/marten-seemann/qtls-go1-18/cipher_suites.go:426:45: undeclared name: any (requires version go1.18 or later)
../../vendor/github.com/marten-seemann/qtls-go1-18/conn.go:177:10: undeclared name: any (requires version go1.18 or later)
../../vendor/github.com/marten-seemann/qtls-go1-18/conn.go:183:13: undeclared name: any (requires version go1.18 or later)
../../vendor/github.com/marten-seemann/qtls-go1-18/conn.go:211:62: undeclared name: any (requires version go1.18 or later)
../../vendor/github.com/marten-seemann/qtls-go1-18/conn.go:973:14: undeclared name: any (requires version go1.18 or later)
../../vendor/github.com/marten-seemann/qtls-go1-18/conn.go:1056:33: undeclared name: any (requires version go1.18 or later)
../../vendor/github.com/marten-seemann/qtls-go1-18/common.go:1496:41: undeclared name: any (requires version go1.18 or later)
../../vendor/github.com/marten-seemann/qtls-go1-18/conn.go:1056:33: too many errors

So we have a build issue with Go 1.18 currently.

Hope that clarifies the original report.

**Comment by tomasz1986** [comment] 2022-04-07 19:55
Thank you for the additional information. I can confirm that if you download https://github.com/syncthing/syncthing/releases/download/v1.19.2/syncthing-source-v1.19.2.tar.gz and try to use that to build Syncthing with Go 1.18, the compilation will fail with the errors listed above.

**Comment by jamesmacwhite** [comment] 2022-04-07 19:58
For info, it seems the presence of the vendor folder in the source tar.gz is the culprit, removing it before compiling works with Go 1.18.

There is another conversation around the same issue over on FreeBSD, and removing the vendor folder seems to be the solution: https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=262808#c6

**Comment by jefferyto** [comment] 2022-04-08 09:57
I believe #8260 should fix this issue (though it will require building with Go 1.17 or higher).

**Comment by imsodin** [comment] 2022-04-08 09:59
Looks like this is about the `go` directive in go.mod. From https://go.dev/doc/modules/gomod-ref#go:

> For packages within the module, the compiler rejects use of language features introduced after the version specified by the go directive. For example, if a module has the directive go 1.12, its packages may not use numeric literals like 1_000_000, which were introduced in Go 1.13.

However inconsistently this only applies to packages in the module itself, not dependencies, in "normal (modules) compilation". Now if we vendor dependencies, these are apparently treated like packages of the module itself. The package in question is gated behind a `go1.18` build flag, so there's no actual problem with compatibility.

I haven't been able to find any specifics on this behaviour or existing reports of similar issues in a quick search.

**Comment by imsodin** [comment] 2022-04-08 10:05
> I believe https://github.com/syncthing/syncthing/pull/8260 should fix this issue (though it will require building with Go 1.17 or higher).

That works indeed. But why - the `any` stuff is introduced in go1.18, not 1.17. Well anyway, we do only support the two latest go releases, so bumping to 1.17 is fine. Thanks for finding this!

**Comment by beholders-eye** [comment] 2022-04-08 20:42
> > I believe #8260 should fix this issue (though it will require building with Go 1.17 or higher).
> 
> That works indeed. But why - the `any` stuff is introduced in go1.18, not 1.17. Well anyway, we do only support the two latest go releases, so bumping to 1.17 is fine. Thanks for finding this!

Is this patching going to be in the `1.19.3` release?

**Comment by zxlhhyccc** [comment] 2022-04-09 04:49
The problem has been resolved and the source code has been compiled using vebdor under GO1.18. The existing patches are compiled using their own go.mod

**Comment by jefferyto** [comment] 2022-04-09 11:51
@AudriusButkevicius perhaps it would be good to wait for #8260 to be merged before closing this issue?

**Comment by AudriusButkevicius** [comment] 2022-04-09 12:17
From what I understand the issue is todo with people having vendor directories, which is fixed by removing them?

**Comment by jamesmacwhite** [comment] 2022-04-09 12:20
@AudriusButkevicius Not quite. This project is currently providing a vendor folder in the source code releases, causing build issues on Go 1.18 as the dependencies in the vendor folder are for a older version of Go.

**Comment by jefferyto** [comment] 2022-04-09 12:39
@jamesmacwhite The issue isn't with the dependencies in the vendor folder, the issue is Go using older (1.16) rules to parse newer (1.18) code (in qtls-go1-18).

**Comment by jamesmacwhite** [comment] 2022-04-09 13:54
@jefferyto My apologies, thanks for clarifying.

**Closed** 2022-04-09 14:01 UTC
Labels: bug, build

**Comment by beholders-eye** [comment] 2022-04-11 18:49
> @jamesmacwhite The issue isn't with the dependencies in the vendor folder, the issue is Go using older (1.16) rules to parse newer (1.18) code (in qtls-go1-18).

Does this mean that just changing go to 1.18 in `go.mod` would make even the source code compile, without removing `./vendor` ?

**Comment by beholders-eye** [comment] 2022-04-20 17:37
@jefferyto , thanks man. But the way the packaging works in source based distributions, fetching dependencies dynamically when building instead of using the `vendor/` dir, breaks the expected security. This means we need to invoke `build.go` like this:

```bash
go run build.go -no-upgrade -version "v0.19.2" build
```

By doing this, it won't run `go mod tidy` at all, and patching `go.mod` to use `1.18` instead of `1.16` just gave me a bunch of go mod vendored errors, which ended with a message like `updates to go.mod needed`. So it would be really nice to have a source tarball with the correct vendor deps in it.

That means a new tarball created after running `go mod tidy`. Thanks in advance.

**Comment by calmh** [comment] 2022-04-20 18:37
Yes. It's fixed. Latest RC, and next release.
