### ISSUE TITLE
gui: "Restore Versions": Error: $scope.restoreVersions.tree.filterNodes is not a function

### ISSUE THREAD

**Issue by Chubukov-Aleksey** [syncthing/syncthing#5223] opened 2018-09-25 13:56 UTC
I tried to revert some changed files in folder with enabled staggered versioning. Clicked on "Versions" button, appeared modal window with horizontal line, two empty fields with labels "Filter by name:" and "Filter by date:", and nothing more. "No data" warning is missing.
Browser console:

```
Error: $scope.restoreVersions.tree.filterNodes is not a function
@http://127.0.0.1:8384/syncthing/core/syncthingController.js:2023:13
$watchCollectionAction@http://127.0.0.1:8384/vendor/angular/angular.js:14298:13
$digest@http://127.0.0.1:8384/vendor/angular/angular.js:14431:23
$evalAsync/<@http://127.0.0.1:8384/vendor/angular/angular.js:14628:15
completeOutstandingRequest@http://127.0.0.1:8384/vendor/angular/angular.js:4959:7
Browser/self.defer/timeoutId<@http://127.0.0.1:8384/vendor/angular/angular.js:5347:7
 logbar.js:11:13
	intercept/console[method] http://127.0.0.1:8384/syncthing/development/logbar.js:11:13
	consoleLog/< http://127.0.0.1:8384/vendor/angular/angular.js:11725:18
	$ExceptionHandlerProvider/this.$get</< http://127.0.0.1:8384/vendor/angular/angular.js:8638:7
	$digest http://127.0.0.1:8384/vendor/angular/angular.js:14449:19
	$evalAsync/< http://127.0.0.1:8384/vendor/angular/angular.js:14628:15
	completeOutstandingRequest http://127.0.0.1:8384/vendor/angular/angular.js:4959:7
	Browser/self.defer/timeoutId< http://127.0.0.1:8384/vendor/angular/angular.js:5347:7
```

Syncthing Version: v0.14.50, Linux (64 bit)
OS Version: Gentoo
Browser Version: Firefox 62.0

**Comment by AudriusButkevicius** [comment] 2018-09-25 18:05
I thought a ticket for this already existed and someone had figured out how to fix it?

**Comment by AudriusButkevicius** [comment] 2018-09-25 18:44
I can't find it either, but I am 110% there was something, so letting this live.

**Comment by calmh** [comment] 2018-09-25 19:04
There was another thing about restore not working on trashcan versioning, which we know of, but this looks like something else.

**Comment by AudriusButkevicius** [comment] 2018-09-25 20:28
No, it was the same issue with the tree initialising outside of the angular digest cycle, or something like that.

**Comment by uok** [comment] 2018-09-25 22:09
I guess you meab https://github.com/syncthing/syncthing/issues/4738

**Comment by AudriusButkevicius** [comment] 2018-09-25 22:14
Unbelievable how poor github's search is.
Duplicate of #4738

**Closed by AudriusButkevicius** 2018-09-25 22:14 UTC
Labels: bug
