### ISSUE TITLE
Add the possibility to share a single file instead of only a folder

### ISSUE THREAD

**Issue by All3xJ** [syncthing/syncthing#8192] opened 2022-02-23 10:07 UTC
If I want to share only a file across devices, I have to manually create a folder and insert the file into it. Why isn't it possible to share only a single file without this extra step? This would fix issue related to moving the file into a folder (so chainging the file location) that can cause file not found errors in programs that are using it (for example video editor or torrent client etc etc). Yeah I can copy it, but the copying process is long sometimes if the file is big.

**Comment by AudriusButkevicius** [comment] 2022-02-23 11:50
I don't think we want to support this.

**Comment by imsodin** [comment] 2022-02-23 12:10
Also duplicate of https://github.com/syncthing/syncthing/issues/4803 and https://github.com/syncthing/syncthing/issues/4230

**Closed by imsodin** 2022-02-23 12:10 UTC
Labels: enhancement, needs-triage
