### ISSUE TITLE
Synchronize with mounted USB HDD

### ISSUE THREAD

**Issue by badele** [syncthing/syncthing#1383] opened 2015-02-25 19:55 UTC
I think it can be even better if it can synchronize with the mounted disks. For that, the simple solutions :

* In syncthing folder configuration, add options "check mounted disk"
* In the mounted USB HDD, the file must be present ".syncthing_mounted_disk"

Apparently, this feature will not be difficult to implement. With this feature, we can save on external hard drives.

What do you think ?

**Comment by AudriusButkevicius** [comment] 2015-02-25 20:19
I've already sort of addressed this, but this is more or less a duplicate of #762 as #762 would solve both problems.

**Comment by calmh** [comment] 2015-02-25 22:00
Isn't this what we already do with the `.stfolder` file, equivalent to `.syncthing_mounted_disk`?

**Comment by AudriusButkevicius** [comment] 2015-02-25 22:07
Sort of, I guess this expects the recovery part too.

**Comment by calmh** [comment] 2015-02-25 22:13
That's #420 then. :)

**Comment by AudriusButkevicius** [comment] 2015-02-25 22:34
Case closed then. Satisfied by #420 and #762

**Closed by AudriusButkevicius** 2015-02-25 22:34 UTC
