### ISSUE TITLE
Folder Master out of sync when others keep files or add extras

### ISSUE THREAD

**Issue by mikelpr** [syncthing/syncthing#2092] opened 2015-07-26 21:56 UTC
e.g. I backup my photos from android DCIM with Syncthing, but when I delete them from the phone the phone thinks it's out of sync, as the other nodes keep previous photos.
This also happens with my synced music folder: I use gnumdk/lollypop on my laptop to play music, and it downloads last.fm cover art in the albums' folders. This makes my main computer think it's out of sync.

The other nodes display as up to date but the folder masters always think they're out of sync and annoyingly are never at 100%

**Comment by AudriusButkevicius** [comment] 2015-07-26 22:00
This is expected behaviour, that's how master works, it refuses to accept changes from anyone, hence a slightest change (even modification times) make it look out of sync.

I suggest you read the docs to understand what it really does.

**Comment by mikelpr** [comment] 2015-07-26 23:10
refusing changes shouldn't make it think it's out of sync itself tho. refusing changes != folder master being out of sync.
you could say that the other nodes are out of sync because they have done changes and they no longer have the exact contents of the folder master, but that shouldn't make the folder master out of sync, it should make the nodes out of sync. instead, the nodes show up to date and the master is out of sync.

**Comment by AudriusButkevicius** [comment] 2015-07-26 23:28
No, master does not mean master copy. This is a peer to peer mechanism, the fact that you have something set to master is only meaningful locally to you. Perhaps you think that read only would be a better name, but it's just more confusing, hence I think why master was chosen (so that people actually go and read up what it does).

Once master is set, it doesn't mean life does no go on outside of that device, in which case being out of sync to what the rest of the cluster thinks is the truth. Essentially, each file has a version, if the version which someone has advertised is higher than yours, it means you are out of sync, simple as that.

You have the option to override (red button which appears), which as a result increments the version to highest seen + 1, making others accept the change, and making the "master copy" the most recent copy available.

This is currently working as intended, hence I am closing it.
If you want to pursue changing the naming or how the percentages look like, you can start a discussion in the forum under a wider audience.

**Closed by AudriusButkevicius** 2015-07-26 23:28 UTC
