### ISSUE TITLE
Hostname-specific .stignore patterns

### ISSUE THREAD

**Issue by novoid** [syncthing/syncthing#8938] opened 2023-06-13 12:19 UTC
I'd like to have an extension of the current `.stignore` concept from https://docs.syncthing.net/users/ignoring.html which is only applied to a specific hostname and which is in-sync across all hosts for that share.

There are multiple technical implementations possible:

- respecting the content of existing `.stignore_$HOSTNAME` files according to the current hostname in addition to the default `.stignore` file.
- introducing hostname-specific sections in the existing `.stignore` file format.
- introducing a $HOSTNAME variable in the existing `.stignore` syntax such that I may add a line like `#include .stignore_${HOSTNAME}` as a user-configuration (silently ignoring missing files if hostname doesn't match an existing file). 
  - _This would be my personal favorite so far as it's a flexible generalization of the problem._

The common difference to the current situation should be that a user may have file ignore patterns that only apply to specific hosts and which are still in-sync across all hosts that consume that share.

# The problem this new feature would solve

There are setups where ignore patterns only should apply to one specific host. For example, when I'm sharing my sub-hierarchy of shell scripts, I may only need a certain sub-set (or sub-hierarchy) on a specific host. To avoid unnecessary disk space, I would like to have a way to define ignore patterns that are only applied to a specific host according to its system hostname.

The current syncthing featureset requires the user to add some `.stignore` patterns that are not in-sync with other hosts that require different ignore patterns.

# Why it is generally useful

The possibility of ignoring files only on specific hosts is something that helps many people setting up their Syncthing ecosystem in a flexible way.

# Alternatives or workarounds 

Currently, I personally create ignore files like `.stignore_common`, `.stignore_host1`, `.stignore_host2` with host-specific, manually curated `.stignore` files that include the common patterns as well as the host-files that do match.

Unfortunately, this concept is not elegant (different ignore files per host for the same share) nor solves the general use-case I try to address.

For example, when adding a new host to an existing share, I need to make sure to create the target directory with its ignore files before syncthing populates this new share with data in order to avoid manually cleaning up the share after I fixed the synced ignore patterns.

**Comment by acolomb** [comment] 2023-06-14 03:52
The existing `.stignore` files are already specific to one host, not synced. I don't understand in your proposal why you want them specific to one host (different) yet also synced (same)? If you really need it, that's already possible by syncing the host-specific file names, then on each host, include the respective one from `.stignore`. Though you seem to be using this pattern already?

**Comment by imsodin** [comment] 2023-06-14 06:47
Sounds largely reasonable, and most of it was covered in some discussion around next-gen ignores before. There's no lack of possibilities to improve the system, there's just lack of developers with the means to implement and maintain such a change. As such unless you intend to do this yourself, and want to use this ticket to scope out what exactly you want to do before implementation, I don't think another issue on this topic is going to help move things along, and thus closing this as a duplicate of the general next-gen ignores issue: https://github.com/syncthing/syncthing/issues/2491. If you do intend to work on this yourself, please say so and I am very happy to re-open and engage in design deliberations :)

**Closed by imsodin** 2023-06-14 06:47 UTC
Labels: enhancement, needs-triage

**Comment by novoid** [comment] 2023-06-14 13:31
> The existing `.stignore` files are already specific to one host, not synced. I don't understand in your proposal why you want them specific to one host (different) yet also synced (same)?

Well, consider adding a new host for an existing share and you don't want the new host to get all the data but only a sub-set. The way to go is ignoring the parts you don't want on that host in the .stignore file.

Currently, you'd need to create an empty directory, manually create a .stignore file and add the ignore patterns for this new host.

With my improvement feature discussed here, the process would be much simpler: On the "old" host, I create a .stignore_NEWHOSTNAME file and add its ignore patterns. On the new host, I just add the share by "answering" the share request in the web interface and I don't have to worry about too much data being synchronized in the initial sync.

Therefore, sharing/synchronizing host-specific ignore files do make much sense in my use-cases.

> If you really need it, that's already possible by syncing the host-specific file names, then on each host, include the respective one from `.stignore`. Though you seem to be using this pattern already?

Yes, that's my current workaround which I tried to simplify for all users by proposing that feature request.

**Comment by acolomb** [comment] 2023-06-15 18:48
> Currently, you'd need to create an empty directory, manually create a .stignore file and add the ignore patterns for this new host.

It's easier than that. You can prepare the host-specific file alright. Then when adding the folder on the new device, you can specify the ignore patterns right there in the dialog (since a couple of versions ago), before anything starts syncing. Simply use this pattern then:

    !.stignore_*
    *

When the folder is synced, edit the ignores again and use the host-specific include directive instead.

You can set this up as a default for new folders, so you don't have to remember.

I still think the idea is not generally useful enough to warrant additional complexity. If you don't control all devices yourself, it even introduces a DoS attack vector: Some device can (maybe by accident) delete another's included ignore-patterns file and BOOM, that device will completely stop syncing the folder with an error condition. And what if some device later joins a folder that happens to have the same hostname?
