### ISSUE TITLE
NTFS: support case sensitivity properly

### ISSUE THREAD

**Issue by dr4Ke** [syncthing/syncthing#5621] opened 2019-03-26 11:42 UTC
### Please do post actual bug reports and feature requests.

I've got several nodes running different flavors of GNU/Linux and one new node running Windows 10.

On my GNU/Linux nodes, I've got several folders containing some files that have the same name but with a different case. I'm not sure it's a good thing to do, but I have these kind of files.

On the Windows node, it is reported as synchronization errors, and puts the folder in a "desynchronized" state.

I read the issue #2739. I'd like to add a suggestion to support NTFS case sensitivity for those who use the `caseSensitiveFilesystem` configuration. I don't know if that's possible. I saw several resources mentionning the `FILE_FLAG_POSIX_SEMANTICS` flag to create case sensitive files.

- https://stackoverflow.com/questions/33998669/windows-ntfs-and-case-sensitivity
- https://tyranidslair.blogspot.com/2019/02/ntfs-case-sensitivity-on-windows.html

I couldn't find a discussion about this possibility in here or the forum.

### Version Information

Syncthing Version: v1.1.0
OS Version: Windows 10 with other case sensitive nodes.

**Comment by AudriusButkevicius** [comment] 2019-03-26 12:17
I am pretty sure its a dupe of the same issue you mentioned, so not sure why you opened a new one.

**Comment by dr4Ke** [comment] 2019-03-26 12:38
Oh. I see. I thought it could be done in syncthing.
I saw this kind of issue indeed. I just missed any discussion about the NTFS createFile flag.
So, it seems that we won't be able to fully address this issue. That's a shame.

**Closed** 2019-03-26 12:42 UTC
