### ISSUE TITLE
conflict resolution - oldest wins?!?

### ISSUE THREAD

**Issue by crusaderky** [syncthing/syncthing#1306] opened 2015-01-28 00:16 UTC
I understand that the current resolution policy for syncthing should be "newest wins".
I'm not getting the same result however in my tests...

Host 1: syncthing 0.10.21, Ubuntu 14.04 amd64
Host 2: syncthing 0.10.21, Windows 7 amd64

Steps to reproduce:
1. start syncthing on Ubuntu
2. change the file on Windows
3. Wait a bit, e.g. a minute. Compare the clock on both hosts to make sure that clock skew is not an issue.
4. change the file on Ubuntu
5. start syncthing on Windows
6. wait for sync
7. the Windows version overwrites the Ubuntu one!

Am I missing something?

**Comment by AudriusButkevicius** [comment] 2015-01-28 08:47
Well if the the initial change on windows has not propagated to ubuntu, this can happen, as there is no conflict resolution. At the point two files get modified on two machines without the other machine being aware of it, it's nondeterministic which file will win. There already is a issue in the tracker about conflict resolution.

**Comment by AudriusButkevicius** [comment] 2015-01-28 10:03
Seems like a duplicate of https://github.com/syncthing/syncthing/issues/220

**Closed** 2015-03-20 14:21 UTC
Labels: duplicate
