### ISSUE TITLE
dpkg: error processing package syncthing-relaysrv (--configure)

### ISSUE THREAD

**Issue by bugreporting** [syncthing/syncthing#7665] opened 2021-05-11 17:03 UTC
### Does your log mention database corruption?

No

### Include required information

Please be sure to include at least:

 - which version of Syncthing and what operating system you are using
Ubuntu 20.04.2 LTS (Focal Fossa) Linux 5.4.0-70-generic #78-Ubuntu SMP Fri Mar 19 13:29:52 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux 

strelaysrv v1.15.0 "Fermium Flea" (go1.16.3 linux-amd64) deb@build.syncthing.net 2021-04-06 06:03:22 UTC [noupgrade]

 - what happened

apt update and apt upgrade caused a failure during installing returning the following error:
```
Setting up syncthing-relaysrv (1.15.0) ...
/var/lib/dpkg/info/syncthing-relaysrv.postinst: 11: Syntax error: "else" unexpected

dpkg: error processing package syncthing-relaysrv (--configure):
 installed syncthing-relaysrv package post-installation script subprocess returned error exit status 2

Errors were encountered while processing:
 syncthing-relaysrv
```

Here is a copy of the `/var/lib/dpkg/info/syncthing-relaysrv.postinst` file:
```
#!/bin/sh

after_upgrade() {
    :

systemctl --system daemon-reload >/dev/null || true
debsystemctl=$(command -v deb-systemd-invoke || echo systemctl)
if ! systemctl is-enabled strelaysrv >/dev/null
then
else
    $debsystemctl restart strelaysrv >/dev/null || true
fi
}

after_install() {
    :

systemctl --system daemon-reload >/dev/null || true
debsystemctl=$(command -v deb-systemd-invoke || echo systemctl)
}

if [ "${1}" = "configure" -a -z "${2}" ] || \
   [ "${1}" = "abort-remove" ]
then
    # "after install" here
    # "abort-remove" happens when the pre-removal script failed.
    #   In that case, this script, which should be idemptoent, is run
    #   to ensure a clean roll-back of the removal.
    after_install
elif [ "${1}" = "configure" -a -n "${2}" ]
then
    upgradeFromVersion="${2}"
    # "after upgrade" here
    # NOTE: This slot is also used when deb packages are removed,
    # but their config files aren't, but a newer version of the
    # package is installed later, called "Config-Files" state.
    # basically, that still looks a _lot_ like an upgrade to me.
    after_upgrade "${2}"
elif echo "${1}" | grep -E -q "(abort|fail)"
then
    echo "Failed to install before the post-installation script was run." >&2
    exit 1
fi
```

 - what you expected to happen instead

The package to install correctly, I ended up stopping the service and commenting out the lines for after_upgrade() and saving to force it to complete.

**Comment by bt90** [comment] 2021-05-12 09:43
Duplicate of #7548

**Closed** 2021-05-12 19:55 UTC
Labels: bug, needs-triage
