### ISSUE TITLE
List of folders/devices for sharing is missing in GUI (version 1.16.0-rc1)

### ISSUE THREAD

**Issue by frlu05** [syncthing/syncthing#7571] opened 2021-04-13 15:17 UTC
Lists to configure sharing are missing in GUI
- List of Devices to share a Folder with
- List of Folders to share to a Devices

Very short description, but I see the issue on both new- and existing folders and on both Intel/Win64 and AMD/Linux32.

**Comment by imsodin** [comment] 2021-04-13 15:33
works for me on nightlies. Can you make sure it's not a caching issue (hard refresh: ctrl+shift+r). And if the problem persists, please check the console for errors (F12).

**Comment by imsodin** [comment] 2021-04-13 15:55
Good point: Checked and also works as expected on main and v1.16.0-rc.1 for me.

**Comment by frlu05** [comment] 2021-04-13 15:56
I've rebooted both my devices (Laptop PC w Win64 and RPI4/ARM w Linux32, till the same issue(s).

Don't see any "errors" after pressing F12, but I don't know what to look for...

;-)

**Comment by imsodin** [comment] 2021-04-13 16:01
Rebooting doesn't necessarily clear your browser cache, please make sure you do that. After hitting F12, there should be a tab or similar named "console", where there's buttons named "errors", "warning", ... - disable all except errors. If there's something there, copy it here, otherwise there's no error :)

**Comment by tomasz1986** [comment] 2021-04-13 16:02
I can confirm the issue.

![image](https://user-images.githubusercontent.com/5626656/114583684-d2d6a880-9cbc-11eb-8daf-9ae51cc40359.png)

Tested with the current `main` (compiled literally a minute ago).

**Comment by imsodin** [comment] 2021-04-13 16:08
Bug is clear - git fail on my part in  #7567. The file is lying around not checked in locally, thus it works just fine for me but no-one else. Thanks!

**Comment by tezfair** [comment] 2021-04-13 16:15
It's also the same under the device tabs too
![image](https://user-images.githubusercontent.com/17702842/114585730-dbf35580-9c7b-11eb-8aea-d0232c6d2ff8.png)

**Comment by frlu05** [comment] 2021-04-13 16:17
Good that you've identified it, I'm moving to slow trying to figure out how to provide input...

Will there be another 1.16.0-rc? I don't feel confident upgrading manually from "nightlies"...

BR/

**Comment by imsodin** [comment] 2021-04-13 16:21
Yes, there will be an rc.2 soon.

**Closed** 2021-04-13 18:23 UTC
Labels: bug

**Comment by frlu05** [comment] 2021-04-15 10:28
Issue resolved/corrected on rc2 - Tested on Intel/Win64 and ARM/Debian32, both with and without "Feature Flags" set to Untrusted".

Thanx!
