### ISSUE TITLE
Ignore version-controlled directories

### ISSUE THREAD

**Issue by MazeChaZer** [syncthing/syncthing#7215] opened 2020-12-19 14:44 UTC
If Syncthing tries to sync directories that are versioned by Git or other VCS software, it will mess up really bad. I had Git repositories destroyed by Syncthing in the past because I forgot to ignore the directory. Fortunately, I could always recover from the Git remote up to now, but there is a real potential for data loss, especially if it's a local-only Git repository. The solution is pretty simple: Just let Syncthing ignore any directory that contains a `.git`, `.svn`, ... directory.

**Comment by imsodin** [comment] 2020-12-19 15:12
Duplicate of https://github.com/syncthing/syncthing/issues/837

**Closed by imsodin** 2020-12-19 15:12 UTC

**Comment by calmh** [comment] 2020-12-19 15:47
Really more like #1114 I think in that it proposes to ignore things based on something else being present in the same directory. Nonetheless, it's far fetched and unlikely, unfortunately.

**Comment by MazeChaZer** [comment] 2020-12-19 17:27
@imsodin to be clear, I don't want to exclude `.git` directories by default (then Syncthing would still mess up my working directory), I want to exclude directories that *contain* a `.git` directory.

**Comment by AudriusButkevicius** [comment] 2020-12-20 15:45
I don't think there will ever be a feature like that, and you'll always have to exclude them manually.

**Comment by MazeChaZer** [comment] 2020-12-22 10:44
Guess I'll migrate away from Syncthing then long-term, because sooner or later it will trash some Git repository I forgot to exclude and I really don't want to risk losing data. I honestly don't understand why this isn't even discussed here, this seems so easy to implement and would save many a lot of trouble :(
It doesn't even have to be a default, like @imsodin suggested, if there was an option “Exclude VCS directories” that would be all I needed. Or if an ignore pattern like `.git/..` would work.

**Comment by calmh** [comment] 2020-12-22 11:44
> this seems so easy to implement

I doubt that's the case, but I'd by happy to be proven wrong. This is open source after all, so anyone can do so at any point.

**Comment by AudriusButkevicius** [comment] 2020-12-22 12:31
> if there was an option “Exclude VCS directories” that would be all I needed

There are hundreds of different things people want to exclude, we can't have a checkbox for every one of them, hence why the ignore patterns are there.

> The ignore pattern you're looking for is .git to ignore all .git directories. I'm not sure why this wouldn't work.

He wants to ignore directories that *contains* .git, but this is false thinking anyway, because if you ignore the git directory, syncthing can only mess up the files tracked by the repo, not used to represent the git structures, so you can always use git to revert any local changes that look dodgy.

**Comment by MazeChaZer** [comment] 2020-12-22 12:50
It is not “false thinking”, that is exactly what I want. I don't want Syncthing to mess with my working directory, only Git should operate on that.

Listen, it's fine if you don't want this feature, I'm just stating what I need and if Syncthing doesn't provide that I use something else. Especially given that I probably can't contribute this myself because I don't have the time. I thought this could be useful feedback for something to consider for the future.

The only thing that annoyed me was that this issue was closed instantly, as a duplicate of something completely different. And that you @AudriusButkevicius now imply in passing that what I need is stupid. You don't know how I work and what I need.

**Comment by MazeChaZer** [comment] 2020-12-22 13:03
For future reference: [`.git/..` doesn't work](https://play.golang.org/p/8fUOwWgwsfT).

**Comment by ProactiveServices** [comment] 2020-12-22 13:07
Issue #2491 has a maybe entry for "Ability to ignore a directory by the presence of a special file in it (cachedir.tag)." This coupled with an extension to the "configuration defaults" feature would resolve your feature request.

Keep in mind people use Syncthing for all sorts of different reasons and ignoring arbitrary paths by default would break things. What of someone who uses Syncthing to copy files to a remote machine which backs up the data, and they want to backup their git projects?

It's easy for us to think our use cases can, or should, apply to everyone, but you'd be surprised how many people come out of the woodwork with valid counterexamples. This is why your issue was closed so quickly and you may have received short shrift from other responders. Lots of people turn up expecting this software to change for them, but without considering the wider picture or without offering to help implement the changes. I agree that Syncthing should sync everything by default, as far as it possibly can. More tools to control what is synced is not a bad thing, though.

**Comment by MazeChaZer** [comment] 2020-12-22 13:26
@ProactiveServices thanks for the link to the issue. I understand that my use case is very different from others. If I used Syncthing for backup I certainly wouldn't want it to exclude my Git repositories. Looking back I have to admit that my initial OP was formulated a bit too bold and simplistic, this really shouldn't be the default behavior but some kind of ignore pattern or option. My problem is just that Syncthing doesn't play well with VCS software and currently there is no solution for this.

**Comment by calmh** [comment] 2020-12-22 13:30
I have no idea what the Go playground link above is supposed to relate to. It has nowthing to do with out ignore patterns. If you're for some reason thinking you can't ignore `.git` directories and everything under them you're dead wrong and just need to try the pattern in Syncthing.

**Comment by calmh** [comment] 2020-12-22 13:33
(Deleted an irrelevant comment by myself.)

**Comment by tomasz1986** [comment] 2020-12-22 13:39
> My problem is just that Syncthing doesn't play well with VCS software and currently there is no solution for this.

Are you perhaps able to have a specific pattern when naming those folders or store them in one location that you could ignore? If not, then maybe some kind of a script that would run periodically in background and add them to `.stignore` automatically?


I believe that the reason for things like `folder/..` (or maybe `folder/../*`?) not to work in `.stignore` is that the dots are interpreted literally, i.e. as if you were trying to ignore a file/folder named `..` (which is not valid, but still).

**Comment by imsodin** [comment] 2020-12-22 13:49
Please lets not discuss about workflows/workarounds in github issues, that's what the forum is for: https://forum.syncthing.net/

And I clearly jumped the gun at closing as duplicate of that issue. As other said, #1114 and the ever-green #2491 would have been the correct choices.
