### ISSUE TITLE
Manually Receive in Send Only Folders

### ISSUE THREAD

**Issue by steelman** [syncthing/syncthing#9329] opened 2024-01-07 10:46 UTC
I use syncthing to share a music library between my PC and my smartphone. I update the library mostly on PC, so I set it up as Send Only on PC and Receive Only on mobile. And it works great 95% of the time. I am not scared that if I accidentally remove something from my phone I will lose it on PC. From time to time, however, I download something to my phone directly and want to upload it to the PC. To do it I reconfigure the folder on the PC temporarily to be Send and Receive. And this works kind of OK (I mean it does what I expect).

The feature I envisioned would make this process easier and more controllable. Here is how it would work:

1. Prepare a Send Only folder on device A
2. Push it to device B, where the folder is configured _Send and Receive_
3. Add file (or make other changes, that may be discussed/configurable) on the device B.
4. Upon the next synchronisation show an indicator on the device A, that there is some new content (or other changes) on the device B.
5. Enable user at the device A to:

  - accept the changes altogether
  - pick individually which files and/or directories should be pulled to the device B.

Some more consideration may be needed for scenarios where more than two devices are synchronised. For example a PC and two portable devices, where changes should be shared only via the PC.

**Comment by tomasz1986** [comment] 2024-01-07 12:07
Duplicate of https://github.com/syncthing/syncthing/issues/4478.

**Closed by tomasz1986** 2024-01-07 12:07 UTC
Labels: enhancement, needs-triage
