### ISSUE TITLE
Add default ignores

### ISSUE THREAD

**Issue by gqqnbig** [syncthing/syncthing#9885] opened 2024-12-25 15:49 UTC
### Feature description

The [config file](https://docs.syncthing.net/users/config.html#config-option-defaults.ignores ) of Syncthing allows users to set default ignore patterns that will be applied to new shared folders. But Syncthing itself doesn't ship with any ignore patterns.

When Syncthing is used on Windows, for example, `desktop.ini`, `Thumbs.db`, `$RECYCLE.BIN`, `System Volume Information`, and sucklike will be synchronized and may cause errors due to permissions. Also on MacOS, users usually don't need to synchronize `DS_Store` files.

Therefore, syncthing should ship with default ignore patterns to increase user friendliness, just like Resilio Sync does.

Here I copy the default ignore patterns from Resilio Sync:

```
$RECYCLE.BIN
$Recycle.Bin
System Volume Information
ehthumbs.db
desktop.ini
Thumbs.db
lost+found
.DocumentRevisions-V100
.TemporaryItems
.fseventsd
.icloud
.iCloud
.DS_Store
.DS_Store?
.Spotlight-V100
.Trashes
.Trash-*
~*
*~
.~lock.*
*.part
*.filepart
.csync_journal.db
.csync_journal.db.tmp
*.swn
*.swp
*.swo
*.crdownload
.@__thumb
.thumbnails
._*
*.tmp
*.tmp.chck
.dropbox
.dropbox.attr
.dropbox.cache
.streams
.caches
.Statuses
.teamdrive
.SynologyWorkingDirectory
@eaDir
@SynoResource
.!@#$recycle
DfsrPrivate
```

### Problem or use case

None

### Alternatives or workarounds

None

**Comment by imsodin** [comment] 2024-12-25 16:30
Duplicate of https://github.com/syncthing/syncthing/issues/837

**Closed by imsodin** 2024-12-25 16:30 UTC
Labels: enhancement, needs-triage
