### ISSUE TITLE
More efficient sharing of subfolders, folders within other shared folders

### ISSUE THREAD

**Issue by drdozer** [syncthing/syncthing#2456] opened 2015-11-10 13:24 UTC
I have an uber syncthing directory tree that is my Documents hierarchy. It contains a mixture of stuff that needs replicating across multiple machines and backing up.

Sometimes I want to be able to have a remote folder shared into a sub-folder e.g. have my phone publish its photos as a syncthing folder, and have it replicate read-only into a sub-folder of my big directory tree. I get the impression that if I have several clones of Documents, each with the read-only folder from my phone overlayed into that tree as a syncthing folder in its own right, that the various different syncthing jobs are constantly checking up on each-other and the various clones of the folder gets polled a lot on the different machines. I'm not confident that it always does the right thing.

Other times I want to share just one sub-folder with somebody else. So I may want to set up a share for Documents/work/project3 as project3 to a collaborator. They should only see project3, and not the intervening directory structure. Ideally, any machine that has a clone of Documents could act as a source of data for a client pulling down project3.

I think both these use-cases boil down to syncthing understanding that one share is a folder nested within another share, and using this to de-duplicate book keeping and resource syncing.

**Comment by marrie** [comment] 2015-11-17 16:26
I agree sub folders should be a bit better but I just share the whole folder with someone or just that 1 folder inside of what ever and only with that person if that makes sence.

So if I have project then inside a and b, I only share a with one person and b  with another.

Hth.

**Comment by marclaporte** [comment] 2015-11-21 15:25
Is this is a duplicate of https://github.com/syncthing/syncthing/issues/1167 ?

**Comment by AudriusButkevicius** [comment] 2015-11-21 16:21
Yes

**Closed by AudriusButkevicius** 2015-11-21 16:21 UTC
Labels: enhancement
