### ISSUE TITLE
Auto recovery from 'folder path missing' race condition.

### ISSUE THREAD

**Issue by slashbeast** [syncthing/syncthing#9639] opened 2024-08-08 19:45 UTC
### Feature description

I am facing issue with Syncthing installed with Homebrew on MacOS with separated, encrypted APFS volume. It appears that Syncthing starts up as LaunchAgent before the `/Volumes/Dropzone` is automatically mounted post boot, which lead to syncthing not working until I restart it

```
[6D6JM] 2024/07/31 16:20:48 WARNING: Error on folder "music" (music-kwjhz-qmx5e): folder path missing
[6D6JM] 2024/07/31 16:20:48 INFO: Failed initial scan of sendreceive folder "camera" (camera-6jd3a-fkkea)
```

This is a difficult to deal with problem because user have no control over this behavior.

Perhaps Syncthing could have some retry logic to check if the path exist and has .stfolder there on interval? In this very case it would help automatically recovery from it.

### Problem or use case

Problem being MacOS with encrypted internal volume that is separated from main data volume and therefore mounted after login, but not before syncthing is started. That could potentially also work well for people that uses external devices with Syncthing.

### Alternatives or workarounds

`brew services restart syncthing` post login

**Comment by tomasz1986** [comment] 2024-08-08 20:00
Duplicate of https://github.com/syncthing/syncthing/issues/9457.

**Closed by tomasz1986** 2024-08-08 20:00 UTC
Labels: enhancement, needs-triage
