### ISSUE TITLE
spurious log file in $XDG_CONFIG_HOME

### ISSUE THREAD

**Issue by hydrargyrum** [syncthing/syncthing#9179] opened 2023-10-22 12:35 UTC
In default configuration

According to [spec](https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html)

> $XDG_CONFIG_HOME defines the base directory relative to which user-specific configuration files should be stored

So this file should not be there: `~/.config/syncthing/syncthing.log`

This is more suitable:

>  The $XDG_STATE_HOME contains state data that should persist between (application) restarts, but that is not important or portable enough to the user that it should be stored in $XDG_DATA_HOME. It may contain: 
> - actions history (logs, history, recently used files, …)

**Comment by hydrargyrum** [comment] 2023-10-22 12:36
(And I would add most other files in `~/.config/syncthing` should probably rather end up in `~/.local/share/syncthing`)

**Comment by acolomb** [comment] 2023-10-22 12:43
As described in #9178, I think even `$XDG_DATA_HOME` would not be the ideal placement.  Not authoritative, but https://wiki.archlinux.org/title/XDG_Base_Directory#User_directories describes it as analogous to `/usr/share`, which as the name implies, could be shared between devices.  Sharing the configuration files, e.g. device ID certificate, would be problematic though.

**Comment by hydrargyrum** [comment] 2023-10-22 12:47
So `$XDG_STATE_HOME` is more appropriate then?

**Comment by calmh** [comment] 2023-10-22 13:27
If there's a log file there it's because you manually asked for it, we don't default to using any log file on unixes.

**Comment by hholst80** [comment] 2023-10-22 15:42
@calm the XDG anti-pattern is a technical debt. I suspect we will continue to see these kind of issues reported from ST users until the issue is fixed.

There are indeed log files stored in the default installation.

![image](https://github.com/syncthing/syncthing/assets/6200749/b3d024ee-a2ed-42e9-96bb-0c4dcfd62ead)

**Comment by hholst80** [comment] 2023-10-22 15:44
> As described in #9178, I think even `$XDG_DATA_HOME` would not be the ideal placement. Not authoritative, but https://wiki.archlinux.org/title/XDG_Base_Directory#User_directories describes it as analogous to `/usr/share`, which as the name implies, could be shared between devices. Sharing the configuration files, e.g. device ID certificate, would be problematic though.

That is why there is a /usr/**local**/share on your system. XDG has a ~/.local too.

**Comment by calmh** [comment] 2023-10-22 15:51
That's an implementation detail of the leveldb database and not what the OP is talking about.

**Comment by acolomb** [comment] 2023-10-22 15:52
The XDG Base Directory Specification is not really related to the LSB Filesystem Hierarchy Standard (FHS).  In contrast to the latter, it is very vague on what goes where and what could possibly be shared between different machines.  The name `.local` MAY imply that it should be kept local to the machine, but the standard makes no such statement.  And the `share` part does suggest to me that it is intended to be shared.

Regarding the FHS and the `/usr/local/` hierarchy, the distinction is basically between stuff managed by the distribution through its package system (`/usr/`) and stuff added by the local administrator.  It has nothing to do with `~/.local/`.

**Comment by hydrargyrum** [comment] 2023-10-22 18:33
@calmh 

> If there's a log file there it's because you manually asked for it, we don't default to using any log file on unixes.

I didn't ask for this path specifically, the command run by `syncthing-start.desktop` is `syncthing […] --logfile=default`, so it **is** syncthing that selects this bogus path, not me.

**Comment by acolomb** [comment] 2023-10-22 19:19
Indeed, that's being set in our own `etc/linux-desktop/syncthing-start.desktop` file.  Should we treat it as a bug to be fixed in that file?

Anyhow, when fixing #9178, the default log file location should be moved as well.

**Comment by calmh** [comment] 2023-10-22 19:43
LOL I called it 

<img width="816" alt="Screenshot 2023-10-22 at 21 42 42" src="https://github.com/syncthing/syncthing/assets/125426/75b9a387-39e9-4031-8251-3b634569c9a2">

**Comment by calmh** [comment] 2023-10-22 19:51
For what it's worth, the current "default" apparently maps into XDG_DATA_HOME if set, so 🤷 (and this stuff predates the existence of the XDG state stuff)

**Closed** 2023-10-25 09:16 UTC
Labels: bug
