### ISSUE TITLE
Set "Minimum Free Disk Space" in MB/GB

### ISSUE THREAD

**Issue by davidak** [syncthing/syncthing#3307] opened 2016-06-15 03:31 UTC
I set "Minimum Free Disk Space" to `0,001` but still get `disk has insufficient free space`. My HDD has over 5 GB free and the Folder i want to sync has 2,4 MB of files, changes are one line in a text file.

I think the setting would make more sense to set to "1 GB" or "500 MB".

**Comment by canton7** [comment] 2016-06-15 07:00
Maybe there's some fun around parsing numbers with a localised decimal point? Try maybe '0.0001'  or just '1'

**Comment by raichu** [comment] 2016-07-05 17:51
I once pushed for this in  #2227 but it was nuked & locked because I pointed out the logical fallacy behind this broken implementation which assumes "1% your HDD is smaller than the space syncthing needs, regardless of the size of your HDD".

**Comment by calmh** [comment] 2016-07-05 19:15
So there's a lot of vitriol here that I'm not going to comment on, I just want to note that

> which defaults to a sensible value such as 1GB

is more or less the reason we don't do this, as defaulting to 1GB would be a bad idea for devices with 1 GB of flash, for example. That is, the default needs to be responsive to the device size, which ends up looking a lot like a percentage.

**Comment by calmh** [comment] 2016-07-05 19:21
No, actually I'll comment on this as well...

> It's easier to go into denial and sweep it under the rug by introducing hacky workarounds and locking to issue and forcefully silence the reporter rather than admitting that you screwed up your design choice and fixing it.

The issue you refer to was closed because it was essentially a duplicate of the previous four issues that I linked to when closing it. And no, that amount of denial, sweeping, hacking and silencing sound like a lot of work compared to admitting we're wrong and fixing it. And we do that often enough.

**Comment by davidak** [comment] 2016-07-06 08:19
>defaulting to 1GB would be a bad idea for devices with 1 GB of flash, for example.

>the default needs to be responsive to the device size

ok, yes. so why not set the default to 5% of total space in GB / MB / kB? Then the value can be easily edited without calculating it yourself.

**Comment by calmh** [comment] 2016-07-06 09:39
Yep I wouldn't be opposed to that. The downside is that it requires some dynamic figuring out the threshold at folder creation time. Pull requests welcome.

**Comment by raichu** [comment] 2016-07-07 20:18
> is more or less the reason we don't do this, as defaulting to 1GB would be a bad idea for devices with 1 GB of flash, for example. That is, the default needs to be responsive to the device size, which ends up looking a lot like a percentage.

1GB, 100MB, it doesn't matter. Make the default based on the device size. I'm talking about the way this config parameter works, *not* its default value.

You don't need to measure the free space in units of file system size in order to make the default something like minimum of, say, 100MB and 5% of total space.

**Comment by canton7** [comment] 2016-07-07 20:38
Dude, be nice. When people give you good things for free, don't be mean to them. That makes them stop wanting to give us free stuff, and everyone suffers.

I mean that in all seriousness - developing a OS project like this is a hobby. People keep doing it because it's fun. Having to deal with people who are being rude is not fun, and it takes all the fun out of everything else. Now when you're deciding what to do on your Friday night, you can either go out or deal with mean people on GitHub, and you start to think that going out seems more attractive...

**Comment by raichu** [comment] 2016-07-07 20:40
OK, then, I'm sowwy with cherry topped pretty pretty please.
Now can you please try to see the *technical* point that I'm making here rather than the subjective niceness score.

**Comment by canton7** [comment] 2016-07-07 20:47
No need to be sarcastic now :)

> change the type of MinHomeDiskFreePct from int to float64, which is was trivial workaround the issue

...

> Pull requests welcome.

**Comment by raichu** [comment] 2016-07-07 20:55
> No need to be sarcastic now :)

It wasn't meant to be sarcasm. That's literally how the issue was solved.

And in case you haven't noticed, that "Pull requests welcome." belongs to a context, which reads:

> Yep I wouldn't be opposed to that. The downside is that it requires some dynamic figuring out the threshold at folder creation time. Pull requests welcome.

On the other hand, he *is* opposed to measuring min free space in bytes, for which I'm pretty sure pull requests are *not* welcome.

**Comment by calmh** [comment] 2016-07-07 21:39
I'm going to lock this issue as well, because you clearly have an axe to grind and I'm tired of it.

Let me restate this though: I think the issue is valid, and I'll welcome a pull request to fix it. @davidak's suggestion to default to some percentage at folder creation time (e.g., one percent as we do now) and then lock that value in as a number of MB or GB and allowing it to be edited as such is perfectly fine. A pull request that implements that *is* welcome.

**Closed** 2017-04-12 09:01 UTC
Labels: easy, enhancement
