### ISSUE TITLE
Add time remaining to remote devices

### ISSUE THREAD

**Issue by spideysri2802** [syncthing/syncthing#9665] opened 2024-08-28 09:44 UTC
### Feature description

it would be nice to see time remaining in the remote devices list. this would show roughly how many minutes are left in the upload to that particular device.

### Problem or use case

currently there's no way to see how much time an upload to another device is going to take. having some rough timings would be very useful.

### Alternatives or workarounds

-

**Comment by tomasz1986** [comment] 2024-08-28 10:21
Duplicate of https://github.com/syncthing/syncthing/issues/899.

**Closed by tomasz1986** 2024-08-28 10:21 UTC
Labels: enhancement, needs-triage
