### ISSUE TITLE
CPU ressources in idle mode gets increased over time

### ISSUE THREAD

**Issue by mumpitzstuff** [syncthing/syncthing#9467] opened 2024-03-11 18:20 UTC
### What happened?

I have the issue that the needed CPU ressources are getting higher over time (just idle and no clients are connected). The bug was introduced by 1.27.2 i would say but i can not test it because i dont know how to switch back to that version (apt-get just offered 1.27.3 as oldest version to me).
Anyway if i restart syncthing and open top, i can see the cpu consumption by around 0.0% - 0.3% on my notebook (no clients connected!). A few hours later the cpu consumption is 2-3 times higher and now at 0.7% - 1.3% permanently (never goes down to 0.0% again). That may not sound like much but it is enough to increase the overall CPU temperature of my notebook by around 8°C which causes the fan to start all the time (noise).
My workaround for now is to restart the server every few hours which is not really nice somehow...

### Syncthing version

v1.27.4

### Platform & operating system

Linux Amd64

**Comment by acolomb** [comment] 2024-03-11 18:27
Duplicate of #9417. Presumably fixed in the next release.

**Closed by acolomb** 2024-03-11 18:27 UTC
Labels: bug, needs-triage
