### ISSUE TITLE
High CPU load if permission denied for .stignore

### ISSUE THREAD

**Issue by Forceu** [syncthing/syncthing#8450] opened 2022-07-26 08:41 UTC
I noticed a very high CPU load for my server, which was caused by syncthing, using all available CPU.

The reason was that I had a folder where syncthing did not have enough permission to open the .stignore file in the folder. It aborted the folder scan with the error, but then retried immediately, causing that high load.

Version: 1.19.1
OS: Ubuntu 20.04

Folder permissions (syncthing user is not owner, but in the group):

> ls -l /home/nonsyncthinguser/

```
[...]
drwxrwxrwx 3 nonsyncthinguser syncthinggroup      4096 Jul 26 08:19 kodiwatched`
```

> ls -l /home/nonsyncthinguser/kodiwatched

```
drwxrwxrwx  3 nonsyncthinguser syncthinggroup        4096 Jul 26 08:19 .
drwxr-xr-x 16 nonsyncthinguser nonsyncthinguser   4096 Jul  9 17:16 ..
[...]
drwxr-xr-x  2 nonsyncthinguser syncthinggroup        4096 Nov 26  2019 .stfolder
-rw-------  1 nonsyncthinguser syncthinggroup           0 Nov 26  2019 .stignore
```

**Comment by imsodin** [comment] 2022-07-27 15:51
Duplicate of https://github.com/syncthing/syncthing/issues/8232, fixed in v1.20.0

**Closed by imsodin** 2022-07-27 15:51 UTC
Labels: bug, needs-triage
