### ISSUE TITLE
UPnP discovery takes into account all UPnP devices

### ISSUE THREAD

**Issue by msteinmann** [syncthing/syncthing#1363] opened 2015-02-18 12:43 UTC
I have a static firewall (without UPnP) on 192.168.1.1 and a second one on 192.168.1.2 with UPnP (just sitting there, waiting to be configured). Syncthing creates a UPnP mapping on the UPnP firewall, which will never be used because .1 is the default route.

INFO: syncthing v0.10.23 (go1.4.1 darwin-amd64 default) unknown-user@syncthing-builder 2015-02-15 15:55:44 UTC
...
INFO: Starting UPnP discovery...
INFO: UPnP discovery complete (found 1 device).
INFO: Created UPnP port mapping for external port 58229 on UPnP device 'Linux Internet Gateway Device' (192.168.1.2).

UPnP should not report success if it cannot create the mapping on the default route device.

**Comment by cqcallaw** [comment] 2015-02-18 16:27
What is meant by "report success" in this context? I ask because there's (intentionally) nothing in the log file about any sort of success besides the successful creation of a port mapping. Successful creation of a port mapping implies exactly nothing about one's connection to the Internet or the global syncthing discovery network.

**Comment by msteinmann** [comment] 2015-02-18 17:00
You're right that the log is correct. But, I think that it is both useless and confusing to open ports on devices that are not in the path. I overlooked the IP address when I started Syncthing on that particular network and only later realised that it had opened-up a port on a firewall that's not in use.

**Comment by cqcallaw** [comment] 2015-02-18 18:02
Ah, that makes sense, and I can definitely see myself concluding the same thing; issues related to near-identical IP addresses can be tricky and frustrating to resolve! That said, I'm going to have to think about how to address the issue. I'm not sure ignoring all routers expect the router on the default route is going to work, because we can't assume the default route is also the route to the syncthing discovery servers.

**Comment by calmh** [comment] 2015-02-19 07:19
I'm not sure this is possible to address correctly. In any case, the simple workaround is to not have UPnP routers sitting around unless they are supposed to be used (we can't know the difference), or enable UPnP on the router that is supposed to be used. :)

**Comment by AudriusButkevicius** [comment] 2015-02-19 10:02
We have the `get gateways` code half way there, which could help us out.

**Comment by calmh** [comment] 2015-02-20 09:14
But are we sure we only want to talk to the UPnP device that happens to be our default gateway?

**Comment by cqcallaw** [comment] 2015-02-23 17:50
Detecting the default gateway ought to be possible since it's available as part of the network interface's connection information (e.g. `ifconfig` or `ipconfig /all`), but I'm definitely not convinced we only want to talk to the UPnP device that is a default gateway.

@msteinmann What was the initial failure that indicated there was a configuration issue with your network environment? What was your first clue that something wasn't working? I ask because I have some ideas about how to report this failure mode, but the manner in which the issue was discovered is going to tell me a lot about whether or not my ideas are viable.

**Comment by msteinmann** [comment] 2015-02-23 20:51
@cqcallaw no real failure as the hole got set up correctly - just not on the router that I expected. So, as @calmh pointed out, it's probably best not to have routers without full connectivity sitting around just for fun. On the other hand, it only really makes sense to poke holes where we expect to transfer data, but I'm not sure if it's worth the trouble anymore.

Maybe it would be better to inform the user in case the gateway router refused to create a UPnP mapping instead of the current message that one or more mappings have been created. The user needs to take action by manually poking a hole if UPnP was not successful.

**Comment by cqcallaw** [comment] 2015-02-25 00:04
@msteinmann Interesting, what prompted you to investigate syncthing's operation on that specific network, then? I'm assuming  _something_ unexpected must have occurred, or you wouldn't have thought to look at the log files. That "something" is what I'm like to know more about.

It definitely seems odd at first glance to poke holes in everything, but indiscriminately poking holes in every available UPnP-enabled router does maximize the probability that we'll be able to reach the syncthing services. It's well-aligned with our goal of establishing communication to the syncthing services with as little fuss as possible.

Informing the user about a router's refusal to create a UPnP mapping is fine for UPnP-enabled routers, and we should already be doing that if the port mapping process fails. It's not really possible to do the same for routers that aren't using UPnP though, because routers without UPnP won't even respond to our requests for information about how such a port mapping request should be made.

**Comment by calmh** [comment] 2015-02-25 22:10
I'm just not sure we will be able to tell correctly or easily what gateway is which. What if it's multihomed and responds from an IP that is not our default gateway (but it's still the same box)? What if you have a default router and a VPN router and want holes in both? What if your outgoing router (default gateway) is not UPnP aware, but you have a specific router that *is* just for the purpose of incoming connections?

I'm not saying these situations are necessarily handled any better today, but the current system has simplicity going for it. Making tweaks to handle a specific (corner-?) case makes me wonder what other corner cases we should also handle in that case...

**Comment by AudriusButkevicius** [comment] 2015-02-25 22:36
I agree.
I'd prefer trying to punch through at any cost (even if its wasteful), rather than not punching through at all.

**Comment by cqcallaw** [comment] 2015-03-01 18:11
Yes, I think we're all in agreement that the current method is simple and robust, and I'm definitely not suggesting we change the port mapping routines. However, I do think @msteinmann has surfaced a valid usability issue: IMO the described behavior is violates the principle of least astonishment and probably isn't what the user expects. I think it would be worthwhile to explore ways we can give the user some clue that the system may not be working as they intended.

**Comment by calmh** [comment] 2015-03-20 14:21
In my book this is working as intended - we can't know which UPnP device to avoid if it replies that it exists and can do port forwards - so I'm closing. If there's something specific we can do to improve it however, do file new tickets or reopen.

**Closed by calmh** 2015-03-20 14:21 UTC
