### ISSUE TITLE
Problem with migrating database

### ISSUE THREAD

**Issue by sargelavoie** [syncthing/syncthing#6438] opened 2020-03-21 02:17 UTC
I just updated synthing from version 1.3.4 to 1.4.0 on a raspberry pi 2, running with another rapsberry pi 4 (not updated yet), three windows 10 PCs (1.4.0 and 1.4.1). Everything was working smoothly before the update, but after that, it crashed on the raspberry pi 2 with a "out of memory" error message" (see below). The GUI do not show anymore, and checking with STTRACE=scanner didn't gave any relevant clue. 

Here is the stderr

> [start] 21:54:52 INFO: syncthing v1.4.0 "Fermium Flea" (go1.13.8 linux-arm) deb@build.syncthing.net 2020-03-06 19:52:22 UTC
> [KSDQO] 21:54:52 INFO: My ID: _blablabla_
> [KSDQO] 21:54:53 INFO: Single thread SHA256 performance is 9.2 MB/s using crypto/sha256 (9.2 MB/s using minio/sha256-simd).
> [KSDQO] 21:54:53 VERBOSE: Starting up (/home/pi/.config/syncthing)
> [KSDQO] 21:54:54 INFO: Hashing performance is 8.46 MB/s
> [KSDQO] 21:54:54 INFO:Migrating  database to schema version 9...
> fatal error: runtime: out of memory

here is the log file

> [start] 2020/03/20 22:06:38.718476 main.go:548: INFO: syncthing v1.4.0 "Fermium Flea" (go1.13.8 linux-arm) deb@build.syncthing.net 2020-03-06 19:52:22 UTC
> [KSDQO] 2020/03/20 22:06:39.169967 syncthing.go:151: INFO: My ID: blablabla
> [KSDQO] 2020/03/20 22:06:40.114781 sha256.go:87: INFO: Single thread SHA256 performance is 9.0 MB/s using minio/sha256-simd (9.0 MB/s using crypto/sha256).
> [KSDQO] 2020/03/20 22:06:40.941838 syncthing.go:183: INFO: Hashing performance is 8.37 MB/s
> [KSDQO] 2020/03/20 22:06:40.942183 schemaupdater.go:101: INFO: Migrating database to schema version 9...
> ...
> Panic at 2020-03-20T22:07:30-04:00
> fatal error: runtime: out of memory
> 
> runtime stack:
> runtime.throw(0x8837d5, 0x16)
>         /usr/local/go/src/runtime/panic.go:774 +0x5c
> runtime.sysMap(0x35800000, 0x6400000, 0x1069398)
>         /usr/local/go/src/runtime/mem_linux.go:169 +0xa8
> runtime.(*mheap).sysAlloc(0x1057b88, 0x6020000, 0x49764, 0x10526d8)
>         /usr/local/go/src/runtime/malloc.go:701 +0x184
> runtime.(*mheap).grow(0x1057b88, 0x3010, 0xffffffff)
>         /usr/local/go/src/runtime/mheap.go:1255 +0x84
> runtime.(*mheap).allocSpanLocked(0x1057b88, 0x3010, 0x10693a8, 0x1)
>         /usr/local/go/src/runtime/mheap.go:1170 +0x264
> runtime.(*mheap).alloc_m(0x1057b88, 0x3010, 0x101, 0x0)
>         /usr/local/go/src/runtime/mheap.go:1022 +0xd0
> runtime.(*mheap).alloc.func1()
>         /usr/local/go/src/runtime/mheap.go:1093 +0x3c
> runtime.(*mheap).alloc(0x1057b88, 0x3010, 0x3010101, 0x66c9e278)
>         /usr/local/go/src/runtime/mheap.go:1092 +0x60
> runtime.largeAlloc(0x601e6cf, 0x70101, 0x66c66100)
>         /usr/local/go/src/runtime/malloc.go:1138 +0x74
> runtime.mallocgc.func1()
>         /usr/local/go/src/runtime/malloc.go:1033 +0x38
> runtime.systemstack(0x30403c0)
>         /usr/local/go/src/runtime/asm_arm.s:354 +0x84
> runtime.mstart()
>         /usr/local/go/src/runtime/proc.go:1146
> 
> goroutine 1 [running]:
> runtime.systemstack_switch()
>         /usr/local/go/src/runtime/asm_arm.s:298 +0x4 fp=0x32de99c sp=0x32de998 pc=0x71674
> runtime.mallocgc(0x601e6cf, 0x79e6d0, 0x1, 0x44)
>         /usr/local/go/src/runtime/malloc.go:1032 +0x8d0 fp=0x32dea04 sp=0x32de99c pc=0x1bbb0
> runtime.makeslice(0x79e6d0, 0x5ebed72, 0x601e6cf, 0x55dc540)
>         /usr/local/go/src/runtime/slice.go:49 +0x6c fp=0x32dea18 sp=0x32dea04 pc=0x59014
> github.com/syndtr/goleveldb/leveldb.(*Batch).grow(...)
>         /root/go/pkg/mod/github.com/syndtr/goleveldb@v1.0.1-0.20190923125748-758128399b1d/leveldb/batch.go:82
> github.com/syndtr/goleveldb/leveldb.(*Batch).appendRec(0x33ae120, 0x1, 0x36d3800, 0x2f, 0x100, 0x55dc540, 0xd4, 0xd4)
>         /root/go/pkg/mod/github.com/syndtr/goleveldb@v1.0.1-0.20190923125748-758128399b1d/leveldb/batch.go:93 +0xc0 fp=0x32dea7c sp=0x32dea18 pc=0x5f50a4
> github.com/syndtr/goleveldb/leveldb.(*Batch).Put(...)
>         /root/go/pkg/mod/github.com/syndtr/goleveldb@v1.0.1-0.20190923125748-758128399b1d/leveldb/batch.go:118
> github.com/syncthing/syncthing/lib/db/backend.(*leveldbTransaction).Put(0x33ae140, 0x36d3800, 0x2f, 0x100, 0x55dc540, 0xd4, 0xd4, 0xd, 0xd)
>         /opt/tcagent/syncthing-2-work/174e136266f8a219/lib/db/backend/leveldb_backend.go:149 +0x58 fp=0x32deaa0 sp=0x32dea7c pc=0x622f38
> github.com/syncthing/syncthing/lib/db.readWriteTransaction.putFile(0xb50198, 0x33ae140, 0x66b5ace0, 0x33ae140, 0xb52788, 0x33de1f0, 0x36d3800, 0x2f, 0x100, 0x5610630, ...)
>         /opt/tcagent/syncthing-2-work/174e136266f8a219/lib/db/transactions.go:486 +0xec fp=0x32deadc sp=0x32deaa0 pc=0x64c4f0
> github.com/syncthing/syncthing/lib/db.(*schemaUpdater).updateSchemato9(0x3080728, 0x7, 0x0, 0x0)
>         /opt/tcagent/syncthing-2-work/174e136266f8a219/lib/db/schemaupdater.go:513 +0x344 fp=0x32deda4 sp=0x32deadc pc=0x637680
> github.com/syncthing/syncthing/lib/db.(*schemaUpdater).updateSchemato9-fm(0x7, 0x896169, 0x2a)
>         /opt/tcagent/syncthing-2-work/174e136266f8a219/lib/db/schemaupdater.go:437 +0x24 fp=0x32dedb8 sp=0x32deda4 pc=0x655864
> github.com/syncthing/syncthing/lib/db.(*schemaUpdater).updateSchema(0x3080728, 0x0, 0x0)
>         /opt/tcagent/syncthing-2-work/174e136266f8a219/lib/db/schemaupdater.go:102 +0x54c fp=0x32deef8 sp=0x32dedb8 pc=0x635a44
> github.com/syncthing/syncthing/lib/db.UpdateSchema(...)
>         /opt/tcagent/syncthing-2-work/174e136266f8a219/lib/db/schemaupdater.go:52
> github.com/syncthing/syncthing/lib/syncthing.(*App).startup(0x30e62c0, 0x709b0, 0x3071894)
>         /opt/tcagent/syncthing-2-work/174e136266f8a219/lib/syncthing/syncthing.go:185 +0x6ac fp=0x32df86c sp=0x32deef8 pc=0x703d70
> github.com/syncthing/syncthing/lib/syncthing.(*App).Start(0x30e62c0, 0xa41514, 0xb53770)
>         /opt/tcagent/syncthing-2-work/174e136266f8a219/lib/syncthing/syncthing.go:106 +0x1c fp=0x32df88c sp=0x32df86c pc=0x7035f4
> main.syncthingMain(0x309c380, 0x1e, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
>         /opt/tcagent/syncthing-2-work/174e136266f8a219/cmd/syncthing/main.go:641 +0x62c fp=0x32dfde8 sp=0x32df88c pc=0x70fd6c
> main.main()
>         /opt/tcagent/syncthing-2-work/174e136266f8a219/cmd/syncthing/main.go:381 +0x380 fp=0x32dffa4 sp=0x32dfde8 pc=0x70d780
> runtime.main()
>         /usr/local/go/src/runtime/proc.go:203 +0x208 fp=0x32dffe4 sp=0x32dffa4 pc=0x43458
> runtime.goexit()
>         /usr/local/go/src/runtime/asm_arm.s:868 +0x4 fp=0x32dffe4 sp=0x32dffe4 pc=0x733ac
> 
> goroutine 35 [syscall]:
> os/signal.signal_recv(0x0)
>         /usr/local/go/src/runtime/sigqueue.go:147 +0x130
> os/signal.loop()
>         /usr/local/go/src/os/signal/signal_unix.go:23 +0x14
> created by os/signal.init.0
>         /usr/local/go/src/os/signal/signal_unix.go:29 +0x30
> 
> goroutine 36 [chan receive]:
> github.com/syncthing/notify.(*nonrecursiveTree).dispatch(0x309f240, 0x309f1c0)
>         /root/go/pkg/mod/github.com/syncthing/notify@v0.0.0-20190709140112-69c7a957d3e2/tree_nonrecursive.go:36 +0x94
> created by github.com/syncthing/notify.newNonrecursiveTree
>         /root/go/pkg/mod/github.com/syncthing/notify@v0.0.0-20190709140112-69c7a957d3e2/tree_nonrecursive.go:29 +0xb8
> 
> goroutine 37 [chan receive]:
> github.com/syncthing/notify.(*nonrecursiveTree).internal(0x309f240, 0x309f200)
>         /root/go/pkg/mod/github.com/syncthing/notify@v0.0.0-20190709140112-69c7a957d3e2/tree_nonrecursive.go:81 +0x34
> created by github.com/syncthing/notify.newNonrecursiveTree
>         /root/go/pkg/mod/github.com/syncthing/notify@v0.0.0-20190709140112-69c7a957d3e2/tree_nonrecursive.go:30 +0xdc
> 
> goroutine 40 [select]:
> github.com/syncthing/syncthing/lib/events.(*logger).serve(0x309fc80, 0xb4bfd0, 0x31f2900)
>         /opt/tcagent/syncthing-2-work/174e136266f8a219/lib/events/events.go:276 +0xec
> github.com/syncthing/syncthing/lib/util.AsService.func1(0xb4bfd0, 0x31f2900, 0x302b580, 0x0)
>         /opt/tcagent/syncthing-2-work/174e136266f8a219/lib/util/utils.go:183 +0x2c
> github.com/syncthing/syncthing/lib/util.(*service).Serve(0x30bae10)
>         /opt/tcagent/syncthing-2-work/174e136266f8a219/lib/util/utils.go:247 +0x124
> created by main.syncthingMain
>         /opt/tcagent/syncthing-2-work/174e136266f8a219/cmd/syncthing/main.go:561 +0x230
> 
> goroutine 41 [select]:
> github.com/syndtr/goleveldb/leveldb/util.(*BufferPool).drain(0x30e7080)
>         /root/go/pkg/mod/github.com/syndtr/goleveldb@v1.0.1-0.20190923125748-758128399b1d/leveldb/util/buffer_pool.go:206 +0xe8
> created by github.com/syndtr/goleveldb/leveldb/util.NewBufferPool
>         /root/go/pkg/mod/github.com/syndtr/goleveldb@v1.0.1-0.20190923125748-758128399b1d/leveldb/util/buffer_pool.go:237 +0x128
> 
> goroutine 42 [select]:
> github.com/syndtr/goleveldb/leveldb.(*session).refLoop(0x30d2960)
>         /root/go/pkg/mod/github.com/syndtr/goleveldb@v1.0.1-0.20190923125748-758128399b1d/leveldb/session_util.go:189 +0x368
> created by github.com/syndtr/goleveldb/leveldb.newSession
>         /root/go/pkg/mod/github.com/syndtr/goleveldb@v1.0.1-0.20190923125748-758128399b1d/leveldb/session.go:93 +0x228
> 
> goroutine 6 [select]:
> github.com/syndtr/goleveldb/leveldb.(*DB).compactionError(0x342c000)
>         /root/go/pkg/mod/github.com/syndtr/goleveldb@v1.0.1-0.20190923125748-758128399b1d/leveldb/db_compaction.go:91 +0x88
> created by github.com/syndtr/goleveldb/leveldb.openDB
>         /root/go/pkg/mod/github.com/syndtr/goleveldb@v1.0.1-0.20190923125748-758128399b1d/leveldb/db.go:148 +0x2f0
> 
> goroutine 7 [select]:
> github.com/syndtr/goleveldb/leveldb.(*DB).mpoolDrain(0x342c000)
>         /root/go/pkg/mod/github.com/syndtr/goleveldb@v1.0.1-0.20190923125748-758128399b1d/leveldb/db_state.go:101 +0xac
> created by github.com/syndtr/goleveldb/leveldb.openDB
>         /root/go/pkg/mod/github.com/syndtr/goleveldb@v1.0.1-0.20190923125748-758128399b1d/leveldb/db.go:149 +0x30c
> 
> goroutine 8 [select]:
> github.com/syndtr/goleveldb/leveldb.(*DB).tCompaction(0x342c000)
>         /root/go/pkg/mod/github.com/syndtr/goleveldb@v1.0.1-0.20190923125748-758128399b1d/leveldb/db_compaction.go:836 +0x1bc
> created by github.com/syndtr/goleveldb/leveldb.openDB
>         /root/go/pkg/mod/github.com/syndtr/goleveldb@v1.0.1-0.20190923125748-758128399b1d/leveldb/db.go:155 +0x40c
> 
> goroutine 9 [select]:
> github.com/syndtr/goleveldb/leveldb.(*DB).mCompaction(0x342c000)
>         /root/go/pkg/mod/github.com/syndtr/goleveldb@v1.0.1-0.20190923125748-758128399b1d/leveldb/db_compaction.go:773 +0x110
> created by github.com/syndtr/goleveldb/leveldb.openDB
>         /root/go/pkg/mod/github.com/syndtr/goleveldb@v1.0.1-0.20190923125748-758128399b1d/leveldb/db.go:156 +0x428
> 
> goroutine 10 [select]:
> github.com/syncthing/syncthing/lib/db.(*Lowlevel).gcRunner(0x307c4b0)
>         /opt/tcagent/syncthing-2-work/174e136266f8a219/lib/db/lowlevel.go:504 +0x19c
> created by github.com/syncthing/syncthing/lib/db.NewLowlevel
>         /opt/tcagent/syncthing-2-work/174e136266f8a219/lib/db/lowlevel.go:68 +0x198
> 
> goroutine 12 [chan receive]:
> main.setupSignalHandling.func1(0x309e7c0, 0x30e62c0)
>         /opt/tcagent/syncthing-2-work/174e136266f8a219/cmd/syncthing/main.go:669 +0x24
> created by main.setupSignalHandling
>         /opt/tcagent/syncthing-2-work/174e136266f8a219/cmd/syncthing/main.go:668 +0x94
> 
> goroutine 43 [chan receive]:
> main.setupSignalHandling.func2(0x309e880, 0x30e62c0)
>         /opt/tcagent/syncthing-2-work/174e136266f8a219/cmd/syncthing/main.go:678 +0x24
> created by main.setupSignalHandling
>         /opt/tcagent/syncthing-2-work/174e136266f8a219/cmd/syncthing/main.go:677 +0x128
> 
> goroutine 44 [sleep]:
> runtime.goparkunlock(...)
>         /usr/local/go/src/runtime/proc.go:310
> time.Sleep(0x540be400, 0x2)
>         /usr/local/go/src/runtime/time.go:105 +0x158
> main.standbyMonitor(0x30e62c0)
>         /opt/tcagent/syncthing-2-work/174e136266f8a219/cmd/syncthing/main.go:757 +0x48
> created by main.syncthingMain
>         /opt/tcagent/syncthing-2-work/174e136266f8a219/cmd/syncthing/main.go:613 +0x76c
> 
> goroutine 21 [chan receive]:
> github.com/syncthing/syncthing/lib/events.(*bufferedSubscription).pollingLoop(0x33b6090)
>         /opt/tcagent/syncthing-2-work/174e136266f8a219/lib/events/events.go:467 +0x6c
> created by github.com/syncthing/syncthing/lib/events.NewBufferedSubscription
>         /opt/tcagent/syncthing-2-work/174e136266f8a219/lib/events/events.go:462 +0x130
> 
> goroutine 46 [select]:
> github.com/thejerf/suture.(*Supervisor).Serve(0x3198000)
>         /root/go/pkg/mod/github.com/thejerf/suture@v3.0.2+incompatible/supervisor.go:454 +0x270
> created by github.com/thejerf/suture.(*Supervisor).ServeBackground
>         /root/go/pkg/mod/github.com/thejerf/suture@v3.0.2+incompatible/supervisor.go:407 +0x2c
> 
> goroutine 22 [chan receive]:
> github.com/syncthing/syncthing/lib/events.(*bufferedSubscription).pollingLoop(0x33b60f0)
>         /opt/tcagent/syncthing-2-work/174e136266f8a219/lib/events/events.go:467 +0x6c
> created by github.com/syncthing/syncthing/lib/events.NewBufferedSubscription
>         /opt/tcagent/syncthing-2-work/174e136266f8a219/lib/events/events.go:462 +0x130
>

**Comment by calmh** [comment] 2020-03-21 08:41
The 1.4.1 RC fixes high memory usage on migration, you might try that one.

**Comment by imsodin** [comment] 2020-03-21 10:52
duplicate of https://github.com/syncthing/syncthing/issues/6422

**Closed by imsodin** 2020-03-21 10:52 UTC
