### ISSUE TITLE
Systemd status=217/USER when starting as www-data

### ISSUE THREAD

**Issue by zguithues** [syncthing/syncthing#4234] opened 2017-06-28 16:48 UTC
Previous working version: v0.14.29

### Issue 
I upgraded to version 0.14.31 via official repository.  After upgrade, syncthing failed to start.

### Description
- I used the systemd system service with the www-data user.
- I had hand edited the syncthing@.service file to include the "-home=/opt/syncthing-config" option.  I realize i should have copied the service file to avoid an overwrite upon update.
- When i upgraded to v0.14.31 my syncthing@.service file was replaced with stock.
- I disabled the @www-data service, copied the syncthing@.service file, made my edit adding the -home option, enabled @www-data service with new file, syncthing does not start.

When googling, i found references to the error: status=217/USER as an issue with usernames with dashes.

> "Your unit file is probably wrong and uses %I instead of %i for the User. Dashes are treated as escaped slashes, so using %I means it'll be unescaped to test/user, which doesn't exist (and yields the failure)."
- https://bugs.archlinux.org/task/37755

However, the file correctly uses "%i", so i'm not certain if these issues are related.

It could have also been another program that updated.  Here is the list:

`Upgrade: lxc-common:amd64 (2.0.7-0ubuntu1~16.04.2, 2.0.8-0ubuntu1~16.04.2), cloud-init:amd64 (0.7.9-113-g513e99e0-0ubuntu1~16.04.1, 0.7.9-153-g16a7302f-0ubuntu1~16.04.1),uuid-runtime:amd64 (2.27.1-6ubuntu3.2, 2.27.1-6ubuntu3.3), libfdisk1:amd64 (2.27.1-6ubuntu3.2, 2.27.1-6ubuntu3.3), openssl:amd64 (1.0.2g-1ubuntu4.6, 1.0.2g-1ubuntu4.8),syncthing:amd64 (0.14.29, 0.14.31), grub-common:amd64 (2.02~beta2-36ubuntu3.9, 2.02~beta2-36ubuntu3.11), libmount1:amd64 (2.27.1-6ubuntu3.2, 2.27.1-6ubuntu3.3),vlan:amd64 (1.9-3.2ubuntu1.16.04.1, 1.9-3.2ubuntu1.16.04.3), util-linux:amd64 (2.27.1-6ubuntu3.2, 2.27.1-6ubuntu3.3), grub2-common:amd64 (2.02~beta2-36ubuntu3.9, 2.02~beta2-36ubuntu3.11),grub-legacy-ec2:amd64 (0.7.9-113-g513e99e0-0ubuntu1~16.04.1, 0.7.9-153-g16a7302f-0ubuntu1~16.04.1), grub-pc:amd64 (2.02~beta2-36ubuntu3.9, 2.02~beta2-36ubuntu3.11),lxd:amd64 (2.0.9-0ubuntu1~16.04.2, 2.0.10-0ubuntu1~16.04.1), mount:amd64 (2.27.1-6ubuntu3.2, 2.27.1-6ubuntu3.3), liblxc1:amd64 (2.0.7-0ubuntu1~16.04.2, 2.0.8-0ubuntu1~16.04.2),grub-pc-bin:amd64 (2.02~beta2-36ubuntu3.9, 2.02~beta2-36ubuntu3.11), libblkid1:amd64 (2.27.1-6ubuntu3.2, 2.27.1-6ubuntu3.3), libuuid1:amd64 (2.27.1-6ubuntu3.2, 2.27.1-6ubuntu3.3),libsmartcols1:amd64 (2.27.1-6ubuntu3.2, 2.27.1-6ubuntu3.3), bsdutils:amd64 (1:2.27.1-6ubuntu3.2, 1:2.27.1-6ubuntu3.3), btrfs-tools:amd64 (4.4-1, 4.4-1ubuntu1),lxd-client:amd64 (2.0.9-0ubuntu1~16.04.2, 2.0.10-0ubuntu1~16.04.1), less:amd64 (481-2.1ubuntu0.1, 481-2.1ubuntu0.2), libssl1.0.0:amd64 (1.0.2g-1ubuntu4.6, 1.0.2g-1ubuntu4.8)`

The only added repositories are syncthing & certbot (for letsencrypt)

### Logs

The following repeats in: journalctl:
```
Jun 28 12:43:30 MYDOMAIN systemd[1]: syncthingZ@www-data.service: Main process exited, code=exited, status=217/USER
Jun 28 12:43:30 MYDOMAIN  systemd[1]: syncthingZ@www-data.service: Unit entered failed state.
Jun 28 12:43:30 MYDOMAIN  systemd[1]: syncthingZ@www-data.service: Failed with result 'exit-code'.
Jun 28 12:43:31 MYDOMAIN  systemd[1]: syncthingZ@www-data.service: Service hold-off time over, scheduling restart.
Jun 28 12:43:31 MYDOMAIN  systemd[1]: Stopped Syncthing - Open Source Continuous File Synchronization for www-data.
Jun 28 12:43:31 MYDOMAIN  systemd[1]: Started Syncthing - Open Source Continuous File Synchronization for www-data.
Jun 28 12:43:31 MYDOMAIN  systemd[3491]: syncthingZ@www-data.service: Failed at step USER spawning /usr/bin/syncthing: No such process
```

Output from: service syncthingZ@www-data status
```
● syncthingZ@www-data.service - Syncthing - Open Source Continuous File Synchronization for www-data
   Loaded: loaded (/lib/systemd/system/syncthingZ@.service; enabled; vendor preset: enabled)
   Active: inactive (dead) (Result: exit-code) since Wed 2017-06-28 12:43:31 EDT; 1min 19s ago
     Docs: man:syncthing(1)
  Process: 3491 ExecStart=/usr/bin/syncthing -home=/opt/syncthing-config -paths -no-browser -no-restart -logflags=3 -logfile=/opt/syncthing-config/log.txt (code=exited, status=217/USER)
 Main PID: 3491 (code=exited, status=217/USER)

Jun 28 12:43:31 MYDOMAIN  systemd[1]: syncthingZ@www-data.service: Service hold-off time over, scheduling restart.
Jun 28 12:43:31 MYDOMAIN  systemd[1]: Stopped Syncthing - Open Source Continuous File Synchronization for www-data.
Jun 28 12:43:31 MYDOMAIN  systemd[1]: syncthingZ@www-data.service: Start request repeated too quickly.
Jun 28 12:43:31 MYDOMAIN  systemd[1]: Failed to start Syncthing - Open Source Continuous File Synchronization for www-data.
```

I'm not certain where else to look.  Hopefully somebody has an idea...

### Version Information

Syncthing Version: v0.14.31
OS Version: Ubuntu 16.04
Browser Version: N/A

**Comment by calmh** [comment] 2017-06-28 17:07
> Dashes are treated as escaped slashes

![1rnsif](https://user-images.githubusercontent.com/125426/27650339-eab42062-5c34-11e7-8e72-bef9b6ba8d77.jpg)

I have nothing more to add there, no idea what's going on.

**Comment by zguithues** [comment] 2017-06-28 17:11
The issue does seem to be related to the dash in "www-data"

I created a new user "syncthing", copied the config dir & set ownership, edited my custom syncthing@.service to point to copied config dir, enabled the syncthingZ@syncthing service, and syncthing starts!

my reasoning in using www-data was because syncthing was sharing data with nextcloud, which is running under apache2.  It was a shortcut to avoid having to deal with permission issues.  I will just make this work using the user syncthing for my needs.

Hopefully whatever caused this issue to crop up gets resolved soon, but at least others will be able to find this issue if/when they have the same problem.

**Comment by calmh** [comment] 2017-06-28 17:12
I retitled, leaving for someone who uses systemd voluntarily to figure out what if anything we've done wrong.

**Comment by zguithues** [comment] 2017-06-28 17:30
Cool, thanks!

my guess is that this is actually caused by something else in the ubuntu repositories, so either it will get fixed upstream quickly, or people will start to have this issue in lots of systemd services.

What do you use to start automatically on linux? supervisord?
I've never used supervisord, but i may look into it if i can't get the permissions to work...

**Comment by calmh** [comment] 2017-06-28 17:39
`runit` or `daemontools` typically, both of which simply run a `run` script and restarts it when it exits, so very easy to work with.

**Comment by AudriusButkevicius** [comment] 2017-06-28 17:45
Should we not close this? What is there to fix?

**Comment by calmh** [comment] 2017-06-28 19:57
I don't know, I think someone should figure out what the problem is and then we can see if it's a misconfiguration on the user side or if we should tweak something.

**Comment by AudriusButkevicius** [comment] 2017-06-28 20:13
I suspect the user needs to enable the service for `www\-data`

**Comment by zguithues** [comment] 2017-06-28 23:12
I will try that tomorrow @AudriusButkevicius and report back.

**Comment by calmh** [comment] 2017-07-02 20:08
Closing as ESYSTEMD

**Closed by calmh** 2017-07-02 20:08 UTC
