### ISSUE TITLE
Filesystem watching failed when parent folder is not listable

### ISSUE THREAD

**Issue by gdlmx** [syncthing/syncthing#5609] opened 2019-03-21 05:41 UTC
### The problem

On windows, if any of the ancestor folders of a monitored folder is not listable (i.e., the "List Folder" permission is unset), the file system watcher will fail. In the verbose log there are these messages:

```
[VK627] 15:17:59 VERBOSE: FolderWatchStateChanged events.Event{SubscriptionID:26, GlobalID:26, Time:time.Time{wall:0xbf1ce1fdcebe16cc, ext:1632000601, loc:(*time.Location)(0x1463440)}, Type:33554432, Data:map[string]interface {}{"folder":"maa2q-yxpwp", "to":"Access is denied."}}
[VK627] 15:18:05 VERBOSE: Summary for folder "maa2q-yxpwp" is map[errors:0 globalBytes:0 globalDeleted:0 globalDirectories:0 globalFiles:0 globalSymlinks:0 globalTotalItems:0 inSyncBytes:0 inSyncFiles:0 localBytes:0 localDeleted:0 localDirectories:0 localFiles:0 localSymlinks:0 localTotalItems:0 needBytes:0 needDeletes:0 needDirectories:0 needFiles:0 needSymlinks:0 needTotalItems:0 pullErrors:0 sequence:0 state:idle version:0 watchError:Access is denied.]
```

The "Watch Error: Access is denied" message will finally appear on the GUI webpage.

I am working in a multi-user workstation where fine-grained ACLs are configured by the administrator. It's common to have a folder structure like "C:\secret_agents\007" where I own the "007" folder but cannot list the parent folder, "secret_agent". 
Older versions of Syncthing (<= 0.14.49) worked fine with such ACL settings but the above error starts to appear when I update syncthing to newer versions (>= 1.0).

### Environments

- Syncthing Version: v1.1.0
- OS Version: Windows 10 and 7
- File system: NTFS

### Steps to reproduce

1. Create a folder `C:\parent\child` and configure Syncthing to monitor it.
2. In the access control list (ACL) of folder `C:\parent` , unset the "List Folder" permission and keep the "Traverse Folder" permission allowed.
3. Enable all permissions for folder `C:\parent\child`.
4. Restart Syncthing.

**Comment by AudriusButkevicius** [comment] 2019-03-21 07:36
That's how permissions work, nothing todo with syncthing.

**Comment by gdlmx** [comment] 2019-03-21 08:05
Could you elaborate to explain why the older version (<1.0) didn't require those permissions? The old watcher in version 0.14.49 has been working perfectly fine *without* the "List folder" permission in any ancestor directory.

**Comment by calmh** [comment] 2019-03-21 08:59
Did the watcher actually *watch* or did it just not complain? If it actually did watch for changes successfully this sounds like a genuine issue, although one on a dependency of our (the watching package).

**Comment by AudriusButkevicius** [comment] 2019-03-21 08:59
Perhaps @imsodin can comment, but my money is that it was caused by a change in go, as I don't think watching was touched for a while.

**Comment by gdlmx** [comment] 2019-03-21 09:20
According to the log message, I can pin down the error to [this line of code](https://github.com/syncthing/syncthing/blob/03d0f0dc340764b95112080471b28414ef6cff3b/lib/model/folder.go#L357)

    eventChan, err := f.Filesystem().Watch(".", ignores, ctx, f.IgnorePerms)

which probably goes down to [basicfs_watch](https://github.com/syncthing/syncthing/blob/03d0f0dc340764b95112080471b28414ef6cff3b/lib/fs/basicfs_watch.go#L49):

    err = notify.Watch(filepath.Join(absName, "..."), backendChan, eventMask)

Therefore the problem might be introduced by recent modification to the [syncthing/notify](https://github.com/syncthing/notify/commits/master) codes. There have been 20 commits since the release of version 0.14.49.

I don't have a development environment to further analyze the error. It would be easier for you to pin it down in a debugger.

**Comment by gdlmx** [comment] 2019-03-21 09:28
@calmh The older version of syncthing did watch for changes successfully. I've been using it for 6 months. Any file modification event is usually detected in seconds although the re-scanning period is set to 1 hour.

**Comment by AudriusButkevicius** [comment] 2019-03-21 09:42
I guess this has some merit to it, but I suspect the `...` is necessery

**Comment by imsodin** [comment] 2019-03-21 11:31
>     1. Create a folder `C:\parent\child` and configure Syncthing to monitor it.
> 
>     2. In the access control list (ACL) of folder `C:\parent` , unset the "List Folder" permission and keep the "Traverse Folder" permission allowed.
> 
>     3. Enable all permissions for folder `C:\parent\child`.

I understand this such, that the folder root directory is `C:\parent\child` and the directory without the "List folder" permission is `C:\parent`, i.e. a parent of the root. I don't see how that is possible, as the watcher library only operates below the folder root, i.e. should never list the contents of `C:\parent`. Could you please double check this please.

Also if you can run a few Syncthing version between 0.14.49 and 1.0.0  to further narrow down the moment in which the behaviour changed, that would be very helpful.

**Comment by gdlmx** [comment] 2019-03-21 15:25
## Test setup
I've setup the folder permission using the following script

```
icacls C:\parent /grant:r syncuser:(X)
icacls C:\parent\child /grant:r syncuser:(OI)(CI)(M)
icacls C:\parent /inheritance:d
icacls C:\parent /remove:g Users
icacls C:\parent /remove:g "Authenticated Users"
```
where `syncuser` is the user who runs Syncthing. 



## Results

### Version 0.14.49

File watcher works normally.
<img src="https://user-images.githubusercontent.com/8292110/54762555-a5f65b00-4bf4-11e9-982d-f519792a083e.png" width="300">


### Version 0.14.50

File watcher fails to start.
<img src="https://user-images.githubusercontent.com/8292110/54762699-de963480-4bf4-11e9-80ce-439fdf8b240c.png" width="300">

### Version 1.1.0

File watcher fails to start.
<img src="https://user-images.githubusercontent.com/8292110/54762730-f077d780-4bf4-11e9-912b-70b61c1eb982.png" width="300">

**Comment by gdlmx** [comment] 2019-03-21 15:34
Probably commit [c2ff49](https://github.com/syncthing/syncthing/commit/c2ff49ed436614cc0a6a0332bd1f3fa63b608a0d#diff-e532ba17c62ef31e448d9f2a775d20f2) accidentally introduced this problem, because it refactored lots of codes in the `fs` (FileSystem) package.

**Comment by imsodin** [comment] 2019-03-21 16:22
Ah yep, I forgot about the symlink handling business - thanks for the thorough debugging!  
I can't be entirely sure, but I'd bet the error comes from `filepath.EvalSymlink` on your root path (which was introduced in that commit, but not accidentally). That performs all kinds of magic on all parents, so I guess some of that requires the missing permission. Unfortunately I don't see a way around this, as evaluating potential symlinks is required to be able to use the paths reported by the notify library (which are evaluated too) - see https://github.com/syncthing/syncthing/issues/5043, which was fixed by https://github.com/syncthing/syncthing/commit/c2ff49ed436614cc0a6a0332bd1f3fa63b608a0d.

To check my hypothesis you could run the following script: https://gist.github.com/imsodin/b1bfc8a17180404cfcc3ef4da1107c7b (`go run notifyWinSym.go`).

**Comment by gdlmx** [comment] 2019-03-21 17:37
I've run your script and both lines fail with "access denied" error.
That confirms your theory: The error does come from [EvalSymlinks](https://github.com/syncthing/syncthing/blob/73fa7a6e5bdbfdda8f988625b016db5eef4e6672/lib/fs/basicfs_windows.go#L215).

**Comment by gdlmx** [comment] 2019-03-21 17:49
In version 0.14.49 you also called [`EvalSymlinks`](https://github.com/syncthing/syncthing/blob/6b82538e623feb4df2bef9fc4b37d581de96309a/lib/fs/basicfs.go#L56). There, if an error occurs, the `root` path is used instead. So the watcher can continue to work.

	rootSymlinkEvaluated, err := filepath.EvalSymlinks(root)
	if err != nil {
		rootSymlinkEvaluated = root
         }

Is it possible to restore this nice old behavior?

**Comment by AudriusButkevicius** [comment] 2019-03-21 17:50
That's the wrong thing to do however, so I'd say no.

**Comment by imsodin** [comment] 2019-03-21 17:52
Nope, because it wasn't nice at all, it resulted in panics: https://github.com/syncthing/syncthing/issues/5043

There would have to be another workaround and/or diving into `filepath.EvalSymlinks` to find the root cause (in the hopes that it can be circumvented). I must admit I don't see a workaround and am not much inclined to invest time into any diving.

**Closed** 2019-03-21 17:56 UTC
