### ISSUE TITLE
Adding multiple folders on the same path

### ISSUE THREAD

**Issue by DirtYiCE** [syncthing/syncthing#1960] opened 2015-06-16 11:53 UTC
I've accidentally managed to add two different shared folder to the same path on one of my machines. Instead of erroring out, or something like that, it just silently merged the two folders together.

Os: gentoo linux hardened, amd64; syncthing 0.11.5. Other machines: gentoo linux amd64, syncthing 0.11.1, 0.11.8.

**Comment by calmh** [comment] 2015-06-16 12:41
I'm undecided whether this is a bug or a feature. There may be legitimate reasons to do this; particularly if one of the duplicate folders is set to be master and the other one isn't...

**Comment by AudriusButkevicius** [comment] 2015-06-16 12:57
I don't understand the silently merged part though.

**Comment by DirtYiCE** [comment] 2015-06-16 13:00
@AudriusButkevicius: it means if I had files a, b, c in folder x, and d, e, f in folder y, after pointing x and y to the same path on a computer I ended up with files a, b, c, d, e, f in both shared folders.

**Comment by Zillode** [comment] 2015-06-20 12:06
That's the intended behaviour of syncing folders that already contain data. I also think we should not limit users of configuring their own setup.
However, I think adding a dialog 'This path is already used for folder x, are you sure this is intentional?' would be useful.

**Comment by sisu4syncthing** [comment] 2015-06-20 13:42
"However, I think adding a dialog 'This path is already used for folder x, are you sure this is intentional?' would be useful."
+1

**Comment by IanOliver** [comment] 2015-06-20 22:27
@calmh While using the same directory for two Syncthing folders might not be an obvious thing to do, it does have its uses with the current way Syncthing works.

I'm using it so that I have one folder on my machine (let's call it machine A) shared with other machines (let's say B and C) - we all have read-write access (there is no master) and we all make changes regularly.

However, a separate machine (D) can only have read-only access. In which case, I can't use the master feature (that would mess up B and C machines that need to be able to make changes). So instead, I've setup second Syncthing folder using the same directory, marked A as the master, then shared the second folder with D.

For now, it gets around there being no option to mark another device(s) specifically as having read-only access while also allowing others read-write access.

I think @Zillode's suggestion of prompting the user to confirm in the event of using the same directory would work quite well.

**Comment by DavidOliver** [comment] 2015-06-20 22:38
> That's the intended behaviour of syncing folders that already contain data. I also think we should not limit users of configuring their own setup.
> However, I think adding a dialog 'This path is already used for folder x, are you sure this is intentional?' would be useful.

+1.

**Comment by Dr-Terrible** [comment] 2015-06-22 07:59
> "However, I think adding a dialog 'This path is already used for folder x, are you sure this is intentional?' would be useful."

:+1:

**Comment by AudriusButkevicius** [comment] 2016-08-21 12:42
I believe we give a red warnin already, hence closing.

**Closed by AudriusButkevicius** 2016-08-21 12:42 UTC
Labels: easy, enhancement
