### ISSUE TITLE
Populate ignore list during shared folder creation, to avoid useless indexing

### ISSUE THREAD

**Issue by napseis** [syncthing/syncthing#3845] opened 2016-12-27 19:26 UTC
hi,

I would like to make a suggestion.
When you create a shared folder, it is currently not possible to define an exclusion list before validating. Hence, the indexing starts by default in the whole folder, and continues while your go back to the folder setting and populate the exclusion list. It's problematic, for example, when you want to exclude the "#recycle" folder inside a Synology NAS, which may contains huge amount of files.

Would it be easy/possible to have access to the ignore list directly during the definition of the shared folder ?

Thanks !

### Version Information

Syncthing Version: all
OS Version: All

**Comment by AudriusButkevicius** [comment] 2016-12-28 02:41
I think there already exists an issue for this, but I am not in a position to find it over a phone so letting it live

**Comment by ProactiveServices** [comment] 2016-12-28 05:48
Dupe of issue #3608

**Closed** 2016-12-28 09:37 UTC

**Comment by napseis** [comment] 2016-12-28 09:53
Hi,
I swear I used the search feature in github, didn't find anything similar. I just checked again now and found the dupe.... 
Sorry guys.
