### ISSUE TITLE
ARMv5 (GoFlex Home) "Unknown" Folder Status, No Sync

### ISSUE THREAD

**Issue by nwcatalyst** [syncthing/syncthing#3685] opened 2016-10-23 17:15 UTC
I successfully installed syncthing on my GoFlex Home (Arch) and Windows 10 desktop. The Windows machine has finished indexing several folders with lots of data and files, and I was able to share the folders with the GFH just fine. However, no sync is taking place, and the folders report an "unknown" status. I've tried changing the rescan interval and manually rescanning the folders. Permissions appear to be correct on the GFH. 

The GFH is not a powerful machine, however the RAM and CPU usage don't seem to indicate that hardware specs are the issue with this...

I expected the GFH to begin to sync the files from each folder listed on the Windows machine. Screenshots are below, GFH first, then Windows.

### Version Information

Syncthing Version: v0.14.9, Linux (ARM)

![image](https://cloud.githubusercontent.com/assets/14971927/19628009/6264563a-9909-11e6-8d63-52ae59c7d726.png)

![image](https://cloud.githubusercontent.com/assets/14971927/19628017/7ad857fc-9909-11e6-8bc4-51d967629d42.png)

**Comment by uok** [comment] 2016-10-23 19:51
It seems your devices are not connected. Please close this issue and use the [forum ](https://forum.syncthing.net/ )for support.

**Closed** 2016-10-24 03:03 UTC

**Comment by 5chdn** [comment] 2016-11-03 09:31
> no sync is taking place, and the folders report an "unknown" status.

@nwcatalyst Having the same issue on multiple platforms with multiple devices which are supposed to sync > 100GB of data. Did you find any solution yet?

> It seems your devices are not connected.

@uok no. the issue is way earlier. In the screenshot above you see that there isn't _any_ status on the device list. It does neither say _connected_ nor _disconnected_. I always have that when my syncthing randomly stops working. But I have no clue why, and it's a very annoying issue, the `--verbose` log just stops at some point without any messages allowing any conclusion.

I also tried to `--reset` the client, but it was only taking a few hours before the client was stuck again in the same state as described by @nwcatalyst above.

**Comment by canton7** [comment] 2016-11-03 09:44
Sounds like the deadlock issue - search the forum.

**Comment by 5chdn** [comment] 2016-11-03 09:47
thanks for the hint. #3634
