### ISSUE TITLE
Lots of pull: no available source device

### ISSUE THREAD

**Issue by canton7** [syncthing/syncthing#2043] opened 2015-07-09 19:21 UTC
Syncthing 1.0.26. I'm seeing lots of 'pull: no available source device' when attempting to fetch a single file from another device.

That other device is online, and has the file in question. I've tried restarting both sides, to no avail.

I set `STTRACE=model,versioner`, and a representative snippet from the resulting log is here: http://pastebin.com/zJCkGK35

Thanks!

**Comment by calmh** [comment] 2015-07-10 06:03
Generally speaking this means the data being requested is not available, or the returned data didn't match the expected hash. I added b78c515 to clarify this in debug output. Possibly the contents of that file have changed but the modification time has not - that would explain "wrong" data being returned and then this error (as no other device has the data on offer). If that's the case, updating the time stamp on the file and doing a rescan on that side would solve it. If not, the debug output above may clarify things...

**Comment by canton7** [comment] 2015-07-10 07:18
Hmm, that file is new to the source device, and doesn't yet exist on the other device. If it's relevant, it was synced to the source device from another device originally (while the device that's currently trying to fetch it was offline).

I tried touching/rescanning, but that made no difference. I'll wait for b78c515724ed6fd5d2bfcd88d639f7dc2057a56c to be released then update this issue.

**Comment by AudriusButkevicius** [comment] 2015-07-10 07:34
Can you get the /file call output aswell from both sides?

**Comment by canton7** [comment] 2015-07-11 12:09
Output of `/rest/db/file` for that file. 

```
{
   "availability":[
   ],
   "global":{
      "flags":"0644",
      "localVersion":74954,
      "modified":"2008-04-19T23:27:48Z",
      "name":"Red Hot Chili Peppers/Live in Hyde Park Disc 2/05. Californication.mp3",
      "numBlocks":50,
      "size":6426901,
      "version":[
         "8746329750173916178:1"
      ]
   },
   "local":{
      "flags":"0644",
      "localVersion":74954,
      "modified":"2008-04-19T23:27:48Z",
      "name":"Red Hot Chili Peppers/Live in Hyde Park Disc 2/05. Californication.mp3",
      "numBlocks":50,
      "size":6426901,
      "version":[
         "8746329750173916178:1"
      ]
   }
}
```

**Comment by canton7** [comment] 2015-07-13 07:12
Righty, upgraded the pulling side to 0.11.4, captured some logs: http://pastebin.com/iDLv4LnU

**Comment by canton7** [comment] 2015-07-15 07:33
This is still an issue.

Anything else I can provide?

**Comment by AudriusButkevicius** [comment] 2015-07-15 08:57
Can you run stindex and stfileinfo utils against the two setups? (In cmd dir on this repo)

**Comment by canton7** [comment] 2015-07-16 07:16
After setting up Go, downloading Syncthing, downloading its dependencies, and running `go run main.go` from inside the `stindex` folder, that fails with `mkdir: the system cannot find the path specified`. Doing the same in `stfileinfo` asks for a path to check: what should I give here?

**Comment by canton7** [comment] 2015-07-16 07:37
Ah, `stfileinfo` looks like it should be given the path to the problematic file?

**Comment by AudriusButkevicius** [comment] 2015-07-16 08:24
One expects path to the file, the other one expects path to index directory

**Comment by canton7** [comment] 2015-07-17 07:33
Right, apologies for the delay.

Output of `stindex` on the machine with the file. I've trimmed it down to the sections which mention the file - let me know if I missed stuff out, and I can post the whole (massive) thing:

```
[device] F:"Music" N:"Red Hot Chili Peppers/Live in Hyde Park Disc 2/05. Californication.mp3" D:7777777-777777N-7777777-777777N-7777777-777777N-7777777-77777Q4
  N:"Red Hot Chili Peppers/Live in Hyde Park Disc 2/05. Californication.mp3"
  F:0644
  M:1208647668
  V:[{8746329750173916178 1}]
  S:6426901
  B:50

[global] F:"Music" N:"Red Hot Chili Peppers/Live in Hyde Park Disc 2/05. Californication.mp3" V:000000010000000179613491578c1c12000000000000000100000020ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
```

And from the machine trying to fetch the file:

```
[device] F:"Music" N:"Red Hot Chili Peppers/Live in Hyde Park Disc 2/05. Californication.mp3" D:3MQH4HE-OPTEIVG-4LNVT6N-6WL7YNT-Q4HIPJX-HSRU7ZZ-STSRKXX-LCK4WAN
  N:"Red Hot Chili Peppers/Live in Hyde Park Disc 2/05. Californication.mp3"
  F:0644
  M:1208647668
  V:[{8746329750173916178 1}]
  S:6426901
  B:50

[global] F:"Music" N:"Red Hot Chili Peppers/Live in Hyde Park Disc 2/05. Californication.mp3" V:000000010000000179613491578c1c12000000000000000100000020db207e1c8e7cc88af16dacfcdf597fc361c3a1e9b9e51a7f329ca2abdd62572c
```

And finally `stfileinfo` on the machine which has the file (the machine trying to pull it doesn't have a copy):
```
[root@StorageDroid syncthing]# bin/stfileinfo /srv/sync/data/syncthing/music/Red\ Hot\ Chili\ Peppers/Live\ in\ Hyde\ Park\ Disc\ 2/05.\ Californication.mp3
File:
  /srv/sync/data/syncthing/music/Red Hot Chili Peppers/Live in Hyde Park Disc 2/05. Californication.mp3

Lstat:
  Size: 6426901 bytes
  Mode: 0644
  Time: 2015-07-10 07:11:59.967508721 +0000 UTC (1436512319)

Blocks:
read /srv/sync/data/syncthing/music/Red Hot Chili Peppers/Live in Hyde Park Disc 2/05. Californication.mp3: input/output error
``

**Comment by canton7** [comment] 2015-07-17 07:42
Also, Syncthing on the pulling device creates `~syncthing~05. Californication.mp3.tmp`, which contains the complete file

**Comment by AudriusButkevicius** [comment] 2015-07-17 08:35
This seems really funky but I have no clue

**Comment by canton7** [comment] 2015-07-17 08:49
What is Syncthing trying to do for the `Blocks` section? I know it must be able to read the file (or `~syncthing~05. Californication.mp3.tmp` wouldn't have been transferred, for starters), but anything else funky?

**Comment by calmh** [comment] 2015-07-17 09:05
This: https://github.com/syncthing/syncthing/blob/master/internal/scanner/blocks.go#L21

That's basically a loop that reads a block at a time into the hashing algorithm. "i/o error" there seems to be an actual read error from the operating system.

**Comment by canton7** [comment] 2015-07-17 09:12
It seems odd that the sending side isn't reporting anything untoward in its logs. I'll try upping STTRACE, if there's a message being hidden somewhere...

**Comment by calmh** [comment] 2015-07-17 09:14
The sending side ends up here: https://github.com/syncthing/syncthing/blob/master/internal/model/model.go#L834

There's no logging there, so you won't see anything. That results in a response being sent to the requesting side saying basically "no data", so it will try to find another source, then hit the "no available source device".

**Comment by calmh** [comment] 2015-07-17 09:21
We should probably have a debug message in place there, and for failure to open, so feel free to open a PR to improve the logging here.

**Comment by canton7** [comment] 2015-07-17 09:22
Aha I see - might it actually be L845, since it seems the file can be opened but reading some part of it seems to be failing? After I `touch`ed that file, shouldn't Syncthing have had to re-index it, and shouldn't that have raised an error of some sort?

 I wonder if the very last few bytes of the file are messed up in some weird filesystem-specific way then - this is an NTFS partition mounted on linux IIRC. I'll have a more thorough look when I'm next home.

**Comment by calmh** [comment] 2015-07-17 09:22
> After I touched that file, shouldn't Syncthing have had to re-index it, and shouldn't that have raised an error of some sort?

I think so, yes. Not sure off hand what happens with read errors on indexing though.

**Comment by calmh** [comment] 2015-07-17 09:23
> Aha I see - might it actually be L845, since it seems the file can be opened but reading some part of it seems to be failing?

Yeah, I posted the wrong link, edited it afterwards :)

**Comment by calmh** [comment] 2015-07-17 09:30
Reopening because there's something interesting here we should fix. :)

**Comment by canton7** [comment] 2015-07-17 09:36
Thanks. I'll leave things in their current weird/broken state for now

**Comment by calmh** [comment] 2015-07-17 10:36
Please do find out what's going on though, if possible. Then we can reevaluate what logging and actions, if any, we should add or fix on the indexing/sending side.

**Comment by canton7** [comment] 2015-07-17 10:55
I'll have a looksee

**Comment by odgeza** [comment] 2015-07-27 10:04
Explains my issue too.

In my case, there is an app that is creating a log of backups, and this seems to be occuring there. Any chance the file is changing while syncthing is trying read the file for a hash? (Or something to that effect - sorry, I don't know the code well (hmm, actually, at all), and I probably never will, just adding a user perspective here.

**Comment by AudriusButkevicius** [comment] 2015-07-27 10:11
Yeah we can't sync files which are constantly changing because it differs between us scanning and us syncibg. So your issue is not the same as the one posted here, and is actually not an issue at all, just a known limitation.

**Comment by odgeza** [comment] 2015-07-27 10:30
Hi, 

But the file isn't constantly changing, I think its created, then its streamed some data into it, then it doesnt change after that.

If it encounters an error, doesn't it just retry later? Wouldn't that invalid flag as indicated by calmh, 10 days ago, just allow it to retry after a while, and sort the issue out, istead of me having to rename it manually or "the equivalent of a windows 'touch'".

**Comment by AudriusButkevicius** [comment] 2015-07-27 10:47
It should correct itself after the file stops changing, a rescan interval passes, and enough time for the other node to download passes. If it changes in between a rescan and download, it will break again. @calmh refers to us failing to scan the file, which I don't think is the issue in your case, I think it's just a case of the file geniunely changing between rescan and download.

You can use md5 et al to verify that, or debug logging in scanner to verify that it's not actually failing at reading the file, like in the case of @canton7

**Comment by canton7** [comment] 2015-07-27 10:48
Yeah - this is only a dup if you get 'input/output error' when trying to read this file.

**Comment by odgeza** [comment] 2015-07-27 10:56
Ok, then there is definitely an issue, because after these file are finished being written, it is never changed again - it may very well change just as its created, but 10 minutes later, its not changing ever. Why would it not have recovered from this situation? Is there a way to get more debug output for this? Without having to run manual tools. For example, the receiver logs "hash x of DB and hash y of received file do not match"

But I have learnt something new here as well.

**Comment by AudriusButkevicius** [comment] 2015-07-27 11:03
Well the same tools as described in this post (stindex stfileinfo) can be used to check the what we see the files content as, versus what we have in the database. You'd have to compile them yourself though. 

Also, I suggest you run STTRACE=scanner env var which will print stuff as it's scanning to perhaps get some clues as to why it's seeing what it's seeing. I guess we should continue the discussion on the old ticket which I will reopen, in order not to pollute this one.

**Comment by ctlaltdefeat** [comment] 2015-09-19 15:08
I'm experiencing this too.
Description:
I have a Linux instance of version v0.11.25 acting as master and a Windows instance of same version synced with it. Around 3000 items of a folder structure around 3 deep is being synced properly, except for one single file which is quite irritating (beforehand I had issues with case-sensitivity, which is sort of understandable, which I fixed by just renaming). The file is being downloaded to the Windows client as a .tmp file to appropriate size, but still is being treated as out of sync, and I get the message of "pull: no available source device" for the file even though clearly there is a source. I've tried restarting both instances, rescanning, etc. to no avail.
Note that the same issue occurs when replacing the Windows instance with an Android instance.
Please let me know what logs I can provide.

**Comment by AudriusButkevicius** [comment] 2015-09-19 15:17
Your problem will be most likely because the file is constantly changing, hence we can't catch up.
Are you syncing some firefox profiles/databases or something?

**Comment by ctlaltdefeat** [comment] 2015-09-19 15:37
Nope, it's just some mp3 file that isn't changing at all.

**Comment by AudriusButkevicius** [comment] 2015-09-19 15:51
Restarting both sides could potentially help.

**Comment by ctlaltdefeat** [comment] 2015-09-19 15:55
I have though, see above

**Comment by AudriusButkevicius** [comment] 2015-09-19 16:17
Please download utils from here and run http://build.syncthing.net/job/syncthing-utils/ 
stwatchfile against the file in question.

**Comment by canton7** [comment] 2015-09-20 11:12
Try doing something on the Linux box which requires reading the whole file, like sha1sum. If that succeeds, it's not the same issue.

**Comment by ctlaltdefeat** [comment] 2015-09-20 17:12
stwatchfile gives:
```/home/ctlaltdefeat/xxxx/xxx.mp3 Size: 8668011 Mtime: 2015-09-18 13:22:45.733122459 +0200 CEST Hash: b8a76121aa84a1552a585667f9a17e66```

sha1sum does succeed.

Just restarted both again, tried again to sync between the Linux master and the Android, and still same same. Weird.

**Comment by AudriusButkevicius** [comment] 2015-09-20 17:58
Does it print multiple lines over time ir just one?

**Comment by dinosore** [comment] 2015-09-21 13:24
I have a solid example of this bug.  It is so repeatable that, on the pi,  I used to pipe syncthing's output via grep to the journal to remove references to the file causing the problem. I no longer do this as I now use the debian package.

On my wife's laptop there is a rather old accounting program, Quicken, which runs under windows xp under virtual box under windows 7.

The strategy it seems to use to keep its file up to date for each entry is to close and immediately re-open its main file.

It's data directory is shared with Windows 7 under a synced folder.

She runs syncthing via synctrayzor, so inotify is involved.

The problem occurs when my wife leaves Quicken open, sometimes for days at a time.

It clears as soon as Quicken is closed.

Below is log from this morning
````
-- Logs begin at Mon 2015-09-21 04:02:55 BST, end at Mon 2015-09-21 13:17:02 BST. --
Sep 21 04:03:54 pi syncthing[311]: [B3GZ3] INFO: syncthing v0.11.25 "Aluminium Ant" (go1.4.2 linux-arm default) unknown-user@syncthing-builder 2015-09-13 09:46:17 UTC
Sep 21 04:03:54 pi syncthing[311]: [B3GZ3] INFO: My ID: B3GZ34Z-
Sep 21 04:03:54 pi syncthing[311]: [B3GZ3] INFO: Database block cache capacity 8192 KiB
Sep 21 04:04:07 pi syncthing[311]: [B3GZ3] OK: Ready to synchronize Ddocuments (read-write)
Sep 21 04:04:22 pi syncthing[311]: [B3GZ3] OK: Ready to synchronize Pdocuments (read-write)
Sep 21 04:04:27 pi syncthing[311]: [B3GZ3] OK: Ready to synchronize Phhg (read-write)
Sep 21 04:04:32 pi syncthing[311]: [B3GZ3] OK: Ready to synchronize Ppics (read-write)
Sep 21 04:04:32 pi syncthing[311]: [B3GZ3] OK: Ready to synchronize Ppictures (read-write)
Sep 21 04:04:34 pi syncthing[311]: [B3GZ3] OK: Ready to synchronize Ddocs (read-write)
Sep 21 04:04:35 pi syncthing[311]: [B3GZ3] OK: Ready to synchronize Dpics (read-write)
Sep 21 04:04:36 pi syncthing[311]: [B3GZ3] OK: Ready to synchronize Dpictures (read-write)
Sep 21 04:04:54 pi syncthing[311]: [B3GZ3] OK: Ready to synchronize Pdocs (read-write)
Sep 21 04:04:54 pi syncthing[311]: [B3GZ3] INFO: Starting web GUI on http://0.0.0.0:8080/
Sep 21 04:04:55 pi syncthing[311]: [B3GZ3] INFO: Completed initial scan (rw) of folder Ppictures
Sep 21 04:05:05 pi syncthing[311]: [B3GZ3] INFO: Completed initial scan (rw) of folder Dpictures
Sep 21 04:05:29 pi syncthing[311]: [B3GZ3] INFO: Completed initial scan (rw) of folder Pdocuments
Sep 21 04:05:49 pi syncthing[311]: [B3GZ3] INFO: Completed initial scan (rw) of folder Phhg
Sep 21 04:06:33 pi syncthing[311]: [B3GZ3] INFO: Starting local discovery announcements
Sep 21 04:06:33 pi syncthing[311]: [B3GZ3] INFO: Device B3GZ34Z- is "pi" at [dynamic]
Sep 21 04:06:33 pi syncthing[311]: [B3GZ3] INFO: Device CLKW22T- is "PAULINE-PC" at [dynamic]
Sep 21 04:06:33 pi syncthing[311]: [B3GZ3] INFO: Device JFW3XNA- is "UNICORN" at [dynamic]
Sep 21 04:06:33 pi syncthing[311]: [B3GZ3] INFO: Starting usage reporting
Sep 21 04:06:36 pi syncthing[311]: [B3GZ3] INFO: API listening on [::]:8080
Sep 21 04:06:44 pi syncthing[311]: [B3GZ3] INFO: New UPnP port mapping: external port 32228 to local port 22000.
Sep 21 04:07:02 pi syncthing[311]: [B3GZ3] INFO: Completed initial scan (rw) of folder Dpics
Sep 21 04:07:32 pi syncthing[311]: [B3GZ3] INFO: Completed initial scan (rw) of folder Ppics
Sep 21 04:08:17 pi syncthing[311]: [B3GZ3] INFO: Completed initial scan (rw) of folder Ddocs
Sep 21 04:08:18 pi syncthing[311]: [B3GZ3] INFO: Established secure connection to CLKW22T- at 192.168.1.1:22000-192.168.1.5:55711
Sep 21 04:08:19 pi syncthing[311]: [B3GZ3] INFO: Device CLKW22T- client is "syncthing v0.11.25"
Sep 21 04:08:19 pi syncthing[311]: [B3GZ3] INFO: Device CLKW22T- name is "PAULINE-PC"
Sep 21 04:12:02 pi syncthing[311]: [B3GZ3] INFO: Completed initial scan (rw) of folder Ddocuments
Sep 21 04:12:45 pi syncthing[311]: [B3GZ3] INFO: Completed initial scan (rw) of folder Pdocs
Sep 21 04:12:47 pi syncthing[311]: [B3GZ3] INFO: Puller (folder "Pdocs", file "Quicken data/Current/PERSONAL.QDT"): pull: no available source device
Sep 21 04:12:47 pi syncthing[311]: [B3GZ3] INFO: Puller: final: no available source device
Sep 21 04:12:49 pi syncthing[311]: [B3GZ3] INFO: Puller (folder "Pdocs", file "Quicken data/Current/PERSONAL.QDT"): pull: no available source device
Sep 21 04:12:49 pi syncthing[311]: [B3GZ3] INFO: Puller: final: no available source device
Sep 21 04:12:50 pi syncthing[311]: [B3GZ3] INFO: Puller (folder "Pdocs", file "Quicken data/Current/PERSONAL.QDT"): pull: no available source device
Sep 21 04:12:50 pi syncthing[311]: [B3GZ3] INFO: Puller: final: no available source device
Sep 21 04:12:52 pi syncthing[311]: [B3GZ3] INFO: Puller (folder "Pdocs", file "Quicken data/Current/PERSONAL.QDT"): pull: no available source device
Sep 21 04:12:52 pi syncthing[311]: [B3GZ3] INFO: Puller: final: no available source device
Sep 21 04:12:53 pi syncthing[311]: [B3GZ3] INFO: Puller (folder "Pdocs", file "Quicken data/Current/PERSONAL.QDT"): pull: no available source device
Sep 21 04:12:53 pi syncthing[311]: [B3GZ3] INFO: Puller: final: no available source device
Sep 21 04:12:55 pi syncthing[311]: [B3GZ3] INFO: Puller (folder "Pdocs", file "Quicken data/Current/PERSONAL.QDT"): pull: no available source device
Sep 21 04:12:55 pi syncthing[311]: [B3GZ3] INFO: Puller: final: no available source device
Sep 21 04:12:56 pi syncthing[311]: [B3GZ3] INFO: Puller (folder "Pdocs", file "Quicken data/Current/PERSONAL.QDT"): pull: no available source device
Sep 21 04:12:56 pi syncthing[311]: [B3GZ3] INFO: Puller: final: no available source device
Sep 21 04:12:58 pi syncthing[311]: [B3GZ3] INFO: Puller (folder "Pdocs", file "Quicken data/Current/PERSONAL.QDT"): pull: no available source device
Sep 21 04:12:58 pi syncthing[311]: [B3GZ3] INFO: Puller: final: no available source device
Sep 21 04:12:59 pi syncthing[311]: [B3GZ3] INFO: Puller (folder "Pdocs", file "Quicken data/Current/PERSONAL.QDT"): pull: no available source device
Sep 21 04:12:59 pi syncthing[311]: [B3GZ3] INFO: Puller: final: no available source device
Sep 21 04:13:01 pi syncthing[311]: [B3GZ3] INFO: Puller (folder "Pdocs", file "Quicken data/Current/PERSONAL.QDT"): pull: no available source device
Sep 21 04:13:01 pi syncthing[311]: [B3GZ3] INFO: Puller: final: no available source device
Sep 21 04:13:02 pi syncthing[311]: [B3GZ3] INFO: Puller (folder "Pdocs", file "Quicken data/Current/PERSONAL.QDT"): pull: no available source device
Sep 21 04:13:02 pi syncthing[311]: [B3GZ3] INFO: Puller: final: no available source device
Sep 21 04:13:02 pi syncthing[311]: [B3GZ3] INFO: Folder "Pdocs" isn't making progress. Pausing puller for 1m0s.
Sep 21 04:13:06 pi syncthing[311]: [B3GZ3] INFO: Puller (folder "Pdocs", file "Quicken data/Current/PERSONAL.QDT"): pull: no available source device
Sep 21 04:13:06 pi syncthing[311]: [B3GZ3] INFO: Puller: final: no available source device
Sep 21 04:13:09 pi syncthing[311]: [B3GZ3] INFO: Puller (folder "Pdocs", file "Quicken data/Current/PERSONAL.QDT"): pull: no available source device
Sep 21 04:13:09 pi syncthing[311]: [B3GZ3] INFO: Puller: final: no available source device
Sep 21 04:13:12 pi syncthing[311]: [B3GZ3] INFO: Puller (folder "Pdocs", file "Quicken data/Current/PERSONAL.QDT"): pull: no available source device
Sep 21 04:13:12 pi syncthing[311]: [B3GZ3] INFO: Puller: final: no available source device
Sep 21 04:13:15 pi syncthing[311]: [B3GZ3] INFO: Puller (folder "Pdocs", file "Quicken data/Current/PERSONAL.QDT"): pull: no available source device
Sep 21 04:13:15 pi syncthing[311]: [B3GZ3] INFO: Puller: final: no available source device
Sep 21 04:13:17 pi syncthing[311]: [B3GZ3] INFO: Puller (folder "Pdocs", file "Quicken data/Current/PERSONAL.QDT"): pull: no available source device
Sep 21 04:13:17 pi syncthing[311]: [B3GZ3] INFO: Puller: final: no available source device
Sep 21 04:13:20 pi syncthing[311]: [B3GZ3] INFO: Puller (folder "Pdocs", file "Quicken data/Current/PERSONAL.QDT"): pull: no available source device
Sep 21 04:13:20 pi syncthing[311]: [B3GZ3] INFO: Puller: final: no available source device
Sep 21 04:13:23 pi syncthing[311]: [B3GZ3] INFO: Puller (folder "Pdocs", file "Quicken data/Current/PERSONAL.QDT"): pull: no available source device
Sep 21 04:13:23 pi syncthing[311]: [B3GZ3] INFO: Puller: final: no available source device
Sep 21 04:13:25 pi syncthing[311]: [B3GZ3] INFO: Puller (folder "Pdocs", file "Quicken data/Current/PERSONAL.QDT"): pull: no available source device
Sep 21 04:13:25 pi syncthing[311]: [B3GZ3] INFO: Puller: final: no available source device
Sep 21 04:13:26 pi syncthing[311]: [B3GZ3] INFO: Puller (folder "Pdocs", file "Quicken data/Current/PERSONAL.QDT"): pull: no available source device
Sep 21 04:13:26 pi syncthing[311]: [B3GZ3] INFO: Puller: final: no available source device
Sep 21 04:13:28 pi syncthing[311]: [B3GZ3] INFO: Puller (folder "Pdocs", file "Quicken data/Current/PERSONAL.QDT"): pull: no available source device
Sep 21 04:13:28 pi syncthing[311]: [B3GZ3] INFO: Puller: final: no available source device
Sep 21 04:13:29 pi syncthing[311]: [B3GZ3] INFO: Puller (folder "Pdocs", file "Quicken data/Current/PERSONAL.QDT"): pull: no available source device
Sep 21 04:13:29 pi syncthing[311]: [B3GZ3] INFO: Puller: final: no available source device
Sep 21 04:13:29 pi syncthing[311]: [B3GZ3] INFO: Folder "Pdocs" isn't making progress. Pausing puller for 1m0s.
````

**Comment by AudriusButkevicius** [comment] 2015-09-21 13:27
This is expected for things such as database, as the data is changing faster then we are syncing, so there is no possible workaround for this, and what you are seeing is not a bug, but a limitation of whats possible without the applications cooperating.

**Comment by dinosore** [comment] 2015-09-21 16:16
No, @AudriusButkevicius , it is not that scenario at all.

The file is updated by manual input.  Nothing is happening at that time in the morning.  The update frequency is zero.

Sometime yesterday, or the day before, my wife updated Quicken.

Quicken closed the file and immediately reopened it

Inotify noticed the change and reported it. (Q. @Zillode did Inotify check whether the file was now locked?)

By the time syncthing tried to access the file, Quicken had a write lock on the file.

What you have here is syncthing repeatedly reporting the ONE condition (a locked file) - this it reports interminably until cleared.

Q Does syncthing carry on syncing other files in the folder?

A write-locked file is not an error.  Agreed, syncthing does cope with the state after it has cleared, but it is very prolix in the process.

**Comment by ctlaltdefeat** [comment] 2015-09-21 22:43
stwatchfile printed only that one line for the few minutes that I left it to run, then I just closed it.
I am using syncthing-inotify (on Arch Linux).
As far as applications interfering, the only thing I could think of is that the file is open in a torrent client (Transmission), but I have thousands of such files that are and always have been syncing fine, and closing it does not help.
It doesn't rule out @dinosore's theory that maybe the locked file condition isn't being rechecked and somehow persistent through restarts.

**Comment by Zillode** [comment] 2015-09-25 22:19
> @Zillode did Inotify check whether the file was now locked?

No

**Comment by cron410** [comment] 2015-10-16 02:12
I am now seeing this on two Server 2012r2 machines trying to sync a 317mb video. Syncthing continues to show Syncing with a percentage that climbs on the Connected Device list for each machine in both consoles. The sync folder in each console flashes Syncing, then 99% and then Scanning every few minutes. When both Syncing progress percentages reach 100%, the sync folder allows me to click on the list of files it wants to sync. Filename appears as follows: "ShowName.S01E13.Name of Episode .avi" note the space between Episode and .avi file extension.  
  
I have tried shutting down both syncthings, deleting the .tmp file in the destination, rescanning both folders, rebooting both machines. No luck so far.

**Comment by cron410** [comment] 2015-10-16 02:19
Came here to post, but i figured it out. My issue was that my torrent client on one machine was downloading directly into the sync folder. The files were changing little by little every few seconds. Syncthing absolutely hated this. I don't know how this happened but I assume it was my own bonehead mistake. The torrent client is configured to download into an "incomplete" folder and then move the completed files into a "completed" folder. My syncthing configuration is looking at the completed folder for new files. I just shut down syncthing until this torrent completes so I don't interrupt the download and move the storage for that torrent. This shouldn't happen to me in the future and has nothing to do with Syncthing. Carry on.

**Closed** 2015-11-19 12:54 UTC

**Comment by AudriusButkevicius** [comment] 2015-11-19 13:02
So this is not fixed. Are we closing this as dupe?

**Comment by cron410** [comment] 2015-11-19 13:12
I had to stop using syncthing because of this. It appears to turn syncthing
into a 1 way sync for me. Ive got about 118gb of stuff in a single sync
folder. No other folders are in use.

**Comment by calmh** [comment] 2015-11-19 13:21
The post above seems to indicate this is the natural effect of files changing continuously. The rest is confusing. If there's a clear issue here we should fix, clarify and reopen.

**Comment by AudriusButkevicius** [comment] 2015-11-19 14:04
Well its a mixed bag of things here, but there are 4 issues I am aware that cause this:

1. Not checking if the file has changed between rescan and request. If you have a large rescan interval, you will think syncthing is broken.
2. Failing to discover changes due to subsecond modifications
3. Failing to discover changes due to mtime being preserved across modifications.
4. Failing to discover changes due to mmaped files

**Comment by calmh** [comment] 2015-11-19 14:26
In that case I think the only solution is to trigger a rescan once we get feedback from another device that the data we sent didn't match the hash we said it would? I remember we talked about that, but couldn't find the issue. It's almost but not quite #2221.
