### ISSUE TITLE
Synchronizing progress cannot reach 100%.

### ISSUE THREAD

**Issue by facat** [syncthing/syncthing#1385] opened 2015-02-26 16:16 UTC
A picture is worth thousands of words.
![Image](http://i2.tietuku.com/d964b4e3cfca6a79.png)

All of my directories are up-to-date, but the progress still remains 86%.
I'm using v0.10.23 for arml7.

**Comment by AudriusButkevicius** [comment] 2015-02-26 16:44
What does the UI look like on the other end?

**Comment by Somasis** [comment] 2015-02-26 19:38
I've been running into this issue as well. It seems to be fixed by removing file ignore entries, though. So I would think files that match the ignore entries need to be ignored in sync progress.

**Comment by AudriusButkevicius** [comment] 2015-02-26 21:33
Thatis actually working as expected. Because from our perspective the device only has part of the files, hence out of sync with the global state.

**Comment by Somasis** [comment] 2015-02-27 01:57
I would think that is very confusing for most end users though; the ignore entries are, to the end user, what Syncthing would just ignore in the file list entirely, even concerning synchronization. That's just my opinion, though.

**Comment by facat** [comment] 2015-02-27 05:38
@AudriusButkevicius The other end says it's 100% completed.

@AudriusButkevicius @Somasis I don't think this issue is caused by ignore list, because my ignore list is empty.

**Comment by AudriusButkevicius** [comment] 2015-02-27 08:14
It has to be due to ignores then. Or perhaps you need to refresh the UI. Does it have any files out of sync marked even though its at 100%? Having screenshots would help more.

**Comment by facat** [comment] 2015-02-27 12:08
@AudriusButkevicius refreshing UI doesn't help. 

    Does it have any files out of sync marked even though its at 100%?

How to see these files out of sync?

**Comment by AudriusButkevicius** [comment] 2015-02-27 12:16
It shows it in folder details:
https://cloud.githubusercontent.com/assets/1652143/5505673/6a1877e6-8793-11e4-970e-4a05a9a7dd85.png

**Comment by facat** [comment] 2015-02-27 14:00
@AudriusButkevicius 
Really, Some files are out of sync, but the state of their directory is up-to-dated.
![Image2](http://i2.tietuku.com/1c4de59f786e403f.png)
![Image2](http://i2.tietuku.com/565f25dd259ffd85.png)
As @Somasis  said, this will make user confused.

**Comment by AudriusButkevicius** [comment] 2015-02-27 15:31
This is actually a duplicate of #1130 in this case.

**Closed by AudriusButkevicius** 2015-02-27 15:31 UTC
