### ISSUE TITLE
Ignoring files while they are still being synced corrupts folder state

### ISSUE THREAD

**Issue by tomasz1986** [syncthing/syncthing#6980] opened 2020-09-11 00:02 UTC
How to reproduce:

1. Share a SO folder from Device A to Device B. Make sure to have large/many files, so that it takes some time to sync. I used 10,000 of 0-byte text files.
2. Accept the folder on Device B as RO and let it start syncing.
3. While the folder is still being synced on Device B, ignore everything with `*` on Device A.
4. After syncing has finished, the ignored files are still included in the Global State.

![image](https://user-images.githubusercontent.com/5626656/92827292-a7c96500-f40c-11ea-8353-30804627e0bd.png)
![image](https://user-images.githubusercontent.com/5626656/92827301-aac45580-f40c-11ea-9346-13be15cd1b29.png)

5. Unignoring the files on Device A leads to having "Out of Sync Items" stuck in sync.

![image](https://user-images.githubusercontent.com/5626656/92827636-0bec2900-f40d-11ea-8221-b83ed2c73be4.png)
![image](https://user-images.githubusercontent.com/5626656/92827650-11497380-f40d-11ea-8d7f-00812c5f6163.png)

6. Even after wiping the database and restarting, the folder on Device A is still stuck with "Waiting to Sync". The "Out of Sync" items themselves are gone though.

![image](https://user-images.githubusercontent.com/5626656/92830047-d85ece00-f40f-11ea-973d-d8795c6469bc.png)

**Comment by tomasz1986** [comment] 2020-09-11 00:23
I have changed the title, as I had initially thought that this is limited to SO and RO folders only, but the same thing happens when syncing SR folders too.

**Comment by calmh** [comment] 2020-09-11 05:48
Interesting. Waiting to sync means it was waiting (due to lack of folder concurrency) for an opportunity to sync, which might clear up some of these things. What happened when it "synced"?

**Comment by tomasz1986** [comment] 2020-09-11 06:10
> Interesting. Waiting to sync means it was waiting (due to lack of folder concurrency) for an opportunity to sync, which might clear up some of these things. What happened when it "synced"?

Yeah, but this was the one and only folder. The status simply got "stuck" and would not go away. Pausing and restarting also did nothing. Only after changing the folder type to something else cleared it.

**Comment by imsodin** [comment] 2020-09-11 07:54
The permanent "waiting to sync" status should be unrelated, that's a bug with handling folder status, where the send-only folder needlessly enters "waiting to sync" and never goes back to idle, see e.g. https://forum.syncthing.net/t/send-only-folder-is-waiting-to-sync-instead-of-out-of-sync/15585. I "accidentally" fixed it before even knowing that particular problem existed: https://github.com/syncthing/syncthing/pull/6951. The fix is in the latest RC. 

I see a dev version in your screenshots, I assume that commit isn't included? Generally please always mention what build (normally version) you are running. Respectively try to reproduce with the latest release or main when running custom builds.

**Comment by tomasz1986** [comment] 2020-09-11 08:33
I am sorry :sweat:. I will remember to mention the version number in the future. I do use my personal builds, but for the sake of simplicity, let us say that the test was done with `v1.9.0`.

I have now re-tested with `main` (`v1.9.1-dev.31.gecc24428`), and the main problem is still here. However, what has changed is the fact that now, the issue does go away after unignoring the files.

Device A (SO)
![image](https://user-images.githubusercontent.com/5626656/92892523-ca32a100-f453-11ea-940a-ef968d989c2a.png)

Device B (RO)
![image](https://user-images.githubusercontent.com/5626656/92892580-d6b6f980-f453-11ea-91b4-df4dea13abaa.png)

Device B (SR)
![image](https://user-images.githubusercontent.com/5626656/92893436-9f951800-f454-11ea-85d1-bf932452c062.png)

**Comment by imsodin** [comment] 2020-09-16 09:20
This is essentially the same as https://github.com/syncthing/syncthing/issues/6988 and I also think this is working as expected: The files were introduced and synced to the receive-only device as valid files before ignoring, and they now remain that way. If you want them cleaned up, you need to delete them without ignoring them (possibly ignoring afterwards if that's what you need).

**Comment by tomasz1986** [comment] 2020-09-16 11:55
Hmm, I understand what you are saying, although having those files synced and included in the global state was not the expected outcome for me, to tell the truth.

The issue itself came up due to a real-life situation, where I:

1. Shared an new SO folder, but forgot to add my patterns to `.stignore`.
2. In that state, accepted the folder as RO on a different device.
3. Realised my mistake, and only then filled `.stignore` up.
4. The ignored files still ended up being synced and included in the global state.

The problem was that my `.stignore` was too complex with too many patterns to go through the files on the RO side and delete them manually. I also did not want to delete the RO folder and restart from scratch due to slow hardware on the RO side.

After many trials, my workaround right now is to ignore everything with `*` on the RO side, let it go though all the files, and then unignore everything again. This way, the already present files get scanned again, but this time they are also marked as "Local Additions", which then allows me to clean the mess up through the Web GUI.

**Closed** 2020-10-02 13:25 UTC
Labels: bug, needs-triage
