### ISSUE TITLE
Ignore by default hidden system files and other hidden Windows file

### ISSUE THREAD

**Issue by tomsotte** [syncthing/syncthing#2783] opened 2016-02-16 08:00 UTC
Would it be possible to ignore certain, or every, hidden system files on Windows? I'm refering as an example to thumbs.db, or, for the Music folder, the AlbumArt_xxxxx.jpg files, which all of this are hidden on PC1, but when I synchronize they are not hidden on PC2.

I can also set for every directory i synchronize to ignore those files but:
1) I'm not sure if there are anyone other files somewhere else which should be hidden by the system and on PC1 it's hidden correctly but on PC2 (who receive the files) it's not hidden
2) Shouldn't there be a policy for hidden files? Or at least transferring the propriety from one PC to another? (if there is already I have not found it)

**Comment by AudriusButkevicius** [comment] 2016-02-16 08:17
Hidden does not translate to anything meaningful on other platforms, hence why it's ignored, same like xattrs on osx and so on.

If you don't want them synced, just ignore them. I don' lt think we should have a special policy for them, because it's an OS specific attribute, hence the policy would not make sense on other platforms. Nor do I think dropbox et al has any policies around that.

**Comment by canton7** [comment] 2016-02-16 08:44
I think there's an argument for ignoring certain files by default (it's been discussed on the forums before), e.g. `thumbs.db` and `.DS_STORE`. Syncing these is almost never the right thing to do, and setting up the ignores for each folder is a PITA.

**Comment by sonnhy** [comment] 2016-02-16 09:51
Sorry, I almost forgot hidden files on Linux/Mac has the "." and does not work the same way as Windows.

Dropbox does not sync those hidden files because I've never saw them on other computers.

Anyway I think it could be a nice implementation. My problem is also less concercing but for who has different OSes it may be frustating.

**Comment by jkufner** [comment] 2016-02-16 09:58
It sometimes makes sense to synchronize hidden files and sometimes it does not. Setting it for each folder would be very annoying, but ignoring all hidden files by default would be dangerous. The best thing is to ignore only known temporary files and directories and let user modify this list.

So there should be global list of ignored files for all folders on the device. Just like it is possible in Git.

**Comment by canton7** [comment] 2016-02-16 10:30
Yeah, I don't think a rule to always ignore hidden files makes sense: there are quite often cases where synchronising hidden files is what the user wants, and those users are going to be very confused that all of their files didn't get synchronised, if and when they notice. 

I think that @sonnhy associates hidden files with ignorable system-specific files, but this is by no means universally true (particularly in the Linux world, where any file that shouldn't get in the way of the user on a regular basis is hidden, e.g. most of `$HOME`. 

I would suggest creating a default `.stignore` (possibly platform-specific) when the user creates a folder, containing some default ignores. That way the default ignores are clearly visible to the user, and can easily be modified if they're undesirable: there are fewer concepts for the user to grasp than if we start introducing extra lists of ignore patterns which the user has to learn about.

**Comment by casimir** [comment] 2016-02-16 10:41
Why not using a global `.stignore`, just like [Git allows](https://help.github.com/articles/ignoring-files/#create-a-global-gitignore)?

**Comment by jkufner** [comment] 2016-02-16 11:08
Default .stignore is not good enough, because user may want to add some files globally. For example when he starts using some program which creates temporary files next to edited files all over the filesystem (and removes them when exitted, but they are still around for a long time). In such case user will want to add pattern to ignore all these files at global level. Doing so for every shared folder is very impractical.

**Comment by AudriusButkevicius** [comment] 2016-02-16 11:11
Yeah, but thats a separate issue which already exists in the tracker, so lets not bikeshed here.

**Comment by canton7** [comment] 2016-02-16 11:13
We already have a mechanism for shared ignore patterns: `#include`. 

Global ignore patterns are a separate issue to this one, and one which already has a solution. 

Let's try and keep this issue on topic guys, otherwise it loses all meaning. This issue is about ignoring system files that shouldn't be synced by default.

**Comment by casimir** [comment] 2016-02-16 11:20
My bad. I was just trying to say that this could be a specific case of global ignore patterns.

**Comment by calmh** [comment] 2016-03-10 15:30
Some default patterns are #837. Ignoring files that have the hidden bit set on Windows is *possible*, so leaving this as an unplanned enhancement.

**Comment by bugith** [comment] 2016-03-31 12:49
Or there could be a per folder option "Override default specific system/hidden global ignore pattern" with 2 sub option: "Override global" or "Override following custom pattern list" 
Just to add ideas to courageous dev ;-)

Bye bye

**Comment by ironista** [comment] 2019-04-20 07:17
What if we used a service like [gitignore.io](https://gitignore.io/api/linux,macos,windows)? In my case I always include a `.osignore` file in `.stignore` for every folder I share:

```
// Created by https://www.gitignore.io/api/linux,macos,windows
// Edit at https://www.gitignore.io/?templates=linux,macos,windows

////// Linux //////
*~

// temporary files which can be created if a process still has a handle open of a deleted file
.fuse_hidden*

// KDE directory preferences
.directory

// Linux trash folder which might appear on any partition or disk
.Trash-*

// .nfs files are created when an open file is removed but is still being accessed
.nfs*

////// macOS //////
// General
.DS_Store
.AppleDouble
.LSOverride

// Icon must end with two \r
Icon

// Thumbnails
._*

// Files that might appear in the root of a volume
.DocumentRevisions-V100
.fseventsd
.Spotlight-V100
.TemporaryItems
.Trashes
.VolumeIcon.icns
.com.apple.timemachine.donotpresent

// Directories potentially created on remote AFP share
.AppleDB
.AppleDesktop
Network Trash Folder
Temporary Items
.apdisk

////// Windows //////
// Windows thumbnail cache files
Thumbs.db
ehthumbs.db
ehthumbs_vista.db

// Dump file
*.stackdump

// Folder config file
[Dd]esktop.ini

// Recycle Bin used on file shares
$RECYCLE.BIN/

// Windows Installer files
*.cab
*.msi
*.msix
*.msm
*.msp

// Windows shortcuts
*.lnk

// End of https://www.gitignore.io/api/linux,macos,windows
```

**Comment by nerdCopter** [comment] 2020-02-13 14:27
+ synology's `@eaDir`

**Comment by beerse** [comment] 2020-12-01 15:13
Wild idea on extending/updating the .stignore feature:
First: Use the file '.stignore' (the current filename) and add to that the directory '.stignore.d' and all files (recursive) in it.
Reason: There everyone can ad there <toolname>  and/or <osname> with dedicated ignore patterns for that area.

Second: Read the .stignore and .stignore.d (in this order) from the software installation location (default: file containing ".stignore"), the 'standard map location' and the root of the current tree-to-sync. 

Major change: do sync the .stignore file and .stignore.d tree in the current tree-to-sync. If you donnot want to do so, Just add "/.stignore" to one of your .stignore files.
To keep up with the current configuration: Add "/.stignore" to the .stignore in the installation directory. The I can put "!./stignore in the .stignore file in the three and it is synced to my wishes.

**Comment by imsodin** [comment] 2020-12-01 15:15
Closing as duplicate of https://github.com/syncthing/syncthing/issues/837

**Closed by imsodin** 2020-12-01 15:15 UTC
Labels: enhancement
