### ISSUE TITLE
Show the device's name when someone adds you

### ISSUE THREAD

**Issue by git-commit** [syncthing/syncthing#1360] opened 2015-02-16 00:26 UTC
I would like to see the device's name additionally to the ID when I get a request.

**Comment by AudriusButkevicius** [comment] 2015-02-16 00:38
No can do. IDs are derived from the ssl certificates, which do not carry the name, and I think there is no space for them to carry the name there. So this is somewhat unfixable.

**Comment by git-commit** [comment] 2015-02-16 11:14
So there is automatic naming after a device is accepted?

I agree that having a devices hostname on public display like this would not be great.

The idea was stemming from the problem, when one if my introducer devices pushed me two requests and I couldn't tell which device was what or even if they're completely new devices.

**Comment by AudriusButkevicius** [comment] 2015-02-16 11:48
Yes, naming happens after a device is connected.

If you add a device it will briefly be nameless, and upon connection will get a name assigned (unless you've explicitly specified a name while adding).

Introducer stuff could carry names, as we are already connected to someone who has a name to the device (though it could be a custom name set specifically by that node)... so this is either a duplicate of #1098, or I believe impossible/unsafe.

**Comment by git-commit** [comment] 2015-02-17 14:07
I agree, #1098 would be a great addition and would help a lot.

Still I see some mainstream users preffering a name, additionaly to the cryptic ID, when first getting added, though this may be something that should be implemented in a 3rd party frontend rather than in protocol.

Thanks for commenting on my suggestion :)

**Comment by calmh** [comment] 2015-02-19 07:25
Yeah, there's a balance here. After acceptance, then name will show up (although maybe that could be done faster), before acceptance we don't want to reveal anything.

**Closed by calmh** 2015-02-19 07:25 UTC
