### ISSUE TITLE
request: add darwin/arm64 build for macOS ARM

### ISSUE THREAD

**Issue by sneak** [syncthing/syncthing#7128] opened 2020-11-18 22:45 UTC
Apple Silicon M1 Macs are out, and a native ARM version of syncthing would be awesome.  AIUI, golang already has support for darwin/arm64 (edit: accidentally wrote darwin/amd64 originally by accident) , so hopefully this isn't much work on your end.  I'm happy to help with testing if you need any as I have the hardware in hand.

**Comment by calmh** [comment] 2020-11-19 10:25
Go supports darwin-arm64 (in the macOS/M1 sense) in the "tip" (current development) version, not in the released 1.15. We have a preview build with this, it's available in the latest release candidate for example: https://github.com/syncthing/syncthing/releases/tag/v1.12.0-rc.3

I don't yet have an M1 Mac so this is completely untested, might not even run. Testing appreciated.

**Comment by sneak** [comment] 2020-11-19 15:03
Will test today and report back.

**Comment by sneak** [comment] 2020-11-19 15:04
Off Topic: just noticed the changelog, and: oh wow, untrusted encrypted devices in 1.12, that's such a great feature I've hoped for for so long!  Thanks so much for all of your hard work!

**Comment by ssgelm** [comment] 2020-11-20 01:08
@calmh FYI I tried the new build and get this panic:
```
$ ./syncthing
panic: qtls.ClientHelloInfo doesn't match

goroutine 1 [running]:
github.com/marten-seemann/qtls-go1-15.init.0()
	github.com/marten-seemann/qtls-go1-15@v0.1.0/unsafe.go:20 +0x1b4
```

**Comment by calmh** [comment] 2020-11-20 06:45
Thanks for testing. Of course the quic package blows up, that will probably need to be disabled until it's updated for Go 1.16.

**Comment by ssgelm** [comment] 2020-11-20 06:53
I've been having an issue where the amd64 version of syncthing spikes to 100% cpu and hangs so I had to turn it off for now so if you'd like me to test anymore arm64 versions please let me know! 😄

**Comment by calmh** [comment] 2020-11-20 06:55
See if this one runs: https://build.syncthing.net/buildConfiguration/Syncthing_BuildMac/86021?buildTab=artifacts&guest=1

**Comment by ssgelm** [comment] 2020-11-20 07:42
Nope same exact panic.

**Comment by calmh** [comment] 2020-11-20 12:43
That's odd because it shouldn't be building that package at all. Maybe it's included by something else. I guess I'll have to experiment when I have M1 hardware, or when Go 1.16 is released.

**Comment by ssgelm** [comment] 2020-11-20 14:46
If I have a chance I will try to see if I can get it to build and run locally.

**Comment by homeisfar** [comment] 2020-11-20 16:03
With the latest arm builds provided, I get the same error as https://github.com/syncthing/syncthing/issues/7128#issuecomment-730752533

I tried installing the latest Syncthing through MacPorts, which theoretically is a fresh compilation job. I'm not sure what happened (no output from MacPorts) but I figured after about three hours the build system was spinning, not actually doing anything useful. Not that I expect this to be fixed here, just mentioning it for awareness. I think the issue is, as already mentioned, Go's currrent lack of support for the new architecture.

The amd64 build does work fine on my M1 Mac with Rosetta. I copied the configuration directly from my old Mac. I haven't noticed any CPU spikes or hangs, but I also don't share many files or generate much activity.

**Comment by calmh** [comment] 2020-11-20 16:47
Apparently the zip build didn't take the extra build tags into account, but now it should so see if this helps: https://build.syncthing.net/buildConfiguration/Syncthing_BuildMac/86187?buildTab=artifacts&guest=1

**Comment by homeisfar** [comment] 2020-11-20 17:24
The arm build you provided launches successfully (`./syncthing`) but with filesystem watcher errors: `Error while trying to start filesystem watcher for folder "org" (uykt5-no3s9), trying again in 1m0s: watching is not supported`

The amd64 build in your latest link launches successfully with no errors.

**Comment by calmh** [comment] 2020-11-20 20:27
Yeah, that's expected, no fs notifications due to cross compilation. Will need a native build for that, or more complicated build setup.

**Comment by lenlo** [comment] 2020-11-22 01:14
> Apparently the zip build didn't take the extra build tags into account, but now it should so see if this helps: https://build.syncthing.net/buildConfiguration/Syncthing_BuildMac/86187?buildTab=artifacts&guest=1
> 
> I read something about having to set `GODEBUG=asyncpreemptoff=1` when running, not sure if that was for amd64+Rosetta or arm64 native or not at all.

FWIW, the amd64 version started up fine on my M1 based Mac mini, but soon after ran into the following error:

`[EB7QQ] 16:29:21 INFO: Completed initial scan of sendreceive folder Xxxxx`
`assertion failed [abi_info.kind == AbiKind::TranslatedCode]: emulated forward to an arm pc that isn't in translated code. arm_pc=0x105bc44d8 abi_kind=6 emulation_interval=[0x105c094fc,0x105c09510) instruction_interval=[0x105c094e8, 0x105c09510) x86_rip=0x404e70d`
`(ThreadContextRegisterState.cpp:677 move_to_instruction_boundary)`

Restarting it with `GODEBUG=asyncpreemptoff=1` seemed to take care of that problem (thanks for that tip!), but file watching would still not work.

I'm now running the arm64 version with file watching disabled. Apart from:

`[EB7QQ] 16:59:46 INFO: Listener for quic://0.0.0.0:22000: unknown address scheme "quic"`

it seems to be working well.

**Comment by FiloSottile** [comment] 2020-11-26 12:38
Is this fix committed anywhere? I still get the panic at bf7d03d when building with Homebrew (after patching `--HEAD` Homebrew/homebrew-core#65703).

Note that this is not a darwin/arm64 issue, but a Go 1.16 one. quic-go relies on internal implementation details of the standard library, so can break at every Go release.

The CPU spikes are probably golang/go#42700 and indeed can be worked around by `GODEBUG=asyncpreemptoff=1`.

**Comment by FiloSottile** [comment] 2020-11-26 12:56
Ah, adding `--tags noquic` got me a working build.

May I suggest gating the quic files on `go1.14,!go1.17` instead? This will ensure that the build works with any version automatically, and lets you opt in to building quic with a new version after you tested it.

**Comment by calmh** [comment] 2020-11-26 14:26
The noquic tag is a quick hack to deal with quic package oddities, not something we really want to perpetuate or systematise I think...

**Comment by imsodin** [comment] 2020-11-26 15:08
@FiloSottile 

> May I suggest gating the quic files on go1.14,!go1.17 instead? This will ensure that the build works with any version automatically, and lets you opt in to building quic with a new version after you tested it. 

That sounds like a good idea. Would you mind suggesting that on https://github.com/marten-seemann/qtls-go1-15 instead? That would make a runtime panic become a build error, which is so much better. And all dependencies of quic would actually profit, instead of everyone having to work around quic badness on their own. There's a better chance that they will take it seriously coming from the go security lead (there's a bit of a track record there of ignoring people until a big player says the same thing as the people).

**Comment by calmh** [comment] 2020-11-26 15:34
(This is way out left field and not strictly related to this issue, but I've been thinking for a while that we should re-evaluate quic as a whole. The idea was that the better NAT penetration would reduce the dependency on relays, but this is not what's happening with current usage stats reporting .33% quic4, 3.25% quic6 and 18% relay connections. Either our NAT detection is wrong/broken or the penetration isn't working for some other reason. (The quic6 connections might be non-NAT firewall penetration due to simultaneous opens.) It's not clear to me we're getting ROI on all the machinery behind the quic connections so we might want to either fix it or remove it...)

**Comment by AudriusButkevicius** [comment] 2020-11-26 17:37
Is there a physical cost associated with keeping it? If it helps that 3.5% of people, it's still saves some relay bandwidth. 

Also, perhaps the brand new tcp punch through is such a hit nowadays that it steals quic's thunder 👯 😄

**Comment by calmh** [comment] 2020-11-26 17:44
The cost is discussing it in this and other issues related to the STUN stuff, and every time there's a new Go release upcoming. :)

**Comment by AudriusButkevicius** [comment] 2020-11-26 18:00
The build pain - sure I get that, and we can just put stuff behind a flag for people who want to build off tip can do that.

Same way every time there is a new version of go and quic hasn't cought up, we can release official builds without quic until we don't have to go chasing people, but I don't think we should rip it out all together.

**Comment by vitobotta** [comment] 2020-11-30 12:06
Hi all, I read the thread but I am not sure of what to try since I am not familiar with Go etc.... I am trying to get syncthing sync to work on file system changes on a Mac with Apple silicon. I am actually trying to get Okteto to work, and Okteto uses syncthing under the hood. Can anyone please tell me if you actually got the realtime sync working, and how to achieve it? Thanks!

**Comment by calmh** [comment] 2020-11-30 13:34
Once there is a stable Go release for the M1 we'll release binaries. In the meantime your best bet is:

- Get the latest development version of Go ("tip") and build it using the appropriate procedure, and
- Get the latest development version of Syncthing and [build it using our build instructions](https://docs.syncthing.net/dev/building.html) and `-tags noquic`.

In theory it might work. None of us on the team have the requisite hardware to test yet, so you're all early adopters for now.

**Comment by vitobotta** [comment] 2020-11-30 14:23
Thanks @calmh. I am trying to compile Go from the master branch but it doesn't seem to be dying anything.... The script to build is not returning any errors but it's taking ages and the go process being used to build the new go is using just 2% of the cpu, so I don't think it's working properly :(

**Comment by calmh** [comment] 2020-11-30 14:25
We cannot support Go's build process here, you need to turn to the Go project for that, or potentially do some research and testing on your own as this is all still in development and unreleased at this point.

**Comment by vitobotta** [comment] 2020-11-30 14:30
Thanks.

**Comment by calmh** [comment] 2020-12-01 12:26
This is a cross compiled build that *might* have working fs notifications, I'd be happy to know how/if it works or not:

https://build.syncthing.net/buildConfiguration/Syncthing_BuildMac/87329?buildTab=artifacts&guest=1

**Comment by vitobotta** [comment] 2020-12-01 16:55
Hi @calmh, just tested and it seems that it doesn't pick up the file system changes in realtime unfortunately. For now I have configured a rescan every 2 seconds as a workaround since the project isn't too big and the rescan is pretty quick. I am going to try and use this build you linked to because the one that I can install with brew and that runs under rosetta is not very stable (it crashes after a while). Thanks!

**Comment by calmh** [comment] 2020-12-08 13:12
My M1 arrived today, and the current build works for me with fs notifications, so that's cool. I added it to the 1.12.1-rc.1 release we just made, I encourage everyone to try that build and file any oddities you discovery. (We'll probably not actually make a 1.12.1 stable release for arm64 until we have quic and stable Go in place, but we can all surf the RCs and nightlies in the meantime.)

**Closed by calmh** 2020-12-08 13:12 UTC
Labels: build

**Comment by vitobotta** [comment] 2020-12-08 13:15
Hi @calmh which build is working for you with fs notifications? I would like to give it a try. Thanks!

**Comment by vitobotta** [comment] 2020-12-08 13:16
@calmh the latest from here? https://build.syncthing.net

**Comment by calmh** [comment] 2020-12-08 13:29
https://github.com/syncthing/syncthing/releases/tag/v1.12.1-rc.1

**Comment by vitobotta** [comment] 2020-12-08 13:30
@calmh it seems to work fine, a huge thanks! :) What value do you use for fsWatcherDelayS?

**Comment by calmh** [comment] 2020-12-08 13:31
I don't change the defaults.

**Comment by vitobotta** [comment] 2020-12-08 13:36
Uhm maybe I was celebrating too soon. The default is 10 seconds, right? With that value the changes are propagated after ten seconds if I understood correctly. How can I have changes propagated in realtime? Is it OK to set fsWatcherDelayS to a lower number? Thanks

**Comment by calmh** [comment] 2020-12-08 13:38
This is not the general settings help thread, please feel free to open a discussion on the forum for tweaking fs notification settings.

**Comment by AudriusButkevicius** [comment] 2020-12-08 13:38
Is this question related to the new silicon? If not, general support questions go on the forum please.

**Comment by vitobotta** [comment] 2020-12-08 13:41
Sorry.
