### ISSUE TITLE
index not up to date after scan folder api called from Filewatcher application (synctrayzor)

### ISSUE THREAD

**Issue by chrisshearing** [syncthing/syncthing#3070] opened 2016-05-09 15:03 UTC
Hi,

We have Syncthing running via SyncTrayzor with a single instance on a Windows 2012 R2 server hosting multiple folders, each of which is connected to a single Syncthing instance running via SyncTrayzor on a users laptop.  The folders on the server are also shared via SMB for when the user logs on to a device other than their dedicated laptop.

The folders on the server are populated with data and we install and set up a laptop with a fresh folder to synchronise (this folder contains the basic structure of a windows documents folder, with a few folder redirections, such as desktop and links)

After the initial sync on a most laptops we notice errors such as these (specific to the user in question)

The Downloads.lnk file is present on both sides when the sync starts and will often result in a conflict file being created.

```
2016-05-03 11:19:43.5268 #1160 [Debug] SyncTrayzor.Syncthing.EventWatcher.SyncthingEventWatcher: Received 6 events 
2016-05-03 11:19:43.5268 #1160 [Debug] SyncTrayzor.Syncthing.SyncthingProcessRunner: [UVYNR] 11:19:43 INFO: Puller (folder "willenbrocka", file "My Settings\\links\\Downloads.lnk"): pull: peers who had this file went away, or the file has changed while syncing. will retry later 
```

This error goes away after a rescan (we have it set to 1 hour as we are using the Filewatcher in Synctrayzor for the immediate changes and frequent scanning of 200+ folders causes huge IO on the server) however as per the log below SyncTrayzor has already successfully sent an API request to scan the folder

Canton7 was extremely helpful and we concluded that SyncTrayzor was sending the API call to Syncthing without issue on [SyncTrayzor issue  256](https://github.com/canton7/SyncTrayzor/issues/256) (starts about halfway down on my reply starting "This might not be related, but we are seeing this popping up in the logs quite regularly,"

```
2016-05-03 11:18:22.7096 #5556 [Debug] SyncTrayzor.Syncthing.EventWatcher.SyncthingEventWatcher: <ItemStarted ID=3284 Time=03/05/2016 11:18:22 Item=my settings\links\Downloads.lnk Folder=willenbrocka Type=File Action=Update>
2016-05-03 11:18:22.7096 #5556 [Debug] SyncTrayzor.Syncthing.TransferHistory.SyncthingTransferHistory: Item started. Folder: willenbrocka, Item: my settings\links\Downloads.lnk, Type: File, Action: Update
2016-05-03 11:18:22.7096 #5556 [Debug] SyncTrayzor.Syncthing.TransferHistory.SyncthingTransferHistory: Created file transfer: <FileTransfer Folder=willenbrocka Path=my settings\links\Downloads.lnk Status=Started ItemType=File ActionType=Update Started=03/05/2016 10:18:22 Finished=>
2016-05-03 11:18:22.7096 #5556 [Debug] SyncTrayzor.Syncthing.EventWatcher.SyncthingEventWatcher: <ItemStarted ID=3285 Time=03/05/2016 11:18:22 Item=AppData\Bookmarks Folder=willenbrocka Type=File Action=Metadata>
2016-05-03 11:18:22.7096 #5556 [Debug] SyncTrayzor.Syncthing.TransferHistory.SyncthingTransferHistory: Item started. Folder: willenbrocka, Item: AppData\Bookmarks, Type: File, Action: Metadata
2016-05-03 11:18:22.7096 #5556 [Debug] SyncTrayzor.Syncthing.EventWatcher.SyncthingEventWatcher: <ItemFinished ID=3286 Time=03/05/2016 11:18:22 Item=AppData\Bookmarks Folder=willenbrocka Error=>
2016-05-03 11:18:22.7276 #5556 [Debug] SyncTrayzor.Syncthing.TransferHistory.SyncthingTransferHistory: Item finished. Folder: willenbrocka, Item: AppData\Bookmarks, Type: File, Action: Metadata
2016-05-03 11:18:22.7276 #5556 [Debug] SyncTrayzor.Syncthing.EventWatcher.SyncthingEventWatcher: <ItemFinished ID=3287 Time=03/05/2016 11:18:22 Item=my settings\links\RecentPlaces.lnk Folder=willenbrocka Error=>
2016-05-03 11:18:22.7276 #5556 [Debug] SyncTrayzor.Syncthing.TransferHistory.SyncthingTransferHistory: Item finished. Folder: willenbrocka, Item: my settings\links\RecentPlaces.lnk, Type: File, Action: Update
2016-05-03 11:18:22.7276 #5556 [Debug] SyncTrayzor.Syncthing.TransferHistory.SyncthingTransferHistory: File Transfer set to complete: <FileTransfer Folder=willenbrocka Path=my settings\links\RecentPlaces.lnk Status=Completed ItemType=File ActionType=Update Started=03/05/2016 10:18:22 Finished=03/05/2016 10:18:22>
2016-05-03 11:18:22.7596 #5556 [Debug] SyncTrayzor.Syncthing.EventWatcher.SyncthingEventWatcher: <ItemFinished ID=3288 Time=03/05/2016 11:18:22 Item=my settings\links\Downloads.lnk Folder=willenbrocka Error=>
2016-05-03 11:18:22.7756 #5556 [Debug] SyncTrayzor.Syncthing.TransferHistory.SyncthingTransferHistory: Item finished. Folder: willenbrocka, Item: my settings\links\Downloads.lnk, Type: File, Action: Update
2016-05-03 11:18:22.7876 #5556 [Debug] SyncTrayzor.Syncthing.TransferHistory.SyncthingTransferHistory: File Transfer set to complete: <FileTransfer Folder=willenbrocka Path=my settings\links\Downloads.lnk Status=Completed ItemType=File ActionType=Update Started=03/05/2016 10:18:22 Finished=03/05/2016 10:18:22>
2016-05-03 11:18:22.7876 #5556 [Debug] SyncTrayzor.Syncthing.EventWatcher.SyncthingEventWatcher: <ItemFinished ID=3289 Time=03/05/2016 11:18:22 Item=my settings\links\Desktop.lnk Folder=willenbrocka Error=>
2016-05-03 11:18:22.8276 #5556 [Debug] SyncTrayzor.Syncthing.TransferHistory.SyncthingTransferHistory: Item finished. Folder: willenbrocka, Item: my settings\links\Desktop.lnk, Type: File, Action: Update
2016-05-03 11:18:22.8276 #5556 [Debug] SyncTrayzor.Syncthing.TransferHistory.SyncthingTransferHistory: File Transfer set to complete: <FileTransfer Folder=willenbrocka Path=my settings\links\Desktop.lnk Status=Completed ItemType=File ActionType=Update Started=03/05/2016 10:18:22 Finished=03/05/2016 10:18:22>
2016-05-03 11:18:22.8276 #5556 [Debug] SyncTrayzor.Syncthing.EventWatcher.SyncthingEventWatcher: <LocalIndexUpdated ID=3290 Time=03/05/2016 11:18:22 Folder=willenbrocka Items=27 Version=1447220>
2016-05-03 11:18:22.8276 #5556 [Debug] SyncTrayzor.Syncthing.EventWatcher.SyncthingEventWatcher: <StateChangedEvent ID=3291 Time=03/05/2016 11:18:22 Folder=willenbrocka From=syncing To=idle Duration=00:00:00.4700000>
2016-05-03 11:18:22.8276 #5556 [Debug] SyncTrayzor.Syncthing.EventWatcher.SyncthingEventWatcher: <FolderSummary ID=3292 Time=03/05/2016 11:18:22 Folder=willenbrocka Summary=<FolderStatus GlobalBytes=1419642039 GlobalDeleted=2 GlobalFiles=7061 LocalBytes=1419642039 LocalDeleted=2 LocalFiles=7061 InSyncBytes=1419642039 InSyncFiles=7061 NeedBytes=0 NeedFiles=0 Invalid= State=idle StateChanged=03/05/2016 11:18:22 Version=1447248>>
2016-05-03 11:18:22.8927 #5556 [Debug] SyncTrayzor.Syncthing.EventWatcher.SyncthingEventWatcher: <GenericEvent ID=3293 Type=FolderCompletion Time=03/05/2016 11:18:22 Data={"completion":0.0013015957186612859,"device":"UVYNR2C-BUN6GAN-MTOYD2J-BIK2QHN-DLU4K2T-N6BKANX-U5PJS5C-CSB7EAC","folder":"willenbrocka"}>
```

These files are just automatically created windows .lnk files so are not important, however I really wanted to make sure that this doesn't happen with other conflicted files and felt it was worth a bug report.

Thanks!

### Version Information

Syncthing Version: v0.12.22
OS Version: Windows 7 x64 / Windows Server 2012 R2

**Comment by AudriusButkevicius** [comment] 2016-05-09 15:10
Can you provide steps that I could reproduce it locally?

**Comment by calmh** [comment] 2016-05-09 15:23
I could see potential issues, on Windows, if the file is exclusively locked. We might get a change notification, try to scan it but cannot due to it being locked still, and not see the change. That would then get picked up by the next scan, scheduled or not.

**Comment by chrisshearing** [comment] 2016-05-09 15:24
It doesn't happen on every user we sync, even though they are configured the same, so I don't know if replicating our environment will replicate the fault,

We redirect the following folders - if you have 2 windows machines with a user configured with these redirections, log into one, then sync with the other it will be similar.

The drive letter we use to map the folder via SMB is the same as a local folder which is mapped by subst - N:

I don't think its needed to exactly map to the same location, but the redirections should mirror whichever drive letter or folder you choose on both sides

desktop - n:\my settings\desktop
documents - n:\
downloads - n:\downloads
favorites - n:\my settings\favorites
links - n:\my settings\links
music - n:\my music
pictures - n:\my pictures
videos - n:\my videos

**Comment by chrisshearing** [comment] 2016-05-09 15:29
@calmh does Syncthing lock the file when creating a conflict file?  The version on the laptop will be newer (as its created on the login) so will replace the file on the server side and a conflict file is created,

Or could be Antivirus getting in the way as the file is updated and copied?  We should see this happen often on any file with a conflict then?

**Comment by calmh** [comment] 2016-05-09 15:29
Syncthing uses no locking. Antivirus is a very common root cause to weird unexplainable issues so, sure, possible.

**Comment by AudriusButkevicius** [comment] 2016-05-09 15:38
I suggest you try to repro with antivirus disabled, and if it still happens, provide either a test env or steps (not a bunch of paths) how to repro with resonable probability of it happening.

**Comment by chrisshearing** [comment] 2016-05-09 15:44
@AudriusButkevicius I've excluded Syncthing and Synctrazor as well as the folder containing their logs + index on the server (the only index which was getting out of sync was on the server) and will check new installs for the error.

We run a fairly complex environment, apart from mirroring our folder redirection I'm not sure of what to suggest to reproduce as I'm not sure what's causing the issue in the first place unfortunately.

**Comment by AudriusButkevicius** [comment] 2016-05-09 15:51
Sure, but we are not magicians either, and can't fix it just by having a vague description of the problem.

**Comment by calmh** [comment] 2016-05-09 16:00
I think an interesting step would be to disable antivirus completely, assuming it'll let you, as it might still be interfering otherwise.

**Comment by chrisshearing** [comment] 2016-05-09 16:04
If I still see the issue after adding the exclusions I'll look into disabling the antivirus - though that's never as easy as it should be!  I've found antivirus turn itself back on or still be checking things unless you uninstall it completely (which I'd rather avoid if possible) and most now prevent you from stopping or killing the service process, very annoying software at times!

**Comment by chrisshearing** [comment] 2016-05-13 13:06
We've installed 8 more clients since adding AV exclusions on our server node and we've not seen the common issue of "peers went away" with the .lnk files, however on 2 of the installs it's happened with real user files and isn't fixed by performing a rescan on the server node.

In testing I managed to fix one client by copying the file on the server end, which synced down successfully to the client then closing syncthing on the client, renaming the copy to the original name then starting syncthing on the client - both then said up to date and I can rename / update that file and changes synchronise successfully.

I tried editing the file and rescanning, this did not fix it, the file still listed as "peers went away" in the client logs

It's only happened on a single file in these 2 folders, the other 6 had no issues at all, the server node reports "Up to Date" and the client "Out of Sync"

Is there anything you need me to do to gather logs, or debug info?

**Comment by AudriusButkevicius** [comment] 2016-05-13 13:19
I think links might not be handled well just because how windows deals with them now that I think about it. I'd have to test it though. How are you creatijg modifying these links?

**Comment by chrisshearing** [comment] 2016-05-13 13:30
The lnk files we first noticed the issue on are the automatically created windows files in the Links folder (to desktop, documents, downloads)

In the users server folder they will have copies of these files created during their first ever network logon, on the laptop the files are created before syncthing starts after we re-install the laptop OS and log in as the user.

If windows doing silly things with lnk files causes this then it's not a big problem - worst case in this scenario is a 1 hour wait time before a changed .lnk file is synced, no data is out of sync, though a user could change a lnk pointing to a file and perhaps change the wrong version - again not the biggest issue.  Our main concern was if there was an issue that could make this happen with a real file,

**Comment by AudriusButkevicius** [comment] 2016-05-13 14:00
I am interested in exact list of steps to reproduce this for me internally, not the overall idea/approach of what you are doing.

Obviously I am not going to reinstall my laptop et al, so you have to narrow it down.

**Comment by chrisshearing** [comment] 2016-05-13 14:16
Unfortunately as it is an intermittent issue and we are not able to reproduce it 100% in our own environment, I don't think its possible for me to give you clear instructions on how to reproduce it in yours,

If we are able to find out what is causing the issue then I'll be able to narrow down the instructions.

**Comment by AudriusButkevicius** [comment] 2016-05-13 14:47
I suspect what lnk destination changing does not update mtime, but I have no idea how to test this.

**Comment by AudriusButkevicius** [comment] 2016-05-13 19:18
Ok, I tested and atleast on Windows 10 modifying the destination .lnk files point to updates the mtime, so my suspicions did not materialize.

I am closing this until we have a way to reproduce this.

**Closed by AudriusButkevicius** 2016-05-13 19:18 UTC

**Comment by chrisshearing** [comment] 2016-05-16 07:44
What about the non lnk files which are not updating the index at all as per my last update?

Should I open a separate issue for this?

**Comment by AudriusButkevicius** [comment] 2016-05-16 07:52
Again, until you have steps to reproduce, there is not much point in opening issues

**Comment by chrisshearing** [comment] 2016-05-16 07:59
Can you give me any indication of what you actually require in these steps to reproduce?

All I've done is set up a folder with data and sync'ed it to an almost empty folder on a new device and the error occurs ~20% of the time.  There is no difference in the setup procedure of devices as we've scripted that.

I can provide you with any log files, turn on any debug options you need, but I don't know what you want from me details wise to reproduce, it just happens on the first sync of a new folder to a new device.

Our environments are likely to be completely different and replicating that on your setup would be completely impossible - it may not even by an environmental difference that is causing the issue.

I can provide you with the config file for both ends of a folder we've seen the issue on if that helps.

**Comment by AudriusButkevicius** [comment] 2016-05-16 08:04
So make sure you can reproduce it without synctraynor (with normal rescanning). If you can, then we can discuss later.

**Comment by AudriusButkevicius** [comment] 2016-05-16 08:05
Also,if you can only reproduce it half the time then you need to work out whats different between the runs (potentially looking at the log) so thatyou could reproduce it reliably.

**Comment by chrisshearing** [comment] 2016-05-20 12:52
I think I have a bit more clarification on the issue now,

I separated this folder to a copy of the syncthing config (so I could test this without impacting the other ~80 users on the main instance) and ran it without synctrayzor using the same index and config file,

The issue was still present and a single file could not sync even after rescanning both sides.

I renamed the index-v0.11.0.db folder and allowed the side with the original files to rescan to a new index, it found 1 file less and the client downloaded the trouble file as soon as the indexing was complete.

I stopped syncthing on the client, deleted the now downloaded good file, used the old index and the file was again broken.

So it looks like there isn't a procedure that's happening to cause this, my guess is that there is a corruption happening in an index for a folder when its added to syncthing (some stuck object?) so the problem already exists and I only notice it when I add a new client to download that folder.  The only actions I've taken at this point are to add the new folder and device to the server config and restart syncthing.

I have a copy of a good index and a bad index for a users folder - is there anyway we can investigate the index to find out if its corrupted and try and trace what might have caused it?

**Comment by AudriusButkevicius** [comment] 2016-05-20 13:11
Sure, zip up the indexes and email them to me or calmh and provide the folder name file name and version which produced the index.

**Comment by chrisshearing** [comment] 2016-05-31 08:25
Sorry for the delay - I had a week's holiday and no access to the index's to send,

One index is 160MB zipped, so I've sent it via a sendthisfile link, I hope that's ok?  If not, please let me know a preferred file transfer method,

folder id="carnellr" 
path="E:\Work\carnellr"
file=included in email, as it contains a student name and number which I don't want to post for all to see online.
v0.12.22, Windows (64 bit)

**Comment by AudriusButkevicius** [comment] 2016-05-31 08:56
Whats the name of the file with the issue?

**Comment by chrisshearing** [comment] 2016-05-31 08:57
That should be in the email I sent you directly - I didn't want to post it visible for all to see,

**Comment by AudriusButkevicius** [comment] 2016-05-31 08:59
I only got the download link and a link pointing at this issue.

**Comment by chrisshearing** [comment] 2016-05-31 09:00
odd - you should have had a direct email from me with a 6mb attachment as well,

I'll resend the message without the index attached to see if that comes though,

**Comment by AudriusButkevicius** [comment] 2016-05-31 19:21
Just for reference, anonymized content of the index.

Faulty
```
[device] F:"carnellr" N:"file" D:UWW37EG
  N:"file"
  F:010644
  M:1463144664
  V:[{UWW37EG 1} {2VEXZC6 4}]
  S:128
  B:0
[device] F:"carnellr" N:"file" D:7777777
  N:"file"
  F:010644
  M:1463144664
  V:[{UWW37EG 1} {2VEXZC6 4}]
  S:128
  B:0
[global] F:"carnellr" N:"file" V: {{[{11938408816169907133 1} {15368952143233636521 4}], 7777777}, {[{11938408816169907133 1} {15368952143233636521 4}], UWW37EG}}
```

OK:
```
[device] F:"carnellr" N:"file" D:7777777
  N:"file"
  F:0644
  M:1463144664
  V:[{2VEXZC6 4}]
  S:315904
  B:3
[global] F:"carnellr" N:"file" V: {{[{15368952143233636521 4}], 7777777}}
```

**Comment by AudriusButkevicius** [comment] 2016-05-31 19:22
In the faulty case it doesn't really look faulty.
It seems that it's just marked as deleted, where as in the other case it's not.

If you have some odd cluster shape, are you sure that one of the nodes does not have `ignoreDeletes` enabled, and hence failing to inform you that the file is deleted?

Alternatively, we'd probably need to get the scanner logs for the folder in question with STTRACE=scanner option.

**Comment by chrisshearing** [comment] 2016-05-31 19:55
its a 2 node cluster, both sides have <ignoreDelete>false</ignoreDelete> set on the folder,

the odd thing is though is that file hadn't been deleted, its was still present on the node where those indexes come from and is there when performing a re-scan to add it to the index.

even stranger checking now, the original file was gone, checking our backups it was present on the day I was doing my tests in the morning and at mid-day - but gone the next morning, I performed the index tests between midday and 3pm.  I'll check with the user who might take some time to respond as staff are not here this week, but I think its more likely that the file was deleted while testing the indexes, probably as it thought it should have been deleted when restarting between different index of the same folder?

I restored the file and put back the original index which had the file marked as deleted and was unable to find it on  a re-scan, set the STTRACE=scanner option and started syncthing,

It still did not pick up the file on a re-scan so I've sent you the log via email (contained quite a bit of personal info again, sorry)

**Comment by AudriusButkevicius** [comment] 2016-05-31 20:00
So looking at the logs it looks like the rescan picked the file up ok this time, hence it should be accounted for.

**Comment by chrisshearing** [comment] 2016-05-31 20:10
It's not appeared on the other node yet - I don't have access to the console of that node from here though - it should re-scan every hour so I can check back later to see if its updated, it doesn't have the peer gone went away error in the logs right now so its probably working now,

I did find I could fix it by copying the file manually to the other end and having it sync back to the side which was having problems seeing it - so swapping between indexes and successfully syncing / deleting it may have had a similar effect and fixed the file to be re-scannable for the index - I'll have to find one of the other instances of being unable to re-scan a file and constant peers went away errors to re-run the STTRACE test

Fixing it that way wasn't really an option though as the peers went away message only appeared on the client, so unless a user reported the yellow exclamation mark on synctrayzor they could have files in this stuck state without us realizing,

**Comment by AudriusButkevicius** [comment] 2016-05-31 20:20
So if it has been detected locally and accounted for, it should appear on the other node, unless there are some errors in the console.

Rescanning on the other side has no meaning, as the file has already been detected locally.

The peers went away message implies that the file content was modified but the modification timestamp was not updated.
Initially the issue was about .lnk files, which I thought were special, but given the files we've talked about privately are not .lnk files, I suspect you are encountering either some sort of software adjusting file content without updating mtimes (deduplication or some strange form of network storage) that is actually causing the issue.

**Comment by chrisshearing** [comment] 2016-05-31 20:25
It's not downloaded on the other node yet, I'll zip up the index again and send it over so we can check its state in the index?

Files are stored on NTFS formatted drive on Windows 2012 R2 server, shared over SMB2.1 (Windows 7 clients) deduplication was disabled prior to adding any folders to syncthing as we encountered #1845 with our initial testing

**Comment by AudriusButkevicius** [comment] 2016-05-31 20:30
So the index won't do much. I think the log will have something useful in this case.
If the log shows what I expect, I'll ask you for additional debug output.

**Comment by chrisshearing** [comment] 2016-05-31 20:32
no worries, index sent just before you replied, sorry!

**Comment by AudriusButkevicius** [comment] 2016-05-31 20:44
Is that the index from the problem side or the ok side?

**Comment by chrisshearing** [comment] 2016-05-31 20:44
problem side

**Comment by AudriusButkevicius** [comment] 2016-05-31 21:00
Was the first index also from the problematic side?

I think this is happening because of https://github.com/syncthing/syncthing/issues/1787
As I can see two versions of the file in the Index, with one letter capitalization changed.

@calmh, possible?

**Comment by chrisshearing** [comment] 2016-05-31 21:10
All the index's have been from the same side - the server side where the files were originally stored and where I thought the index wasn't updating after a re-scan

I've checked my backups, but they only go back to 18/04/2016 and the folder was added to the index on 31/03/2016

In the backups the file doesn't have the _numbers_numbers at the end and ASCRF in the name is just CRF, however my backups are snapshots at 7am and mid-day so it could have been renamed but with a wrong capitalization of a character, then renamed after changing just the capitalization which my backups would not capture.

**Comment by AudriusButkevicius** [comment] 2016-05-31 21:14
So I can see `ASCRF` and  `AsCRF`

**Comment by chrisshearing** [comment] 2016-05-31 21:20
yep that makes a lot of sense given what I can see on my backups - I think we've found the issue!

File was renamed to its current version but the casing was missed on the s, then renamed straight away to S hitting issue #1797

**Comment by AudriusButkevicius** [comment] 2016-05-31 21:27
Though I am not convinced it should behave like that, even with the issue present, hence why I want @calmh opinion before I start testing and trying to reproduce.

**Comment by AudriusButkevicius** [comment] 2016-05-31 21:28
Still, check the logs on the other side and let me know if there is something of interest/error related there.

**Comment by chrisshearing** [comment] 2016-05-31 21:29
understood - what may be relevant in this case, is that when then file was renamed there was only 1 node for the folder,

The second node was added later which is when we noticed the problem and were getting the peer went away message (as its probably trying to download the incorrectly cased file?)
