### ISSUE TITLE
When will iOS version realease?

### ISSUE THREAD

**Issue by mendax1234** [syncthing/syncthing#8361] opened 2022-05-25 06:31 UTC
### Include required information
l use iPhone and l also want to use syncthing. How to do that? It seems that syncthing doesn't support iPhone. So, when will you release an iOS version?

Please be sure to include at least:

 - what problem your new feature would solve
 - how or why you think it is generally useful (i.e., not just for you)
 - what alternatives or workarounds you considered

**Comment by calmh** [comment] 2022-05-25 06:44
Duplicate of #102

**Closed by calmh** 2022-05-25 06:44 UTC
Labels: enhancement, needs-triage
