### ISSUE TITLE
ignorePerms to enable by default of not on shared folders

### ISSUE THREAD

**Issue by ediazrod** [syncthing/syncthing#7065] opened 2020-10-29 13:13 UTC
Hi will be great as we have a <defaultFolderPath> vaule a value like defaultIgnorePerms to have a default ignore or not on the new shared folder creation on the GUI interface.

Thanks!

**Comment by imsodin** [comment] 2020-10-29 13:18
Duplicate of https://github.com/syncthing/syncthing/issues/4224

**Closed by imsodin** 2020-10-29 13:18 UTC
Labels: enhancement, needs-triage
