### ISSUE TITLE
"Failed items" and/or "Out of Sync" errors when using nested folders

### ISSUE THREAD

**Issue by tomasz1986** [syncthing/syncthing#7074] opened 2020-10-31 11:42 UTC
I know that this is something that should be avoided, but still.

How to reproduce:

1. Share an empty folder between Device A and B.
2. Share another empty folder located in the previously shared folder between Device A and B.

	![image](https://user-images.githubusercontent.com/5626656/97777987-39588600-1bb7-11eb-93ca-49b0f3f7c9ef.png)
	![image](https://user-images.githubusercontent.com/5626656/97777990-45dcde80-1bb7-11eb-9524-19d8b43ecb32.png)
3. Add a file to the nested folder on Device A and let it sync.
4. Either the main folder or the nested folder on Device B gets stuck in this error state.
	![image](https://user-images.githubusercontent.com/5626656/97778009-6ad15180-1bb7-11eb-8790-1ff8cff77bb2.png)
	![image](https://user-images.githubusercontent.com/5626656/97778019-83416c00-1bb7-11eb-981b-7b0ac47239c2.png)
	![image](https://user-images.githubusercontent.com/5626656/97778032-b84dbe80-1bb7-11eb-9e90-3785d1d1250e.png)
	![image](https://user-images.githubusercontent.com/5626656/97778044-cd2a5200-1bb7-11eb-8ef3-3f5d1b2c8f91.png)

The error messages get cleared after pausing and resuming the affected folders, or restarting Syncthing itself. Temp files created in the process also get deleted after 24 hours, so this is more or less a cosmetic issue, because the folders are in fact in sync.

One problem here is that these error messages do not describe what is really going on. The first one, i.e. "file modified but not rescanned; will try again later" means nothing to the user, and the second one, i.e. "The system cannot find the file specified." is simply not true, because the actual file is there.

Tested with `main` (`v1.11.0-rc.3.dev.7.gdeafe4ca`).

**Comment by imsodin** [comment] 2020-11-09 10:56
I can't reproduce on current main. This might have been fixed by https://github.com/syncthing/syncthing/pull/7093 - could you please try if you still get the problem now?

**Comment by tomasz1986** [comment] 2020-11-10 14:32
Hmm, so I have re-tested this with the current `main`, and the main problem is gone.

What is still left are all those temp files that remain in the folder for 24 hours. Is there anything that can be done about it other than waiting for Syncthing to delete them later?

**Comment by imsodin** [comment] 2020-11-10 15:04
What likely happens is that one folder first syncs the file, then the second starts to as well and at the last step aborts, as the file changed unexpectedly due the first folder syncing. And the temp file remains on purpose when there's an error syncing, for potential reuse. So I consider this working as desired.

**Closed by imsodin** 2020-11-10 15:04 UTC
Labels: bug, waiting-for-info
