### ISSUE TITLE
Sync progress accounts for folders not being synced

### ISSUE THREAD

**Issue by joaofl** [syncthing/syncthing#3424] opened 2016-07-21 13:58 UTC
I've noticed that, since I've upgraded to version 14, the scanning got stuck at 91%, in one side (A), and 100% in the other side (B). While both sides show "Up-to-date" to all folders.

I found out that it is happening because, in A I've tagged the folder Z to be shared, but did not add it on B. Because of that, A thinks folder Z is unsynced, and account for 91% of all folders, which should be 100%.

Is it a normal behavior, or can one consider it a bug? But the fact is that it is confusing from user's perspective. Follows a screenshot.

### Version Information

Syncthing Version: v0.14.0 (maybe would happen in previous versions as well)
OS Version: Ubuntu Mint 16.04

![selection_001](https://cloud.githubusercontent.com/assets/8092452/17025220/e0bc0c0e-4f52-11e6-9197-4eff8b87d2dc.png)

**Comment by wweich** [comment] 2016-07-21 14:06
> scanning got stuck at 91%

There is no scanning in your screenshot, the remote device being stuck at 91%, not scanning.

This is normal behavior. Your node know/thinks that the remote one should have all data of e.g. 11 folders but only reports data for 10, so the device is 91% complete.
The second node knows/thinks that the remote node should have all data of 10 folders and reports all data for that 10 folders, so it is at 100%/Up to date.

This is expected and is not new in 0.14.

**Comment by joaofl** [comment] 2016-07-21 14:21
But why should node A account for a folder which was not "added" by node B?
At the same time, at node A, this same folder Z shows "Up to date", so as a user, how can you know where this 9% missing comes from? That is my point.

**Comment by wweich** [comment] 2016-07-21 16:25
The status on the left side is your local status (if you are up to date). As node A doesn't know of any modifications done by other nodes, it reports the folder as up to date.

I don't really know, if syncthing tracks, if a remote device accepted the sharing of a folder, but it seems to be not doing that. So node A thinks that B should be syncing folder Z with it and therefore reports the device as 91%.

**Comment by joaofl** [comment] 2016-07-21 17:02
It is not exactly a bug, but things could be a bit more explicit in this sense.

Another thing is, at node B, I get the pop-up "Want to add folder Z?" and I click "Later". But later is to broad. Because, if in one minute a change my mind, how can I get that offer again? Only by restarting node B?

There should be a list of folders with pending acceptant, kept locally, for whenever you decide to add it.

**Comment by calmh** [comment] 2016-07-21 17:21
What would you expect in this case? As wweich says, you've said that the other side should share 11 folders. It announces that it has all the data on ten of them and none of the data for the eleventh. Out conclusion is that it's working on it, or maybe waiting for the sharing prompt or whatever. Saying "100%" here would be a somewhat dangerous thing, as it does not have 100% of the things you've shared with it. Consider if it were a backup device, and you trusted the 100% to mean it had everything it should have.

**Comment by xduugu** [comment] 2016-07-21 17:42
Somehow related to this @calmh :

Is the folder index exchanged before the folder is accepted? I observed this, but had no time to verify it. So, is it possible to use this for some kind of DOS by creating a folder with a big index and share it with some device? But I guess the device must be already trusted before an index get exchanged.

**Comment by calmh** [comment] 2016-07-21 17:46
It's indexed (as in, hashed) when added. The other device announces that they want to share the folder with you, but won't send index data for it unless you specifically say that you *do* share it.

That's our implementation though. A device could send you unlimited amounts of crap index data for random folders if it wanted. But that device is already trusted and accepted by you, so if they're misbehaving you should remove it from the config and walk over with the cluebat.

**Comment by joaofl** [comment] 2016-07-21 17:57
@calmh 
Your point makes sense, but somehow a folder which was not accepted to be shared yet, should not be considered as shared. There should be something in between, like "pending acceptance". A point in which a folder was already announced to a node, but no index was shared yet.

Otherwise, how can a server node knows what is actually being synced?

**Comment by AudriusButkevicius** [comment] 2016-07-21 18:13
There are not many options here, you either include it in the calculations, or you don't (as this is what this ticket is about). And from the two options, reporting non-100 percent has less dramatic consequences, so I think we can close this.

I will be against any suggestions that suggest introducing yet another number/sentence into the UI

**Comment by calmh** [comment] 2016-07-21 18:20
One thing we could *potentially* do is flag the sharing mismatch. We know from the initial cluster config messages that they are sharing fewer folders than we expect them to, and we could highlight this with a red status and exclamation mark and whatever.

**Comment by AudriusButkevicius** [comment] 2016-07-21 18:41
To be honest, redoing the UI would be effort better spent, so that we actually have a place where to plugin all of these things.

**Comment by joaofl** [comment] 2016-07-21 18:44
One way, with very few impact would be to have something like:

![selection_002](https://cloud.githubusercontent.com/assets/8092452/17034627/74e95c9c-4f7b-11e6-824e-1d22c4beef45.png)

With more details when you mouse-over it.

**Comment by dhs-rec** [comment] 2016-08-10 06:33
I see a similar issue here, with 0.14.3 on a Windows (Server 2012R2 fwiw) machine. It's connected to 5 other devices, 3 of them being Linux, 2 are Windows. All of them are running 0.14.3.

It permanently shows "Syncing (99%)" for all three Linux devices, while Windows devices are fine. Never seen this before with 0.13.x.

**Comment by AudriusButkevicius** [comment] 2016-08-10 06:39
It's potentially a side effect of ignores. Also check the logs.

**Comment by dhs-rec** [comment] 2016-08-10 06:51
I don't use ignores. Logs don't show any problem.

BTW: While checking the logs I found that log entries on Windows have a time associated (but no date), while log entries on Linux have neither. They should show date **and** time on **both** platforms.

**Comment by calmh** [comment] 2016-08-10 07:01
That depends on how Syncthing is started; see `-logflags`. The default is same on all platforms. Also, not related to this issue. :)

**Comment by dhs-rec** [comment] 2016-08-10 07:07
Ah, OK. Nevermind ;-)

**Comment by calmh** [comment] 2016-08-14 17:24
"functions as designed" as far as I'm concerned

**Closed by calmh** 2016-08-14 17:24 UTC
