### ISSUE TITLE
image sync error in SAMSUNG Galaxy devices One UI 5 beta(Android 13)

### ISSUE THREAD

**Issue by IMnoobnoob** [syncthing/syncthing#8504] opened 2022-08-17 18:40 UTC
- which version of Syncthing and what operating system you are using
device 1: version 1.20.4, Galaxy S22, Android 13, One UI 5 beta
device 2: version 1.20.4, Galaxy Tab s7 plus, Andriod 12, One UI 4.1  

 - browser and version, if applicable
 - what happened,
After upgrad to One UI 5 beta(Android 13) Image sync does not work properly.
When I delete image in one device, image does not deleted properly in the other device.
It remains file like this (does not deleted properly)
![Screenshot_20220818_032821_Gallery](https://user-images.githubusercontent.com/92251043/185215761-b6b91018-e719-4319-bee8-c07c64b5cca5.png)

I think this bug is related in .thumbnails

 - what you expected to happen instead, and
image file is deleted in all synced devices properly

 - any steps to reproduce the problem.
this is my setting
![Windows_20220818-033555_SyncTrayzor](https://user-images.githubusercontent.com/92251043/185217290-d2d5f376-50a1-4090-bd3a-974bcef46892.png)
![Windows_20220818-033548_SyncTrayzor](https://user-images.githubusercontent.com/92251043/185217293-b0f1aa4c-e911-4f11-ac34-84511c412a24.png)
![Windows_20220818-033540_SyncTrayzor](https://user-images.githubusercontent.com/92251043/185217297-74ca232f-a7d8-400f-b477-14ca40fa8417.png)
![Windows_20220818-033524_SyncTrayzor](https://user-images.githubusercontent.com/92251043/185217300-0d021b60-7b15-4d05-9b73-1d81069f35f8.png)

and this is log file
[syncthing log file.txt](https://github.com/syncthing/syncthing/files/9365317/syncthing.log.file.txt)

**Comment by tomasz1986** [comment] 2022-08-17 19:09
Likely a duplicate of https://github.com/syncthing/syncthing-android/issues/1818.

**Closed** 2022-08-17 19:23 UTC
Labels: bug, needs-triage
