### ISSUE TITLE
FATAL: open NUL: The system cannot find the file specified.

### ISSUE THREAD

**Issue by AkelD** [syncthing/syncthing#2995] opened 2016-04-19 23:12 UTC
I recently had to install windows, and when I tried to run Syncthing I got:
```
[monitor] 20:04:25 INFO: Log output saved to file "D:\Windows\Appdata\Syncthing\syncthing.log"
[monitor] 20:04:25 INFO: Starting syncthing
[monitor] 20:04:25 FATAL: open NUL: The system cannot find the file specified.
```
I tried running it with -verbose, but got the same output.
Since I have %appdata% in my data partition to not have to worry about lost data when I reinstall, at first I thought this was because syncthing was trying to use the old drive letter, since for whatever reason last time the instalation decided to label it as F:\ rather than D:\. So I renamed  %appdata%\syncthing and ran ST again.
And it gave me the exact same error. It doesn't even write to syncthing.log. I already tried running it with my admin account and had the same problem.
Any idea of what could be causing this?

### Version Information

Syncthing Version: v0.12.22
OS Version: Windows XP SP3

**Comment by AudriusButkevicius** [comment] 2016-04-19 23:45
Please search through existing issues before opening new ones.

Duplicate of https://github.com/syncthing/syncthing/issues/1936
As for what's causing this, it's the 15 year old operating system people still use.

**Closed by AudriusButkevicius** 2016-04-19 23:45 UTC
