### ISSUE TITLE
Panic! ST crashes when I rebuild project in visual studio

### ISSUE THREAD

**Issue by Xeenych** [syncthing/syncthing#5214] opened 2018-09-20 16:21 UTC
St is watching a folder with Visual Studio project in it. When I star rebuild ST crashes and creates panic log
[panic-20180920-191528.log](https://github.com/syncthing/syncthing/files/2402142/panic-20180920-191528.log)

May be something related with lettercase in the folder path
`Notify backend is processing a change outside of the filesystem root: f.root==\\?\d:\Projects, root==\\?\D:\Projects, path==\\?\d:\Projects`

goroutine 

Syncthing Version: v0.14.50
OS Version: Windows
Browser Version: Chrome

**Comment by canton7** [comment] 2018-09-20 16:29
See https://forum.syncthing.net/t/panic-bug-notify-backend-is-processing-a-change-outside-of-the-filesystem-root/12133/7, duplicate of #5176, fix is in 014.51-rc.1

**Closed by canton7** 2018-09-20 16:29 UTC
