### ISSUE TITLE
Add new state for serving data to others

### ISSUE THREAD

**Issue by muzzol** [syncthing/syncthing#9610] opened 2024-07-15 08:36 UTC
### Feature description

It would be nice to have a state other than Idle when device is transfering data to others.

![gui1](https://github.com/user-attachments/assets/516eb345-162e-458c-8293-567cee7de4b6)

### Problem or use case

User case is very simple: I put a 10G file on a synced dir and status is idle after a very short time on local device so I shutdown the computer but file isn't really transfered yet.

there's a lot of discussions about this behaviour:

https://github.com/syncthing/syncthing/issues/7874

https://github.com/syncthing/syncthing/issues/9508

https://github.com/Martchus/syncthingtray/discussions/273

In my opinion status should never be idle for a machine transfering data, either receiving or giving.
Idle should be equal to doing absolutely nothing.

In current status clients calling API can't really know if a machine is needed for a sync to complete.

### Alternatives or workarounds

I've seen some hacks parsing local log to know if local machine is really doing something, but that's very unreliable.

**Comment by tomasz1986** [comment] 2024-07-15 08:49
Duplicate of https://github.com/syncthing/syncthing/issues/2730.

**Closed by tomasz1986** 2024-07-15 08:49 UTC
Labels: enhancement, needs-triage
