### ISSUE TITLE
junctionsAsDirs not working

### ISSUE THREAD

**Issue by TiraelSedai** [syncthing/syncthing#9791] opened 2024-10-28 21:09 UTC
### What happened?

I just cannot make Syncthing to go down the directory junctions in my folder.

I've set junctionsAsDirs to true, I've tried pause/unpause, I've tried restarting Syncthing.
I'm creating junctions with `mklink /J dst src`

Am I missing something? Can I enable any logging that will help me understand what's going on?

I've tried STTRACE=walker but I see basically nothing of value when I press re-scan of that folder where I have my junctions:

```
[PM2LM] 2024/10/29 00:08:44.809505 walk.go:124: DEBUG: walker/6mezc-ujfk2@0xc002b1e6e0 Walk [] Matcher/[]@0xc0010983f0
[PM2LM] 2024/10/29 00:08:44.809505 walk.go:292: DEBUG: walker/6mezc-ujfk2@0xc002b1e6e0 ignored (internal): .stfolder
```

### Syncthing version

1.28.0

### Platform & operating system

Windows 11

**Comment by bt90** [comment] 2024-10-28 21:15
Duplicate of #9775

**Closed by bt90** 2024-10-28 21:15 UTC
Labels: bug, needs-triage
