### ISSUE TITLE
"panic: leveldb: snapshot released" after Ctrl+C

### ISSUE THREAD

**Issue by tomasz1986** [syncthing/syncthing#7071] opened 2020-10-30 11:17 UTC
I have just got this after using Ctrl+C to close Syncthing when running it directly from terminal in Android.

```
[TX7YP] 2020/10/30 11:10:09.183374 set.go:534: WARNING: Fatal error: xxxxx-xxxxx Get(xxx): leveldb: snapshot released
Panic at 2020-10-30T11:10:09Z
panic: leveldb: snapshot released

goroutine 151 [running]:
github.com/syncthing/syncthing/lib/db.fatalError(0x4102de48, 0x51c112e8, 0x541b57c0, 0x94, 0x51f4a7c0)
	github.com/syncthing/syncthing/lib/db/set.go:535 +0x210
github.com/syncthing/syncthing/lib/db.(*FileSet).Snapshot.func1(0x4102de48, 0x51c112e8, 0x541b57c0, 0x94)
	github.com/syncthing/syncthing/lib/db/set.go:149 +0x40
github.com/syncthing/syncthing/lib/db.(*Snapshot).Get(0x52410d20, 0xffffffff, 0xffffffff, 0xffffffff, 0xffffffff, 0xffffffff, 0xffffffff, 0xffffffff, 0xffffffff, 0x5410b560, ...)
	github.com/syncthing/syncthing/lib/db/set.go:241 +0x2c4
github.com/syncthing/syncthing/lib/model.cFiler.CurrentFile(0x52410d20, 0x5410b560, 0x83, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	github.com/syncthing/syncthing/lib/model/folder.go:1153 +0x60
github.com/syncthing/syncthing/lib/scanner.(*walker).walkRegular(0x51f2a9c0, 0x410362f0, 0x52410d60, 0x5410b560, 0x83, 0x4103c488, 0x51f30520, 0x52460940, 0x0, 0x0)
	github.com/syncthing/syncthing/lib/scanner/walk.go:332 +0x50
github.com/syncthing/syncthing/lib/scanner.(*walker).handleItem(0x51f2a9c0, 0x410362f0, 0x52410d60, 0x5410b560, 0x83, 0x4103c488, 0x51f30520, 0x52460940, 0x52460980, 0x0, ...)
	github.com/syncthing/syncthing/lib/scanner/walk.go:325 +0x224
github.com/syncthing/syncthing/lib/scanner.(*walker).walkAndHashFiles.func1(0x5410b560, 0x83, 0x4103c488, 0x51f30520, 0x0, 0x0, 0xe, 0x414f7a50)
	github.com/syncthing/syncthing/lib/scanner/walk.go:268 +0xab8
github.com/syncthing/syncthing/lib/fs.(*MtimeFS).Walk.func1(0x5410b560, 0x83, 0x4103c450, 0x52ce7958, 0x0, 0x0, 0x4021c1fc, 0x52ce7958)
	github.com/syncthing/syncthing/lib/fs/mtimefs.go:124 +0x60
github.com/syncthing/syncthing/lib/fs.(*walkFilesystem).walk(0x51f1abd0, 0x5410b560, 0x83, 0x4103c450, 0x52ce7958, 0x52422810, 0x51f09f50, 0x0, 0x0)
	github.com/syncthing/syncthing/lib/fs/walkfs.go:80 +0x140
github.com/syncthing/syncthing/lib/fs.(*walkFilesystem).walk(0x51f1abd0, 0x51cbf440, 0x5a, 0x4103c450, 0x520b8cb8, 0x52422810, 0x51f09f50, 0x0, 0x0)
	github.com/syncthing/syncthing/lib/fs/walkfs.go:112 +0x460
github.com/syncthing/syncthing/lib/fs.(*walkFilesystem).walk(0x51f1abd0, 0x52403f50, 0x2b, 0x4103c450, 0x524a04b0, 0x52422810, 0x51f09f50, 0x0, 0x0)
	github.com/syncthing/syncthing/lib/fs/walkfs.go:112 +0x460
github.com/syncthing/syncthing/lib/fs.(*walkFilesystem).walk(0x51f1abd0, 0x52403da0, 0x22, 0x4103c450, 0x524a0400, 0x52422810, 0x51f09f50, 0x0, 0x0)
	github.com/syncthing/syncthing/lib/fs/walkfs.go:112 +0x460
github.com/syncthing/syncthing/lib/fs.(*walkFilesystem).walk(0x51f1abd0, 0x524a6360, 0x12, 0x4103c450, 0x524a0350, 0x52422810, 0x51f09f50, 0x0, 0x0)
	github.com/syncthing/syncthing/lib/fs/walkfs.go:112 +0x460
github.com/syncthing/syncthing/lib/fs.(*walkFilesystem).walk(0x51f1abd0, 0x52383ea0, 0x9, 0x4103c450, 0x524a0120, 0x52422810, 0x51f09f50, 0x0, 0x0)
	github.com/syncthing/syncthing/lib/fs/walkfs.go:112 +0x460
github.com/syncthing/syncthing/lib/fs.(*walkFilesystem).walk(0x51f1abd0, 0x40bdc4d5, 0x1, 0x4103c450, 0x5231f9e0, 0x52422810, 0x51f09f50, 0x0, 0x0)
	github.com/syncthing/syncthing/lib/fs/walkfs.go:112 +0x460
github.com/syncthing/syncthing/lib/fs.(*walkFilesystem).Walk(0x51f1abd0, 0x40bdc4d5, 0x1, 0x52422810, 0x0, 0x52422810)
	github.com/syncthing/syncthing/lib/fs/walkfs.go:135 +0xf0
github.com/syncthing/syncthing/lib/fs.(*caseFilesystem).Walk(0x51f3c730, 0x40bdc4d5, 0x1, 0x52422810, 0x0, 0x414f7a50)
	github.com/syncthing/syncthing/lib/fs/casefs.go:273 +0x90
github.com/syncthing/syncthing/lib/fs.(*MtimeFS).Walk(0x52410da0, 0x40bdc4d5, 0x1, 0x5244e4e0, 0x52460980, 0x5244e4e0)
	github.com/syncthing/syncthing/lib/fs/mtimefs.go:110 +0x7c
github.com/syncthing/syncthing/lib/scanner.(*walker).walk.func1(0x51f2a9c0, 0x410362f0, 0x52410d60, 0x52460940, 0x52460980)
	github.com/syncthing/syncthing/lib/scanner/walk.go:114 +0x1f0
created by github.com/syncthing/syncthing/lib/scanner.(*walker).walk
	github.com/syncthing/syncthing/lib/scanner/walk.go:111 +0x168
```

[panic-20201030-111009.log](https://github.com/syncthing/syncthing/files/5464716/panic-20201030-111009.log)

Syncthing version is `v1.10.0`.

**Comment by imsodin** [comment] 2020-10-30 14:31
Duplicate of https://github.com/syncthing/syncthing/issues/6994

**Closed by imsodin** 2020-10-30 14:31 UTC
Labels: bug, needs-triage

**Comment by tomasz1986** [comment] 2020-10-30 15:52
Hmm, a duplicate, but does it not mean that https://github.com/syncthing/syncthing/issues/6994 should be reopened then?
