### ISSUE TITLE
Add Support/Autorenaming for Whatsapp Documents (Ending in period/Ilegal Filenames)

### ISSUE THREAD

**Issue by Charlie-Ramirez-Animation-Studios-de-MX** [syncthing/syncthing#9479] opened 2024-03-20 02:29 UTC
### Feature description

Although initially this could be a WhatsApp problem _[and in fact it is]._ I have tried to contact Whatsapp support on several occasions, including pointing out the disruptive nature of this application behavior with some file systems, Terminals and backup applications, only receiving negative responses stating that "It is normal and intended behavior or _Therefore, despite the problems that this causes, there are no plans to change it._". This motivates me to open the proposal to add support for conflicting names or auto processing options, since at the moment the backup of these elements simply stops until manual intervention (and consequently requires physical access or another option to be able to remotely rename the files on the source device) is made. 
![image](https://github.com/syncthing/syncthing/assets/64709446/ecc3e693-c0ab-4b5c-851e-f798a7f6a61e) 
![image](https://github.com/syncthing/syncthing/assets/64709446/5d94ebd1-d9a0-42eb-ac2e-863da8648307)

### Problem or use case

**A main use of syncthing is to backup and synchronize files from mobile devices** (a common alternative to resilio sync) so it is a very common scenario for complete folders or drives to be backed up, being in the case of android WhatsApp Media Folders a point of interest in the copy so it is intrinsic that there are differences between the illegal character limitations of the Android Linux kernel and Windows NTFS/FAT systems.
See: https://gist.github.com/doctaphred/d01d05291546186941e1b7ddc02034d3
https://www.mtu.edu/umc/services/websites/writing/characters-avoid/
https://en.wikipedia.org/wiki/Filename

### Alternatives or workarounds

Some backup software resorts to asking the user or performing automatic measures such as automatic renaming if there is a name incompatibility between platforms. So far the only way I have found to get around this is to manually copy the files or delete the period of the file. 

In this case, using Resilio as an example, invalid characters are replaced with underscores [a somewhat old practice but also used by other software to avoid conflicts] also adding a warning of the file rename in the user panel, or The default behavior of Windows Explorer by removing the problematic character in the name leaving it as a file without an extension _(since apparently what WhatsApp does is eliminate the file extension but leaves the period in the file name)_

![image](https://github.com/syncthing/syncthing/assets/64709446/53b2e4fa-360a-464a-bbfc-188c900c3600)
![image](https://github.com/syncthing/syncthing/assets/64709446/ddee69d4-3c8c-41f6-ba9c-bc2dff71124c)

**Comment by rasa** [comment] 2024-03-20 05:41
Fixed in #7876.

**Comment by imsodin** [comment] 2024-03-22 23:00
Duplicate of https://github.com/syncthing/syncthing/issues/1734

**Closed by imsodin** 2024-03-22 23:00 UTC
Labels: enhancement, needs-triage
