### ISSUE TITLE
Web Client doesn't reconnect after Computer Suspend

### ISSUE THREAD

**Issue by QJKX** [syncthing/syncthing#4393] opened 2017-09-23 13:38 UTC
I have a syncthing tab pinned in the background.
When I suspend, then resume after some hours I get the error message:

> Connection Error
> 
> Syncthing seems to be experiencing a problem processing your request. Please refresh the page or restart Syncthing if the problem persists.
> 

I expect the client to be more intelligent about this. (Possibly it needs to detect that the clock has jumped forward, wait, then try reconnecting)
This doesn't seem to be a problem for quick suspend/resumes.

### Version Information

Syncthing Version: v0.14.37, Linux (64 bit)
OS Version: Debian 9.1 (64 bit)
Browser Version: Firefox 55.0.3 (64-bit) (Official, not from debian)

syncthing and syncthing-inotify are running as systemd services on the service manager of the respective user.

**Comment by AudriusButkevicius** [comment] 2017-09-23 13:46
It asks you to refresh the page, why don't you just do that?

**Comment by QJKX** [comment] 2017-09-23 13:55
I suspend and resume the machine a lot. It's inconvenient to do that every time.

I want the tab to be connected in the background, so I can be notified if there's anything that needs my attention.

**Comment by AudriusButkevicius** [comment] 2017-09-23 14:13
So I shrug when people say pressing a single key is inconvenient, but sure, let's tag this as an unplanned enhancement, and let's hope someone cares enough to make this happen.

**Comment by Nutomic** [comment] 2017-09-27 13:25
For some reason, this functionality works perfectly for me (and always has). Almost the same setup, Syncthing 64 bit on Manjaro, Firefox 55.0.3. Maybe your problem is caused by an addon or such?

**Comment by AudriusButkevicius** [comment] 2017-09-27 13:32
I did notice it happening too. If you open it in chrome, kill syncthing, wait for the UI to throw the error, restart it, it recovers in the background but the error modal doesn't get cleared.

**Comment by Nutomic** [comment] 2017-09-27 13:50
Just checked, that also works fine here.

**Comment by QJKX** [comment] 2017-09-27 17:52
> If you open it in chrome, kill syncthing, wait for the UI to throw the error, restart it, it recovers in the background but the error modal doesn't get cleared.

Yes, that's exactly the same behavior I'm experiencing in the browser.

It does seem to be intermittent though, and hasn't happened the last 2 times I've resumed my machine.

>Maybe your problem is caused by an addon or such
Definitely possible.

**Comment by AudriusButkevicius** [comment] 2017-10-14 22:06
So it only doesn't reconnect when we get a 500 due to internal syncthing error.
We recover on generic connection failures, so closing this until OP provides a reproducer/browser network logs.

**Closed by AudriusButkevicius** 2017-10-14 22:06 UTC
Labels: enhancement
