### ISSUE TITLE
Unable to sync a case-different file if already exists in the folder prior to syncing

### ISSUE THREAD

**Issue by tomasz1986** [syncthing/syncthing#6993] opened 2020-09-20 02:24 UTC
This is likely exactly the same problem as https://github.com/syncthing/syncthing/issues/6989, but I am creating a new issue, as there are no ignores involved this time.

How to reproduce:

1. Add a file called `test` to a folder on Device A.
2. Copy the `test` file from Device A to a folder on Device B.
3. Rename the `test` file on Device B to `TEST`.
4. Share the folder between A and B.

![image](https://user-images.githubusercontent.com/5626656/93692873-6a16bb80-fb33-11ea-969d-d03825e8c90e.png)
![image](https://user-images.githubusercontent.com/5626656/93692875-6be07f00-fb33-11ea-89cf-5aa722d20373.png)
![image](https://user-images.githubusercontent.com/5626656/93692876-6e42d900-fb33-11ea-9b48-12381323872c.png)

The difference between this and https://github.com/syncthing/syncthing/issues/6989 is that here the folder on both A and B is "Out of Sync", while in the case with ignores involved, only one side was "Out of Sync". I guess that fixing this issue will also fix https://github.com/syncthing/syncthing/issues/6989.

Tested with `main` (`v1.10.0-rc.2.dev.2.gd2e32957`).

**Comment by calmh** [comment] 2020-09-20 06:54
This seems like desired behavior to me - you can't have both test and TEST on either of the devices, so they are both out of sync. What would you expect to happen instead?

**Comment by tomasz1986** [comment] 2020-09-20 07:22
Well, if `Case Sensitive FS` is disabled, and the files have exactly the same content, I would expect to treat them as the same file.

This is how case-insensitive operating systems like Windows operate. If Syncthing worked in a similar manner, the "ideal" solution would be to simply keep the cases different on each device, but treat them as the same file. I guess that this is not possible in Syncthing though, at least with how it currently treats case sensitivity differences, right?

With the current limitations, how about simply choosing one casing (e.g. following the file added to Syncthing last), and replace the other side(s) with it? It may not be ideal, but I believe that it would be still better than having such files in the "Out of Sync" state.

**Comment by calmh** [comment] 2020-09-20 07:25
That is indeed not how Syncthing works. As mentioned before we might special case handle it when the contents are identical. In the general case "pick one and discard the other" is the data loss bug that we *fixed* with this behavior.

**Comment by tomasz1986** [comment] 2020-09-20 07:55
> That is indeed not how Syncthing works. As mentioned before we might special case handle it when the contents are identical. In the general case "pick one and discard the other" is the data loss bug that we _fixed_ with this behavior. You can get that back by enabling "case sensitive fs".

Hmm, so this is interesting. With `Case Sensitive FS` enabled, Syncthing indeed "syncs" the two folders, marking them "Up to Date".

However, the actual result is as follows.

Device A
```
test
~syncthing~TEST.tmp
```

Device B
```
TEST
~syncthing~test.tmp
```

The case being preserved is indeed my desired behaviour, although I am not sure about the temp files hanging there like that. I guess that they will be deleted after 24 hours anyway.

The problem is that I do like the new behaviour allowing to actually case rename files after they have been added to Syncthing, which is impossible with `Case Sensitive FS` enabled.

> I think that option means the opposite of what you think it means. :) It does not tell Syncthing to be case sensitive - Syncthing is always case sensitive. It tells Syncthing that you promise you have a case sensitive file system.

Understood. I would say that this is not easy to comprehend from a purely user perspective though, especially for someone that has only used Windows for their whole life.

**Comment by acolomb** [comment] 2020-09-20 08:00
You're welcome to join in on https://github.com/syncthing/docs/issues/566 where I suggested to add an explanation of the basic case sensitivity behavior and assumptions to the documentation. I also think that being case sensitive at Syncthing's core is unexpected but a good thing that just needs a rationale.

**Comment by calmh** [comment] 2020-09-20 08:12
It is not intended to be a user facing option though, really. To the extent that it is, it's only an optimization option to be deployed on actual case-sensitive systems. It does not result in sensible behavior on Windows, but rather random data loss and out of sync scenarios (the old situation).

**Comment by tomasz1986** [comment] 2020-09-20 08:18
> You can get that back by enabling "case sensitive fs".

I think that there is a bug with `Case Sensitive FS` enabled. I do not want to create a new issue, as I have already created too many in the past few days.

This is what happens if you perform the "How to reproduce" operation listed in the beginning of this thread, but with `Case Sensitive FS` enabled this time.

1. Syncthing reports two files, even though Device A has only `test`, while Device B has only `TEST`.
![image](https://user-images.githubusercontent.com/5626656/93706750-7ff0a480-fb64-11ea-836c-23d0b223143d.png)
![image](https://user-images.githubusercontent.com/5626656/93706752-81ba6800-fb64-11ea-8718-651b20312732.png)

2. Deleting `test` from Device A also deletes `TEST` from Device B, but after the operation, Device B is stuck with an error.
![image](https://user-images.githubusercontent.com/5626656/93706772-bdedc880-fb64-11ea-88dc-6baefd17417f.png)
![image](https://user-images.githubusercontent.com/5626656/93706774-c0502280-fb64-11ea-8dcc-fffbca57fc5f.png)
![image](https://user-images.githubusercontent.com/5626656/93706786-d78f1000-fb64-11ea-9ff5-438dc4f02375.png)

3. Fortunately, pausing and restarting the folder clears the error.

Still, if the two files are actually kept in the folder with different cases, then the total state will report two files instead of one. Also, if one of the two files gets modified, it will replace the other one, this time including the case. However, Syncthing will still keep reporting 2 files instead of 1.

**Comment by calmh** [comment] 2020-09-20 08:20
I'll try again to me more clear: the behavior you "get back" is not desirable: it's buggy and broken. We fixed it. You can not enable the `case sensitive fs` option on a non-case sensitive fs and get reasonable behavior. What you do get is the "we clobber the contents of a random file when there is a case conflict", which is what I somewhat facetiously and stupidly suggested you could get back by enabling that option.

**Comment by acolomb** [comment] 2020-09-20 08:24
As an actual improvement, could Syncthing check for the folder marker in two different casing variants and refuse to sync when it sees case-folding behavior there whereas the configuration says `caseSensitiveFS = true`?

**Comment by calmh** [comment] 2020-09-20 08:27
No, because that check doesn't work in the general case. The case sensitivity properties of a given folder can vary for any directory within the folder. We've hashed this out multiple times on the forum and in the various issues relating to the case sensitivity fix, so lets not do it once more here, please, it's exasperating.

**Comment by acolomb** [comment] 2020-09-20 08:28
You're right. Sorry I didn't catch the previous discussions.

**Comment by tomasz1986** [comment] 2020-09-20 08:29
> What you do get is the "we clobber the contents of a random file when there is a case conflict", which is what I somewhat facetiously and stupidly suggested you could get back by enabling that option.

I see. I guess it was good to do some testing anyway.

I really hope that there will indeed be some special treatment of files that have identical content, but different case. Right now, the new behaviour has caused a lot of issues with my folder syncing, especially when `.stignore` is added to the equation.

**Comment by calmh** [comment] 2020-09-20 08:35
Right. So that's been suggested and can be implemented based on the other issue, and the need for some writeup seems clear and is also noted in another issue, so I'm going to close this one as the subject describes the intended behavior.

**Closed by calmh** 2020-09-20 08:35 UTC
Labels: bug, needs-triage

**Comment by tomasz1986** [comment] 2020-09-21 13:04
I am sorry for writing again in the closed issue, but there seems to be a problem when trying to disable `caseSensitiveFS`. Even though it stays disabled in the Advanced Configuration, the folder needs to be actually paused and restarted for the setting to take effect.
