### ISSUE TITLE
Conflicts with one-way edit

### ISSUE THREAD

**Issue by LeReverandNox** [syncthing/syncthing#1795] opened 2015-05-10 22:51 UTC
Hey guys,
I got a small issue since I upgrade to 0.11.X,
I still use Syncthing for an amateur communautary project in a one-way solution (a Debian 'server' distribute the files from a master folder, and the Windows clients synchronize on it)
It's been running great for over 8 months,

Since 0.11, each time I modify a file on the server, a sync-conflict file appear on every client. Even if they didn't make any modification on their side.
We try to delete indexes on both sides, but it didn't help.

I really don't understand... If you want any specific log, tell me.

Thank you ! :)

**Comment by djtm** [comment] 2015-05-14 07:15
Pretty similar here. Not sure if it's each time. But it does happen a lot.

**Comment by ShadowKyogre** [comment] 2015-05-14 18:53
I can confirm this. Additionally, this is a really huge problem since there's one file I frequently modify on one computer, then sync back to my phone. For some reason the OLDER versions are treated as what should be the one syncing around, not the newer versions.

Pretty huge regression for 0.11.x 3:.

**Comment by Zillode** [comment] 2015-05-14 18:57
Please add sufficient information for us to analyze the issue. Which version, which machines [etc](https://github.com/syncthing/syncthing/blob/master/CONTRIBUTING.md)

**Comment by ShadowKyogre** [comment] 2015-05-14 19:02
@Zillode:

For my desktop: Arch Linux @ Syncthing version 0.11.2
For my phone: Android 4.4.4 (Kitkat) through Cyanogenmod @ latest version on google play

Steps to reproduce:
1. Edit a file on my desktop
2. Turn on syncthing on desktop
3. Turn on syncthing on phone
4. Wait for the two to connect to each other
5. Then they should sync.

Expected result: Phone downloads file from computer
Actual result: Computer downloads file from phone

This also happened when I was trying to sync things back with my home server too.

**Comment by Zillode** [comment] 2015-05-14 19:09
@ShadowKyogre this is https://github.com/syncthing/syncthing/issues/831 and will be fixed in the next release.

**Comment by ShadowKyogre** [comment] 2015-05-14 19:11
@Zillode: Ooooh, gotcha! I still get the random sync-conflict files with one-way edits though, but that does help!

**Comment by LeReverandNox** [comment] 2015-05-14 20:08
@Zillode:
Thank you for your answer.

- Here's my setup :
The 'server' : Debian 8 64bit / Syncthing Linux amd64 0.11.3
All the clients (around 150) : Windows 7/8/8.1 64bits / Syncthing Windows amd64 0.11.3
The server as a master folder shared with all the clients (read-only).

- What's happening :
Each time I edit a file (e.g dummy.xml) on the server, instead of just overwriting this file on the clients, it does, but also create a conflict files such as : dummy.sync-conflict-20150508-233413.xml
It happens every single time I edit any file, either if the client have made a modification on his side or not.

- What I expect :
To work as before : just override the modified files with no conflicts where there is no need.

There's not obvious error in the default log or in the GUI.
If you want me to generate a specific log with SSTRACE, I'll be glad to do so.

Thank's :)

**Comment by AudriusButkevicius** [comment] 2015-05-15 08:39
Sounds like a bug, needs a test case.

**Comment by Zillode** [comment] 2015-05-18 20:26
Hmm, I can't reproduce this via an integration test. It seems we need a linux server and several windows clients?

**Comment by Zillode** [comment] 2015-05-18 20:46
In a manual test with linux as master, a linux client and a windows client, I see that something is clearly wrong. I get the override button for every change on the master, and a conflicting file on the clients.

**Comment by LeReverandNox** [comment] 2015-05-19 12:21
@Zillode: I did some tests on my setup, and by overriding all the clients with the override button, it seems to work again (at least for now, as far as I can see... I need a few days to have my collaborators feedback)
The server has apparently retrieve the "control" on the files.

**Comment by calmh** [comment] 2016-01-01 15:10
Note that getting to the "override" stage as @Zillode does here can be explained by for example a FAT filesystem, which has lower modification time granularity than we expect and thus can cause a metadata update directly after our update. That doesn't cause a conflict file though; that needs a reproducer or I don't think this can be resolved.

**Comment by buggyro** [comment] 2016-02-06 09:40
I have the same problem with conflict files.
My setup:
- 2 windows machines (win 8.1 and win 10) where the files are being modified
- 1 ubuntu 15.10 with BTRFS, allways-on machine for back-up and syncing when one of the windows machine is offline.
The problem seems to appear only when one of the windows machines are offline and the linux machine is used for syncing.
Could this be a Linux problem?

**Comment by calmh** [comment] 2016-02-11 10:08
I'd happily attribute whatever weirdness you're seeing to BTRFS as that seems to be a never ending source of WTF. Is this reproducible on ext4 or so?

**Comment by AudriusButkevicius** [comment] 2016-02-11 10:14
About the older file replacing newer files, possibly related to android and the way we check mtimes when resolving conflicts.

**Comment by buggyro** [comment] 2016-02-12 12:00
I did a little more digging.
The error logs show nothing (syncthing-inotify and syncthing).
If i work directly on the linux machine inotify picks up the change, but syncthing does not send it to the other computers.
Sadly i don't have a ext4 partition to test.
I have another Suse server that i setup for 3rd party, which doesn't have inotify, and has no problems.
I'll try to disable inotify to see if issue persists

**Comment by djtm** [comment] 2016-05-24 21:05
Hi, I still get this. Could I get some hints for debugging help? I haven't found any good sources on how to debug this kind of error specifically. I'm thinking maybe `STTRACE=files,scanner`?

I have:
```
one master folder,
one other node,
both linux, one i386, one amd64
```

The `other node` constantly has sync conflicts, though I never edit anything there, it's basically write only. They're both still on v. 0.12.25.

**Comment by djtm** [comment] 2016-05-24 21:34
relatime should't be the problem, it's actually the linux default since 2.6.30:

> Update  inode  access  times  relative to modify or change time.  Access time is only updated if the previous access time was earlier than the current modify or change time.  (Similar to noatime, but it doesn't break mutt or other applications that need to know if  a file has been read since the last time it was modified.)

lazytime should not be a problem either, it
> only updates times (atime, mtime, ctime) on the in-memory version of the file inode.

so a crash could lead to errors here.

A problem in ecryptfs would not be unthinkable either, happened before: https://bugzilla.kernel.org/show_bug.cgi?id=33372

**Comment by AudriusButkevicius** [comment] 2016-05-24 22:20
I bet if you drop ecryptfs you won't see it happen, so it's most likely ecryptfs that's causing it.

**Comment by djtm** [comment] 2016-05-26 11:38
Ok, I'll try that. Any hints on how to debug this? We rely on mtime, so I'll try to write a script that creates files and checks for correct mtime behavior with `stat  -c %Y`. 
If we get a problematic scenario due to ecryptfs, then the bug would really be a bug to file for the Linux kernel.

**Comment by djtm** [comment] 2016-05-26 14:39
I couldn't find more than 1 (possible) second of difference during testing and that second might be due to the way the script works.
Maybe it's got something to do with truecrypt, because that's typically where the problems occur for me. Though I've enabled truecrypt changing the mtime with `truecrypt -m ts`,  there might be the root of the  problem. I'll still try moving the share off ecryptfs now. The syncthing config dir shouldn't be a problem right?

**Comment by AudriusButkevicius** [comment] 2016-05-26 14:51
I don't understand the question.

**Comment by djtm** [comment] 2016-05-26 15:03
The fact that the **config** dir is on ecryptfs could not cause an issue, could it?

**Comment by AudriusButkevicius** [comment] 2016-05-26 15:21
Well if syncthing won't find it's config when starting it will potentially generate new content in that folder.
I am not sure what implications it will cause to encfs then trying to decrypt these unecrypted files.

Also, the db lives there, so havig an encryption penalty accessing the db is not ideal.

**Comment by djtm** [comment] 2016-05-26 15:22
Yes, but it shouldn't cause sync conflicts.

**Comment by AudriusButkevicius** [comment] 2016-05-26 15:23
Syncthings home folder being encrypted shouldn't, unless you are doing something mad like syncing syncthings own folder.

**Comment by djtm** [comment] 2016-05-30 14:01
Ok. Moving to ext4 didn't help. Anyone else using this with _truecrypt_?

**Comment by calmh** [comment] 2016-08-14 18:21
Quite sure this shouldn't happen now, with better modtime handling and so on. If it does, please open a *new issue* with steps to reproduce, as the above relates to 0.11.

**Closed by calmh** 2016-08-14 18:21 UTC
Labels: bug
