### ISSUE TITLE
v1.2.1-rc2 no client restart on upgrade

### ISSUE THREAD

**Issue by tezfair** [syncthing/syncthing#5869] opened 2019-07-18 12:43 UTC
After Synthing rc-1 upgraded to rc-2, all my windows based instances failed to restart after the upgrade and effectively crashed. I was able to recover a log from a synctrazor which may help

[RTF25] 19:57:31 INFO: Automatic upgrade (current “v1.2.1-rc.1” < latest “v1.2.1-rc.2”) 
[RTF25] 19:57:33 INFO: Connection to xxxxxxxxxxxx closed: Syncthing is being stopped 
[RTF25] 19:57:34 WARNING: Automatically upgraded to version “v1.2.1-rc.2”. Restarting in 1 minute. 
[RTF25] 19:57:50 INFO: Connection to xxxxxxxxxxxx closed: Syncthing is being stopped 
[RTF25] 19:58:11 INFO: Connection to xxxxxxxxxxxx closed: Syncthing is being stopped 
[RTF25] 19:58:34 INFO: QUIC listener ([::]:22000) shutting down 
[RTF25] 19:58:34 INFO: Connection to xxxxxxxxxxxx closed: Syncthing is being stopped 
[RTF25] 19:58:34 INFO: Connection to xxxxxxxxxxxx closed: Syncthing is being stopped 
[RTF25] 19:58:34 INFO: Connection to xxxxxxxxxxxx closed: Syncthing is being stopped 
[RTF25] 19:58:34 INFO: Connection to xxxxxxxxxxxx closed: Syncthing is being stopped 
[RTF25] 19:58:34 INFO: Connection to xxxxxxxxxxxx closed: Syncthing is being stopped 
[RTF25] 19:58:35 INFO: TCP listener ([::]:22000) shutting down 
[RTF25] 19:58:44 INFO: connections.Service: Service &util.service{serve:(func(chan struct {}) error)(0x8c82a0), stop:(chan struct {})(0xc0002d3080), stopped:(chan struct {})(0xc0002d30e0), err:error(nil), mut:(*sync.Mutex)(0xc000249ff8)} failed to terminate in a timely manner 2019/07/17 19:58:44 Supervisor discover.cachingMux: discover.cachingMux: Service IPv6 local failed to terminate in a timely manner 2019/07/17 19:58:44 Supervisor local: local: Service multicastBeacon failed to terminate in a timely manner 
[RTF25] 19:58:44 INFO: Exiting

this was on different PCs but affected all my Syncthing installations

**Comment by imsodin** [comment] 2019-07-18 12:52
This is a duplicate of https://github.com/syncthing/syncthing/issues/5860

And it isn't actually crashing and does restart correctly, it's just that before we didn't wait for those services nor log that they didn't stop properly. There's a PR in review that fixes this: #5863

**Comment by tezfair** [comment] 2019-07-18 13:02
Just to clarify, all my Syncthings were not running at all after the upgrade as your reply suggests they are restarted (unless they then crashed after the restart). I had no issue on any other version full or rc.

**Comment by imsodin** [comment] 2019-07-18 13:08
Thanks for the clarification. I just checked and the same is true here (running as systemd service). So it looks like there's a problem with the exit codes as well.

**Comment by imsodin** [comment] 2019-07-18 13:26
I can reproduce it also from UI without the service timeouts. Syncthing just generally returns with exit code 0 when it should restart. Most certainly due to #5805, I am looking into it.

**Closed** 2019-07-18 18:49 UTC
Labels: bug, skip-changelog
