### ISSUE TITLE
Puller inspecting strange directories

### ISSUE THREAD

**Issue by koppor** [syncthing/syncthing#4383] opened 2017-09-20 06:00 UTC
I got a huge output of strange directories when syncing:

```
[4QJNC] 07:56:04 INFO: Folder "BTSync" error is cleared, restarting
[4QJNC] 07:56:05 INFO: Puller (folder "BTSync", dir '\x00'): {Arbeiten\2017 - Tamara not a directory: .}
[4QJNC] 07:56:05 INFO: Puller (folder "BTSync", dir '\x01'): {Arbeiten\2017 - Tamara\ausarbeitung - comments OK.pdf not a directory: .}
[4QJNC] 07:56:05 INFO: Puller (folder "BTSync", dir '\x02'): {Projects\#2 Reviews\2017-10-10 - EMISA journal not a directory: .}
[4QJNC] 07:56:05 INFO: Puller (folder "BTSync", dir '\x03'): {Projects\#2 Reviews\2017-10-10 - EMISA journal\154-337-5-RV.pdf not a directory: .}
[4QJNC] 07:56:05 INFO: Puller (folder "BTSync", dir '\x04'): {Projects\#2 Reviews\Neuer Ordner not a directory: .}
[4QJNC] 07:56:05 INFO: Puller (folder "BTSync", dir '\x05'): {Projects\HiWis\HiWis - verantwortet von Olly.xlsx not a directory: .}
[4QJNC] 07:56:05 INFO: Puller (folder "BTSync", dir '\x06'): {lit\0 - bib\koppor-bibliography.bib.sav not a directory: .}
[4QJNC] 07:56:05 INFO: Puller (folder "BTSync", dir '\a'): {lit\0 - bib\koppor-bibliography.bib.sync-conflict-20170906-130728-4QJNCSX.sav not a directory: .}
[4QJNC] 07:56:05 INFO: Puller (folder "BTSync", dir '\b'): {software-portable\JabRef-dev-fat.jar not a directory: .}
[4QJNC] 07:56:05 INFO: Puller (folder "BTSync", dir '\t'): {software-portable\Tor Browser\Browser\AccessibleMarshal.dll not a directory: .}
[4QJNC] 07:56:05 INFO: Puller (folder "BTSync", dir '\n'): {software-portable\Tor Browser\Browser\IA2Marshal.dll not a directory: .}
[4QJNC] 07:56:05 INFO: Puller (folder "BTSync", dir '\v'): {software-portable\Tor Browser\Browser\TorBrowser\Data\Browser\Caches\profile.default\directoryLinks.json not a directory: .}
```

It seems that a certain sequence of ASCII characters are checked as directory:

<details>
[4QJNC] 07:58:06 INFO: Folder "BTSync" error is cleared, restarting
[4QJNC] 07:58:08 INFO: Puller (folder "BTSync", dir '\x00'): {Arbeiten\2017 - Tamara not a directory: .}
[4QJNC] 07:58:08 INFO: Puller (folder "BTSync", dir '\x01'): {Arbeiten\2017 - Tamara\ausarbeitung - comments OK.pdf not a directory: .}
[4QJNC] 07:58:08 INFO: Puller (folder "BTSync", dir '\x02'): {Projects\#2 Reviews\2017-10-10 - EMISA journal not a directory: .}
[4QJNC] 07:58:08 INFO: Puller (folder "BTSync", dir '\x03'): {Projects\#2 Reviews\2017-10-10 - EMISA journal\154-337-5-RV.pdf not a directory: .}
[4QJNC] 07:58:08 INFO: Puller (folder "BTSync", dir '\x04'): {Projects\#2 Reviews\Neuer Ordner not a directory: .}
[4QJNC] 07:58:08 INFO: Puller (folder "BTSync", dir '\x05'): {Projects\HiWis\HiWis - verantwortet von Olly.xlsx not a directory: .}
[4QJNC] 07:58:08 INFO: Puller (folder "BTSync", dir '\x06'): {lit\0 - bib\koppor-bibliography.bib.sav not a directory: .}
[4QJNC] 07:58:08 INFO: Puller (folder "BTSync", dir '\a'): {lit\0 - bib\koppor-bibliography.bib.sync-conflict-20170906-130728-4QJNCSX.sav not a directory: .}
[4QJNC] 07:58:08 INFO: Puller (folder "BTSync", dir '\b'): {software-portable\JabRef-dev-fat.jar not a directory: .}
[4QJNC] 07:58:08 INFO: Puller (folder "BTSync", dir '\t'): {software-portable\Tor Browser\Browser\AccessibleMarshal.dll not a directory: .}
[4QJNC] 07:58:08 INFO: Puller (folder "BTSync", dir '\n'): {software-portable\Tor Browser\Browser\IA2Marshal.dll not a directory: .}
[4QJNC] 07:58:08 INFO: Puller (folder "BTSync", dir '\v'): {software-portable\Tor Browser\Browser\TorBrowser\Data\Browser\Caches\profile.default\directoryLinks.json not a directory: .}
[4QJNC] 07:58:08 INFO: Puller (folder "BTSync", dir '\f'): {software-portable\Tor Browser\Browser\TorBrowser\Data\Browser\Caches\profile.default\frequencyCap.json not a directory: .}
[4QJNC] 07:58:08 INFO: Puller (folder "BTSync", dir '\r'): {software-portable\Tor Browser\Browser\TorBrowser\Data\Browser\Caches\profile.default\safebrowsing\test-block-simple.pset not a directory: .}
[4QJNC] 07:58:08 INFO: Puller (folder "BTSync", dir '\x0e'): {software-portable\Tor Browser\Browser\TorBrowser\Data\Browser\Caches\profile.default\safebrowsing\test-block-simple.sbstore not a directory: .}
[4QJNC] 07:58:08 INFO: Puller (folder "BTSync", dir '\x0f'): {software-portable\Tor Browser\Browser\TorBrowser\Data\Browser\Caches\profile.default\safebrowsing\test-flash-simple.pset not a directory: .}
[4QJNC] 07:58:08 INFO: Puller (folder "BTSync", dir '\x10'): {software-portable\Tor Browser\Browser\TorBrowser\Data\Browser\Caches\profile.default\safebrowsing\test-flash-simple.sbstore not a directory: .}
[4QJNC] 07:58:08 INFO: Puller (folder "BTSync", dir '\x11'): {software-portable\Tor Browser\Browser\TorBrowser\Data\Browser\Caches\profile.default\safebrowsing\test-flashallow-simple.pset not a directory: .}
[4QJNC] 07:58:08 INFO: Puller (folder "BTSync", dir '\x12'): {software-portable\Tor Browser\Browser\TorBrowser\Data\Browser\Caches\profile.default\safebrowsing\test-flashallow-simple.sbstore not a directory: .}
[4QJNC] 07:58:08 INFO: Puller (folder "BTSync", dir '\x13'): {software-portable\Tor Browser\Browser\TorBrowser\Data\Browser\Caches\profile.default\safebrowsing\test-flashsubdoc-simple.pset not a directory: .}
[4QJNC] 07:58:08 INFO: Puller (folder "BTSync", dir '\x14'): {software-portable\Tor Browser\Browser\TorBrowser\Data\Browser\Caches\profile.default\safebrowsing\test-flashsubdoc-simple.sbstore not a directory: .}
[4QJNC] 07:58:08 INFO: Puller (folder "BTSync", dir '\x15'): {software-portable\Tor Browser\Browser\TorBrowser\Data\Browser\Caches\profile.default\safebrowsing\test-malware-simple.pset not a directory: .}
[4QJNC] 07:58:08 INFO: Puller (folder "BTSync", dir '\x16'): {software-portable\Tor Browser\Browser\TorBrowser\Data\Browser\Caches\profile.default\safebrowsing\test-malware-simple.sbstore not a directory: .}
[4QJNC] 07:58:08 INFO: Puller (folder "BTSync", dir '\x17'): {software-portable\Tor Browser\Browser\TorBrowser\Data\Browser\Caches\profile.default\safebrowsing\test-phish-simple.pset not a directory: .}
[4QJNC] 07:58:08 INFO: Puller (folder "BTSync", dir '\x18'): {software-portable\Tor Browser\Browser\TorBrowser\Data\Browser\Caches\profile.default\safebrowsing\test-phish-simple.sbstore not a directory: .}
[4QJNC] 07:58:08 INFO: Puller (folder "BTSync", dir '\x19'): {software-portable\Tor Browser\Browser\TorBrowser\Data\Browser\Caches\profile.default\safebrowsing\test-track-simple.pset not a directory: .}
[4QJNC] 07:58:08 INFO: Puller (folder "BTSync", dir '\x1a'): {software-portable\Tor Browser\Browser\TorBrowser\Data\Browser\Caches\profile.default\safebrowsing\test-track-simple.sbstore not a directory: .}
[4QJNC] 07:58:08 INFO: Puller (folder "BTSync", dir '\x1b'): {software-portable\Tor Browser\Browser\TorBrowser\Data\Browser\Caches\profile.default\safebrowsing\test-trackwhite-simple.pset not a directory: .}
[4QJNC] 07:58:08 INFO: Puller (folder "BTSync", dir '\x1c'): {software-portable\Tor Browser\Browser\TorBrowser\Data\Browser\Caches\profile.default\safebrowsing\test-trackwhite-simple.sbstore not a directory: .}
[4QJNC] 07:58:08 INFO: Puller (folder "BTSync", dir '\x1d'): {software-portable\Tor Browser\Browser\TorBrowser\Data\Browser\Caches\profile.default\safebrowsing\test-unwanted-simple.pset not a directory: .}
[4QJNC] 07:58:08 INFO: Puller (folder "BTSync", dir '\x1e'): {software-portable\Tor Browser\Browser\TorBrowser\Data\Browser\Caches\profile.default\safebrowsing\test-unwanted-simple.sbstore not a directory: .}
[4QJNC] 07:58:08 INFO: Puller (folder "BTSync", dir '\x1f'): {software-portable\Tor Browser\Browser\TorBrowser\Data\Browser\Caches\profile.default\safebrowsing\testexcept-flash-simple.pset not a directory: .}
[4QJNC] 07:58:08 INFO: Puller (folder "BTSync", dir ' '): {software-portable\Tor Browser\Browser\TorBrowser\Data\Browser\Caches\profile.default\safebrowsing\testexcept-flash-simple.sbstore not a directory: .}
[4QJNC] 07:58:08 INFO: Puller (folder "BTSync", dir '!'): {software-portable\Tor Browser\Browser\TorBrowser\Data\Browser\Caches\profile.default\safebrowsing\testexcept-flashallow-simple.pset not a directory: .}
[4QJNC] 07:58:08 INFO: Puller (folder "BTSync", dir '"'): {software-portable\Tor Browser\Browser\TorBrowser\Data\Browser\Caches\profile.default\safebrowsing\testexcept-flashallow-simple.sbstore not a directory: .}
[4QJNC] 07:58:08 INFO: Puller (folder "BTSync", dir '#'): {software-portable\Tor Browser\Browser\TorBrowser\Data\Browser\Caches\profile.default\safebrowsing\testexcept-flashsubdoc-simple.pset not a directory: .}
[4QJNC] 07:58:08 INFO: Puller (folder "BTSync", dir '$'): {software-portable\Tor Browser\Browser\TorBrowser\Data\Browser\Caches\profile.default\safebrowsing\testexcept-flashsubdoc-simple.sbstore not a directory: .}
[4QJNC] 07:58:08 INFO: Puller (folder "BTSync", dir '%'): {software-portable\Tor Browser\Browser\TorBrowser\Data\Browser\Caches\profile.default\startupCache\startupCache.4.little not a directory: .}
[4QJNC] 07:58:08 INFO: Puller (folder "BTSync", dir '&'): {software-portable\Tor Browser\Browser\TorBrowser\Data\Browser\profile.default\SecurityPreloadState.txt not a directory: .}
[4QJNC] 07:58:08 INFO: Puller (folder "BTSync", dir '\''): {software-portable\Tor Browser\Browser\TorBrowser\Data\Browser\profile.default\SiteSecurityServiceState.txt not a directory: .}
[4QJNC] 07:58:08 INFO: Puller (folder "BTSync", dir '('): {software-portable\Tor Browser\Browser\TorBrowser\Data\Browser\profile.default\blocklist.xml not a directory: .}
[4QJNC] 07:58:08 INFO: Puller (folder "BTSync", dir ')'): {software-portable\Tor Browser\Browser\TorBrowser\Data\Browser\profile.default\browser-extension-data\{73a6fe31-595d-460b-a920-fcc0f8843232}\storage.js not a directory: .}
[4QJNC] 07:58:08 INFO: Puller (folder "BTSync", dir '*'): {software-portable\Tor Browser\Browser\TorBrowser\Data\Browser\profile.default\compatibility.ini not a directory: .}
[4QJNC] 07:58:08 INFO: Puller (folder "BTSync", dir '+'): {software-portable\Tor Browser\Browser\TorBrowser\Data\Browser\profile.default\extensions.ini not a directory: .}
[4QJNC] 07:58:08 INFO: Puller (folder "BTSync", dir ','): {software-portable\Tor Browser\Browser\TorBrowser\Data\Browser\profile.default\extensions.json not a directory: .}
[4QJNC] 07:58:08 INFO: Puller (folder "BTSync", dir '-'): {software-portable\Tor Browser\Browser\TorBrowser\Data\Browser\profile.default\extensions\https-everywhere-eff@eff.org.xpi not a directory: .}
[4QJNC] 07:58:08 INFO: Puller (folder "BTSync", dir '.'): {software-portable\Tor Browser\Browser\TorBrowser\Data\Browser\profile.default\extensions\staged not a directory: .}
[4QJNC] 07:58:08 INFO: Puller (folder "BTSync", dir '/'): {software-portable\Tor Browser\Browser\TorBrowser\Data\Browser\profile.default\extensions\staged\https-everywhere-eff@eff.org.json not a directory: .}
[4QJNC] 07:58:08 INFO: Puller (folder "BTSync", dir '0'): {software-portable\Tor Browser\Browser\TorBrowser\Data\Browser\profile.default\extensions\staged\https-everywhere-eff@eff.org.xpi not a directory: .}
[4QJNC] 07:58:08 INFO: Puller (folder "BTSync", dir '1'): {software-portable\Tor Browser\Browser\TorBrowser\Data\Browser\profile.default\extensions\staged\{73a6fe31-595d-460b-a920-fcc0f8843232}.json not a directory: .}
[4QJNC] 07:58:08 INFO: Puller (folder "BTSync", dir '2'): {software-portable\Tor Browser\Browser\TorBrowser\Data\Browser\profile.default\extensions\staged\{73a6fe31-595d-460b-a920-fcc0f8843232}.xpi not a directory: .}
[4QJNC] 07:58:08 INFO: Puller (folder "BTSync", dir '3'): {software-portable\Tor Browser\Browser\TorBrowser\Data\Browser\profile.default\extensions\tor-launcher@torproject.org.xpi not a directory: .}
[4QJNC] 07:58:08 INFO: Puller (folder "BTSync", dir '4'): {software-portable\Tor Browser\Browser\TorBrowser\Data\Browser\profile.default\extensions\torbutton@torproject.org.xpi not a directory: .}
[4QJNC] 07:58:08 INFO: Puller (folder "BTSync", dir '5'): {software-portable\Tor Browser\Browser\TorBrowser\Data\Browser\profile.default\extensions\{73a6fe31-595d-460b-a920-fcc0f8843232}.xpi not a directory: .}
[4QJNC] 07:58:08 INFO: Puller (folder "BTSync", dir '6'): {software-portable\Tor Browser\Browser\TorBrowser\Data\Browser\profile.default\parent.lock not a directory: .}
[4QJNC] 07:58:08 INFO: Puller (folder "BTSync", dir '7'): {software-portable\Tor Browser\Browser\TorBrowser\Data\Browser\profile.default\places.sqlite-shm not a directory: .}
[4QJNC] 07:58:08 INFO: Puller (folder "BTSync", dir '8'): {software-portable\Tor Browser\Browser\TorBrowser\Data\Browser\profile.default\preferences\extension-overrides.js not a directory: .}
[4QJNC] 07:58:08 INFO: Puller (folder "BTSync", dir '9'): {software-portable\Tor Browser\Browser\TorBrowser\Data\Browser\profile.default\prefs.js not a directory: .}
[4QJNC] 07:58:08 INFO: Puller (folder "BTSync", dir ':'): {software-portable\Tor Browser\Browser\TorBrowser\Data\Browser\profile.default\search.json.mozlz4 not a directory: .}
[4QJNC] 07:58:08 INFO: Puller (folder "BTSync", dir ';'): {software-portable\Tor Browser\Browser\TorBrowser\Data\Browser\profile.default\sessionCheckpoints.json not a directory: .}
[4QJNC] 07:58:08 INFO: Puller (folder "BTSync", dir '<'): {software-portable\Tor Browser\Browser\TorBrowser\Data\Browser\profile.default\xulstore.json not a directory: .}
[4QJNC] 07:58:08 INFO: Puller (folder "BTSync", dir '='): {software-portable\Tor Browser\Browser\TorBrowser\Data\Tor\cached-certs not a directory: .}
[4QJNC] 07:58:08 INFO: Puller (folder "BTSync", dir '>'): {software-portable\Tor Browser\Browser\TorBrowser\Data\Tor\cached-microdesc-consensus not a directory: .}
[4QJNC] 07:58:08 INFO: Puller (folder "BTSync", dir '?'): {software-portable\Tor Browser\Browser\TorBrowser\Data\Tor\cached-microdescs not a directory: .}
[4QJNC] 07:58:08 INFO: Puller (folder "BTSync", dir '@'): {software-portable\Tor Browser\Browser\TorBrowser\Data\Tor\cached-microdescs.new not a directory: .}
[4QJNC] 07:58:08 INFO: Puller (folder "BTSync", dir 'A'): {software-portable\Tor Browser\Browser\TorBrowser\Data\Tor\control_auth_cookie not a directory: .}
[4QJNC] 07:58:08 INFO: Puller (folder "BTSync", dir 'B'): {software-portable\Tor Browser\Browser\TorBrowser\Data\Tor\geoip not a directory: .}
[4QJNC] 07:58:08 INFO: Puller (folder "BTSync", dir 'C'): {software-portable\Tor Browser\Browser\TorBrowser\Data\Tor\geoip6 not a directory: .}
[4QJNC] 07:58:08 INFO: Puller (folder "BTSync", dir 'D'): {software-portable\Tor Browser\Browser\TorBrowser\Data\Tor\lock not a directory: .}
[4QJNC] 07:58:08 INFO: Puller (folder "BTSync", dir 'E'): {software-portable\Tor Browser\Browser\TorBrowser\Data\Tor\state not a directory: .}
[4QJNC] 07:58:08 INFO: Puller (folder "BTSync", dir 'F'): {software-portable\Tor Browser\Browser\TorBrowser\Docs\ChangeLog.txt not a directory: .}
[4QJNC] 07:58:08 INFO: Puller (folder "BTSync", dir 'G'): {software-portable\Tor Browser\Browser\TorBrowser\Docs\sources\bundle.inputs not a directory: .}
[4QJNC] 07:58:08 INFO: Puller (folder "BTSync", dir 'H'): {software-portable\Tor Browser\Browser\TorBrowser\Docs\sources\versions not a directory: .}
[4QJNC] 07:58:08 INFO: Puller (folder "BTSync", dir 'I'): {software-portable\Tor Browser\Browser\TorBrowser\Tor\tor.exe not a directory: .}
[4QJNC] 07:58:08 INFO: Puller (folder "BTSync", dir 'J'): {software-portable\Tor Browser\Browser\TorBrowser\UpdateInfo\active-update.xml not a directory: .}
[4QJNC] 07:58:08 INFO: Puller (folder "BTSync", dir 'K'): {software-portable\Tor Browser\Browser\TorBrowser\UpdateInfo\updates.xml not a directory: .}
[4QJNC] 07:58:08 INFO: Puller (folder "BTSync", dir 'L'): {software-portable\Tor Browser\Browser\TorBrowser\UpdateInfo\updates\0\update.mar not a directory: .}
[4QJNC] 07:58:08 INFO: Puller (folder "BTSync", dir 'M'): {software-portable\Tor Browser\Browser\TorBrowser\UpdateInfo\updates\0\update.status not a directory: .}
[4QJNC] 07:58:08 INFO: Puller (folder "BTSync", dir 'N'): {software-portable\Tor Browser\Browser\TorBrowser\UpdateInfo\updates\0\update.version not a directory: .}
[4QJNC] 07:58:08 INFO: Puller (folder "BTSync", dir 'O'): {software-portable\Tor Browser\Browser\TorBrowser\UpdateInfo\updates\backup-update.log not a directory: .}
[4QJNC] 07:58:08 INFO: Puller (folder "BTSync", dir 'P'): {software-portable\Tor Browser\Browser\TorBrowser\UpdateInfo\updates\last-update.log not a directory: .}
[4QJNC] 07:58:08 INFO: Puller (folder "BTSync", dir 'Q'): {software-portable\Tor Browser\Browser\application.ini not a directory: .}
[4QJNC] 07:58:08 INFO: Puller (folder "BTSync", dir 'R'): {software-portable\Tor Browser\Browser\browser\blocklist.xml not a directory: .}
[4QJNC] 07:58:08 INFO: Puller (folder "BTSync", dir 'S'): {software-portable\Tor Browser\Browser\browser\extensions\{972ce4c6-7e08-4474-a285-3208198ce6fd}.xpi not a directory: .}
[4QJNC] 07:58:08 INFO: Puller (folder "BTSync", dir 'T'): {software-portable\Tor Browser\Browser\browser\features\e10srollout@mozilla.org.xpi not a directory: .}
[4QJNC] 07:58:08 INFO: Puller (folder "BTSync", dir 'U'): {software-portable\Tor Browser\Browser\browser\omni.ja not a directory: .}
[4QJNC] 07:58:08 INFO: Puller (folder "BTSync", dir 'V'): {software-portable\Tor Browser\Browser\chrome.manifest not a directory: .}
[4QJNC] 07:58:08 INFO: Puller (folder "BTSync", dir 'W'): {software-portable\Tor Browser\Browser\firefox.exe not a directory: .}
[4QJNC] 07:58:08 INFO: Puller (folder "BTSync", dir 'X'): {software-portable\Tor Browser\Browser\lgpllibs.dll not a directory: .}
[4QJNC] 07:58:08 INFO: Puller (folder "BTSync", dir 'Y'): {software-portable\Tor Browser\Browser\libEGL.dll not a directory: .}
[4QJNC] 07:58:08 INFO: Puller (folder "BTSync", dir 'Z'): {software-portable\Tor Browser\Browser\libGLESv2.dll not a directory: .}
[4QJNC] 07:58:08 INFO: Puller (folder "BTSync", dir '['): {software-portable\Tor Browser\Browser\mozavcodec.dll not a directory: .}
[4QJNC] 07:58:08 INFO: Puller (folder "BTSync", dir '\\'): {software-portable\Tor Browser\Browser\mozavutil.dll not a directory: .}
[4QJNC] 07:58:08 INFO: Puller (folder "BTSync", dir ']'): {software-portable\Tor Browser\Browser\mozglue.dll not a directory: .}
[4QJNC] 07:58:08 INFO: Puller (folder "BTSync", dir '^'): {software-portable\Tor Browser\Browser\nss3.dll not a directory: .}
[4QJNC] 07:58:08 INFO: Puller (folder "BTSync", dir '_'): {software-portable\Tor Browser\Browser\omni.ja not a directory: .}
[4QJNC] 07:58:08 INFO: Puller (folder "BTSync", dir '`'): {software-portable\Tor Browser\Browser\platform.ini not a directory: .}
[4QJNC] 07:58:08 INFO: Puller (folder "BTSync", dir 'a'): {software-portable\Tor Browser\Browser\plugin-container.exe not a directory: .}
[4QJNC] 07:58:08 INFO: Puller (folder "BTSync", dir 'b'): {software-portable\Tor Browser\Browser\plugin-hang-ui.exe not a directory: .}
[4QJNC] 07:58:08 INFO: Puller (folder "BTSync", dir 'c'): {software-portable\Tor Browser\Browser\precomplete not a directory: .}
[4QJNC] 07:58:08 INFO: Puller (folder "BTSync", dir 'd'): {software-portable\Tor Browser\Browser\qipcap.dll not a directory: .}
[4QJNC] 07:58:08 INFO: Puller (folder "BTSync", dir 'e'): {software-portable\Tor Browser\Browser\removed-files not a directory: .}
[4QJNC] 07:58:08 INFO: Puller (folder "BTSync", dir 'f'): {software-portable\Tor Browser\Browser\updater.exe not a directory: .}
[4QJNC] 07:58:08 INFO: Puller (folder "BTSync", dir 'g'): {software-portable\Tor Browser\Browser\xul.dll not a directory: .}
[4QJNC] 07:58:08 INFO: Folder "BTSync" isn't making progress. Pausing puller for 1m0s.
</details>

### Version Information

Syncthing Version: v0.14.38, Windows (64 bit) 
OS Version: Windows 10

**Comment by calmh** [comment] 2017-09-20 06:12
Yeah, that's a logging bug.

Duplicate of #4375.

**Closed by calmh** 2017-09-20 06:12 UTC
