### ISSUE TITLE
Syncthing gets stuck when Unix creates folder and file with different case in name

### ISSUE THREAD

**Issue by JonasT** [syncthing/syncthing#2007] opened 2015-06-27 11:54 UTC
When having a folder synced between windows and linux, then shutting down windows, creating something on linux like a file named ```python``` and a folder named ```Python``` in the same place, then booting windows and attempting to sync, syncthing is very much not happy:

```[FWQAX] 13:40:56 INFO: Puller: final: open \\?\D:\sims4mod\python-3.3.5\Python-3.3.5\Python\~syncthing~thread.o.tmp: Das System kann den angegebenen Pfad nicht finden.
[FWQAX] 13:40:56 INFO: Puller (folder "sims4mod", file "python-3.3.5\\Python-3.3.5\\Python\\pyfpe.o"): dst create: open \\?\D:\sims4mod\python-3.3.5\Python-3.3.5\Python\~syncthing~pyfpe.o.tmp: Das System kann den angegebenen Pfad nicht finden.
[FWQAX] 13:40:56 INFO: Puller: final: open \\?\D:\sims4mod\python-3.3.5\Python-3.3.5\Python\~syncthing~pyfpe.o.tmp: Das System kann den angegebenen Pfad nicht finden.
[FWQAX] 13:40:56 INFO: Puller (folder "sims4mod", file "python-3.3.5\\Python-3.3.5\\Python\\compile.c"): dst create: open \\?\D:\sims4mod\python-3.3.5\Python-3.3.5\Python\~syncthing~compile.c.tmp: Das System kann den angegebenen Pfad nicht finden.
[FWQAX] 13:40:56 INFO: Puller: final: open \\?\D:\sims4mod\python-3.3.5\Python-3.3.5\Python\~syncthing~compile.c.tmp: Das System kann den angegebenen Pfad nicht finden.
[FWQAX] 13:40:56 WARNING: Folder "sims4mod" isn't making progress - check logs for possible root cause. Pausing puller for 1m0s.```
with ```
Das System kann den angegebenen Pfad nicht finden.``` being ```
the system cannot find the given path``` which I think is the equivalent to ```no such file or directory```.

I can't tell you what the best solution is (since obviously on windows you can't create files with those names), but the current hanging with ```
Folder "sims4mod" isn't making progress - check logs for possible root cause``` and refusing to do anything useful from that point on can't be it.

I guess this should simply be handled as a regular conflict similar to other edit conflicts? It certainly shouldn't syncthing cause to fail syncing entirely with log error spam as it appears to be the case right now.

**Comment by AudriusButkevicius** [comment] 2015-06-27 13:51
I think this is a duplicate of: https://github.com/syncthing/syncthing/issues/1787 ?

**Comment by Zillode** [comment] 2015-07-31 19:52
Agreed

**Closed by Zillode** 2015-07-31 19:52 UTC
