### ISSUE TITLE
Display error unknown device

### ISSUE THREAD

**Issue by 3dde** [syncthing/syncthing#9295] opened 2023-12-18 17:39 UTC
I'm using a user service of syncthing 1.26.1 on fedora 39. I don't know if this issue is recent, or if it already occurred in previous versions, but I noticed it today:

When logging into the web interface, I get the following:
![Screenshot_20231218_182904](https://github.com/syncthing/syncthing/assets/73657699/452a2f7d-afe7-430f-9287-ebf0fa349a30)

I've tried using Brave and Firefox, both with the same result, I've tried going back to basic http auth (as mentioned in #9208) and I've tried restarting the browser and clearing cookies. Nothing worked so far. The logs also don't indicate any problem. Any ideas what might have caused this, and how it can be fixed? Syncthing continues to sync just normally in the background, so I think it should be just an issue with the web interface.

**Comment by imsodin** [comment] 2023-12-19 23:08
Duplicate of https://github.com/syncthing/syncthing/issues/9208

Updating to >=1.27.0 or clearing cookies should fix the issue.

**Closed by imsodin** 2023-12-19 23:08 UTC
Labels: bug, needs-triage

**Comment by 3dde** [comment] 2023-12-19 23:30
I assumed that because the fix didn't work, this was a different issue. But I'll wait for the update and report back if the issue still persists. Thank you!
