### ISSUE TITLE
lib/symlinks: Problem with symlinks if syncthing for windows is running

### ISSUE THREAD

**Issue by n86io** [syncthing/syncthing#3857] opened 2017-01-01 19:08 UTC
Here the problem.

![syncthing](https://cloud.githubusercontent.com/assets/8514256/21582523/6a29c276-d05c-11e6-9ae6-b94726153196.png)

In fact, no single change are happened, but the global changes show it and synced every displayed "change".

This happened only, if syncthing for windows is running. If i shutdown the windows-syncthing and use only unix-based (Ubuntu 16.04 and macOS Sierra) syncthing versions, this error not happened.

It only happened with folder-symlinks, not with file-symlinks.

### Version Information

Syncthing Version: v0.14.18 (I have noticed that already in v0.14.17)
OS Version: Windows 10 (Pro and Home)

**Comment by calmh** [comment] 2017-01-01 20:00
.17 or .18 shouldn't matter here. This looks like a real problem to me.

**Comment by AudriusButkevicius** [comment] 2017-01-01 20:26
I suspect one of the nodes participating is pre-symlink field, and uses blocks instead, hence permanently bounces as one stores it the field, other stores in the block.

**Comment by n86io** [comment] 2017-01-01 21:31
The version information is in my opinion clear enough, to know how version i use and it's clear to me, that an upgrade can possible clear some problems, if new updates available.

I had the problem with .17 and have it now also with .18

With .14 i have also delete this symlinks and created new.

**Comment by AudriusButkevicius** [comment] 2017-01-01 21:56
I am not talking about a single version, I am talking about all devices involved. The fact that changes come from unknown device imply an old version.

**Comment by n86io** [comment] 2017-01-02 08:02
No, all devices use .18. And if i make a change on a windows device, in global changes it shows, that it come from the windows device, but not for the symlink problem.

**Comment by calmh** [comment] 2017-01-02 08:59
I'm fairly sure this is a genuine bug so we can stop doubting @n86io :) There is code to prevent sending new format symlink entries to old versions, even.

**Comment by AudriusButkevicius** [comment] 2017-01-02 09:12
Yet I am still suspicious about the unset ModifiedBy in the screenshots.

**Comment by n86io** [comment] 2017-01-02 09:37
Sorry @AudriusButkevicius, but i have no reason, to mislead you or other developers and i have no time for such silly things. ;-)

**Comment by nrm21** [comment] 2017-01-05 02:16
I'm having a hard time duplicating this:

Client 1:   Windows 10  14393.576
Client 2:   Windows 10  14393.576

When I make either dir or regular symlink on either client I get no sync of any file and no mention of it in the log.  ST just ignores them, which I understand to be the correct behavior.

**Comment by calmh** [comment] 2017-01-05 02:33
Syncthing probably needs to run as administrator to sync the symlinks. If it does that, the links should sync properly in Windows as well.

(I suspect they won't, but they *should*.)

**Comment by nrm21** [comment] 2017-01-05 02:52
Ok so I have it working now... when I create symlink on Windows (using mklink.exe at the admin CLI) I get a symlink (surprise), but... on first sync it makes a .symlink file on the other windows box, which is not recognized as a symlink... just a plain file that is a type .symlink.

Windows parses filnames in filename.ext format so maybe it's just getting conused that there is nothing before the dot and so thinking thats the filetype.

Whatever... anyway, after that the next scan, few secs later (on the receiver) it then resyncs that file back clobbering the original valid symlink with this .symlink file so they both have the crappy one.

**Comment by AudriusButkevicius** [comment] 2017-01-05 08:16
Unknown is for blank, but it should never be blank.

**Comment by calmh** [comment] 2017-01-05 10:13
Wow, this is broken. I figured I'd test this out.

- Started my Win10
- Command prompt as administrator
- `mkdir c:\test1`
- `mklink /d c:\test1 c:\Windows`

<img width="445" alt="screen shot 2017-01-05 at 11 12 22" src="https://cloud.githubusercontent.com/assets/125426/21676873/e2a09382-d337-11e6-8953-19463cfcc9cd.png">

- Start a new blank syncthing instance, 0.14.18 downloaded from github
- Add `c:\test1` as a folder, figured I'd see what it adds to the index and then see what gets synced

<img width="525" alt="screen shot 2017-01-05 at 11 13 31" src="https://cloud.githubusercontent.com/assets/125426/21676903/04700650-d338-11e6-9666-53be2c1a254f.png">

It follows the shit out of that symlink...

**Comment by AudriusButkevicius** [comment] 2017-01-05 10:25
It follows as it's at the root, so it makes sense.

**Comment by calmh** [comment] 2017-01-05 10:25
It's not at the root

**Comment by calmh** [comment] 2017-01-05 10:27
A file type symlink that does not exist gets synced correctly, but the global log looks like @nrm21 says (type "file" even).

<img width="504" alt="screen shot 2017-01-05 at 11 26 53" src="https://cloud.githubusercontent.com/assets/125426/21677316/e6471266-d339-11e6-99c8-818a3d689b3f.png">

<img width="817" alt="screen shot 2017-01-05 at 11 26 37" src="https://cloud.githubusercontent.com/assets/125426/21677330/eca61d5a-d339-11e6-85d0-885c3df070e3.png">

**Comment by AudriusButkevicius** [comment] 2017-01-05 10:29
Ah yes, it's not at the root. Regarding Unknown I suspect we are not setting ModifiedBy somewhere.

**Comment by AudriusButkevicius** [comment] 2017-01-05 10:30
And yes, following the link... Wtf.

**Comment by calmh** [comment] 2017-01-05 10:41
Wow, this is *really* weird.

I created a recursive directory symlink, `c:\test1\dir\recursive -> c:\test1`, and

1. Syncthing follows it, gets infinite recursion and breaks the sync
2. `dir /s` also does infinite recursion until it breaks

<img width="925" alt="screen shot 2017-01-05 at 11 38 00" src="https://cloud.githubusercontent.com/assets/125426/21677680/787834ca-d33b-11e6-85fa-18dbfb6fce47.png">

I poke around a little, and now `dir /s` does *not* do recursion any more. Look at it closely, the symlink type has changed from `SYMLINKD` to `SYMLINK` and is not followed. Create another one with `mklink /d` and we're back in recursion land.

**Comment by AudriusButkevicius** [comment] 2017-01-05 10:44
How are they different?

**Comment by calmh** [comment] 2017-01-05 10:46
Even `dir` doesn't understand them enough to not follow them into eternal recursion. Apparently our scanner sees them as real directories and follows them, even though we try hard to avoid that. The type of the symlink changed under my feet and now it's no longer followed. What the fuck is going on here?

**Comment by AudriusButkevicius** [comment] 2017-01-05 10:52
Syncthing is probably changing the type, and I am sure we did not follow them in Go 1.5 + when the code was added, yeah stdlib changed, our code changed, it's possible its screwed now.

**Comment by calmh** [comment] 2017-01-05 14:02
Yep, the typing is wrong, and perhaps that's what's gets triggered every scan.

<img width="502" alt="screen shot 2017-01-05 at 15 00 48" src="https://cloud.githubusercontent.com/assets/125426/21683039/e0a77238-d357-11e6-944c-732bbee69863.png">

<img width="401" alt="screen shot 2017-01-05 at 15 00 59" src="https://cloud.githubusercontent.com/assets/125426/21683042/e3d20d88-d357-11e6-8a33-55495938a9e7.png">

<img width="611" alt="screen shot 2017-01-05 at 15 01 04" src="https://cloud.githubusercontent.com/assets/125426/21683050/e81e5c5c-d357-11e6-9fe1-184c301be54a.png">

**Comment by calmh** [comment] 2017-01-05 15:22
v0.13.10 doesn't sync any symlinks at all, ever, on Windows as far as I can tell. Even when enabled and running as administrator, when v0.14.18 actually does sync symlinks (but fail). So it's broken there as well.

Which brings me back to why even try maintaining this functionality when it's been broken since way back, noone seems to care, and we don't really have testing procedures for it?

**Comment by AudriusButkevicius** [comment] 2017-01-05 15:30
Windows symlinks, yeah fine, others are probably bein used.

**Comment by calmh** [comment] 2017-01-05 15:33
Oh yes, fully agree. But those don't have types, don't get followed by default, don't require admin for usage, etc. so are in general much easier to test and keep working somewhat securely...

**Comment by nrm21** [comment] 2017-01-05 15:35
As a (mostly) windows user I can tell you that very few Windows users use symlinks.  It's no where near as pervasive as Linux.  So if it gets removed, few will cry.  Though those that do will cry loudly.

And on that subject:
https://xkcd.com/1172/

**Comment by Ferroin** [comment] 2017-01-05 15:41
Agreed, I can attest that even as a sysadmin and power user, I only ever use symlinks on windows to work around poorly written applications that have hard-coded paths (or refuse to behave properly when migrating data to a different location).

The fact that it's been admin only (although the next build of 10 will supposedly remove that restriction when in developer mode) since it's inception, and that traditional styled links (which Syncthing syncs correctly, and are more correctly equivalent to .desktop files on Linux), reparse points, and directory junctions cover the typical usages in more versatile ways means that they're pretty much unused by sane, security conscious people.

**Comment by AudriusButkevicius** [comment] 2017-01-05 15:45
I am fine to drop symlinks on windows.

**Comment by PanderMusubi** [comment] 2017-01-10 10:21
Perhaps add some warnings on both sides when encountering syncing of symlinks to MS Windows?

**Comment by calmh** [comment] 2017-02-07 12:33
Resolved by #3962, such as it is.

**Closed by calmh** 2017-02-07 12:33 UTC
Labels: bug

**Comment by SoepStengel** [comment] 2017-10-02 20:19
Ok I cry! Syncthing used to sync perfectly with a junction (made with sysinternals junction) a few versions ago. After upgrading to a version I don't remember, the directory was not recognized anymore (Error: not a directory). Are symlinks/junctions really not supported anymore?

**Comment by AudriusButkevicius** [comment] 2017-10-02 21:53
It might be a regression introduced by the refactor. Try to understand which version is caused by, verify/explain exact paths in question, etc.
