### ISSUE TITLE
Filenames are interpreted as glob patterns when they shouldn't be

### ISSUE THREAD

**Issue by grawity** [syncthing/syncthing#7485] opened 2021-03-16 14:03 UTC
I created a few files containing a literal `[-l]` in their name, and surprisingly, they cause warnings in other hosts which have received those files:

> 2021-03-15 14:13:00: globbing: syntax error in pattern for Notes/Networks/Finger/ITS/@up.update.uu.se [-l] (20201004)~[0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9]-[0-9][0-9][0-9][0-9][0-9][0-9].txt
>
> 2021-03-15 14:13:29: globbing: syntax error in pattern for Notes/Networks/Finger/nullroute.eu.org/@nullroute.eu.org [-l] (20180523)~[0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9]-[0-9][0-9][0-9][0-9][0-9][0-9].txt
>
> 2021-03-15 14:14:54: globbing: syntax error in pattern for Notes/Networks/Finger/ITS/@up.update.uu.se [-l] (20201004)~[0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9]-[0-9][0-9][0-9][0-9][0-9][0-9].txt
>
> 2021-03-15 14:14:55: globbing: syntax error in pattern for Notes/Networks/Finger/nullroute.eu.org/@nullroute.eu.org [-l] (20180523)~[0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9]-[0-9][0-9][0-9][0-9][0-9][0-9].txt

I suspect these patterns are used in file versioning -- indeed the receiving folders have "File Versioning: Staggered File Versioning" enabled.

 - Syncthing v1.14.0, Linux (64-bit Intel/AMD)

**Comment by imsodin** [comment] 2021-03-16 14:06
Duplicate of https://github.com/syncthing/syncthing/issues/2606

**Closed by imsodin** 2021-03-16 14:06 UTC
Labels: bug, needs-triage
