### ISSUE TITLE
GUI: Folder Sorting/Categorizing/Tagging

### ISSUE THREAD

**Issue by Crozh** [syncthing/syncthing#8931] opened 2023-06-07 21:48 UTC
- What problem your new feature would solve? 
 - How or why you think it is generally useful (i.e., not just for you)
Some people may save multiple folders from the same subject and they will, of course, be scattered all around the folders section. 
This can be a good thing for people who like or need to be really tidy and organized with their shared files. Maybe even "upgrading" their workflow a little bit? Of course this is a stretch, but I wouldn't consider it a bad thing.  
 
 - What alternatives or workarounds you considered
 Only thing I considered a workaround but is a big hassle is deleting the shared folder under syncthing and realocating it.
You could even make the GUI folders draggable so I can categorize them myself? I don't like this approach but it is one for sure. 

I wouldn't call this a must, but it is an improvement and a QOL feature, in my opinion. I'm unaware if this is a feature I missed, but I searched time and time again and haven't seen it anywhere.

**Comment by imsodin** [comment] 2023-06-08 09:59
Duplicate of https://github.com/syncthing/syncthing/issues/2070

**Closed by imsodin** 2023-06-08 09:59 UTC
Labels: enhancement, needs-triage
