### ISSUE TITLE
some nodes can see each other on local network

### ISSUE THREAD

**Issue by rezad1393** [syncthing/syncthing#2535] opened 2015-11-30 07:43 UTC
hi
I have synthing installed on these devices:
1 laptop connected via wifi
2 android tablet connected via wifi
3 desktop pc connected via lan
they all can ping each other.
they are on the same router (openwrt installed on that)
the laptop and the tablet can sync with each other without problems

but the laptop and desktop see each other as disconnected.
I have enabled local discovery on them and added them to each other by adding their device id to each other but they still don't see the other one.

could this be openwrt related?
maybe between wifi and lan there is a issue?
though they can ping each other and ssh works too.

**Comment by wweich** [comment] 2015-11-30 08:04
Is your LAN and Wifi the same network? (all devices have the same IP range)
If yes, check if the router blocks broadcast or multicast between LAN and Wifi. This is needed for local discovery.

As a workaround you can set the IP of you desktop in the devices settings on the other two nodes. Instead of `dynamic` set it to `IP:Port, dynamic`.

**Comment by rezad1393** [comment] 2015-11-30 08:13
the lan and wifi are on the same router. which has openwrt installed.
the ip are in the same range (192.168.1.0/24) and in openwrt lan and wireless access point are in the same zone.
as I said I can ping and ssh between two devices.
and I have tried the ip:port method with no success.

**Comment by AudriusButkevicius** [comment] 2015-11-30 08:38
You need to be in thr same subnet for local discovery to work. If you are running linux, multicasts are blocked by the firewall by most distros. For windows you need to make sure that he network type is Home. Also, your router might be preventing multicasts. 

I am closing this as its clearly a fiewall.issue given direct connection doesn't work. I suggest you follow the docs on how to setup the firewall.

**Closed by AudriusButkevicius** 2015-11-30 08:38 UTC

**Comment by rezad1393** [comment] 2015-11-30 09:05
??
As I said in the issue description I CAN use syncthing between tablet and laptop /(with linbux on it)
the issue is that I cant connect between pc( with linux on it ) and laptop

**Comment by AudriusButkevicius** [comment] 2015-11-30 09:18
I closed this, as this is a support request, and not a bug report.

I've named the most common reasons why this could happen, and the fact that ot works between A and B but not B and C implies configuration issues. I suggest you triple check firewall settings on both sides.

If you want further support, please use the forums.
