### ISSUE TITLE
Race condition in restarting folder

### ISSUE THREAD

**Issue by calmh** [syncthing/syncthing#6133] opened 2019-11-07 10:34 UTC
`TestIntroducer` triggers this:

```
10:29:43 INFO: Connection to AIR6LPZ-7K4PTTV-UXQSMUU-CPQ5YWH-OEDFIIQ-JUG777G-2YQXXR5-YD6AWQR at  closed: restarting folder folder1
10:29:43 INFO: Connection to GYRZZQB-IRNPV4Z-T7TC52W-EQYJ3TT-FDQW6MW-DFLMU42-SSSU6EM-FBK2VAY at  closed: restarting folder folder1
10:29:43 INFO: Restarted folder folder1 (sendreceive)
10:29:43 INFO: No stored folder metadata for "folder2": recalculating
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xb60084]

goroutine 1150 [running]:
github.com/syncthing/syncthing/lib/db.(*FileSet).ListDevices(0x0, 0x1, 0x1, 0xc0005e63c0)
	/opt/tcagent/syncthing-4-work/src/github.com/syncthing/syncthing/lib/db/set.go:367 +0x34
github.com/syncthing/syncthing/lib/model.(*model).startFolderLocked(0xc005466b00, 0xe4c442, 0x7, 0x0, 0x0, 0x0, 0xe4cd3b, 0x8, 0x0, 0xc00557b3c0, ...)
	/opt/tcagent/syncthing-4-work/src/github.com/syncthing/syncthing/lib/model/model.go:271 +0x226
github.com/syncthing/syncthing/lib/model.(*model).RestartFolder(0xc005466b00, 0xe4c442, 0x7, 0x0, 0x0, 0x0, 0xe4cd3b, 0x8, 0x0, 0xc0003f4a80, ...)
	/opt/tcagent/syncthing-4-work/src/github.com/syncthing/syncthing/lib/model/model.go:484 +0x930
github.com/syncthing/syncthing/lib/model.(*model).CommitConfiguration(0xc005466b00, 0x0, 0xc005b39b80, 0x2, 0x2, 0xc005b3af00, 0x2, 0x2, 0x0, 0x0, ...)
	/opt/tcagent/syncthing-4-work/src/github.com/syncthing/syncthing/lib/model/model.go:2534 +0xd26
github.com/syncthing/syncthing/lib/config.(*wrapper).notifyListener(0xc004f60800, 0xf92aa0, 0xc005466b00, 0x0, 0xc005b39b80, 0x2, 0x2, 0xc005b3af00, 0x2, 0x2, ...)
	/opt/tcagent/syncthing-4-work/src/github.com/syncthing/syncthing/lib/config/wrapper.go:241 +0x1d0
github.com/syncthing/syncthing/lib/config.(*wrapper).notifyListeners.func1(0xc004f60800, 0xc000345180, 0xc000345500, 0xf93fa0, 0xc000226ec0, 0xf92aa0, 0xc005466b00)
	/opt/tcagent/syncthing-4-work/src/github.com/syncthing/syncthing/lib/config/wrapper.go:232 +0x12b
created by github.com/syncthing/syncthing/lib/config.(*wrapper).notifyListeners
	/opt/tcagent/syncthing-4-work/src/github.com/syncthing/syncthing/lib/config/wrapper.go:231 +0x28e
FAIL	github.com/syncthing/syncthing/lib/model	3.693s
```

Theoretically there should be a file set but apparently it's nil (deleted). There's no locking to prevent this as we release the lock in RestartFolder between creating the set and calling startFolderLocked.

**Comment by imsodin** [comment] 2019-11-07 11:37
Weird. The set is added to the model in `addFolderLocked` and `fmut` is held while calling that and `startFolderLocked` and neither of those drops the lock until that panic. The set created in `RestartFolder` outside of the lock is local, so I don't see how anybody can mess with that until it "enters the lock".  

I have only seen failures from builds of #6107. I assume the problem is that the db has been closed while `RestartFolder` was in progress, thus `NewFileSet` now returns nil without an error. A solution would be to ensure in `model.Stop` that no more `CommitConfiguration` etc is going on.

**Comment by calmh** [comment] 2019-11-07 11:58
Ah, that's probably it!

**Comment by imsodin** [comment] 2019-11-30 14:59
I completely forgot about this. Now that https://github.com/syncthing/syncthing/pull/6107 is merged I get the following panics when running tests on master, which can be explained by the same thing:

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xe6581a]

goroutine 821 [running]:
github.com/syncthing/syncthing/lib/db.(*FileSet).ListDevices(...)
	/media/ext4_data/Coding/go/src/github.com/syncthing/syncthing/lib/db/set.go:367
github.com/syncthing/syncthing/lib/model.(*model).startFolderLocked(0xc0002fde40, 0x10e74aa, 0x7, 0x0, 0x0, 0x0, 0x10e7e60, 0x8, 0x0, 0xc0004ff500, ...)
	/media/ext4_data/Coding/go/src/github.com/syncthing/syncthing/lib/model/model.go:301 +0x20a
github.com/syncthing/syncthing/lib/model.(*model).restartFolder(0xc0002fde40, 0x10e74aa, 0x7, 0x0, 0x0, 0x0, 0x10e7e60, 0x8, 0x0, 0xc0004ff480, ...)
	/media/ext4_data/Coding/go/src/github.com/syncthing/syncthing/lib/model/model.go:524 +0xa25
github.com/syncthing/syncthing/lib/model.(*model).CommitConfiguration(0xc0002fde40, 0x0, 0xc00068a840, 0x2, 0x2, 0xc00000de00, 0x2, 0x2, 0x0, 0x0, ...)
	/media/ext4_data/Coding/go/src/github.com/syncthing/syncthing/lib/model/model.go:2610 +0xdb5
github.com/syncthing/syncthing/lib/config.(*wrapper).notifyListener(0xc00017ac00, 0x127d080, 0xc0002fde40, 0x0, 0xc00068a840, 0x2, 0x2, 0xc00000de00, 0x2, 0x2, ...)
	/media/ext4_data/Coding/go/src/github.com/syncthing/syncthing/lib/config/wrapper.go:211 +0x1d0
github.com/syncthing/syncthing/lib/config.(*wrapper).notifyListeners.func1(0xc00017ac00, 0xc000035500, 0xc000035880, 0x127db80, 0xc00003a9d0, 0x127d080, 0xc0002fde40)
	/media/ext4_data/Coding/go/src/github.com/syncthing/syncthing/lib/config/wrapper.go:202 +0x12b
created by github.com/syncthing/syncthing/lib/config.(*wrapper).notifyListeners
	/media/ext4_data/Coding/go/src/github.com/syncthing/syncthing/lib/config/wrapper.go:201 +0x286
FAIL	github.com/syncthing/syncthing/lib/model	6.996s
```

Do you already have another error-bubble-up-PR incoming soon that can address this? Otherwise we need to put some kind of band-aid on this for the next release.

**Comment by calmh** [comment] 2019-12-01 08:22
No, nothing brewing yet. There is the other issue on connect-before-folder-start which also needs resolving before the next RC, not sure if that's related or if you have a plan? I can do something somewhere but I wasn't sure where your toes are, in order to not step on them :)

**Comment by imsodin** [comment] 2019-12-01 13:43
The specific issue/regression that was in the RC is already fixed by https://github.com/syncthing/syncthing/pull/6173. For the general problem of "config vs folder-service vs connection racyness" I do have a large PR upcoming. I just wanted to file that and write is has nothing to do with this problem between closing services and closing db, but it partly does. I'll see whether I can extract those parts that will fix this issue (as I expect the full PR to be contentious).

**Closed** 2019-12-04 06:15 UTC
Labels: bug
