### ISSUE TITLE
Reduce database size by FileInfo indirection

### ISSUE THREAD

**Issue by calmh** [syncthing/syncthing#5047] opened 2018-07-04 07:37 UTC
Currently we store each FileInfo per the device that announces it - one for ourselves and once for each peer device. When the devices in a cluster are in sync the FileInfo will be identical for all of them. If there are many devices (think hundreds or thousands) this can become a large multiplier on the database size.

We could instead use an intermediary index and a reference counter. That is, instead of todays

```
(KeyTypeDevice, device, folder, filename) -> marshalled FileInfo
```

we could do

```
(KeyTypeDevice, device, folder, filename) -> hash of marshalled FileInfo
(KeyTypeHashedFileInfo, hash of marshalled FileInfo) -> (refcounter, marshalled FileInfo)
```

When doing inserts we hash the marshalled FileInfo and store that in place of the marshalled FileInfo. We then look up the item corresponding to that hash and either write `(1, marshalled FileInfo)` or bump the counter if it already exists.

When overwriting a FileInfo we need to do the lookup and decrease the counter for the old value, potentially deleting the actual FileInfo when the counter reaches zero.

(We only *delete* FileInfos when dropping a folder, which can be special cased.)

**Comment by canton7** [comment] 2018-07-04 10:04
Another option, of course, is to avoid reference counting and instead do periodic garbage collection? That avoids the case where the reference counting gets messed up by something, and we end up with FileInfos which are never removed.

**Comment by calmh** [comment] 2018-07-04 11:20
Yep.

**Comment by imsodin** [comment] 2018-07-04 12:56
Instead of file  info hash, one could also separate device specific fields (e.g. invalid, I don't think there is more?) out and use something like
```
(KeyTypeDevice, device, folder, filename) -> (version, invalid)
(KeyTypeVersion, folder, filename, version) -> (refcounter, marshalled FileInfo)
```
to keep even less full file info copies.

**Comment by calmh** [comment] 2018-07-05 06:39
Sure, I don't think K-V was every really the insect's appendages it's just what was available and worked. SQLite was problematic both performance and concurrency wise when I tried it but I may well have fucked up. Trading some performance for ease of use and being able to index on random things is probably worth it.

**Comment by imsodin** [comment] 2020-02-13 09:07
Fixed by https://github.com/syncthing/syncthing/pull/6283 (and duplicate of https://github.com/syncthing/syncthing/issues/5898, respectively the other way around chronologically).

**Closed by imsodin** 2020-02-13 09:07 UTC
Labels: enhancement
