### ISSUE TITLE
Files are not synched until "/rest/system/reset" is called

### ISSUE THREAD

**Issue by pchico83** [syncthing/syncthing#6316] opened 2020-02-10 21:35 UTC
I am one of the github.com/okteto/okteto maintainers. Okteto uses syncthing to synchronize code changes between the local filesystem and a pod running in Kubernetes.

We are experiencing an issue where local and remote files are not insync (for example after a git checkout) until you manually modify the file locally.

Forcing scans does not help. The only thing that works is to call "/rest/system/reset" on the remote syncthing.

For a particular file not insync, this is the result of calling "/rest/db/file" locally:

```
bash-3.2$ curl http://localhost:57336/rest/db/file?folder=okteto-api&file=pkg/model/space.go
{
  "availability": [
    {
      "id": "ATOPHFJ-VPVLDFY-QVZDCF2-OQQ7IOW-OG4DIXF-OA7RWU3-ZYA4S22-SI4XVAU",
      "fromTemporary": false
    }
  ],
  "global": {
    "deleted": false,
    "ignored": false,
    "invalid": false,
    "localFlags": 0,
    "modified": "2020-02-10T11:55:30.204129596+01:00",
    "modifiedBy": "ABKAVQF",
    "mustRescan": false,
    "name": "pkg/model/space.go",
    "noPermissions": false,
    "numBlocks": 1,
    "permissions": "0644",
    "sequence": 146,
    "size": 2081,
    "type": "FILE",
    "version": [
      "ABKAVQF:1"
    ]
  },
  "local": {
    "deleted": false,
    "ignored": false,
    "invalid": false,
    "localFlags": 0,
    "modified": "2020-02-10T15:26:01.437380687+01:00",
    "modifiedBy": "ABKAVQF",
    "mustRescan": false,
    "name": "pkg/model/space.go",
    "noPermissions": false,
    "numBlocks": 1,
    "permissions": "0644",
    "sequence": 150,
    "size": 2129,
    "type": "FILE",
    "version": [
      "ABKAVQF:1"
    ]
  }
}
```

and on remote:

```
pablo@Pablos-MacBook-Pro ~ % curl http://localhost:57335/rest/db/file?folder=okteto-api&file=pkg/model/space.go
{
  "availability": [
    {
      "id": "ABKAVQF-RUO4CYO-FSC2VIP-VRX4QDA-TQQRN2J-MRDXJUC-FXNWP6N-S6ZSAAR",
      "fromTemporary": false
    }
  ],
  "global": {
    "deleted": false,
    "ignored": false,
    "invalid": false,
    "localFlags": 0,
    "modified": "2020-02-10T14:26:01.437380687Z",
    "modifiedBy": "ABKAVQF",
    "mustRescan": false,
    "name": "pkg/model/space.go",
    "noPermissions": false,
    "numBlocks": 1,
    "permissions": "0644",
    "sequence": 150,
    "size": 2129,
    "type": "FILE",
    "version": [
      "ABKAVQF:1"
    ]
  },
  "local": {
    "deleted": false,
    "ignored": false,
    "invalid": false,
    "localFlags": 0,
    "modified": "2020-02-10T10:55:30.204129596Z",
    "modifiedBy": "ABKAVQF",
    "mustRescan": false,
    "name": "pkg/model/space.go",
    "noPermissions": false,
    "numBlocks": 1,
    "permissions": "0644",
    "sequence": 146,
    "size": 2081,
    "type": "FILE",
    "version": [
      "ABKAVQF:1"
    ]
  }
}
```

Logs don't show any error.

Any idea what might be the issue? Or anything I can do for troubleshooting the issue?
Any API call I can use to detect this situation?

### Version Information

Syncthing Version: v1.3.3
OS Version: MacOS Catalina

**Comment by calmh** [comment] 2020-02-11 06:27
It looks like your database (on ABKAVQF) has at some point moved back in time, such as having been restored from backup. That doesn't work. If that is not the case, do you have a reproducer for this?

**Comment by pchico83** [comment] 2020-02-11 07:16
@calmh we don't restore backups, but our users could go back to a previous commit and the filesystem might look like a previous time in history.
How does it work though? Why calling the scan api (locally and on remote) does not help?
I am working on reproducible steps today, but it rarely happens. I am also running syncthing with audit logs now in case it helps.

**Comment by calmh** [comment] 2020-02-11 07:36
Devices don't always send the full index database to each other, because that's very inconvenient. Instead, changes that happen get monotonically increasing sequence numbers and each side remembers the highest sequence number they've got from the other side. If you "rewind" one side they will reuse sequence numbers that the other side already has, and thinks will be weird. The reset you do forces the other side to forget everything which works around it.

You should probably not have the index database on some filesystem that can get rewound like this.

Closing as this seems like not a bug, feel free to yell if it does reproduce without rewinding the database or discuss freely on the forum :)

**Closed by calmh** 2020-02-11 07:36 UTC
