### ISSUE TITLE
panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by tomasz1986** [syncthing/syncthing#7561] opened 2021-04-10 08:18 UTC
If I remember correctly, this happened a few days ago when trying to start Syncthing on a new device (with an existing `config.xml` file, but with no database). The program panicked almost immediately (see the first log), and then failed to start any more due to a corrupted database (see the three other logs).

I actually suspect an incompatible SATA driver (i.e. a very old driver used in a newer version of Windows), because I was also experiencing other problems with the device, but I'm reporting this anyway, just in case something else is the culprit.

```
Panic at 2021-04-07T19:29:47+09:00
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x8 pc=0x4755bc]

goroutine 389 [running]:
github.com/minio/sha256-simd.(*digest).Write(0xc003d70f50, 0x0, 0xc0c0c000c0c0c0, 0x0, 0xeb10e0, 0x1886400, 0x0)
	github.com/minio/sha256-simd@v0.1.1/sha256.go:133 +0x205
github.com/syncthing/syncthing/lib/protocol.BlocksHash(0xc000ce6000, 0x129, 0x200, 0x40e749, 0xc003d7a9a0, 0xe0)
	github.com/syncthing/syncthing/lib/protocol/bep_extensions.go:379 +0xe6
github.com/syncthing/syncthing/lib/db.readWriteTransaction.putFile(0x1334518, 0xc002a1e4b0, 0x28d0f7d8, 0xc002a1e4b0, 0x133ac38, 0xc0001e8620, 0x0, 0x0, 0xc001120a10, 0x61, ...)
	github.com/syncthing/syncthing/lib/db/transactions.go:559 +0x667
github.com/syncthing/syncthing/lib/db.(*Lowlevel).updateRemoteFiles(0xc0000da580, 0xc000c7d480, 0xb, 0x10, 0xc000c81a40, 0x20, 0x20, 0xc001afa000, 0x329, 0x349, ...)
	github.com/syncthing/syncthing/lib/db/lowlevel.go:172 +0xab8
github.com/syncthing/syncthing/lib/db.(*FileSet).Update(0xc0028e4940, 0xffde0e91e780c6fa, 0xdcb35c46bdb54c10, 0xbab7b8799dec5e36, 0xeae0afae8fac4517, 0xc001afa000, 0x329, 0x349)
	github.com/syncthing/syncthing/lib/db/set.go:142 +0x527
github.com/syncthing/syncthing/lib/model.(*model).handleIndex(0xc0004781a0, 0xffde0e91e780c6fa, 0xdcb35c46bdb54c10, 0xbab7b8799dec5e36, 0xeae0afae8fac4517, 0xc001b38060, 0xb, 0xc001a9e000, 0x329, 0x492, ...)
	github.com/syncthing/syncthing/lib/model/model.go:1142 +0x625
github.com/syncthing/syncthing/lib/model.(*model).IndexUpdate(0xc0004781a0, 0xffde0e91e780c6fa, 0xdcb35c46bdb54c10, 0xbab7b8799dec5e36, 0xeae0afae8fac4517, 0xc001b38060, 0xb, 0xc001a9e000, 0x329, 0x492, ...)
	github.com/syncthing/syncthing/lib/model/model.go:1095 +0x96
github.com/syncthing/syncthing/lib/protocol.nativeModel.IndexUpdate(0x2a6650f8, 0xc0004781a0, 0xffde0e91e780c6fa, 0xdcb35c46bdb54c10, 0xbab7b8799dec5e36, 0xeae0afae8fac4517, 0xc001b38060, 0xb, 0xc001a9e000, 0x329, ...)
	github.com/syncthing/syncthing/lib/protocol/nativemodel_windows.go:26 +0xb9
github.com/syncthing/syncthing/lib/protocol.encryptedModel.IndexUpdate(0x1331768, 0xc003701560, 0xc003c73300, 0xffde0e91e780c6fa, 0xdcb35c46bdb54c10, 0xbab7b8799dec5e36, 0xeae0afae8fac4517, 0xc001b38060, 0xb, 0xc001a9e000, ...)
	github.com/syncthing/syncthing/lib/protocol/encryption.go:65 +0xcd
github.com/syncthing/syncthing/lib/protocol.(*rawConnection).handleIndexUpdate(0xc003772100, 0xc001b38060, 0xb, 0xc001a9e000, 0x329, 0x492, 0x1, 0x1)
	github.com/syncthing/syncthing/lib/protocol/protocol.go:592 +0x1f3
github.com/syncthing/syncthing/lib/protocol.(*rawConnection).dispatcherLoop(0xc003772100, 0x0, 0x0)
	github.com/syncthing/syncthing/lib/protocol/protocol.go:475 +0x8c5
github.com/syncthing/syncthing/lib/protocol.(*rawConnection).Start.func2(0xc003772100)
	github.com/syncthing/syncthing/lib/protocol/protocol.go:276 +0x32
created by github.com/syncthing/syncthing/lib/protocol.(*rawConnection).Start
	github.com/syncthing/syncthing/lib/protocol/protocol.go:275 +0x8c
```

[panic-20210407-192947.log](https://github.com/syncthing/syncthing/files/6289484/panic-20210407-192947.log)
[panic-20210407-192952.log](https://github.com/syncthing/syncthing/files/6289485/panic-20210407-192952.log)
[panic-20210407-193010.log](https://github.com/syncthing/syncthing/files/6289487/panic-20210407-193010.log)
[panic-20210407-193026.log](https://github.com/syncthing/syncthing/files/6289488/panic-20210407-193026.log)

Syncthing was v1.15.0 (custom compiled build).

**Comment by tomasz1986** [comment] 2021-04-10 08:20
By the way, I think that I have just created an issue with no labels, right?

This has come up before, and the reason seems to be that if you click on the "new issue" button before logging in, and only log in later when asked to, then GitHub doesn't ask about anything else and just proceeds to create the issue.

**Comment by AudriusButkevicius** [comment] 2021-04-10 10:13
Not sure what's happening here. If the panic doesn't lie, then it happened on this line in the minio package:
```
		n := copy(d.x[d.nx:], p)
```

But the only way this would panic with a nil deref would be if d.x is nil, but it can't be as it's a fixed size array oppose to a slice.

The digest object itself has an address in the stack trace, so it's not that either, as there is also previous access of `d` in that function.

To be honest, cosmic rays/bad hardware is the only way I can explain this.

**Comment by calmh** [comment] 2021-04-10 10:21
I'm also leaning towards bad hardware, or at least memory corruption for some reason (possibly race condition).

```
goroutine 389 [running]:
github.com/minio/sha256-simd.(*digest).Write(0xc003d70f50, 0x0, 0xc0c0c000c0c0c0, 0x0, 0xeb10e0, 0x1886400, 0x0)
	github.com/minio/sha256-simd@v0.1.1/sha256.go:133 +0x205
```

Parameters to `Write` here are `0xc003d70f50` (the `*digest`, all good), `0x0, 0xc0c0c000c0c0c0, 0x0` which is the pointer/len/cap of the slice header, which makes absolutely no sense, and space for return values which we can ignore. A byte slice with nil pointer and absurd length (and zero cap) isn't something we can create intentionally in Go...

**Comment by AudriusButkevicius** [comment] 2021-04-10 10:37
Right, given two opinions agree that this is not a bug we can fix, but more likely bad hardware, closing.

**Closed by AudriusButkevicius** 2021-04-10 10:37 UTC
Labels: bug

**Comment by tomasz1986** [comment] 2021-04-10 10:54
Yeah, although the hardware itself is fine - I have checked it. It was likely the SATA driver, as since the panic Syncthing has been running fine on the default Windows drivers so far.

**Comment by AudriusButkevicius** [comment] 2021-04-10 11:02
The only way that would happen is if the binary was corrupted/read corrupted from disk into memory.

Otherwise, what this code is doing is completely unrelated to storage per-se. as it's data that arrived over the network gets corrupted while it's in memory, so it's either the binary is dodgy and corrupted it, or it got corrupted in ram or the network card.

**Comment by tomasz1986** [comment] 2021-04-10 11:16
Hmm, interesting. The compiled binary itself is fine, but it was copied onto the machine from a different one also on the same day, so there is a possibility that it could have got corrupted in the process.
