### ISSUE TITLE
Unable to logout and excessive events after upgrading to 1.26.0

### ISSUE THREAD

**Issue by er-pa** [syncthing/syncthing#9209] opened 2023-11-09 08:23 UTC
### Does your log mention database corruption?

No.

### Include required information

System: MacOS 14.0
Browser (tested at least): Firefox 119.0.1

When upgrading from either 1.23.7 or 1.25.0 to 1.26.0, I am not able to logout using the logout button and the API-calls tend to go haywire.

Steps to reproduce the issue (at least it seems to work here):
1.) Use an older version, go to firefox and log in.
2.) Upgrade Syncthing (in my case I restarted the binary, but now without the `--no-upgrade` call, and/or pressing the upgrade button in the GUI
3.) ...problems.
(I managed to get to this point now four times following the above steps)

What I expected: Properly logout and go to the (new) login page.
What happens: Nothing really, just a refresh of the page.

But more interestingly, when this happens, the API-calls become the following (I took one second out of it, but it just keeps going as this):
```
[ICLAR] 2023/11/09 09:13:43.023445 api.go:534: DEBUG: http: GET "/rest/events?since=756": status 200, 234 bytes in 64.75 ms
[ICLAR] 2023/11/09 09:13:43.023464 events.go:335: DEBUG: log 758 LoginAttempt map[remoteAddress:127.0.0.1:52226 success:true username:eric]
[ICLAR] 2023/11/09 09:13:43.025943 api_auth.go:153: DEBUG: Sessionless HTTP request with authentication; this is expensive.
[ICLAR] 2023/11/09 09:13:43.069215 api_auth.go:153: DEBUG: Sessionless HTTP request with authentication; this is expensive.
[ICLAR] 2023/11/09 09:13:43.069841 api_auth.go:153: DEBUG: Sessionless HTTP request with authentication; this is expensive.
[ICLAR] 2023/11/09 09:13:43.070226 api_auth.go:153: DEBUG: Sessionless HTTP request with authentication; this is expensive.
[ICLAR] 2023/11/09 09:13:43.070927 api_auth.go:153: DEBUG: Sessionless HTTP request with authentication; this is expensive.
[ICLAR] 2023/11/09 09:13:43.092638 events.go:335: DEBUG: log 759 LoginAttempt map[remoteAddress:127.0.0.1:52231 success:true username:eric]
[ICLAR] 2023/11/09 09:13:43.092731 api.go:534: DEBUG: http: GET "/rest/events?since=757": status 200, 234 bytes in 66.78 ms
[ICLAR] 2023/11/09 09:13:43.095479 api_auth.go:153: DEBUG: Sessionless HTTP request with authentication; this is expensive.
[ICLAR] 2023/11/09 09:13:43.139419 events.go:335: DEBUG: log 760 LoginAttempt map[remoteAddress:127.0.0.1:52226 success:true username:eric]
[ICLAR] 2023/11/09 09:13:43.139801 api.go:534: DEBUG: http: GET "/rest/system/status": status 200, 1734 bytes in 70.59 ms
[ICLAR] 2023/11/09 09:13:43.142368 api.go:534: DEBUG: http: GET "/rest/system/discovery": status 200, 3 bytes in 72.53 ms
[ICLAR] 2023/11/09 09:13:43.142401 events.go:335: DEBUG: log 761 LoginAttempt map[remoteAddress:127.0.0.1:52229 success:true username:eric]
[ICLAR] 2023/11/09 09:13:43.142673 events.go:335: DEBUG: log 762 LoginAttempt map[remoteAddress:127.0.0.1:52230 success:true username:eric]
[ICLAR] 2023/11/09 09:13:43.142702 api.go:534: DEBUG: http: GET "/rest/system/connections": status 200, 3249 bytes in 72.48 ms
[ICLAR] 2023/11/09 09:13:43.146976 api.go:534: DEBUG: http: GET "/rest/system/error": status 200, 21 bytes in 76.06 ms
[ICLAR] 2023/11/09 09:13:43.146997 events.go:335: DEBUG: log 763 LoginAttempt map[remoteAddress:127.0.0.1:52221 success:true username:eric]
[ICLAR] 2023/11/09 09:13:43.170161 events.go:335: DEBUG: log 764 LoginAttempt map[remoteAddress:127.0.0.1:52231 success:true username:eric]
[ICLAR] 2023/11/09 09:13:43.170172 api.go:534: DEBUG: http: GET "/rest/events?since=758": status 200, 1158 bytes in 74.71 ms
[ICLAR] 2023/11/09 09:13:43.174089 api_auth.go:153: DEBUG: Sessionless HTTP request with authentication; this is expensive.
[ICLAR] 2023/11/09 09:13:43.239169 events.go:335: DEBUG: log 765 LoginAttempt map[remoteAddress:127.0.0.1:52226 success:true username:eric]
[ICLAR] 2023/11/09 09:13:43.239185 api.go:534: DEBUG: http: GET "/rest/events?since=763": status 200, 234 bytes in 65.08 ms
[ICLAR] 2023/11/09 09:13:43.242124 api_auth.go:153: DEBUG: Sessionless HTTP request with authentication; this is expensive.
[ICLAR] 2023/11/09 09:13:43.306970 events.go:335: DEBUG: log 766 LoginAttempt map[remoteAddress:127.0.0.1:52231 success:true username:eric]
[ICLAR] 2023/11/09 09:13:43.306983 api.go:534: DEBUG: http: GET "/rest/events?since=764": status 200, 233 bytes in 64.85 ms
[ICLAR] 2023/11/09 09:13:43.309735 api_auth.go:153: DEBUG: Sessionless HTTP request with authentication; this is expensive.
[ICLAR] 2023/11/09 09:13:43.374618 api.go:534: DEBUG: http: GET "/rest/events?since=765": status 200, 234 bytes in 64.89 ms
[ICLAR] 2023/11/09 09:13:43.374627 events.go:335: DEBUG: log 767 LoginAttempt map[remoteAddress:127.0.0.1:52226 success:true username:eric]
[ICLAR] 2023/11/09 09:13:43.378931 api_auth.go:153: DEBUG: Sessionless HTTP request with authentication; this is expensive.
[ICLAR] 2023/11/09 09:13:43.444048 api.go:534: DEBUG: http: GET "/rest/events?since=766": status 200, 234 bytes in 65.12 ms
[ICLAR] 2023/11/09 09:13:43.444056 events.go:335: DEBUG: log 768 LoginAttempt map[remoteAddress:127.0.0.1:52231 success:true username:eric]
[ICLAR] 2023/11/09 09:13:43.448017 api_auth.go:153: DEBUG: Sessionless HTTP request with authentication; this is expensive.
[ICLAR] 2023/11/09 09:13:43.513037 events.go:335: DEBUG: log 769 LoginAttempt map[remoteAddress:127.0.0.1:52226 success:true username:eric]
[ICLAR] 2023/11/09 09:13:43.513065 api.go:534: DEBUG: http: GET "/rest/events?since=767": status 200, 233 bytes in 65.05 ms
[ICLAR] 2023/11/09 09:13:43.516088 api_auth.go:153: DEBUG: Sessionless HTTP request with authentication; this is expensive.
[ICLAR] 2023/11/09 09:13:43.580859 api.go:534: DEBUG: http: GET "/rest/events?since=768": status 200, 234 bytes in 64.78 ms
[ICLAR] 2023/11/09 09:13:43.580881 events.go:335: DEBUG: log 770 LoginAttempt map[remoteAddress:127.0.0.1:52231 success:true username:eric]
[ICLAR] 2023/11/09 09:13:43.584044 api_auth.go:153: DEBUG: Sessionless HTTP request with authentication; this is expensive.
[ICLAR] 2023/11/09 09:13:43.646095 api_auth.go:153: DEBUG: Sessionless HTTP request with authentication; this is expensive.
[ICLAR] 2023/11/09 09:13:43.649088 api.go:534: DEBUG: http: GET "/rest/events?since=769": status 200, 234 bytes in 65.05 ms
[ICLAR] 2023/11/09 09:13:43.649097 events.go:335: DEBUG: log 771 LoginAttempt map[remoteAddress:127.0.0.1:52226 success:true username:eric]
[ICLAR] 2023/11/09 09:13:43.653972 api_auth.go:153: DEBUG: Sessionless HTTP request with authentication; this is expensive.
[ICLAR] 2023/11/09 09:13:43.712674 events.go:335: DEBUG: log 772 LoginAttempt map[remoteAddress:127.0.0.1:52231 success:true username:eric]
[ICLAR] 2023/11/09 09:13:43.712788 api.go:534: DEBUG: http: GET "/rest/system/log?since=2023-11-09T09%3A13%3A41.573146%2B01%3A00": status 200, 18252 bytes in 66.69 ms
[ICLAR] 2023/11/09 09:13:43.720538 api.go:534: DEBUG: http: GET "/rest/events?since=770": status 200, 465 bytes in 66.57 ms
[ICLAR] 2023/11/09 09:13:43.720554 events.go:335: DEBUG: log 773 LoginAttempt map[remoteAddress:127.0.0.1:52226 success:true username:eric]
[ICLAR] 2023/11/09 09:13:43.738952 api_auth.go:153: DEBUG: Sessionless HTTP request with authentication; this is expensive.
[ICLAR] 2023/11/09 09:13:43.807517 events.go:335: DEBUG: log 774 LoginAttempt map[remoteAddress:127.0.0.1:52231 success:true username:eric]
[ICLAR] 2023/11/09 09:13:43.807556 api.go:534: DEBUG: http: GET "/rest/events?since=772": status 200, 234 bytes in 68.61 ms
[ICLAR] 2023/11/09 09:13:43.811814 api_auth.go:153: DEBUG: Sessionless HTTP request with authentication; this is expensive.
[ICLAR] 2023/11/09 09:13:43.877726 events.go:335: DEBUG: log 775 LoginAttempt map[remoteAddress:127.0.0.1:52226 success:true username:eric]
[ICLAR] 2023/11/09 09:13:43.877736 api.go:534: DEBUG: http: GET "/rest/events?since=773": status 200, 234 bytes in 65.92 ms
[ICLAR] 2023/11/09 09:13:43.881131 api_auth.go:153: DEBUG: Sessionless HTTP request with authentication; this is expensive.
[ICLAR] 2023/11/09 09:13:43.945979 api.go:534: DEBUG: http: GET "/rest/events?since=774": status 200, 234 bytes in 64.85 ms
[ICLAR] 2023/11/09 09:13:43.945997 events.go:335: DEBUG: log 776 LoginAttempt map[remoteAddress:127.0.0.1:52231 success:true username:eric]
[ICLAR] 2023/11/09 09:13:43.950385 api_auth.go:153: DEBUG: Sessionless HTTP request with authentication; this is expensive.
```
For the record, when this happens, the environment is quiet. No syncthing, other remote devices are offline and I don't do anything. So I don't expect much more events than a handful once every +- 10 seconds.

To get out of this loop, clearing the cookies followed by restarting the browser tends to work.

As a side-note, this came forward (in a spamming fashion) in the console:
```
Some cookies are misusing the recommended “SameSite“ attribute (1643)
```

```
Cookie “sessionid-ICLAR” does not have a proper “SameSite” attribute value. Soon, cookies without the “SameSite” attribute or with an invalid value will be treated as “Lax”. This means that the cookie will no longer be sent in third-party contexts. If your application depends on this cookie being available in such contexts, please add the “SameSite=None“ attribute to it. To know more about the “SameSite“ attribute, read https://developer.mozilla.org/docs/Web/HTTP/Headers/Set-Cookie/SameSite
```

**Comment by calmh** [comment] 2023-11-09 10:35
Yeah, apparently old cookies cause an issue in the new code. Possibly we should simply use a new cookie name now and push a patch release.

**Comment by calmh** [comment] 2023-11-09 10:43
```diff
diff --git a/lib/api/api.go b/lib/api/api.go
index 1f2fd3a55..ddf4734e0 100644
--- a/lib/api/api.go
+++ b/lib/api/api.go
@@ -372,7 +372,7 @@ func (s *service) Serve(ctx context.Context) error {

        // Wrap everything in basic auth, if user/password is set.
        if guiCfg.IsAuthEnabled() {
-               sessionCookieName := "sessionid-" + s.id.String()[:5]
+               sessionCookieName := "sessionid-v2-" + s.id.String()[:5]
                handler = basicAuthAndSessionMiddleware(sessionCookieName, guiCfg, s.cfg.LDAP(), handler, s.evLogger)
                handlePasswordAuth := passwordAuthHandler(sessionCookieName, guiCfg, s.cfg.LDAP(), s.evLogger)
                restMux.Handler(http.MethodPost, "/rest/noauth/auth/password", handlePasswordAuth)
```

**Comment by er-pa** [comment] 2023-11-09 10:55
I'm not sure if that's the complete solution either. The haywire api calls diminish, but the logging out part still doesn't work as expected as it seems to immediately try to authenticate, I think.

```
[ICLAR] 2023/11/09 11:53:06.244502 api.go:534: DEBUG: http: POST "/rest/noauth/auth/logout": status 204, 0 bytes in 0.08 ms
[ICLAR] 2023/11/09 11:53:06.275341 api_auth.go:153: DEBUG: Sessionless HTTP request with authentication; this is expensive.
[ICLAR] 2023/11/09 11:53:06.378883 events.go:335: DEBUG: log 33 LoginAttempt map[remoteAddress:127.0.0.1:57901 success:true username:eric]
```

**Comment by bt90** [comment] 2023-11-09 10:58
The browser is free to cache basic auth credentials, and there is no clean way to delete them programmatically.

**Comment by bt90** [comment] 2023-11-09 11:12
Duplicate of #9208

**Closed** 2023-11-09 11:12 UTC
Labels: bug, needs-triage
