### ISSUE TITLE
panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by tomasz1986** [syncthing/syncthing#7230] opened 2020-12-24 10:39 UTC
What happened?

1. Started Syncthing with `STRECHECKDBEVERY=1s`.
2. The GUI became completely unresponsive.
3. Tried to shut down using the GUI.
4. Clicking the shutdown button caused Syncthing to panic and restart.
5. Had to kill the process to stop the panics.

```
[D4DZU] 19:23:01 INFO: TCP listener ([::]:22000) shutting down
Panic at 2020-12-24T19:23:11+09:00
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x20 pc=0x9c68ff]

goroutine 28 [running]:
github.com/syncthing/syncthing/lib/db.(*metadataTracker).Sequence(0x0, 0xffffffff, 0xffffffff, 0xffffffff, 0xffffffff, 0xffffffff, 0xffffffff, 0xffffffff, 0xffffffff, 0x0, ...)
	github.com/syncthing/syncthing/lib/db/meta.go:232 +0x3f
github.com/syncthing/syncthing/lib/db.(*FileSet).Sequence(...)
	github.com/syncthing/syncthing/lib/db/set.go:383
github.com/syncthing/syncthing/lib/model.(*model).newFolder(0x139057a0, 0x127eccc0, 0xb, 0x127eccd8, 0x6, 0x0, 0x127ecce8, 0x6, 0x0, 0x125c0620, ...)
	github.com/syncthing/syncthing/lib/model/model.go:526 +0x112
github.com/syncthing/syncthing/lib/model.(*model).onServe(0x139057a0)
	github.com/syncthing/syncthing/lib/model/model.go:267 +0x151
github.com/syncthing/syncthing/lib/model.(*model).Serve(0x139057a0)
	github.com/syncthing/syncthing/lib/model/model.go:250 +0x21
github.com/thejerf/suture.(*Supervisor).runService.func1(0x1250e1e0, 0x2, 0x32795080, 0x139057a0)
	github.com/thejerf/suture@v4.0.0+incompatible/supervisor.go:643 +0x69
created by github.com/thejerf/suture.(*Supervisor).runService
	github.com/thejerf/suture@v4.0.0+incompatible/supervisor.go:631 +0x4b

goroutine 1 [chan receive]:
github.com/syncthing/syncthing/lib/syncthing.(*App).Wait(...)
	github.com/syncthing/syncthing/lib/syncthing/syncthing.go:370
main.syncthingMain(0x1256f780, 0x1f, 0x0, 0x0, 0x0, 0x1, 0x0, 0x0, 0x0, 0x0, ...)
	github.com/syncthing/syncthing/cmd/syncthing/main.go:719 +0x59f
main.main()
	github.com/syncthing/syncthing/cmd/syncthing/main.go:438 +0x33b
```

[panic-20201224-192311.log](https://github.com/syncthing/syncthing/files/5739292/panic-20201224-192311.log)
[panic-20201224-192730.log](https://github.com/syncthing/syncthing/files/5739294/panic-20201224-192730.log)
[panic-20201224-192751.log](https://github.com/syncthing/syncthing/files/5739295/panic-20201224-192751.log)
[panic-20201224-192804.log](https://github.com/syncthing/syncthing/files/5739296/panic-20201224-192804.log)

Syncthing v1.12.0.

**Comment by imsodin** [comment] 2020-12-24 11:31
That's the same root cause as https://github.com/syncthing/syncthing/issues/7005 (returning nil filesets on shutdown), and that was fixed by https://github.com/syncthing/syncthing/pull/7150.

**Closed by imsodin** 2020-12-24 11:31 UTC
Labels: bug, needs-triage
