### ISSUE TITLE
Re-use as many existing file pieces as possible

### ISSUE THREAD

**Issue by uok** [syncthing/syncthing#1909] opened 2015-06-03 16:14 UTC
**Scenario 1** - conflict

1) device A (folder master): *bigfile.txt* is transferred to device B
2) device B: conflict happens and file is renamed to *conflict.txt*
3) device A: *bigfile.txt* is changed (1 byte different)

*Result*: *bigfile.txt* needs to be completely transferred again to device B
*Improved*: use pieces from *conflict.txt* to speed up transfer/creation of *bigfile.txt*

**Scenario 2** - deletion

1) device B: *bigfile.txt* is deleted
2) device A (with file versioning): *bigfile.txt* is moved to `.stversions`
3) device B: *bigfile.txt* is restored from OS recycle bin

*Result*: *bigfile.txt* needs to be completely transferred again to device A
*Improved*: use pieces from files in `.stversions` to speed up transfer/creation of *bigfile.txt*

**Scenario 3** - same file in different folders

1) device C: shares folder *company_archive* (containing *bigcompanyvideo.avi*) with device D
2) device C: shares folder *business_year_2015* with device D
 (this folder also contains identical *bigcompanyvideo.avi* because user copied it there for a presentation) 

*Result*: *bigcompanyvideo.avi* needs to be completely transferred twice
*Improved*: use pieces from files accross folders to speed up transfer/creation of *bigcompanyvideo.avi*

-
all things would help save a lot of bandwidth and time, especially in Europe where internet connections are asynchronous most of the time (= slow upload, fast download)

**Comment by AudriusButkevicius** [comment] 2015-06-03 16:32
Scenario 1 is potentially (not convinced) just a race condition between us moving the file for conflict, and indexing it.

Scenario 2, I don't think we should index .stversions, as the user can himself delete files there to free up space, making management of the index unbearable.

**Comment by uok** [comment] 2015-06-03 16:38
Edit: added scenario 3

@AudriusButkevicius 
I understand, but how is this different from normal file deletion (outside .stversions)?

**Comment by AudriusButkevicius** [comment] 2015-06-03 22:39
Scenario 3 is already covered, and 2 is different because we don't scan it or index it, hence nothing to maintain.

**Comment by calmh** [comment] 2015-06-04 17:32
We *could* index it, but for some reason my gut feeling says I don't want to. Need to think on it.

**Comment by AudriusButkevicius** [comment] 2015-06-04 18:25
Though @calmh, is scenario 1 plausible, given that we move something for conflict, and not reuse the blocks in the conflicting file? Because the file will only get picked up after the next rescan, correct?

**Comment by bigbear2nd** [comment] 2015-06-04 19:07
If we would index it, we could have an per folder option on the remote devices to download the files from .stversions (something that i would appreciate)

**Comment by calmh** [comment] 2015-06-04 20:23
How would that work? I make a change to a file, that change get synced to another device, they archive their old version, I download their old version (the one I had before I changed it) into *my* .stversions...? That sounds a bit convoluted and I'm not sure what it achieves?

**Comment by calmh** [comment] 2015-06-04 20:28
BTW scenario 1 above doesn't happen, as I understand it.

> 1) device A (folder master): bigfile.txt is transferred to device B
> 2) device B: conflict happens and file is renamed to conflict.txt

The *old* bigfile.txt is renamed due to the conflict. We also have the new bigfile.txt that we just synced (or there would be no conflict).

> 3) device A: bigfile.txt is changed (1 byte different)

Synced as usual.

**Comment by dcarosone** [comment] 2015-06-04 21:12
The scenario that I tripped over was rearranging directories. Roughly:

Some/place/big.file renamed to other/place/big.file

I think the removal of the original location was noticed and processed
before the discovery of the new. The contents were clearly transferred
again.

Using inotify and having both systems online at the time might have
contributed. Perhaps a single scan or a reconnect would have sent things in
the right order; it seems to me that deletes are generally sent last?

Either way, and to cover other races where we are faster than the humans
changing and moving files, being able to draw on the blocks of previous
versions for reconstruction is a hugely useful thing. I had naively
expected it would be done, until I learned the hard way above.

I'll go so far as to say that it was probably the primary reason for me to
use the .stversions cache. I use zfs with snapshots, and generally would go
there for recovery.

Also, when we rename something into .stversions, can't we (effectively)
rename the index entries as well? No need to (re)scan ?

**Comment by AudriusButkevicius** [comment] 2015-06-04 21:20
@calmh I think #1 does potentially happen, because we move old bigfile.txt out for conflict, and cannot reuse blocks anymore.

**Comment by calmh** [comment] 2015-06-09 13:04
But we have the *new* bigfile.txt we can reuse stuff from. And it's newer, so must be better. :)

Possibly, possibly, we could scan .stversions and keep that data around as something not sent to others, used as a last resort source of block reuse before asking for them from the network...

**Comment by bigbear2nd** [comment] 2015-06-10 06:00
I would like to sync the .stversions for various reasons:
 - I like to have the same data in a folder which i sync
 - I can clean out the .stversions without access to the remote pc (e.g. a Friends pc.)
 - I have easy access to old files (Working on something, syncthing detects the change, sends it to the remote host and i get back the old version into the .stversions folder. > very eays to revert changes)

**Comment by calmh** [comment] 2015-06-10 08:02
What if you share a folder with two other devices, both of which have .stversions enabled? They might even have different versioning schemes set? The cluster synchronized .stversions dir would become a mess...

Note that can already today fake this by adding an extra folder; i.e. a folder `default-versions` with path `~/Sync/.stversions` and similar that you can share with hosts that need it. Don't enable versioning on the versioning though. :)

**Comment by kisolre** [comment] 2015-11-25 14:33
Scenario 4 - files moved between shared folders

1) Device A shares folders F1 and F2 with device B.
2) On device A bigfile.ext is moved from folder F1 to folder F2 (simple rename).
3) Device B removes file bigfile.ext from folder F1 and then pulls file bigfile.ext from device A to folder F2 

So bigfile.ext is transferred over the network without actual need to do so.

**Comment by wweich** [comment] 2015-11-25 14:46
In this scenario you would need to make sure, that device A does a rescan of F2 and probably stop scanning F1 until the file is synced.

**Comment by AudriusButkevicius** [comment] 2015-11-25 17:09
Yeach scenario 4 is impossible without causing unexpected behaviour and unnecessery delays.

**Comment by AudriusButkevicius** [comment] 2016-04-27 20:30
So I think we can close this.

Most of the cases are covered, and the case of reusing stuff from .stversions just gives me shivers.

**Closed** 2016-04-28 06:14 UTC
Labels: enhancement

**Comment by uok** [comment] 2016-04-28 07:56
workaround
add root folder including .stversions as a new Syncthing folder and do not share it with a device
works great!
