### ISSUE TITLE
Syncthing deletes directory leading to data loss.

### ISSUE THREAD

**Issue by ajvogel** [syncthing/syncthing#2907] opened 2016-03-28 15:48 UTC
At some point Syncthing duplicated directories with different capatalisations. In other words I had a directory called "Application" and at some point I had both "application" and "Application" as directories. When I deleted one of the directories syncthing deleted the other as well. This lead to some dataloss!

I can't reproduce the duplicate directories part but I can reproduce the deleting part by creating directories "Test" and "test" and then deleting one. Syncthing deletes the other as well. 

One of my remote devices is a windows machine. So I expect it has something to do with that. Maybe "Application" gets mapped to "application" on the windows machine and then back to "application" on the linux machine.

**Comment by AudriusButkevicius** [comment] 2016-03-28 15:56
In Windows the filesystem is not case sensitive, hence there is only one "application" directory regardless of the case, and when you delete one of them on a case sensitive backend it deletes the sole instance on Windows.

This is essentially a duplicate of #1787

**Closed by AudriusButkevicius** 2016-03-28 15:56 UTC

**Comment by canton7** [comment] 2016-03-28 16:03
I think he's saying that he created "Applications" on Linux, and Syncthing created "applications" on both Windows and Linux?

It's not clear what exactly happened, but that's my interpretation....

Even if he created both "Applications" and "applications" on Linux, it would make sense if there was a way that he could delete one of them without syncthing deleting the other...

**Comment by AudriusButkevicius** [comment] 2016-03-28 16:06
We don't mess around with the case when creating directories so I don't think we could have created it with the wrong case.

The fact that it got deleted still ties down to the ticket I linked above, which is essentially us not dealing with case insensitive filesystems in general, potentially leading to data loss.
