### ISSUE TITLE
Out of sync: failed to remove dirs, files on winxp (busy error)

### ISSUE THREAD

**Issue by t-o-l-i-x** [syncthing/syncthing#2522] opened 2015-11-27 07:41 UTC
Hi All! Thanks for the great Sync thing!

But I am experiencing an "Out of sync" problem on my Win XP box after upgrade from 0.11.25 to 0.12.4 (please see the log below). Other boxes (Linux, Win7, Win7, Android) in the domain has upgraded fine. What can cause this "Busy" error? There is no any other activity with these files.

[3JIVD] 2015/11/26 15:55:34.515625 events.go:206: DEBUG: poll 1m0s
[3JIVD] 2015/11/26 15:55:34.515625 events.go:206: DEBUG: poll 1m0s
[3JIVD] 2015/11/26 15:55:34.515625 events.go:206: DEBUG: poll 1m0s
[3JIVD] 2015/11/26 15:55:34.515625 events.go:206: DEBUG: poll 1m0s
[3JIVD] 2015/11/26 15:55:34.515625 events.go:206: DEBUG: poll 1m0s
[3JIVD] 2015/11/26 15:55:34.515625 events.go:206: DEBUG: poll 1m0s
[3JIVD] 2015/11/26 15:55:34.515625 rwfolder.go:257: DEBUG: rwFolder/default@0x1f446f00 changed 3
[3JIVD] 2015/11/26 15:55:34.515625 rwfolder.go:287: INFO: Folder "default" isn't making progress. Pausing puller for 1m0s.
[3JIVD] 2015/11/26 15:55:34.515625 rwfolder.go:288: DEBUG: rwFolder/default@0x1f446f00 next pull in 1m0s
[3JIVD] 2015/11/26 15:55:34.515625 events.go:144: DEBUG: log 1517 FolderErrors map[folder:default errors:[{test remove \\?\H:\Sync\test: Процесс не может получить доступ к файлу, так как этот файл занят другим процессом.} {test-vdvp remove \\?\H:\Sync\test-vdvp: Процесс не может получить доступ к файлу, так как этот файл занят другим процессом.} {test2 remove \\?\H:\Sync\test2: Процесс не может получить доступ к файлу, так как этот файл занят другим процессом.}]]
[3JIVD] 2015/11/26 15:55:34.515625 events.go:144: DEBUG: log 1518 StateChanged map[duration:0.125 folder:default to:idle from:syncing]
[3JIVD] 2015/11/26 15:55:34.515625 events.go:206: DEBUG: poll 1m0s
[3JIVD] 2015/11/26 15:55:34.515625 events.go:206: DEBUG: poll 1m0s

The localized error message above says "the file is busy".

**Comment by wweich** [comment] 2015-11-27 08:10
This error normally means, that the file is in use by another program and locked, so Syncthing cannot read it.

**Comment by calmh** [comment] 2015-11-27 11:43
Specifically for a directory it could mean some program has it as it's current working directory, or an explorer window is open on it, or something.

**Comment by AudriusButkevicius** [comment] 2015-11-27 11:48
I'd close this.

**Comment by buinsky** [comment] 2015-11-28 23:33
I have the same issue after upgrade to 0.12.4. Nothing blocks the folder (I checked it).

**Comment by AudriusButkevicius** [comment] 2015-11-28 23:48
Are you sure you are not having the same issue with 0.12.3? 

How do you know if nothing is keeping the folders locked?

**Comment by AudriusButkevicius** [comment] 2015-11-28 23:50
Also, what OS?

**Comment by buinsky** [comment] 2015-11-28 23:57
> Are you sure you are not having the same issue with 0.12.3?

I'm sure.

> How do you know if nothing is keeping the folders locked?

I cheked it.

> Also, what OS?

XP x32

**Comment by AudriusButkevicius** [comment] 2015-11-29 00:05
Can you post the errors as well, just to make sure it's the same issue.

**Comment by buinsky** [comment] 2015-11-29 00:06
> Can you post the errors as well, just to make sure it's the same issue.

[SCMY2] 03:04:50 INFO: Puller (folder "NewFilms", dir "3"): delete: remove \\?\d
:\qBittorrent\Tantal\NewFilms\3: Процесс не может получить доступ к файлу, так к
ак этот файл занят другим процессом.
[SCMY2] 03:04:51 INFO: Puller (folder "NewFilms", dir "3"): delete: remove \\?\d
:\qBittorrent\Tantal\NewFilms\3: Процесс не может получить доступ к файлу, так к
ак этот файл занят другим процессом.
[SCMY2] 03:04:51 INFO: Folder "NewFilms" isn't making progress. Pausing puller f
or 1m0s.
[SCMY2] 03:05:53 INFO: Puller (folder "NewFilms", dir "3"): delete: remove \\?\d
:\qBittorrent\Tantal\NewFilms\3: Процесс не может получить доступ к файлу, так к
ак этот файл занят другим процессом.

**Comment by buinsky** [comment] 2015-11-29 00:10
I can delete folder in explorer. Also qBittorrent is closed.

**Comment by AudriusButkevicius** [comment] 2015-11-29 00:24
Is it 100% reproducible?
What's the scenario to reproduce it?

**Comment by buinsky** [comment] 2015-11-29 00:30
> Is it 100% reproducible?

Yes. 
1) Create folder on Windows 7 machine.
2) After syncing I delete folder on Windows 7 machine.
3) On WinXP machine the folder stay not deleted.

**Comment by AudriusButkevicius** [comment] 2015-11-29 00:51
@calmh I'd say we drop support for Windows XP, as there is just trouble there, and I am not prepared to install a VM with a 15 year old OS just to debug it.

**Comment by buinsky** [comment] 2015-11-29 01:04
@AudriusButkevicius

According to this: https://en.wikipedia.org/wiki/Usage_share_of_operating_systems Windows XP market share is 9.03%. 

I can share VMWare VM with Windows XP if you want to.

**Comment by AudriusButkevicius** [comment] 2015-11-29 01:28
I don't think I want.

I guess we'll leave it for someone who runs WinXP and cares enough about it to debug it and fix it.
You can also see changes that went into v12 vs v11 and see if you can spot anything.

**Comment by calmh** [comment] 2015-11-29 07:46
If this is XP specific it's probably not going to get fixed, but I'm fairly sure removing directories has worked fine on XP and probably still does. I'm inclined to suspect antivirus or similar, as that's often the cause for mysteriously locked files and directories. If removing directories on XP were broken in general I think we'd have more complaints...

**Comment by AudriusButkevicius** [comment] 2015-11-29 12:05
Well there was some refactoring between v0.11 and v0.12 and I am just thinking that we might end up being in the same dir we are deleting for example.

**Comment by buinsky** [comment] 2015-11-29 12:44
> Well there was some refactoring between v0.11 and v0.12 and I am just thinking that we might end up being in the same dir we are deleting for example.

This is most likely.

**Comment by calmh** [comment] 2015-11-29 21:21
We don't chdir anywhere. We stat files before deleting them, but that's basically the difference?

**Comment by buinsky** [comment] 2015-11-30 01:04
I just checked the issue on another WinXP machine. The result is the same.

**Comment by AudriusButkevicius** [comment] 2015-11-30 01:24
So I guess we are not arguing that it does not happens.
The important bit is finding whats causing it. See if every version of v0.12 causes it to narrow it down. If it happens with v0.12.0, then someone who is interested in fixing this needs to do some git bisecting and seeing which commit breaks it, and fix it.

**Comment by t-o-l-i-x** [comment] 2015-11-30 11:44
Thanks for advices, going to research it. The same issue: https://github.com/syncthing/syncthing/issues/1308

**Closed** 2015-11-30 16:21 UTC
