### ISSUE TITLE
File system watcher does nothing on sync folders that are at the drive root

### ISSUE THREAD

**Issue by sagamusix** [syncthing/syncthing#8344] opened 2022-05-15 21:07 UTC
Using Syncthing v1.20.1 through SyncTrayzor 1.1.29 on Windows 10 (64-bit), it seems that file system watching does not work for sync folders that are at the drive root. Supposedly this was already a problem in the past (#5578) and was fixed, but in comparison to that old bug report, Syncthing just fails silentely for me: There is no hint in the GUI that there was an error setting up the file system watcher, yet no changes are picked up unless I do a full scan. If I create a trivial sync folder in some other place than a drive root, the watcher seems to do its job again. However, I cannot be 100% confident that this is the distinguishing factor because there's of course also other differences (like my trivial sync folder being almost empty while those sync folders that span entire drives contain tens of thousands of files).

All sync folders that I tried are local NTFS-formatted partitions, and none of them are the system drive. I just started using Syncthing (which I really like so far apart from this small issue!), so I cannot tell if this is a recent regression.

**Comment by tomasz1986** [comment] 2022-05-15 21:10
This is a duplicate of https://github.com/syncthing/syncthing/issues/7944.

**Closed** 2022-05-15 21:22 UTC
Labels: bug, needs-triage
