### ISSUE TITLE
Copy Device Identification Fails

### ISSUE THREAD

**Issue by pauldurham** [syncthing/syncthing#8915] opened 2023-05-27 20:27 UTC
In SyncTrayzor, one can select:  Actions, Show ID, Copy.
This "copy" action does not actually copy the identification string for pasting in another application.  Even selecting the string first & then clicking on "copy" does nothing. The only way to copy the string is to select it with the mouse & then press Ctrl-C.

Using Windows 11 Enterprise.
SyncTrayzor 1.1.29
Syncthing 1.23.4

**Comment by tomasz1986** [comment] 2023-05-28 04:51
This is a duplicate of https://github.com/canton7/SyncTrayzor/issues/749.

**Closed** 2023-05-28 05:05 UTC
