### ISSUE TITLE
Can't add device.

### ISSUE THREAD

**Issue by JoaoAparicio** [syncthing/syncthing#9014] opened 2023-08-02 11:20 UTC
- Syncthing version: v1.23.6
- OS version: Android 12. Kernel 4.19.188

- I was trying to add a device to the Syncthing android app. I click "Add a device", then either copy paste the device ID or take a photo of the ID, fill in the device name, and then there's no button to actually add. The only option I have is to "go back", at which point I'm asked if I want to discard the changes.

- I expected to have the device added to the list of devices.

- Additional comment: I have the same problem if the remote device tries to connect: I get a notification on my phone from the Syncthing app. I'm asked if I want to accept the request from the remote device, or ignore. I press accept. This takes me to the "add device menu", and I'm stuck again as the only thing I can do from there is back and discard.

I'm attaching a screenshot of the menu in question
![WhatsApp Image 2023-08-02 at 6 13 49 AM](https://github.com/syncthing/syncthing/assets/5380486/9747b3d8-163e-416d-ae50-dab93caae471)

**Comment by tomasz1986** [comment] 2023-08-02 11:27
Duplicate of https://github.com/syncthing/syncthing-android/issues/1947. For now, if you don't want to upgrade to a release candidate, you should still be able to click the button if you press around the location where it should normally be.

**Closed** 2023-08-02 11:31 UTC
Labels: bug, needs-triage
