### ISSUE TITLE
syncthing-inotify + syncthing leading to dropped updates with common prefixes

### ISSUE THREAD

**Issue by DarkHelmet433** [syncthing/syncthing#2851] opened 2016-03-18 01:11 UTC
Running syncthing-inotify and syncthing 0.12.19 on FreeBSD-11.

Until recently we were happily using rsync to update a syncthing distribution pool in the freebsd.org cluster.  We rsync from the source-of-truth into the pool, syncthing-inotify notices the changes and informs syncthing.  Syncthing then fans out the data nicely.  All the syncthing nodes are a mesh of peers, the rsync forces them to converge if there's a problem.

After our change from 0.12.13 to 0.12.19 we are now seeing dropped updates.   I provoked an update by deleting several directory trees and updating the indexes and signatures.  When the rsync happened, the inotify logs look correct and it appears that syncthing was correctly informed.

```
# touch index.txt ; touch *.sig
.... 
[OK] 00:55:00 Syncthing is indexing change in admin-built: [amd64_10.txt.sig amd64_11.txt.sig amd64_9.txt.sig i386_10.txt.sig i386_11.txt.sig ia64_10.txt.sig index.txt index.txt.sig sparc64_10.txt.sig]
```
The line in syncthing-inotify's log appears to correctly show that syncthing has received the correct notifications and has acknowledge them all correctly.

However, the result is this on the master (the mesh peer receiving the updates):
```
-rw-r--r--  1 syncthing  syncthing  3421 Mar 17 23:53 index.txt
-rw-r--r--  1 syncthing  syncthing   512 Mar 17 23:53 index.txt.sig
-rw-r--r--  1 syncthing  syncthing   512 Mar 17 23:53 amd64_9.txt.sig
-rw-r--r--  1 syncthing  syncthing   512 Mar 17 23:53 amd64_10.txt.sig
```
But the rest of the mesh has:
```
-rw-r--r--  1 syncthing  syncthing  3421 Mar 17 23:53 index.txt
-rw-r--r--  1 syncthing  syncthing   512 Mar 17 23:48 index.txt.sig
-rw-r--r--  1 syncthing  syncthing   512 Mar 17 23:53 amd64_9.txt.sig
-rw-r--r--  1 syncthing  syncthing   512 Mar 17 23:53 amd64_10.txt.sig
```
The problematic file is "index.txt.sig". 

The gui reports everything is in sync.  If I hit a 'rescan all' on the master, then the missing changes are discovered and the mesh resyncs. 

.stignore on the "master" mesh peer looks like this:
```
// rsync in-flight transfers
// eg: foo.txz is transferred as .foo.txz.23yXh3
.*
```

Another example, this time not using rsync at all.  This is directly in the monitored file system area.
```
syncthing@syncthing.nyi:/home/syncthing/built % touch foo.txt foo.txt.sig
syncthing@syncthing.nyi:/home/syncthing/built % ls -lrtT foo*
-rw-r--r--  1 syncthing  syncthing  0 Mar 18 01:02:34 2016 foo.txt
-rw-r--r--  1 syncthing  syncthing  0 Mar 18 01:02:34 2016 foo.txt.sig
...
[OK] 01:02:34 Syncthing is indexing change in admin-built: [foo.txt foo.txt.sig]
```
and on the peers:
```
root@syncthing.ysv:~syncthing/built # ls -lrtT foo*
-rw-r--r--  1 syncthing  syncthing  0 Mar 18 01:02:34 2016 foo.txt
```
foo.txt.sig didn't even arrive. GUI reports all peers 100% in sync.

Then I hit the 'rescan' button for the admin-built collection, and re-checked the peers:
```
root@syncthing.ysv:~syncthing/built # ls -lrtT foo*
-rw-r--r--  1 syncthing  syncthing  0 Mar 18 01:05:18 2016 foo.txt.sig
-rw-r--r--  1 syncthing  syncthing  0 Mar 18 01:05:18 2016 foo.txt
```
Is there some magic involving suffixes that I'm not aware of?  Perhaps there's a prefix/suffix bug in notification handlers inside syncthing?

What should I do next to track this down?

PS: If I don't use a common prefix, eg: "foo.txt and foo.sig" instead of "foo.txt and foo.txt.sig" then it works.

**Comment by DarkHelmet433** [comment] 2016-03-18 01:57
I did a rollback test.  The last working version is 0.12.15.  0.12.16 through 0.12.20 are broken with "touch foo.txt foo.txt.sig" in the root of a synced folder and syncthing-inotify.

**Comment by plouj** [comment] 2016-03-18 02:06
Thanks for doing the rollback investigation. It's very likely that my fix for #2151 uncovered a deeper issue with syncthing-inotify that causes it to drop some events without passing them on to syncthing.

**Comment by DarkHelmet433** [comment] 2016-03-18 02:08
I ran syncthing-inofity with -verbose=4. It is passing all the events to syncthing, and syncthing is acking them them all.

**Comment by DarkHelmet433** [comment] 2016-03-18 02:24
I've discovered the behavior is different for previously known files.

The response to 'touch bar.txt bar.txt.sig' on official 1.12.20 binaries, for the first time those files ever existed:

```
peter@overcee[ 7:14PM]~/Sync-1041> touch bar.txt bar.txt.sig
...
[DEBUG] 19:14:24 Change detected in: /home/peter/Sync/bar.txt.sig (could still be ignored)
[TRACE] 19:14:24 Change detected in: /home/peter/Sync/bar.txt.sig
[DEBUG] 19:14:24 Change detected in: /home/peter/Sync/bar.txt (could still be ignored)
[TRACE] 19:14:24 Change detected in: /home/peter/Sync/bar.txt
[DEBUG] 19:14:24 [FS] Tracking: bar.txt.sig
[DEBUG] 19:14:24 [FS] Tracking: bar.txt
[DEBUG] 19:14:24 Timeout AccumulateChanges
[DEBUG] 19:14:24 Informing about bar.txt.sig
[DEBUG] 19:14:24 Informing about bar.txt
[TRACE] 19:14:24 Informing ST: default: [bar.txt bar.txt.sig]
[TRACE] 19:14:24 Requesting STEvents: 363928
[TRACE] 19:14:24 Requesting STEvents: 363929
[OK] 19:14:25 Syncthing is indexing change in default: [bar.txt bar.txt.sig]
[DEBUG] 19:14:25 [INFORMED] Removed tracking for bar.txt
[DEBUG] 19:14:25 [INFORMED] Removed tracking for bar.txt.sig
```

On a remote machine, I ended up with:
```
-rw-r--r--   1 peter  peter         0 Mar 17 19:14 bar.txt.sig
-rw-r--r--   1 peter  peter         0 Mar 17 19:14 bar.txt
```

Then deleting them:
```
peter@overcee[ 7:16PM]~/Sync-1042> rm bar.txt bar.txt.sig
...
[DEBUG] 19:16:37 Change detected in: /home/peter/Sync/bar.txt (could still be ignored)
[TRACE] 19:16:37 Change detected in: /home/peter/Sync/bar.txt
[DEBUG] 19:16:37 Change detected in: /home/peter/Sync/bar.txt.sig (could still be ignored)
[TRACE] 19:16:37 Change detected in: /home/peter/Sync/bar.txt.sig
[DEBUG] 19:16:37 [FS] Tracking: bar.txt
[DEBUG] 19:16:37 [FS] Tracking: bar.txt.sig
[DEBUG] 19:16:37 Timeout AccumulateChanges
[DEBUG] 19:16:37 Informing about bar.txt
[DEBUG] 19:16:37 Informing about bar.txt.sig
[TRACE] 19:16:37 Informing ST: default: [bar.txt bar.txt.sig]
[TRACE] 19:16:37 Requesting STEvents: 363956
[OK] 19:16:37 Syncthing is indexing change in default: [bar.txt bar.txt.sig]
[DEBUG] 19:16:37 [INFORMED] Removed tracking for bar.txt
[DEBUG] 19:16:37 [INFORMED] Removed tracking for bar.txt.sig
```
The files were deleted from the peer, as expected.

Now, creating them again:
```
peter@overcee[ 7:18PM]~/Sync-1043> touch bar.txt bar.txt.sig
...
[DEBUG] 19:18:17 Change detected in: /home/peter/Sync/bar.txt.sig (could still be ignored)
[TRACE] 19:18:17 Change detected in: /home/peter/Sync/bar.txt.sig
[DEBUG] 19:18:17 Change detected in: /home/peter/Sync/bar.txt (could still be ignored)
[TRACE] 19:18:17 Change detected in: /home/peter/Sync/bar.txt
[DEBUG] 19:18:17 [FS] Tracking: bar.txt.sig
[DEBUG] 19:18:17 [FS] Tracking: bar.txt
[DEBUG] 19:18:17 Timeout AccumulateChanges
[DEBUG] 19:18:17 Informing about bar.txt.sig
[DEBUG] 19:18:17 Informing about bar.txt
[TRACE] 19:18:17 Informing ST: default: [bar.txt bar.txt.sig]
[TRACE] 19:18:17 Requesting STEvents: 363977
[TRACE] 19:18:17 Requesting STEvents: 363978
[OK] 19:18:17 Syncthing is indexing change in default: [bar.txt bar.txt.sig]
[DEBUG] 19:18:17 [INFORMED] Removed tracking for bar.txt
[DEBUG] 19:18:17 [INFORMED] Removed tracking for bar.txt.sig
```
And the remote didn't get "bar.txt.sig"
```
-rw-r--r--   1 peter  peter         0 Mar 17 19:18 bar.txt
```

**Comment by plouj** [comment] 2016-03-18 02:50
Well, I can reliably reproduce the situation where the ```.sig``` file doesn't appear in syncthing's index after
```rm -f foo.txt foo.txt.sig; touch foo.txt foo.txt.sig```
according to
```curl -s http://localhost:8384/rest/db/browse?folder=default | json_pp```
but the annoying difference is that I'm not seeing things like
```Syncthing is indexing change in default: [foo.txt foo.txt.sig]```
My log only shows
```Syncthing is indexing change in default: [foo.txt]```
ie: syncthing-inotify doesn't tell syncthing about the ```.sig``` file. Also syncthing with```STTRACE=walker``` only shows
```walk.go:100: DEBUG: Walk /home/plouj/Sync/ [foo.txt] 131072 &{[] true 0xc820117a40 d41d8cd98f00b204e9800998ecf8427e 0xc82045cb40 0xc820490a60}```
I can reliably reproduce this on syncthing master (bea272c).

**Comment by plouj** [comment] 2016-03-18 03:05
What version of syncthing-inotify do you use?

**Comment by plouj** [comment] 2016-03-18 03:12
Even with the latest version (master) of syncthing-inotify I see
```Syncthing is indexing change in default: [foo.txt foo.txt.sig]```
in the syncthing-inotify log, but only 
```Walk /home/plouj/Sync/ [foo.txt] 131072 &{[] true 0xc82019a6e0 d41d8cd98f00b204e9800998ecf8427e 0xc8200b3260 0xc82047e890}```
from syncthing.

**Comment by plouj** [comment] 2016-03-18 03:27
Seems like the ```.sig``` files get lost during the [unification](https://github.com/syncthing/syncthing/blob/master/lib/model/model.go#L1322). If only it was a function that we could unit test... :)

**Comment by DarkHelmet433** [comment] 2016-03-18 03:47
From a bystander's point of view, the code near [model.go](https://github.com/syncthing/syncthing/blob/master/lib/model/model.go#L1336) looks like it's intended to be used on exact matches of directories. string.HasPrefix() doesn't seem right - consider "usr/lib/..." vs "usr/libexec/...".

**Comment by DarkHelmet433** [comment] 2016-03-18 04:35
FWIW; the cluster that was having the initial problems ("admin-built" folder) was running syncthing-inotify-0.6.7 (vs current 0.6.8).  I used a different machine with the "default"folder was unpatched 0.6. (!). I'll go and update those now.

**Comment by calmh** [comment] 2016-03-18 07:32
It would be interesting to see this with STTRACE=scanner to see what we actually do scan when being notified like this. Obviously the difference between 0.12.15 and 0.12.16 does narrow this down a bit, and we should refactor and add some tests to the code that you point to.

**Comment by calmh** [comment] 2016-03-18 08:20
This build is a v0.12.20 + a fixed "unifySubs". See if that makes a difference? I suspect the problem here is that `index.txt` is a prefix of `index.txt.sig` which should be fixed here.

**Comment by calmh** [comment] 2016-03-18 08:32
The build failed due to a test in the v0.12 code not working on Go 1.6, but the artefacts should be good anyway.

http://build.syncthing.net/job/syncthing-branch/226/artifact/src/github.com/syncthing/syncthing/

**Comment by DarkHelmet433** [comment] 2016-03-18 09:53
Ok, I've fired up that build and am using the proper version of syncthing-inotify on the test machine.
```
peter@overcee[ 2:33AM]~/Sync-1174> touch foo.txt foo.txt.sig
...
[OK] 02:35:32 Syncthing is indexing change in default: [foo.txt foo.txt.sig]
...
[M2XGE] 2016/03/18 02:35:32.319990 walk.go:100: DEBUG: Walk /home/peter/Sync/ [foo.txt foo.txt.sig] 131072 &{[] true 0xc8222514e0 d41d8cd98f00b204e9800998ecf8427e 0xc82022c360 0xc8223a7f60}
[M2XGE] 2016/03/18 02:35:32.320120 walk.go:488: DEBUG: checkDir /home/peter/Sync/ &{Sync 195 2147484096 {63593890531 812944000 0x112e300} {712342500 2636426 16832 21 433 433 4294967295 {1412910059 929565437} {1458293731 812944000} {1458293731 812944000} 195 81 16384 2048 0 0 {1412910059 929565437}}}
[M2XGE] 2016/03/18 02:35:32.320359 walk.go:304: DEBUG: rescan: File{Name:"foo.txt", Flags:010644, Modified:1458293590, Version:[{M2XGECJ 6}], Size:128, Blocks:[]} 1458293731 -rw-r--r--
[M2XGE] 2016/03/18 02:35:32.320398 walk.go:319: DEBUG: to hash: foo.txt File{Name:"foo.txt", Flags:0644, Modified:1458293731, Version:[{M2XGECJ 7}], Size:0, Blocks:[]}
[M2XGE] 2016/03/18 02:35:32.320469 walk.go:304: DEBUG: rescan: File{Name:"foo.txt.sig", Flags:010644, Modified:1458293590, Version:[{M2XGECJ 4}], Size:128, Blocks:[]} 1458293731 -rw-r--r--
[M2XGE] 2016/03/18 02:35:32.320496 walk.go:319: DEBUG: to hash: foo.txt.sig File{Name:"foo.txt.sig", Flags:0644, Modified:1458293731, Version:[{M2XGECJ 5}], Size:0, Blocks:[]}
[M2XGE] 2016/03/18 02:35:32.320530 walk.go:189: DEBUG: real to hash: foo.txt
[M2XGE] 2016/03/18 02:35:32.320602 walk.go:189: DEBUG: real to hash: foo.txt.sig
[M2XGE] 2016/03/18 02:35:32.320704 walk.go:167: DEBUG: Walk progress done /home/peter/Sync/ [foo.txt foo.txt.sig] 131072 &{[] true 0xc8222514e0 d41d8cd98f00b204e9800998ecf8427e 0xc82022c360 0xc8223a7f60}

peter@overcee[ 2:35AM]~/Sync-1175> rm foo.txt foo.txt.sig
...
[OK] 02:36:41 Syncthing is indexing change in default: [foo.txt foo.txt.sig]
...
[M2XGE] 2016/03/18 02:36:41.087575 walk.go:100: DEBUG: Walk /home/peter/Sync/ [foo.txt foo.txt.sig] 131072 &{[] true 0xc8222514e0 d41d8cd98f00b204e9800998ecf8427e 0xc82022c360 0xc8223a7f60}
[M2XGE] 2016/03/18 02:36:41.087662 walk.go:488: DEBUG: checkDir /home/peter/Sync/ &{Sync 193 2147484096 {63593890600 580706000 0x112e300} {712342500 2636426 16832 21 433 433 4294967295 {1412910059 929565437} {1458293800 580706000} {1458293800 580706000} 193 81 16384 2048 0 0 {1412910059 929565437}}}
[M2XGE] 2016/03/18 02:36:41.087740 walk.go:214: DEBUG: error: /home/peter/Sync/foo.txt <nil> lstat /home/peter/Sync/foo.txt: no such file or directory
[M2XGE] 2016/03/18 02:36:41.087779 walk.go:214: DEBUG: error: /home/peter/Sync/foo.txt.sig <nil> lstat /home/peter/Sync/foo.txt.sig: no such file or directory
[M2XGE] 2016/03/18 02:36:41.087869 walk.go:167: DEBUG: Walk progress done /home/peter/Sync/ [foo.txt foo.txt.sig] 131072 &{[] true 0xc8222514e0 d41d8cd98f00b204e9800998ecf8427e 0xc82022c360 0xc8223a7f60}
```
Repeating this part works as expected now, so that's an improvement.

However..
```
peter@overcee[ 2:41AM]~/Sync-1184> touch foo.txt foo.txt.sig
peter@overcee[ 2:41AM]~/Sync-1185> touch bar.txt bar.txt.sig
...
[OK] 02:41:20 Syncthing is indexing change in default: [foo.txt foo.txt.sig]
[OK] 02:41:30 Syncthing is indexing change in default: [bar.txt bar.txt.sig]
...
[M2XGE] 2016/03/18 02:41:20.946625 walk.go:100: DEBUG: Walk /home/peter/Sync/ [foo.txt foo.txt.sig] 131072 &{[] true 0xc821df4ae0 d41d8cd98f00b204e9800998ecf8427e 0xc8217aa240 0xc8230a7450}
[M2XGE] 2016/03/18 02:41:20.946728 walk.go:488: DEBUG: checkDir /home/peter/Sync/ &{Sync 195 2147484096 {63593890880 443092000 0x112e300} {712342500 2636426 16832 21 433 433 4294967295 {1412910059 929565437} {1458294080 443092000} {1458294080 443092000} 195 81 16384 2048 0 0 {1412910059 929565437}}}
[M2XGE] 2016/03/18 02:41:20.946916 walk.go:304: DEBUG: rescan: File{Name:"foo.txt", Flags:010644, Modified:1458294050, Version:[{M2XGECJ 12}], Size:128, Blocks:[]} 1458294080 -rw-r--r--
[M2XGE] 2016/03/18 02:41:20.946961 walk.go:319: DEBUG: to hash: foo.txt File{Name:"foo.txt", Flags:0644, Modified:1458294080, Version:[{M2XGECJ 13}], Size:0, Blocks:[]}
[M2XGE] 2016/03/18 02:41:20.947038 walk.go:304: DEBUG: rescan: File{Name:"foo.txt.sig", Flags:010644, Modified:1458294050, Version:[{M2XGECJ 10}], Size:128, Blocks:[]} 1458294080 -rw-r--r--
[M2XGE] 2016/03/18 02:41:20.947085 walk.go:319: DEBUG: to hash: foo.txt.sig File{Name:"foo.txt.sig", Flags:0644, Modified:1458294080, Version:[{M2XGECJ 11}], Size:0, Blocks:[]}
[M2XGE] 2016/03/18 02:41:20.947124 walk.go:189: DEBUG: real to hash: foo.txt
[M2XGE] 2016/03/18 02:41:20.947192 walk.go:189: DEBUG: real to hash: foo.txt.sig
[M2XGE] 2016/03/18 02:41:20.947281 walk.go:167: DEBUG: Walk progress done /home/peter/Sync/ [foo.txt foo.txt.sig] 131072 &{[] true 0xc821df4ae0 d41d8cd98f00b204e9800998ecf8427e 0xc8217aa240 0xc8230a7450}
[M2XGE] 2016/03/18 02:41:30.896664 walk.go:100: DEBUG: Walk /home/peter/Sync/ [bar.txt bar.txt.sig] 131072 &{[] true 0xc821df4ae0 d41d8cd98f00b204e9800998ecf8427e 0xc8217aa240 0xc8230a7450}
[M2XGE] 2016/03/18 02:41:30.896765 walk.go:488: DEBUG: checkDir /home/peter/Sync/ &{Sync 197 2147484096 {63593890890 386911000 0x112e300} {712342500 2636426 16832 21 433 433 4294967295 {1412910059 929565437} {1458294090 386911000} {1458294090 386911000} 197 81 16384 2048 0 0 {1412910059 929565437}}}
[M2XGE] 2016/03/18 02:41:30.896967 walk.go:304: DEBUG: rescan: File{Name:"bar.txt", Flags:010644, Modified:1458292809, Version:[{M2XGECJ 6}], Size:128, Blocks:[]} 1458294090 -rw-r--r--
[M2XGE] 2016/03/18 02:41:30.897001 walk.go:319: DEBUG: to hash: bar.txt File{Name:"bar.txt", Flags:0644, Modified:1458294090, Version:[{M2XGECJ 7}], Size:0, Blocks:[]}
[M2XGE] 2016/03/18 02:41:30.897086 walk.go:304: DEBUG: rescan: File{Name:"bar.txt.sig", Flags:010644, Modified:1458292809, Version:[{M2XGECJ 6}], Size:128, Blocks:[]} 1458294090 -rw-r--r--
[M2XGE] 2016/03/18 02:41:30.897116 walk.go:319: DEBUG: to hash: bar.txt.sig File{Name:"bar.txt.sig", Flags:0644, Modified:1458294090, Version:[{M2XGECJ 7}], Size:0, Blocks:[]}
[M2XGE] 2016/03/18 02:41:30.897150 walk.go:189: DEBUG: real to hash: bar.txt
[M2XGE] 2016/03/18 02:41:30.897218 walk.go:189: DEBUG: real to hash: bar.txt.sig
[M2XGE] 2016/03/18 02:41:30.897307 walk.go:167: DEBUG: Walk progress done /home/peter/Sync/ [bar.txt bar.txt.sig] 131072 &{[] true 0xc821df4ae0 d41d8cd98f00b204e9800998ecf8427e 0xc8217aa240 0xc8230a7450}
....
remote machine:
-rw-r--r--   1 peter  peter         0 Mar 18 02:41 foo.txt.sig
-rw-r--r--   1 peter  peter         0 Mar 18 02:41 foo.txt
-rw-r--r--   1 peter  peter         0 Mar 18 02:41 bar.txt.sig
-rw-r--r--   1 peter  peter         0 Mar 18 02:41 bar.txt
local machine:
peter@overcee[ 2:41AM]~/Sync-1186> rm foo* bar*    
...      
[OK] 02:41:39 Syncthing is indexing change in default: [bar.txt bar.txt.sig foo.txt foo.txt.sig]
...
[M2XGE] 2016/03/18 02:41:39.764692 walk.go:100: DEBUG: Walk /home/peter/Sync/ [bar.txt bar.txt.sig foo.txt foo.txt.sig] 131072 &{[] true 0xc821df4ae0 d41d8cd98f00b204e9800998ecf8427e 0xc8217aa240 0xc8230a7450}
[M2XGE] 2016/03/18 02:41:39.764798 walk.go:488: DEBUG: checkDir /home/peter/Sync/ &{Sync 193 2147484096 {63593890899 259240000 0x112e300} {712342500 2636426 16832 21 433 433 4294967295 {1412910059 929565437} {1458294099 259240000} {1458294099 259240000} 193 81 16384 2048 0 0 {1412910059 929565437}}}
[M2XGE] 2016/03/18 02:41:39.764895 walk.go:214: DEBUG: error: /home/peter/Sync/bar.txt <nil> lstat /home/peter/Sync/bar.txt: no such file or directory
[M2XGE] 2016/03/18 02:41:39.764937 walk.go:214: DEBUG: error: /home/peter/Sync/bar.txt.sig <nil> lstat /home/peter/Sync/bar.txt.sig: no such file or directory
[M2XGE] 2016/03/18 02:41:39.764981 walk.go:214: DEBUG: error: /home/peter/Sync/foo.txt <nil> lstat /home/peter/Sync/foo.txt: no such file or directory
[M2XGE] 2016/03/18 02:41:39.765009 walk.go:214: DEBUG: error: /home/peter/Sync/foo.txt.sig <nil> lstat /home/peter/Sync/foo.txt.sig: no such file or directory
[M2XGE] 2016/03/18 02:41:39.765103 walk.go:167: DEBUG: Walk progress done /home/peter/Sync/ [bar.txt bar.txt.sig foo.txt foo.txt.sig] 131072 &{[] true 0xc821df4ae0 d41d8cd98f00b204e9800998ecf8427e 0xc8217aa240 0xc8230a7450}
....
remote machine:
-rw-r--r--   1 peter  peter         0 Mar 18 02:41 foo.txt.sig
-rw-r--r--   1 peter  peter         0 Mar 18 02:41 foo.txt
local machine:
peter@overcee[ 2:47AM]~/Sync-1027> fetch -q -o - 'http://localhost:8384/rest/db/browse?folder=default' | json_pp | egrep '(foo|bar).txt'
   "foo.txt" : [
            "foo.txt" : [
   "foo.txt.sig" : [
```

In the second sample, I did as separate steps:
```
touch bar.txt bar.txt.sig
touch foo.txt foo.txt.sig
... pause ...
rm foo* bar*
```
and "foo.txt" and "foo.txt.sig" got left behind.  You can see the syncthing trace show it was looking at them.

If I hit 'rescan' on the 'default' folder in the gui, then:
```
[M2XGE] 2016/03/18 02:49:42.520144 walk.go:100: DEBUG: Walk /home/peter/Sync/ [] 131072 &{[] true 0xc821df4ae0 d41d8cd98f00b204e9800998ecf8427e 0xc8217aa240 0xc8230a7450}
[M2XGE] 2016/03/18 02:49:42.520255 walk.go:488: DEBUG: checkDir /home/peter/Sync/ &{Sync 193 2147484096 {63593890899 259240000 0x112e300} {712342500 2636426 16832 21 433 433 4294967295 {1412910059 929565437} {1458294099 259240000} {1458294099 259240000} 193 81 16384 2048 0 0 {1412910059 929565437}}}
[M2XGE] 2016/03/18 02:49:42.520648 walk.go:246: DEBUG: ignored: .stfolder
[M2XGE] 2016/03/18 02:49:42.710836 walk.go:167: DEBUG: Walk progress done /home/peter/Sync/ [] 131072 &{[] true 0xc821df4ae0 d41d8cd98f00b204e9800998ecf8427e 0xc8217aa240 0xc8230a7450}
```
and on the remote side the files disappear, and the disappear from the browse json output.

So there's still a problem.  The simple case appears fixed though.

**Comment by DarkHelmet433** [comment] 2016-03-18 10:07
It doesn't seem to be dependent on doing the group of files as a single step either.  With shell, syncthing-inotify logs ("[OK]") and syncthing trace ("[M2XGE]") interleaved in order:
```
peter@overcee[ 2:58AM]~/Sync-1197> touch foo.txt foo.txt.sig bar.txt bar.txt.sig
...
[M2XGE] 2016/03/18 02:59:21.162739 walk.go:100: DEBUG: Walk /home/peter/Sync/ [bar.txt bar.txt.sig foo.txt foo.txt.sig] 131072 &{[] true 0xc821df4ae0 d41d8cd98f00b204e9800998ecf8427e 0xc8217aa240 0xc8230a7450}
[M2XGE] 2016/03/18 02:59:21.162881 walk.go:488: DEBUG: checkDir /home/peter/Sync/ &{Sync 197 2147484096 {63593891960 660184000 0x112e300} {712342500 2636426 16832 21 433 433 4294967295 {1412910059 929565437} {1458295160 660184000} {1458295160 660184000} 197 81 16384 2048 0 0 {1412910059 929565437}}}
[M2XGE] 2016/03/18 02:59:21.163046 walk.go:304: DEBUG: rescan: File{Name:"bar.txt", Flags:010644, Modified:1458295095, Version:[{M2XGECJ 14}], Size:128, Blocks:[]} 1458295160 -rw-r--r--
[M2XGE] 2016/03/18 02:59:21.163079 walk.go:319: DEBUG: to hash: bar.txt File{Name:"bar.txt", Flags:0644, Modified:1458295160, Version:[{M2XGECJ 15}], Size:0, Blocks:[]}
[M2XGE] 2016/03/18 02:59:21.163153 walk.go:304: DEBUG: rescan: File{Name:"bar.txt.sig", Flags:010644, Modified:1458295095, Version:[{M2XGECJ 14}], Size:128, Blocks:[]} 1458295160 -rw-r--r--
[M2XGE] 2016/03/18 02:59:21.163177 walk.go:319: DEBUG: to hash: bar.txt.sig File{Name:"bar.txt.sig", Flags:0644, Modified:1458295160, Version:[{M2XGECJ 15}], Size:0, Blocks:[]}
[M2XGE] 2016/03/18 02:59:21.163246 walk.go:304: DEBUG: rescan: File{Name:"foo.txt", Flags:010644, Modified:1458295095, Version:[{M2XGECJ 18}], Size:128, Blocks:[]} 1458295160 -rw-r--r--
[M2XGE] 2016/03/18 02:59:21.163264 walk.go:319: DEBUG: to hash: foo.txt File{Name:"foo.txt", Flags:0644, Modified:1458295160, Version:[{M2XGECJ 19}], Size:0, Blocks:[]}
[M2XGE] 2016/03/18 02:59:21.163304 walk.go:304: DEBUG: rescan: File{Name:"foo.txt.sig", Flags:010644, Modified:1458295095, Version:[{M2XGECJ 16}], Size:128, Blocks:[]} 1458295160 -rw-r--r--
[M2XGE] 2016/03/18 02:59:21.163330 walk.go:319: DEBUG: to hash: foo.txt.sig File{Name:"foo.txt.sig", Flags:0644, Modified:1458295160, Version:[{M2XGECJ 17}], Size:0, Blocks:[]}
[M2XGE] 2016/03/18 02:59:21.163350 walk.go:189: DEBUG: real to hash: bar.txt
[M2XGE] 2016/03/18 02:59:21.163396 walk.go:189: DEBUG: real to hash: bar.txt.sig
[M2XGE] 2016/03/18 02:59:21.163422 walk.go:189: DEBUG: real to hash: foo.txt
[M2XGE] 2016/03/18 02:59:21.163480 walk.go:189: DEBUG: real to hash: foo.txt.sig
[M2XGE] 2016/03/18 02:59:21.163576 walk.go:167: DEBUG: Walk progress done /home/peter/Sync/ [bar.txt bar.txt.sig foo.txt foo.txt.sig] 131072 &{[] true 0xc821df4ae0 d41d8cd98f00b204e9800998ecf8427e 0xc8217aa240 0xc8230a7450}
...
[OK] 02:59:21 Syncthing is indexing change in default: [bar.txt bar.txt.sig foo.txt foo.txt.sig]
...
peter@overcee[ 2:59AM]~/Sync-1198> fetch -q -o - 'http://localhost:8384/rest/db/browse?folder=default' | json_pp | egrep '(foo|bar).txt'

   "foo.txt" : [
   "foo.txt.sig" : [
   "bar.txt" : [
   "bar.txt.sig" : [
peter@overcee[ 2:59AM]~/Sync-1199> rm foo.txt foo.txt.sig bar.txt bar.txt.sig
...
[M2XGE] 2016/03/18 02:59:40.808277 walk.go:100: DEBUG: Walk /home/peter/Sync/ [bar.txt bar.txt.sig foo.txt foo.txt.sig] 131072 &{[] true 0xc821df4ae0 d41d8cd98f00b204e9800998ecf8427e 0xc8217aa240 0xc8230a7450}
[M2XGE] 2016/03/18 02:59:40.808370 walk.go:488: DEBUG: checkDir /home/peter/Sync/ &{Sync 193 2147484096 {63593891980 300297000 0x112e300} {712342500 2636426 16832 21 433 433 4294967295 {1412910059 929565437} {1458295180 300297000} {1458295180 300297000} 193 81 16384 2048 0 0 {1412910059 929565437}}}
[M2XGE] 2016/03/18 02:59:40.808466 walk.go:214: DEBUG: error: /home/peter/Sync/bar.txt <nil> lstat /home/peter/Sync/bar.txt: no such file or directory
[M2XGE] 2016/03/18 02:59:40.808518 walk.go:214: DEBUG: error: /home/peter/Sync/bar.txt.sig <nil> lstat /home/peter/Sync/bar.txt.sig: no such file or directory
[M2XGE] 2016/03/18 02:59:40.808577 walk.go:214: DEBUG: error: /home/peter/Sync/foo.txt <nil> lstat /home/peter/Sync/foo.txt: no such file or directory
[M2XGE] 2016/03/18 02:59:40.808610 walk.go:214: DEBUG: error: /home/peter/Sync/foo.txt.sig <nil> lstat /home/peter/Sync/foo.txt.sig: no such file or directory
[M2XGE] 2016/03/18 02:59:40.808813 walk.go:167: DEBUG: Walk progress done /home/peter/Sync/ [bar.txt bar.txt.sig foo.txt foo.txt.sig] 131072 &{[] true 0xc821df4ae0 d41d8cd98f00b204e9800998ecf8427e 0xc8217aa240 0xc8230a7450}
...
[OK] 02:59:40 Syncthing is indexing change in default: [bar.txt bar.txt.sig foo.txt foo.txt.sig]
...
peter@overcee[ 2:59AM]~/Sync-1200> fetch -q -o - 'http://localhost:8384/rest/db/browse?folder=default' | json_pp | egrep '(foo|bar).txt'

   "foo.txt" : [
   "foo.txt.sig" : [
```
And again, a forced scan from the GUI fixes it.

**Comment by calmh** [comment] 2016-03-18 10:16
The deletion detection logic for scanning with subs is also broken, in a similar but different way to the other breakage. :)

**Comment by calmh** [comment] 2016-03-18 12:12
Try this one: http://build.syncthing.net/job/syncthing-branch/227/artifact/src/github.com/syncthing/syncthing/

**Closed** 2016-03-18 12:16 UTC
Labels: bug

**Comment by DarkHelmet433** [comment] 2016-03-18 12:20
I don't see the #228 build - gets a 404.  Using the 'next' links from #226 only goes up to 227, as does http://build.syncthing.net/job/syncthing-branch/

**Comment by calmh** [comment] 2016-03-18 12:22
Apparently Jenkins crashed during the build. It seems to do that now and then when things are pushed to master. Hang on and I'll trigger a new build (229). :)

**Comment by calmh** [comment] 2016-03-18 12:29
There: http://build.syncthing.net/job/syncthing-branch/229/artifact/src/github.com/syncthing/syncthing/

**Comment by DarkHelmet433** [comment] 2016-03-18 12:42
Build 229 looks good so far.. 
I'll continue to beat on it in anger and see if I can break it again :)
Thanks!
