### ISSUE TITLE
sync fails when a file has the same size and timestamp, but the hash is invalid.

### ISSUE THREAD

**Issue by jhernberg** [syncthing/syncthing#2414] opened 2015-10-28 18:48 UTC
It appears that there is a race condition and syncing can fail in the following scenario.  A file has changed, but still has the same timestamp and size as when syncthing already created the hash.  In this case the puller will flag a file as failed.  I don't know the design decisions of the program, but maybe a good workaround would be for the puller to ask the sender to rescan such files.

The puller side will have entries like this repeating in the log:

Oct 27 22:55:34 tor syncthing[1244]: [VWIC7] INFO: Puller (folder "Working", file "La Coccinelle/La Coccinelle - Guitar - 151027/Media/02-Click Check-151027_2101.wv"): pull: no available source device
Oct 27 22:55:34 tor syncthing[1244]: [VWIC7] INFO: Puller: final: no available source device

Forgot to add some information: syncthing 0.11.26 and syncthing-inotify 0.6.7, both systems running linux.

**Comment by AudriusButkevicius** [comment] 2015-10-28 19:01
Whatever is creating the file violates the basic principles imposed by the OS. The time and size are snapshotted before the hash is calculated, so its impossible to modify the content and not mtime without deliberately doing so.

In a case where this is done deliberately, syncthing can't do anything.

**Comment by jhernberg** [comment] 2015-10-28 19:10
As I understood from calmh on irc, it's possible that a modification took place at the same timestamp without changing the size of the file (for instance updating a header), and thus syncthing will ignore the notification that the file has change and not create a new hash for it.

**Comment by DarkHelmet433** [comment] 2015-10-28 21:54
I've had this problem.  Syncthing has begun indexing while a file is being modified in the same 1-second time window and the hasher got stale data.  I suspect it depends on whether you're getting sub-1-second timestamp granularity or not from the OS / file system.

The problem is syncthing doesn't recover gracefully.  If the hasher lost the race and pushes an inconsistent hash to the network, no nodes have data that matches the hash.  As near as I can tell, the node with the bad hash keeps sending inconsistent data that doesn't match the hash it provided and the other nodes go into "Not making progress, pausing puller for 1 minute" mode.

I modified our publication step into the syncthing mesh by writing to the directory, pausing one second and bumping the timestamp a second time to make sure that syncthing will invalidate any partial hash work.  Where we can, we rename into the pool to try and avoid ever modifying a file in place.

It would be better if the sender detected the unexpected hash mismatch and automatically rehashed.

For the most part, we have a separate master folder and rsync into the syncthing work directory.  That solves the update races and works around the broken "Master folder" mode.

**Comment by AudriusButkevicius** [comment] 2015-10-28 22:00
So this is easily solvable, the requestee already sends the expected hash, we just need to check if the content matches as we read it off the disk and rescan. There is even a PR for this, but its not finished as far as I recall, correct @Zillode ?

**Comment by calmh** [comment] 2015-10-29 07:33
"dealbreaker"? :) OK. Ideally we'd want to check against our own block database though, as the device on the other side may be acting on an old index or something similar.

(Also, future complication: variable block size, with blocks being larger than the requested amount of data.)

**Comment by samvde** [comment] 2015-11-26 15:14
Well, to me it's a dealbreaker. I just experienced an issue where sync would be stuck at x% waiting for some 10GB worth of PST files to sync between MS and Linux. Updating the timestamp on all the PST files fixed this for me.

The fact that it's blocking the syncing operation because of this is the big issue.

**Comment by Zeitwaechter** [comment] 2015-12-23 22:39
Seems similiar to my problem..

I do sync files of a WordPress project between multiple nodes with a rescan timing of 10 secs.
One node - dev (MS), one node - dev (Arch Linux), one node - "backup" (Arch Linux) and one node webhost (Arch Linux).
(It doesn't matter - at this point - if it's really a good idea to do it that way. CI will be implemented on a later date.)

The thing is: 
If I change parts of the source code on one node (Linux) and the sync begins I get the kind of a feeling that any of the other nodes - probably the MS-one - syncs old content back because it just got updated - so I think it has to do with the timestamp. Thus, conflict-files are created unnecessarily.

I apologize for not having looked deeper into it and that I'm just pin-pointing.. But it sounds so alike that I couldn't resist to add my scenario to the list.

**Comment by AudriusButkevicius** [comment] 2015-12-23 23:52
No, conflicts are created by concurrent modifications. Though there is a report about some windows machines misbehaving in the recent release. You can try an older release like suggested in that ticket and if that helps do a git bisect helping us understand which commit introduced it, as none of us can repro it.

**Comment by AudriusButkevicius** [comment] 2016-07-04 20:46
Closing in favor of #2922

**Closed by AudriusButkevicius** 2016-07-04 20:46 UTC
Labels: bug
