### ISSUE TITLE
Adèle Exarchopoulos marked as invalid directory name

### ISSUE THREAD

**Issue by rocky1138** [syncthing/syncthing#1805] opened 2015-05-13 00:26 UTC
File name "x/y/Ad?le Exarchopoulos" contains invalid characters; marked as invalid.

The character which is invalid is è, but many languages use this character, so I'm thinking this is a bug.

v0.11.3, Linux (ARM)

**Comment by calmh** [comment] 2015-05-13 06:14
The error you quote only exists in code compiled for Windows, but you say Linux. The filename in the topic doesn't contain any invalid characters, but the one quote has a question mark in it which is not allowed on Windows. This makes no sense?

**Comment by rocky1138** [comment] 2015-05-13 23:35
Derp, I think you're right. I had two tabs open: one for my windows machine, one for my RPi. I must have copied the error from the wrong window, meaning that this was a Windows machine error.

**Comment by rocky1138** [comment] 2015-05-14 01:27
21:25:44: File name "Music/Arstodir/?rst??ir - ?rst??ir - Live in Dresden 2013 (FREE DOWNLOAD - includes Heyr himna smi?ur) - 05 Or? a? eigin vali.mp3" contains invalid characters; marked as invalid.

21:25:44: File name "Music/Arstodir/?rst??ir - ?rst??ir - Live in Dresden 2013 (FREE DOWNLOAD - includes Heyr himna smi?ur) - 06 ? me?an j?r?in sefur.mp3" contains invalid characters; marked as invalid.

21:25:44: File name "Music/Arstodir/?rst??ir - ?rst??ir - Live in Dresden 2013 (FREE DOWNLOAD - includes Heyr himna smi?ur) - 07 Lj?? ? sand.mp3" contains invalid characters; marked as invalid.

21:25:44: File name "Music/Arstodir/?rst??ir - ?rst??ir - Live in Dresden 2013 (FREE DOWNLOAD - includes Heyr himna smi?ur) - 08 N? gleymist ?g.mp3" contains invalid characters; marked as invalid.

21:25:44: File name "Music/Arstodir/?rst??ir - ?rst??ir - Live in Dresden 2013 (FREE DOWNLOAD - includes Heyr himna smi?ur) - 09 Heyr, himna smi?ur (live at Wuppertal train station).mp3" contains invalid characters; marked as invalid.


---

The characters are from this filename: Árstíðir - Árstíðir - Live in Dresden 2013 (FREE DOWNLOAD - includes Heyr himna smiður) - 01 Þér ég unni

**Comment by calmh** [comment] 2015-05-14 07:00
That's weird though. What's the locale etc on that Pi? We handle utf-8 filenames just fine, and the complaint on the windows side seems to be about the literal question mark. Something seems to happen to make us think those file names contain question marks already on the Pi... o_O

**Comment by rocky1138** [comment] 2015-05-18 01:01
en_gb

On Thu, May 14, 2015 at 3:00 AM, Jakob Borg <notifications@github.com>
wrote:

> That's weird though. What's the locale etc on that Pi? We handle utf-8
> filenames just fine, and the complaint on the windows side seems to be
> about the literal question mark. Something seems to happen to make us think
> those file names contain question marks already on the Pi... o_O
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/syncthing/syncthing/issues/1805#issuecomment-101944048>
> .
>



-- 
http://www.johnrockefeller.net

**Comment by rocky1138** [comment] 2015-05-18 01:01
pi@pibridge ~ $ locale
LANG=en_GB.UTF-8
LANGUAGE=
LC_CTYPE="en_GB.UTF-8"
LC_NUMERIC="en_GB.UTF-8"
LC_TIME="en_GB.UTF-8"
LC_COLLATE="en_GB.UTF-8"
LC_MONETARY="en_GB.UTF-8"
LC_MESSAGES="en_GB.UTF-8"
LC_PAPER="en_GB.UTF-8"
LC_NAME="en_GB.UTF-8"
LC_ADDRESS="en_GB.UTF-8"
LC_TELEPHONE="en_GB.UTF-8"
LC_MEASUREMENT="en_GB.UTF-8"
LC_IDENTIFICATION="en_GB.UTF-8"
LC_ALL=

On Sun, May 17, 2015 at 9:00 PM, John Rockefeller <jrockefeller1@gmail.com>
wrote:

> en_gb
>
> On Thu, May 14, 2015 at 3:00 AM, Jakob Borg <notifications@github.com>
> wrote:
>
>> That's weird though. What's the locale etc on that Pi? We handle utf-8
>> filenames just fine, and the complaint on the windows side seems to be
>> about the literal question mark. Something seems to happen to make us think
>> those file names contain question marks already on the Pi... o_O
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/syncthing/syncthing/issues/1805#issuecomment-101944048>
>> .
>>
>
>
>
> --
> http://www.johnrockefeller.net
>



-- 
http://www.johnrockefeller.net

**Comment by rocky1138** [comment] 2015-05-18 01:02
I just checked on my Windows machine, and the offending character has been replaced with an underscore. I'm fine with that. I'm not sure why it happened, though.

**Comment by AudriusButkevicius** [comment] 2015-05-18 07:21
Syncthing does not replace characters? Are you running 2 sync solutions side by side?

**Comment by rocky1138** [comment] 2015-05-18 18:51
Yes.

**Comment by AudriusButkevicius** [comment] 2015-05-18 19:26
In that case, strange things can happen I guess, and I guess your second solution solved the problem by replacing the characters with underscores, as syncthing does not yet have this feature.

**Comment by Zillode** [comment] 2015-07-29 18:20
Thus duplicate of https://github.com/syncthing/syncthing/issues/1734

**Closed by Zillode** 2015-07-29 18:20 UTC
