### ISSUE TITLE
"Receive Encrypted" folder incorrectly reports "unexpected items" after "reverting local additions"

### ISSUE THREAD

**Issue by tomasz1986** [syncthing/syncthing#8278] opened 2022-04-13 09:27 UTC
1. On Device 1, add a new folder with some files to Syncthing.
2. Share the newly added folder with Device 2, protecting it with a password.
3. On Device 2, accept the folder as "Receive Encrypted", but point it at a path with pre-existing files.
4. Let the two devices sync. A manual connection reset will be necessary for the first sync to actually work.
5. Device 2 will now download the files, while also reporting "local additions".
6. Use the "revert local additions" button to get rid of the non-encrypted files.
7. Device 2 now reports "unexpected items", even though the files themselves have been physically deleted. Pressing the "revert local additions" button again does nothing.
8. Pausing and resuming the folder is required to clear the error.

The final state, before step 8., looks like this:

![image](https://user-images.githubusercontent.com/5626656/163145307-1ed798cb-6776-4a4b-856f-5027af612970.png)
![image](https://user-images.githubusercontent.com/5626656/163145317-e5a7aec1-1b8f-4401-afa0-9fc61945ee8f.png)
![image](https://user-images.githubusercontent.com/5626656/163145327-6dc80489-c0a3-48ea-ad3d-7adaa6150b1c.png)

Below are logs with `db,model` enabled:

- [syncthing1.log](https://github.com/syncthing/syncthing/files/8480106/syncthing1.log)
- [syncthing2.log](https://github.com/syncthing/syncthing/files/8480109/syncthing2.log)

All testing was done using the current `main` (0525c755f4d2e4b0254b7eb33d9b45ea5474993e) under Windows 10.

**Comment by calmh** [comment] 2023-03-10 08:11
Duplicate of #8196

**Closed by calmh** 2023-03-10 08:11 UTC
Labels: bug, needs-triage
