### ISSUE TITLE
lib/model: Reply with an error message when block hash check fails

### ISSUE THREAD

**Issue by AudriusButkevicius** [syncthing/syncthing#2922] opened 2016-03-31 22:20 UTC
And rescan on provider, to work around mtime and similar issues?

Alternatively we could check the hash on the provider instead, but that's CPU load on the provider, which I am not sure if it's a good idea? 
In a distributed state it's probably better to split the CPU load among many providers, but in the initial state peers might overwhelm it, unless temp indexes.

**Comment by calmh** [comment] 2016-04-01 06:56
(Sort of duplicate of #2414, although that one describes the problem and this the solutions.)

**Comment by calmh** [comment] 2016-04-01 06:59
One possible way to tackle it (which may be mentioned somewhere) would be to keep a cache of the last *x* blocks requested by a given peer. If they're asking for something we've already given them, we should recheck that block (file) or be suspicious of that peer. It's something that indicates an error somewhere in the chain at least, as it shouldn't happen during normal operations.

**Comment by AudriusButkevicius** [comment] 2016-04-01 07:05
You think thats better than an additional message?

**Comment by calmh** [comment] 2016-04-01 07:41
Not necessarily, although I'm still thinking about it... It's just I don't really like having to relay on another device to tell us we are wrong for us to be able to fix the situation. Hence maybe preferring to always hash data before sending (unless told not to by configuration, maybe defaulting to having this disabled if hash performance is below a threshold), or doing periodic rehashes anyway, or triggering on suspicious behavior as above...

**Comment by DarkHelmet433** [comment] 2016-07-04 22:40
I'm still not sure this isn't a syncthing problem.  I thought I had observed that it wasn't waiting for files to properly settle before beginning to hash them, but that might have been a side effect of another fixed bug.

Anyway, given this sequence of events:
clock tick 1
process writes first update, file has timestamp of 'tick1'
syncthing wakes up and hashes
process writes second update, file has new contents but still has a timestamp of 'tick1'
clock tick 2

The file's timestamp will be "tick 1" and would have been syncthing's fault for being too quick.  Other tools wait for the timestamp to be at least 1 second old before beginning operations so that they can actually detect a 3rd party update.  Even venerable old unix make(1) has 1-second timestamp granularity workarounds.

With 'settle' deferral then this sequence would happen instead:
clock tick 1
process writes first update
syncthing wakes up, notices file timestamp == now, defers hashing for 1 second
process writes second update
clock tick 2
syncthing wakes up, sees timestamp = 'now-1', begins hashing.  At end of hashing it is still 'now-1' so it can conclusively determine that there was no undetected write and can now push the hash to the cluster.

If the file's timestamp is in the same second as 'now' then there's no meaningful way to detect an update.

This opens other cans of worms.. if a file is being constantly written then the hashes still will go stale due to the continuous deferrals so things are never quite that simple.  A scan/hash can't be considered "final" unless the timestamps at the start and end of the hashing operation are at least 1 second old.

Of course, if syncthing is already taking care of this then I'll apologize and go hide in a corner.

**Comment by canton7** [comment] 2016-07-04 22:46
Synching doesn't handle constantly changing files particularly well anyway (in my understanding): by the time a puller tries to fetch the file, it's changed and the pull fails.

**Comment by AudriusButkevicius** [comment] 2016-07-04 22:48
So on most filesystems (not FAT32 and Samba probably), modification timestamps are down to the milliseconds, and given we have various things before we actually process the file (such as db access, finish hashing previous file since it gets placed into the queue), I'd say it's fairly unlikely for what you've described to happen.

Yet I don't have objections to defer hashing queueing for a second, it should have no effect (apart from increasing minimum scan time by one second).

**Comment by DarkHelmet433** [comment] 2016-07-04 23:19
For what its worth, the BSD UFS1 file system is strictly 1-second granularity.

UFS2 itself supports millisecond precision (although the kernel only does it with millisecond precision):
 49289 stat     CALL  lstat(0x7fdfffffcf5,0x7fdfffff808)
 49289 stat     NAMI  "foo"
 49289 stat     STRU  struct stat {dev=54, ino=2638133, mode=0100644, nlink=1, uid=0, gid=0, rdev=10538224, atime=1467673055.893984000, stime=1467673488.479654000, ctime=1467673488.479654000, birthtime=1467673055.893968000, size=4, blksize=16384, blocks=4, flags=0x0 }
 49289 stat     RET   lstat 0

Likewise with ZFS there are also 1ms timestamps.

I have only used syncthing with ufs2 and zfs, so there are 1ms timestamps available and that invalidates my argument entirely. Gah.

I haven't seen the problem in quite a while though.  I did modify the freebsd.org cluster to avoid modifying files in place that syncthing could see.  Instead I strictly renames files into place so there should never be stale hashes.  After the inotify + common path prefix fix a few revisions ago I haven't seen any stuck sync operations there.

**Comment by calmh** [comment] 2016-07-05 06:21
Syncthing only looks at the second part of file timestamps. Any higher precision is ignored currently.

**Comment by DarkHelmet433** [comment] 2016-07-06 16:41
Huh, so that does make it a syncthing bug then?  If it's actually doing hashing in the same 1 second interval as a file is modified and ignoring sub-1-second timestamps then how can it detect when it is losing a race?

**Comment by calmh** [comment] 2016-07-06 17:19
It doesn't.

**Comment by imsodin** [comment] 2018-10-18 15:11
If I understand this issue right it is fixed by #4767 by checking the hash on the provider and rescanning if appropriate.

**Closed by imsodin** 2018-10-18 15:11 UTC
Labels: enhancement
