### ISSUE TITLE
Syncthing never sync if folder settings is only upload on master and only download on client

### ISSUE THREAD

**Issue by playaz44** [syncthing/syncthing#9684] opened 2024-09-05 23:16 UTC
### What happened?

Hello, on latest version v1.27.11 I can't sync folders with settings:

1. on primary node where files are created folder settings are set to "send only"
2. then files are uploaded to the main server where all files are kept and this folder is set to "download only"
3. then files from folder "download only" is assigned to another folder with send and receive perms on this same node where are distributed from the main server to individual clients
4. then a sync error occurs, duplicates occur and then whatever you choose (use local version, last known conflict version or newest file) the sync error disappears for a few minutes and then reappears

discarding local changes on the main server does not bring any changes

in the previous version of syncthing ignoring local changes resulted in synchronizing all files according to the main folder, now every few minutes a sync error will be displayed on all clients using the main folder

summarize: folder is sent to another master server where it is assigned to receive only, then the same folder is assigned to another master folder (on the same node) which has permission to write and read from all clients, previously, rejecting local changes on the main server in the download-only folder resulted in file synchronization on all clients without any error, currently on the latest version of syncthing rejecting local changes causes a duplicate synchronization error on each client and whatever is selected has no effect, this folder cannot be synchronized

### Syncthing version

v1.27.11

### Platform & operating system

Linux arm64, linux intel/amd64

### Browser version

Chrome 128.0.6613.114

**Comment by calmh** [comment] 2024-09-06 05:04
> causes a duplicate synchronization error on each client 

What does this even mean? This report is sorely lacking in actual error messages or screenshots of the problem.

**Comment by playaz44** [comment] 2024-09-06 22:22
![image](https://github.com/user-attachments/assets/0c852ec1-f650-4a4b-b442-d476d3abb434)

client 1 duplicate files error:
![image](https://github.com/user-attachments/assets/0f85b3a6-644f-4ce1-83e9-d2daa32f3d61)

Previously, rejecting local changes on node 2 override all clients so that each had the original files from node 1. Currently, rejecting local changes has no effect because clients frequently say that there is a problem with duplicate files and deleting the entire folder and synchronizing again does not help.

**Comment by calmh** [comment] 2024-09-07 04:15
Ah, I think this is #9677, try with newly released .12

**Comment by calmh** [comment] 2024-09-08 05:35
Duplicate of #9677

**Closed by calmh** 2024-09-08 05:35 UTC
Labels: bug, needs-triage
