### ISSUE TITLE
Delete device will trigger folder scan, keep delete old device make the syncthing consume height cpu and disk io.

### ISSUE THREAD

**Issue by WoolenWang** [syncthing/syncthing#9637] opened 2024-08-08 08:07 UTC
### What happened?

trigger the DELETE /devices/{device_id} api to delete old lose connect device 
the syncthing will start scan all folders (all folders are share each device)

### Syncthing version

v1.27.4

### Platform & operating system

windows x64

**Comment by tomasz1986** [comment] 2024-08-08 08:35
Duplicate of https://github.com/syncthing/syncthing/issues/6891? Why this happens is explained in https://github.com/syncthing/syncthing/issues/6891#issuecomment-674368449.

**Closed** 2024-08-08 20:02 UTC
Labels: bug, needs-triage
