### ISSUE TITLE
Run on mobile data, run on metered wi-fi desktop options

### ISSUE THREAD

**Issue by RustoMCSpit** [syncthing/syncthing#9745] opened 2024-09-29 22:06 UTC
### Feature description

Android has these settings but not desktop

### Problem or use case

.

### Alternatives or workarounds

.

**Comment by RustoMCSpit** [comment] 2024-09-29 22:08
similar / the same? https://github.com/syncthing/syncthing/issues/8394

**Comment by imsodin** [comment] 2024-09-30 04:59
Indeed duplicate of https://github.com/syncthing/syncthing/issues/8394

**Closed by imsodin** 2024-09-30 04:59 UTC
Labels: enhancement, needs-triage
