### ISSUE TITLE
make a hook on new sync 

### ISSUE THREAD

**Issue by angryjk** [syncthing/syncthing#7222] opened 2020-12-21 14:26 UTC
Hello team! I am intrested in such feature like:
1 When new changes made in file hook to remote server.

**Comment by calmh** [comment] 2020-12-21 14:28
Duplicate of #5601 maybe?

**Comment by angryjk** [comment] 2020-12-21 14:40
> Duplicate of #5601 maybe?

Hi calmh! Thank you for fast responce. Have not tested windows cli! But almost yes. Maybe i should share more toughts. Will tr y to make it in next message.

**Closed** 2020-12-21 14:41 UTC
Labels: enhancement, needs-triage
