### ISSUE TITLE
Updated device name not used

### ISSUE THREAD

**Issue by scienmind** [syncthing/syncthing#4211] opened 2017-06-14 10:19 UTC
After updating to 0.14.30 (includes #4168):

On device A:
 - Edit device B, erase name field (so that it'll receive name updates from B), save
 - Device B name is shown to be few chars of its ID
 - Once device B connects, the ID chars are replaced with B's "readable" name (so far so good)

On device B: 
 - Change self name from "B" to "NEW_NAME". Restart (should not be needed, but to make sure...)

On device A: 
 - restart
 - wait for B to connect
 - console shows: `Device IDIDIDID client is "syncthing v0.14.30" named "NEW-NAME"`
 - however, in web UI, device B's name remains "B" and not changes to "NEW_NAME"

---
As a side note (maybe i should file a separate issue with it...): 
Iit's not really clear when the device name in use will be updated remotely and when it won't.
According to the UI notice, Updates will take place if the field was initially left blank. However, once device connected and received the name, it'll be filled in there, unclear for the user whether it was written there manually 3 month ago and here to stay forever, or was received automatically and is expected to receive further updates.

Suggestion: In case of auto update - dim the name field un-editable, and add checkbox:
" [ ] Override device name". Once checked, user can set his alias for device and updates won't be received.

---
### Version Information

Syncthing Version: v0.14.30
OS Version: Windows 10 x64

**Comment by calmh** [comment] 2017-06-14 11:52
This exists as the advanced option `overwriteRemoteDeviceNamesOnConnect` but the UI could be better.

**Comment by AudriusButkevicius** [comment] 2017-06-14 12:41
This is working as intended, you misinterpreted what was being fixed in that pull request.

**Closed by AudriusButkevicius** 2017-06-14 12:41 UTC

**Comment by scienmind** [comment] 2017-06-14 13:40
I see, my bad.

I thought the intent was to implement calmh's suggestion here: https://github.com/syncthing/syncthing/issues/4164#issuecomment-303031386

>  It would probably be better to turn this on it's head, always follow the other side by default, and in the device configuration have an explicit "[X] Override device name: ________________" thing.
