### ISSUE TITLE
Don't sync on metered networks

### ISSUE THREAD

**Issue by MikeBishop** [syncthing/syncthing#2426] opened 2015-11-03 09:01 UTC
In https://github.com/syncthing/syncthing-android/issues/409, the Android client was updated to not sync over metered Wi-Fi networks.  However, a quick test shows that the Windows client is perfectly happy to sync over metered Wi-Fi (or presumably, cellular) networks.  Could you consider adding a similar restriction to the Windows code, so that SyncThing doesn't suck multiple GB over my tethered cell phone?

**Comment by MikeBishop** [comment] 2015-11-03 09:20
For additional info, it looks like the Windows APIs for this are the [NLM_CONNECTION_COST](https://msdn.microsoft.com/en-us/library/windows/desktop/hh448264(v=vs.85).aspx) enum returned by [INetworkCostManager::GetCost](https://msdn.microsoft.com/en-us/library/windows/desktop/hh448261(v=vs.85).aspx).

**Comment by alex2108** [comment] 2015-11-03 12:00
I think this is something for [SyncTrayzor](https://github.com/canton7/SyncTrayzor) or other wrappers to add, syncthing is platform independent and this feature maybe does not even exist for all operating systems. (on android it's also not syncthing itself, but the java gui application that has this feature)

**Comment by MikeBishop** [comment] 2015-11-03 12:32
Okay -- I can relay the suggestion over there, then.  I presume SyncTrayzor has a way to tell SyncThing not to sync?  Or does it just stop the process and be done with it?

**Comment by calmh** [comment] 2015-11-03 13:06
Devices can be paused, which is probably the right way to do it from the inside. If the Windows API can be implemented cleanly in syncthing I'm not necessarily against doing that either.

**Comment by kc0tfb** [comment] 2015-11-22 12:52
Allowing the local wrapper to adjust individual hosts is probably the best way to do it. Consider this a "+1" for that idea. Ideally, this would pause anything going through the default gateway on a network while still allowing sync to things on the local subnet. (e.g. My son and I each tether to my phone's hotspot; our laptops are still syncing while everything else pauses).

**Comment by capi** [comment] 2015-11-22 18:13
@calmh Isn't pausing devices still exchanging index? Or does it really prevent connections between the devices?

**Comment by calmh** [comment] 2015-11-22 18:18
Paused devices are disconnected, yes.

**Comment by lkwg82** [comment] 2018-08-11 09:52
As I recognize, this is implemented in SyncTrayzor some time ago.

**Comment by AudriusButkevicius** [comment] 2018-08-11 11:45
@lkwg82 please stop closing things just because you feel like it.

**Comment by lkwg82** [comment] 2018-08-11 14:45
@AudriusButkevicius I believe this is implemented.

**Comment by capi** [comment] 2018-08-11 14:47
@lkwg82 Even if it is implemented in SyncTrayzor, it is not implemented in Syncthing itself. Not everyone is using SyncTrayzor on Windows, since this is mutually exclusive with running it as a service. So there might be a reason to implement this in Syncthing "core" as well.

**Comment by ignisf** [comment] 2018-12-23 11:36
NetworkManager also provides information if the current connection is metered (see https://people.freedesktop.org/~lkundrak/nm-docs/nm-dbus-types.html#NMMetered) so IMO this feature may be useful on all platforms

**Comment by 3v1n0** [comment] 2019-02-04 17:41
Metered setting flag in network manager connections can be easily fetched also via DBus and should definitely be implemented by synchting as it's not something strictly UI related (and NM stays in system service in fact)

**Comment by AudriusButkevicius** [comment] 2019-02-04 18:49
A PR implementing this would be the best evidence of this being simple :)

**Comment by jtagcat** [comment] 2020-06-07 16:33
Nman also differentiates between guessing and user defined.

It would be nice to do this per-folder and sync files up to this size / throttle to this speed and smallest files first (still keeps the sync going, but avoids causing problems).

I'm not familiar with syncthing (and not very with go), but I can try to implement this.

**Comment by AudriusButkevicius** [comment] 2020-06-07 16:45
PRs are always welcome, if you have questions regarding implementation, you can ask them on the forum, and we'll always be happy to help.

**Comment by jtagcat** [comment] 2020-06-15 08:00
Note to self: Would implement in 2 parts:
 - First, an API to call with 'System is now Metered!', 'System is now not metered'
(- Metered behaviour, per-folder, do you pause it, download&/upload files smaller than x)
 - Plug all platforms in to the API
Probably duplicate it (to have the same (independent) api for power-saving).
Also look in to getting some of https://github.com/Catfriend1/syncthing-android implementation of this to upstream (only leaving the wrapper to deal with forwarding the system's status to syncthing)

**Comment by vn971** [comment] 2022-08-12 21:15
Adding to what others have already said, checking the metered connection in the way that @ignisf mentioned would also help owners of PinePhones and Librem phones. Syncthing works well on these phones! The metered limitation is crucial there though, for the same reasons as it is on Android.

**Comment by calmh** [comment] 2023-03-10 13:53
Duplicate of #8394 

(that issue being more general)

**Closed by calmh** 2023-03-10 13:53 UTC
Labels: enhancement
