### ISSUE TITLE
User remains logged in after shutdown when leaving or unchecking "Stay logged in" at login prompt

### ISSUE THREAD

**Issue by ProperBrgdbald** [syncthing/syncthing#9420] opened 2024-02-15 01:36 UTC
- Version: v1.27.3, Linux (64-bit Intel/AMD)
 - found as of update on Feb 7, 2024 (v1.27.3)
 - Firefox 110.0, to be tested on 122.0.1

**What I do:** 
1. I start up Syncthing while on my computer (manually started) 
2. I run the Web UI
3. I log in to the Web UI (leaving "Stay logged in" unchecked), 
4. I check on my syncing, 
5. I use the Actions -> Shutdown to stop syncing and then shut down my computer.

**What I find:**
- With the "Stay logged in" unchecked, upon next start of my computer, Syncthing and the Web UI, I am immediately/already logged in.

**What I expect:** 
- With the "Stay logged in" unchecked, upon next start of my computer, Syncthing and the Web UI, I need to provide login credentials.
- If I have only shutdown Syncthing: with the "Stay logged in" unchecked, upon next start of Syncthing and the Web UI, I need to provide login credentials.

**Comment by ProperBrgdbald** [comment] 2024-02-15 02:34
The new Actions -> Log out is a useful addition, but it seems the user cannot log out and shut down at the same time.

**Additional testing and change from v1.23.6:**
From being logged in and looking at the Syncthing main page:

- Using Actions -> Shutdown with the browser remaining open, and then restarting Syncthing and UI
  - 1.23.6: Syncthing remains logged in
  - 1.27.3: Syncthing remains logged in

- Using Actions -> Shutdown, then close the browser, and then restart Syncthing and UI
  - 1.23.6: Syncthing prompts for login (as expected)
  - 1.27.3: Syncthing remains logged in
  
- Close the browser without shutting down Syncthing and UI, then restart browser or UI:
  - 1.23.6: Syncthing remains logged in
  - 1.27.3: Syncthing remains logged in

**Comment by calmh** [comment] 2024-02-15 06:14
Not checking the box means the credentials are session scoped in the browser, meaning you get logged out by closing the browser window.

**Comment by ProperBrgdbald** [comment] 2024-02-19 06:23
I thought the new login screen was introduced after 1.23.6 (ie. 1.23.6 uses the browser prompt rather than a dedicated page).

To confirm:
- Is Syncthing's intended behaviour to remain logged in after a shutdown or restart?
- Or is this is how the credentials are stored in the browser and therefore not something Syncthing controls?

**Comment by calmh** [comment] 2024-02-19 06:55
GUI authentication was added in 0.8.0 in April 2014, where you remained logged in over a restart since the browser cached the credentials.

The HTML login form was added in 1.26.0 in November 2023. The behaviour changed so that restart caused logout since the browser only had a session cookie, and Syncthing forgot the session cookie on restart. This was a regression on a decade-long established behaviour.

This was fixed in 1.27.3 by retaining the session server-side over restarts. To summarise the current behavior, which I think is as desired:

- If you log in and restart Syncthing, you remain logged in.
- If you tap log out you get logged out.
- If you *didn't* select "keep me logged in" when logging in and you close your browser window, you get logged out.

**Closed** 2024-02-19 06:57 UTC
Labels: bug, needs-triage
