### ISSUE TITLE
Folder isn't making progress

### ISSUE THREAD

**Issue by merlink01** [syncthing/syncthing#1521] opened 2015-03-25 21:12 UTC
System 1 is Raspbian, System 2 is Arch Linux
Syncthing v0.10.29 <---> Syncthing v0.10.29

On the Raspbian System:
[JKWBD] 22:05:06 WARNING: Folder "hostname" isn't making progress - check logs for possible root cause. Pausing puller for 1m0s.

Before there are a lot of messages like:
[JKWBD] 21:48:56 INFO: Puller (folder "hostname", file "path/to/file"): shortcut: chmod path/to/file: operation not permitted

and:
[JKWBD] 22:08:14 INFO: Puller (folder "Console", file " path/to/file"): dst stat dir: stat /home/pi path/to/folder: no such file or directory

There are some spaces in Folder Name.

**Comment by merlink01** [comment] 2015-03-25 21:56
OK, the Folder wasn't created, thats why I got this Message.
[JKWBD] 22:08:14 INFO: Puller (folder "Console", file " path/to/file"): dst stat dir: stat /home/pi path/to/folder: no such file or directory

After I created this Folder manually, syncing of the Files inside this folder starts fine.

So there seems to be a problem in creating Folders.

Could also be caused ba spaces in the Foldername like "My Folder".

**Comment by merlink01** [comment] 2015-03-25 22:00
A second small Bug: If this happens, files are queued multiple times, so the list of not syncronized objects is bigger than necessary.

**Comment by AudriusButkevicius** [comment] 2015-03-25 22:17
Is the folder by accident matching any set of ignore patterns.

**Comment by merlink01** [comment] 2015-03-26 08:44
No, no ignore patterns defined on both Machines.

**Comment by AudriusButkevicius** [comment] 2015-03-26 09:12
Best option in this case I guess is to nuke the indexes, as they somehow got corrupt in a way that a file has lost the parent directory index entry.

**Comment by merlink01** [comment] 2015-03-26 17:59
OK, I'll try it.

Should I delete the Index Files on Both machines?

**Comment by AudriusButkevicius** [comment] 2015-03-26 21:15
It might be a good idea.

**Comment by merlink01** [comment] 2015-03-28 16:07
OK, I fixed it now. Thanks.

I had to delete the index Files on the raspberry.

After this a small number files stayed to do no progress.
chmodded them to 777 didn't help. 
changed ownership from root:root to pi:pi for this files did the job.

What about a funktion to overtake the ownership of all files in the sync folder?

**Comment by AudriusButkevicius** [comment] 2015-03-28 16:18
We might not be running as root, hence we might not be able to take ownership of anything.
Ideally syncthing creates stuff in the users home directory, hence we already own both the files and the directory.

The issue might be that someone packaged the package for RPI incorrectly.

**Comment by merlink01** [comment] 2015-03-29 15:05
In this case it was a filecopy from root so everything is fine with the package.

But it could be practical to generate a warning if files in a syncdir are not owned by the syncthing user.

**Comment by jstnlth** [comment] 2015-04-27 18:47
I had a similar problem - a root:root owned file was copied.  Ownership was changed to root, and then of course it couldn't do chmod permissions after that (syncthing running as non-root).  I got this log message: " INFO: Puller (folder "foldername", file "folder/file.ext"): shortcut: chmod folder/file.ext: operation not permitted".   Perhaps you can change the order around, and set the ownership as the LAST attribute to be changed?  Of course this only fixes the FIRST time sync, so any deletions or changes in the future (by root on one) will fail on the other.

**Comment by AudriusButkevicius** [comment] 2015-04-27 18:49
Our usual policy is to either fully succeed, or to fully fail, hence keeping the file with wrong permissions is not really an option. You can enable ignore permissions if you wish.

**Comment by jstnlth** [comment] 2015-04-27 19:27
I think we are agreeing, but not communicating.  Currently, you do NOT fully succeed.  This situation was an initial file share.  It copied the file over, then set the owner to root, and then failed to set the chmod permissions.  It the order was changed to copy file, then set chmod permissions, then set owner (as the last attribute to be changed), then I wouldn't expect the "operation not permitted" error, and everything would match the source.

**Comment by AudriusButkevicius** [comment] 2015-04-27 19:38
We don't sync uid/gid so we could not have changed the owner.

**Comment by Zillode** [comment] 2015-04-27 19:55
@jstnlth it is also impossible for syncthing and other processes to chown files to root (if they are not running as root that is).

**Comment by calmh** [comment] 2015-05-07 19:47
There is some problem here, but it sounds like it's related to ownership or permissions on the destination. Closing, but please yell and I'll reopen if this is reproducible so we can look at it.

**Closed by calmh** 2015-05-07 19:47 UTC

**Comment by koppor** [comment] 2016-12-29 09:01
Can the output of "isn't making progress" more verbose?

I have following output and I don't know, what I should do here. 

```
[4QJNC] 09:56:35 INFO: syncthing v0.14.17 "Dysprosium Dragonfly" (go1.7.4 windows-amd64) jenkins@build.syncthing.net 2016-12-27 10:29:12 UTC
[4QJNC] 09:56:35 INFO: My ID: 4QJNCSX
[4QJNC] 09:56:36 INFO: Single thread hash performance is 259 MB/s using minio/sha256-simd (178 MB/s using crypto/sha256).
[4QJNC] 09:56:44 INFO: Ready to synchronize BTSync (readwrite)
[4QJNC] 09:56:44 INFO: TCP listener ([::]:22000) starting
[4QJNC] 09:56:44 INFO: Device PEIZ2ZO is "aslap3" at [dynamic]
[4QJNC] 09:56:44 INFO: Device WOFXBKK is "MASSNA" at [tcp://massana.informatik.uni-stuttgart.de]
[4QJNC] 09:56:44 INFO: Device 4QJNCSX is "ROEMERBERG" at [dynamic]
[4QJNC] 09:56:44 INFO: Starting usage reporting
[4QJNC] 09:56:44 INFO: GUI and API listening on 127.0.0.1:8384
[4QJNC] 09:56:44 INFO: Access the GUI via the following URL: http://localhost:8384/
[4QJNC] 09:57:14 INFO: Completed initial scan (rw) of BTSync
[4QJNC] 09:57:19 INFO: Folder "BTSync" isn't making progress. Pausing puller for 1m0s.
[4QJNC] 09:57:37 INFO: Established secure connection to PEIZ2ZO at 129.69.214.58:22000-141.58.28.113:49867 (tcp-server) (TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384)
[4QJNC] 09:57:37 INFO: Device PEIZ2ZO client is "syncthing v0.14.17" named "aslap3"
[4QJNC] 09:57:41 INFO: Folder "BTSync" isn't making progress. Pausing puller for 1m0s.
[4QJNC] 09:58:44 INFO: Folder "BTSync" isn't making progress. Pausing puller for 1m0s.
```

**Comment by AudriusButkevicius** [comment] 2016-12-29 09:50
There is already an issue tracking the problem you are seeing, as well as addressing lack of logs.

**Comment by AudriusButkevicius** [comment] 2016-12-29 09:51
You should however see failed items in the web UI.

**Comment by koppor** [comment] 2016-12-29 12:15
Sorry, I didn't find the issue with Google and [searching for open issues containing the text "isn't making progress"](https://github.com/syncthing/syncthing/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aopen%20%22isn%27t%20making%20progress%22%20). I could not find any [label](https://github.com/syncthing/syncthing/labels) containing "GUI". https://github.com/syncthing/syncthing/issues/385 does not contain something about error reports.

The concrete issue doesn't seem to be https://github.com/syncthing/syncthing/issues/1355

Sorry, I cannot find the issues you are referring to.  Maybe you can point me to the issues? I am very willing to follow up there and to test things.

I am using SyncTrayzor and the UI is as follows

![grabbed_20161229-131346](https://cloud.githubusercontent.com/assets/1366654/21543653/bb7a2c38-cdc8-11e6-9432-2ab007e5de9a.png)

**Comment by canton7** [comment] 2016-12-29 12:44
Expand the BTSync folder, then click on Failed Items

**Comment by AudriusButkevicius** [comment] 2016-12-29 12:45
The issue is #3839

**Comment by calmh** [comment] 2017-01-01 20:03
Locking to avoid further musings on a two year old unrelated issue
