### ISSUE TITLE
When adding ignores at folder creation time, .stignore file can't be created

### ISSUE THREAD

**Issue by bugith** [syncthing/syncthing#4094] opened 2017-04-13 13:23 UTC
When creating a folder share, specified Ignore Patterns won't save unless the _path/.stignore_ yet exists.
Since #3608 the Ignore Patterns button logic is OK (grayed when no path is given), but if it is not possible to create the full path to .stignore on create, then the button should not even show (or remain grayed) as long as the folder share is not created (then needing to re-open/edit the folder share to set Ignores, allowing to drop synching selected Ignores... and go to the directory tree to do some clean-up)

**Comment by calmh** [comment] 2017-04-13 13:28
Confirmed. When adding a new folder, filling out a path, clicking "edit ignores", clicking save, clicking save, the following happens:

![img_0103](https://cloud.githubusercontent.com/assets/125426/25006583/c35207e0-205d-11e7-8ef1-1c411e4812ca.PNG)

This should be fixed before 0.14.27 release

**Comment by imsodin** [comment] 2017-04-13 13:46
Also a big thanks from me for uncovering this!

The problem is not that .stignore is not existing, but that the directory does not yet exist. If you create a new folder in a directory without .stignore everything works fine.
The error happens here:
https://github.com/syncthing/syncthing/blob/master/lib/osutil/atomic.go#L40

Two possible solutions:
When a folder is added check whether the folder exists and create it no matter whether it is paused or not.
Check whether the folder exists in `ignore.WriteIgnore` and create it if it doesn't.

@calmh Which do you prefer?

**Comment by calmh** [comment] 2017-04-13 13:48
> On 13 Apr 2017, at 15:46, Simon Frei <notifications@github.com> wrote:
> 
> When a folder is added check whether the folder exists and create it no matter whether it is paused or not.

This sounds reasonable to me.

**Comment by imsodin** [comment] 2017-04-13 14:06
I am struggling to find where/when a non-existing root directory is created when a new (unpaused) folder is added in a non-existing directory.

**Comment by calmh** [comment] 2017-04-13 15:04
Eh... Somewhere called from startfolder or the health check would be my guess

**Comment by imsodin** [comment] 2017-04-13 15:10
The whole thing is a bit convoluted and maybe involves the folder marker. The directory is [created only if there is no existing index](https://github.com/syncthing/syncthing/blob/master/lib/model/model.go#L242), I don't really understand why and what happens if there is already an index (possibly a missing folder marker error?).
If I would just create the directory in [CommitConfiguration](https://github.com/syncthing/syncthing/blob/master/lib/model/model.go#L2381) instead this mechanism (whatever it is for) would be circumvented.
When adding the folder the error from the failing ignore due to the missing directory [is ignored](https://github.com/syncthing/syncthing/blob/master/lib/model/model.go#L328).

So while it would be easy to just create the directory, with my limited knowledge of the mechanisms during folder creation, I am unsure about what effects this might have and how to do it most consistently.

**Comment by calmh** [comment] 2017-04-13 15:18
It certainly is a convoluted. The index thing is about detecting the difference between the folder not existing because it's entirely new and the folder being suddenly missing (which will indeed cause the folder marker missing thing).

We could do it when committing the configuration instead, probably. I don't think that mechanism existed or at least was built out when the current system was invented. We're old enough to have legacy code now... D:

Needs to still work when someone shuts down Syncthing and adds a folder to the config, but that's just a specific check at startup instead.

**Comment by imsodin** [comment] 2017-04-13 15:25
So it should be fine to move only the directory creation from `startFolderLocked` to `CommitConfiguration`, as the folder marker will still be missing. Thus the folder marker missing error will still happen and everything is safe and backwards compatible (hopefully).

**Comment by AudriusButkevicius** [comment] 2017-04-13 17:04
The only problem will be with folders added via modifying config.xml.

**Comment by imsodin** [comment] 2017-04-13 17:22
That could be handled by only doing it for paused folders in `CommitConfiguration` and leaving `startFolderLocked` as is. But then this could still be a problem when there is a [paused folder in config.xml](https://github.com/syncthing/syncthing/blob/master/cmd/syncthing/main.go#L817) to which the path does not exist (can that even happen?). And maybe there is more places to be looked after I didn't see yet. Once again I feel this would be much easier/cleaner to handle if a paused folder would be added to the model, just not started.

**Comment by AudriusButkevicius** [comment] 2017-04-13 17:31
We could just force commit configuration upon startup precreating the paused ones and removing logic from startFolderLocked?

**Comment by AudriusButkevicius** [comment] 2017-04-13 17:31
I am fine to keep the folders in the model, but we'd have to add a bunch of if conditions in a lot of places to make that happen.

**Comment by imsodin** [comment] 2017-04-13 18:01
> We could just force commit configuration upon startup precreating the paused ones and removing logic from startFolderLocked?

Something like this?
https://github.com/syncthing/syncthing/pull/4095/commits/7a2c1ad5cc3fbecb06290551acd4f442697fa591

> I am fine to keep the folders in the model, but we'd have to add a bunch of if conditions in a lot of places to make that happen.

I just always see the potential benefits, but don't know the rest of the code good enough to see the caveats :)

**Comment by bugith** [comment] 2017-04-18 08:23
As of 27rc4, the Ignore Patterns button is no more in GUI on Add Folder.

**Comment by calmh** [comment] 2017-04-18 11:31
Correct. I pulled this out of the 0.14.27 release to give us time to sort out the issues. It should reappear in 0.14.28.

**Closed** 2017-04-23 23:51 UTC
Labels: blocker, bug
