### ISSUE TITLE
Shared Folder switches to "receive encrypted" on its own, making sync impossible

### ISSUE THREAD

**Issue by csarn** [syncthing/syncthing#8858] opened 2023-04-08 21:02 UTC
### Does your log mention database corruption?
No.

### Include required information

Please be sure to include at least:

 - which version of Syncthing and what operating system you are using
There are 4 machines involved, I'm not sure if the last one is relevant.

**Machine A**:
v1.23.4, Windows (64-bit)

**Machine B**:
v1.18.0-ds1, Linux (64-bit ARM)

**Machine C**:
Linux AMD64, docker: syncthing/syncthing:1.18

**Machine D** (possibly irrelevant):
v1.23.2, Linux (64-bit Intel/AMD)

 - what happened:
 
Likely Relevant Setup:
Machine B has C configured as "untrusted". C has B as auto-accept.

I added a folder to B, shared with A, C, D. C is the only encrypted one.
C auto-accepts. I manually accepted on A and D.
Existing files are synced correctly.
Some time later, less than 1 hour, the connection between A and B gets disconnected, and can't be established again because "remote expects to exchange encrypted data, but is configured for plain data" (log excerpt from A).
B is now configured to treat A as untrusted. according to the web interface, it would use the same encryption password for A as it has configured for C.
 
This seems reproducible on my setup, as I deleted those folders on all devices and re-created it (getting a different folder ID), and the same thing happened again.

 - what you expected to happen instead, and

I would expect the ecryption settings to never change except when I explicitly do so via the web interface. Especially when that completely breaks syncing.

 - any steps to reproduce the problem.
Due to the setup mentioned above, I assume it would not be too easy to recreate the problem.

If you have any hints what I could try to fix this, I'd appreciate it.
I can also try recreate the problem and collect logs from all involved machines.

**Comment by calmh** [comment] 2023-04-09 06:34
I tried to reproduce this in a similar three-device setup, but couldn't. Is this something that happened to you once and you think the steps above are roughly what happened, or something you can reproduce? If you can reproduce it, logs from all devices would be very valuable. I can't really see a mechanism for the described error to occur...

(I did find another unrelated problem with auto-accepted shares, however...)

**Comment by er-pa** [comment] 2023-04-09 16:11
It may be worth a shot updating the more out-dated instances to a recent version. A significant version-gap can always lead to unpredictable or unexpected behaviour.

**Comment by calmh** [comment] 2023-04-09 17:45
There's also some confusion in the description, the subject of the issue is that some device switches to receive-encrypted, but the description is that some other device switches to having untrusted toggled and a password set, which is the opposite.

**Comment by csarn** [comment] 2023-04-09 18:39
> There's also some confusion in the description, the subject of the issue is that some device switches to receive-encrypted, but the description is that some other device switches to having untrusted toggled and a password set, which is the opposite.

You're right, but I actually saw both... One (I think the "recieve-encrypted" one) was my first encounter of this issue, and after deleting and re-creating the share (new folder ID) I go the other one.

I'll try updating all involved versions and see if the problem remains.
If version mismatches could lead to trouble, what is the best way of managing a "fleet" of synced devices, like android, something debian based (where 1.18 is in the repo), windows etc.? Just not using the debian-provided packages?

**Comment by calmh** [comment] 2023-04-09 18:52
Version mismatches wouldn't cause this, I have no idea what would.

**Comment by acolomb** [comment] 2023-04-10 06:04
I've observed sometimes that my password manager's browser extension tries to fill in the password field automatically for the encryption password in the sharing dialog. Do you have anything similar active in your browser?

**Comment by csarn** [comment] 2023-04-10 10:48
Good hint, but no, I have no saved passwords for the syncthing browser interface.

**Comment by calmh** [comment] 2023-11-07 00:49
Closing as I see no mechanism for this to occur, nor any way to troubleshoot it.

**Closed by calmh** 2023-11-07 00:49 UTC
Labels: bug, waiting-for-info
