### ISSUE TITLE
Wrong display behavior with long filenames in sync modal

### ISSUE THREAD

**Issue by avignat** [syncthing/syncthing#5473] opened 2019-01-20 21:45 UTC
![6bf71367-aa78-4030-9c49-68acb5df3426 png](https://user-images.githubusercontent.com/1545450/51445415-d1e48580-1d04-11e9-9d2f-29b5e0140429.jpg)

Pattern: `AAA\A\A\AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA\AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA`

### Version Information

Syncthing Version: v1.0.0
OS Version: Windows 10
Browser Version: Firefox 64.0.2 (64bits)

**Comment by sisu4syncthing** [comment] 2019-02-01 23:11
I had this too some times, so I can confirm.

Syncthing Version: v1.0.0
OS Version: Windows 7 64Bit / Mac OS 10.12.6 
Browser Version: Waterfox 56.2.6 (64-bit) (Win+Mac) and Safari Version 12.0.3 (12606.4.5.3.1)

I open the WebGUI with https://ip:port/?lang=en

**Comment by tomasz1986** [comment] 2020-05-04 23:22
I did not notice that https://github.com/syncthing/syncthing/issues/6268 was marked as a duplicate of this issue. I think that we can close this one too, following https://github.com/syncthing/syncthing/commit/f560e8c850e177b295509248dc49b09eb9bd5888.

**Closed** 2020-05-04 23:41 UTC
