### ISSUE TITLE
Folder Rescan upon start up despite setting: no folder watching and long rescan schedule

### ISSUE THREAD

**Issue by Borbarad13** [syncthing/syncthing#8358] opened 2022-05-23 12:00 UTC
Version:  v1.20.1, Windows (64-bit Intel/AMD)

What happened:
When I start my PC and start Synching it seems to always rescan all folders upon start up. The folders have:
 * "Watch for Changes" disabled
 * A Full Scan interval of 600000 (~Weekly)

What I expected to happen instead:
There should be no rescan upon startup. Unless I have overseen any config, it speaks against what the user has defined in the config. My use case is that I have data that changes somewhat frequently and I would like to control how often these changes are detected to avoid that syncs happen too often.

**Comment by tomasz1986** [comment] 2022-05-23 12:07
Duplicate of https://github.com/syncthing/syncthing/issues/5353.

**Closed** 2022-05-23 12:34 UTC
Labels: bug, needs-triage
