### ISSUE TITLE
Old device removed from introducer isn't removable from other devices

### ISSUE THREAD

**Issue by Tstassin** [syncthing/syncthing#5426] opened 2019-01-03 17:45 UTC
As explained in [this forum post](https://forum.syncthing.net/t/unable-to-remove-device-that-has-been-removed-from-introducer/12638)

OLD_DEVICE has been introduced to REMOTE_DEVICE in the past by INTRODUCER_DEVICE
OLD_DEVICE has since been removed from INTRODUCER_DEVICE
REMOTE_DEVICE can't remove OLD_DEVICE because "this device will be reintroduced by INTRODUCER_DEVICE"

Syncthing Version: v1.0.0 (previously same bug on 0.14.54)
OS Version: Ubuntu 16.04
Browser Version: Firefox latest / Safari latest

![capture d ecran 2019-01-03 a 17 38 21](https://user-images.githubusercontent.com/10681663/50652682-90737c80-0f87-11e9-8190-00419b30166b.png)

![capture d ecran 2019-01-03 a 17 40 40](https://user-images.githubusercontent.com/10681663/50652704-9f5a2f00-0f87-11e9-8381-89c20327b1d6.png)

**Comment by AudriusButkevicius** [comment] 2019-01-09 23:10
Is remote device no longer an introducer? Or SkipIntroductionRemovals is enabled somewhere?

**Comment by AudriusButkevicius** [comment] 2019-01-09 23:11
Also, did the devices reconnect since introducer removed the old device?

**Comment by Tstassin** [comment] 2019-01-12 22:20
> Is remote device no longer an introducer? Or SkipIntroductionRemovals is enabled somewhere?

Remote device is not an introducer. I never used the advanced parameter 'skip introducter removals".

> Also, did the devices reconnect since introducer removed the old device?

Yes, they are always connected.

**Comment by AudriusButkevicius** [comment] 2019-01-12 22:47
Well the web gui thinks it's an introducer. Can you provide longs and screenshots of the remote device settings on local device (the one that you can't remove the device from).

**Comment by Wurzelmann** [comment] 2019-08-08 11:35
This seems to be fixed in Syncthing v1.2.0 (installed on Arch here), but the bug is still present in vv1.0.0-ds1 (Debian Buster), so maybe this issue can be closed?

**Comment by AudriusButkevicius** [comment] 2019-08-08 12:22
I don't think there was anything related to this that could have fixed it.

**Comment by nshtg** [comment] 2020-01-29 08:21
The bug is still occuring in v1.3.3 for me. @AudriusButkevicius

**Comment by tomasz1986** [comment] 2020-02-19 00:27
I have experienced the same issue.

![image](https://user-images.githubusercontent.com/5626656/74789840-39e71000-52f9-11ea-9974-622d49b72eee.png)

This happens on all my devices, where the same device was originally set (and still is) as an introducer. It is impossible to remove any devices introduced by it, even though they have been long removed from the introducer itself.

The workaround is to temporarily set the original introducer to non-introducer, remove the problematic devices, and then set it to introducer again.

**Comment by AudriusButkevicius** [comment] 2020-02-19 06:31
Yeah, seems like a bug.

**Comment by ErikGulliksen** [comment] 2020-06-18 12:56
This still happens for me in 1.6.1.
I have a device removed from the introducer which I now can't remove from other devices.

**Comment by calmh** [comment] 2020-06-18 16:00
I try to ignore these things, but since this is the multiple-th time today and multiple times in this same thread: open issues in the tracker are *known issues*. We know it still happens in the latest release, that's why the issue is here and is open. So there is no need to reiterate that fact. A better contribution is a patch to fix it.

**Comment by hiqua** [comment] 2020-12-20 17:25
Suggestion:

* To fix this issue:
  * don't disable the "Remove" button if the device has been introduced.
  * adapt the tooltip to "{{ willBeReintroducedBy }} might reintroduce this device."

* In a new feature request issue, suggest:
  * to disable the removal button iff the introducer:
    * still has the device &&
    * is currently connected

AFAIU, disabling the "Remove" is a useful UI feature if it works. If it doesn't, like presently, it does more harm than good.

**Closed** 2021-01-15 19:46 UTC
Labels: bug
