### ISSUE TITLE
GUI listen configuration doesn't recognize "localhost" as 127.0.0.1

### ISSUE THREAD

**Issue by dgnuff** [syncthing/syncthing#6092] opened 2019-10-18 05:45 UTC
Steps to reproduce:

1.  Install SyncTrayzor and Syncthing.
2.  In Syncthing's settings ensure there is no password set for GUI access.
2.  In SyncTrayzor's settings, set the GUI listen address to "localhost:8384"
3.  Start SyncTrayzor and have it start Syncthing.

Expected: Syncthing recognizes "localhost" as a synonym for 127.0.0.1 and does not issue a security warning.

Observed: SyncThing issues the "The Syncthing admin interface is configured to allow remote access without a password." warning.

Reproduction: 100%

Workaround: Change the GUI listen address in SyncTrayzor's settings to 127.0.0.1:8384

Syncthing Version: v1.3.0
SyncTrayzor Version: 1.1.23
OS Version: Windows 10 Home - 1903
Browser Version: Whatever browser is built into SyncTrayzor

**Comment by calmh** [comment] 2019-10-18 05:50
Duplicate of #6049

**Closed by calmh** 2019-10-18 05:50 UTC
