### ISSUE TITLE
Sometimes .tmp files are left on device after successful sync

### ISSUE THREAD

**Issue by ssergiienko** [syncthing/syncthing#2681] opened 2016-01-10 11:33 UTC
My case: i rename music files on Desktop PC to match some new pattern. After long sync with android device i have notice that on android left few .tmp files. This files is not empty, they just a copy of files that exists on device after sync(files with new name pattern).

Not sure, about reason but guess this may happens due this situations:
1) Android has sleep during sync few times and maybe this somehow affect clean up process.
2) Files renamed right during sync|index progress.

On desktop v0.12.11
On android v0.12.6

**Comment by AudriusButkevicius** [comment] 2016-01-10 11:46
They get cleaned up after 24 hours by dafault, you can adjust that to be less than 24 hours in advanced config.

**Comment by AudriusButkevicius** [comment] 2016-01-10 11:49
The reason I am closing this is because we rename the temp file to its final desfinatiom once its synced, so the fact that it's there means it can't be an exact copy. You could run md5sum to verify that. Alternatively, it could be some android bug, but you need to provide better steps to reproduce this, as I can't seem to repro this.

Also, can you provide the name of the temp file?

**Comment by AudriusButkevicius** [comment] 2016-01-10 11:50
I guess I'll reopen intil you respond.

**Comment by ssergiienko** [comment] 2016-01-10 12:07
About `it can't be an exact copy`:
- I think they are exact copy because the only thing i was doing on my Desktop was os.rename in Python script on around ~1200 files. But only 5-6 .tmp  files are left.
Also, all this files was synced BEFORE i rename them on Desktop.
I didn't run md5sum on android to check that some-fname-with-syncthing-prefix.id.4323423436.mp3.tmp === fname.id.4323423436.mp3, but i ckecked them by file size and it was equal byte to byte. If i reproduce this case again i will try to calc hashsum.

During sync after rename, my music folder has grow from ~16GB to ~24GB. Is cleanup process called in case of ended disk space right during sync? Because there was lots of such files, and they gone only at the end of process, except 5-6.

**Comment by AudriusButkevicius** [comment] 2016-01-10 12:23
No, the cleanup happens only when the files are of certain age. 

We do truncate temp files to their final size so they look like they are the same size, but are just full of 0s.

Also, syncthing-prefix.id is not very useful as on different platforms the prefix is different, so I'd rather you provide a real name and not some crafted example.

I am closing this as I think what you are seeing is just a truncated themp file, where the content of it is actually different. This is expected.

**Closed by AudriusButkevicius** 2016-01-10 12:23 UTC

**Comment by ssergiienko** [comment] 2016-01-10 12:30
`not some crafted example`:
- I'm sorry, it's just all that i can remember because i delete this tmp files a few hours ago.
Thanks for help! I will reopen this issue when i found some method to reproduce this bug and get hash of files and they exact names.

**Comment by AudriusButkevicius** [comment] 2016-01-10 12:38
As I said in my last sentence, I think you are just observing normal behaviour during operation.
If a a file gets modified, we allocate a temp file to reassemble the modifications. If the file we were reassembling disappears, we keep the temp file around for N hours. Now due to a recent change, we pre-truncate all files to their final size, hence why it looks to you like the files are identical, though in reality they are not.

**Comment by ssergiienko** [comment] 2016-01-10 13:10
Ok, thanks for explain, but to be sure i reproduce this once again and leave it here. Just now on 2GB music folder with code like this:
```
Python 3.5.1 (default, Dec  7 2015, 12:58:09) 
[GCC 5.2.0] on linux
>>> import os
>>> dir = '/home/user/Android/sdcard0/Music/test/'
>>> for i in os.listdir(dir):
...  os.rename(i, i + '.zzzz')
# At 95% sync i rename all files back:
>>> for i in os.listdir(dir):
...  os.rename(i, i[:-5])
```
After full sync complete i have on android(real filenames):
Both `.syncthing.Britney Spears - Gimm more.mp3.tmp`  and `Britney Spears - Gimm more.mp3`. As you said, they have different hashes. I will live this file for some time to see if it will be deleted in future.

If this is a normal behaviour then it's not obvious :) Especially if know that only modification was made to file is rename. Also if we have not much space(sdcard) that files can lead to disk space problems.

**Comment by AudriusButkevicius** [comment] 2016-01-10 13:16
Renames do not generate temp files.

**Comment by ssergiienko** [comment] 2016-01-10 13:21
@AudriusButkevicius As i reproduce - they are :) And please, read my sentence about file `Pantera - Planet Caravan (Black Sabath Cover).mp3.zzzz`  (i updated my comment few seconds before your answer)

**Comment by ssergiienko** [comment] 2016-01-10 13:41
`It could be potentially because you rename them twice before it gets in sync, hence why it creates the temp files.`
 - No, i noticed that .tmp files created always, even at first rename. In GUI process this can be seen like separate operations `local copy from original file` and `delete old file`

`the files are sparse, so I think they don't actually take up space`
 - I open this .tmp file with audio player and it can play it, at least 1-2min starting part of it.

**Comment by AudriusButkevicius** [comment] 2016-01-10 13:50
If it creates tmp files then the content is not the same. Potentially you changed some MP3 tags or something which makes the content actually different.

That's even more likely if you can play the first few minutes of the song.

**Comment by ssergiienko** [comment] 2016-01-10 15:31
Looks like your guess is correct, bug is not reproduced if it's not MP3... But right now i can't reproduce it with MP3 too)
Thanks for help, will assume that this all due android media indexer that periodically doing his bad things.
