### ISSUE TITLE
[0.11.0] Error creating discovery client  udp6://announce-v6.syncthing.net:22026 Unsupported scheme:

### ISSUE THREAD

**Issue by marcelpaulo** [syncthing/syncthing#1750] opened 2015-05-02 08:55 UTC
Running ST **0.11.0** on Xubuntu 15.04

When ST starts, this message is output:
```
Error creating discovery client  udp6://announce-v6.syncthing.net:22026 Unsupported scheme:
```

It doesn't seem to have any impact whatsoever, since ST is working fine.

I started it with `STTRACE=discover`: here's the [log](http://bpaste.net/show/b20318ecd272), and my [config.xml](http://bpaste.net/show/b4d41f7feecc).

**Comment by wweich** [comment] 2015-05-02 09:26
Do you have IPv6 configured for that machine? It seems not.
If it's not configured, you can remove that entry from the global discovery server list.

**Comment by marcelpaulo** [comment] 2015-05-02 09:29
It's configured:
```
paulo@monk:~$ ifconfig eth0
eth0      Link encap:Ethernet  HWaddr 18:03:73:57:5e:e7  
          inet addr:192.168.25.3  Bcast:192.168.25.255  Mask:255.255.255.0
          inet6 addr: fe80::1a03:73ff:fe57:5ee7/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:2551723 errors:0 dropped:0 overruns:0 frame:0
          TX packets:2768348 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000 
          RX bytes:1716427840 (1.7 GB)  TX bytes:2454407193 (2.4 GB)
```

Most local connections between my laptop and my Android phone are done over IPv6.

**Comment by calmh** [comment] 2015-05-02 13:14
You don't have any global IPv6 connectivity. The error is reasonable, but can be ignored in your case.

**Comment by marcelpaulo** [comment] 2015-05-02 13:20
Oh, I see, it does make sense. I'm gonna remove that address from the announce list. 

Thanks for the explanation, @calmh.

**Comment by chucic** [comment] 2015-05-12 13:56
I'm getting

    [SUXRZ] 15:45:58 INFO: Error creating discovery client  Unsupported scheme:
twice, once after

    [SUXRZ] 15:45:58 INFO: Starting global discovery announcements
and after

    [SUXRZ] 15:46:10 INFO: New UPnP port mapping: external port 9558 to local port 22000.
I'm ignoring it as suggested, but it's missing

    udp6://announce-v6.syncthing.net:22026
although it's in config. Is this expected?

Windows 7 64bit, syncthing 0.11.3

**Comment by wweich** [comment] 2015-05-12 15:02
Getting it twice is expected, because the "descovery client" is restarted after setting UPnP.

You probably get the error because your internet connection does not support IPv6.

**Comment by chucic** [comment] 2015-05-12 15:33
Thanks for info about "twice".

Yes, I don't have IPv6. But my error says

    [SUXRZ] 15:45:58 INFO: Error creating discovery client  Unsupported scheme:
instead of

    [SUXRZ] 15:45:58 INFO: Error creating discovery client udp6://announce-v6.syncthing.net:22026 Unsupported scheme:
Error with ````udp6://announce-v6.syncthing.net:22026```` says what is wrong and user then realise, that he has no IPv6 and ignore this, but error without address does not point to core of problem. From my perspective it's not by design, but I may be wrong, hence that question.

**Comment by calmh** [comment] 2015-05-12 19:58
I tried to have this open, because the error sucks and should be fixed/clarified. We'll try again. :)

**Comment by Zillode** [comment] 2015-05-16 20:06
as a sidenote: I think upnp errors should not be presented in the notification window because it unnecessary alarms new users of minor technical problems. We should improve important notifications, e.g. when files cannot be created (https://github.com/syncthing/syncthing/issues/1437) and reduce technical logging (such as this one).

**Comment by calmh** [comment] 2015-05-19 16:15
Yes. Warning level should be reserved for serious stuff, that is both important and actionable by the user somehow...

**Comment by chungy** [comment] 2015-06-05 03:26
I get this same message (Unsupported scheme), and I do actually have a global IPv6 address.

**Comment by calmh** [comment] 2015-06-07 11:09
"Unsupported scheme" is a config error. What is the actual discovery server URL? It should start with either `udp4://` or `udp6://`.

**Comment by chungy** [comment] 2015-06-07 11:28
It should have been the default, but I just peeked into the config.xml and it looks like a leading space was causing the issue; I removed it and it seems to work now.

**Closed** 2015-06-25 15:50 UTC
Labels: easy, enhancement
