### ISSUE TITLE
Syncthing and external drive

### ISSUE THREAD

**Issue by imisanthrope** [syncthing/syncthing#1997] opened 2015-06-24 12:07 UTC
Hi!
Noticed strange behavior when unmount/mount external HDD:
- Folder on a node B synchronized with folder on external HDD on node A
- external HDD on node A have been unmounted
- Folder on node B was changed (for example, I delete 1 file)
- mount HDD again to node A
- deleted file appears on node B again
So, seems like when external HDD mounted again, all files on it counted as new and are being synced back to other nodes, even if they were modified/deleted previously.
I noticed, that when I delete file on node B during external drive was disconnected from node A, Syncthing on node A get that (I see "delete file <..>" in folder status on node A), but when external HDD mounted back, that change doesn't being applied.

**Comment by AudriusButkevicius** [comment] 2015-06-24 13:49
```
 I noticed, that when I delete file on node B during external drive was disconnected from node A, Syncthing on node A get that (I see "delete file <..>" in folder status on node A), but when external HDD mounted back, that change doesn't being applied.
```
Sorry, I don't understand this bit.

**Comment by imisanthrope** [comment] 2015-06-24 14:05
Sorry for my grammar(
I'll try to describe it more detailed:
1. I disconnect external HDD on node A
2. I delete a file (named, for example, 'TEST') on node B
3. Web GUI on node A says that "Last File Received" is "Delete TEST" (thats why I decided, that Syncthing tracks modifications even if folder is missing)
4. I connect external HDD back to node A
5. File TEST present on that external HDD and Syncthing syncs it back to node B, although it was deleted from node B

As I see, Syncthing guided by logic that:
- event 1 -> folder disappeared
- event 2 -> file was deleted
- event 3 -> folder appeared back -> file appeared back -> that's a new file, and event 3 was after event 2, so lets sync it with others.

But that's not right behavior. I often use laptop with external HDD, which I connect only when needed and with Syncthing I cant keep files on that HDD because any modifications that will be made on other nodes while HDD is disconnected will be discarded when I connect HDD. 
So I'm stucked on half-way migrating from BtSync to Syncthing because of this problem. BtSync solves such case well, keeping all modifications happened while HDD was disconnected and applying them when it connected back, and files were deleted on other nodes also are being deleted on HDD.

In fact, problem is only in the moment of connecting HDD: Syncthing should not think that files in suddenly re-appeared folder are new one and perform with them like they always were there waiting for all modifications were made on other nodes.

**Comment by dcarosone** [comment] 2015-06-24 19:47
What operating system and file system on the external drive?

(I wonder what mtime the OS is presenting on remount)

**Comment by imisanthrope** [comment] 2015-06-24 20:02
Latest OS X with journaled HFS+ on both Nodes, including external HDD.

**Comment by AudriusButkevicius** [comment] 2015-06-24 20:46
Right, this is a bug, we don't check folder health when pulling.

**Comment by imisanthrope** [comment] 2015-06-25 07:40
Glad to hear that it's a bug. Because since it's a bug, there is a chance it will be fixed :)
Thanks a lot for your attention to my problem.

**Comment by imisanthrope** [comment] 2015-06-29 07:42
I performed test with FAT32 external HDD (internal FS is HFS+), same results:
- add folder on external HDD to Syncthing
- sync it with another node
- remove external HDD
- delete some files on another node
- attach external HDD back
- deleted files appear again

Seems like such behavior is independent from external drive filesystem.

**Comment by Zillode** [comment] 2015-07-29 19:49
I tried reproducing this but I think there is some info missing. Does it work with one file? Is it big? Do you modify or create a file (if you create one, nodes need to be synced because node b can only remove the file if it has the data). 
```
=== RUN TestRemountAfterSync
2015/07/29 19:45:34 Cleaning...
2015/07/29 19:45:34 Generating files...
2015/07/29 19:45:35 Starting instance 1...
2015/07/29 19:45:37 Starting instance 2...
2015/07/29 19:45:45 Verifying...
2015/07/29 19:45:45 'Unmounting' folder...
2015/07/29 19:45:45 Scan changes...
2015/07/29 19:45:46 'Remounting' folder...
2015/07/29 19:45:46 Syncing...
--- PASS: TestRemountAfterSync (20.81s)
```

**Comment by AudriusButkevicius** [comment] 2015-07-29 19:52
ping @calmh

**Comment by imisanthrope** [comment] 2015-07-31 10:52
@Zillode 
Yes, I tried with one file. Not big, about 4MB. I'm not creating or modifying it, I delete it from node A, while synced folder on node B is "missing" (external drive is disconnected). When I connect drive back, deleted file appear again => node B thinks that it is a new file and sends it back to node A.

**Comment by Zillode** [comment] 2015-07-31 21:33
@imisanthrope 
I believe this is exactly represented by my unit test. Is there a node C in your configuration?

**Comment by imisanthrope** [comment] 2015-08-03 12:42
@Zillode 
Yes, I have node C, but this folder is not synced with C.
Today I represented this bug without external drive, just by moving folder on one node and putting it back.
I'll try to do same with 3 nodes.

**Comment by imisanthrope** [comment] 2015-08-04 07:54
No, same thing with 3 nodes.
I put 4 items to test folder, moved folder on node A (and it reports that folder is missing), then delete 1 file on node B.
Here is node A state: 
![2015-08-04 10 50 23](https://cloud.githubusercontent.com/assets/6872959/9055800/c4e630da-3a96-11e5-9bf3-6c6b65fc7ca9.png)
Here is node B state (node C is the same):
![2015-08-04 10 50 14](https://cloud.githubusercontent.com/assets/6872959/9055846/110675e2-3a97-11e5-984c-6728cea4b120.png)
But when I move folder on node A back, all nodes report state with 4 files.

**Comment by AudriusButkevicius** [comment] 2015-09-12 22:20
I think this specific case is now fixed.

**Closed by AudriusButkevicius** 2015-09-12 22:20 UTC
Labels: bug

**Comment by imisanthrope** [comment] 2015-09-14 07:33
Yep, now after connecting external HDD back all changes sync properly, deleted files don't sync back. Thanks a lot, now BtSync could be completely replaced by Syncthing.

**Comment by AudriusButkevicius** [comment] 2015-09-14 07:43
That specific commit hasn't been released yet, but the issue requires speific conditions to reproduce.

**Comment by imisanthrope** [comment] 2015-09-14 07:50
Well, I was able to reproduce the bug on all my Macs) But I believe that my issue could be at least platform-specific. Anyway, I'm very happy with Syncthing, it becomes better and better. Now the only thing I miss is OS X tags (Syncthing doesn't sync them), but it's not really necessary.
