### ISSUE TITLE
syncthing/relaysrv:1.14.0 can't start

### ISSUE THREAD

**Issue by xux1217** [syncthing/syncthing#7519] opened 2021-03-23 10:53 UTC
Hi, 

  I use docker to start relaysrv service, 1.13.1 is work normal, but 1.14.0 can't start, I think it's hang by start process.

### Does your log mention database corruption?
the logs is only these:

> 
/var/strelaysrv # /bin/strelaysrv  -pools="" -debug
2021/03/23 10:44:04 main.go:140: strelaysrv v1.14.0 "Fermium Flea" (go1.16 linux-amd64) docker@syncthing.net 2021-02-26 12:21:13 UTC [noupgrade]
2021/03/23 10:44:04 main.go:146: Connection limit 838860
2021/03/23 10:44:04 main.go:185: ID: GXY4ZU6-SWN6TPR-J5VCJXI-H7QOLJI-2XLYKM2-R2IURON-FULDBN5-D7TWNQ5

### Include required information
strelaysrv version is "strelaysrv v1.14.0 "Fermium Flea" (go1.16 linux-amd64) docker@syncthing.net 2021-02-26 12:21:13 UTC [noupgrade]".

image version:  syncthing/relaysrv:1.14.0 

docker version is: 19.03.12

**Comment by calmh** [comment] 2021-03-23 11:16
Duplicate of #7451 

Resolved in 1.15.0 when it's released.

**Comment by calmh** [comment] 2021-03-23 11:17
Though perhaps we should do something about the docker image we provide not being great at the moment...

**Closed by calmh** 2021-03-23 11:17 UTC
Labels: bug, needs-triage

**Comment by xux1217** [comment] 2021-03-23 14:33
ok. 

Thank you for your effort~
