### ISSUE TITLE
Can it synchronize between different folders on one device?

### ISSUE THREAD

**Issue by chenyajunai** [syncthing/syncthing#9011] opened 2023-07-30 12:31 UTC
At present, it can only synchronize between different devices. Can it synchronize between different folders on one device? The system mounts network Cloud storage, and wants to directly back up and synchronize some resources and mount them directly to Cloud storage

**Comment by calmh** [comment] 2023-07-30 12:37
Duplicate of #4721

**Closed by calmh** 2023-07-30 12:37 UTC
Labels: enhancement, needs-triage
