### ISSUE TITLE
Emit "added" instead of "modified" event when a deleted files is created again

### ISSUE THREAD

**Issue by Tstassin** [syncthing/syncthing#5541] opened 2019-02-15 12:56 UTC
[Following this discussion in the forum](https://forum.syncthing.net/t/removed-and-then-re-added-subfolder-triggers-deleted-and-then-modified-events/12857)

When a file or folder is deleted, it is marked as `deleted: true` in the database. An event with `data.action: 'deleted'` is also emitted.

When this file or folder is created again OR a file or folder with same name and path is created, it is marked as `deleted: false` in the database and an event with `data.action: 'modified'` is emitted. This is **counterintuitive**, emitting `data.action: 'added' `seems more consistent.

Unfortunately, I'm not good at coding with Go, I will not be able to make the PR.

![capture d ecran 2019-02-15 a 09 01 13](https://user-images.githubusercontent.com/10681663/52858036-502c2000-3129-11e9-91eb-bbc61d425ced.png)

### Version Information

Syncthing Version: v1.0.1
OS Version: Mac OS X / Ubuntu

**Comment by AudriusButkevicius** [comment] 2019-02-15 18:36
I wouldn't hold your breath on someone fixing this, it's minor and affects pretty much no-one.

**Comment by calmh** [comment] 2019-02-25 20:27
Actually, I change my mind. The current actions are the following:

- `updated` which refers to all updates of content on disk (added, changed, mkdir)
- `metadata` which is a special for metadata only update (permissions or modtime of files)
- `deleted` when we delete something on disk.

You could argue there should be an `added` but there's never been one and there is no provision for one in the code. So I think this is not a bug, just how we intend things to work.

**Comment by calmh** [comment] 2019-02-25 20:29
I change my mind again. :) The above is correct for sync actions, but for local change events we do have `added`, and don't correctly emit it after a delete. That is a bug.

**Comment by imsodin** [comment] 2019-06-17 12:51
The change events are generated by the same function for both local and sync/remote changes at https://github.com/syncthing/syncthing/blob/master/lib/model/folder.go#L811. And at that point we have information on the previous state, i.e. if the file was newly created or modified except for the version vector, which is used for the `added` action type. So AFAIK this is working as expected.

**Comment by Tstassin** [comment] 2019-06-17 14:08
So according to you the following scenario is correct :

Create directory `dir/`

> Event : added

Create file `dir/document.pdf`

> Event : added

Delete file `dir/document.pdf`

> Event : deleted

One year later, for some other purpose, somebody else creates another `dir/document.pdf`, with another content and purpose the event is still :

> Event : modified

I am tracking events, and it seems confusing for me that any "modified" event isn't every time preceded by an "added" event. 
State of a file is much more intuitive to me like this :
added -> (modified) -> deleted -> added
Not like this :
added -> deleted -> modified -> (modified) -> deleted -> modified -> deleted...
In some ways, in this last case, it could work with a new "readded" event instead of modified.

**Comment by imsodin** [comment] 2019-06-17 14:29
Yes, and no. I am saying it's working as intended, but I am not saying that it is intuitively correct. And it would be really hard (read practically impossible) to keep track of the state before until this point, to know whether a file was changed or added. To make this less confusing I'd just scrap the `added` action alltogether (it's anyway flawed, as an unignored file will also be considered `added`, which is wrong).

**Comment by Tstassin** [comment] 2019-06-18 06:01
To me, except the `deleted -> modified` corner case (which happens only when files/folders share same path and name), the `added` event is fundamental in all kind of "watch for changes/additions" scripts and flows. Removing it would break a lot of things, or maybe I'm not using the events API as intented.

**Comment by calmh** [comment] 2019-06-18 09:10
I think that the event names should be in relation to the thing on disk. If it was not present before but now it is, it was “added”. If it was present and was modified, then “modified”. If removed, then “deleted”. Our internal database state (or what happened to the file a year ago) *shouldn't* matter. 

If this isn’t feasible (I didn’t check the code) then we should probable coalesce added and modified into just modified or something else. So that we have two different event types, one where the thing still exists (and maybe was created) and one where it does not. 

Regardless it does not make sense to base it on the existence of not of our database records as these are not something that should be visible to the outside.

**Comment by calmh** [comment] 2020-05-06 06:47
The `added` event is now a goner permanently as per the above commit, so this is a `wontfix` unfortunately.

**Closed by calmh** 2020-05-06 06:47 UTC
Labels: bug
