### ISSUE TITLE
https://discovery-v6.syncthing.net/v2/ has a self-signed (untrusted) SSL cert

### ISSUE THREAD

**Issue by danackerson** [syncthing/syncthing#8425] opened 2022-07-11 10:24 UTC
- which version of Syncthing and what operating system you are using
 -- v1.20.3, Linux (64-bit ARM) "Fermium Flea"

 - what happened,
 -- Device discovery stalls on IPv6:
"global@https://discovery-v6.syncthing.net/v2/: Post "https://discovery-v6.syncthing.net/v2/": dial tcp [2a03:b0c0:0:1010::bb:4001]:443: connect: cannot assign requested address"

 - what you expected to happen instead, and
 -- Successful connection to https://discovery-v6.syncthing.net/v2/

 - any steps to reproduce the problem:
 `curl https://discovery-v6.syncthing.net/v2/`
curl: (60) SSL certificate problem: self-signed certificate
More details here: https://curl.se/docs/sslcerts.html

**Comment by AudriusButkevicius** [comment] 2022-07-11 10:49
I don't think this is true. V6 addresses are for ipv6 connectivity, which looking at the first error, you don't have, and thats ok. The second error (curl one) is probably todo with resolving the cname as ipv4 (somehow?) and us presenting the v4 certificate on the v6 cname?

**Comment by AudriusButkevicius** [comment] 2022-07-11 10:59
The cert is valid as per https://dnschecker.org/ssl-certificate-examination.php

I think your problem is that you don't have ipv6 connectivity.

I have no idea why curl returns what it returns, but if you have no ipv6 connectivity, it should not be able to connect at all.

**Closed by AudriusButkevicius** 2022-07-11 10:59 UTC
Labels: bug, needs-triage

**Comment by danackerson** [comment] 2022-07-11 11:52
if it helps, I'm based in Germany:
```
$ curl -v -6 https://discovery-v6.syncthing.net/v2/
*   Trying 2a03:b0c0:0:1010::bb:4001:443...
* Connected to discovery-v6.syncthing.net (2a03:b0c0:0:1010::bb:4001) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
*  CAfile: /etc/ssl/certs/ca-certificates.crt
*  CApath: /etc/ssl/certs
* TLSv1.0 (OUT), TLS header, Certificate Status (22):
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
* TLSv1.2 (IN), TLS header, Certificate Status (22):
* TLSv1.3 (IN), TLS handshake, Server hello (2):
* TLSv1.2 (IN), TLS header, Certificate Status (22):
* TLSv1.2 (IN), TLS handshake, Certificate (11):
* TLSv1.2 (OUT), TLS header, Unknown (21):
* TLSv1.2 (OUT), TLS alert, unknown CA (560):
* SSL certificate problem: self-signed certificate
* Closing connection 0
curl: (60) SSL certificate problem: self-signed certificate
More details here: https://curl.se/docs/sslcerts.html

curl failed to verify the legitimacy of the server and therefore could not
establish a secure connection to it. To learn more about this situation and
how to fix it, please visit the web page mentioned above.```

I get the same error in the browser even if I `curl -v -6 https://[2400:6180:100:d0::741:a001]` with the alternate IPv6 address. Maybe this is some weird CDN issue (depending on where I'm exiting at)?

**Comment by bt90** [comment] 2022-07-11 12:20
Just tried via openssl and i also get a selfsigned certificate.

```
openssl s_client -showcerts -connect discovery-v6.syncthing.net:443
```

**Comment by wweich** [comment] 2022-07-11 13:02
Don't the discovery servers use self signed certs and expect the clients to send theirs? So it is expected that curl etc. will complain.

**Comment by bt90** [comment] 2022-07-11 13:05
I think so. The problem stated by OP is caused by missing IPv6 connectifity and therefore expected. So everything is working as intended.
