### ISSUE TITLE
Pay closer attention to the fact that files have disappeared.

### ISSUE THREAD

**Issue by dcarosone** [syncthing/syncthing#1838] opened 2015-05-20 02:19 UTC
I have recently been seeing the alert about "folder not making progress, pausing puller..", and on looking at the logs, it is reporting that there is no available source node.  This is despite the fact that the source node is still online.

What appears to be happening:
1. Application on Node A creates a file, often a temporary file for a save-in-progress that will shortly be renamed to the actual destination (as a mechanism to catch disk full or other errors)
2. Syncthing on Node A does a scan and sees the file, updates global state to Node B.
3. Node B starts pulling.
4. Application finishes the save and renames the file.
5. B is still pulling, and getting the errors.
6. A does not notice the file has disappeared, despite apparently trying to read the file.  It will notify B that the pulls cannot be served, but not notify B that the file has gone and it should stop pulling.
7. Problem continues until A does a rescan.

Note that, for Reasons, node A can't run inotify, and has a relatively long rescan interval, which exacerbates the problem.

So essentially, this is a request to have the existence error discovered when trying to serve a puller either implicitly update state (as if it had been discovered in a scan), or trigger a scan because our view of fs contents is clearly out of date.

I'm uncertain whether to call it a bug or an enhancement.

(0.11.5 on linux for both nodes)

**Comment by dcarosone** [comment] 2015-05-20 03:08
Assuming the above is correct, I assume the implementation logic is that in a mesh of nodes with shared global state, some will have the file and others not yet.  In this case, getting ENOENT attempting to open a file in global state to service a pull block request can just be rejected, and the assumption is that we will pull that block ourselves in due course.

However, I think we should also check if the file is in local state, and remove it from there (or just rescan) if we can't open it.

**Comment by calmh** [comment] 2015-05-20 06:34
> I think we should also check if the file is in local state, and remove it from there (or just rescan) if we can't open it.

This sounds reasonable enough.

**Comment by tg2k** [comment] 2015-06-12 20:56
FWIW I am seeing this sort of thing too, or at least something very similar. If I create a new folder, and quickly rename it, or copy a file, and then quickly rename it, it seems to get Syncthing into a bad state. Even if I rescan or restart Syncthing, it keeps hunting for the phantom file or folder and seems to be persistently out of sync with these files.

**Comment by calmh** [comment] 2015-06-12 21:04
That sounds like #1355

**Comment by tg2k** [comment] 2015-06-12 22:27
It may be. In my case I recall this order of events, from last weekend:

Machine A:
1. Created folder named X
2. Moved a bunch of files from another folder (another synced folder where I do image processing) into folder X
3. Renamed files in folder X all at once (attaching the same descriptive prefix onto many image files at a time)
4. Decided folder X was a longer name than needed (now that I had renamed all the images within it) and renamed it to folder Y
5. Some time later I noticed Syncthing is hung up on the now-missing folder X. It is logging messages like this:

[2GV6S] 15:49:31 INFO: Puller (folder "Pictures", file "xxx\\xxx\\xxx\\xxxxxxxxxx\\Descriptive name.NEF"): dst stat dir: GetFileAttributesEx \\?\c:\users\xxx\Pictures\xxx\xxx\xxx\xxxxxxxxxx: The system cannot find the file specified.
[2GV6S] 15:49:31 INFO: Puller: final: GetFileAttributesEx \\?\c:\users\xxx\Pictures\xxx\xxx\xx\xxxxxxxxxxx: The system cannot find the file specified.
[2GV6S] 15:49:31 WARNING: Folder "Pictures" isn't making progress - check logs for possible root cause. Pausing puller for 1m0s.

This is a folder 4 levels beneath a folder that is shared only with Machine B. Where it lists the file names, there are a total of 9 out-of-sync files being reported (at least in the web interface). The web interface lists them like so:

[down arrow] Sync             Filename
...

In case it matters, Machine A is Windows 8.1 x64; Machine B is Windows 7 x64. Both are set to Random File Pull Order, and this folder is synced with a 60s interval.

I have clicked resync on Machine A, and restarted Syncthing multiple times; on Machine B I restarted Syncthing and am not seeing resync button. Machine B now seems to be stuck, actually, reporting either (0%) sync with some other machines, and (-0%) with Machine A. (I treat Machine B as something of a hub, syncing with a number of other machines, but this particular folder is only directly synced with Machine A.) Both machines are running 0.11.8.

...actually, maybe it was just the client code that was stuck. I restarted my browser on Machine B and it seems to be doing better, but it too is stuck, logging messages like this:

[GYYLA] 16:16:32 INFO: Puller (folder "Pictures", dir "xxx\\xxx\\xxx\\xxxxxxxxxx"): delete: <nil>
[GYYLA] 16:16:32 WARNING: Folder "Pictures" isn't making progress - check logs for possible root cause. Pausing puller for 1m0s.

The first message (the "missing" directory name) is logged 11 times in a row. In the UI, Machine B shows only 1 item out of sync: The "missing" directory name, like so:
             * Update              old dir name                    128 B

Does any of that give you an idea what's going wrong?

**Comment by cbhushan** [comment] 2015-06-24 02:02
I think I am facing this issue right now. I did following: 

1. Added a big folder (~90 GB with several folders and files) on two computers A & B. It got all synced up and everything seemed to work fine. 
2. Added another computer C to sync the big folder. 
3. While files were being synced to C, I started looking into big folder on A. I realized that a lot of files & folder were no longer useful to me. So I deleted them, reducing the folder size to ~21GB. 
4. After ~10 minutes I noticed the message: `Folder "Blah-Blah" isn't making progress - check logs for possible root cause. Pausing puller for 1m0s`
5. Checked log files and found that they were >2GB in size on all computers and were filled with messages like `[OWIS7] 17:53:09 INFO: Puller (folder "Blah-Blah", file "blah-blah-blah.gz"): dst stat dir: stat /mnt/work/sync/old-deleted-folder: no such file or directory`

Computer A status:
![comp1](https://cloud.githubusercontent.com/assets/3436053/8321228/1a6e2bf4-19d9-11e5-91e7-a10402f310f3.png)

Computer B status:
![comp2](https://cloud.githubusercontent.com/assets/3436053/8321229/1a71d4fc-19d9-11e5-82a6-088fb1572af6.png)

As the number of files is relatively large, I can't possibly manually delete these empty folders, as suggested by some comments. Also, the logs are basically filling up my HDD. As of now, I have to stop syncthing. But I do need to sync. Is there a temporary workaround with the log file thing? Also, will using inotify-syncthing resolve this type of issue?

**Comment by dcarosone** [comment] 2015-06-24 03:56
Start syncthing, preferably in a manner that prevents the two instances
communicating, so they run disconnected.  (pull a network cable, or
whatever is appropriate)

Force both to rescan.

Let them connect.

You may still have problems, but if so, it's probably not this issue.

On 24 June 2015 at 12:03, C Bhushan <notifications@github.com> wrote:

> I think I am facing this issue right now. I did following:
>
>    1. Added a big folder (~90 GB with several folders and files) on two
>    computers A & B. It got all synced up and everything seemed to work fine.
>    2. Added another computer C to sync the big folder.
>    3. While files were being synced to C, I started looking into big
>    folder on A. I realized that a lot of files & folder were no longer useful
>    to me. So I deleted them, reducing the folder size to ~21GB.
>    4. After ~10 minutes I noticed the message: Folder "Blah-Blah" isn't
>    making progress - check logs for possible root cause. Pausing puller for
>    1m0s
>    5. Checked log files and found that they were >2GB in size on all
>    computers and were filled with messages like [OWIS7] 17:53:09 INFO:
>    Puller (folder "Blah-Blah", file "blah-blah-blah.gz"): dst stat dir: stat
>    /mnt/work/sync/old-deleted-folder: no such file or directory
>
> Computer A status:
> [image: comp1]
> <https://cloud.githubusercontent.com/assets/3436053/8321228/1a6e2bf4-19d9-11e5-91e7-a10402f310f3.png>
>
> Computer B status:
> [image: comp2]
> <https://cloud.githubusercontent.com/assets/3436053/8321229/1a71d4fc-19d9-11e5-82a6-088fb1572af6.png>
>
> As the number of files is relatively large, I can't possibly manually
> delete these empty folders, as suggested by some comments. Also, the logs
> are basically filling up my HDD. As of now, I have to stop syncthing. But I
> do need to sync. Is there a temporary workaround with the log file thing?
> Also, will using inotify-syncthing resolve this type of issue?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/syncthing/syncthing/issues/1838#issuecomment-114698260>
> .
>



-- 
Dan.

**Comment by AudriusButkevicius** [comment] 2015-06-24 06:20
Alternatively, readd the folder under a different name on all davices.

**Comment by cbhushan** [comment] 2015-06-26 18:42
Re-adding and rescanning did resolve lots of issues. 

Does inotify-syncthing resolve this type of issue?

**Comment by imsodin** [comment] 2020-03-19 22:04
This was fixed by https://github.com/syncthing/syncthing/pull/4767 (#accidentalArcheology).

**Closed by imsodin** 2020-03-19 22:04 UTC
Labels: enhancement
