### ISSUE TITLE
Syncing linux acl's and file ownership

### ISSUE THREAD

**Issue by useronkel** [syncthing/syncthing#8293] opened 2022-04-19 12:17 UTC
Hi.
Beside, it'a a great tool and avoid a lot of headaches which are caused by unison :-)
OS: Linux
We running into issues syncing multiple sftp and ftp-s servers, because the acl's and user/group ownerships are not synced.
We know there's a security impact on running as root on the hosts, but we have no alternatives for this.

We would be graceful, if this feature will be implemented on linux hosts. I think it could cause an incompatible version with m$-windows, but perhaps, the FileSystem Type is an alternative to this.
Multiple options for FileSystem Type could solve this issue.
Instead of just using 'basic', it could be enhanced with 'linux', 'extended acl' etc.

I think this is not only useful for me, but also for other linux users out there.
An alternative method is a script  which will run after filesync to sync permissions and acl's separately, but this is an awful solution (lack of time and inconsistancies).

Greetings :-)

**Comment by imsodin** [comment] 2022-04-19 12:25
That's a duplicate of https://github.com/syncthing/syncthing/issues/2698 (acl) and https://github.com/syncthing/syncthing/issues/1329 (group/owner).

**Closed by imsodin** 2022-04-19 12:25 UTC
Labels: enhancement, needs-triage
