### ISSUE TITLE
Sync Read-Only Master (Windows) to Linux NAS (QNAP Linux)

### ISSUE THREAD

**Issue by Catfriend1** [syncthing/syncthing#4589] opened 2017-12-12 08:24 UTC
Hi,

I am observing the same bug quite a long time (since the windows client was von 0.14.26 syncthing).
The Master sends an installation repository (exe, dll, inf, zip files and so on) from a local pc hard disk (NTFS) to a QNAP Linux NAS (ext4 native format). The NAS hosts the "duplicated folders" as a SMB share where windows clients have access to.

To cut down information a little bit as I think to know what happens, a brief reproduction:
a) In a sub-folder "Microsoft" of the root sync folder "Installation", there was a file "Autorun.inf" dated 2017-03-22 when the folder was first "filled" with data. The file synced ok to the NAS and was shared \\qnap\Installation\Microsoft\Autorun.inf. Clients could access the file properly.
b) Yesterday, I updated the folder by deleting all contents on the source PC and put a new content there. Then, the file "autorun.inf" had mod date 2017-12-11. It synced to the NAS and ls -l -a showed sth. like:
autorun.inf 2017-12-11
Autorun.inf 2017-03-22
c) I went into SSH to the NAS and deleted "Autorun.inf", because SMB clients always read "Autorun.inf" instead of "autorun.inf". ls then showed on the NAS:
autorun.inf 2017-12-11
... and clients could access this proper new file correctly via SMB.
d) Today, I hit the "Overwrite" button on the PC, because NAS showed out of sync. Then the NAS showed a problem, but had the right file.
autorun.inf 2017-12-11
![image](https://user-images.githubusercontent.com/16361913/33874073-c5063e24-df1d-11e7-94ef-545abc5fee87.png)
After pc override button was hit, a new file showed on the nas (I Think this causes the peer error)
.syncthing.Autorun.inf.tmp 12.12.2017 09.18.46
![image](https://user-images.githubusercontent.com/16361913/33874172-1846eb56-df1e-11e7-8798-ccb0cb661709.png)

Do you need more info to replicate this?
I think syncthing must prevent creating files under linux that are case-sensitive when a windows host tells a case-insensitive file-name.

### Version Information
Syncthing Version: v0.14.40 + v0.14.41 + v0.14.42-rc.1
OS Version: Windows 10 Pro 1703 + QNAP Linux FW 4.3.3.0361 (+ 4.3.3.0188)

**Comment by calmh** [comment] 2017-12-12 08:27
Duplicate of #1787, #2739 I think

**Closed by calmh** 2017-12-12 08:27 UTC
