### ISSUE TITLE
Folder quota / size limits

### ISSUE THREAD

**Issue by ServidoresJMG** [syncthing/syncthing#7464] opened 2021-03-13 07:28 UTC
Hi guys.
It would be possible to implement the size limitation per authorized device.
that is, if A wants to copy his documents into B, this grants him a space quota.
I think it is very possible and useful since currently the size of the synchronization is obtained, they could go for there are the shots.
I have several computers synchronized on a server, this is getting out of hand
Thanks

**Comment by calmh** [comment] 2021-03-13 08:18
Devices don't really have a size, folders do. Is this #4244? Note that you can set file system quotas on folders outside of Syncthing.

**Comment by AudriusButkevicius** [comment] 2021-03-13 09:18
Pretty sure it is.

**Comment by ServidoresJMG** [comment] 2021-03-13 09:46
disk quotas cannot be set in windows per device or folder, if not per user

**Comment by calmh** [comment] 2021-03-13 10:06
That's unfortunate. Perhaps some other file system, storage technology, or operating system might be better suited.

**Comment by calmh** [comment] 2021-03-13 10:13
Actually, I'll reopen as this is something that could conceivably be done, and that people might want to vote for. I don't think we should do it, and I'm not going to do it, but someone might come up with a comprehensive proposal and an elegant implementation and then I wouldn't stand in the way.

**Comment by AudriusButkevicius** [comment] 2021-03-13 10:15
It's not true that windows does not support it.


https://docs.microsoft.com/en-us/windows-server/storage/fsrm/checklist-apply-quota-to-volume-or-folder

**Comment by imsodin** [comment] 2021-03-13 10:26
Duplicate of https://github.com/syncthing/syncthing/issues/4244

**Closed by imsodin** 2021-03-13 10:26 UTC
