### ISSUE TITLE
Paused/resume device API calls can hang for long periods

### ISSUE THREAD

**Issue by canton7** [syncthing/syncthing#3001] opened 2016-04-22 11:03 UTC
I've had an issue reported (https://github.com/canton7/SyncTrayzor/issues/252) where calls to `/rest/system/resume` and `/rest/system/pause` can sometimes hang (for more than 90 seconds, at which point I time out). It appears to happen unpredictably.

It appears that the device in question is never actually paused/resumed, although I'm not 100% sure of that.

I notice that `PauseDevice` and `ResumeDevice` both [acquire a lock](https://github.com/syncthing/syncthing/blob/ea54525a33e4d59be1025d740da6c23c069913ea/lib/model/model.go#L1069) - maybe something's holding this for an extended period?

Syncthing version v0.12.22, Windows.

**Comment by AudriusButkevicius** [comment] 2016-04-22 11:14
We need to make it crash somehow to figure out whats holding the lock. My money is on Windows firewall blocking socket writes indefinately.

**Comment by canton7** [comment] 2016-04-22 11:18
Tricky... we lost the "monitor" process (SyncTrayor) when that dies, so we won't be able to capture output even if we do get it to crash.

I can probably code up something to kill Syncthing if it does die, but I'm not sure how to kill it in such a way that it will produce the output you need, working within the constraints of the winapi. Any suggestions?

**Comment by AudriusButkevicius** [comment] 2016-04-22 11:27
It prints the stacktraces to stderr/out so I think you can capture them just fine. The bigger problem is making it crash. I know it's sigstop on unix, no idea what it is in windows. Worst case we can add a crash/debug endpoint which returns the stacktraces to as json or forces a panic.

**Comment by canton7** [comment] 2016-04-22 11:46
Hmm, I can't seem to find anything helpful online.

**Comment by AudriusButkevicius** [comment] 2016-04-22 11:52
See http://stackoverflow.com/a/19145992/1508606 and STPROFILE

**Comment by canton7** [comment] 2016-04-22 11:55
Perfect, thanks :+1:

**Comment by AudriusButkevicius** [comment] 2016-04-22 12:02
Also, STTRACE=sync (I think) will log lock usage, there is also another var (check help) for defining a threshold what gets logged. Hard to find links on the phone.

**Comment by scienmind** [comment] 2016-05-01 15:06
Ok, I had several of those crashes (https://github.com/canton7/SyncTrayzor/issues/252) appearing randomly. Usually after prolonged usage (i.e. running ST overnight). 
Now, while the full blown crash is quite rare, the same error message appears in the logs far more frequently.

So, here's SyncTrayzor log with the error, appearing after "wake from sleep":
https://gist.github.com/anonymous/a2baa96d5f17b65c269f36316493b6ed

And, as per canton7's request, I've set `STPROFILER=localhost:8385`, and here's the output of  `http://localhost:8385/debug/pprof/goroutine?debug=2`: 
https://gist.github.com/anonymous/973b8cbf5cfb9f3cad63daa184403b1a

**Comment by AudriusButkevicius** [comment] 2016-05-01 16:00
So the crash you posted now does not look related to the original crash, furthermore, I don't see any reasonable blocking from syncthing. The only lock I can see is on the GetIgnores() due to a scan currently running.

**Comment by scienmind** [comment] 2016-05-01 16:02
OK, I'll post again the "actual" crash then, once I'll catch it

**Comment by canton7** [comment] 2016-05-01 16:58
That SyncTrayzor log doesn't show a crash, no.

**Comment by scienmind** [comment] 2016-05-11 11:57
I have had SyncTrayzor & Syncthing silently crashing during "wake from sleep", here are the logs:
SyncTrayzor: https://gist.github.com/anonymous/a52a5158bd4cca9145137fda6092dc2d
Syncthing: https://gist.github.com/anonymous/7134dbcbadf381ff1e83961fb7056c31

Unfortunately, `/debug/pprof/goroutine?debug=2` can't be polled, since syncthing is dead...

**Comment by AudriusButkevicius** [comment] 2016-05-11 12:44
This is on Synctrayzors plate, not syncthings.

**Comment by canton7** [comment] 2016-05-11 13:30
Yes, this is a separate issue. Please open a new issue on SyncTrayzor's issue tracker.

**Comment by AudriusButkevicius** [comment] 2016-07-04 20:39
Any reproducers, or should we close this?

**Comment by scienmind** [comment] 2016-07-04 20:44
I added some logs here recently: https://github.com/canton7/SyncTrayzor/issues/252#issuecomment-226832675

If people are positive that it's purely a wrapper's fault, than this can be closed...

**Comment by AudriusButkevicius** [comment] 2016-07-04 20:49
So there are no outstanding/in progress rest requests in the profiles you posted.

**Comment by scienmind** [comment] 2016-07-04 21:23
If @canton7 confirms that the cause behind those recent crashes isn't due to syncthing's misbehave, we can close this.

**Comment by canton7** [comment] 2016-07-04 21:51
The logs of @scienmind's still show `/rest/system/{pause,resume}` hanging for long periods. 

Last I remember, we were waiting for @scienmind to post the output of `/debug/pprof/goroutine?debug=2` after it happens again.

**Comment by AudriusButkevicius** [comment] 2016-07-04 22:00
Well if you look for gui in the stacks he posted (on your ticket), there is barely anything there.

**Comment by canton7** [comment] 2016-07-04 22:09
Hmm, both if those logs are different again. 

I can't look up which request they're making since I'm on mobile, but the error is `SocketException No connection could be made because the target machine actively refused it 127.0.0.1:PORT` instead of the timeout I opened this issue about.

**Comment by canton7** [comment] 2016-07-04 22:13
I'll have a better look tomorrow when I'm at a computer.

**Comment by calmh** [comment] 2016-11-23 13:26
Barring deadlocks and stuff (which are bugs that we should fix), the calls blocking until the pause/resume action is taken is by design and not a bug. We may add things to or redesign the API, but this is not the ticket for it.

**Closed by calmh** 2016-11-23 13:26 UTC
Labels: bug

**Comment by calmh** [comment] 2016-12-26 13:18
How was this addressed by this change?

**Comment by AudriusButkevicius** [comment] 2016-12-26 13:36
Device pauses are now handled in CommitConfig which I hope fixes this issue.

**Comment by calmh** [comment] 2016-12-28 22:07
I think it doesn't as things still require holding pmut, which is what was blocking above. (I'm not convinced this is a problem necessarily, and we should slowly move away from those locks probably, but it's not my bug report.)

**Comment by AudriusButkevicius** [comment] 2016-12-28 22:10
Well if OP can still repro we can reopen.

**Comment by scienmind** [comment] 2016-12-28 22:21
I haven't witnessed those crashes for quite a long while. And unfortunately I never got a clear way/steps of reproducing it, it always was kinda random.
I had few crashes a couple of weeks ago, but timing was bad and I couldn't play with it much, so it may be unrelated to this issue.

If it'll reappear, I will let you know.
