### ISSUE TITLE
In-place file updates on devices with little spare space

### ISSUE THREAD

**Issue by 01010101lzy** [syncthing/syncthing#7130] opened 2020-11-19 16:52 UTC
## Feature request

When updating a file, instead of copying all content into a temporary file and replacing the original, only write the difference between the old and new file, and update the target file in-place.

## Reason

When syncing large files between almost-full disks, the current syncing method makes it impossible when empty space is smaller than file size. This is especially useful when the large files only change by a little (e.g. game files between game updates).

## Workarounds?

My current workaround is to use a second disk to hold some of the large files while letting Syncthing update the rest.

**Comment by imsodin** [comment] 2020-11-19 17:21
Duplicate of https://github.com/syncthing/syncthing/issues/3897

**Closed by imsodin** 2020-11-19 17:21 UTC
Labels: enhancement, needs-triage
