### ISSUE TITLE
Tracking moved/renamed/deleted files/folders

### ISSUE THREAD

**Issue by jamilk** [syncthing/syncthing#1677] opened 2015-04-21 14:43 UTC
(Apologies if this has already been discussed, I've tried to understand Syncthing, but I don't quite have my head wrapped around how it work just yet.)

I work in an office with ~25 computers, some are laptops which are often disconnected from the network/internet for days at a time before reconnecting. My colleagues are not at all technical and do strange things with their files all the time.

There are a number of problems we've seen with Bittorrent Sync (which we're hoping to scrap when Syncthing v1.0 comes out), which seem to share a common origin: Deletions don't seem to be properly tracked.
### Scenario 1: Simple deletion

File/folder is deleted, computers currently online all sync up, then later a laptop rejoins the network and adds the deleted file/folder back again. Unless we can get ALL of our computers onto the network syncing all at the same time (which we should assume is never), we will have zombie files/folders that keep reappearing and just won't die.
### Scenario 2: Simple rename/move of a file/folder

This is equivalent to a delete old + add new. It suffers the exact same problem as above, but additionally needs the entire folder to be copied again (I understand this is because it's impossible(?) to know the difference between a "move" and a "delete + add").
### Scenario 3: The Marjorie Manouevre

Named after the colleague who did it, it's where she needed to update a file with new info, then save it under a different name (the filename contains the date of modification, which is fine, I don't care). What she did was:
1. Modify the file and save it
2. Rename the file
This created a problem, because the first modification started to sync through the network, when the file was effectively deleted and added under a new name. The old file then appeared again later. I don't know if it was the modified version or not, because although the computers' clocks are synced, the timestamps aren't necessarily 100% accurate.

Ideally, it would be nice for every file to have its own unique identifier (perhaps a filesize + CRC hash), which would remain the same regardless of renaming/moving and stored in a database (the .sync directory?) to keep track of deletions.

Really, it makes sense for it to work like Git itself, but where push/pulls are done in real-time and fast-forward merges are done automatically.

Thanks for building Syncthing. I'm excited for it to reach v1.0!

**Comment by calmh** [comment] 2015-04-21 14:49
I think all of this should be nicely handled in v0.11 at least. Probably in v0.10 as well to be honest, but there may be issues there in other cases, around conflicts...

**Comment by ultravioletnanokitty** [comment] 2015-04-24 00:37
in my experience, syncthing is particularly bad at dealing with a synced folder being completely reorganised. for example, i'm currently rearranging and cleaning up my images folder (with many subdirectories), which is synced between only two nodes (my laptop and desktop). as the folder had gotten very messy, i've been moving folders and hundreds of individual files around, but not removing more than a few individual files. if i move, say, a folder containing ~500 images into a new subfolder, syncthing completely fails to notice how simple the change really was. instead, it immediately tells me that <size of folder> is out of sync, and spends far too long (on the order of 15+ minutes) reconciling the changes. luckily, it does seem to check itself locally before wasting network bandwidth by re-transferring the files, but the amount of time it takes to re-verify the exact same data in a new folder is ridiculous. if it makes a difference, i am using the syncthing-inotify extension. the same behaviour occurs if i run syncthing without the wrapper, however, so i don't think it's an issue.

my suggestions: use the native inotify support that's supposedly coming (or another method, if deemed superior) to track when files and entire directories are moved, as opposed to deleted. implement a means of informing other nodes that those files/directories only need to be relocated, so that nodes don't spend forever rearranging files one-at-a-time.

**Comment by calmh** [comment] 2015-04-24 05:14
Yeah. Since we don't do inotify, we don't know what's a rename and what isn't, so we need to rehash the new files. The other devices will see the rename however, and do it efficiently. And I don't see this being a particularly common situation...

**Comment by ultravioletnanokitty** [comment] 2015-04-24 06:46
well, what about my question? does REST provide a way to report the difference to syncthing? if not, why not? it makes sense that syncthing can't handle this itself, but it seems like you could at least provide a means for an external wrapper to solve this problem...

also, i believe this is a very common situation. how else is one to completely (or even slightly) change the subfolder structure of a synced folder? i rearrange my folders like this on a periodic basis, as i tend to save things in a rather disorganised fashion when i'm in a hurry. i'm sure i'm far from the only one who does this... especially considering non-technical users like Marjorie above. even when the user is well-informed, moving one single directory into a different subdirectory will trigger this behaviour. this can be disconcerting since all syncthing tells you is that (possibly several GiB of) your files are out of sync, and the hashing process takes a long time.

at the very least, i feel syncthing should recursively check if a newly added file/directory structure (based upon any combination of name, permissions, and size, not hashes) perfectly matches one that was just removed, and inform the user of something more specific than "out of sync". for example, a separate "verifying moved files" progress bar would be much better. if the data proves to be different, then the "out of sync" indicator would be triggered. it takes minimal processing power to compare two directory trees based upon readily available attributes, so it could be done quite quickly.

suddenly changing folder sizes and file counts after a simple move are confusing and worrying, and i feel that providing a separate indicator for re-hashing of existing files would greatly improve user experience.

**Comment by AudriusButkevicius** [comment] 2015-04-24 07:54
It does not take minimal processing power to compare two directory trees, as you still need to rehash the files to verify it's the same file as before. There is no other way, apart from blindly closing your eyes and trusting that inotify says without even validating it.

As for the UX, it says scanning, at that point you know that nothing is accurate until it completes hence I am not sure what the issue is. Are you suggesting we hide file counts while scanning is in progress?

**Comment by dcarosone** [comment] 2015-04-24 08:02
The suggestion is that for (say) a directory move out rename, the tree of
file stat attributes other than hash (mtime, inode, size, blocks, etc) will
match.

The idea seems to be to do a fancy list/tree compare after scanning stat
info, but before hashing, to see if a large common subset can be explained
by a directory move.

**Comment by ultravioletnanokitty** [comment] 2015-04-24 08:09
@AudriusButkevicius the idea is to make it clear to the user that syncthing knows about the move (and that it's re-checking their files) and isn't going to waste your network bandwidth or mess your files up. comparing the file/directory structure before re-hashing uses minimal processing power, as the attributes in question can simply be read from disk. i'm well aware that re-hashing is necessary without good filesystem watching, and i'm not suggesting that be changed.

@dcarosone that's exactly what i mean. this isn't about changing how syncthing handles things, as that seems to be sound and the re-hashing is unavoidable since we can't tell if a file was really just moved (and not modified too) without it. i simply feel it'd improve user experience greatly to display a separate message under the repository status when a probable move is detected via attributes that are readily available.

**Comment by AudriusButkevicius** [comment] 2015-04-24 09:15
Well we've already established that syncthing doesn't know about the move. Syncthing knows about some files being removed and some files being added.
I think that hiding file counts while scanning is happening is the best solution as it does not make the job any more resource intense, and to make people less paranoid.

In order to deduce the `probable move` you'd have to traverse the folder twice, once building up some sort of index what was removed and newly added to make this deduction, then traversing 2nd time to actually do the job of hashing. This has a cost of actually storing the index, and actually traversing the folder twice... I personally would rather not have this additional cost for the sake of some questionable (as it's not yet well defined) UX improvement.

@dcarosone mtime size does not necessarily mean it's the same file and inode is linux specific.

**Comment by ultravioletnanokitty** [comment] 2015-04-24 11:44
@AudriusButkevicius your points about extra resource cost are absolutely valid... that said, hiding things from the user is rarely the best answer. i myself find it helpful and reassuring to be able to watch file counts and folder sizes as syncthing figures them out. it'd just be more helpful if the status display was more descriptive than "scanning" and "out of sync". perhaps don't show the out-of-sync display unless syncthing is certain that things haven't just been rearranged? it still seems better to me to provide more specific information (while keeping it non-technical), as opposed to less or none at all. 

as for ux improvement, i agree that detecting probably moved files isn't worthwhile if it can't be done very cheaply resource-wise. i have to wonder how significant the resource cost would really be, though... since the objective is to detect a move of an identical folder structure within a sync repo, perhaps traversing entire directory trees isn't necessary unless things match at the upper levels of the tree. a new folder with a different name from existing folders in the repo can be eliminated instantly, for example. also, does syncthing not already build up such an index prior to hashing so it knows what it needs to hash? i was under the impression that this data is largely already available to syncthing, it just needs to be compared.

if the initial comparison can be done at minimal resource cost, it'd be trivial to display a different message than "out of sync" (like "verifying moved files" as i suggested above) for the same counters currently under that heading. anyone who's used bittorrent sync is likely to be more than a little cagey about seeing a ton of their files suddenly go out of sync, as with that product it can often mean that you'll have quite a duplicate mess to clean up shortly.

overall, i feel it would greatly help overall user perception if syncthing was more communicative about what it's doing. this is especially true with non-technical users coming from bittorrent sync. the current level of vagueness, combined with how long the hashing process takes, can easily lead to the perception that something is wrong. this is especially true when the user doesn't expect that a simple move should trigger such a lengthy rescan.

**Comment by calmh** [comment] 2015-04-24 23:09
Being able to tell syncthing that something was renamed seems useful, but is also a bit risky. Currently syncthing only trusts what it can see by itself by reading and (cryptographically secure) hashing the files. If it completely trusted an external source about what happens, you could easily end up with corruption. The current approach uses more resources on the source device, but it ensures the end result is correct.

**Comment by ultravioletnanokitty** [comment] 2015-04-25 00:23
@calmh you make an excellent point there. that said, it would be a useful feature to have for those who know the potential consequences and are using a wrapper they trust. perhaps add the capability, but make it an advanced option that displays a warning when enabled? that way, by default the risk wouldn't be present.

**Comment by calmh** [comment] 2015-04-25 00:40
I think the *real* solution here is to merge with the syncthing-inotify project, and then implicitly trust the inotify notifications. Until then, I honestly don't think it's worth making the change just to avoid some read IO on the source device. Well, unless someone files an awesome pull request to do this, then it'll certainly be considered.

**Comment by Zillode** [comment] 2015-05-06 21:33
https://github.com/syncthing/syncthing/issues/1711 could also help

**Comment by terrycloth** [comment] 2015-06-06 08:58
Another possible solution for moving files and folders, is *start* the move or rename from the Syncthing GUI. There would be no way for a user to make a destructive mistake if they told Syncthing to move a folder or rename some files or whatever, and then Syncthing took care of it.

**Comment by 3three** [comment] 2015-07-15 14:36
I completely agree that merging with syncthing-inotify is a good idea.

Under heavy usage, as you'd find in a multi-person office, the reliability needs to approach that of the actual file-system itself. Where, regardless of what operation (add, delete, rename, modify, etc.), how quickly those operations occur (potentially faster than the difference in clock synchronisation), the possibility of conflicts/branches, the number of clients, or the connectivity state of each client, syncthing must always remain in a coherent state.

If not, I fear that it simply won't be able to scale, which would be a real pity.

But if so, then there would be a multitude of real-world use-cases.

Git itself is all of those things, minus the automatic syncing. If there was a way to incorporate branches, with auto-merging, in a way that was close to transparent to the user, then it'd be terrifically useful. As I mentioned before that may mean hunkering down closer to the file-system level.

(Perhaps the syncthing client could do alerts/notifications whenever a choice of branch appears?)

I realise this is a huge ask, but the reliability under all conditions is (I believe) quite important.

**Comment by xordspar0** [comment] 2018-09-03 21:12
Has any work been done on this recently? Is it still valid?

**Comment by calmh** [comment] 2018-09-04 04:44
I’m honestly not sure what this issue is about or what is the actionable outcome to close it. I think maybe to do renames without rehashing? I don’t think we’ll ever do that.

I’m going to close. If someone can summarize in a couple of sentences what he action would be that I’ve missed, please do so for a reopen.

**Closed by calmh** 2018-09-04 04:44 UTC
Labels: enhancement
