### ISSUE TITLE
date selection GUI corrupted

### ISSUE THREAD

**Issue by QingKongBaiYu** [syncthing/syncthing#7650] opened 2021-05-09 15:03 UTC
version: 1.16.1
browser: chrome 90.0.4430.93
cannot select date when trying to restore version.

![image](https://user-images.githubusercontent.com/45838887/117577003-898e4300-b11a-11eb-8ccf-434e8e531f61.png)

**Comment by AudriusButkevicius** [comment] 2021-05-09 15:10
Duplicate of #4755

**Closed by AudriusButkevicius** 2021-05-09 15:10 UTC
Labels: bug, needs-triage
