### ISSUE TITLE
v1.26.0 GUI Loops Forever on Login

### ISSUE THREAD

**Issue by alexmarkley** [syncthing/syncthing#9210] opened 2023-11-09 23:48 UTC
### Does your log mention database corruption?

No errors in log.

### Include required information

**which version of Syncthing and what operating system you are using**

v1.26.0, Linux (64-bit Intel/AMD Container)

**browser and version, if applicable**

Issue is present with Firefox 119.0 (64-bit) on macOS.

(Cannot be reproduced with Google Chrome Version 119.0.6045.123 (Official Build) (arm64))

 **what happened**

I was presented with the new form-based login screen. I logged in with my usual username and password. Instead of showing me the dashboard, the browser tab locks up with what looks like a redirect loop.

**what you expected to happen instead**

I expected to log in and be presented with the usual dashboard.

**any steps to reproduce the problem**

This issue only seems to affect v1.26.0 when using Firefox to access the GUI. **Also** this issue only seems to get triggered if I am accessing a remote Syncthing GUI using the IP address of the remote host. (This issue does not occur when loading the local GUI via `localhost`.)

**WORKAROUND**

I've gone into the settings and set `sendBasicAuthPrompt` which allows me to access the dashboard via Firefox.

**Comment by bt90** [comment] 2023-11-10 06:08
Duplicate of #9208

**Closed** 2023-11-10 06:08 UTC
Labels: bug, needs-triage

**Comment by pyhedgehog** [comment] 2023-11-13 23:08
@bt90
> Duplicate of #9208
Maybe there are another reason: #9221 (not duplication of cookies, but incorrect cookie option).
