### ISSUE TITLE
 Capitalization Issues 

### ISSUE THREAD

**Issue by UVJkiNTQ** [syncthing/syncthing#6012] opened 2019-09-13 13:25 UTC
### Version Information

Syncthing Version: v1.2.2
OS Version: Windows 10 and Archlinux x64

This issue happens within different OS. 
I suggest X (Windows) and Y(Linux). 
I will try to express the issue in timeline.

Scene.0
X: abc
Y: abc

Scene.1
abc on X renamed to Abc
X: Abc
Y: Abc, abc

Scene.2
pause syncthing
rm -r abc on Y  （I guess I may have problems, so I backuped ABC on X）
and restart syncthing
At the early seconds
X: Abc
Y: Abc

Very short after
X: (null)
Y: Abc

Very short after
X: (null)
Y: (null)

--------------------
It seems syncthing on X trys to delete abc on X and because of windows api treats Abc as abc.
A rename deadly cause a big problem.
Is there a way to prevent this?

**Comment by calmh** [comment] 2019-09-13 13:47
Duplicate of #1787. Also #2739.

**Closed by calmh** 2019-09-13 13:47 UTC
