### ISSUE TITLE
Discovery P2P

### ISSUE THREAD

**Issue by Slender1808** [syncthing/syncthing#8056] opened 2021-11-23 17:31 UTC
Having a p2p discovery system improves scalability and also provides backup system for current discovery system as well as allowing users to participate in the project.

My suggestion does not depend on modifications to the project for its functioning.

The way I thought would be by creating a folder and sharing it on syncthing, and somehow getting the id and ip connected in that folder and saving it within itself.

The way to store this data can be through sqlite or folder structure.

### Sqlite structure example:

| ip | id |
|--|--|
| 8.8.8.8 | EQ652TN-45GGV3I-TA6UEPW-VLZBJPD-VBMQXXN-3JTXJ36-4YHLFF7-VTTRQAR |
| 145.46.78.45 | TQ652TN-45GGV3I-TA7UEPW-VLZBJPD-VBMQXXN-3JTXJ36-4YHLFF7-VTTRQAR |

### Folder structure example:
IP 8.8.8.8

/8/8/8.csv

| Class | Initial bits | Start | End | Subnet mask | CIDR notation |
|--|--|--|--|--|--|
| A | 0 | 1.0.0.1 | 126.255.255.254 | 255.0.0.0 | /8 |
| B | 10 | 128.0.0.1 | 191.255.255.254 | 255.255.0.0 | /16 |
| C | 110 | 192.0.0.1 | 223.255.255.254 | 255.255.255.0 | /24 |

using the ip mask as a way to separate into folders and where the last part of the ip mask would be csv file where it would have ip with id

| ip | id |
|--|--|
| 8 | EQ652TN-45GGV3I-TA6UEPW-VLZBJPD-VBMQXXN-3JTXJ36-4YHLFF7-VTTRQAR |
| 45 | TQ652TN-45GGV3I-TA7UEPW-VLZBJPD-VBMQXXN-3JTXJ36-4YHLFF7-VTTRQAR |

**Comment by calmh** [comment] 2021-11-23 20:28
Duplicate of #3388

folding into parent issue

**Closed by calmh** 2021-11-23 20:28 UTC
Labels: enhancement, needs-triage
