### ISSUE TITLE
Potential for Excessive DNS requests

### ISSUE THREAD

**Issue by bluewavenet** [syncthing/syncthing#2718] opened 2016-01-20 18:28 UTC
Looking at the dnsmasq logs on my router, Syncthing seems to be making very large numbers of DNS queries. 

I am running two instances on both of two laptops running OpenSuse Leap 42.1. 
Syncthing performance is very good, but the router (running OpenWrt) is showing dnsmasq as the busiest service running on it. Two laptops with ip4 and ip6 and two instances each, yes, but it repeats over and over.

Syncthing v0.12.15. but not looked for this with previous versions.

Attached is a sample log file, grep filtered for syncthing.
[syncthing.txt](https://github.com/syncthing/syncthing/files/97877/syncthing.txt)

**Comment by calmh** [comment] 2016-01-20 19:27
Weird. Syncthing logs say something?

**Comment by bluewavenet** [comment] 2016-01-20 20:44
All looks normal, very little to say for its self. Typical startup log, after this it pretty much stays quiet:

Jan 20 20:39:54 linux-8nro syncthing[8674]: [KZINF] INFO: Using discovery server https://discovery-v6-3.syncthing.net/?id=VK6HNJ3-VVMM66S-HRVWSCR-IXEHL2H-U4AQ4MW-UCPQBWX-J2L2UBK-NVZRDQZ
Jan 20 20:39:54 linux-8nro syncthing[8674]: [KZINF] INFO: Completed initial scan (rw) of folder default
Jan 20 20:39:54 linux-8nro syncthing[8674]: [KZINF] INFO: Device H3HO47M-PTTISGN-GZQ7JGV-UDKJNKB-VTR7IDQ-UKSCMWO-7B3KRUH-6CVDYQB is "linux-inspiron.site@rob" at [dynamic]
Jan 20 20:39:54 linux-8nro syncthing[8674]: [KZINF] INFO: Device KZINF6G-KAN5URU-METBYQ7-P6TSK5Z-V5OX67K-BKO7LCN-3TER3VP-CPSRUAQ is "linux-8nro-tosh@rob" at [dynamic]
Jan 20 20:39:54 linux-8nro syncthing[8674]: [KZINF] INFO: Device GWV6AEU-KDGRD5I-QW2DDKK-F3FPAF7-JAVZ22I-4QEKNDA-4AAKUFI-66AURQI is "linux-2kns.site@rob" at [dynamic]
Jan 20 20:39:54 linux-8nro syncthing[8674]: [KZINF] INFO: Starting usage reporting
Jan 20 20:39:54 linux-8nro syncthing[8674]: [KZINF] INFO: API listening on 127.0.0.1:8384
Jan 20 20:39:54 linux-8nro syncthing[8674]: [KZINF] INFO: GUI URL is https://127.0.0.1:8384/
Jan 20 20:40:04 linux-8nro syncthing[8674]: [KZINF] INFO: No UPnP device detected
Jan 20 20:40:05 linux-8nro syncthing[8674]: [KZINF] INFO: Completed initial scan (rw) of folder Data

**Comment by AudriusButkevicius** [comment] 2016-01-20 23:33
Try STTRACE=dailer env var

**Comment by bluewavenet** [comment] 2016-01-21 11:10
I have set STTRACE to dialer and shows no difference. I am not sure syncthing is picking it up as I am running as user, started with systemd using sysncthing@.service. Have set STTRACE for both root and the user (rob).
What should I expect? Do I need to modify sysncthing@.service?

**Comment by canton7** [comment] 2016-01-21 11:14
> What should I expect? Do I need to modify sysncthing@.service?

Yes: Add `Environment=STTRACE=dialer` to the `[Service]` section, then `systemctl daemon-reload` to reload it (then restart syncthing)

**Comment by rumpelsepp** [comment] 2016-01-21 11:55
> What should I expect? Do I need to modify sysncthing@.service?

Use a dropin; `systemctl edit syncthing@youruser.service`.

**Comment by bluewavenet** [comment] 2016-01-21 13:16
This is the only difference:
Jan 21 12:57:53 linux-8nro syncthing[21342]: [KZINF] DEBUG: Dialer logging disabled, as no proxy was detected.
@rumpelsepp systemctl is not supported on opensuse leap.
@canton7 Adding a Environment line did the trick.

**Comment by rumpelsepp** [comment] 2016-01-21 13:17
> systemctl is not supported on opensuse leap

Sounds like a really outdated systemd version, then. Anyway…

**Comment by bluewavenet** [comment] 2016-01-21 13:21
systemctl edit is not supported. It is a very stable distro, released only in December 2015, so not so much outdated, more not state of the art. Not a problem.
Anyway :  Dialer logging disabled, as no proxy was detected. ?

**Comment by rumpelsepp** [comment] 2016-01-21 13:24
> systemctl edit is not supported. It is a very stable distro, released only in December 2015, so not so much outdated, more not state of the art. Not a problem.

Last post from my side, to avoid bikeshedding… :)
I talked about system**d**; `systemctl` has been added with version 218, which has been released in december 2014: https://github.com/systemd/systemd/blob/ddb4b0d3eb57292c38a76f9b977f73cea15448fb/NEWS#L1364-L1369

**Comment by bluewavenet** [comment] 2016-01-21 13:37
OpenSuse Leap 42.1 has version 2.10, whereas Tumbleweed has 2.24, so there we have it.

However, this is not the problem. Syncthing is still dns bombing my router ;)

**Comment by rumpelsepp** [comment] 2016-01-21 13:42
Maybe you could try `STTRACE=discover` instead.

**Comment by canton7** [comment] 2016-01-21 13:46
Maybe I'm betraying a lack of knowledge here - but isn't the problem most likely to lie somewhere between the Go stdlib and your computer? Syncthing will tell Go "OK, open a connection to *this domain*". Go will (probably?) invoke some OS-specific API call to resolve that domain to an IP. Your OS will then decide whether to use a cached response, or query its DNS server. Here, apparently, it's deciding to do the latter.

I'm not sure how Syncthing can possibly affect this process. For example, if you 'ping google.co.uk' does this hit your router?

**Comment by bluewavenet** [comment] 2016-01-21 14:21
@canton7 
If I ping a new url, the local OS hits the router. If I ping again, the OS gets the answer from it's cache, ie not the router.

**Comment by bluewavenet** [comment] 2016-01-21 14:23
@rumpelsepp 
STTRACE=discover:
[SyncthingDebugDiscover.txt](https://github.com/syncthing/syncthing/files/99238/SyncthingDebugDiscover.txt)

**Comment by canton7** [comment] 2016-01-21 14:25
>  If I ping again, the OS gets the answer from it's cache, ie not the router.

How come the OS is using its cache for ping, but not for requests made from Syncthing, then?

**Comment by bluewavenet** [comment] 2016-01-21 14:39
@canton7   No idea, but it is doing so. I forget the details but it is possible to call the dns libraries specifiying no-cache.... Cant think of any reason otherwise.
eg if I use nslookup google.com it gets it from cache if available, but dig google.com always hits the router.
With 3 laptops, each with 2 instances of Syncthing, it is noticeable on the router, but not yet a problem. With an office of 10 laptops all syncing 10 users data for hot desking/home working, suddenly it may well be an issue.
Syncthing takes this type of config in its stride and works beautifully, tested with 4 users/laptops so far, making local servers and cloud solutions redundant....  :)

**Comment by calmh** [comment] 2016-01-21 18:32
Statically linked Syncthing uses an internal resolver, so I'm guessing this is the 32 bit build maybe?

**Comment by bluewavenet** [comment] 2016-01-21 20:50
No, sorry, 64 bit.

**Comment by bluewavenet** [comment] 2016-01-21 21:20
Whether the OS is caching or not is not the issue. Why is syncthing making such rapid and repeated queries on my setup? syncthing-linux-amd64-v0.12.15, and openSUSE-Leap-42.1-x86_64

**Comment by AudriusButkevicius** [comment] 2016-01-21 21:43
how do you know its syncthing though?

**Comment by bluewavenet** [comment] 2016-01-21 21:51
See the router dnsmasq log I first posted - all syncthing. It is going to be something fairly simple I'm sure.

**Comment by bluewavenet** [comment] 2016-01-21 21:59
Actually, I see the problem. Syncthing is trying to resolve discovery-v6-3.syncthing.net and it does not exist, apparently. So it keeps asking over and over.

**Comment by bluewavenet** [comment] 2016-01-21 22:02
discovery-v4-1.syncthing.net as well.

**Comment by canton7** [comment] 2016-01-21 22:03
```
$ dig discovery-v6-3.syncthing.net AAAA

;; ANSWER SECTION:
discovery-v6-3.syncthing.net. 30 IN     AAAA    2400:6180:0:d0::d9:d001

$ dig discovery-v4-1.syncthing.net A

;; ANSWER SECTION:
discovery-v4-1.syncthing.net. 134 IN    A       194.126.249.5
```

Looks like they exist to me...

**Comment by canton7** [comment] 2016-01-21 22:12
>  Why is syncthing making such rapid and repeated queries on my setup

Like I said... 

> Syncthing will tell Go "OK, open a connection to this domain". Go will (probably?) invoke some OS-specific API call to resolve that domain to an IP. Your OS will then decide whether to use a cached response, or query its DNS server.

Someone using a programming language will not typically do a DNS lookup, cache the result themselves, then use that cache: they'll ask the standard library "OK, open a connection to this domain, and do the DNS lookup if you have to". Neither is it (typically) the standard library's responsibility to cache the results of DNS lookups: that would lead to really hard-to-diagnose issues where the user is flushing their PC's DNS cache like crazy, but some applications still use a stale record because they have a separate cache. 

It's not Syncthing that should be caching anything: it's your OS. So the question is why isn't your OS caching the lookups?

It looks like Syncthing is asking the OS for the A records for domains with only AAAA records, and for AAAA records for domains with only A records. It's understandable that the OS can't answer this question, and defers to the router. However the OS is also being asked for lookups that it should have cached (successful lookups, at that), and the OS is inexplicably forwarding those to the router.

Are you certain your OS is set up to cache DNS lookups? Is nscd running? (google tells me this is what OpenSUSE uses)...

**Comment by bluewavenet** [comment] 2016-01-22 08:27
The issue here is not whether my OS caches or does not.

This came to light as I was working on a different project and set out to monitor dnsmasq on the router but found so much "noise" from syncthing that it made it difficult to see what I was looking for .

**The issue is why syncthing rapidly retries dns queries. Does it NEED to do so?**

Even if it does, it is not a problem for one instance of syncthing running on a LAN.
BUT what if 100 or more instances were running somewhere on that LAN.

For whatever reason, it appears my router sometimes cannot resolve one or other of the discovery servers. That is not the issue here either. It might be the reason it is happening though...

**Comment by canton7** [comment] 2016-01-22 08:32
It looks like Syncthing's interacting with the discovery servers about once every 10 seconds (@calmh or @AudriusButkevicius will have to tell you whether this is expected).

> The issue here is not whether my OS caches or does not.

Again, in my understanding, it is. Applications very rarely cache DNS lookups: it is not their responsibility (things like browsers do tend to, but they're the exception). It is the responsibility of the OS to be the first line of caching..

**Comment by canton7** [comment] 2016-01-22 09:20
In fact, it is not possible for applications to cache DNS lookups in accordance with the specification: `getaddrinfo` does not return the TTL, and so applications do not know how long to cache records for.

**Comment by bluewavenet** [comment] 2016-01-22 11:24
I am not asking for syncthing to cache its dns lookups. 
I am asking why syncthing generates so many in the first place.
It makes it potentially **VERY** noisy when it is just checking to see if it has anything to do.

**Comment by MyPod** [comment] 2016-01-22 11:25
I think that has been answered to you already
> It looks like Syncthing is asking the OS for the A records for domains with only AAAA records, and for AAAA records for domains with only A records.

**Comment by canton7** [comment] 2016-01-22 11:27
> I am asking why syncthing generates so many in the first place.

As I said, because Syncthing is making lots of connections to other machines.

**Comment by canton7** [comment] 2016-01-22 11:34
Can you capture logs with `STTRACE=dialer` set for a longer period of time, and also post the logs from your router for the same period of time?

The `STTRACE=dialer` logs only last for a few minutes, and most of those as Syncthing starting up: it's impossible to say what it's doing once it's finished starting.

Being able to correlate entries in the `STTRACE=dialer` log and in your router's log would also be very useful.

**Comment by bluewavenet** [comment] 2016-01-22 11:48
As I posted earlier, the result of setting STTRACE=dialer :
Jan 21 12:57:53 linux-8nro syncthing[21342]: [KZINF] DEBUG: Dialer logging disabled, as no proxy was detected.

**Comment by canton7** [comment] 2016-01-22 11:49
Ah, my bad, I misread the context of the log you posted earlier.

Replace "dialer" with "discover" in my previous message.

**Comment by bluewavenet** [comment] 2016-01-22 11:50
"It looks like Syncthing is asking the OS for the A records for domains with only AAAA records, and for AAAA records for domains with only A records."
**Why is it doing this?**

**Comment by canton7** [comment] 2016-01-22 11:52
Less shouty, please :smile: 

On further investigation, it's your OS doing those lookups, not Syncthing. Syncthing is asking `getaddrinfo` "give me an address for this domain name", and your OS is kicking off both A and a AAAA record lookups.

**Comment by bluewavenet** [comment] 2016-01-22 12:00
There is an issue resolving the discovery servers that is not local to my internet feed/router. I have now tried on various connections including hotspots and mobile data. DNS queries seem to often fail, but not always - I am talking about only the discovery servers here, not DNS in general. For example:
linux-8nro:/home/rob # ping discovery-v6-3.syncthing.net
ping: unknown host discovery-v6-3.syncthing.net
linux-8nro:/home/rob # nslookup discovery-v6-3.syncthing.net
Server:		192.168.1.254
Address:	192.168.1.254#53

Non-authoritative answer:
*** Can't find discovery-v6-3.syncthing.net: No answer

**Comment by canton7** [comment] 2016-01-22 12:01
Could you please provide the information I'm asking for?

`discovery-v6-3.syncthing.net` only has an AAAA record: if your host doesn't have IPv6, it's not going to bother looking that record up.

**Comment by AudriusButkevicius** [comment] 2016-01-22 12:07
So syncthing reconnects to each disconnected device every minute by default.
Reconnecting involves performing discovery lookups. In the case discovery returns no results, that fact is cached for 5 minutes. If we fail to look up, we don't try again for 1 minute. Given there are 6 discovery server addresses (3xv4, 3xv6) and we lookup both A and AAAA for all of them (because we access via http and have to ask both of the questions), that's effectively 12 requests per minute per syncthing device in the network, which is nowhere excessive, unless you have hundreds of devices.

Most of the calls should be absorbed by the OS cache (we don't do anything fancy, just using a use the standard library to access a webpage).
If it's a bug, it's a bug in the Go standard library, if not a bug, then your OS is not going a proper job of caching.



That is nowhere excessive.

**Comment by canton7** [comment] 2016-01-22 12:13
It's 12 requests per minute, per syncthing device in the network, per disconnected device, surely?

One thing I'm looking for in those `discover` logs is how many devices it's looking for. He's averaging about one lookup every 20 seconds per discovery server per syncthing device on the network.

**Comment by AudriusButkevicius** [comment] 2016-01-22 12:14
Which is correct, it doesn't know if AAAA or A exists until it asks.

**Comment by canton7** [comment] 2016-01-22 12:18
... assuming there are three disconnected devices, I think?

He should be getting one lookup per discovery server per record type per minute (if I understood you correctly), and he's getting three a minute. I think 3 disconnected devices is the best explanation?

**Comment by bluewavenet** [comment] 2016-01-22 12:24
Thanks @AudriusButkevicius 
Perhaps the title of this should be "Potentially Excessive..."
To put this into context, I have tested previously on 10 machines each running 10 instances(one for each of 10 users) and syncthing worked perfectly, enabling the 10 people in the office to hotdesk as well as randomly choose a laptop to take on the road or home. So that is 100 instances all running at the same time or 1200 requests per minute. During this test I did not think to look at the router as I was only concerned with the performance of syncthing.

**Comment by bluewavenet** [comment] 2016-01-22 12:27
With multiple instances per machine, IPv6 is required for local discovery. In the UK at least, most ADSL internet connections do not support IPv6.

**Comment by canton7** [comment] 2016-01-22 12:29
Doing the IPv6 lookups (as with the IPv4 lookups) *should be* incredibly cheap: we hit the OS cache, and it returns "no result" in a tiny fraction of a second. So cheap that there's no point in trying to avoid doing them.

**Comment by AudriusButkevicius** [comment] 2016-01-22 12:38
An application or even a set of applications can perform as many DNS requests as they want, and it's supposed to be amortized by the OS and the caching mechanisms that DNS as a protocol provides.

I am inclined to close this as invalid, as it's not our fault, it's your OS fault or even your routers fault for not caching the fact that there is no v4 or v6 address for that given hostname, which it is supposed to according to https://tools.ietf.org/html/rfc2308

**Comment by canton7** [comment] 2016-01-22 12:39
I had a bit of a perusal through the Go source, and it looks like there are situations (cgo not available?) where it will reach out directly to the servers configured in `/etc/resolv.conf` instead of calling `getaddrinfo`...?

**Comment by bluewavenet** [comment] 2016-01-22 12:40
@canton7 Yes, however the default negative TTL in nscd is "0". ie the negative query is not cached. Sure I can set this to something other than zero, but that could have a knock on effect for any other applications on the box, for example if the adsl goes down briefly at the moment a query is made etc.

Anyway - here is a 6+ hour discovery log: 
[syncthingdebug.txt](https://github.com/syncthing/syncthing/files/100762/syncthingdebug.txt)

**Comment by canton7** [comment] 2016-01-22 12:42
Cool, it's doing one lookup per device per minute, as it's supposed to.

**Comment by bluewavenet** [comment] 2016-01-22 12:46
True, but this is just the log for one instance on that machine. It is running two instances so the router sees twice as many. There is another machine on at the moment also running two instances, so the router sees four times as many.

**Comment by AudriusButkevicius** [comment] 2016-01-22 12:47
Ok, but still, half of these are supposed to be cached by the OS.

**Comment by bluewavenet** [comment] 2016-01-22 12:49
Not by default. And it is a default of nscd. Like I said, I can change it, but that is not desirable for other applications on the box.

**Comment by canton7** [comment] 2016-01-22 12:49
You said it doesn't cache *failed* lookups by default, which means it should still cache *successful* lookups...

**Comment by bluewavenet** [comment] 2016-01-22 12:50
It does  cache successful lookups with a 600 second TTL.

**Comment by canton7** [comment] 2016-01-22 12:51
> Ok, but still, atleast half of these are supposed to be cached by the OS.

Your OS *isn't* caching them - see your router's logs. We're wondering why...

**Comment by bluewavenet** [comment] 2016-01-22 13:07
Here is a sample log from nscd
[nscdlog.txt](https://github.com/syncthing/syncthing/files/100791/nscdlog.txt)

**Comment by canton7** [comment] 2016-01-22 13:16
It's odd that it's only logging about `discovery-v4-3.syncthing.net`...

**Comment by bluewavenet** [comment] 2016-01-22 13:32
Perhaps someone can change the name of this to "Potential for Excessive DNS requests". I don't think I can...

**Comment by AudriusButkevicius** [comment] 2016-01-22 13:50
So I don't think there is anything for us to do here, can I close this?

**Comment by canton7** [comment] 2016-01-22 14:08
The slightly-open question in my mind is whether Go is using `getaddrinfo` or doing things manually. After his last nscd log I'm about 90% sure Go is using `getaddrinfo`, but there's still a question over why nscd isn't looking lookups for the other discovery servers.

**Comment by bluewavenet** [comment] 2016-01-22 14:44
Like I said, it is a potential issue. Something somewhere is not quite right. As it stands I might have a problem getting it past the Network Support people in a large rollout. When I get time I will investigate further.

**Comment by AudriusButkevicius** [comment] 2016-01-22 15:42
I am closing this, as I don't think we are the suspect here. @calmh can reopen if he thinks otherwise.

**Closed by AudriusButkevicius** 2016-01-22 15:42 UTC

**Comment by bluewavenet** [comment] 2016-01-22 17:16
Thanks everyone for input. I will report back if I find anything more on the subject :)
