### ISSUE TITLE
Device list display broken in Advanced settings

### ISSUE THREAD

**Issue by greatroar** [syncthing/syncthing#6685] opened 2020-05-27 09:03 UTC
In the GUI, click Actions, Advanced, then select a folder and look at the Devices field.

On all my devices, all folders display something like

    [object Object], [object Object]

Looks like a JavaScript serialization bug.

Syncthing 1.6.0-rc5; also current master. Happens in both Firefox and Chromium.

**Comment by calmh** [comment] 2020-05-27 09:07
Duplicate of #4569

**Closed by calmh** 2020-05-27 09:07 UTC
Labels: bug, needs-triage
