### ISSUE TITLE
WebUI table column widths broken on narrow displays

### ISSUE THREAD

**Issue by merlinuwe** [syncthing/syncthing#5774] opened 2019-06-10 13:36 UTC
The interface is broken since the latest release
Start it and see it (reproducable)
Version Information

App Version: 1.1.4.1
Syncthing Version: v1.1.4
Android Version: Android 9
Device manufacturer: Honor

![Screenshot_20190608_090240_com github catfriend1 syncthingandroid](https://user-images.githubusercontent.com/4138869/59199041-50976d80-8b95-11e9-9c63-c816d7a84b95.jpg)
![Screenshot_20190608_090159_com github catfriend1 syncthingandroid](https://user-images.githubusercontent.com/4138869/59199045-52613100-8b95-11e9-80f2-94f42a34906e.jpg)
![Screenshot_20190608_090230_com github catfriend1 syncthingandroid](https://user-images.githubusercontent.com/4138869/59199053-53925e00-8b95-11e9-9309-4e994a694b00.jpg)

I use syncthing-fork, catfried1 asked me to place this issue here.

**Comment by imsodin** [comment] 2019-06-10 14:10
I think the right thing to do below a certain display width is to display everything in one column, i.e. the data below the label instead of next to each other. Now some CSS/JS/HTML-knowledgeable person needs to figure out how to do that :)

**Comment by AudriusButkevicius** [comment] 2019-06-10 17:52
Not reprodu

**Comment by AudriusButkevicius** [comment] 2019-06-10 17:53
Not reproducible on my device. I guess it's just a device with very low screen reaolution?

**Comment by AudriusButkevicius** [comment] 2019-06-10 18:08
Actually. I am closing this. Android has a UI. Web UI is somewhat an escape hatch, but there is nothing we can do to accommodate these tiny screens I think. Perhaps it's zoomed in and try opening 127.0.0.1:8384 in normal phone browser and zoom out. Worst case this should be in a different repo as its android specific.

**Comment by merlinuwe** [comment] 2019-06-10 18:14
Here is the resolution:
the Honor 10  was the flagship of honor.

Display | Type | IPS LCD capacitive touchscreen, 16M colors
-- | -- | --
Size | 5.84 inches, 85.1 cm2 (~79.9% screen-to-body ratio)
Resolution | 1080 x 2280 pixels, 19:9 ratio (~432 ppi density)

**Comment by AudriusButkevicius** [comment] 2019-06-10 18:17
I suspect you are somehow zoomed in.

**Comment by calmh** [comment] 2019-06-10 18:25
There probably is some sort of zooming involved, or that browser is weird.

The problem is there, but at smaller point widths. Looking at something iPhone 5 sized (320x568, the smallest predefined actual device in my responsive testing thing), it's sort of crappy but not as bad as in the above:

<img width="339" alt="Screen Shot 2019-06-10 at 20 23 16" src="https://user-images.githubusercontent.com/125426/59217161-a41db180-8bbd-11e9-87c4-6adc84a07416.png">

Manually dragging things down to 250-260 pixels wide really makes things fall apart:

<img width="278" alt="Screen Shot 2019-06-10 at 20 24 15" src="https://user-images.githubusercontent.com/125426/59217244-cca5ab80-8bbd-11e9-81b3-e625ab3be20a.png">

But at that point we're talking about so tiny screens that I'm not sure there is much to do.

**Comment by merlinuwe** [comment] 2019-06-10 18:29
I switched it back to normal. Now I see a little bit more of the letters. The problem occured with the latest release, even with everything set to "Normal" or "Standard".

![grafik](https://user-images.githubusercontent.com/4138869/59217417-31610600-8bbe-11e9-8cbe-9fd49825caa8.png)

**Comment by merlinuwe** [comment] 2019-06-10 18:34
![grafik](https://user-images.githubusercontent.com/4138869/59217647-b2b89880-8bbe-11e9-893c-40f76137a93a.png)

The text of the devices appear ok.

![grafik](https://user-images.githubusercontent.com/4138869/59217781-032ff600-8bbf-11e9-90df-3b7cb30cbbed.png)

**Comment by calmh** [comment] 2019-06-10 18:35
Yeah, there's two problems here. Or, well, three. One, the balance of column widths plus ellipsis overflow is Really Hard(tm) to get right in css. Two, there was some zoom going on. Three, German. There's no way to line break those headers in the left column. :/

**Comment by calmh** [comment] 2019-06-10 18:44
I'm going to let this one live, on the off chance that someone finds a way to make this more elegant.

**Comment by merlinuwe** [comment] 2019-06-10 18:46
"Reihenfolge" instead of "Dateiübertragungsreihenfolge" would be shorter and stays understandable in this context.

(I wear glasses...)

**Comment by calmh** [comment] 2019-06-10 18:47
I'm starting to get over 40 and holding my phone at arms length, so not judging. ;)

Probably it would be good to tweak down the length of or even abbreviate some of the column labels.

**Comment by merlinuwe** [comment] 2019-06-10 18:51
That's the real reason, why selfiesticks exist. ;-) I'm 55. Thanks for reopening. If you need some more german abbreviaitions, don't hestitate to ask me.

**Comment by wweich** [comment] 2019-06-11 15:54
I have an idea how to display the table columns below each other and will try to dinf time to put together a PR in the next few days.

Setting the display size in Android will effect the `@media` width, so setting this to a higher value will result in a narrower screen.
But setting the font size somehow does effect the Syncthing-Android WebView but not the "normal" Chrome. So I can't test how I could detect that and put the columns below each other even though they should fit with the current screen width.

**Comment by AudriusButkevicius** [comment] 2019-06-11 17:44
Doesn't chrome have a super duper screen simulator built in?

**Closed** 2019-06-17 12:24 UTC
Labels: enhancement
