### ISSUE TITLE
Files with invalid file names should fail louder

### ISSUE THREAD

**Issue by BethAr** [syncthing/syncthing#3012] opened 2016-04-26 06:37 UTC
*Edit by calmh because tl;dr:* Files with invalid characters in the file name are dropped from incoming updates. With a warning, but that warning goes away and then the device looks happy in the GUI. Instead, we should accept the invalid files into the index, display a non-100% sync status, and warn repeatedly (every pull iteration, unless we do something else?).

----

Hello,

I have a Linux (Mint 17.3) machine synching a backup folder to a Windows 7 computer. I thought the backup was running correctly for a couple of months, but when I had to format I found out many files never arrived at the Windows machine.

Obviously the problem was Windows stupid filepath limitation, but I was a bit scared that Syncthing didn't warn me in any way that some files were never synched. The fact that it told me all that time that the folder was _up to date_ is very unnerving.

I would like to request some sort of warning when this happens. The folder on the Linux machine was set as a master folder, and no file was ever added to the Windows machine's folder manually, so it should tell me that there were files missing on the other end, not that the folder was up to date.

I can't specify the version because I went through several Syncthing updates in that time.

Thank you.

**Comment by calmh** [comment] 2016-04-26 07:13
That sounds very odd indeed. It will fail to sync filenames that can't be represented on windows, but it does so quite loudly and and gets visibly stuck in "out of sync". Not showing an error and looking "up to date" is surprising - can you reproduce this?

**Comment by AudriusButkevicius** [comment] 2016-04-26 07:20
So I think we should close this, atleast until steps of reproduction have been provided, because this is based on some old memories of some old version, which might not even be relevant anymore.

**Comment by calmh** [comment] 2016-04-26 07:35
I don't think we've *ever* behaved as the OP describes, or I hope so, so I would like at least some comments on this before closing. Perhaps it's reproducible.

**Comment by BethAr** [comment] 2016-04-26 21:22
Ok,

The last version that was installed on the machine was v0.12.21, and I noticed the problem just last week, so it isn't old. I don't know which version I started with, but I know the dates, so maybe you can tell.

Here is my setup in more detail. It began like this:

**Source machine**
HP Pavillion g4 notebook running Windows 7 Professional x64.
Installed Syncthing on 2016-01-20 (I know because I mailed me the ID)
3-4gb backup folder set as Master: C:\Beta\Backup
320gb Samsung HDD, single NTFS partition.
Running Avast antivirus.

**Target machine**
Dell desktop running WIndows 7 Professional x64.
Installed Syncthing on 2016-01-20 (same day)
Folder synched to: F:\Apoio\Beta\Backup
1.5tb Western Digital Caviar Green HDD, 460gb NTFS partition.
Running Panda antivirus.

It operated like this until February, then I migrated the Source machine to Linux:

**Source machine**
HP Pavillion g4 notebook running Linux Mint 17.3.
Installed Syncthing on 2016-02-15
3-4gb backup folder set as Master: \home\beta\Backup
320gb Samsung HDD, 286gb ext4 partition.

The Target machine remained the same until last week, when I decided to migrate it to Linux as well. Then I begin sorting the backup out to prepare for formatting, and I noticed the files were missing. There were 32 .mp3 files, and 12 .docx files. I then copied them with a thumb drive, but the copy failed because of filepath limitations, and I noticed that the files had very long names.

**Additional information**
The computers are synched through the internet, they are rarely together in a LAN, because the notebook stays at my workplace.

I never got an Out of Sync error for my Backup folder, regardless if the Source machine was running Windows or Mint. I did get Out of Sync errors for other folders, and they happened because I tampered with them, like deleting files on the Target side, but I never messed with the Backup.

On all Windows machines I was running the SyncTrayzor client with Syncthing. When I switched to Linux I used Syncthing just with the Web UI.

**Comment by AudriusButkevicius** [comment] 2016-04-26 21:33
The other reason they could be ignored is because they had invalid characters in their names (such as `:` which is not valid on Windows), but I am sure it would look out of sync in that case.

Regardless, until there are steps on how to reproduce this (especially given you already have the files which you think cause problems), this is all vapor.

**Comment by BethAr** [comment] 2016-04-26 22:46
Very well, I just reproduced it. I don't have the Mint machine here, so I used this one as Source:

Lenovo 3000 n200 running Manjaro/Xfce 15.12
Syncthing v0.12.21
Source folder set as Master at: /home/beta/Teste
80gb Hitachi HDD, 50gb ext4 partition.

Target is the same as above.
Target folder: F:\Apoio\Beta\Teste

**Results**
If I add a file with a very long name (255 chars), I get _no errors_. The file arrives at the target, and I can't do nothing with it there. Windows will scrub it with chkdsk later, if I recall.

If add a file with either a `:` or `?` in the name, I do get a warning at the Target machine, but I get no errors at the Source machine, and even though the file _never_ arrived at the Target, it still reports the folder as Up to Date.

I only got an error reported at the Source machine (Out of Sync error) from a invalid filename, when I added a file with a `\` in the name, which arrived as a folder in the Target. Overriding the folder with the red button did nothing, I had to delete it manually to sort things out.


So the issue stands: I get no warning that there was a problem at the Target, even though the Source is set as Master. I had to RDP into the Target machine, which runs headless, and open up a browser to see the problems.

**Comment by AudriusButkevicius** [comment] 2016-04-26 23:04
So you are saying the file does arrive.
The fact that you can't do anything with it or the fact that chkdsk decides to nuke it is not really our fault.

From our perspective, I believe syncthing has delivered what it has promised to do, which is getting the file there, so from it's perspective everything is there and up to date.

**Comment by BethAr** [comment] 2016-04-26 23:07
The file does not arrive iif it has an invalid character, and the Source still thinks it is up to date.

**Comment by AudriusButkevicius** [comment] 2016-04-26 23:11
it thinks it's up to date, but not the other side. It's up to date from the perspective of what it can get.

**Comment by BethAr** [comment] 2016-04-26 23:14
Oh come on!

Make a folder and add a single file with a `:` at the name. It will never get to the Target. See if the Source will report any errors. It will even say it has 1 file synched. This is a blatant lie!

**Comment by AudriusButkevicius** [comment] 2016-04-26 23:21
So I will try that, but that's not what the initial ticket reports.
The ticket reports about files with long paths.

**Comment by BethAr** [comment] 2016-04-26 23:23
The problem Is even worse, if for some reason Syncthing stops at the Target, and then restarts (power loss, for instance) it won't even report the error, the Target will say it is Up to Date as well. So not even the Target reports it correctly.

You are right, I'm unable to reproduce the errors I faced. I believe they are related to long paths, and I will continue to test it.

Meanwhile, I've changed the issue title.

**Comment by AudriusButkevicius** [comment] 2016-04-26 23:32
So not sure what you mean by silently, given you are clearly warned?

**Comment by AudriusButkevicius** [comment] 2016-04-26 23:34
Also, I am inclined to close as duplicate, given we have https://github.com/syncthing/syncthing/issues/1734

**Comment by BethAr** [comment] 2016-04-26 23:39
How am I warned? The Source machine, the one where the folders is set to Master, never reports it, never becomes Out of Sync.

The Target may report it, but what if it is a NAS, or is run headless like my case? If you don't look at it at the right time, you are lost.

**Comment by AudriusButkevicius** [comment] 2016-04-26 23:40
So I will double check that, but it should not reach 100% completion.

**Comment by BethAr** [comment] 2016-04-27 00:59
I would like to add that with long file names you get absolutely no warning on either side. The files arrive there, sure, but what is the point?

**Comment by canton7** [comment] 2016-04-27 06:01
Regarding long file names,the story is actually more complex than it seems. They are supported by NTFS and by certain parts of windows. Other parts of windows (which use older sections of the winapi) fail to handle them correctly. 

Syncthing is an application which correct handles long paths. The fact that you then tried to use applications which can't handle long paths is not Syncthing's fault. 

I can't find any sources which indicate that chkdsk will remove long paths, and given that they're perfectly valid on NTFS I would be extremely surprised if it did.

**Comment by calmh** [comment] 2016-04-27 06:05
I'm confused. On long file names:

> I would like to add that with long file names you get absolutely no warning on either side. The files arrive there, sure, but what is the point?

We sync these files correctly. I see no issue here?

On file names that are not valid on the destination:

> How am I warned? The Source machine, the one where the folders is set to Master, never reports it, never becomes Out of Sync.
> The Target may report it, but what if it is a NAS, or is run headless like my case? If you don't look at it at the right time, you are lost.

The target (receiver) does log a warning pop one up in the GUI, and on the other side it should be reported as less than 100% in sync. It's not the source/master side that has the problem, so *it* will not display as "out of sync".

Is this not the case?

**Comment by wweich** [comment] 2016-04-27 06:30
I can reproduce the invalid character problem.
I created a file `test: 1.txt` on Linux and tried to sync it to Windows. It is not synced and there is a notice `File name "test: 1.txt" (folder "***") contains invalid characters; marked as invalid.` This is expected.
But what's not expected is, that now everything is displayed as up to date, folder and device on both sides. But the Windows side has one item less in both local and global state.

It seems that incoming invalid items are not added to the global state.

_Restarting the nodes and rescanning several times did not change anything._

Source (Linux):
![unbenannt1](https://cloud.githubusercontent.com/assets/1026763/14843571/abc8ba7c-0c51-11e6-9d72-66574f067f18.png)
Destination (Windows 7 64Bit):
![unbenannt2](https://cloud.githubusercontent.com/assets/1026763/14843577/b8bac658-0c51-11e6-9f35-e3622569a761.png)

_I also checked the long file/path name, and as @canton7 already said, Windows 7 / NTFS can handle long file names, but some Software (e.g. Office 2007 cannot)._

**Comment by calmh** [comment] 2016-04-27 11:45
Was the file 0 bytes large? I could see that causing the above output, as the destination is missing 0 bytes of data (i.e. it's in sync). Otherwise, that is a clear bug - it should show as "Syncing (99%)" or something from the Linux side.

**Comment by AudriusButkevicius** [comment] 2016-04-27 23:17
Results of my isolated test:
![image](https://cloud.githubusercontent.com/assets/1144861/14870968/277d09fa-0cd6-11e6-9cba-b380587530f7.png)

**Comment by calmh** [comment] 2016-04-28 06:11
Yes, that's what I expect. I think you can trick our in sync calculation with zero byte files (maybe we should add a constant "ovhead" per file for calculation purposes, as we do with deleted files), but otherwise this seems "functions as designed" to me.

If there's something we should improve in that design I'm open to hearing it, but it's not immediately clear to me what that is.

**Comment by AudriusButkevicius** [comment] 2016-04-28 07:18
So I did notice that the completion % was skewed for an old test folder which had a lot of cruft in the index (it was showing 86% completiom for one of two failed files of same size) but I couldn't repro it after removing and readding it.

**Comment by AudriusButkevicius** [comment] 2016-04-28 07:20
So perhaps we should not drop the items from the index, but accept them and just show them out of sync?

**Comment by calmh** [comment] 2016-04-29 14:41
We need to skip handling them at a later stage in that case, or we'll spam the logs with complains about failed creates and stuff.

**Comment by AudriusButkevicius** [comment] 2016-04-29 14:44
Yeah, thats what I mean. Essentially fail the items immediately, and exclude them from the pull loop.

**Comment by calmh** [comment] 2016-05-01 07:22
Ok, clarifying the ticket.

**Closed** 2016-08-05 07:13 UTC
Labels: enhancement
