### ISSUE TITLE
puller: Stale .syncthing.tmp files left behind

### ISSUE THREAD

**Issue by shodanshok** [syncthing/syncthing#2725] opened 2016-01-23 15:03 UTC
Hi, I have a possible issue with stale temporary files (.syncthing.*.tmp) left behind.

Let's start with a very simple scenario: two fileservers (L and R) with an empty, to-be-synched dir at path `/opt/fileserver/test/`. I've started syncthing on both server and added the relative folder via webgui. Folder rescan time is at 5 seconds. The `/opt/fileserver/test/` directory is shared, on both server, to a Windows7 machine via Samba.

Then, I executed the following command to copy something  into the synched dir:
`cp -a /tmp/dir/ /opt/fileserver/test/`. After some seconds the files were synchronized:

<pre>
[root@master test]# ls -alR
.:
total 12
drwxr-xr-x. 3 root root 4096 Jan 23 15:39 .
drwxr-xr-x. 6 root root 4096 Jan 22 11:41 ..
drwxr-xr-x. 2 root root 4096 Jan 23 15:03 dir
-rw-r--r--. 1 root root    0 Jan 22 11:41 .stfolder

./dir:
total 262152
drwxr-xr-x. 2 root root      4096 Jan 23 15:03 .
drwxr-xr-x. 3 root root      4096 Jan 23 15:39 ..
-rw-r--r--. 1 root root 268435456 Jan 23 15:03 disk.img
[root@master test]#

[root@slave test]# ls -alR
.:
total 12
drwxr-xr-x. 3 root root 4096 Jan 23 15:39 .
drwxr-xr-x. 6 root root 4096 Jan 22 11:41 ..
drwxr-xr-x. 2 root root 4096 Jan 23 15:39 dir
-rw-r--r--. 1 root root    0 Jan 22 11:41 .stfolder

./dir:
total 125068
drwxr-xr-x. 2 root root      4096 Jan 23 15:39 .
drwxr-xr-x. 3 root root      4096 Jan 23 15:39 ..
-rw-r--r--. 1 root root 268435456 Jan 23 15:03 disk.img
</pre>

So far, so good. Then, from the Win7 machine (via Explorer), I did the following operations:
1) on L server, move dir/disk.img to ../disk.img and wait for the change to propagate to R
2) on R server, move disk.img to dir/disk.img and wait for the change to propagate to L
3) on L server, move dir/disk.img to ../disk.img and wait for the change to propagate to R

After point n.3, I see a temporary .syncthing.disk.img.tmp hanging on R server (see screenshot1.png also).

<pre>
[root@master test]# ls -alR
.:
total 262160
drwxr-xr-x. 3 root root      4096 Jan 23 15:41 .
drwxr-xr-x. 6 root root      4096 Jan 22 11:41 ..
drwxr-xr-x. 2 root root      4096 Jan 23 15:41 dir
-rw-r--r--. 1 root root 268435456 Jan 23 15:03 disk.img
-rw-r--r--. 1 root root         0 Jan 22 11:41 .stfolder

./dir:
total 8
drwxr-xr-x. 2 root root 4096 Jan 23 15:41 .
drwxr-xr-x. 3 root root 4096 Jan 23 15:41 ..
[root@master test]#

[root@slave test]# ls -alR
.:
total 250136
drwxr-xr-x. 3 root root      4096 Jan 23 15:41 .
drwxr-xr-x. 6 root root      4096 Jan 22 11:41 ..
drwxr-xr-x. 2 root root      4096 Jan 23 15:41 dir
-rw-r--r--. 1 root root 268435456 Jan 23 15:03 disk.img
-rw-r--r--. 1 root root         0 Jan 22 11:41 .stfolder
-rw-r--r--. 1 root root 268435456 Jan 23 15:41 .syncthing.disk.img.tmp

./dir:
total 8
drwxr-xr-x. 2 root root 4096 Jan 23 15:41 .
drwxr-xr-x. 3 root root 4096 Jan 23 15:41 ..
[root@slave test]#
</pre>

Interesting, I am not able to replicate the issue in the reverse direction (with an hanging temporary file on L). From my tests, I discovered that setting keepTemporariesH to 0 prevent the problem, but I am not sure this is the ideal solution.

My understanding is that temporary files are kept only when the transfer does not complete, and this is clearly not the case. So, I wonder:
1) why temporary files are kept in this case
2) what I can do to correctly prevent/solve the problem.

Thank you.
![screenshot1](https://cloud.githubusercontent.com/assets/13137622/12530789/899c4a2e-c1ea-11e5-9df3-04933be8f04f.png)
![screenshot2](https://cloud.githubusercontent.com/assets/13137622/12530791/89a1168a-c1ea-11e5-8540-30059fcc8801.png)
![screenshot3](https://cloud.githubusercontent.com/assets/13137622/12530790/899e8c12-c1ea-11e5-914a-d161dd3e7f65.png)

**Comment by AudriusButkevicius** [comment] 2016-01-23 15:28
It's kept when it's not complete, or the transfer got interrupted due to other reasons (file changed for example).

These get cleaned up after 12 (or 24) hours anyway.

**Comment by AudriusButkevicius** [comment] 2016-01-23 15:31
Also, check if the file is not sparse, as it might be.

**Comment by shodanshok** [comment] 2016-01-23 17:49
True, but the transfer was not unsuccessful nor interrupted. It went ok (and md5sum confirms).
The file was not a sparse one, it was fully allocated.
I understand that tmp files are going to be deleted the first scan after keepTemporariesH expired, but I wonder *why* they are not removed upon successful transfer in the first place...

**Comment by AudriusButkevicius** [comment] 2016-01-23 18:00
Well they are, as they are essentially renamed into place, and not copied. You have to provide steps that reproduce this reliably, as I don't think amyone wants to go for a witch hunt trying to answer why.

**Comment by shodanshok** [comment] 2016-01-23 18:17
> they are essentially renamed into place, and not copied

This is exactly the reason I am surprised. Apart using `--verbose`, what else can I do to track down the issue? I can provide inotify-level events. Can they be useful?

Thanks.

**Comment by calmh** [comment] 2016-01-23 18:30
I'm also slightly confused about how this happens, but on the other hand I've already rewritten this code for merging in v0.13, so I don't think investigating this too deeply is valuable at this point.

**Comment by shodanshok** [comment] 2016-01-23 20:04
Oh, I agree.
For pure curiosity, I tracked what happens at filesystem level via inotify. In both cases, I moved a file from `/opt/fileserver/test/disk.img` to `/opt/fileserver/test/dir/disk.img`

NO .TMP FILE LEFT (or created):
<pre>
MOVED_FROM:/opt/fileserver/test/dir/:/opt/fileserver/test/dir/disk.img:/opt/fileserver/test/dir/disk.img:
MOVED_TO:/opt/fileserver/test/:/opt/fileserver/test/disk.img:/opt/fileserver/test/disk.img:
MOVE:/opt/fileserver/test/:/opt/fileserver/test/dir/disk.img:/opt/fileserver/test/disk.img:
</pre>

STALE .TMP:
<pre>
CREATE:/opt/fileserver/test/dir/:/opt/fileserver/test/dir/.syncthing.disk.img.tmp:/opt/fileserver/test/dir/.syncthing.disk.img.tmp:
CLOSE_WRITE:/opt/fileserver/test/dir/:/opt/fileserver/test/dir/.syncthing.disk.img.tmp:/opt/fileserver/test/dir/.syncthing.disk.img.tmp:
MOVED_FROM:/opt/fileserver/test/:/opt/fileserver/test/disk.img:/opt/fileserver/test/disk.img:
MOVED_TO:/opt/fileserver/test/dir/:/opt/fileserver/test/dir/disk.img:/opt/fileserver/test/dir/disk.img:
MOVE:/opt/fileserver/test/dir/:/opt/fileserver/test/disk.img:/opt/fileserver/test/dir/disk.img
</pre>

As you can see, the temporary file was created *but not used*, as the `/opt/fileserver/test/disk.img` was directly moved to the new location.

So, you confirm this is not the expected behavior?
Thanks.

**Comment by calmh** [comment] 2016-01-24 07:00
Yeah, that's a bug.

**Comment by calmh** [comment] 2016-01-24 07:01
To be fixed by #2540

**Comment by lkwg82** [comment] 2016-05-04 21:52
@shodanshok Would be nice if you can check after 0.13 release again.

**Comment by calmh** [comment] 2016-05-05 05:47
Unfortunately my changes that would possibly fix this won't make it into v0.13, so no. But we'll get there.

**Comment by meonkeys** [comment] 2017-11-20 22:32
Is this still open? I don't think I am seeing a repro but it would be nice to rule out this bug. I'm on v0.14.40. If this is still open I'll try to get a clean room repro and report back.

**Comment by AudriusButkevicius** [comment] 2017-11-20 22:38
Temp files are kept around for 24 hours (by default) for reuse in case the download broke and we need to restart.
If you have files older than that, then it could be an issue, yet we'd still need a repro.

**Comment by lkwg82** [comment] 2018-02-04 16:37
@shodanshok Have you seen it again?

**Comment by shodanshok** [comment] 2018-02-04 21:16
@lkwg82 I am not using synchthing reguarlarly, so I can not answer your question right now... sorry.

**Closed** 2018-02-04 22:01 UTC
Labels: bug
