### ISSUE TITLE
Joining relay session (BEP/relay): Incorrect response code 1: not found

### ISSUE THREAD

**Issue by andrewufrank** [syncthing/syncthing#3272] opened 2016-06-07 05:15 UTC
running 13.4. i see regularly the error message 
Joining relay session (BEP/relay): Incorrect response code 1: not found

or
Joining relay session (BEP/relay): Incorrect response code 2: already connected

It appears since moving to 13, i never saw it running 12.x before. 

what is the cause? what can be done to fix it? 
thank you!

**Comment by AudriusButkevicius** [comment] 2016-06-07 07:24
Do you know which relay that happens with?

**Comment by calmh** [comment] 2016-06-07 07:26
I guess this is when the discovery server says a device is connected to a certain relay, but they are in fact not? We only remove those entries by time out, which can be a while I think?

**Comment by AudriusButkevicius** [comment] 2016-06-07 07:29
I'd have to check the code, but this is joining the session, rather than getting an invitation.

**Comment by andrewufrank** [comment] 2016-06-07 08:31
i find in the syslog:
`Jun  7 10:01:45 almeria syncthing[11419]: [xxx] WARNING: Joining relay session (BEP/relay): Incorrect response code 1: not found
Jun  7 10:01:45 almeria syncthing[11419]: [xxx] INFO: Disconnected from relay relay://195.154.113.77:22067
Jun  7 10:01:46 almeria syncthing[11419]: [xxx] INFO: Joined relay relay://134.119.8.239:22067
`
does this help?

**Comment by scienmind** [comment] 2016-06-07 09:18
The same story as I discussed here here: https://forum.syncthing.net/t/using-relays-periodically-generates-notice-messages/7550/9.

I still think there is more to it then just "one especially bad internet connection"...

**Comment by AudriusButkevicius** [comment] 2016-06-07 09:38
This is something elset though. I need to look at the code not from the phone though

**Comment by scienmind** [comment] 2016-06-07 10:12
The `Joining relay session (BEP/relay): Incorrect response code 2: already connected` I talked about in the forum is the most frequent one, but occasionally, since v.0.13 I"m getting those as well:
`Joining relay session (BEP/relay): EOF`
`Joining relay session (BEP/relay): Incorrect response code 1: not found`
`Joining relay session (BEP/relay): Incorrect response code 2: already connected`
`Joining relay session (BEP/relay): dial tcp P:PORT: connectex: An established connection was aborted by the software in your host machine.`
`Joining relay session (BEP/relay): dial tcp IP:PORT: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.`

**Comment by AudriusButkevicius** [comment] 2016-06-07 10:13
All of them apart from the second one is a sign of shit internet.

**Comment by AudriusButkevicius** [comment] 2016-06-07 19:30
So `already connected` can happen if both sides happen to connect at virtually the same time, and the relay happens to be running on a weak machines. Essentially this: 
https://github.com/syncthing/syncthing/blob/master/cmd/relaysrv/session.go#L125
default case should be replaced with some sort of timeout.

The `not found` can potentially be caused by a misconfigured relay with a very short session timeout or a slow connecting node, which happens to take a while (long while) to connect to the relay, by which time the session has already timed out.

I do not think any of these are fatal, and should resolve themselves in 10 or so minutes.

I do not think there was any fundamental behavioural changes in 0.13 that could potentially be to blame, yet the network the relays has expanded quite a lot recently, potentially on-boarding funky relays which cause these things that you observe.

**Comment by andrewufrank** [comment] 2016-06-08 06:57
thank you for your very instructive explanation indicating that i need not worry (except for the quality of my internet provider, but there is limited choice). in general, it would be best if the GUI shows only information which needs action by the user and perhaps even indicates what should be done.

**Comment by AudriusButkevicius** [comment] 2016-06-08 07:08
This was already addressed by @scienmind

**Closed by AudriusButkevicius** 2016-06-08 07:08 UTC
