### ISSUE TITLE
Sync extended file attributes on supported file systems

### ISSUE THREAD

**Issue by lockedshadow** [syncthing/syncthing#2698] opened 2016-01-15 23:40 UTC
For now, Syncthing is not preserve extended file attributes (xattrs) when sync, as says in FAQ. But some tagging engines for Linux (such as Baloo, former Nepomuk from KDE) stores metainformation (tags, comments, ratings etc.) exactly in xattrs, therefore this metainfo are not synchronized across the cluster. Maybe is possible to add optional feature to sync xattrs across nodes, if file system supports it?

Some (possibly) related articles:
https://en.wikipedia.org/wiki/Extended_file_attributes#Linux
https://community.kde.org/Baloo/Architecture

P.S. I apologise for my very bad english. Hope that you can understand me.

**Comment by AudriusButkevicius** [comment] 2016-01-15 23:58
I am pretty sure it's a duplicate, but I can't find the original ticket.

**Comment by generalmanager** [comment] 2016-01-16 17:22
Maybe not an exact dupe of this, but at least related: https://github.com/syncthing/syncthing/issues/1329

**Comment by shodanshok** [comment] 2016-01-22 16:49
If this got implemented/merged, can it be coded as optional? In many cases, xattrs / EAs propagation are not needed.

**Comment by AudriusButkevicius** [comment] 2016-01-22 17:00
I think it will work based on include/exclude lists.

**Comment by bouillon** [comment] 2016-01-31 20:46
I'm KDE user. It's very important feature. I vote for it. Without I only can just play with syncthing without serios use because i'm going lose information.BtSync help currently out but OP Syncthing would be my favorit after the freature is implemented. I think this will be important also for OSx Users.

**Closed** 2022-09-14 07:50 UTC
Labels: enhancement
