### ISSUE TITLE
Script to run before and after syncing

### ISSUE THREAD

**Issue by majkinetor** [syncthing/syncthing#8121] opened 2022-01-17 15:15 UTC
I want to synchronize database of application running all the time on 2 machines. Syncthing can't do that on Windows since file is locked while the app runs.

This can be done by allowing custom script to run before and after synchronization: before sync, I will close/kill the app and after it, I will start it again.

**Comment by calmh** [comment] 2022-01-17 16:08
For a change to be detected Syncthing must be able to scan the file, which I suppose it can't if it's a locked database. Running a script to shut down your application on every scan sounds painful. Otherwise, I think this is a duplicate of the hooks issue...

**Comment by calmh** [comment] 2022-01-17 16:08
Duplicate of #5601

**Closed by calmh** 2022-01-17 16:08 UTC
Labels: enhancement, needs-triage

**Comment by majkinetor** [comment] 2022-01-17 20:28
Thanks for the duplicate info, didnt find it.

> For a change to be detected Syncthing must be able to scan the file, which I suppose it can't if it's a locked database. Running a script to shut down your application on every scan sounds painful. Otherwise, I think this is a duplicate of the hooks issue...

It should be used only for remote syncing, not other way around. The problem of locally detecting changes is solvable via shadowcopy.
